### ISSUE TITLE
Publishing silently fails and closes PR when repo has required reviews enabled

### ISSUE THREAD

**Issue by verythorough** [netlify/netlify-cms#1019]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
If the publish branch is a [protected branch](https://help.github.com/articles/about-protected-branches/) on GitHub, with [required reviews](https://help.github.com/articles/enabling-required-reviews-for-pull-requests/) enabled, clicking the publish button in the CMS will silently fail, close the PR, and delete the branch, unless the user has the ability to [dismiss the review requirement](https://help.github.com/articles/dismissing-a-pull-request-review/).

The netlify-cms repo happens to be a repo that works like this. Required reviews are enabled, but admin users (not write-permitted users) can override and merge without review. The config for netlifycms.org/admin uses the github backend, so users log in with their own GitHub accounts.

If a write-only collaborator (like @tech4him1, who took the screenshot below) tries to publish a change, GitHub sends the following response:
![capture](https://user-images.githubusercontent.com/6111186/35021873-d0cf8f54-fae7-11e7-84be-5f61798ee985.JPG)
The CMS ignores the response, assumes success, and deletes the branch and closes the PR.

If a repo admin (like me; I took the next screenshot) tries to publish, everything works as normal:
![screen shot 2018-01-16 at 5 22 52 pm](https://user-images.githubusercontent.com/6111186/35022034-9f7b7674-fae8-11e7-92df-0df15d5fb74d.png)

**- What is the expected behavior?**
When branch protections are in place and the user (or git-gateway user token) doesn't have permission to override them, the CMS should leave the PR and branch as they are, and display a relevant error message.

**- Please link or paste your `config.yml` below if applicable.**
See https://github.com/netlify/netlify-cms/blob/master/website/site/static/admin/config.yml 😉

**Comment by tech4him1** [comment]
Screenshot showing request methods and response codes:
![cms failure](https://user-images.githubusercontent.com/20345941/35022170-c54478e8-faf1-11e7-9ffc-81939d477478.JPG)
