### ISSUE TITLE
Editorial workflow metadata is branch-agnostic

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#1024]
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

If an editorial workflow entry in the metadata does not exist, the workflow won't load. This can happen, for example, if a new collection type is being tested in a separate branch and has unpublished entries that do not exist in the main branch. When attempting to load the editorial workflow in the main branch in this case, Netlify CMS will see the metadata for the other branch's unpublished entries and try to load them (and hang when they're not found).

The root issue is that metadata is not connected to a branch, but also that the editorial workflow stops working if entries aren't found.

**- What is the expected behavior?**

Workflow should load

**- If the current behavior is a bug, please provide the steps to reproduce.**

* Use a basic test Netlify CMS instance, the only requirement is that it uses editorial workflow
* Create a new branch from master
* On the new branch, update the CMS config with a new collection type
* Create an entry in the new collection, but leave it unpublished
* Move back to master and try to load the editorial workflow in the CMS

**- Please mention your CMS, node.js, and operating system version.**

CMS 1.0.3

**Comment by erezrokah** [comment]
Closing as stale. We don't save any metadata anymore, just use PR labels and infer the rest of the information
