### ISSUE TITLE
Unsaved changes indicator styling

### ISSUE THREAD

**Issue by ziburski** [netlify/netlify-cms#1031]
In the editor, the indicator that says "Unsaved changes" or "Changes saved" in the top left is not a button. Therefore, it should be styled differently from buttons.

Right now:
![old](https://user-images.githubusercontent.com/1299080/35193419-6446ac46-fea2-11e7-9767-7e75f390c523.png)

Proposed Change:
![new](https://user-images.githubusercontent.com/1299080/35193421-68b8e488-fea2-11e7-8988-5624d9a1c338.png)

Thoughts? Are there any other instances of wannabe buttons?

Also, I’m a little confused by how the indicator works. When are my changes saved? How can I save my changes? Does saved equal published in this case? If so, we could also discuss making the wording consistent across the CMS.

**Comment by erquhart** [comment]
That's a really good point, and I really like the proposed style.

Regarding saved change status, it makes more sense in the editorial workflow, which has a save button next to the status indicator. In the simple workflow, save and publish are the same action. We need to iterate on this whole toolbar anyway, but this specific issue is especially pertinent for the simple workflow, agreed.
