### ISSUE TITLE
NetlifyCMS.org: Widget docs duplicated in search.

### ISSUE THREAD

**Issue by tech4him1** [netlify/netlify-cms#1034]
Our Algolia search on the website is duplicating entries for the widget docs.
For example, for the `boolean` widget we get `/docs/widgets/boolean/#boolean` and `/docs/widgets/#boolean`. This is due to how we set up https://github.com/netlify/netlify-cms/pull/866.

@verythorough @erquhart @Benaiah I'm guessing we could prevent Algolia from indexing/listing the files under `/docs/widgets/` in search, only link to the index of it directly.

**Comment by erquhart** [comment]
Interesting, I've noticed this on netlify.com too

**Comment by verythorough** [comment]
Widget docs no longer have their own page, so search is no longer showing duplicates. Closing as fixed!
