### ISSUE TITLE
Warn on duplicate collection, file, and field names in config

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#1035]
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

Config keys that are assumed unique are not validated for uniqueness, so unpredictable failures take place when multiple same-named keys exist where they shouldn't.

**- What is the expected behavior?**

If keys that must be unique are not, an error message should be generated and Netlify CMS should not load.

**Comment by r1b** [comment]
It would be nice to have widget validation `unique` similar to `pattern` that validates field uniqueness in a collection

**Comment by erquhart** [comment]
@r1b totally agree - mind opening a separate issue for that?
