### ISSUE TITLE
Mistake in docs re: setting up 'relation' widget

### ISSUE THREAD

**Issue by sumeetjain** [netlify/netlify-cms#1042]
**- Do you want to request a *feature* or report a *bug*?**  
BUG

**- What is the current behavior?**  
Docs mislead with regard to setting up a relation widget.

**- If the current behavior is a bug, please provide the steps to reproduce.**  
Go to https://www.netlifycms.org/docs/widgets/#relation and locate this information:

![](https://cl.ly/p3La/Screen%20Shot%202018-01-24%20at%208.53.55%20AM.png)

**- What is the expected behavior?**  
Where it says `searchFields: "[name, twitterHandle]"`, it should instead say `searchFields: ["name", "twitterHandle"]`.

**Comment by tech4him1** [comment]
Thanks for reporting @sumeetjain, feel free to submit a PR to update that file (https://github.com/netlify/netlify-cms/blob/master/website/site/content/docs/widgets.md).
