### ISSUE TITLE
Adding the ability to have multiple selections on the select widget.

### ISSUE THREAD

**Issue by elvisguillen** [netlify/netlify-cms#1050]
**- Do you want to request a *feature* or report a *bug*?**

This is a feature request. 

**- What is the current behavior?**

Currently the select widget allows for the selection of a single string value with a dropdown menu.

**- What is the expected behavior?**

Would love to have the option to select multiple strings from an array through a radio selection menu. This functionality would be similar to Wordpress' current category selection menu. It'd be really helpful for posts that can be organized under multiple predefined categories.

The lists widget currently allows for comma separated values but need these values to be predefined.

**Comment by erquhart** [comment]
There's a multi-select in the works in #922.

**Comment by alexandernanberg** [comment]
@erquhart I'd be willing to work on this! Do we want a complete new widget for this or just an option on the current select?

**Comment by erquhart** [comment]
Awesome! Current select was the plan. Just merged a PR to start using the react-select library, so that will help 👍🏼

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
