### ISSUE TITLE
Relation widget is not accepting a List as valueField

### ISSUE THREAD

**Issue by prabu-ramaraj** [netlify/netlify-cms#1052]
**- Do you want to request a *feature* or report a *bug*?**
Bug
**- What is the current behavior?**
Relation widget is not accepting a List field as valueField
**- If the current behavior is a bug, please provide the steps to reproduce.**
Say for example we have this setup as Relation field.
`{label: "Features", name: "features", widget: "relation", collection: "pages", searchFields: ["title"], valueField: "features"} `
Here the "features" valuefield is a List type
 `{label: Features, name: features, widget: list, default: ["super", "very super"]}`
**- What is the expected behavior?**
It should add the values in the list to the current collection

**- Please mention your CMS, node.js, and operating system version.**

**- Please link or paste your `config.yml` below if applicable.**
https://github.com/prabu-ramaraj/one-click-hugo-cms/blob/master/site/static/admin/config.yml

**Comment by d4rekanguok** [comment]
This feature is now supported in the latest version of NetlifyCMS! See #3754
