### ISSUE TITLE
Community page: 'Next development planning session' widget is partly hidden

### ISSUE THREAD

**Issue by thomaskuntzz** [netlify/netlify-cms#1055]
On the [community page](https://www.netlifycms.org/community/), the widget showing the date of the next development planning looks cut off, as you can see in the GIF below:

![screenshot](https://user-images.githubusercontent.com/16361470/35472046-5d26c714-0368-11e8-8c07-8af02757b0d7.gif)

I'm on Safari 11.0.2

Maybe this is the expected behavior, but it looks kinda weird, I feel like there is information that is hidden below the screen. I would suggest to reduce its height so that it fits in the screen and we can see its borders.

**Comment by tech4him1** [comment]
I can confirm this -- on screens that are vertically small, the box gets cut off.
