### ISSUE TITLE
Change direction of arrow on collapsed editor widget

### ISSUE THREAD

**Issue by Doocey** [netlify/netlify-cms#1057]
**- Do you want to request a *feature* or report a *bug*?**

Requesting a small UI change on ListItemTopBar.js.

**- What is the current behavior?**

Direction of arrow on collapsed editor widget, for both images and YouTube embeds is set to _up_ (^) as per the following screenshot:

![Current collapsed arrow behaviour](https://preview.ibb.co/nHWEgw/default_behaviour.png)

**- Preferred behaviour of collapsed widget**

Preferably the default orientation for a collapsed icon is right-facing, rather than an upward arrow.

![Preferred Arrow Icon Behaviour](https://preview.ibb.co/f02gTb/preferred_behaviour.png)

This a relatively straight-forward fix, and I believe it makes things more logical from a UI/UX perspective. The right-facing arrow on collapsed state **clearly** signals that there is expandable content.

**Comment by tech4him1** [comment]
Closes by #1059.
