### ISSUE TITLE
Selecting multiple entries via the 'relation' widget

### ISSUE THREAD

**Issue by sumeetjain** [netlify/netlify-cms#1061]
**- Do you want to request a *feature* or report a *bug*?**

FEATURE

It would be nice if the 'relation' widget could select multiple entries from the related collection.

E.g. in the case of `Post` and `Tag` (assume these are collections), a traditional blog setup would have a many-to-many relationship between these collections' entries. Furthermore, `Tags` are usually user-addable, which means a basic dropdown list doesn't suffice (since it's populated only by a static list of tags).

Even outside the context of many-to-many relationships, being able to select multiple entries through the 'relation' widget would add value for one-to-many relationships. Any time you need to bulk-assign many children to a parent, the easiest UX would be to open the parent for editing and quickly add many of the children via the 'relation' widget.

All of this is essentially suggesting the addition of an interface that allows multiple entries to populate the value of a 'relation' widget field.

**Comment by erquhart** [comment]
This would be a great improvement, thanks for raising it @sumeetjain.

**Comment by moonmeister** [comment]
Would this be extending the "relation" widget or adding a "relations" widget? I could see use cases for only wanting 1 or wanting many. What if we leave it a single widget but add a "limit" config that takes a number. Then the single widget could support 1 to infinity(theoretically). Thoughts?

**Comment by moonmeister** [comment]
Looks like there's already a react [library](https://github.com/olahol/react-tagsinput) for this...and it looks to work with the existing `react-autosuggest` that's already being used.

**Comment by tech4him1** [comment]
Related to #391 (and somewhat to #1050).

**Comment by moonmeister** [comment]
Working on implementing this. Got a non working version where I'm trying to implement auto complete. I think I'll be giving up on this path...especially if this is just going to end up extending the existing `relation` widget...if it's going to be an additional widget then the nesting works...
https://github.com/moonmeister/netlify-cms/commit/c89c73189b9c1500dab8cbbff0d370290c509857

If you want to see a working version without autocomplete checkout:
https://github.com/moonmeister/netlify-cms/commit/c89c73189b9c1500dab8cbbff0d370290c509857

I've added it to the top of the `kitchen sink`.

**Comment by ciokan** [comment]
Hi @moonmeister, 

Whats the status of this issue?

**Comment by moonmeister** [comment]
@ciokan yes, I'm back from 4.5 months of willderness, so I can actually work on this again. I still want it, you interested in helping?

**Comment by ciokan** [comment]
I'm not, at all, familiar with the source code but I'll be happy to take a shot at it. Is this where you left off: https://github.com/moonmeister/netlify-cms/commit/c89c73189b9c1500dab8cbbff0d370290c509857?

**Comment by ciokan** [comment]
IMHO the existing relation widget should be extended with a boolean field such as `allowMultiple` near `valueField` and other stuff. It's still a relation after all. What do you think?

**Comment by andreimoment** [comment]
@moonmeister thank you for taking this on. It would be very useful.

I'd also consider "relation-multiple" for a name as it needs no explanation.
