### ISSUE TITLE
Option To Disable "Add New Item" In List Widgets.

### ISSUE THREAD

**Issue by alteducation** [netlify/netlify-cms#1065]
**- Do you want to request a *feature* or report a *bug*?**
      Feature

**- What is the current behavior?**
     I want the user to be able to edit array items without adding additional new ones. Currently the user can add new items 
**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**
   The 'Add New Item' Button is removed in selected arrays, & the user can only edit the current items

**- Please mention your CMS, node.js, and operating system version.**

CMS Ver 1.1.0
 **- Please link or paste your `config.yml` below if applicable.**

**Comment by erquhart** [comment]
This makes sense, agreed.

**Comment by gazebosx3** [comment]
Hi! I'd like to take this issue, if that's ok with y'all.

**Comment by tech4him1** [comment]
@gazebosx3 Sounds great, let us know if you have any questions!

**Comment by gazebosx3** [comment]
Hey, I'm a bit confused about the requirements of this issue. Is "Array" referring to the array in the Select Widget? If so, I don't see where, in the CMS, users can add elements to a select array...

<img width="850" alt="screen shot 2018-02-07 at 12 44 00 pm" src="https://user-images.githubusercontent.com/27162255/35932047-9f6b7472-0c04-11e8-98a9-298a698c4dc1.png">

**Comment by tech4him1** [comment]
![capture](https://user-images.githubusercontent.com/20345941/35944620-4b319010-0c1a-11e8-8277-61385aa75b5b.JPG)
The button that we want to be optional is on the "List" widget, sorry that wasn't clarified.

**Comment by erquhart** [comment]
@gazebosx3 feel free to reach out in [Gitter](https://gitter.im/netlify/netlifycms) if you need help in realtime.
