### ISSUE TITLE
How to update to new version?

### ISSUE THREAD

**Issue by ragasirtahk** [netlify/netlify-cms#1073]
**- Do you want to request a *feature* or report a *bug*?**

Feature

**- What is the current behavior?**

There is no documentation explaining how to update to a newer version of Netlify CMS.

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

A documentation should be created explaining how to update to a newer version of Netlify CMS.

**- Please mention your CMS, node.js, and operating system version.**

**- Please link or paste your `config.yml` below if applicable.**

**Comment by ragasirtahk** [comment]
I am willing to create a proper documentation for this if I am provided a basic overview of the procedure.

**Comment by tech4him1** [comment]
If you are using a package manager like Yarn or NPM, you will use their standard procedure to update. This is how both the Hugo and Gatsby starters are set up.

If you are using the CMS through a CDN like Unpkg, then that depends on the version tag you are using.
- (Recommended) If you use `^1.0.0`, the CMS will do all updates *except major versions* automatically.
  - It will upgrade to `1.0.1`, `1.1.0`, `1.1.2`.
  - It will not upgrade to `2.0.0` or higher.
  - It will not upgrade to beta versions.
- If you use `~1.0.0`, the CMS will do only patch updates automatically.
  - It will upgrade `1.0.1`, `1.0.2`.
  - It will not upgrade to `1.1.0` or higher.
  - It will not upgrade beta versions.
