### ISSUE TITLE
Docs: Menu should not overlap footer.

### ISSUE THREAD

**Issue by ragasirtahk** [netlify/netlify-cms#1077]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

The long pages at https://www.netlifycms.org/docs/ are not resposive. View the GIF below.

**- If the current behavior is a bug, please provide the steps to reproduce.**

![website issue](https://user-images.githubusercontent.com/26816046/35793021-e69c447e-0a75-11e8-8d5d-6a543bcaffd5.gif)

**- What is the expected behavior?**

The 'links sidebar' should not overlap the footer.

**- Please mention your CMS, node.js, and operating system version.**

**- Please link or paste your `config.yml` below if applicable.**

**Comment by ragasirtahk** [comment]
Tested on Firefox Quantum (x64) and Chromium (x64) on Windows 10 (x64).

**Comment by xifengjin88** [comment]
Hi, if this issue was not taken, may I work on this issue? Thanks!

**Comment by tech4him1** [comment]
@xifengjin88 It is available, thank you!

**Comment by xifengjin88** [comment]
@tech4him1 you are welcome!! happy to help!!

**Comment by xifengjin88** [comment]
Hi netlify community,
 I think I am gonna be busy for awhile, so I will not be able to work on this issue. if anyone wants to work on this issue, feel free to work on this!!

**Comment by daveyko** [comment]
Hi I would like to work on this issue! Thank you!

**Comment by daveyko** [comment]
@tech4him1  I believe I was able to resolve this issue, however I can't seem to push my branch up (I have linted, rebased, and the test specs pass). I believe this has to do with my permissions. Feedback would be appreciated. Thank you!

**Comment by ragasirtahk** [comment]
@daveyko did you create a pull request?

**Comment by ragasirtahk** [comment]
@daveyko you need to submit a PR for the changes, after that two people will check it and commit it.

**Comment by daveyko** [comment]
@ragasirtahk PR was just made! Thank you for your response!
