### ISSUE TITLE
question: Can I intregation mybb in netlify-cms ?

### ISSUE THREAD

**Issue by BogusCurry** [netlify/netlify-cms#1083]
Hello there ;D
I have a little question, can I intregation the forumscript mybb (mybb.com) in the cms ?

Greetings
Bogus

**Comment by erquhart** [comment]
That'd be a toughie - Netlify CMS is primarily for git-based data. Going to close this, but if you want to discuss further, [Gitter](https://gitter.im/netlify/netlifycms) is the place for questions like this.
