### ISSUE TITLE
Expanding local development options

### ISSUE THREAD

**Issue by andreasremdt** [netlify/netlify-cms#1085]
As discussed in #1082, there might be a confusion about local development in the CMS.

**For reference:**

> Actually I totally forgot about the fact that the CMS is getting its data from GitHub, although I would say that I understand the way these things work. I guess it's because of the typical workflow with systems like Wordpress that I'm used to, where you have your local environment (with data) and once you reach a certain point you push everything onto the live server, including database. It's a different workflow.
>
> I can't speak for other developers, but I myself didn't think about your solution when I encountered the issue - I was sure I messed something up in the config.
>
> The thing I see is that, although the CMS's configuration in the `config.yml` is straight forward and easy, I don't want to add my changes to the Repo without knowing if it works in the CMS. Maybe I made a typo and messed up the config - so I would have to make this quick fix and push my changes before testing again. This seems a bit tedious to me, but maybe there are other solutions? In this specific case I wanted to add a new page to the Pages collection and verify it's working fine before adding / pushing anything to Git or GitHub.

Possible ideas:

* Adding a method besides `git-gateway` or `github` specifically for local development
* Letting the user know in the backend that although the CMS is accessed from a local web server the sources are fetched from the live repo
* Explaining more about development options in the docs. I didn't find anything about this point in the documentation.

(EDIT: fixed formatting)

**Comment by tech4him1** [comment]
There is a local file-system backend in progress at #329 / #786.

cc/ @talves @Benaiah @erquhart

**Comment by erquhart** [comment]
I agree with all of these points.

**Comment by rdebeasi** [comment]
On this week's community call, @erquhart demoed the new external media library feature using a local CMS config - I think it was called something like "dev-test." Is there documentation on this feature somewhere? If the feature exists but is't documented, I'd be happy to put together some docs.

**Comment by tomrutgers** [comment]
```
backend:
    name: test-repo
```

There is no documentation for it currently, but I think it would definitely be good to have some!

**Comment by dantman** [comment]
netfly-cms seems to already have git-gateway and local test-repo handling. While it would be nice to have a full filesystem backed backend to allow previewing the actual site (which I think is what #329 is going for). In the meantime wouldn't be be relatively easy to create a version that does something like git cloning the current repo to a bare repo at a path defined in config and publishing commits there instead of online. Then the same commit flow is used and the user just needs to pull new stuff into their actual repo.

**Comment by talves** [comment]
@dantman You would have to create a backend for what you are talking about and an api to run the git commands.

I have a file-system backend (beta still), but you can see a working example using the latest version [here in this create-react-app example](https://github.com/ADARTA/netlify-cms-react-example)

**Comment by erquhart** [comment]
Closing in favor of #2335.
