### ISSUE TITLE
Make a pure "Hugo Site Starter" instead of the current "Victor Hugo" based site starter

### ISSUE THREAD

**Issue by ragasirtahk** [netlify/netlify-cms#1091]
The current "Hugo Site Starter" on https://www.netlifycms.org/docs/start-with-a-template/ uses https://github.com/netlify-templates/one-click-hugo-cms .

The one click Hugo cms repository uses "Victor Hugo" and Netlify CMS which has a bit different structure from the original "Hugo" structure.

I think the **title should be changed to "Victor Hugo Site Starter"** and a **new template should be created for "Hugo Site Starter"**. This new template will only use pure "Hugo" and "Netlify CMS".

What are your views on it?

**Comment by erquhart** [comment]
Victor Hugo was created to provide a Hugo setup with front end tooling (babel, etc) - what's the advantage of removing that?

**Comment by ragasirtahk** [comment]
I am suggesting that it should be made clear on that page that the starter is based on Victor Hugo

**Comment by ragasirtahk** [comment]
Also, I think there should be an option for those who want only Hugo instead of Victor Hugo Site Starter

**Comment by tech4him1** [comment]
@erquhart I do agree that understanding how that template works is a little confusing at first -- especially while trying to understand the CMS as well.

**Comment by talves** [comment]
I am wondering if it would be a good thing to create the generic one click Hugo starter to see a simple setup of taking an existing simple Hugo theme example to include the CMS.

Might be a good opportunity to mix in the `file-system` backend also. Now all I would need is time.

**Comment by ragasirtahk** [comment]
@talves I can create the generic one click Hugo starter with an existing Hugo template. And you can mix in the file-system backend. How does it sound?

**Comment by talves** [comment]
@ragasirtahk I will do what I can find time for. Accepted your invite on your repo.

**Comment by ragasirtahk** [comment]
I am no longer creating a template for plain 'Hugo'. Current things seem fine.
