### ISSUE TITLE
Sorting collection list

### ISSUE THREAD

**Issue by george-oakling** [netlify/netlify-cms#1099]
We should definitely have the option of using some sort of... sorting :) of particular collections. From my point of view, there should be an configuration option for sorting, which will be connected to field. So if we know the type of "sorted by" field (eg. number, date, datetime), we can sort the items afterwards, like this:
https://github.com/george-oakling/netlify-cms/commit/3c69c51c52c5fe51f46cae5e7cd8774d1000982a

**Comment by erquhart** [comment]
Totally agree, this has been long awaited. If you're interested in taking a stab at it, comment there and we can discuss further.
