### ISSUE TITLE
Replace assets paths in README

### ISSUE THREAD

**Issue by xuopled** [netlify/netlify-cms#111]
Hello, 

I followed the `Installing` section of your `README` but assets in your default template don't exist : 
- //cms.netlify.com/assets/main.js
- //cms.netlify.com/assets/main.css

I found somewhere else these files : 
- //cms.netlify.com/assets/cms.js
- //cms.netlify.com/assets/vendor.js
- //cms.netlify.com/assets/cms.css

Are they the good ones ?

**Comment by DavidWells** [comment]
Same problem https://github.com/netlify/netlify-cms/issues/118

**Comment by calavera** [comment]
Hi!

I'm sorry, but those links are not up yet, hopefully tomorrow. Until then, you can build it yourself with `npm build`.

**Comment by DavidWells** [comment]
@calavera `npm run build` fails https://github.com/netlify/netlify-cms/blob/master/package.json#L10 

webpack.config.js file doesn't exist.

Anything special I need to do here?

**Comment by okonet** [comment]
It is related to #119 that I was planning to work on very soon. I'll update the issue as well.
