### ISSUE TITLE
Al tratar de entrar nuevo record hace que la p[agina se cierre

### ISSUE THREAD

**Issue by emenaphoto** [netlify/netlify-cms#1111]
**- Do you want to request a *feature* or report a *bug*?**

**- What is the current behavior?**

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Please mention your CMS, node.js, and operating system version.**

**- Please link or paste your `config.yml` below if applicable.**

**Comment by tech4him1** [comment]
@emenaphoto Can you provide steps to reproduce, or a screenshot?

**Comment by erquhart** [comment]
In English: Trying to enter a new record causes the page to close.

@emenaphoto closing for now, please re-open if you have more details.
