### ISSUE TITLE
 On the fly hugo update by git-gateway

### ISSUE THREAD

**Issue by uncledent** [netlify/netlify-cms#1118]
Hello, 

is it possible to regenerate the site after each persisted entry by git-gateway? How could I have the copy of the repository also locally?

I see, that there is a gulp watching /site directory for changes, running hugo afterwards. The problem is, that by git-gateway (apparently) there is no local copy of the repository, so it is not being triggered. 

So I have to wait for the automatic deployment, which is bad for the purpose of my app, as I need immediate result. 

Thank you in advance!

**Comment by erquhart** [comment]
You'd have to run `git pull` each time you save a change.
