### ISSUE TITLE
Date widget in list returning Datetime instead of Date

### ISSUE THREAD

**Issue by thebetternewt** [netlify/netlify-cms#1119]
**- Do you want to request a *feature* or report a *bug*?**

**- What is the current behavior?**

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Please mention your CMS, node.js, and operating system version.**

**- Please link or paste your `config.yml` below if applicable.**

I'm using a date widget in a list, but noticed it was returning a datetime stamp instead of a date formatted "YYYY-MM-DD" as described in the docs ([date widget](https://www.netlifycms.org/docs/widgets/#date)). My json file after creating dates from within the CMS:

```
{
"blackout_dates": [
{
"note": "Vacation",
"start_date": "2018-02-19T06:00:00.000Z",
"end_date": "2018-02-23T18:50:33.987Z"
}
]
}
```

config file: [config.yml](https://github.com/thebetternewt/loveleerolls_victor_hugo/blob/master/site/static/admin/config.yml)

For now I have just set a "format" option with the value "YYYY-MM-DD" to enforce the expected output.

**Comment by erquhart** [comment]
Yep we're definitely not setting that default format anywhere in the codebase. This applies to both the Date and DateTime widgets.

**Comment by erquhart** [comment]
Actually we _are_ setting the default as what you're seeing, a full date *and* time ISO8601, which is correct for the DateTime widget only. Opening a PR to fix default for the Date widget.

**Comment by thebetternewt** [comment]
Thanks guys!
