### ISSUE TITLE
'followed quick start guide/steps..', but i cannot access <site/admin>

### ISSUE THREAD

**Issue by miqui** [netlify/netlify-cms#1120]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

**- Do you want to request a *feature* or report a *bug*?**
report a bug 
**- What is the current behavior?**
when i try to access:
https://miqui-me.netlify.com/admin/#/
I get a "not found" message

**- If the current behavior is a bug, please provide the steps to reproduce.**
follow quick start guide to publish a new site, in the netlify site configure Oauth app for the new published site, went to: https://miqui-me.netlify.com/admin/#/

..get a not found message...

**- What is the expected behavior?**
I expected to be able to use netlify CMS tool to edit the site.

**- Please link or paste your `config.yml` below if applicable.**

https://github.com/miqui/miqui.me/blob/master/site/config.toml

**Comment by erquhart** [comment]
You'll need to put your own repository info in the config.yml: https://github.com/miqui/miqui.me/blob/master/site/static/admin/config.yml

**Comment by ragasirtahk** [comment]
Seems fixed now :)

**Comment by MarinKacaj** [comment]
Unfortunately, I have the same problem:
[My repo](https://github.com/MarinKacaj/tanci-craft-dev)
[My config.yml](https://github.com/MarinKacaj/tanci-craft-dev/blob/netlify/static/admin/config.yml)
[My Netlify site](https://tanci-craft-dev.netlify.com)
[My Netlify site admin panel](https://tanci-craft-dev.netlify.com/admin/) - won't even show up - 404 instead

**Comment by tomrutgers** [comment]
Your admin panel shows up just fine here
