### ISSUE TITLE
Admin UI: Remove Container's width constraint

### ISSUE THREAD

**Issue by peduarte** [netlify/netlify-cms#1122]
Hello 👋 

**- Do you want to request a *feature* or report a *bug*?**
*Feature* (...more like a UI Enhancement)

**- What is the current behavior?**
The Admin UI currently sets a `max-width` of `1600px` to the Entry Editor Container (`nc-entryEditor-container). 

**- What is the expected behavior?**
This is behaving as per the expected behaviour, however, I'd like to propose removing this width restriction and allow the container to be fluid.

One of the (many) killer features of Netlify CMS is the custom preview. I imagine that most people would want to make use of this functionality and display a preview of what they're entering in situ (a new page, blog post, etc...).

The current container width restriction limits how wide your preview can be. 

For my current use case, I'm creating a new blog post, and I'm not able to check how it looks in my "wide" breakpoint. 

Please refer to the screen shots below:

---

**Current**
![screenshot 2018-02-20 14 23 56](https://user-images.githubusercontent.com/372831/36429490-becbff26-164a-11e8-9264-90b263088fb7.png)

---

**Proposal**
![screenshot 2018-02-20 14 25 45](https://user-images.githubusercontent.com/372831/36429509-caa60832-164a-11e8-856b-359c5d55aa32.png)

---

If you're open to this idea, please let me know and I'd be happy to contribute.

Thanks!

**Comment by erquhart** [comment]
The idea was that folks would drag the resizable middle bar between the two panes if they wanted to peek at a wider breakpoint. I remember @neutyp discussing this point at length around the 1.0 launch.

The challenge from a design standpoint is that the form fields should only be so wide, and as you see in your proposal, when you spread everything out the control pane is just floating in whitespace.

Maybe a fullscreen button would be worthwhile.

@neutyp @ziburski thoughts?

**Comment by ziburski** [comment]
If we have the space to show both a normal-size editor and a full-width preview, I think it’s reasonable to use that space. Doesn’t have to be fullscreen, but just making that container a bit wider for large screens would help. Why would we make people drag between the two if we can show both?

To be fair, it’s a very different challenge on smaller screens where you might not want to compromise the editor view. I’d still like to see us further explore alternatives to the two-pane approach, like the zooming concept I proposed #409.

**Comment by erquhart** [comment]
It really doesn't make sense to impose the limitation, I agree with just making it wider for the purposes of this issue.

**Comment by austincondiff** [comment]
Any status on this? This needs to happen. Is there any way to add custom css to do this manually in the mean time?

**Comment by erquhart** [comment]
Just hasn't happened because it isn't on fire, and no one has opened a PR.

**Comment by peduarte** [comment]
Jeeeeez, is this still going? 😂 

I can create a PR if people really want this.

👍 for yes

**Comment by erquhart** [comment]
HELP US PEDRO YOU'RE OUR ONLY HOPE

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by t1merickson** [comment]
Verrrry slow reply, but I'm referenced above (changed my username from @neutyp, sorry about the confusion there).    I like Pedro's proposed design. As long as the divider between the edit section (at left) and the preview section (at right) is obvious, and the form fields are constrained in width, it works and looks good to me.   The only change I would make would be to make the divider between said sections the same thickness/width as the thickness of the border on the field inputs (2px).

**Comment by peduarte** [comment]
@erquhart @t1merickson PR here https://github.com/netlify/netlify-cms/pull/2626

- [x] Form fields constrained in width
- [ ] Divider prominence 

Regarding the divider:
- Do you want a `2px` divider only above a certain breakpoint? If so, which one?

**Comment by t1merickson** [comment]
At all times, IMO.  The reason for the change is to make it more obvious the border is dragable.  For example, it's different than the borders in the header/toolbar/navbar.  Those dividers are 1px and not draggable.   Unless I'm forgetting something, I don't see how it would be relative to breakpoint.   The UI already breaks in a bunch of ways at small viewing sizes, especially below 960px width.  We should open another issue to address those issues.  This is when @ziburski's concept could come in handy. At small viewing sizes we can collapse the preview down to a thumbnail as he demonstrated.

**Comment by austincondiff** [comment]
The separator seems to be a separate issue. However, I’d keep it 1px wide with an invisible 8px wide hover/dragable zone. I’d make it a shadow instead of a border so it does not affect layout and make it a transparent gray. When it is hovered over, that 1px border could expand to 8px to give the user some affordance that that area is dragable to resize the panes. When dragging, the opacity would increase making the line more defined. What do y’all think? I can create a PR for this when I return from vacation if this is something we’d like to see. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by peduarte** [comment]
Cool, on here #2626 I've got it as a `2px` width, always. I agree the divider behaviour could potentially be improved, perhaps with some of the ideas from @austincondiff 

But I also agree it seems like a separate issue.
