### ISSUE TITLE
Add possibility to disable Preview panel

### ISSUE THREAD

**Issue by xuopled** [netlify/netlify-cms#113]
Sometimes, The preview panel do not have a real interest because we do not have markdown field. So I could be great to disable it in config file for a collection

**Comment by biilmann** [comment]
I agree - it's a common issue for setting files, configurations, etc. Sometimes it makes sense to use the preview pane to show a customized view of what the setting means and so on, but there's definitively also cases where it's just in the way...

**Comment by cedricdelpoux** [comment]
It's exactly what I was thinking

**Comment by cassiozen** [comment]
Hi @xuopled , I agree this would be great. 

This is definitely in our list, but I don't have time to work on this now. Can you help us?

Every key/value that you set on for a collection will be loaded and the collections reducer will mount the state based on it.

The CMS components are split into container components (the ones which have access to the redux store) and presentational components.

The content editor is made of:
  • The EntryPage container - connects to the Redux store and renders the EntryEditor 
  • The EntryEditor presentational component - responsible for presenting the preview pane and the editor pane (or control pane, as we call).

How this feature can be implemented: Read the config key/value from the store on EntryPage and pass it as props to EntryEditor. Then, on EntryEditor, decide whether to render or not the PreviewPane based on the config value.

**Comment by americool** [comment]
Going to take a look at this today.

**Comment by calavera** [comment]
It would be great if this could have two levels of integration:

1. Disable completely by configuration. For example, I don't want it for my full installation.
2. Disable by user setting. For example, I don't want to see it because my screen is too small for both panels.

**Comment by americool** [comment]
I've got something. May not exactly be how people have envisioned it and certainly needs styling, but I'll submit a PR soon so people can take a look at it.
