### ISSUE TITLE
Allow setting config URL with link element in head

### ISSUE THREAD

**Issue by Benaiah** [netlify/netlify-cms#1132]
**- Do you want to request a *feature* or report a *bug*?**

*feature*

**- What is the current behavior?**

You cannot change the location or format of the `config.yml` - it's [hardcoded to `'config.yml'`](https://github.com/netlify/netlify-cms/blob/b4b584682473924556a41cae10f64f085b0f432b/src/actions/config.js#L92) (relative to the CMS location).

**- What is the expected behavior?**

You should be able to set the config URL by adding a `<link>` element to the `<head>` of the CMS page, as follows:

```html
<link href="CONFIG_URL" type="CONFIG_FORMAT" rel="cms-config-url">
```

For now, we can require the `type` to be `text/yaml` or `application/x-yaml`, and continue to assume YAML format. Eventually, we could allow setting the format by setting the `type` attribute, and infer the format from the URL extension if there is no `type` set.

**Comment by brianlmacdonald** [comment]
Can I give this a shot?

**Comment by Benaiah** [comment]
@brianlmacdonald absolutely, we'd love for somebody to tackle this. It should be a pretty simple fix - the place where it's currently hardcoded is linked in the issue above. If you need any help feel free to ask here or on [the Gitter channel](https://gitter.im/netlify/NetlifyCMS) - thanks for your interest!

**Comment by brianlmacdonald** [comment]
Cool, I'll take a look at everything and circle back if I have any questions!

**Comment by talves** [comment]
@brianlmacdonald great job on #1146

**Comment by barthc** [comment]
@tomrutgers issue still valid?

**Comment by tomrutgers** [comment]
Closing. Thanks @barthc!
