### ISSUE TITLE
Configure string widget to respect block scalar styles set in yaml frontmatter?

### ISSUE THREAD

**Issue by 01ivr3** [netlify/netlify-cms#1137]
Is it possible to configure the string widget to respect block scalar styles set in yaml frontmatter?

ref: [In YAML, how do I break a string over multiple lines?](https://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines/21699210#21699210)

For example, if I have the following key:value in frontmatter
```
key: |
  here is the string value
  separated onto multiple lines

  with a blank line between the 2nd and 3rd
```
editing this with a string widget in NetlifyCMS will, on publishing, overwrite the pipe `|` block style indicator to  a greater than  `>` or greater than w/ dash `>-`.

**Comment by erquhart** [comment]
Not currently, no. Netlify CMS will however write YAML that's true to the content entered, so you won't be missing newlines that are supposed to be present.

Do you have an example where this is causing a problem?

**Comment by 01ivr3** [comment]
@erquhart apologies for the late reply. I posted this before I realized I could use the markdown widget for fields other than the `body` below front matter content
