### ISSUE TITLE
Netlify Api - Authorized no login

### ISSUE THREAD

**Issue by SureDroid** [netlify/netlify-cms#1147]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When logging in wherever (netlify site, netlifycms site, etc), the api returns authorized in a new tab but does not actually login (login as in auto-delete the app netlify page and redirect url to netlify home admin, etc) after connecting to github for mobile (android). 

**Steps to reproduce:**
Login netlify on mobile browser (android)

**What is the expected behavior?**
Close netlify api tab and redirect to whatever page.

**Tested Apps:**
Chrome version 64.0.3282.137
Samsung internet version 6.4.10.5

**Phone version:**
Samsung S8 - SM-G950U1

[Screenshot](https://imgur.com/a/kFcbp) of authorized netlify api page.

**Comment by tech4him1** [comment]
@SureDroid Can you share a link to your site?

Likely a duplicate of https://github.com/netlify/netlify-cms/issues/770.

**Comment by tech4him1** [comment]
@SureDroid Can you share a link to your site and/or repo so that we can try to reproduce?

**Comment by SureDroid** [comment]
This does not involve custom domains at all. You can view it logging in to netlify. https://app.netlify.com
Also bug fixed? Been having this issue for the past two days, came back now and it's working w/ direct login. Something has changed. Anyway, it now works. So if something changed, thanks.

**Comment by tech4him1** [comment]
@SureDroid Glad it's working now! This repo is specifically for Netlify CMS, not Netlify.com, so you would need to contact their support anyway.
