### ISSUE TITLE
"Cannot read property 'name' of undefined" when logging in

### ISSUE THREAD

**Issue by PizzaFox** [netlify/netlify-cms#1148]
**- Do you want to request a *feature* or report a *bug*?**
Bug
**- What is the current behavior?**
Every login displays the following warning popup: !![Error warning](https://i.imgur.com/0ivazcO.png)
`Cannot read property 'name' of undefined`
**- If the current behavior is a bug, please provide the steps to reproduce.**

- Log out
- Log in

**- What is the expected behavior?**
Logins do not display any errors or warnings

**- Please mention your CMS, node.js, and operating system version.**
Running off of Netlify. CMS version `^1.0.0`.

**Comment by tech4him1** [comment]
@PizzaFox Can you link your repo (and site if possible)?

**Comment by PizzaFox** [comment]
[Live website](https://sjhsboosterclub.netlify.com/)
[Repository](https://github.com/PizzaFox/sjhs-booster-club)

**Comment by PizzaFox** [comment]
Using `localStorage.clear()` in the web inspector panel resolved this issue.
