### ISSUE TITLE
Raw Edit File

### ISSUE THREAD

**Issue by SureDroid** [netlify/netlify-cms#1152]
**- Do you want to request a *feature* or report a *bug*?**
Feature/Bug?

I am new to netlify cms. I have spent about four hours trying to figure out a way to add a way to raw edit a file in collections. (No markdown or anything, just direct edit and save). Is there any way possible, and if not could that be added? 

Thank You.

**Comment by tech4him1** [comment]
This config should work:
```
collections:
  - name: "settings"
    label: "Settings"
    files:
      - name: "raw"
        label: "Raw File"
        file: "_data/test.txt"
        fields:
          - {label: "Content", name: "body", widget: "text"}
```

**Comment by tech4him1** [comment]
Just trying to test and it seems like the CMS loads and saves the file as empty every time. Is this what you were running into @SureDroid? If so, there must be a bug there.

**Comment by SureDroid** [comment]
The text widget says that it takes multiple lines and saves them as string, is that one line? I thought that text saves it as only one line. What I am trying to do is be able to edit the config.toml for my site (victor hugo). I'll check if that works and come back,

**Comment by tech4him1** [comment]
> The text widget docs says that it takes multiple lines and saves them as string, is that one line? I thought that text saves it as only one line. What I am trying to do is be able to edit the config.toml for my site (victor hugo). I'll check if that works and come back.

Nope, it should save whatever you type in (multiple lines).

**Comment by tech4him1** [comment]
> Coming back at my previous comment, does not work, comes back with empty text editor and blank preview.

That's what I was seeing as well. I'll try to look into this hopefully later today or tomorrow.

**Comment by tech4him1** [comment]
Relevant code line:
https://github.com/netlify/netlify-cms/blob/7caa15627744c4c01efdde73978b22b3cf72eea2/src/formats/formats.js#L71

**Comment by tech4him1** [comment]
@SureDroid As a workaround for now, you should be able to set `format: frontmatter` on the collection.

Example:
```yaml


collections: # A list of collections the CMS should be able to edit
  - label: "Settings"
    name: "settings"
    format: frontmatter  #<--------------------------- Workaround
    files:
      - label: "Config"
        name: "config"
        file: "site/config.toml"
        fields:
          - {label: "Editor", name: "body", widget: "text"}
```

**Comment by SureDroid** [comment]
This does not work. First thing I saw when I (tried using formatmatter)[https://github.com/SureDroid/hugobuild/commit/708ddbf1f99cff2c6e1d9c7ededc58743ae45e6c] was that the page was that the text and preview was empty. I pasted in my current config and I took a [screenshot](https://imgur.com/a/BeeX4). Looking from it, I immediately saw that it was taken as a one line and the text was being wrapped. Publishing the file, my config.toml got (overwrited with a one line string)[https://github.com/SureDroid/hugobuild/commit/a568db] which failed generation in netlify auto-deploy. I also (tried using toml)[https://github.com/SureDroid/hugobuild/commit/06d19c9] as my format but that did not work aswell w/ a similar result. I'll try a txt file and see if it works and come back.

**Comment by SureDroid** [comment]
I tested editing a raw txt file (suredroid@d114a43169d45d4c0b3c15d1841caa815eee8774).

**Comment by tech4him1** [comment]
>  I also tried using toml as my format but that did not work aswell w/ a similar result.

TOML is a valid format, and it will work for this -- however, you have to define each line as a field, instead of just one main `body` field.

**Comment by tech4him1** [comment]
@SureDroid 

> The **first** one I am sure that you are aware of, is that the preview is single line, which makes the preview section more useless than it already is for editing raw files.

You can set this on the collection to turn the preview off:
```yaml
editor:
  preview: false
```

> The **second** strange behavior which you may not know of is after publishing, going out of the page and back into the page, it goes blank.

My bad, you need to set `yaml-frontmatter` or `toml-frontmatter` instead of just `frontmatter`. It actually doesn't matter whether you use `yaml-frontmatter` or `toml-frontmatter`, since you are using a raw file instead of markdown. (I did test this with your config, so it should work.)

**Comment by tech4him1** [comment]
@SureDroid Did the last comment work for you?

**Comment by SureDroid** [comment]
Sorry for no update. Was going ask if a way to fully raw edit config toml files would be added, but I guess I should get used to creating a box for every single line. Thanks for the help. Earlier you mentioned a bug and said that this was a workaround, so I didn't know if I should close this issue or not if the bug still exists. Anyway, all my problems are fixed. Thanks for your time!

**Comment by tech4him1** [comment]
Thank you! I think this is no longer a bug, I was just misunderstanding your original request :).

> Was going ask if a way to fully raw edit config toml files would be added, but I guess I should get used to creating a box for every single line.

Are you thinking of that as a way to have the CMS infer the fields from the file that already exists? If so, that is a very interesting idea, it would be awesome if you could open a new issue as a feature request.

**Comment by SureDroid** [comment]
Alright, will do!

**Comment by erquhart** [comment]
> where the collection could reason about a raw toml file, break out a list of items, and be able to append / edit / delete to the toml list intelligently in a UI similar to that of normal blog posts or pages

Can you explain a bit more what you mean here?

**Comment by nickiescutia** [comment]
Sure; my use case is a basic portfolio site that i have control over. 

This particular theme im using has a ‘recent works’ section that’s a list of pictures. As a graphic designer, im not primarily interested in the blogs or pages that the cms can edit and post, but rather those images.

I pump out new art daily, and would love a way to just pop open the cms and not only upload new media i create, but also add that to my deployed site without dropping down into a terminal with git or editing config files directly (im not really a programmer, my husband set most of this up for me).

Right now the only way to do that (with this particular theme), is to edit the raw toml file, as that is where this theme lists out its ‘works’ sections.

Does that make sense? There mogjt be another theme that uses a collection to do that, but usually the thumbnail and picture galleries and setup in a toml file.

**Comment by nickiescutia** [comment]
Here’s a direct link to the part of the themes instructions that kind of lay out the problem - https://github.com/digitalcraftsman/hugo-strata-theme/blob/master/README.md#build-up-your-portfolio

Since the toml file controls the section I’m interested in, I have to have that raw file edit, but it would be much nicer if the cms had a way of displaying the portfolio section on a similar way as other collections (blog posts/pages).

**Comment by SureDroid** [comment]
I think what you said above is what I have been waiting for and wanted. Thanks for adding it. Will test it out when I get the chance.

**Comment by TonioGela** [comment]
> @nickiescutia You can currently edit a single file just like any other post (see [`files`-type collections in the docs](https://www.netlifycms.org/docs/collection-types/#file-collections)). The only limitation currently is that you must define all fields in the file (including `baseURL`, etc.).

What about TOML files with tables like 
```
[[section]]
foo = "bar"
```
Are they mappable? Maybe using lists?

**Comment by tomrutgers** [comment]
A TOML table is an array of objects basically, so I think the list widget with a `fields` property should work. Try this:

```
- name: section
  label: Section
  widget: list
  fields: 
    - {name: foo, label: Foo, widget: string}
```

**Comment by barthc** [comment]
@tomrutgers  I think it's should be  `object` instead of `list` :smile:

**Comment by tomrutgers** [comment]
@barthc Correct me if I'm wrong but doesn't

```toml
[[section]]
foo = "bar"
```

translates to the following (in json)?

```json
{
  "section": [
    { "foo": "bar" }
  ]
}
```

https://github.com/toml-lang/toml#array-of-tables

**Comment by barthc** [comment]
Sorry, you are right mistook `[[section]]` for` [section]` :+1:

**Comment by GerryWilko** [comment]
Apologies posting this to such an old issue but I'm struggling to see a resolution to the original issue (title anyway) in here.

Is there any way to do a raw file edit within Netlify CMS? I understand this is kind of against the principle of Netlify CMS to some extent as it should be ideally split up editable fields but it would be ideal to have a fall back to edit a file in RAW should you wish.

In my case I want to be able to raw edit a YAML file is full of configs. These will rarely need to be changed by customers but are regularly updated and added to by our dev team. It feels unnecessary to define fields in Netlify CMS for each one.

@tech4him1 I really like your idea of Netlify CMS doing a best effort parse of a file to see if it can extrapolate fields! 😄

**Comment by erezrokah** [comment]
Hi @GerryWilko would using the [code widget](https://www.netlifycms.org/docs/widgets/#code) satisfy your use case? Not exactly editing a raw file, but you should be able to edit YAML code.

**Comment by erezrokah** [comment]
> Essentially I want to just be able to edit x.yml as a whole not to edit a text field within x.yml even if that text property is YAML itself. Does that make sense?

Yes of course. I wasn't clear with my suggestion which is your second example.

Your request is somehow related to https://github.com/netlify/netlify-cms/issues/531 and I can see it being useful as an opt in configuration to default to raw edit mode if no fields are configured for a file.

How about creating a new issue for it? This one kind of branched out too much
