### ISSUE TITLE
Add custom collection template with react component

### ISSUE THREAD

**Issue by xuopled** [netlify/netlify-cms#116]
It could be great to define a custom template for collections. 

I saw the feature is implemented somewhere because you used it in the `roots-cms-example` : https://github.com/netlify-templates/roots-cms-example/blob/master/admin/index.jade#L25-L55

netlify-cms is developped in `React`. So what do you think about define these collections templates with `React` components ? It could be easy to maintain and reuse in home page for collections lists for example

**Comment by cassiozen** [comment]
Hi @cedricdelpoux - You mean for previewing collections entries when editing? 

If that's the case, we already have it working - take a look here: https://github.com/netlify/netlify-cms#registerpreviewstyle

**Comment by cedricdelpoux** [comment]
Oh yes sorry I missed `regsiterPreviewTemplate`. It exactly what I was looking for.

Is there a way to reuse these preview templates in the collections lists ?

**Comment by cassiozen** [comment]
No, not right now, but it's a good idea to think about. 

I'll close this issue for now, but feel free to reopen if you want to add to the discussion.
