### ISSUE TITLE
Preview pane error

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#1160]
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

When the editor is open an error is generated:

http://facebook.github.io/react/docs/error-decoder.html?invariant=40

This same kind of bug surfaced a while back via `react-frame-component`, and was addressed in https://github.com/ryanseddon/react-frame-component/pull/88. Seems to have resurrected.

**- Please link or paste your `config.yml` below if applicable.**

Observed back to at least CMS 1.3.1

**Comment by erezrokah** [comment]
Closing as stale
