### ISSUE TITLE
Can't access my admin 

### ISSUE THREAD

**Issue by Zinenda** [netlify/netlify-cms#1161]
**- Do you want to request a *feature* or report a *bug*?**

**- What is the current behavior?**

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Please mention your CMS, node.js, and operating system version.**

**- Please link or paste your `config.yml` below if applicable.**

**Comment by tech4him1** [comment]
@Zinenda Please ask on our Gitter channel: https://gitter.im/netlify/NetlifyCMS
