### ISSUE TITLE
Custom preview not rendering until image added

### ISSUE THREAD

**Issue by cmontgomerymt** [netlify/netlify-cms#1163]
**- Do you want to request a *feature* or report a *bug*?**
Bug
**- What is the current behavior?**
when using a custom preview template, the preview is not rendering until an image is added

**- If the current behavior is a bug, please provide the steps to reproduce.**
create and register preview template:

blogpreview.js
```
var blogPreview = createClass({
	render: function() {
		var entry = this.props.entry;
		var title = entry.getIn(['data', 'title']);
	  var thumbnail = entry.getIn(['data', 'thumbnail']);
	  var thumbnailImage = this.props.getAsset(thumbnail);
		var body = entry.getIn(['data', 'body']);
	  return h('div', {},
			h('h1', {"className": "title"}, title),
			h('img', {"className": "thumbnail", src: thumbnailImage.toString()}),
			h('p', {"className": "text"}, body)
	  );
	}
});
  
CMS.registerPreviewTemplate("blog", blogPreview);
```
In this case I am creating the file and linking to it, because I intend to have multiple preview templates and do not want to flood admin/index.html with javascript.

include script
```
<script src="scripts/blogpreview.js"></script>
```
**- What is the expected behavior?**
when using the standard preview template, things like title and body populate as I enter them.

when using the custom template, nothing renders until I add an image

![screen shot 2018-03-08 at 18 32 11](https://user-images.githubusercontent.com/36431314/37145522-6eb3316e-2304-11e8-915d-cd6e15d6b54b.png)

![screen shot 2018-03-08 at 18 32 26](https://user-images.githubusercontent.com/36431314/37145532-73ba7924-2304-11e8-9390-261b6f90e8a2.png)

**- Please mention your CMS, node.js, and operating system version.**

```https://unpkg.com/netlify-cms@^1.0.0/dist/cms.js```
**- Please link or paste your `config.yml` below if applicable.**

**Comment by erquhart** [comment]
`thumbnailImage.toString()` is probably throwing an error and crashing the iframe on every render until `thumbnailImage` has a value. Check the console to confirm. 

If that's the case, just make sure `thumbnailImage` has a value before attempting to use its `toString` method.

**Comment by cmontgomerymt** [comment]
Awesome!
Thank you for the insight. I was too caught up in the element inspector and total forgot to look in the console.

Thanks again!
