### ISSUE TITLE
front matter fields are removed on publish if not set in `collections` ?!?

### ISSUE THREAD

**Issue by 01ivr3** [netlify/netlify-cms#1174]
Do I have it right that any front matter field NOT defined in a collection in config.yml will simply be removed by NetlifyCMS when it publishes any updates to a page's front matter?

**Comment by erquhart** [comment]
Yep, Netlify CMS reads in the values identified in the configuration only, so they're never included in the output. The `hidden` widget exists for fields that you want to keep but do not want to show in the editor.

**Comment by 01ivr3** [comment]
Ahh apologies, I missed this one. The `hidden` widget solves the issue. Thank you!
