### ISSUE TITLE
CMS assets 404

### ISSUE THREAD

**Issue by DavidWells** [netlify/netlify-cms#118]
Looks like the http://cms.netlify.com/assets/main.js and http://cms.netlify.com/assets/main.css from the https://github.com/netlify/netlify-cms#installing are 404 right now

Where can I find the working links?

Thanks =)

Looks like the same issue as https://github.com/netlify/netlify-cms/issues/111

**Comment by calavera** [comment]
I just replied in #111. Closing this since it's a duplicated :raised_hands:
