### ISSUE TITLE
Automatically generate index.html

### ISSUE THREAD

**Issue by okonet** [netlify/netlify-cms#120]
In order to simplify setup for users, we could use https://github.com/ampedandwired/html-webpack-plugin to generate `index.html` automatically.

This would also allow us the long-term caching for assets. See https://medium.com/@okonetchnikov/long-term-caching-of-static-assets-with-webpack-1ecb139adb95 for more info.

**Comment by cassiozen** [comment]
I'll close for now for inactivity. please feel free to reopen if you want to add to the discussion
