### ISSUE TITLE
Dashboard should display all posts from all collections

### ISSUE THREAD

**Issue by okonet** [netlify/netlify-cms#121]
Right now, navigating to the dashboard (http://localhost:8081/admin/#/) will display only posts from the first collection in the list of collections. We should either redirect there or show all posts on this page.

**Comment by calavera** [comment]
I don't think we should display everything, the dashboard should show a summary of what you have and can do. Showing all posts could be very unfriendly if you have lots and lots of articles.

**Comment by okonet** [comment]
Yes, I agree dashboard should not display everything. But in the current implementation, it is even more confusing since it is displaying post from the first category and very is no visual clue to that so one can think he's looking at all posts.

**Comment by cassiozen** [comment]
We will make the dashboard an independent area. Right now, it will contain only the Editorial Workflow card board, but the idea is to grow in the future.
