### ISSUE TITLE
The date on the file is different from the frontmatter

### ISSUE THREAD

**Issue by raulcraveiro** [netlify/netlify-cms#1222]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**- Do you want to request a *feature* or report a *bug*?**

Report a bug

**- What is the current behavior?**

I set the post date to a future date, but when I publish, the file name uses the date that I published, not the date from the frontmatter.

**- If the current behavior is a bug, please provide the steps to reproduce.**

When you create a post, you set the date to 2018-04-04, but publish the post on 2018-04-03. The file will be named "2018-04-03-nameofthepost.md" but on the front-matter will display "2018-04-04".

Example: https://github.com/raulcraveiro/blog/blob/f0253f23397e16ae8a5905b073fa9a86ed509a69/_posts/2018-04-03-outro-teste.md

**- What is the expected behavior?**

I expect that the file name uses the front matter date.

**- Please mention your CMS, node.js, and operating system version.**
CMS: 1.0.0
Operating System: Windows 10 Home
Jekyll version: 3.6.2
Node version: I don't know

**- Please link or paste your `config.yml` below if applicable.**

https://github.com/raulcraveiro/blog/blob/master/admin/config.yml

**Comment by erquhart** [comment]
There's no correlation between a date field in your frontmatter and the date placeholders for slugs - the placeholders will always use the current date at entry creation. Consider that an entry's frontmatter could have multiple dates, and it's not clear which should be used.

The underlying concern of slug customization is being addressed under #445, feel free to add comments there.
