### ISSUE TITLE
Media Library isn't searchable

### ISSUE THREAD

**Issue by swartists** [netlify/netlify-cms#1228]
**- Do you want to request a *feature* or report a *bug*?**

**- What is the current behavior?**

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Please mention your CMS, node.js, and operating system version.**

**- Please link or paste your `config.yml` below if applicable.**

**Comment by tech4him1** [comment]
@swartists The Media Library should have a search bar. Are you having a problem using it?

**Comment by swartists** [comment]
Yes, the search bar is there but when I search a filename, the CMS moves to an error page and no content appears.


Beth Hancock
Head of Digital Content | Web/Creative

STARWORKS ARTISTS
1601 Vine Street
Los Angeles, CA 90028

T  +1 424 704 2466
C +1 917 446 0451

www.starworksartists.com
instagram.com/starworksartists

**Comment by tech4him1** [comment]
Can you provide a link to your repo?

**Comment by tech4him1** [comment]
Also, when the CMS shows the error page, are there any errors in your browser console?

**Comment by erquhart** [comment]
The repo is private.

@owenhoskins know anything?
