### ISSUE TITLE
Error when loading config: Should give helpful feedback on incorrect configuration

### ISSUE THREAD

**Issue by cassiozen** [netlify/netlify-cms#123]
> Uncaught (in promise) TypeError: _integrations.reduce is not a function(…)

**Comment by cassiozen** [comment]
@okonet, I'm can't reproduce this. Tried on both Smashing-pattern-library (using Algolia Integration) and Vegandollhouse (No integrations, directly on github). Both pointing to a local running CMS (on Master branch).

**Comment by cassiozen** [comment]
Are you still seeing this error?

**Comment by okonet** [comment]
Yes, still seeing it.

**Comment by okonet** [comment]
Quickly logging `integrations` results in following:

![2016-10-20 at 15 54](https://cloud.githubusercontent.com/assets/11071/19562696/92aa8e32-96dd-11e6-9275-8dde6315b6c7.png)

**Comment by cassiozen** [comment]
Using what? Vegandollhouse or smashing? Or happens in both?

**Comment by okonet** [comment]
Smashing on `cms-serach` branch and `master` on cms

**Comment by cassiozen** [comment]
I just pushed and updated Smashing config.yaml on the CMS-Search branch. Can you pull and test again?

**Comment by okonet** [comment]
That fixed it. Either way, I'll keep it open since in this case it should display a helpful error message.

**Comment by cassiozen** [comment]
👍

**Comment by josephearl** [comment]
An error is displayed now if there is a config error https://github.com/netlify/netlify-cms/pull/368

**Comment by erquhart** [comment]
@josephearl yeah we can close this.
