### ISSUE TITLE
Bad typography in posts list

### ISSUE THREAD

**Issue by okonet** [netlify/netlify-cms#125]
Titles in the list of articles have huge `line-height` that makes them unreadable. See screenshot — it's one title!

![2016-10-20 at 16 29](https://cloud.githubusercontent.com/assets/11071/19564052/90442c34-96e2-11e6-99ff-b96af22588a6.png)

**Comment by okonet** [comment]
We should also fix typography and make cards consistent for editorial as well

![2016-10-20 at 16 38](https://cloud.githubusercontent.com/assets/11071/19564386/b33c8bd6-96e3-11e6-8cbb-7600d3afa27a.png)

**Comment by cassiozen** [comment]
You can go ahead and change these - since we don't have a complete layout, change to values you feel comfortable with.
