### ISSUE TITLE
Make field label config optional

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#1256]
**- Do you want to request a *feature* or report a *bug*?**

enhancement

**- What is the current behavior?**

"label" is required for field config

**- What is the expected behavior?**

I'd like to just name fields and have the capitalized name serve as the default label. The default (string) widget is most commonly used, so this means many widgets could be defined as:

```yaml
- { name: 'title' }`
```

which makes way for the ultimate minimal field definition:

```yaml
- title
```

😱 

Thoughts?

**Comment by m-henderson** [comment]
I think this is a good idea. So, if no label is defined then we will use the capitalized name for the label?

**Comment by erquhart** [comment]
Exactly. The `- <name>` definition syntax I mentioned would be out of scope for this ticket, so just making the label optional with capitalized name as the default is all that's needed.

**Comment by m-henderson** [comment]
https://github.com/netlify/netlify-cms/pull/1553 will fix this.
