### ISSUE TITLE
Markdown Widget Tab

### ISSUE THREAD

**Issue by ekoeryanto** [netlify/netlify-cms#1259]
**- Do you want to request a *feature* or report a *bug*?**
*feature*
**- What is the current behavior?**
There is no `tab` button
**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**
`tab` button exists or the `textarea` accept tab key so creating nested list will be easy 

**- Please mention your CMS, node.js, and operating system version.**

**- Please link or paste your `config.yml` below if applicable.**

**Comment by erquhart** [comment]
The markdown widget does support nested lists via the tab key:

![image](https://user-images.githubusercontent.com/2112202/38747091-a92ab2c0-3f17-11e8-99f0-e7b06000c2e5.png)

**Comment by erquhart** [comment]
The markdown widget does support nested lists via the tab key:

![kapture 2018-04-13 at 12 39 28](https://user-images.githubusercontent.com/2112202/38747163-e87cd20a-3f17-11e8-8b77-3123513bc0ea.gif)

**Comment by ekoeryanto** [comment]
God, yes it work. the tab key is accepted only on list, but it is reasonable.
Thanks.
