### ISSUE TITLE
Changes to config.yml not picked up by subsequent builds

### ISSUE THREAD

**Issue by dheerajvs** [netlify/netlify-cms#1269]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
Changes to `config.yml` pushed to GitHub are not being picked up in subsequent builds.

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Make changes to `config.yml` by adding new fields to an existing collection and/or adding new collections.
2. Push these changes to GitHub. This triggers a new build.
3. Compare `<mysite>.netlify.com/admin/config.yml` with the one in GitHub. The new changes made are not seen.
4. I also noticed that changes to index.html of the admin site are also not picked up in the published admin site.
5. In desperation, I deleted the entire site and created a new one. The new site is showing the latest changes correctly. But any further changes to `config.yml` are not picked up again.

**Note:** Manually triggering a build even with the "Clear build cache" option does not help.

**- What is the expected behavior?**
The contents of `config.yml` at `<mysite>.netlify.com/admin/config.yml` must be the same as the one in GitHub after changes to the file.

**- Please mention your CMS, node.js, and operating system version.**

- Netlify CMS version: 1.5.0
- Node version on my local development machine: 8.9.4
- OS version on my local development machine: Windows 10

**- Please link or paste your `config.yml` below if applicable.**

- [config.yml in the CMS](https://goofy-brown-518935.netlify.com/admin/config.yml)
- [config.yml in GitHub](https://github.com/dheerajvs/gatsby-kitchen/blob/master/static/admin/config.yml)

**Comment by tech4him1** [comment]
@dheerajvs That would be an issue with your website, not with the CMS. You can try reaching out to Netlify.com support with a description of the problem: https://www.netlify.com/support.

**Comment by tech4him1** [comment]
Glad it is fixed! If you could still see the old file by accessing it's URL directly, though `/admin/config.yml`, then it was definitely not the CMS, it was the hosting, because the CMS is just fetching it directly through the browser.

**Comment by erquhart** [comment]
Sounds like caching

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
