### ISSUE TITLE
Datetime widget is wrapping date in single quotes

### ISSUE THREAD

**Issue by charlotte-l** [netlify/netlify-cms#1271]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Dates generated by the Datetime widget are wrapped in single quotes in the document's front matter.
Example: 
`date: '2018-03-21T11:14:49+00:00'`

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a new entry in the CMS
2. Click "Save"
3. Change status to "Ready"
4. Click "Publish"
5. Note that in the markdown file created, the front matter date is wrapped in single quotes

No other front matter fields which we are using are subject to this issue. 

**- What is the expected behavior?**
Previously the date was not wrapped in single quotes. As the date is now interpreted as a string, this breaks interactions with metalsmith (which requires dates to be in a date format, not as a string).
Example: 
`date: 2018-03-21T11:14:49+00:00`

**- Please mention your CMS, node.js, and operating system version.**
Netlify CMS v1.5.0

**Comment by tech4him1** [comment]
@charlotte-l Can you check what CMS version this happened in? Has it just been since v1.5.0?

**Comment by erquhart** [comment]
@tech4him1 I believe we intentionally dropped the date type from the yaml parser right? Looks like some SSG's need it after all. Hadn't thought much about type requirements in output until this started being reported.

**Comment by erquhart** [comment]
Oh okay, gotcha. So that's tough - the date widget was _supposed_ to be returning a string the whole time, the documented default value, but was instead returning the same default value as `datetime`. A blank string as format should be the way to go, but I'm betting the CMS will consider that falsy and ignore it.

**Comment by tech4him1** [comment]
`moment().format('')` still returns a string for me though, have you tested it?

**Comment by tech4him1** [comment]
We'll also need to note which file formats will serialize to a string anyway. YAML and TOML have an explicit Date format, but JSON doesn't.
