### ISSUE TITLE
Feature: Better support for posts without titles (microblog posts)

### ISSUE THREAD

**Issue by markphilpot** [netlify/netlify-cms#1274]
Right now there is nothing that prevents the creation of posts without titles, but the UI shows empty regions for those posts.  

![image](https://user-images.githubusercontent.com/46191/38827636-65aa5520-4168-11e8-9fe1-6200db0b8817.png)

It would be nice if instead it showed the first X characters (~120) of the post when there is no title.

**Comment by erquhart** [comment]
Totally agree.

**Comment by markphilpot** [comment]
To be clear (and I don't know if this comment belongs here or #445) I was able to create a post without a title (and hence no slug) by relying completely on the time fields:

`slug: "{{year}}-{{month}}-{{day}}-{{hour}}_{{minute}}_{{second}}"`

I agree it's probably better to fix the handling in #445 before but it might not be required.

**Comment by barthc** [comment]
I don't think it's possible any more to create a post without an identifier field or with empty identifier field value, as this error 
` Failed to persist entry: Error: Collection must have a field name that is a valid entry identifier, or must have 'identifier_field' set`
popups up.

**Comment by tomrutgers** [comment]
Just tested this and you are correct @barthc. That error only shows up in the console, so there's not a hell of a lot of feedback as to what's happening but the post isn't published anymore.

**Comment by tech4him1** [comment]
@tomrutgers Do we have another issue covering actual support of posts without titles, or should we reopen/expand this issue to include full support?

**Comment by tomrutgers** [comment]
@tech4him1 There was this one, https://github.com/netlify/netlify-cms/issues/1700 but it got closed by https://github.com/netlify/netlify-cms/pull/1543. We could reopen/expand but then again this issue hasn't been very active anyway.. Thoughts?
