### ISSUE TITLE
Disable preview globally

### ISSUE THREAD

**Issue by ccsource** [netlify/netlify-cms#1289]
**- Do you want to request a *feature* or report a *bug*?**
Feature
**- What is the current behavior?**
You can only disable preview using `preview: false` per collection
**- What is the expected behavior?**
You can add code in the top at config.yml like the following to disable preview **globally**

```
editor:
  preview: false
```

**Comment by lomby92** [comment]
Is still a required feature? In that case, I could work on it

**Comment by erezrokah** [comment]
Thanks @lomby92, I assigned you to the issue. Please let me know if you need anything from the maintainers to get started.
