### ISSUE TITLE
Big Size Bundle

### ISSUE THREAD

**Issue by ekoeryanto** [netlify/netlify-cms#1290]
**- Do you want to request a *feature* or report a *bug*?**
I think it's *feature*
**- What is the current behavior?**
big size bundle
**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**
small size bundle

**- Please mention your versions where applicable.**

Netlify CMS version:
Browser version:

Node.JS version:
Operating System:

**- Please link or paste your `config.yml` below if applicable.**

**Comment by ekoeryanto** [comment]
also, what about make react external so widget created by user can be small?

**Comment by erquhart** [comment]
They'd still have to install it, and many apps that utilize Netlify CMS aren't using React, so it's just an extra step for them.

#328 covers general bundle size improvement, if you think this is a duplicate of that, please close and add a thumbs up and/or comment over there.

**Comment by ekoeryanto** [comment]
Oops, missing that. Sorry
