### ISSUE TITLE
Feature: 'image by URL' editor component

### ISSUE THREAD

**Issue by tomsabin** [netlify/netlify-cms#1293]
**- Do you want to request a *feature* or report a *bug*?**

Feature

**- What is the current behavior?**

<img width="639" alt="screen shot 2018-04-20 at 14 04 04" src="https://user-images.githubusercontent.com/885223/39052396-bc228c7c-44a3-11e8-89de-610a83e362be.png">

**- What is the proposed behavior?**

<img width="639" alt="screen shot 2018-04-20 at 14 05 46" src="https://user-images.githubusercontent.com/885223/39052468-f5a8315e-44a3-11e8-8dc1-79ed26aa9464.png">

- an alternative to uploading an image to Netlify CMS, by referencing an external image instead.

This is partially possible by registering another editor component (see below), but this new editor component gets in conflict with the existing [image editor component](https://github.com/netlify/netlify-cms/blob/8849953b50c54db69ca078a85a5f614892c22f98/src/components/MarkdownPlugins/image.js#L12) (as it's using the same pattern match). However, this component calls the `toBlock` function correctly when first added into the rich editor block, but after changing context, the text is matched to the existing image component. 

```JS
CMS.registerEditorComponent({
  id: 'image_by_url',
  label: 'Image by URL',
  fields: [
    {name: 'url', label: 'Image URL', widget: 'string'},
    {name: 'alt', label: 'Alternative text', widget: 'string'}
  ],
  pattern: /^!\[(.*)\]\((.*)\)$/,
  fromBlock: function(match) {
    // Netlify CMS doesn't seem to execute this function
    return {
      image: match[2],
      alt: match[1]
    };
  },
  toBlock: function(obj) {
    var url = obj.url || '';
    var alt = obj.alt || '';
    return '![' + alt + '](' + url + ')';
  },
  toPreview: function(obj) {
    // Netlify CMS doesn't seem to execute this function
    var url = obj.url || '';
    var alt = obj.alt || '';
    return '<img src="' + obj.url + '" alt="' + obj.alt + '" />';
  }
});
```

**Comment by erquhart** [comment]
I think we'd take a PR to update the current image widget with this.
