### ISSUE TITLE
Markdown Widget Excerpt Option

### ISSUE THREAD

**Issue by ekoeryanto** [netlify/netlify-cms#1304]
**- Do you want to request a *feature* or report a *bug*?**
* *Feature*

**- What is the current behavior?**
no option to toggle the feature
**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**
option `excerpt` exists and `excerpt` button optionally added to the editor

**- Please mention your versions where applicable.**

Netlify CMS version:
Browser version:

Node.JS version:
Operating System:

**- Please link or paste your `config.yml` below if applicable.**

**Comment by erquhart** [comment]
Good point, the Editor Widget button should be removable via configuration just like the others.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by VivekNayyar** [comment]
Can I take this up?

**Comment by erquhart** [comment]
Go for it!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vivek12345** [comment]
@erquhart Can you help me a little here as to what all files to look at for fixing this?

**Comment by ekoeryanto** [comment]
@vivek12345 it uses `gray-matter` so you can search for that

**Comment by marvinkome** [comment]
Please, I like to understand this issue better?

**Comment by erquhart** [comment]
@ekoeryanto I'm not sure if the summary was ever edited for this, but as currently written it isn't clear what this issue is about. Can you explain the request? I initially understood it to be about disabling/removing the Markdown widget's rich text/markdown toggle, but that no longer seems to be the case.

**Comment by ekoeryanto** [comment]
@erquhart, yes I forgot about that. we should be just add a button to add excerpt, sorry.

**Comment by tech4him1** [comment]
@ekoeryanto @erquhart I'm not sure how will we make it clear to the user how or where an excerpt is created by using the more-tag. Wouldn't having them type it in be just as easy?

**Comment by erquhart** [comment]
Probably best to create an [editor component](https://www.netlifycms.org/docs/custom-widgets/#registereditorcomponent) for that. I feel like we can provide a visual indicator just fine, even though the actual code is a comment, but I'm not 100% certain.

**Comment by vivek12345** [comment]
Apologies for the late entry here.I should have researched a bit more about the issue before jumping into finding it as a good first issue and asking to fix it.
After going through a bit of code, I have also realised that I also need to understand the real use case of the excerpt here and then try to fix it

**Comment by erezrokah** [comment]
Closing as stale. Please comment if still relevant and the suggested fix (editor component) doesn't work
