### ISSUE TITLE
How to use h3-h6 in the markdown widget?

### ISSUE THREAD

**Issue by liquidvisual** [netlify/netlify-cms#1308]
In the docs it only shows "heading-one" and "heading-two" as button options. In my templates, I only give users access to h3 and lower, is there any way to do that without making a custom widget?

I've tried passing "heading-three" and "h3" but that doesn't work - and there doesn't seem to be any info (that I could find) on the Slate repo.

**Comment by erquhart** [comment]
Support is already in place, we just need to add the buttons. We should have a larger pool of available buttons than what is enabled by default anyway, should cover everything we support.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by liquidvisual** [comment]
Awesome! Looking forward to it :)

**Comment by mbrookes** [comment]
You missed a question. 😀 

- What should the configuration option for non-default buttons look like?

**Comment by erquhart** [comment]
@Dammmien h3 - h6 is fine for now, can't think of anything else that is well supported enough to include in the toolbar. The icons are custom, just a collection of svgs that we add to as needed.

@mbrookes non default buttons is a separate area of concern, we'd need to allow augmentation of the editor's parser to make that happen. Generally [editor components](https://www.netlifycms.org/docs/custom-widgets/#registereditorcomponent) are enough for custom requirements.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Dammmien** [comment]
@erquhart It takes too much place to display all the buttons.
Does something like that is ok for you ?
![capture d ecran 2018-04-26 a 13 53 37](https://user-images.githubusercontent.com/3051737/39304236-5ab20e4e-4959-11e8-8b53-4ec430c3af35.png)
The editor also support strikethrough text, doest I add a button for it ?

**Comment by erquhart** [comment]
Dropdown works great, although I'm not sure the icon communicates "Header" very well. Adding a strikethrough button would be awesome.

**Comment by oliverpool** [comment]
I was looking for that and just realized, that it has already been implemented!

**Comment by erquhart** [comment]
Ah, yeah this should have been closed.
