### ISSUE TITLE
Loading never ends when opening an unpublished entry in editorial workflow

### ISSUE THREAD

**Issue by okonet** [netlify/netlify-cms#131]
During my work on #129 I've noticed that when opening an unpublished draft the loading will never stop. Here is how the actions are looking in inspector:

![2016-10-21 at 14 58](https://cloud.githubusercontent.com/assets/11071/19599075/e3b9b7e6-979e-11e6-8d11-661879d655d0.png)

So, basically, the action with `type: "UNPUBLISHED_ENTRY_REQUEST"` is fired but the `SUCCESS` or `FAILURE` not.

I can also share a complete `state.json` from redux store.

**Comment by okonet** [comment]
After I've added a `FAILURE` handler, I see that there is an error happening:

`TypeError: Cannot read property 'match' of undefined`

I assume this should be fixed before this one can be closed.

**Comment by cassiozen** [comment]
Fixed [here](https://github.com/netlify/netlify-cms/commit/5151e7cdb1a8ef96d4d3a33120ebdc2d5d54f53b)
