### ISSUE TITLE
Use 'squash and merge' if possible when publishing posts

### ISSUE THREAD

**Issue by raniesantos** [netlify/netlify-cms#1328]
**I mentioned this in the Gitter chat and was told to write up an issue on this.**

### Current behavior:

When the CMS publishes a post, it merges the post behind the scenes. However the resulting commit history shows every single minor update done to the post, it keeps the entire commit history.

### Suggested change in behavior:

The CMS should use the 'Squash and Merge' functionality instead when available.

### Reasoning:

This would make sense for the CMS because when you publish a post, most people (at least I hope so) don't want to see the commit history of the post, it just creates a bunch of visual noise in the git log/commit history.

**Comment by delucis** [comment]
I’m working on a PR that would allow configuration of the `merge_method` passed to the [GitHub API](https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button), which would allow you to set:

```yml
# config.yml
backend:
  merge_method: squash
```

Are there any opinions on implementation details? I have it defaulting to `merge` so it’s backwards-compatible, but I’m not doing any tests on the string to make sure it’s a valid value. Also, `rebase` merges don’t seem to make all that much sense in this context. Would it be more user friendly to have a Boolean option for squash merges instead?

```yml
backend:
  squash_merges: true
```

**Comment by raniesantos** [comment]
> I have it defaulting to `merge` so it’s backwards-compatible

Good.

> Also, `rebase` merges don’t seem to make all that much sense in this context. Would it be more user friendly to have a Boolean option for squash merges instead?

I agree with this, adding a third option just complicates things.
