### ISSUE TITLE
[Minor change] For consistency, the string widget should always wrap input in quotes

### ISSUE THREAD

**Issue by raniesantos** [netlify/netlify-cms#1329]
Very minor issue, but I think it's still worth bringing up.

### Current behavior:

In the case of a post title, the string widget doesn't wrap strings in quotes by default. The generated .md file will contain `title: Foo Bar`. But when you type certain special characters into the widget, it wraps the title in quotes like this (in this example, the character in question is a colon) `title: 'Foo: Bar'`.

### Suggested change in behavior:

The string widget should always wrap the input in quotes.

Additionally, when converting `title`s with single quotes to `slug`s don't add a hyphen.

Example:

`title: 'First Rule: Don''t Talk About Fight Club'` produces this markdown file `first-rule-don-t-talk-about-fight-club.md`.

It should be `first-rule-dont-talk-about-fight-club.md`.

It might be a good idea to strip out all single quotes before converting `title`s to `slug`s

### Reason:

Consistency.

**Comment by raniesantos** [comment]
After some messing around with this widget, I realize now that it's difficult when words like *don't* and *can't* are entered into it.

I am closing this issue.

**Comment by raniesantos** [comment]
I reopened it because I misunderstood something about how YAML escapes quotes.

**Comment by tech4him1** [comment]
It's not technically a bug, just a preference, so a feature would be more appropriate.

**Comment by tech4him1** [comment]
On the YAML quoting part -- why is that an area we need to be consistent in? The YAML parser we use tries to output the simplest code possible, leaving off quotes unless they are absolutely necessary. I tend to agree with that view. Is there an actual problem you are having, or just a preference?

**Comment by raniesantos** [comment]
The only reason I had when I first wrote this issue was for **consistency**. So that the titles in all my .md files have quotes around them.

I did make it clear that I know its a minor issue, so if you close this now, I wouldn't mind.

**Comment by tech4him1** [comment]
Thank you, I appreciate it! The YAML parser we use is https://github.com/nodeca/js-yaml. I don't think they currently support setting the quote style. Since this is minor, like you mentioned, I think we will wait. If at some point in the future they add support for setting quote styles we can re-open this.

Thanks again for filing!

**Comment by raniesantos** [comment]
Created separate issue #1698
