### ISSUE TITLE
Question: How to pass other blog/post data to the CMS Preview (blog post)

### ISSUE THREAD

**Issue by MassivDash** [netlify/netlify-cms#1335]
Hello, 

I am having problems with passing markdown data from other posts to CMS preview. So basically i am showing links to other posts on a post template, what should I do or how should i pass in the props from other posts to be shown in the CMS preview panel ?

I tried to hardcode the missing values in the actual postpreview template but got a react children cannot be a object error. 

Thanks for any help

**Comment by erquhart** [comment]
If you're linking to the other entries using the relation widget, the data for those entries will be in `fieldsMetaData` for each relation field in the preview. Here's the docs: https://www.netlifycms.org/docs/customization/#accessing-metadata
