### ISSUE TITLE
Frontmatter should retain unknown fields

### ISSUE THREAD

**Issue by straight-shoota** [netlify/netlify-cms#1338]
Currently, frontmatter fields not defined in the `fields` option are removed when editing a file.
I don't know the rationale behind this behaviour, but to me (and others #1174) it is highly unexpected. This can easily break things when intended frontmatter configuration gets silently stripped off with no immediate benefit.
In my opinion it would make more sense to simply ignore and keep frontmatter fields the CMS doesn't know about.

I often use frontmatter fields to define specific configuration of a page that is not supposed to be editable through the CMS. While it is possible to add `hidden` fields for that, it seems highly unnecessary - and is very tedious if you have to repeat multiple hidden fields for each file in a file collection. And it's still error prone because you easily forget to add a custom field name to the config. When somebody edits that file through the CMS, it's broken.

**Comment by tech4him1** [comment]
I think this would be great, and seeing we are getting ready for 2.0, we should probably add it then.

**Comment by erquhart** [comment]
Agreed.

**Comment by suhay** [comment]
I was hoping to get a PR out for this today, but got pulled into something else. I have the logic ready to go, just need to write a test for it before put the request in. Hoping to have this ready for review by next week!

**Comment by fool** [comment]
I just got bit by this yesterday - the navigation on our site is driven by "interesting" fields in the frontmatter that I hadn't understood fully until I had to debug where all the nav items went and found the diffs from the CMS removing this:

```
menu:	
    main:	
        parent: aboutmenu
```

so - +1 for this someday :)

**Comment by straight-shoota** [comment]
I still think this is an important feature and there are quite a few supporters. Just waiting for someone to implement it...

**Comment by dieffe** [comment]
I would need this as well.
