### ISSUE TITLE
Add pre-save, pre-publish hooks to CMS

### ISSUE THREAD

**Issue by cpjolicoeur** [netlify/netlify-cms#1348]
Per discussion in the Gitter channel, just making an issue for thoughts & discussion around adding some "hooks" to the CMS for pre-save and pre-publish events.   These hooks could allow the CMS user to modify file content before persisting to the backend (and/or other content changes anyone might want to do in the given hook).

**Comment by delucis** [comment]
I recently needed a widget to automatically generate a modified time for entries, but had to make do with generating it when the editor was opened. Seems like a good example of a widget that would benefit from these hooks.

Could components declare `preSave()` and `prePublish()` similar to the [`isValid()` method](https://www.netlifycms.org/docs/custom-widgets/#advanced-field-validation) that is already available?

**Comment by erquhart** [comment]
I love the idea of events in general, big thumbs up for this.

**Comment by tech4him1** [comment]
Agreed, for the case of providing an initial value like @delucis mentioned, we can work on something like https://github.com/netlify/netlify-cms/issues/725.

**Comment by erquhart** [comment]
Ha! Any ideas for alternatives?

**Comment by xuopled** [comment]
I think this feature could be very usefull for some cases.

I have my content in a git submodules. So each netlify-cms update commit to my submodule repo. But My main repo does not change anymore so netlify does not trigger a new deploy.

**Comment by visuallization** [comment]
Oh yes this feature would be really nice! I could then create dynamically pages with a script within in my nextjs app. So let's say: As an author I create a new page and publish it over netlify cms, "on save" -> the hook kicks in, executes the script which creates tsx files in pages/ based on the .md files in content/.

Are there any news about the progress here?

**Comment by davejm** [comment]
See #2344 for a quick mockup of how this might be implemented. Unsure if this is the right direction but it's a suggestion.

**Comment by erquhart** [comment]
Commented, thanks for using a PR to promote a path forward!

**Comment by delucis** [comment]
Has there been some movement on this or other ways of achieving this behaviour? I see that #2344 is still open.

**Comment by cpjolicoeur** [comment]
Well #2344 was also just closed for inactivity by the bot. :(

It seems this whole project is pretty hit-or-miss when it comes to activity.  The stale bot was just added yesterday and seems to have wiped a bunch of stuff out.

**Comment by TidyIQ** [comment]
I also desperately need this. Is this a WIP or just stale?

**Comment by erquhart** [comment]
This issue is not going to be closed. Introducing stale bot was a step towards maintaining a meaningful backlog - it’s actually a good thing. You’ll see us following up on virtually every issue on this repo over the next two weeks. Thank you all so much for your patience!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by erezrokah** [comment]
#1171 is somehow related in the way both mechanisms hook into specific CMS operations

**Comment by ehayman** [comment]
Just chiming in that this would be SUPER helpful for my project! Would love to see a path forward.

**Comment by erezrokah** [comment]
You can now add events handlers for `prePublish` and `postPublish` events: https://www.netlifycms.org/docs/beta-features/#registering-to-cms-events

Doesn't allow modifying the entry data before publish (at the moment and open to discussion) - can anyone share a use case for changing the data before publish that can't be achieved using a custom widget?

The reason for not allowing it yet is that it requires some thought on how to do it in a safe way. Meaning making sure any change conforms to the data validation enforced by the widgets.

**Comment by delucis** [comment]
@erezrokah My use case was for a last modified date field. This _can_ be achieved with a custom widget, but my effort a while back (see [my comment above](#issuecomment-387866733)) only allowed me to update that time when a post was opened for editing, not when it was saved, which I guess could be more idiomatically handled with `prePublish`.

**Comment by erezrokah** [comment]
Thanks @delucis, that does makes sense. Will keep the issue open for further discussion.

**Comment by vai0** [comment]
@delucis have you been able to find a solution that allows for updating the time on publish rather than on opening the entry? i am also trying to create a "date modified" widget, but none of the solutions have been ideal.

**Comment by delucis** [comment]
@vai0 It’s a while since I worked on this, but no, I just made do with using the time the entry was opened, I think.

**Comment by s8gv** [comment]
Hi @vai0 and @delucis, I have the same use-case. I need to get the published/last updated date-time. I fyou have any workaround can you please let me know Thanks.
