### ISSUE TITLE
[website] consider gatsby instead of hugo

### ISSUE THREAD

**Issue by zebapy** [netlify/netlify-cms#1351]
## Change netlifycms.org website (website folder in this repo) to use Gatsby instead of Hugo

Seems like there could be benefits to using Gatsby instead of Hugo since netlify cms is React based and gatsby has a growing presence in the react static site realm. 

Reasons to move
- No need for all the gulp set up (remove a lot of deps)
- Would remove jquery plugins in favor of react components
- React templating benefits should be obvious here

I'd love to take a crack at this if there's buy-in. I'd just try to recreate the existing site 1:1

## Edit
I've got most of this done here
https://github.com/zebapy/netlify-cms/tree/gatsby-site/website

**Comment by flexchar** [comment]
I think it should be static-site-generator agnostic, and thus, based on API rather than tailored to a specific structure. As such, end users could simply define configuration to work with whichever SSG they wish, just as it does now with collections.

**Comment by zebapy** [comment]
@flexchar I'm talking about the netlifycms.org website in this repo. Not sure I follow how you're talking about the same thing? I could be wrong

**Comment by talves** [comment]
Seriously though. Converting the site to Gatsby or React-Static is more of a preference and a testament to how awesome the JAMStack is today. My vote is React-Static but, if someone is willing to take on Gatsby, I would not be apposed to it. 😋

***Admission:*** Gatsby is a very well supported and maintained project. It is well done. Just not my preferred SSG at the moment.

**Comment by zebapy** [comment]
Out of desire to practice Gatsby, I have a Gatsby version about 80% done.
I'll post it shortly!

**Comment by knpwrs** [comment]
> My vote is React-Static but, if someone is willing to take on Gatsby, I would not be apposed to it. 😋

Casting my vote for react-static as well. I've found it to be a lot simpler than Gatsby. It's also ultimately better at splitting out routes if you want some reasoning that's more objective (for instance, on my site, currently powered by Gatsby, all of the blog posts are in one bundle with other pages in their own bundles, I would prefer for each blog post to be in its own bundle).

**Comment by zebapy** [comment]
@erquhart I have a lot of this done here if you want to check it out https://github.com/zebapy/netlify-cms/tree/gatsby-site/website

I still need to fix a couple things but wanted to share it earlier.

**Comment by knpwrs** [comment]
@zebapy Gatsby only splits on routes or individual items rather than collections of items. I'll quote Kyle Matthews from an email correspondence:

> A few things that might be confusing about code splitting. We only code split in production not development. It simplifies things a lot in development if we just have a single bundle.js. Also we only create code splits on "routes". Meaning if multiple pages share the same React component e.g. blog posts then there'll only be one bundle created for all the blog posts.

**Comment by knpwrs** [comment]
Another good candidate could be [VuePress](https://vuepress.vuejs.org/). I haven't used it myself but I like that they let you use Vue components inside Markdown. It reminds me of [mdx](https://github.com/mdx-js/mdx).

**Comment by erquhart** [comment]
Apparently VuePress is tailored to technical documentation, very interesting. The default theme includes: 

Responsive layout
Optional Homepage
Simple out-of-the-box header-based search
Algolia Search
Customizable navbar and sidebar
Auto-generated GitHub link and page edit links

Very interesting.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zebapy** [comment]
There's also https://docusaurus.io/

**Comment by erquhart** [comment]
@zebapy I just got to check out your fork, it really is 80% to a production ready Gatsby migration. You have my vote, killer work my friend. Thanks so much for jumping in like this!

**Comment by DirtyF** [comment]
For the record, here's [a webpagetest on the actual website](https://webpagetest.org/result/180515_3T_8d35a431e0b9bff3fc4839e40d5f064a/). It would be interesting to compare results between both SSG. Gatsby should score better at LightHouse by default.

**Comment by bep** [comment]
>React templating benefits should be obvious here

How is this obvious in a documentation site? Can you elaborate?

**Comment by erquhart** [comment]
@DirtyF webpagetest of the in progress deploy preview: https://www.webpagetest.org/result/180525_GC_a9486c40a857bef10a68b25d6791a59e/

**Comment by bep** [comment]
>Since the vast majority of content contributions happen in Markdown files, I expect docs contributions to be largely unaffected.

Sure, I just wanted you to think about it and not just dive into some "would it not be cool to do the docs in react" simple arguments.

From a document contributor perspective (i.e. as someone who wants to write documentation), I would, of course (I'm biased), prefer something static that I could just `git clone; somebinary run; edit and commit`. I have not looked at your current distribution, but that should be possible with Hugo and compiled JS/CSS. That is not the case with a JS static generator where you would need to do the whole NPM dance to get it up and running. 

So, there are trade-offs to consider. Your docs may get "richer" in its UI, but it may also be harder to reason about for editors. And if you really feel that you need all those animated buttons to get the message across ...
