### ISSUE TITLE
[feature request] derive title from fields

### ISSUE THREAD

**Issue by zebapy** [netlify/netlify-cms#1352]
**Feature request**

Is there a way to derive the title from a field or a combination of fields? Currently my app has no real use for a title field because it's not used in the content but there needs to be a distinguishable title for identifying content from the collection landing page.

**Comment by barthc** [comment]
@erquhart  doesn't the `identifier_field` config option address this issue?

**Comment by tomrutgers** [comment]
@barthc yes it does. 
@zebapy you can use `identifier_field: fieldname` to use another field than title.

**Comment by erquhart** [comment]
Good catch guys 👍

**Comment by zebapy** [comment]
This is _almost_ want I was hoping for. Seems you can't combine values though and it's based on one field? I was looking for something like `identifier_field: "{{date}}-examplename"`

**Comment by erquhart** [comment]
If this is strictly for the collection landing page, #2019 should do the trick for you.
