### ISSUE TITLE
Relation Widget Makes API call for each instance

### ISSUE THREAD

**Issue by hughrawlinson** [netlify/netlify-cms#1357]
**- Do you want to request a *feature* or report a *bug*?**

A Bug

**- What is the current behavior?**

I have a config file that contains a list of relation widgets. The RelationControl component seems to be making an API request for each widget in the list, even though they're relating to the same collection. Because I have quite a long list, this is having a huge negative impact on page load time.

**- If the current behavior is a bug, please provide the steps to reproduce.**

Create a json file in your repository, and configure a collection with a list of elements using the relation widget. Relate to your collection of blog posts. Watch netlify load the document listing once for each widget.

**- What is the expected behavior?**

I'd expect netlify to cache the document listing so that page load doesn't take 30 seconds for loading the same data over and over again.

**Comment by erquhart** [comment]
@hughrawlinson can you share a minimal reproduction case that can be cloned/forked? Or share the one you're encountering this issue with?

**Comment by hughrawlinson** [comment]
I cant share the one I'm encountering the issue with, but I'll try and repro it with another site :)

**Comment by barthc** [comment]
Entries are now cached.
