### ISSUE TITLE
[feature request] Pagination inside the CMS

### ISSUE THREAD

**Issue by gedeondt** [netlify/netlify-cms#1362]
When working with big amounts of documents for a document type it seems that all of them are listed at once inside the CMS. I have tested a site with 10.000 posts and all of them were listed with no pagination on the CMS.

Thanks

**Comment by tech4him1** [comment]
@Benaiah will your pagination work for GitLab affect GitHub as well?

**Comment by erezrokah** [comment]
Closing as duplicate of https://github.com/netlify/netlify-cms/issues/50
