### ISSUE TITLE
1.8.1 - Cannot publish new documents

### ISSUE THREAD

**Issue by Jinksi** [netlify/netlify-cms#1377]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

Using CMS version `1.8.1`, cannot publish new documents. Get __Failed to persist entry__ error.

See console.log screenshot:

<img width="1262" alt="screen shot 2018-05-24 at 12 22 10 pm" src="https://user-images.githubusercontent.com/3147296/40461518-14a1c37a-5f4f-11e8-90ec-5ba813cd7f78.png">

May have something to do with 

**- If the current behavior is a bug, please provide the steps to reproduce.**

Creating a new document in a collection, clicking **Publish Now**

**- What is the expected behavior?**

Rolling back to `1.8.0` fixes this issue.

**- Please mention your versions where applicable.**

Netlify CMS version: 1.8.1
Browser version: Chrome 67

Node.JS version:
Operating System: macOS 10.13.3

**- Please link or paste your `config.yml` below if applicable.**

**Comment by Jinksi** [comment]
FYI using `git-gateway`

**Comment by erquhart** [comment]
Unable to reproduce so far. Can you still reproduce? Any error message toast notifications popping up when it fails?

#1239 seems the only likely PR in 1.8.1 to cause something like this, but it _should_ have produced a toast notification if that was the case.

**Comment by Jinksi** [comment]
Yes, toast notification is:

`Failed to persist entry: API_ERROR: Not Found`

<img width="501" alt="screen shot 2018-05-24 at 2 16 44 pm" src="https://user-images.githubusercontent.com/3147296/40464206-2b0aebc4-5f5d-11e8-88a2-97080bd83b95.png">

**Comment by erquhart** [comment]
Can you link to a repo that reproduces? Still not able to trigger the error.

**Comment by Jinksi** [comment]
https://github.com/Jinksi/test2

[CMS new post page](https://festive-blackwell-918a9c.netlify.com/admin/#/collections/post/new)
I've opened invites if you want to log in.

I've used the [one-click-hugo-cms](https://github.com/netlify-templates/one-click-hugo-cms) template and added [this commit](https://github.com/Jinksi/test2/commit/e1053dcffb2b94312fb3a2ad605b614096f3d27d) to use 1.8.1.

I'm able to update existing posts, but cannot create new posts.

**Comment by kyleoliveiro** [comment]
I'm trying to get started with Netlify CMS, and I'm running into this error as well while using `github` backend.

**Comment by satzz** [comment]
Also happening to mine(It didn't a few days ago). I'm using `unpkg.com/netlify-cms@^1.0.0`. The error happens when saving a new entry in editorial workflow, as well as when publishing.

**Comment by erquhart** [comment]
Working on this now.

**Comment by papandreou** [comment]
Was the new version published to npm? I don't see it:

```
$ npm info --json netlify-cms | jq -r '.["dist-tags"].latest'
1.8.1
```

The npm guys had an incident the other day that caused published packages to not be available immediately, could be that the problem is back: https://status.npmjs.org/incidents/3rjzvts6v98k

**Comment by tech4him1** [comment]
It is live on npmjs.com and unpkg.

**Comment by papandreou** [comment]
Ah, there is a new incident reported: https://status.npmjs.org/incidents/238t55n6f03f

**Comment by erquhart** [comment]
Whoops, accidental close.

I'm seeing it on unpkg now.

**Comment by papandreou** [comment]
I wrote an email about the missing package to npm support.

**Comment by erquhart** [comment]
Awesome, thanks @papandreou.

**Comment by papandreou** [comment]
They wrote me back, and it's there now :tada:

**Comment by Jinksi** [comment]
All working 👏
