### ISSUE TITLE
Save in-progress posts to localStorage.

### ISSUE THREAD

**Issue by tech4him1** [netlify/netlify-cms#1380]
Currently, if a user is working on a post, and either the API or the browser has problems, there is no in-browser backup. They must close the window and thereby lose their post. I think we should have some way to cache a post while it is being written. Once it is saved successfully (published or as a draft), the instant cache can be cleared.

**Comment by erquhart** [comment]
Agreed, way overdue. #388 covers this as well, we should track the request there.
