### ISSUE TITLE
Custom confirmation url for new user invite

### ISSUE THREAD

**Issue by runandrew** [netlify/netlify-cms#1388]
I am using Netlify/Netlify CMS with a React Static Site. To access the admin panel, the Netlify CMS site is located at domain.com/admin. When I invite new users, they are sent to my root domain domain.com#token, which does not present anything to make a password (I believe this is because I do not have the identity widget on that part of my site).

Is there a way to change the confirmation url to direct straight to domain.com/admin?

Thanks!

**Comment by erquhart** [comment]
Has to happen on your root domain, you'll need to have the widget in place on your home page.

**Comment by raae** [comment]
If you use the Gatsby plugin [gatsby-plugin-netlify-cms](https://www.gatsbyjs.org/packages/gatsby-plugin-netlify-cms/) both the admin page and the identity manager is added for you.

**Comment by erquhart** [comment]
@runandrew please re-open if you need more info.
