### ISSUE TITLE
Editor component fields: required and isValid not honored

### ISSUE THREAD

**Issue by papandreou** [netlify/netlify-cms#1390]
**- Do you want to request a *feature* or report a *bug*?**

*bug*

**- What is the current behavior?**

It doesn't seem to be possible to achieve validation for fields in custom editor components. Seems like the `required` and `isValid` options are ignored.

**- If the current behavior is a bug, please provide the steps to reproduce.**

Marking the `Youtube Video ID` field as `required` (or adding `isValid(value) {return false}`) reproduces it:

```js
CMS.registerEditorComponent({
  // Internal id of the component
  id: "youtube",
  // Visible label
  label: "Youtube",
  // Fields the user need to fill out when adding an instance of the component
  fields: [{
    name: 'id',
    label: 'Youtube Video ID',
    widget: 'string',
    required: true
  }],
  // Pattern to identify a block as being an instance of this component
  pattern: /^youtube (\S+)$/,
  // Function to extract data elements from the regexp match
  fromBlock: function(match) {
    return {
      id: match[1]
    };
  },
  // Function to create a text block from an instance of this component
  toBlock: function(obj) {
    return 'youtube ' + obj.id;
  },
  // Preview output for this component. Can either be a string or a React component
  // (component gives better render performance)
  toPreview: function(obj) {
    return (
      '<img src="http://img.youtube.com/vi/' + obj.id + '/maxresdefault.jpg" alt="Youtube Video"/>'
    );
  }
});
```

1. Add a Youtube component
2. Don't fill out the `Youtube Video ID` field
3. Click "Publish"

**- What is the expected behavior?**

That the publication attempt is blocked because the custom widget is in an invalid state.

[The docs for custom widgets say this should be supported for all widget fields](https://github.com/netlify/netlify-cms/blob/master/website/site/content/docs/custom-widgets.md#advanced-field-validation), so this is a bit surprising.

> All widget fields, including those for built-in widgets, include basic validation capability using the `required` and `pattern` options.

**- Please mention your versions where applicable.**

Netlify CMS version: 1.8.4
Browser version: Chrome 66.0.3359.181 (OSX)

Node.JS version: 9.5.0
Operating System: 5.6.0

**- Please link or paste your `config.yml` below if applicable.**

**Comment by tech4him1** [comment]
@papandreou What line are you adding `isValid` to? Do you have a code example using `isValid` instead of `required`?

**Comment by papandreou** [comment]
@tech4him1, I added it to the field declaration like this:

```js
  fields: [{
    name: 'id',
    label: 'Youtube Video ID',
    widget: 'string',
    isValid(value) {
      return false;
    }
  }],
```

**Comment by tech4him1** [comment]
@papandreou I believe it is supposed to go directly in `registerEditorComponent`, not nested under `fields`.

**Comment by papandreou** [comment]
@tech4him1, ah, seems like I didn't not read the documentation for `isValid` closely enough. It does say "the widget control", not "the widget field". Neat that it can be used to validate the component state as a whole.

However, putting it at the top level like this doesn't work either:

```js
CMS.registerEditorComponent({
  // Internal id of the component
  id: "youtube",
  isValid(value) {
    return false;
  },
```

If I add a `debugger` statement to it, I can tell that it isn't even being called.

**Comment by papandreou** [comment]
@talves, ah, thanks for clearing that up. I must have confused the concepts when reading the documentation, https://www.netlifycms.org/docs/custom-widgets/#advanced-field-validation does say that the widget **control** can implement an `isValid` method.

Because the `isValid` examples don't provide any context and come right after an example that used `registerEditorComponent` I assumed that "the widget control" was a synonym for the spec object passed to `registerEditorComponent` :roll_eyes:

Consider this a vote for tightening up this section of the documentation a bit.
