### ISSUE TITLE
CollectionName not prepended to branch names in Editorial Workflow mode

### ISSUE THREAD

**Issue by shaunbent** [netlify/netlify-cms#1396]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

I have two collections which contain pages with the same names with different content. With the Editorial Workflow enabled changing any of these pages effects the other collections equivalent page.

I think I've worked out what is happening, it looks like the generated branch names do not contain the `collectionName-` as it suggests it should in the documentation.

At first I thought this was the same issue as https://github.com/netlify/netlify-cms/issues/1164 but I actually think its different.

Looking at the code I think the problem is here: https://github.com/netlify/netlify-cms/blob/55a24a75c14fcef97b19f9c1fe6cc1579e0b59c2/src/backends/github/API.js#L325

It seem as just the `slug` is passed to the `generateBranchName` function and not `options.collectionName` as well. I might be wrong though.

So in my case instead of `cms/pages-consumer/color`, I get `cms/color`.

**- If the current behavior is a bug, please provide the steps to reproduce.**

- Create two collections with pages/files of the same name
- Make a change to a file in one collection and see the branch/PR created with the name `cms/[name of file]`
- Try changing the corresponding file in the other collection and you should see the changes you made in the previous step.

**- What is the expected behavior?**

Branches should be created with the `collectionName` prepended to the branch name allowing them to be different.

**- Please mention your versions where applicable.**

Netlify CMS version: 1.8.4
Browser version: Chrome 66

Node.JS version: 9.8.0
Operating System: OS X

**- Please link or paste your `config.yml` below if applicable.**

**Comment by erquhart** [comment]
Looks like a long standing regression from [#145](https://github.com/netlify/netlify-cms/pull/145/files#diff-d3cff7a0c66d0acce37277791446d509L211).

**Comment by nazihahmed** [comment]
a simple fix i made to my branch (in our case we had `index.md` for most collections), so i simply check if the slug is index and add to it the collectionName.
here is a ref which you can base your fix on: 
in file `API.js` after line `281`
```
      if (file.slug === "index") {
        file.slug = "index-" + file.path.match(/\/([\w-]+)\/index\.md$/)[1];
      }
```
the line ` file.path.match(/\/([\w-]+)\/index\.md$/)[1];` takes the collection name from the path, you will need to modify the code to work in your case for either to pass the collection name to this function somehow to to parse it out of the url

**Comment by erquhart** [comment]
We'd definitely take a PR for this.

**Comment by nazihahmed** [comment]
I will work on that by the weekend..
it needs some changes, anyways happy to help
