### ISSUE TITLE
Slug pattern doesn't accept dots

### ISSUE THREAD

**Issue by CodeEsthete** [netlify/netlify-cms#1399]
I hope this is not a duplicate. 

I create a slug with following pattern and I noticed that everything after "." gets removed and en suffix added which I don't want to have. 

     slug: "{{year}}-{{month}}-{{slug}}.pl"

After creating new page my filename looks like 

     2018-08-my-new-page-en.md

while I am expecting to see it like 

     2018-08-my-new-page.pl.md

**Comment by erquhart** [comment]
Yeah it's this right here:

https://github.com/netlify/netlify-cms/blob/1.8.4/src/backends/backend.js#L86-L87

@tech4him1 any reason not to allow dots?

**Comment by erquhart** [comment]
Ah, duh, the extension field. @CodeEsthete I believe this solves your issue, but please comment if not and I'll reopen.

**Comment by Nic128** [comment]
I tried adding the extension as mentioned. I can create the entry properly.
```
extension: "pl.md"
format: "frontmatter"
```
It produces `{{slug}}.pl.md` files, great.

I can't seem to list the entry back. Changing to `extension: "md"` works and I see the created file. I want to keep `pl.md` in the end, but can't use it fully. What could be the issue?

**Comment by tech4him1** [comment]
@Nic128 Can you file a new issue? Please add as much detail on how to reproduce as you can -- that should work.

**Comment by ntloi95** [comment]
Because I use Netlify cms with other plugin, I have to have "." in file name. It required filename with format:
"{url}.{{language}}.md" 
Is there any way to solve it? language change programmatically.
