### ISSUE TITLE
[Discussion] Custom Widget Library

### ISSUE THREAD

**Issue by talves** [netlify/netlify-cms#1400]
## Feature Request:

Allow for users to make PR's to add their custom widgets to the NetlifyCMS site to keep track of published widgets out there.

## Proposal:

Requirements might include having a custom widget be published to npm. The collection would allow someone to add a configuration entry into frontmatter that would be added to the site page showing all available widgets with targeted SSG, categories and features for the developer to be able to find what they need.

cc/
@Benaiah 
@erquhart 
@tech4him1 
Maintainers: Make updates to this request as you feel is needed based on comments and ideas.

**Comment by talves** [comment]
We have been discussing creating a place for people to publish information about their custom widgets on the NetlifyCMS site somewhere. You are right, and a plan to have a full information format will help quite a bit. I am sure we will get there. We just need someone in the community to take it on when they get time. I might tackle it with some other stuff I am doing, but it is lower on the priority at the moment.

**References:**
https://github.com/netlify/netlify-cms/issues/325#issuecomment-393947637, https://github.com/netlify/netlify-cms/issues/325#issuecomment-393973461

**Comment by hennessyevan** [comment]
This is kind of a neat implementation https://www.gatsbyjs.org/plugins/ I think would be worthwhile looking at as well, from what I can tell it just searches for NPM packages related to `gatsby-plugin` and then sorts them based on their popularity, or make it more curated, something like what I assume is that case with netlify's own [headlesscms.org](https://headlesscms.org/). That would put more work on the reviewers' end though.

The widget starter does encourage custom widgets to be named `netlify-cms-widget-<name>` already.

**Comment by talves** [comment]
Closing based on duplicate https://github.com/netlify/netlify-cms/issues/1286
