### ISSUE TITLE
Drag and drop builder

### ISSUE THREAD

**Issue by scottybo** [netlify/netlify-cms#1401]
Question: Is there a Drag and Drop builder that works with Netlify? i.e the equivalent of: https://elementor.com/pro/

Page builders dramatically speed up the creation of sites and they're much "friendlier" for end users to work with, as let's be honest, the average SME employee who has been given the job of keeping the site up to date doesn't have the first idea about anything technical.

**Comment by loremipson** [comment]
#1169 seems to be really close.

**Comment by scottybo** [comment]
looks promising, thanks! When is v2 due?

**Comment by loremipson** [comment]
I'm no official voice here, but the last I heard is it's still on for July. Probably mid to end July.

Someone can correct me if this has changed though.

**Comment by scottybo** [comment]
Good to know, thanks!

**Comment by haroldao** [comment]
> I'm no official voice here, but the last I heard is it's still on for July. Probably mid to end July.
> 
> Someone can correct me if this has changed though.

🥺
