### ISSUE TITLE
Error accessing Netlify CMS from mobile browser

### ISSUE THREAD

**Issue by anbuchelva** [netlify/netlify-cms#1402]
**- Do you want to request a *feature* or report a *bug*?**
Bug
**- What is the current behavior?**
I tried accessing Netlify CMS from mobile chrome browser. It took me to the error page.
**- If the current behavior is a bug, please provide the steps to reproduce.**
Login to Netlify CMS through mobile, chrome browser
Try to edit the post, which is already in draftsman
The markdown portion doesn't scroll up, scroll the page manually, when the keyboard is visible,
Error!!
**- What is the expected behavior?**
It shouldn't take us to error page

**- Please mention your versions where applicable.**

Netlify CMS version: netlify-cms@^1.0.0
Browser version: chrome 67 android

Node.JS version: Not applicable
Operating System: Android

**- Please link or paste your `config.yml` below if applicable.**
https://github.com/anbuchelva/hyperion/blob/master/source/admin/config.yml

**Comment by tech4him1** [comment]
@anbuchelva It is a known issue that the CMS doesn't work in mobile. We want to get it working, but right now, like you found, the main blocker is the support of the markdown editor, Slate. If you want to help contribute to their issue with your findings, that would be great!

Netlify CMS issue: https://github.com/netlify/netlify-cms/issues/441
Slate issue: https://github.com/ianstormtaylor/slate/issues/1720
