### ISSUE TITLE
Cannot upload large Files to Media Gallery

### ISSUE THREAD

**Issue by pungggi** [netlify/netlify-cms#1404]
**- Do you want to request a *feature* or report a *bug*?**
Bug
**- What is the current behavior?**
Cannot upload large Files to Media Gallery. I am trying to upload a 55 MB Video.
It says:
API_ERROR: NetworkError when attempting to fetch resource.
CORS-Header 'Access-Control-Allow-Origin' is missing

I am using gatsby-plugin-netlify-cms.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Upload a file bigger than 50 MB

**- Please mention your versions where applicable.**
Netlify CMS version: 1.8.4
Node.JS version: 8.9.0
Operating System: Windows 10

https://github.com/graphicmachines/website

**Comment by erquhart** [comment]
Fixed?

**Comment by pungggi** [comment]
No, but it doesnt seem to be the problem of the cms..but github..

I manually tried to upload a 53 MB Video.. and it says my limit is 25 MB. I thought the limit is 100 MB according to the docs?!

**Comment by erquhart** [comment]
Ah - _reading_ blobs supports up to 100MB, the docs don't specify a limit for _creating_ them. Apparently it's 25MB.

Watch this issue for updates on external asset store integrations: https://github.com/netlify/netlify-cms/issues/432
