### ISSUE TITLE
Hidden field in editor component is rendered

### ISSUE THREAD

**Issue by papandreou** [netlify/netlify-cms#1405]
**- Do you want to request a *feature* or report a *bug*?**

*bug*

**- What is the current behavior?**

An editor component that declares a hidden field will have it rendered:

![screen shot 2018-06-05 at 11 10 57](https://user-images.githubusercontent.com/373545/40966679-6ab6c768-68b1-11e8-90a6-37c9c1cefca2.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Declare an editor component that has a field with `widget: 'hidden'`:

```js
CMS.registerEditorComponent({
  // Internal id of the component
  id: "youtube",
  // Visible label
  label: "Youtube",
  // Fields the user need to fill out when adding an instance of the component
  fields: [{
    name: 'id',
    label: 'Youtube Video ID',
    widget: 'string'
  }, {
    name: 'myHiddenField',
    label: 'My hidden field',
    widget: 'hidden'
  }],
  // Pattern to identify a block as being an instance of this component
  pattern: /^youtube (\S+)$/,
  // Function to extract data elements from the regexp match
  fromBlock: function(match) {
    return {
      id: match[1]
    };
  },
  // Function to create a text block from an instance of this component
  toBlock: function(obj) {
    return 'youtube ' + obj.id;
  },
  // Preview output for this component. Can either be a string or a React component
  // (component gives better render performance)
  toPreview: function(obj) {
    return (
      '<img src="http://img.youtube.com/vi/' + obj.id + '/maxresdefault.jpg" alt="Youtube Video"/>'
    );
  }
});
```

2. Add an instance of the component to a markdown editor.

Observe that the label for the hidden field is rendered with a `No control for widget: 'hidden'` message below it. The same thing happens if the hidden field has no `label` except that a small gray box is rendered instead of the label.

**- What is the expected behavior?**

That the field isn't rendered, similar to how `hidden` widgets work for collections.

**- Please mention your versions where applicable.**

Netlify CMS version: 1.8.4
Browser version: Chrome 67.0.3396.62/OSX

Node.JS version: 9.5.0
Operating System: OSX

**- Please link or paste your `config.yml` below if applicable.**

**Comment by erquhart** [comment]
Good catch!
