### ISSUE TITLE
Ability to sort collections by date modified or other fields

### ISSUE THREAD

**Issue by chrisjpatty** [netlify/netlify-cms#1412]
**- Do you want to request a *feature* or report a *bug*?**
Feature request

It would be nice to be able to sort collections by fields other than the title. When a collection grows large enough it becomes more difficult to navigate. 

**- Please mention your versions where applicable.**
Netlify CMS version: 1.7.0
Browser version: Chrome 66

**Comment by tech4him1** [comment]
This seems like a duplicate of https://github.com/netlify/netlify-cms/issues/54?

**Comment by chrisjpatty** [comment]
Oops, you're right, I somehow missed that one. Closing as a duplicate of #54.
