### ISSUE TITLE
Can't access private repos

### ISSUE THREAD

**Issue by pbrandone** [netlify/netlify-cms#1415]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Log in with github backend to access a private repo. My user has the correct privileges.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Add NetlifyCMS to a private repo
2. Configure CMS to use github backend and provide `repo`
3. Try to Log In with github
4. Not Found notif is triggered

**- What is the expected behavior?**
Be able to login. My user has access to the repo

Netlify CMS version: 1.8.0
Browser version: Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by robertkarlsson** [comment]
I had this problem when going from public -> private repo. I had go generate a new key.

**Comment by pbrandone** [comment]
@robertkarlsson with github backend or with git-gateway?

**Comment by pbrandone** [comment]
@robertkarlsson also I never went from public to private. It was always private.

Opened a PR at #1416 with my quick-fix. If it's not the right way or, even better, if I'm doing something wrong please let me know so we can close both the issue and the PR

**Comment by tech4him1** [comment]
@pbrandone Is the repo under an GitHub organization, or is it on your personal account?

**Comment by pbrandone** [comment]
@tech4him1 under an org

**Comment by tech4him1** [comment]
Looks like GitHub has instructions here:
1. https://help.github.com/articles/requesting-organization-approval-for-oauth-apps/
2. https://help.github.com/articles/approving-oauth-apps-for-your-organization/

**Comment by pbrandone** [comment]
@tech4him1 thanks but it seems that netlify CMS doesn't appear under the oAuth apps list.
The only way I can get this to work this way is completely removing application restrictions. Is this the right way?

**Comment by erquhart** [comment]
Did you check under "OAuth Apps" or "Third Party Access"? It's "Third Party Access" that would show the request.

**Comment by pbrandone** [comment]
I found the issue. Because I already had played a bit with netlifyCMS under my own user (not org), this app was under my own personal settings.
By revoking my user access and trying to log in again I could manage grant access to the org.

Sorry for all the trouble and thanks for the help

**Comment by amadeann** [comment]
I also wasn't able to access the admin panel for a private repo belonging to an organization. Here's how I fixed it:

1. Go to https://github.com/settings/applications 
2. Select `Authorized OAuth Apps` tab
3. Click on `Netlify CMS`
4. Click on `Grant` next to your organization name

This assumes that you already granted access to `Netlify CMS` from your private profile.

**Comment by Uzay-G** [comment]
I am also having this issue (site created yesterday). Any tips?

I tried resetting identity / git gateway but still it fails with the message 

> Git Gateway Error: Please ask your site administrator to reissue the Git Gateway token.
