### ISSUE TITLE
GitHub Backend o-auth permissions set too widely

### ISSUE THREAD

**Issue by ro-savage** [netlify/netlify-cms#1423]
Currently when using Github Backend, the app requires access to pretty much everything.

![image](https://user-images.githubusercontent.com/9244507/41239202-22fd7a0c-6d98-11e8-860c-2df8309aa68f.png)

The scope is hard coded to `repo` here : https://github.com/netlify/netlify-cms/blob/78e4b829d0ced72f8f38721d38c0d67ccb092aaf/src/backends/github/AuthenticationPage.js#L26

It would make more sense to have a much more limited scope or at least a way to customise it.

I'd suggest `public_repo` by default.

In the future, maybe deploy keys would work better, allowing only access to a single repo.

**Comment by erquhart** [comment]
I suppose making this configurable would be fine, just might require some error handling around attempts to access restricted repos.

Proposing:

1. Keep the current default, it's important that this "just works"
2. Accept an `auth_scope` property under `backend` in `config.yml`
3. Restrict accepted values to those that work for the CMS, currently `repo` and `public_repo`

Thoughts?

cc/ @Benaiah @talves @tech4him1

**Comment by talves** [comment]
@erquhart The screen capture implies the login has access to ALL repos within the login. Is that true or is it only the repo logging into?

**Comment by tech4him1** [comment]
@talves It has access to every repo on your account -- the only two OAuth scopes available for repo access are `repo` (ALL repos) and `public_repo` (write access to ALL public repos).

**Comment by EasterPeanut** [comment]
The permissions are insane. I don't need Netlify to have read/write permissions over ALL repo's and I don't need Netlify to have **organization access**. What for does Netlify need this? Plus, the default setting is that it wants PUBLIC and PRIVATE repo access? Seriously, this is red flags all over for me and it's making me not want to use Netlify.

**Comment by erezrokah** [comment]
I'm going to prioritize this one to better support the open authoring workflow (no need for private repository access)
