### ISSUE TITLE
Feature :: Field Note Option

### ISSUE THREAD

**Issue by gil--** [netlify/netlify-cms#1426]
Unless I somehow overlooked it, there is no way to currently add a "note" to a field. So, would there be interest in adding a new option to all fields called Note? There are times where a more detailed description of expected input would be helpful to the user than just a field label by itself. Something like:

##### @gilgnyc for example. 

Probably a terrible example but hopefully you get the point. I can try to mock up a UI example tonight. 

I mainly want to see if this is something that would be considered for core before I spent a lot of time adding it to the code base.

**Comment by shaunbent** [comment]
I think this is a great idea, I'm currently creating a website powered by Netlify CMS which has multiple contributors and it would be great to add additional descriptions to fields to help editors better understand the types of content they should use.

**Comment by tech4him1** [comment]
This seems like a duplicate of https://github.com/netlify/netlify-cms/issues/552 to me -- if so can we move the discussion there?

**Comment by gil--** [comment]
Indeed it's along the same lines. Sorry about this. Searched for 'Note' but didn't find anything so I opened this. 

Will close.
