### ISSUE TITLE
editing files with the same name in different collections

### ISSUE THREAD

**Issue by stavmaz** [netlify/netlify-cms#1431]
I have an issue with editing files with the same name in different collections.
When editing a file (index.md) in a specific collection the cms creates a new branch with the name cms/index, now it's in workflow screen waiting to be merged. Then I want to edit a different file with the same name (index.md) in a different collection and in a different folder of course (as specified correctly in the config.yml file), but i get the content of the first index.md that i edited already.

i've tried to track the calls in network tab in dev tools and saw that the collection is being called right but then the file is not the right one.

**Comment by erquhart** [comment]
Thanks for reporting - this is a known issue (#1396), please add any additional comments there.
