### ISSUE TITLE
Sites can't be deployed to GitLab group

### ISSUE THREAD

**Issue by patrikhuber** [netlify/netlify-cms#1434]
**- Do you want to request a *feature* or report a *bug*?** => Bug

**- What is the current behavior?** => Site always deployed under the personal GitLab account

**- If the current behavior is a bug, please provide the steps to reproduce.** => Have a GitLab account that additionally has a group created - so there is, for example, https://gitlab.com/myusername as well as https://gitlab.com/groups/mygroupname/ under your account. If you're using GitLab for your business, you'd have this structure in your account. The personal space, and the group for the business.

Then click here: https://app.netlify.com/start/deploy?repository=https://github.com/netlify-templates/one-click-hugo-cms&stack=cms
to deploy the example app to GitLab. It gets deployed under the personal GitLab account, which is not useful for businesses.

**- What is the expected behavior?** => Be able to choose / deploy into the group namespace.

**Comment by erquhart** [comment]
This would be a feature request for the Netlify platform - maybe mention it in `https://gitter.im/netlify/community`. Netlify CMS isn't involved with site deployments.

**Comment by verythorough** [comment]
@patrikhuber, though this does pertain to the Netlify platform, I'll post an answer here in case anyone else happens across it.

Your link above is for a Deploy to Netlify button. They're made to be a quick way to deploy a copy of a pre-made site, and for this reason, some less-common options are dropped in favor of simplicity. It's true this wouldn't work for a business using a GitLab group, but most businesses aren't deploying copies of pre-made sites, anyway.

To deploy the site linked above using a group-owned repo, the steps are a little more manual:

1. Clone the example repo (https://github.com/netlify-templates/one-click-hugo-cms) to your group on GitLab.
2. Log in to Netlify, and click **New site from Git**.
3. Authenticate with GitLab, and you'll see a list of all the repos our access token has access to. Select your group from the dropdown to filter for repos belonging to your group.
4. Select your cloned repo. 
5. The example repo is configured so the site deploy settings will be pre-filled. Click **Deploy site**, and your site will be deployed.
7. From the the dashboard of your new site, select **Identity** from the top menu items.
8. Click **Enable Identity**.
9. Go to **Settings > Identity > Services**, and click **Enable Git Gateway**.

When you've finished those steps, you'll have done what the Deploy to Netlify button does. After that, you can follow the rest of the guide on https://www.netlifycms.org/docs/start-with-a-template/

**Comment by patrikhuber** [comment]
@verythorough Cool that's awesome and very helpful, thank you very much!
