### ISSUE TITLE
Invalid markdown generated when applying styling to a selection with leading or trailing whitespace

### ISSUE THREAD

**Issue by papandreou** [netlify/netlify-cms#1448]
**- Do you want to request a *feature* or report a *bug*?**

*bug*

**- What is the current behavior?**

When applying bold or italics to a selection that includes leading or trailing whitespace, the resulting markdown will put the space inside the `**`/`_` delimiters. This means that the delimiter isn't a 
[left/right flanking delimiter run](https://spec.commonmark.org/0.28/#emphasis-and-strong-emphasis), and thus markdown compilers will render the emphasis characters literally.

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Enter `foo bar quux` in a markdown widget.
2. Select ``bar `` including the space after:

![screen shot 2018-06-18 at 10 06 36](https://user-images.githubusercontent.com/373545/41525300-cd86a0be-72e0-11e8-8568-97de22d0c230.png)

3. Click the Bold button:

![screen shot 2018-06-18 at 10 06 49](https://user-images.githubusercontent.com/373545/41525318-e0fbc944-72e0-11e8-8e9c-292d1f29022e.png)

4. Switch to markdown mode:

![screen shot 2018-06-18 at 10 06 57](https://user-images.githubusercontent.com/373545/41525386-17d98604-72e1-11e8-921f-f4131ac78612.png)

Observe that the rendered markdown is invalid (or rather, that it doesn't specify the bold text correctly). This can be verified using [the commonmark.js demo](https://spec.commonmark.org/dingus/) or [the markdown-it demo](https://markdown-it.github.io/), for example.

**- What is the expected behavior?**

That the bold text in the markdown does not include the space: `foo **bar** quux`.

A more advanced variant of the bug can be created without ever having leading/trailing whitespace in a selection:

1. Enter the text `foo bar quux baz`
2. Select `bar quux`
3. Click the bold button
4. Delete `quux ` (including the following whitespace) via the keyboard
5. Switch to markdown mode.

This produces `foo **bar **baz`, which should have been `foo **bar** baz`.

Turns out this happens a lot in practice when editing the sort of content that we manage via netlify-cms.

**- Please mention your versions where applicable.**

Netlify CMS version: 1.9.2
Browser version: Chrome 67.0.3396.87/OSX

Node.JS version: 10.4.1
Operating System: Mac OSX 10.13.5 (High Sierra)

**Comment by robertgonzales** [comment]
Has anyone found a workaround for this issue?

**Comment by papandreou** [comment]
@robertgonzales, I've attempted a fix, PR here: #1517. Would be great if you could take it for a spin!

**Comment by polemius** [comment]
I've tested this behaviour on the lates master branch and looks like this issue not relavent now:

<img width="118" alt="Screen Shot 2019-10-03 at 21 44 50" src="https://user-images.githubusercontent.com/48512663/66158870-1449ba80-e627-11e9-86dd-c084e5fbc7ac.png">
<img width="113" alt="Screen Shot 2019-10-03 at 21 44 58" src="https://user-images.githubusercontent.com/48512663/66158872-16137e00-e627-11e9-93bd-e525e549c084.png">
<img width="169" alt="Screen Shot 2019-10-03 at 21 45 03" src="https://user-images.githubusercontent.com/48512663/66158875-17dd4180-e627-11e9-8484-7d41aa232407.png">

**Comment by papandreou** [comment]
Yes, the fix was landed and included in 2.4.0. I'll close this.
