### ISSUE TITLE
[bug] int val output in TOML format as floating point

### ISSUE THREAD

**Issue by slathrop** [netlify/netlify-cms#1457]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
TOML file output always renders numbers as float. This is *by design* in the [tomlify package](https://github.com/jakwings/tomlify-j0.4#known-problems) and requires custom "output replacer" logic to fix.

**- If the current behavior is a bug, please provide the steps to reproduce.**
In config.yml, specify collection format as `toml` and a field as `number` with `valueType` set to `int`.

**- What is the expected behavior?**
`int` should *not* be rendered as a `float` with a decimal point `789.0`. Instead, it should be rendered `789`.

**- Please mention your versions where applicable.**
Netlify CMS version: 1.9.2
Browser version:
Latest Chrome beta

**Comment by barthc** [comment]
Fixed in #1458
