### ISSUE TITLE
images not appearing when their filenames contain Unicode

### ISSUE THREAD

**Issue by arsenijesavic** [netlify/netlify-cms#1459]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Cannot retrieve some images if a folder has more then 1000 files.
Getting error: "Failed to load resource: the server responded with a status of 404 ()".
However, in the admin panel, media assets are retrieving all images, probably due to the fact that it is using blobs (https://github.com/netlify/netlify-cms/commit/55a24a75c14fcef97b19f9c1fe6cc1579e0b59c2).

**- If the current behavior is a bug, please provide the steps to reproduce.**
Create a site using gatsby-starter-netlify-cms with github as backend,
add static/img folder with more then 1000 files.
create the collection that is consuming all images. 

**- What is the expected behavior?**
Ability to get all files from static/img folder.

This bug is probably connected to the [github api ](https://developer.github.com/v3/repos/contents/) limit that states: "This API has an upper limit of 1,000 files for a directory. If you need to retrieve more files, use the Git Trees API."

Does anybody have any idea how to get around this limit?

Netlify CMS version: 1.9.0
Browser version: Chrome 67

**Comment by erquhart** [comment]
Can you explain "create the collection that is consuming all images"?

The GitHub backend doesn't currently pull image blobs through the API, do you have more than 1,000 entries in your collection directory?

**Comment by arsenijesavic** [comment]
Sorry for bad explanation, what I wanted to say is use all images.
After a lot of debugging, the problem was not in amount, rather it was in different latin encodings (probably because images were named on windows, and consumed on mac).
It was creating bad links, and I realize that after trying to access images directly using https://raw.githubusercontent.com, and inspecting network tab on chrome.

Here is an example for the letter š
full image name: 7_Flešmoba_IlijaLazarevic.jpg

network request when directly accessing an image on git hub repo (this one is showing image)
.../img/12_Fle%C5%A1moba_ilijaLazarevic.jpg

network request on the website (404 not found)
/img/12_Fles%CC%8Cmoba_ilijaLazarevic.jpg

After replacing all special latin character with regular one, I can access all 1489 images, and everything works fine. :)

**Comment by tech4him1** [comment]
Weird, we should probably try to fix that if possible.

**Comment by tech4him1** [comment]
Great, glad you found the problem! If it's working in the CMS but not on the live website, then it sounds like that's probably an issue you would need to address with your site generator.
