### ISSUE TITLE
No error message shown if there is an error in authentication

### ISSUE THREAD

**Issue by zolamk** [netlify/netlify-cms#1460]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
"Doesn't display any kind of warning or error message for incorrect password or email"

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Created a site with netlify cms
2. Tried to login with incorrect email and password
3. Silently fails with no error or warning

**It should display some sort of warning**

Netlify CMS version: 1.9.2
Browser version: Firefox 60.0.1

[config.yml](https://saleina.netlify.com/admin/config.yml)

**Comment by tech4him1** [comment]
You will need to add the identity script to your admin page and home page (it should be in the `<head>`).
```html
<script type="text/javascript" src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>
```

**Comment by zolamk** [comment]
@tech4him1 not sure why it doesn't work without `netlify-identity-widget.js` but it has solved the issue
