### ISSUE TITLE
[Bug] Cannot list multi-part extension files

### ISSUE THREAD

**Issue by Nic128** [netlify/netlify-cms#1462]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
You can't list files using a multi-part extension.

**- If the current behavior is a bug, please provide the steps to reproduce.**
- Forked the one-click-hugo-cms: https://gitlab.com/Nic128/one-click-hugo-cms/
- Rename the posts from `.md` to `.en.md`
- Set the extension for the posts and format to:
```
extension: 'en.md'
format: 'frontmatter'
```
- Create a new post, the post will be created properly. `{{slug}}.en.md`
- You can't see any file listed for editing, even if the files exist.
- I see the list data from ajax calls, but the filtering in the cms code is filtering everything out.

**- What is the expected behavior?**
If just using `md` list the files correctly, `en.md` should list the same files.

I found out how to use multi-part extension from this thread. https://github.com/netlify/netlify-cms/issues/1399

**- Please mention your versions where applicable.**

Netlify CMS version: 1.9.2
Browser version: Firefox 60

Node.JS version: 8.11.2
Operating System: OSX

**- Please link or paste your `config.yml` below if applicable.**
https://gitlab.com/Nic128/one-click-hugo-cms/blob/master/site/static/admin/config.yml

**Comment by Nic128** [comment]
I did some digging.

``
entriesByFolder(collection, extension) {
    return this.api.listFiles(collection.get("folder"))
    .then(files => files.filter(file => fileExtension(file.name) === extension))
    .then(this.fetchFiles);
  }
``

`fileExtension(file.name)` is made to only return `md` from the filename. Makes sense.

`fileExtensionWithSeparator` from the `pathHelper.js` file has a lot of usecases I wouldn't want to break.

My use case could be solved by doing something this.

``
entriesByFolder(collection, extension) {
    return this.api.listFiles(collection.get("folder"))
    .then(files => files.filter(file => file.name.endsWith(extension)))
    .then(this.fetchFiles);
  }
``

But all the other cases wouldn't work. Trailing slash, etc...

If the slug with language `{{slug}}.{{language}}` gets added as part of 2.0, this fix won't be necessary.

**Comment by tech4him1** [comment]
@Nic128 That's exactly the right fix, it was added to GitHub in https://github.com/netlify/netlify-cms/pull/1123, but didn't get ported over to GitLab. Feel free to make a PR for that if you're up for it.
