### ISSUE TITLE
netlify-cms@^1.0.0 error after login

### ISSUE THREAD

**Issue by julie-impuls** [netlify/netlify-cms#1467]
When using netlify-cms@^1.0.0, I get the following error in Chrome after login in the admin: JSON.parse: unexpected character at line 1 column 1 of the JSON data.

In the console I get a 404 on .netlify/git/settings (implementation.js:62).

I fixed this by using netlify-cms@1.9.2 for now.

**Comment by tech4him1** [comment]
@julie-impuls This sounds like a problem with your Git Gateway (and/or Identity) settings, since `^1.0.0` is currently the same as `1.9.2`.  Try re-generating the access token (https://www.netlify.com/docs/git-gateway/#getting-started), then trigger a new deploy.

**Comment by julie-impuls** [comment]
@tech4him1 Re-generating the access token and triggering a new deploy seemed to work. Thank you!
