### ISSUE TITLE
Telephone number links aren't displayed correctly

### ISSUE THREAD

**Issue by Juhannuspukki** [netlify/netlify-cms#1479]
**- Do you want to request a *feature* or report a *bug*?**

*bug*

**- What is the current behavior?**

The CMS displays tel links as plaintext.

**- If the current behavior is a bug, please provide the steps to reproduce.**

Write a tel link, such as [+358 123 456 7890](tel:+358 123 456 7890) and look for it in preview.

**- What is the expected behavior?**

The example link appears as +358 123 456 7890 with an underline and blue color, just like urls.

**- Please mention your versions where applicable.**

Netlify CMS version: 1.9.1

**Comment by erquhart** [comment]
Tel links work, it's just spaces that don't - they're not valid characters in a link under Commonmark or GitHub Flavored Markdown notice that GitHub didn't style the link in your original post). Closing, but do comment if I'm missing something.
