### ISSUE TITLE
Combine javascripts to enhance performance

### ISSUE THREAD

**Issue by StarAzure** [netlify/netlify-cms#1482]
The live site loads as many as 5 javascript files right out of the box. testmysite gives a score of 100 as its possibly biased towards netlify but many other site speed tests do not like that there are many js files and gives a score of 0:

How can all these js files be combined into a single bundled js file ? 

See message below from pingdom site tools:

_There are 5 JavaScript files served from siteXYZ.netlify.com. **They should be combined into as few files as possible.**
https://siteXYZ.netlify.com/app-c4111e1d649156d8637d.js
https://siteXYZ.netlify.com/commons-3120bf6e8d158c1696fb.js
https://siteXYZ.netlify.com/component---src-layouts-index-js-38e5017e687a172512dc.js
https://siteXYZ.netlify.com/component---src-pages-index-js-a4f3baa95fc08592a373.js
https://siteXYZ.netlify.com/path---index-07c4097b72a6410d9e4e.js_

**Comment by tech4him1** [comment]
Netlify CMS does not actually output your site like a traditional CMS. It is considered a "headless CMS", which allows you to create and update your content, but leaves the output to a "site generator" (such as Hugo or Gatsby). Accordingly, the CMS doesn't actually have anything to do with what JavaScript is output, and you will need to configure that in your site generator.
