### ISSUE TITLE
Use HTML elements for accessibility #a11y

### ISSUE THREAD

**Issue by growdigital** [netlify/netlify-cms#1486]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

Many HTML elements used in the app are `<div>`s rather than semantically correct and accessible HTML elements (such as `<main>`, `<aside>`, `<li>` etc.). This means accessibilty software such as screen readers can't navigate the screen as effectively.

This is a refinement on https://github.com/netlify/netlify-cms/issues/1333 Accessiblity #a11y issues 

**- If the current behavior is a bug, please provide the steps to reproduce.**

Use a screen reader with the app. Alternatively, view source and see that eg the main content area `nc-collectionPage-main` uses a `<div>` rather than `<main>`.

**- What is the expected behavior?**

Use semantically correct HTML elements where possible 🙂

**- Please mention your versions where applicable.**

Netlify CMS version: 2.0.0-dev-dev
Browser version: 61.0

Node.JS version: v8.9.1
Operating System: MacOS 10.13.5

**- Please link or paste your `config.yml` below if applicable.**

**Comment by tech4him1** [comment]
Awesome, I've been wishing someone would do this! 😃

**Comment by alexandernanberg** [comment]
I think #1585 should've closed this correct?

**Comment by erquhart** [comment]
Yeah, looks like 👍
