### ISSUE TITLE
Transfer the cookies to Github API

### ISSUE THREAD

**Issue by MrEfrem** [netlify/netlify-cms#1491]
* Do you want to request a feature or report a bug?
Feature

I develop the Editor with own authorization founded on JWT tokens. 
The Netlify CMS I've put to the iframe. 
Also I use own OAuth server and Github proxy therefore I've set `api_root` and `base_url` to the own endpoints. 
To authorize clients in a own API I'm checking JWT token stored in the cookie (or in `Authorize` header).
The OAuth request successfully send cookies to the my OAuth server and I'm authorizing client. But the "Github" requests, the Netlify CMS execute via "Fetch API", and it don't send the cookies to `api_root` endpoint. To make that, is necessary to add the option `credentials: 'include'` to all "fetch API" requests.
I can to create PR, what do you think?

**Comment by MrEfrem** [comment]
oh, I've found graceful way to return from "OAuth" endpoint my JWT token and then "Github" requests will put it to "Authorization" header which I will check.

**Comment by tech4him1** [comment]
@MrEfrem Great, glad you were able to get it working! For future reference, there is also an open source platform called [`git-gateway`](https://github.com/netlify/git-gateway) that is built for that exact purpose, and it already integrates with the CMS.

**Comment by MrEfrem** [comment]
The `git-gateway` has connect with third-party identity server.

**Comment by tech4him1** [comment]
I believe it's possible to use it yourself (without a third party). @biilmann Can you explain? I'm wanting to know myself, even if @MrEfrem has his set up 😄.

**Comment by MrEfrem** [comment]
@tech4him1 I also have set up my solution so that I more don't input username/password for log in to CMS. I.e. when I log in to the my Editor I'm also doing log in to the Github REST API to get `access_token`. And when I log in to the CMS I just return received before `access_token` from `auth_endpoint`. But with `git-gateway` I didn't find how to implement similar, because it always ask first to input the `username` / `password`.
Also would be ideally if I can log in to CMS without click on `Login with GitHub` button.
I hope the my trick will work further also well and the developers won't break current implementation of the `Github` backend further -:). Therefore many thanks for their work.
