### ISSUE TITLE
it broke 

### ISSUE THREAD

**Issue by jairajmatharu** [netlify/netlify-cms#1492]
**- Do you want to request a *feature* or report a *bug*?**

**- What is the current behavior?**

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Please mention your versions where applicable.**

Netlify CMS version:
Browser version:

Node.JS version:
Operating System:

**- Please link or paste your `config.yml` below if applicable.**

**Comment by tech4him1** [comment]
@jairajmatharu Please describe what your issue is and answer the questions in the issue description so that we can help you better.
