### ISSUE TITLE
Serious problems when using multiple branches.

### ISSUE THREAD

**Issue by richtera** [netlify/netlify-cms#1493]
Bug

When using two deployments with the CMS pointed to two different branches everything works ok until one person edits the same file as another person on the other branch. Since the refs/heads/cms is not name spaced by the base branch like ``` `refs/heads/cms/${basebranch}` ``` maybe or some variation. Then the branches will match and when it tried to do the merge all hell breaks loose :)

It's easy to produce. Make a netlify content repo with admin setup.
Branch the repo.
Deploy both branches on different netlify instances.
Login to admin on both.
Edit the same file in both instances.

Everything works fine without Editor workflow turned on, so you'd have to turn that on as well.

**- Please mention your versions where applicable.**
Netlify CMS version: 1.9.3
Browser version: 67 chrome

Node.JS version: 9.11
Operating System: Mac OS X

**- Please link or paste your `config.yml` below if applicable.**

**Comment by richtera** [comment]
Added PR #1494

**Comment by erezrokah** [comment]
Closing as stale
