### ISSUE TITLE
Failed to load netify identity setting on google cloud site.

### ISSUE THREAD

**Issue by ankush86** [netlify/netlify-cms#1495]
**- Do you want to request a *feature* or report a *bug*?**
Bug
**- What is the current behavior?**
I deployed my application on google cloud which is using netify-cms with gatsby.  I am unable to login on admin section. I used git-gateway. when I try to login I am getting error
_`Failed to load settings from /.netlify/identity`_ 

On localhost it is working fine.

Thanks in advance

**Comment by erquhart** [comment]
The `/.netlify/identity` endpoint is referring to Netlify's managed Identity service. It isn't available on Google Cloud. Please reach out in Netlify's [community Gitter](https://gitter.im/netlify/community) if you have other questions on this!
