### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by vanjaPalpa** [netlify/netlify-cms#1496]
**- Do you want to request a *feature* or report a *bug*?**

**- What is the current behavior?**

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Please mention your versions where applicable.**

Netlify CMS version:
Browser version:

Node.JS version:
Operating System:

**- Please link or paste your `config.yml` below if applicable.**

**Comment by tech4him1** [comment]
@vanjaPalpa Please provide details on how the error occured so that we can try to fix it.
