### ISSUE TITLE
Question: Customize deploy message on github 

### ISSUE THREAD

**Issue by caelialuk** [netlify/netlify-cms#1497]
Is it possible to customize this message (Update pages "about"), and if so, how?

![screen shot 2018-07-13 at 2 43 01 pm](https://user-images.githubusercontent.com/24300124/42708608-d72f724c-86ab-11e8-9797-7ead5cc4b9c3.png)

**Comment by tech4him1** [comment]
Yes! It is currently a beta feature, the documentation is here: https://www.netlifycms.org/docs/beta-features/#commit-message-templates.
