### ISSUE TITLE
Change `tabindex`es on the editor page.

### ISSUE THREAD

**Issue by emsenn** [netlify/netlify-cms#1499]
**- Do you want to request a *feature* or report a *bug*?**
feature
**- What is the current behavior?**
When you arrive at the page-editing page, and press tab, it takes you through the links in the header first.

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**
 It'd be more convenient if it took you immediately to collection fields, and then cycled through the header and footer. However, this may be counter to accessibility standards, in which case, please disregard me.

**- Please mention your versions where applicable.**

Netlify CMS version:
Browser version:

Node.JS version:
Operating System:

**- Please link or paste your `config.yml` below if applicable.**

**Comment by renestalder** [comment]
Tabindex shouldn't be used. It's counter accessible as you already mention. It's better to provide a hidden skip link to directly jump to the content.

Alternatively there is also the possibility of accesskeys as hidden table of contents to quickly jump to all sections. But that would probably be over-engineered for the case of a CMS UI.
