### ISSUE TITLE
[Bug] - Multi-users editing same collection entries

### ISSUE THREAD

**Issue by loremipson** [netlify/netlify-cms#1500]
**Current behavior**

Multi-user editing causes potential issues if they start editing the same content entries in a couple of scenarios:

1. If two or more users end up editing the _same_ content entry at the _same_ time.
2. If the publishing workflow is enabled, and an entry is marked as "In Review" or "Ready", other users can continue to make edits to the entries.

Both situations result in failed publishing/saving and/or lost work for any user aside from the initial editor.

**Steps to reproduce**

This one takes various playing around, it seems. We're getting mixed results when doing this, but below are the situations we tried.

* Have **User A** and **User B** both open the _same_ collection entry.
* **User A** edits and saves the entry.
* **User B** (unaware of User A's edits) also edits and saves the entry.
* **User A's** work is now either lost due to **User B's** save. Or **User B's** save fails and he/she loses all of their work.

**Expected behavior**

An entry should be "locked" once it's in edit mode. If one user is editing, display a message to other potential users that it is locked, so they do not risk losing edits.

If publishing workflow is set in the project, the entry file(s) should also be locked if they are moved into the "In Review" or "Ready" columns.

**Comment by erezrokah** [comment]
Closing as this is covered in https://github.com/netlify/netlify-cms/issues/277
