### ISSUE TITLE
Package has both yarn.lock and package-lock.json

### ISSUE THREAD

**Issue by giraffesyo** [netlify/netlify-cms#1516]
This package seems to be mixing use of yarn and npm. With the advent of yarn 1.7.0 we were given the ability to import `package-lock.json` from npm into yarn.

 It's recommended that we choose one package manager and stick to it throughout the project, to prevent confusion. In the [contributing.md](https://github.com/netlify/netlify-cms/blob/master/CONTRIBUTING.md), yarn is recommended to be installed, but then is never used within the instructions. In the package.json file npm is chosen over yarn within the scripts.

I also think that we should not maintain two lock files.

Are there any thoughts on this?

**Comment by erquhart** [comment]
I was planning on using Renovate to keep both lock files up to date, but after reading up a bit the consistency issues are best avoided. Choosing to support one or the other is tough, but sounds like we should.

**Comment by erquhart** [comment]
It sort of is - I could have sworn I had an idea on how to just use the npm lockfile even with that being the case, but can't recall now. Not seeing precedent of checking in package-lock.json in any of the better known Lerna projects.

**Comment by talves** [comment]
Just for clarification: **workspaces are Yarn Workspaces** and Lerna takes advantage of this structure using yarn.

**Comment by tech4him1** [comment]
Yup, exactly. It seems like Lerna has it's own code to handle workspaces without Yarn -- it's not as nice, though. See https://github.com/lerna/lerna/pull/899.

**Comment by LayersOfAbstraction** [comment]
I have a React web app that keeps generating those files on Github repo even though I've deleted them from my local repo and explicitly said to exclude them in my .gitnore file. These two files have over 60 vulnerbilities that I'm getting auto fixes for. Any idea and how I can stop them from being uploaded?

**Comment by erquhart** [comment]
We should just drop package-lock.json. With our yarn dependency due to workspaces, documentation should be updated to indicate yarn rather than npm.
