### ISSUE TITLE
incorrect href value on docs site

### ISSUE THREAD

**Issue by m-henderson** [netlify/netlify-cms#1529]
**- Do you want to request a *feature* or report a *bug*?**
bug
**- What is the current behavior?**
Clicking href on docs site returns 404
**- If the current behavior is a bug, please provide the steps to reproduce.**
1. navigate to https://www.netlifycms.org/docs/widgets/
2. under "Widgets" in the third paragraph click "configuration code".
3. you are navigated to a 404 page.
**- What is the expected behavior?**
1. click "configuration code"
2. the user should be directed to "https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms/example/config.yml".

**- Please mention your versions where applicable.**

Netlify CMS version:
Browser version:

Node.JS version:
Operating System:

**- Please link or paste your `config.yml` below if applicable.**

**Comment by m-henderson** [comment]
https://github.com/netlify/netlify-cms/pull/1533 will fix this one.

**Comment by verythorough** [comment]
Closed by #1533
