### ISSUE TITLE
Images from Media Assets are not fetched correctly giving 403 when using bitbucket

### ISSUE THREAD

**Issue by bomzj** [netlify/netlify-cms#1546]
**- Do you want to request a *feature* or report a *bug*?**
*bug*

**- What is the current behavior?**
![image](https://user-images.githubusercontent.com/2025775/43370694-5f029270-938c-11e8-8933-06805034e420.png)
In my local sandbox attempt to fetch images give 403 for each image request, while other stuff (non images) are fetched correctly. Image urls have wrong url containing guid instead of "master". 
api.bitbucket.org/2.0/repositories/bomzj/house-fresh/src/**84cf67837016f94a5f00e809d62ca2faf7dabca7**/static/img/houseFreshLogo128x128.svg
VS
All other fetch requests have "master" instead of guid e.g. api.bitbucket.org/2.0/repositories/bomzj/house-fresh/src/**master**/static/css/main.css 

In postman, for testing purposes,  I replaced that guid with "master" and got the image.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1) use bitbucket as backend in config.yml
2) log in to a site 
3) open Media assets popup

**- What is the expected behavior?**
Images should display without any issues.

**- Please mention your versions where applicable.**
Netlify CMS version: 2.0.6
Browser version: Chrome 68
Node.JS version: 8.9
Operating System: Windows 10

**- Please link or paste your `config.yml` below if applicable.**
backend:
  name: bitbucket
  repo: private info

media_folder: "static/img"

**Comment by tech4him1** [comment]
ping @Benaiah

**Comment by arifpedia** [comment]
Same here, but i'm using GitLab as backend (private repo). In Headers Tab, Status Code: 404 Not Found. 
![netlifycms](https://user-images.githubusercontent.com/4081293/43537051-6c1d9af0-95e8-11e8-93d4-037c8573c231.PNG)

If i open link image to new tab:
![netlifycms1](https://user-images.githubusercontent.com/4081293/43537701-435ed320-95ea-11e8-87d1-eee3064268af.PNG)

**Comment by tech4him1** [comment]
@arifpedia There is a separate issue filed for that problem at https://github.com/netlify/netlify-cms/issues/1436.
