### ISSUE TITLE
[docs] internal links get mangled

### ISSUE THREAD

**Issue by vladdu** [netlify/netlify-cms#1560]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
Clicking on any internal links in the docs pages (i.e. pointing to somewhere under https://www.netlifycms.org/docs/), the href gets mangled: the href is appended to the current page's URL, like it was an internal link. 

The source code looks ok, though, so my guess is some javascript is involved. Links to external URLs work ok too.

**- If the current behavior is a bug, please provide the steps to reproduce.**
- open the "Introduction" page
- click on "Start with template" link
- I get shown https://www.netlifycms.org/docs/intro/https://www.netlifycms.org/docs/start-with-a-template/

**- What is the expected behavior?**
The correct page should get opened.

**Comment by m-henderson** [comment]
@vladdu I am not able to reproduce this issue. What browser are you using? Can you try another browser and let me know if the page opens correctly for you?

**Comment by vladdu** [comment]
I can confirm that it works as expected if I disable Javascript on the page, from the dev tools.

**Comment by vladdu** [comment]
https://github.com/gatsbyjs/gatsby/issues/6888
