### ISSUE TITLE
Add / remove data from yml file

### ISSUE THREAD

**Issue by mittalyashu** [netlify/netlify-cms#1605]
**- Do you want to request a *feature* or report a *bug*?** feature

**- What is the current behaviour?** not able to edit the data file `_data/member.yml` in Jekyll

**- What is the expected behaviour?** able to add or remove data from yml file directly from netlifyCMS.

**Comment by tech4him1** [comment]
You can use a `file`-type collection in the CMS, see the docs at https://www.netlifycms.org/docs/collection-types/#file-collections.

**Comment by tech4him1** [comment]
qu
