### ISSUE TITLE
Sort field output when nested under object/list.

### ISSUE THREAD

**Issue by mittalyashu** [netlify/netlify-cms#1609]
**- Do you want to request a *feature* or report a *bug*?** Not sure

**- What is the current behavior?**

I have fields setup this way.

![image](https://user-images.githubusercontent.com/29014463/44050030-5daa8dc4-9f53-11e8-8eae-4cea403e6df1.png)

I want the name to show up first and then colour, but the output is

![image](https://user-images.githubusercontent.com/29014463/44050038-646254b2-9f53-11e8-8cdd-390360e14488.png)

First color and then name. Why?

_(Example from the [github repo](https://github.com/mittalyashu/netlify-sort))_

![carbon_2018-08-14_01-16-14](https://user-images.githubusercontent.com/29014463/44054242-b3724d12-9f5f-11e8-8127-9b9ef9c3daed.png)

**- What is the expected behavior?**

I want the name to show up first and then colour.

**- Please mention your versions where applicable.**
Netlify CMS version: 2.0.9
Browser version: 68.0.3440.106

**- Links**

* Github repo: https://github.com/mittalyashu/netlify-sort
* Live website: https://elegant-lewin-22ee38.netlify.com/admin/

**Comment by erquhart** [comment]
Color and then name because it's alphabetical. This is essentially an object and key order should not matter or be relied upon. I don't see us supporting this but feel free to comment if you feel it merits further discussion.
