### ISSUE TITLE
Workflow on github should create a label and attach it to the PR.

### ISSUE THREAD

**Issue by springdo** [netlify/netlify-cms#1617]
**Describe the solution you'd like**
Workflow plugin is great if you use netlify-cms as the single source of the truth *and* your content moderators can merge / publish from it UI. 

In our case, we have a bot account that acts as the person who raises PRs. So when a user logs in, they don't have to be added to the git organisation but can still contribute content via the bot. The bot does not have permission to merge to master.  I would like to see the workflow tag the PR in git with the state of the workflow ie `ready` etc. This way a content moderator can look at the Git PRs to see what's not in draft and merge accordingly

**Alternative solution**
Create the PR _only_ when the issue has been moved into `review`

**Comment by erquhart** [comment]
Agreed, was discussing this exact thing with @tech4him1 a few weeks back. I created a proposal out of that discussion in #1669.

**Comment by erezrokah** [comment]
closing in favour of https://github.com/netlify/netlify-cms/issues/1669
