### ISSUE TITLE
Markdown editor is not saving the emoji

### ISSUE THREAD

**Issue by mittalyashu** [netlify/netlify-cms#1618]
**Describe the bug**

When I select an emoji from the emoji picker it doesn't save to the editor, but if we copy the emoji from somewhere else and then paste it, then it works.

**To Reproduce**

Steps to reproduce the behaviour:

1. Edit the post
2. Right-click inside the markdown editor
3. Select emoji option
4. Add the emoji of your choice
5. Close the emoji pop-up.

**Expected behaviour**

When we select an emoji, it should save the emoji in the markdown editor.

**Screenshots**

![image](https://files.gitter.im/netlify/NetlifyCMS/FKul/2018-08-14_17-58-19.gif)

**Applicable Versions:**

 - Netlify CMS version: 2.0.9
 - Git provider: GitLab
 - OS: Windows 10
 - Browser version: 68.0.3440.106

**Additional context**

I think this emoji picker option is built in chrome  _(not sure)_.

**Comment by robertkarlsson** [comment]
I tried this in the PR #1451 that updates Slate and adding emojis is working on OSX Chrome. Can you try the preview link for the CMS there and see if you can add emojis since we don't run the same OS.

**Comment by mittalyashu** [comment]
Yeah, it worked: https://youtu.be/A4PkdwuizqI

**Comment by dmackca** [comment]
Experiencing this in 2022 with version 2.10.192. Should I open a new issue?
