### ISSUE TITLE
Bitbucket repo "No Auth Provider Found"

### ISSUE THREAD

**Issue by lichtner** [netlify/netlify-cms#1627]
I am not sure if it is a bug, maybe I missed something. I tried to set up bitbucket repo followed instructions here: https://www.netlifycms.org/docs/add-to-your-site/

**I did this:**

In top menu **OAuth applications**:

1. I created new OAuth app (here https://app.netlify.com/account/applications)

Then for the site:

2. In **Identity** menu I added my personal gmail 
3. In **Settings/Identity/Registration** I set **Invite only**
4. In **Setting/Access control/OAuth** I set **key** and **secret** from created **new OAuth App** (from step 1)

After clicking on button **Login with Bitbucket** I get 
![image](https://user-images.githubusercontent.com/411581/44283063-654cf280-a25d-11e8-8214-a07f8bac64ad.png)

on netlify subdomain this:
![image](https://user-images.githubusercontent.com/411581/44279014-33815f00-a250-11e8-88a2-e87a60eb1f13.png)

I also copied hugo static pages on my server I saw this:
![image](https://user-images.githubusercontent.com/411581/44279042-4f850080-a250-11e8-99a2-842ceaf0ddc5.png)

/static/admin/index.html
```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Content Manager</title>
  <script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>
</head>
<body>
  <!-- Include the script that builds the page and powers Netlify CMS -->
  <script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
</body>
</html>
```

**Applicable Versions:**
 - Netlify CMS version: 2.0.9
 - Git provider: BitBucket
 - OS: Ubuntu 18.04
 - Browser version chrome 68

**CMS configuration**
```yml
backend:
  name: bitbucket
  repo: my-repo-name
```
I am not sure I missed something to set up? Thanks

**Comment by unyo** [comment]
Make sure the callback url for your oauth consumer points here: https://api.netlify.com/auth/done/

**Comment by nolafs** [comment]
I do have this as me callback but it won't work

https://api.netlify.com/auth/done/

**Comment by tomrutgers** [comment]
@nolafs I believe bitbucket is having some issues at the moment
