### ISSUE TITLE
Error loading the CMS configuration

### ISSUE THREAD

**Issue by cringer** [netlify/netlify-cms#1628]
**Describe the bug**
Error when loading the admin page.  Error states it cannot find the `collections` in my config.yml but it is there.  See screenshot for full error.

**To Reproduce**
1. Go to 'www.codenexus.xyz/admin' or 'practical-brown-7a0ff6/admin'

**Expected behavior**
netlify-cms should load

**Screenshots**
![image](https://user-images.githubusercontent.com/835448/44304518-7b68ba80-a312-11e8-95f5-7610003bf48e.png)

**Applicable Versions:**
 - Netlify CMS version: 2.0.9
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version Chrome Version 68.0.3440.106 (Though it happens in all browsers)

**CMS configuration**
```
backend:
  name: git-gateway
media_folder: "images/uploads"
collections:
  - name: "posts"
    label: "Posts"
    folder: "source/_posts"
    create: "true"
    slug: "{{slug}}"
    fields:
      -  {label: "Extends", name: "extends", widget: "hidden", default: "_layouts.post"}
      -  {label: "Title", name: "title", widget: "string"}
      -  {label: "Author", name: "author", wiget: "hidden"}
      -  {label: "Date", name: "date", widget: "datetime"}
      -  {label: "Content", name: "section", widget: "hidden", default: "content"}
      -  {label: "Body", name: "body", widget: "markdown"}
```

**Additional context**
Application is using jigsaw as it's static site generator.

**Comment by erquhart** [comment]
Check your deployed config here: http://codenexus.xyz/admin/config.yml

That's all the CMS can see, you'll need to troubleshoot why your deployed config is not the same as your source config. Second file somewhere that's the real source? Builds failing?

**Comment by cringer** [comment]
That was it.  The build_production directory didn't have the latest config.yml as the build was failing on netlify.  I checked the deploy logs and dependencies were failing due to usage of php 5.6 instead of 7.2.
