### ISSUE TITLE
Widget hints do not work

### ISSUE THREAD

**Issue by TonyBogdanov** [netlify/netlify-cms#1636]
**Describe the bug**
Setting the `hint` property of any widget seems to have no effect in the backend UI as described [in the docs](https://www.netlifycms.org/docs/widgets/#common-widget-options). I'm using netlifycms version `2.0.9` ( `^2.0.0` ) from `unpkg`.

**Screenshots**
![image](https://user-images.githubusercontent.com/3586948/44360723-6469ca00-a4c4-11e8-9f27-a4a96949f9d3.png)
![image](https://user-images.githubusercontent.com/3586948/44360742-75b2d680-a4c4-11e8-9956-1edf95ce655c.png)

**Applicable Versions:**

 - Netlify CMS version: 2.0.9.
 - Git provider: GitHub.
 - OS: Windows 10.
 - Browser version: at least Chrome 68 & Edge 42.

**CMS configuration**
https://pastebin.com/b8EMdxXS

**Comment by erquhart** [comment]
That functionality was released in 2.0.10 last night. Had not considered that our docs site is running straight from master and ends up ahead of our released code - we'll have to do something about that.
