### ISSUE TITLE
Docs: Move "Reference" section before "Guides"

### ISSUE THREAD

**Issue by cdschroeder** [netlify/netlify-cms#1641]
**Is your feature request related to a problem? Please describe.**
The "Creating Custom Widgets" page is listed _before_ the actual "Widgets" page. And in general, it seems like the Reference pages will be useful to nearly everyone (while the Guides pages are more for those who want advanced customization).

**Describe the solution you'd like**
I think we should resolve this by switching the "Guides" and "Reference" sections. 

We might also consider renaming the "Guides" section to be less ambiguous (both guides here are related to advanced customization). 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by erquhart** [comment]
Makes sense, agreed.

**Comment by adamayd** [comment]
The change I've made simply swaps Guides and References.  I can re-submit the pull request if a better name for Guides is suggested and agreed upon.

**Comment by tomrutgers** [comment]
In the sketches in https://github.com/netlify/netlify-cms/issues/1692 I called it customization. Would that name cover its content?

**Comment by adamayd** [comment]
@tomrutgers No one else has really commented on this, should I resubmit a PR with Guides renamed to Customization?

**Comment by tomrutgers** [comment]
@verythorough @erquhart thoughts?

**Comment by erquhart** [comment]
I merged it as is before reading this. We can always change it later.
