### ISSUE TITLE
Pulling custom settings from config.yml best practises

### ISSUE THREAD

**Issue by TylerBarnes** [netlify/netlify-cms#1642]
**Is your feature request related to a problem? Please describe.**

I'm trying to figure out the best place to store things like API keys and custom settings. Adding them to config.yml seems to make sense but I'm not really sure what the best practise would be for retrieving these values.

**Describe the solution you'd like**

I'd like a function I can import from netlify-cms and utilize in my react app or maybe a suggestion on best practises for writing this function myself. Or perhaps an entirely different solution.

**Describe alternatives you've considered**

I see config.js in the src folder has a function called loadConfig(). I assume this is only for internal use though and the file wont import anyway.

**Comment by TylerBarnes** [comment]
Hmm, maybe it makes more sense to just make a collection of site settings instead.

**Comment by erquhart** [comment]
Can you provide any examples? Are the API keys related to CMS extensions that you're using?

**Comment by erquhart** [comment]
Closing this as stale, please comment if  there's anything further.
