### ISSUE TITLE
Deploy instructions

### ISSUE THREAD

**Issue by bsde1234** [netlify/netlify-cms#1644]
Please give local deploy instructions

**Comment by tech4him1** [comment]
@bpmottathai We have documentation of how to add Netlify CMS to your site: https://www.netlifycms.org/docs/add-to-your-site/. Can you explain more specifically what you are having problems with?

**Comment by bpmottathai** [comment]
what I did was 
> npm install netlify-cms
Then
>npm run build
it gives

`netlify-cms@2.0.9 build /home/name/node_modules/netlify-cms
> cross-env NODE_ENV=production webpack

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

npm ERR! Linux 4.15.0-20-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! netlify-cms@2.0.9 build: `cross-env NODE_ENV=production webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the netlify-cms@2.0.9 build script 'cross-env NODE_ENV=production webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the netlify-cms package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs netlify-cms
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls netlify-cms
npm ERR! There is likely additional logging output above.

`

**Comment by papandreou** [comment]
The copy of netlify-cms you get when `npm install`ing the module is not suitable for development, because all of the development prerequisites (webpack, test runner etc.) are in the [`devDependencies` section of `package.json`](https://github.com/netlify/netlify-cms/blob/82a6256458f1aea412836c7c6923f83bf6d5a525/package.json#L45-L91), and thus don't get installed in that case.

Try cloning the repository instead, and run `npm install` in it:

```
git clone git@github.com:netlify/netlify-cms
cd netlify-cms
npm install
npm install -g yarn # if you don't have it installed already
npm start
```

**Comment by papandreou** [comment]
Oh, it's being worked on here: https://github.com/netlify/netlify-cms/pull/1645/ -- probably not a coincidence :)

**Comment by bpmottathai** [comment]
Pc freezes here
https://s33.postimg.cc/p46bpbgyn/IMG_20180823_140127.jpg

**Comment by bpmottathai** [comment]
What are the pre requirements for netlify. I have nodejs and npm. Any other like react or something I have warning of unmet peer dependency react immutable and slate

**Comment by tech4him1** [comment]
@bpmottathai Are you trying to develop Netlify CMS or just use it on your website?

**Comment by bpmottathai** [comment]
Sorry as I am noob I can't get you. What I need is a site like app.netlify.com and a netlify template for my own. Is it possible?

**Comment by tech4him1** [comment]
@bpmottathai There are a few things we need to clear up here:

- netlify.com is a website hosting platform. It doesn't have anything to do with the CMS.
- Netlify CMS is an "editor" for your website content. It can be used with or without Netlify.com.
- If you are just trying to create your own website, you don't need to `cd netlify-cms` or run it's build -- it has already been built for you.
- The easiest way to get started on creating a website with Netlify CMS if you don't already have one is to use our starter templates and follow those instructions. Here is a link: https://www.netlifycms.org/docs/start-with-a-template/.

**Comment by bpmottathai** [comment]
I don't need to start a template like hugo with netlify cms. I need netlify cms under my domain

**Comment by tech4him1** [comment]
Do you already have a website? If so, what site generator does it use?

**Comment by bpmottathai** [comment]
The website is for my customers not for me.

**Comment by tech4him1** [comment]
The interface that Netlify CMS provides looks like this: https://cms-demo.netlify.com/

Is that what you are wanting?

**Comment by bpmottathai** [comment]
Yes

**Comment by tech4him1** [comment]
Netlify CMS isn't normally used to edit templates for your site, just the content. If you are creating a website for your customer you will need to create the site first to work with a site generator like Hugo or Jekyll. After you have the site created you can add the CMS interface.

**Comment by tech4him1** [comment]
If I am misunderstanding what you are wanting here, I apologize. You may try asking on the Chat: https://gitter.im/netlify/community

**Comment by bpmottathai** [comment]
If I create a site like https://deploy-preview-1645--netlify-cms-www.netlify.com/ when click deploy to domain will it go to app.netlify.com or app.mydomain.com

**Comment by erezrokah** [comment]
Closing at stale
