### ISSUE TITLE
date widget does not use provided "format" property for input value

### ISSUE THREAD

**Issue by bjrn** [netlify/netlify-cms#1648]
**Describe the bug**
If I set the format property in a date widget to `YYYY-MM-DD`, the field is saved correctly in the file, but in the date input in the CMS, the date is still shown as `MM/DD/YYYY`

**To Reproduce**
Add a field in config.yml like so: 

```
- { label: Publish Date, name: date, widget: date, format: 'YYYY-MM-DD' }
```

**Expected behavior**
the input field should display the value in `YYYY-MM-DD` format

**Applicable Versions:**
 - Netlify CMS version: 2.0.9
 - Git provider: GitHub
 - OS: macOS
 - Browser version: chrome 68

**Comment by bjrn** [comment]
Looks like it might be supported already by `react-datetime` which is powering the date picker?

documentation: [react-datetime: Specify available units](https://www.npmjs.com/package/react-datetime#specify-available-units)

would the solution be to pass down the `dateFormat` prop from config?

**Comment by tech4him1** [comment]
That's what I would do. We should then be able to take out some of our custom formatting logic as well. If you want to create a PR, have at it!

**Comment by bjrn** [comment]
@tech4him1 I've started looking at this, one thing that would simplify the code quite a bit, but also somewhat break the api for config.yml, was if we can separate `format` into `dateFormat` and `timeFormat` for the `DateTimeControl`. The underlying component, [react-datetime](https://www.npmjs.com/package/react-datetime) uses these props already, and <DateTimeControl> is just wrapping <DateControl> and adding the boolean `includeTime`, which basically passes `timeFormat={true}`, ie show timePicker with default locale setting for AM/PM.

AFAIK there is no way in format.js to seperate the date and time format in a format string?

The api change would then be that the `datetime` widget would get separate `dateFormat` and `timeFormat` props instead of just `format`:

```- { name: "datetime", widget: "datetime", dateFormat: "YY-MM-DD", timeFormat: "HH:mm" }```

`date` widget could keep its `format` prop, 
but maybe it's better to change that to `dateFormat` too for constency?

```- {label: "Formatted Date", name: "date_formatted", widget: "date", format: "YYYY-MM-DD"}```

Another option would be to keep **`format`** for `dateFormat` and just add `timeFormat` … 

Would love to hear your thoughts here

**Comment by tech4him1** [comment]
I think adding a `timeFormat` parameter would be fine -- we're trying to combine the Date and DateTime widgets anyway (#1688) at some point. Otherwise, we could just allow setting the date format right now, and allow a time format in a later change.
