### ISSUE TITLE
Use draft.js as rich text editor

### ISSUE THREAD

**Issue by daaain** [netlify/netlify-cms#165]
**- Do you want to request a *feature* or report a *bug*?**

A Feature

**- What is the current behavior?**

Very minimal rich text (Markdown) editor

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

A nice editor experience, something along the lines of Medium

**- Please mention your node.js, and operating system version.**

n.a.

________________

I'm working on a Phenomic based site and I'm very excited about your CMS, can't wait for you to finish the transition to React!

Just came across some really cool libraries and was thinking it would be awesome if you could use these for the rich text editor! So check [this demo](http://bitwiser.in/medium-draft/) out first, it's running [medium-draft](https://github.com/brijeshb42/medium-draft) which is an extension on [draft.js](https://facebook.github.io/draft-js/). Not only these are built in React, but there's already a [plugin](https://github.com/sstur/draft-js-export-markdown) which can output Markdown and [one](https://github.com/sstur/draft-js-import-markdown) which can import.

I'm not sure what your plans are for the editor, but if you used this stack that would be wonderful! N.b. at least from a user's point of view, I haven't developed with them.

**Comment by cassiozen** [comment]
Hi @daaain.

When porting the CMS to React, we started using Draft.js for rich text editor. We also tried slate.js and a bunch of others.

Draft is really cool, but it still misses a few things we think are important (such as a nested document tree, which allows for the usage of tables, in eg.)

In our experience so far, ProseMirror stood out as the best match for the CMS needs ([PR #149](https://github.com/netlify/netlify-cms/pull/149))

Thanks for participating in the discussion. I'm closing this issue, but feel free to reopen if something new appears.
