### ISSUE TITLE
"Publish successful" even though it failed with an HTTP 400

### ISSUE THREAD

**Issue by pheara** [netlify/netlify-cms#1656]
**Describe the bug**

Our setup run's Netlify against a Gitlab server, that we also use for sign-in into Netlify. When editing a post as a user without push-permissions (our master branch was protected as it turns out), the network-tab shows an error 400 ("bad request" with a message like "you cannot push to this branch"). However, the Netlify-GUI was still showing the green "Entry saved"-popup. When reloading the page or navigating back and to the post again, the changes are gone, of course. This is misleading and might lead to lost work.

**To Reproduce**
1. Have a post on a write-protected branch in a repo on a Gitlab server, respectively login with a user without write-permissions
2. Edit that post
3. Click "Publish Now"
4. The green "Entry saved" popup should show up, the network-tab should show an error 400
5. Navigate back and to the post again or reload the page
6. The changes are gone (even though it has said before that they're saved), the misconfiguration of the git requires debugging / reading the network-tab to discover.

**Expected behavior**

The pop-up at step 4 / after publishing to show an error, tell me that the post wasn't saved and that the problem is that my account doesn't have permissions to do so (and tell me to ask my git-admin to make changes to the specific branches write permissions if I want access)

**Applicable Versions:**

 - Netlify CMS version: netlify-cms 2.0.9
 - Git provider: Gitlab 11.1.4 at <https://gitlab.fsinf.at/fsinf/website>
 - OS: Windows 10
 - Browser version 61.0.2

**CMS configuration**
<https://beta.fsinf.at/admin/config.yml>

**Comment by tech4him1** [comment]
> You shouldn't be able to log in without write permissions, need to find out why that's not the case for the GitLab backend.

@m0ru Do the users have write permissions for the rest of the repo, and just not the protected branch?

**Comment by erezrokah** [comment]
Closing as stale
