### ISSUE TITLE
Docs site navigation broken on mobile

### ISSUE THREAD

**Issue by anjackson** [netlify/netlify-cms#1665]
The main navigation menu on the NetlifyCMS docs site appears to be broken on iOS Safari. Once I go to https://www.netlifycms.org/docs/intro I can’t navigate to the other pages.

**Comment by tech4him1** [comment]
@zebapy Mind checking into this?

`this.props.history` is not defined here:
https://github.com/netlify/netlify-cms/blob/f801b192211b1e1953ced969a3093eab9e04e14d/website/src/components/mobile-nav.js#L5

**Comment by zebapy** [comment]
I will today hopefully

**Comment by zebapy** [comment]
I thought a simple swap to `@reach/router`'s `navigate` corrected this (https://github.com/zebapy/netlify-cms/commit/250c242ccc15cd597df8b2c257d1dea5a8ba5a6d) but now I have some other gatsby problem https://github.com/gatsbyjs/gatsby/issues/7643

**Comment by tech4him1** [comment]
@zebapy Is it worth just fixing them in seperate PRs? I think we could go ahead and merge the `navigate` one now. The 404 bug seems to be affecting other links on the page as well, so we can do a seperate PR once that is resolved. Thank you so much for looking into this!

**Comment by raniesantos** [comment]
Possibly related:

The js on the https://www.netlifycms.org/docs/widgets/ page seems to be broken. The buttons at the bottom of the page don't show the widgets.

[![982244e8-d61c-466c-9a5e-27235552fe81.png](https://files.gitter.im/netlify/NetlifyCMS/UCzw/thumb/982244e8-d61c-466c-9a5e-27235552fe81.png)](https://files.gitter.im/netlify/NetlifyCMS/UCzw/982244e8-d61c-466c-9a5e-27235552fe81.png)

**Comment by zebapy** [comment]
@raniesantos I cannot reproduce this on chrome. @tech4him1 did you?

**Comment by zebapy** [comment]
I mocked up (in code) the nav if it was a toggle and normal links (so it works again). Any interest in this? https://github.com/zebapy/netlify-cms/compare/gatsby-v2...zebapy:website-mobile-nav

<img width="460" alt="screenshot 2018-08-26 10 40 29" src="https://user-images.githubusercontent.com/2199845/44629381-7ca27480-a91c-11e8-9d5c-209430c0d85a.png">

**Comment by tech4him1** [comment]
@zebapy I'd be fine with that. It's probably more accessible anyway, since it's a real `nav`.

**Comment by tech4him1** [comment]
@raniesantos I cannot reproduce, can you give me browser details?

**Comment by erquhart** [comment]
Do it.
