### ISSUE TITLE
No matching version found for netlify-cms-backend-github@^2.0.6

### ISSUE THREAD

**Issue by pungggi** [netlify/netlify-cms#1671]
**Describe the bug**
Cannot install netlify-cms anymore

**Screenshots**
![grafik](https://user-images.githubusercontent.com/5635709/44616328-4dbdcd00-a84e-11e8-95ee-4874d81e1490.png)

**Applicable Versions:**
 - Netlify CMS version: 2.0.10
 - Git provider:  BitBucket
 - OS: Windows 10

 - Node.JS version: 8.9.4
 - NPM version: 5.8.0

**Context**
"gatsby": "next",
 "gatsby-plugin-netlify-cms": "^3.0.0-rc.0",

**Comment by pungggi** [comment]
Version 2.0.6 is not published on npm..

https://www.npmjs.com/package/netlify-cms-backend-github?activeTab=versions

**Comment by DavidRayner** [comment]
Same problem for me. Currently the latest version of netlify-cms-backend-github is 2.0.5 and the latest version of netlify-cms-backend-gitlab is 2.0.4 - but netlify-cms 2.0.10 requires later versions

https://github.com/netlify/netlify-cms/blob/cad676dbf3e6e69ee432ce553ca8d34466fd476e/packages/netlify-cms/package.json#L2-L4

https://github.com/netlify/netlify-cms/blob/cad676dbf3e6e69ee432ce553ca8d34466fd476e/packages/netlify-cms/package.json#L27-L28

**Comment by erquhart** [comment]
Publishing seems to not have happened for some packages in yesterday's release. Checking.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by erquhart** [comment]
Manually published `netlify-cms-backend-github@2.0.6` and `netlify-cms-backend-gitlab@2.0.5`. Lerna listed them as successfully published, really not sure what happened. Thanks for opening @pungggi.
