### ISSUE TITLE
TypeError when trying to insert an image in the markdown widget

### ISSUE THREAD

**Issue by jcmnunes** [netlify/netlify-cms#1672]
**Describe the bug**
TypeError when trying to insert an image in the markdown widget (see GIF below).

**To Reproduce**
1. Go to a collection inside the content manager that has a markdown widget in it
2. Click on the plus button and try to insert an image
4. See TypeError in the console

**Expected behavior**
We should be able to add images to the markdown widget

**Screencast**
[![screen capture on 2018-08-25 at 11-01-35](https://user-images.githubusercontent.com/20345941/44618865-31fcfb80-a83b-11e8-993e-aee83e66dada.gif)](https://d.pr/free/i/yBl4u9)

**Applicable Versions:**
 - Netlify CMS version: 2.0.10
 - Git provider: GitHub
 - OS: macOS High Sierra, version 10.13.6
 - Browser version: Chrome Version 68.0.3440.106 

**CMS configuration**
https://github.com/jcmnunes/mcteixeira/blob/master/static/admin/config.yml

**Comment by erquhart** [comment]
Fixed in #1655.
