### ISSUE TITLE
Combine `date` and `datetime` widgets into a single widget

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#1688]
The date and datetime widgets are the same widget, with subtle differences in shared code enacted via boolean flag. They should be combined, I'd say stick with `datetime` for the combined widget to make it more findable via search.

**Comment by bjrn** [comment]
Hi @erquhart, should I go ahead and deprecate the `date` widget in favor of `datetime` in this related PR: #1739 

That would make it a breaking change, but since documentation needs to updated anyways, maybe it's better to do both changes at once?

**Comment by erquhart** [comment]
@bjrn that could work, but maybe in a subsequent PR just for clarity. Deprecating functionality isn't breaking, so it can be done now.
