### ISSUE TITLE
Allow title to be empty if specifying path for the identifier

### ISSUE THREAD

**Issue by markphilpot** [netlify/netlify-cms#1700]
**Describe the bug**
Confluence of assumptions:

- In `backend.js` an identifier is required even if `{{slug}}` is not used in the `config.yml::collections:slug`

- `IDENTIFIER_FIELDS` includes `title` and `path` but searches for `title` first. So if you specify both `title` and `path` as fields, `title` is always preferred.

- For a microblog, the `title` needs to be an empty string in the rss.

In my configuration, I set `title` to an empty string, and `path` to an identifier, but I always get `Collection must have a field name that is a valid entry identifier` error because `title` is empty.

I'm not sure what the right solution is given how the logic is distributed, but ideally it would support `title` as an empty string with `path` specified as the identifier. Or more basically, only require the identifier field if `{{slug}}` is in the `slug` template string

**Comment by erquhart** [comment]
Once #1543 merges, you'll be able to explicitly set `"path"` (or any other field name) as the identifier.

**Comment by erquhart** [comment]
Fixed in #1543.
