### ISSUE TITLE
[Media Library] Option to disable

### ISSUE THREAD

**Issue by martijnvdwoude** [netlify/netlify-cms#1702]
**Is your feature request related to a problem? Please describe.**
I use the CMS to manage text only, and I want to prevent users from uploading media/images.

**Describe the solution you'd like**
I'd like to see an option to disable the Media Library uploading of images altogether.
`media_folder` is now a required configuration, I'd like to see this optional. This could also hide the Media toolbar button and the menu option in the editor UI under the "+" button.

**Comment by erezrokah** [comment]
This should be possible by registering an external media library class and returning `false` in the `enableStandalone` method.
See the uploadcare library as an example: https://github.com/netlify/netlify-cms/blob/60013a06f9dcffb27d2ae48984f93e2b5063985f/packages/netlify-cms-media-library-uploadcare/src/index.js#L168

**Comment by erezrokah** [comment]
Adding a full example:
`cms.js`:
```js
CMS.registerMediaLibrary({
  name: 'disabled',
  init: () => ({ show: () => undefined, enableStandalone: () => false }),
});
```

`config.yml`:
```yaml
media_library:
  name: 'disabled'
```
