### ISSUE TITLE
List widget requires "fields" for one-field, contrary to the offical docs

### ISSUE THREAD

**Issue by idiazroncero** [netlify/netlify-cms#1710]
Hello;

Contrary to [the official docs](https://www.netlifycms.org/docs/widgets/#list), i've realized that single-item list widgets always need the key to be "fields" - not "field" - in order to work

**Describe the bug**
The example for a single-field list widget on the official docs won't work:

````
- label: "Gallery"
  name: "galleryImages"
  widget: "list"
  field:
    - {label: Image, name: image, widget: image}
````

It seems that now it needs to be "fields" instead.

**Expected behavior**
Either recover the "field" value or correct the misleading documentation.

**Screenshots**
<img width="707" alt="captura de pantalla 2018-09-04 a las 14 55 18" src="https://user-images.githubusercontent.com/3958741/45032639-98132b00-b052-11e8-8713-28c31929ca9b.png">

**Applicable Versions:**
 - Netlify CMS version: 2.0.11
 - Git provider: GitHub

**CMS configuration**
(only the two fields shown on screenshot)
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        fields:
          - {label: Image, name: image, widget: image}
      - label: "Gallery2"
        name: "galleryImages2"
        widget: "list"
        field:
          - {label: Image, name: image, widget: image}

**Comment by erquhart** [comment]
@idiazroncero I'm not able to reproduce. Are you certain you're on 2.0.11? You can check the console when the CMS loads to be sure. If so, can you share a repo that reproduces this?

**Comment by idiazroncero** [comment]
It's the same as in #1709 
The repo is https://github.com/idiazroncero/dc-fotografia. It's based on https://github.com/danurbanowicz/eleventy-netlify-boilerplate with pulls the NetlifyCMS from Unpkg.com using:

````
<script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
````

And the console.log prints 2.0.11 as the version.
The error happens both on Chrome and Firefox.

**Comment by idiazroncero** [comment]
You can check the config.yml here:
https://github.com/idiazroncero/dc-fotografia/blob/master/admin/config.yml
Lines 17-34 are the ones to check.

The List widget fields are copied from the docs, that's why they wont' use single quotes for the field definitions as the rest of the file. Nevertheless, I tried everything, even both with and without quotes, to no avail.

**Comment by erquhart** [comment]
Ah! It's because you're defining `field` with a list. Needs to be a map:

```yaml
# wrong
field:
  - {label: Image, name: image, widget: image}

# right
field:
  {label: Image, name: image, widget: image}
```

**Comment by Herohtar** [comment]
@erquhart If that's the case the docs need to be fixed because the example shows it as a list.

**Comment by idiazroncero** [comment]
Awesome, thx
