### ISSUE TITLE
UNPKG link in Quick Start Guide failing HTTP ERROR 503

### ISSUE THREAD

**Issue by mjraval** [netlify/netlify-cms#1711]
**UNPKG link in the Quick Start Guide in admin/index.html for netlify-cms.js give http error 503**

As Suggested at https://www.netlifycms.org/docs/add-to-your-site/

**To Reproduce try to Load the below page in Browser**
```
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Content Manager</title>
</head>
<body>
  <!-- Include the script that builds the page and powers Netlify CMS -->
  <script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
</body>
</html>
```
**I Understand that this is not a bug report nor the right place, but couln't find any other way to bring this to notice, please suggest the needful**

**Updated it to jSDelivr Link for the moment and works fine**
[https://cdn.jsdelivr.net/npm/netlify-cms@2.0.11/dist/netlify-cms.js](https://cdn.jsdelivr.net/npm/netlify-cms@2.0.11/dist/netlify-cms.js)

**Comment by tomrutgers** [comment]
The docs might need an update. The latest version on unpkg works fine as well:
https://unpkg.com/netlify-cms@2.0.11/dist/netlify-cms.js

**Comment by erquhart** [comment]
Yeah we heard about the unpkg issues over the weekend, should be fine now.

**Comment by mjraval** [comment]
Thanks for the reply @tomrutgers and @erquhart . Sent pull request #1713  after adding a comment mentioning that either jsDelivr of unpkg can be used.
