### ISSUE TITLE
TypeError: e.get is not a function using netlify cms admin

### ISSUE THREAD

**Issue by joshicraft** [netlify/netlify-cms#1714]
**Describe the bug**
Netlify CMS is giving the error when i try to open a file in the CMS

**To Reproduce**
Steps to reproduce the behavior. For example:
1. Log into netlify cms
2. Open the projects or services page
3. Get the error

**Expected behavior**
I get a page saying... 

"Sorry!
There's been an error - please report it!

TypeError: e.get is not a function"

![netlify cms](https://user-images.githubusercontent.com/43000040/45093106-86717680-b16b-11e8-92c2-2e429808db8d.PNG)

**Applicable Versions:**

 - Netlify CMS version:  2.0
 - Git provider: GitHub
 - OS: Windows 7

 - Node.JS version: >= 4.0

**CMS configuration**

[config.yaml](https://github.com/joshicraft/cert-weld/blob/master/admin/config.yml)

**Additional context**

[package.json](https://github.com/joshicraft/cert-weld/blob/master/src/lang/en/Views/Projects.json)

[services.json](https://github.com/joshicraft/cert-weld/blob/master/src/lang/en/Views/Services.json)

**Comment by tomrutgers** [comment]
The config yaml identation for all your list widgets isn't deep enough

wrong:
```
fields:
- {label: Heading 1, name: heading1, widget: string}
- {label: Link, name: to, widget: string}
```

right:
```
fields:
  - {label: Heading 1, name: heading1, widget: string}
  - {label: Link, name: to, widget: string}
```

**Comment by joshicraft** [comment]
@tomrutgers I fixed the indentation but this didn't resolve the issue.

**Comment by joshicraft** [comment]
There seems to be an issue when trying to write the scheema for these lines...

    - label: Images
      name: images
      widget: list
      fields:
        - {label: Image, widget: string}

With the following JSON format...

    "images": ["c", "b"],

How do I write this properly? I haven't figured it out.

**Comment by tech4him1** [comment]
@joshicraft In the list widget config, change `fields` (plural) to `field` (singular).

**Comment by joshicraft** [comment]
@Caleb Thanks! that solved the problem for me :)
