### ISSUE TITLE
CMS example link goes to Page not found

### ISSUE THREAD

**Issue by laurajodz** [netlify/netlify-cms#1725]
**Describe the bug**
https://www.cupofdata.com/blog goes to Page not found

**To Reproduce**

Steps to reproduce the behavior. For example:
1. Go to https://www.netlifycms.org/docs/examples/
2. Click on Cup Of Data (https://www.cupofdata.com/blog)
3. See error Page not found

**Comment by tomrutgers** [comment]
In the meantime I opened up a pull request to remove it from the examples: https://github.com/netlify/netlify-cms/pull/1726

**Comment by laurajodz** [comment]
thank you both! my goal was to get it removed from our site, sorry that was not very clear.

**Comment by erquhart** [comment]
I reached out to them, it's just temporary. We'll leave this open but let's hold off on removing for now.

**Comment by tech4him1** [comment]
@jgwerner Let us know when the blog is back up so we can re-add it to the demo site!

**Comment by erquhart** [comment]
Still down, closing.
