### ISSUE TITLE
Unable to save blog post when using list

### ISSUE THREAD

**Issue by amykapernick** [netlify/netlify-cms#1749]
**Describe the bug**
I'm unable to save blog posts based on my current config, it's giving an error and the save bar just stalls

**To Reproduce**
Happens every time, repo is https://github.com/amykapernick/amygoestoperth/tree/netlify-gatsby/ and it's happening on local and prod

**Expected behavior**
The file to save

**Screenshots**
![image](https://user-images.githubusercontent.com/15953185/45592851-7481a600-b9ab-11e8-8f8e-c538a4632aef.png)
![image](https://user-images.githubusercontent.com/15953185/45592854-7cd9e100-b9ab-11e8-9f63-02265d899cc5.png)

**Applicable Versions:**

 - Netlify CMS version: 2.1.1
 - Git provider: GitHUb
 - OS: Windows 10
 - Browser version Version 68.0.3440.106 (Official Build) (64-bit)

 - Node.JS version: 10.7.0
 - NPM: 6.1.0

**CMS configuration**
```collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    editor:
      preview: false
    fields:
      - { name: publishDate, label: Date, widget: date }
      - { name: title, label: Title }
      - name: body
        label: Body
        widget: list
        fields:
          - {name: content, label: Content, widget: markdown}```


**Additional context**
Works fine when not using the list, but wanting to make the body repeatable fields

**Comment by erquhart** [comment]
`body` is a special field name whose value is output below the frontmatter, so the list widget won't work there.

If you want repeatable markdown fields, just use a different field name and update your templates accordingly.
