### ISSUE TITLE
image not found after refresh

### ISSUE THREAD

**Issue by ciokan** [netlify/netlify-cms#1750]
I have an image field. If I upload and click to `Choose selected` it looks fine with thumbnail and all. If I refresh the page and Choose the same image it tries to load it from a relative path which leaves me with a 404:

![screenshot from 2018-09-16 19-15-42](https://user-images.githubusercontent.com/474948/45598446-f80bb900-b9e4-11e8-8c90-0cf997f29220.png)

Media config:

```
...
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
...
```

This is how the img looks like after refresh:

`<img src="/images/uploads/screenshot-from-2018-09-11-19-55-10.png" class="css-mnkk9b e1awjdnj1">`

Any ideas?

**Comment by talves** [comment]
@ciokan the image has not been deployed to your site until the deploy finishes. Could this be the case in this instance?

**Comment by ciokan** [comment]
I'm on localhost trying this in netlify cms. I can see the image being pushed in the repo when I upload so it's there...on the remote but I don't understand why it sends a relative path when I select images for widgets.

**Comment by tech4him1** [comment]
I'm assuming this could be fixed along with https://github.com/netlify/netlify-cms/issues/990. Any objections?

**Comment by erquhart** [comment]
Thought we were already using the API, weird. Commenting on #990 for more info.

**Comment by johtso** [comment]
Definitely feel the images should be hotlinked from GitHub for the thumbnail. Otherwise the images will be broken if the image isn't currently being published on your website..

**Comment by erezrokah** [comment]
Related https://github.com/netlify/netlify-cms/pull/2817

**Comment by andrewmmc** [comment]
May I know if it's fixed? I am still getting image from public website instead of git repository, which caused images broken in preview and image widget.

ps. Works properly in Media modal.

Version: netlify-cms-app 2.12.12
