### ISSUE TITLE
Components added via `registerEditorComponent` lose their events

### ISSUE THREAD

**Issue by ciokan** [netlify/netlify-cms#1756]
**Describe the bug**
Components added via `registerEditorComponent` lose their events (`onClick` was tested) on the preview panel. 

**To Reproduce**

Load this editor component and click the yellow box. It has an `alert` set for `onClick` but it never fires.

```
import React from 'react';

class Test extends React.Component {
	render() {
		return <div style={{
			background: 'yellow',
			width: 200,
			height: 200
		}} onClick={() => alert('yellow')}/>
	}
}

const TestEditorComponent = {
	id: 'test-events',
	label: 'Test events',
	fields: [],
	pattern: /{"widget":"test-events"}/,

	fromBlock: match => {
		return {widget: "test-events"};
	},

	toBlock: obj => {
		return `{"widget":"test-events"}`;
	},

	toPreview: obj => {
		return <Test/>;
	},
};

export default TestEditorComponent;
```

**Expected behavior**

An alert should pop.

**Comment by ciokan** [comment]
It seems that components are rendered using `renderToString` which causes them to lose all hooks: https://github.com/netlify/netlify-cms/blob/f801b192211b1e1953ced969a3093eab9e04e14d/packages/netlify-cms-widget-markdown/src/serializers/remarkRehypeShortcodes.js#L41

**Comment by erquhart** [comment]
Yeah they're really not meant to be interactive components that way, the widgets used for the individual fields can be interactive, though.
