### ISSUE TITLE
Cpanel and gitlab don't accept auto generated netlify domain

### ISSUE THREAD

**Issue by alexgmuir** [netlify/netlify-cms#1761]
**Describe the bug**

Netlify auto generated the following domain which does resolve in a browser however both cpanel and gitlab are not accepting it.

This is the autogenereated domain
http://youthful-swanson-43b845.netlify.com

Error From Gitlab:
The form contains the following error:
Auto devops domain contains invalid characters (valid characters: [a-z0-9\-])

Error from cpanel cname record:
Must specify a valid IPv4 address

**To Reproduce**

using http://youthful-swanson-43b845.netlify.com

Attempt to create auto deploy in gitlab
Attempt to create cname record in cpanel 

**Expected behavior**

no errors

**Screenshots**

![image](https://user-images.githubusercontent.com/6494943/45745898-691fbc00-bbf1-11e8-9176-6799a60febfc.png)
![image](https://user-images.githubusercontent.com/6494943/45745915-750b7e00-bbf1-11e8-914a-89579074898a.png)

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by erquhart** [comment]
> valid characters: [a-z0-9-]

Sounds like they want you to leave off the protocol. Try dropping the "http://" and just entering "youthful-swanson-43b845.netlify.com".

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
