### ISSUE TITLE
GitHub oauth popup doesn't allow scrolling in Firefox

### ISSUE THREAD

**Issue by Herohtar** [netlify/netlify-cms#1765]
When using the GitHub authentication backend, the popup window that displays the application authorization page doesn't allow scrolling when using Firefox. It seems to work fine in Chrome and Edge.

**To Reproduce**
1. Open the CMS admin page on a site configured to use the GitHub backend
2. Click "Login with GitHub"
3. Try to scroll the authorization request page

**Expected behavior**
Window should allow scrolling so users can see the information at the bottom.

**Screenshots**

No scrollbar in Firefox:
![image](https://user-images.githubusercontent.com/10427164/45921467-e9f1e880-be7b-11e8-8f65-0dd751f94e14.png)

Chrome has a scrollbar:
![image](https://user-images.githubusercontent.com/10427164/45921521-c7ac9a80-be7c-11e8-944b-45c56a2d5fce.png)

**Applicable Versions:**

 - Netlify CMS version: 2.1.2
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version: Firefox 63.0b8 (64-bit)

**Comment by tech4him1** [comment]
I'm wondering if instead of `toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no`, we can just do `scrollbars=yes`, since things default to `no`.

**Comment by tech4him1** [comment]
Looks like `scrollbars` is an exception that defaults to `yes` in most browsers, so we should be able to do just width and height.

Testing with just `width, height`:
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari

**Comment by tech4him1** [comment]
@Herohtar Thanks for reporting!

**Comment by cfjedimaster** [comment]
FYI, I'm running into this today at this site - https://ragequit.tips/. This site isn't quite released yet, but using latest Firefox, I had the same issue. I couldn't accept because the popup wouldn't let me scroll down.

**Comment by barthc** [comment]
Scroll works for me on latest firefox ( 70.0.1)

**Comment by cfjedimaster** [comment]
Latest is 71.0.

**Comment by erezrokah** [comment]
I can see the scroll bar on https://ragequit.tips/ with Firefox 71.0 (MacOS).
![image](https://user-images.githubusercontent.com/26760571/70124002-7ef59180-167c-11ea-9839-24980d2dc633.png)

**Comment by cfjedimaster** [comment]
I'm on Windows - maybe it's OS specific?

**Comment by erezrokah** [comment]
You could try the suggestion here: https://support.mozilla.org/bm/questions/976345
