### ISSUE TITLE
Distribution build is not ES5-compatible

### ISSUE THREAD

**Issue by travellingprog** [netlify/netlify-cms#1771]
**Describe the bug**

I've found that importing NetlifyCMS has a module causes Create React App's `build` script to fail, and the error point to this link: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify . Essentially, it seems that the module is not EcmaScript 5 compatible.

**To Reproduce**

1. Add `import CMS from 'netlify-cms'` into a JS file of a Create React App project.
2. Run the build script script (e.g. `npm run build` or `yarn build`).
3. The following error will show up:

```sh
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/netlify-cms/dist/netlify-cms.js:14:23390 

Read more here: http://bit.ly/2tRViJ9
```

**Expected behavior**

The Create React App should compile

**Applicable Versions:**

Netlify CMS versions 2.1.2 and 2.0.0 have this issue. Version 1.9.3 does not have this issue.

**CMS configuration**

**config.js** (passing in the config manually)

```js
export default {
  backend: {
    name: 'git-gateway',
    branch: 'netlify'
  },
  media_folder: 'public/images/uploads',
  public_folder: '/images/uploads',

  /* Collections */
  collections: [
    {
      name: 'posts',
      label: 'Post',
      description: 'A post about music',
      folder: 'public/content/posts',
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}',
      create: true,
      fields: [
        {
          label: 'Title',
          name: 'title',
          widget: 'string',
          tagname: 'h1'
        },
        {
          label: 'Body',
          name: 'body',
          widget: 'markdown'
        }
      ]
    }
  ]
}
```

**Additional context**

I looked into the compiled build that is imported (netlify-cms/dist/netlify-cms.js) includes template literals, which I believe is causing the problem. @tech4him1 has confirmed this problem and found that the transpilation broken when the switch to Babel 7 was made.

**Comment by tech4him1** [comment]
@erquhart I'm thinking since we have been outputting a non-transpiled build so far, and that is what CDN users have been using, we should start outputting two versions -- `cms.js` and `cms.es5.js` (transpiled). The transpiled version would be the default for Node.JS, but the regular `cms.js` would continue to be the same.

**Comment by travellingprog** [comment]
I know this is kind of tangential, but it would be good to add somewhere in the documentation the browser support, especially of the CDN version. It could be just a simple link to a Babel config file in the repo. For me, aside from a comment on an old issue, I have no idea where in the repo to find the browser support.

**Comment by tech4him1** [comment]
For sure, feel free to create a PR for that if you'd like. Support is these browsers, with supported versions determined at CMS publish time: https://github.com/netlify/netlify-cms/blob/68ef4e90b0bfbafea06cc52499aad569853a5d1a/package.json#L37-L41

**Comment by tech4him1** [comment]
I'm not thinking the NPM package should actually bundle dependencies -- it should still have the `require` calls left in. Maybe we should do four builds:
- bundled, ES5
- bundled, untranspiled
- CJS/unbundled, ES5
- CJS/unbundles, untranspiled

**Comment by talves** [comment]
@travellingprog can you upgrade `react-scripts@^2.0.0` and see if that error gets resolved. you can target the same `browserslist` as the cms.

`package.json`

      "browserslist": [
        "last 2 Chrome versions",
        "last 2 Opera versions",
        "last 2 Firefox versions",
        "last 2 Edge versions",
        "last 2 Safari versions",
        "last 2 iOS versions",
        "last 2 ChromeAndroid versions"
      ]

**Comment by travellingprog** [comment]
yeah, that worked!  I tried it with react-scripts 2.0.2.

Thanks

**Comment by talves** [comment]
@travellingprog Great. I will close this for now. 👍
