### ISSUE TITLE
Add possibility to include image title in editor

### ISSUE THREAD

**Issue by pdrvsky** [netlify/netlify-cms#1775]
**Is your feature request related to a problem? Please describe.**
Currently, there's no option to take advantage of markdowns image title feature. It is especially important, while preparing the website content for SEO optimization.

**Describe the solution you'd like**
Improve editor-component-image to parse image title syntax (i.e. `![alt](image_src "title")`) and allow user to edit its content in the WYSWIG editor.

**Describe alternatives you've considered**
I've recently tried to make a custom widget which supports title attribute, but the regex pattern used in interal implementation is more generic and overwrites it, thus it's not possible to fullfill the request without the edition of cms' source code.

**Comment by erquhart** [comment]
Agreed 👍

**Comment by zvinless** [comment]
I started looking into this and ran into an issue where the title gets stripped from the AST node text, e.g.:
```markdown
![alt](/path.png "title")
```
gives me
```markdown
![alt(/path.png)
```
with no `"title"` text. It works fine without the quotes, but that's obviously not the right syntax. I'm not really familiar with everything that might be going on. Is it related the cause of other editor component issues (#1001, #1044)?

**Comment by erquhart** [comment]
Somewhere in our maze of serializers no doubt. If you start in `packages/netlify-cms-widget-markdown/serializers/index.js` and follow the yellow brick road, that should get you close.

There's a `remarkImagesToText` serializer that is definitely stripping out titles and may be the sole perpetrator here.
