### ISSUE TITLE
Login to /admin/ does not work with GitLab identity backend

### ISSUE THREAD

**Issue by macau23** [netlify/netlify-cms#1779]
**Describe the bug**
Deployed one-click-hugo-cms to GitLab (not GitHub), everything went well.
The Identity config already looked correct (enabled, backend gitlab with token, e-mail confirmation). However I cannot login using GitLab. Nothing happens, I keep returning to the /admin/ page again and again. If I create a new normal user and login it works.

**To Reproduce**
1. Go to https://github.com/netlify-templates/one-click-hugo-cms
2. Click on Deploy to Netlify
3. Scroll down to Prefer a different provider? You can also connect to GitLab. Click.
4. Follow the flow.
5. Check e-mail and click anything that needs confirming.
6. After deployment go to /admin/ and try to log in.

**Expected behavior**
Login works.

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by macau23** [comment]
Tested with Chrome and Firefox.

**Comment by tomrutgers** [comment]
Your config still has `git-gateway` set as a backend. Try changing it to `gitlab`. Have a look at the authentication & backends section in the docs for available options and configuration: https://www.netlifycms.org/docs/authentication-backends/#gitlab-backend

**Comment by tomrutgers** [comment]
Can't reproduce in firefox, the login works just fine when I deploy the starter to GitLab. Maybe try clearing your cache, or start fresh?

**Comment by tech4him1** [comment]
@macau23 Also, have you tried creating a regular user, *and then* logging in with GitLab?

**Comment by macau23** [comment]
@tech4him1 Let me try for this current problem.

**Comment by tech4him1** [comment]
yeah, `one-click-hugo-cms` is pretty much a successor to `kaldi-hugo-cms-template`. @erquhart Are you guys maintaining both, or should the old one be archived?

**Comment by erquhart** [comment]
Archived kaldi, thanks for the reminder.

@macau23 this should not be an issue with [one-click-hugo-cms](https://github.com/netlify-templates/one-click-hugo-cms).
