### ISSUE TITLE
Datetime widget zIndex and/or style broken

### ISSUE THREAD

**Issue by ciokan** [netlify/netlify-cms#1787]
I have this field as part of an editor component that contains a datetime. When I click to select the date, the widget appears under the rest of content (z-index?) and seems to have a bad style applied (I can see a separate widget lurking underneath).

![screenshot from 2018-10-03 11-25-36](https://user-images.githubusercontent.com/474948/46399070-6d72cb80-c6ff-11e8-950b-094be74e7f61.png)

I can't select a date unless I add many blank lines to accommodate its vertical.

**Comment by erquhart** [comment]
Can you either:

1. Fork [this codepen](https://codepen.io/erquhart/pen/dgNEYo) and add your component to reproduce, or

2. Provide the source of your editor component
