### ISSUE TITLE
Limit the choice of block level component in the Markdown editor

### ISSUE THREAD

**Issue by baptLesta** [netlify/netlify-cms#1788]
Is it possible to customize the editor ui bar of the markdown widget to limit the choice of block level component in the Markdown editor?

I know you can do:
` -{label: "Markdown", name: "markdown", widget: "markdown", buttons: ["bold", "italic"]`

But, it will be perfect to have the possibility to add:
`
-{label: "Markdown", name: "markdown", widget: "markdown", components: ["youtube", "image", "vimeo"]}
`

**Comment by tech4him1** [comment]
@baptLesta Just to make sure I'm understanding you correctly -- You are suggesting that after you have adding all the editor components that you want by using `CMS.registerEditorComponent()`, you would be able to turn some of those components off for specific markdown widgets?

**Comment by baptLesta** [comment]
Exactly !

**Comment by erquhart** [comment]
Yeah, this makes sense.

**Comment by erquhart** [comment]
If anyone is looking for a starting point, this is a _great_ first issue.

**Comment by sddaniels** [comment]
Apologies for my dupe search not being extensive enough! I may pick this one up.

**Comment by erquhart** [comment]
No problem! Here's a good starting point - it's the line where we pass the `buttons` from the markdown field configuration to the toolbar to customize which buttons appear (bold, italic, etc). The `field` object is an Immutable Map of the current field configuration. `components` would probably be a good config key for this.

**Comment by sddaniels** [comment]
Thanks! I briefly looked through the button customization PR also, so hopefully I'm GTG.
