### ISSUE TITLE
Build failing on Netlify

### ISSUE THREAD

**Issue by klintron** [netlify/netlify-cms#1803]
**Describe the bug**

I don't know if this is the right place to report this (I'm not sure if this is an issue with Netlify CMS, Netlify, Gatsby, or the Gatsby + Netlify CMS Starter), but I can't build my new Netlify CMS site using the Gatsby template. The initial build work, as did a couple more, but now every time I try to build I get a slew of error messages. I Googled some of them and some of them have been discussed in various places, but I don't know which one is actually causing the build to fail.

**To Reproduce**

1. Make a change in Netlify CMS or press "Trigger Deploy" in Netlify
2. Login to Netlify and view errors

**Expected behavior**

The site will build without throwing a slew of errors.

**Screenshots**

In lieu of screenshots, please find error log below.

**Applicable Versions:**

 - Netlify CMS version: 2.1.2
 - GitHub
 - OS: My OS: MacOS High Sierra. No idea what Netlify is running, which I assume is where the errors are happening.
 - Browser version My browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit).

 - Node.JS version: This is done on Netlify's side, right?

**CMS configuration**
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  
  - name: "Games"
    label: "Games"
    folder: "src/pages/games"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

**Additional context**

Here's the error log:

4:53:21 PM: Build ready to start
4:53:22 PM: build-image version: 42bca793ccd33055023c56c4ca8510463a56d317
4:53:22 PM: buildbot version: 6bab8b64bbd90091082af19fedf16bf73d502e5e
4:53:22 PM: Fetching cached dependencies
4:53:22 PM: Starting to download cache of 106.6MB
4:53:23 PM: Finished downloading cache in 871.895608ms
4:53:23 PM: Starting to extract cache
4:53:27 PM: Finished extracting cache in 3.466807641s
4:53:27 PM: Finished fetching cache in 4.410022703s
4:53:27 PM: Starting to prepare the repo for build
4:53:27 PM: Preparing Git Reference refs/heads/master
4:53:28 PM: Found netlify.toml. Overriding site configuration
4:53:28 PM: Different publish path detected, going to use the one specified in the toml file: 'public' versus '/' in the site
4:53:28 PM: Different build command detected, going to use the one specified in the toml file: 'npm run build' versus '' in the site
4:53:28 PM: Starting build script
4:53:28 PM: Installing dependencies
4:53:28 PM: Started restoring cached node version
4:53:30 PM: Finished restoring cached node version
4:53:31 PM: v8.12.0 is already installed.
4:53:31 PM: Now using node v8.12.0 (npm v6.4.1)
4:53:31 PM: Attempting ruby version 2.3.6, read from environment
4:53:32 PM: Using ruby version 2.3.6
4:53:33 PM: Using PHP version 5.6
4:53:33 PM: Started restoring cached node modules
4:53:33 PM: Finished restoring cached node modules
4:53:33 PM: Started restoring cached yarn cache
4:53:33 PM: Finished restoring cached yarn cache
4:53:33 PM: Installing NPM modules using Yarn version 1.3.2
4:53:34 PM: yarn install v1.3.2
4:53:34 PM: [1/4] Resolving packages...
4:53:35 PM: success Already up-to-date.
4:53:35 PM: Done in 1.22s.
4:53:35 PM: NPM modules installed using Yarn
4:53:36 PM: Started restoring cached go cache
4:53:36 PM: Finished restoring cached go cache
4:53:36 PM: unset GOOS;
4:53:36 PM: unset GOARCH;
4:53:36 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.10.linux.amd64';
4:53:36 PM: export PATH="/opt/buildhome/.gimme/versions/go1.10.linux.amd64/bin:${PATH}";
4:53:36 PM: go version >&2;
4:53:36 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.10.linux.amd64.env';
4:53:36 PM: go version go1.10 linux/amd64
4:53:36 PM: Installing missing commands
4:53:36 PM: Verify run directory
4:53:36 PM: Executing user command: npm run build
4:53:36 PM: > gatsby-starter-netlify-cms@1.1.3 build /opt/build/repo
4:53:36 PM: > npm run clean && gatsby build
4:53:36 PM: > gatsby-starter-netlify-cms@1.1.3 clean /opt/build/repo
4:53:36 PM: > rimraf .cache public
4:53:39 PM: success open and validate gatsby-config — 0.007 s
4:53:39 PM: success load plugins — 0.219 s
4:53:40 PM: success onPreInit — 0.836 s
4:53:40 PM: success delete html and css files from previous builds — 0.084 s
4:53:40 PM: success initialize cache — 0.009 s
4:53:40 PM: success copy gatsby files — 0.014 s
4:53:40 PM: success onPreBootstrap — 0.003 s
4:53:40 PM: success source and transform nodes — 0.096 s
4:53:40 PM: success building schema — 0.255 s
4:53:40 PM: success createPages — 0.053 s
4:53:40 PM: success createPagesStatefully — 0.025 s
4:53:40 PM: success onPreExtractQueries — 0.001 s
4:53:40 PM: success update schema — 0.142 s
4:53:40 PM: error GraphQL Error Unknown field `image` on type `frontmatter_2`
4:53:40 PM:   file: /opt/build/repo/src/templates/product-page.js
4:53:40 PM:    1 |
4:53:40 PM:    2 |   query ProductPage($id: String!) {
4:53:41 PM:    3 |     markdownRemark(id: { eq: $id }) {
4:53:41 PM:    4 |       frontmatter {
4:53:41 PM:    5 |         title
4:53:41 PM: >  6 |         image
4:53:41 PM:      |         ^
4:53:41 PM:    7 |         heading
4:53:41 PM:    8 |         description
4:53:41 PM:    9 |         intro {
4:53:41 PM:   10 |           blurbs {
4:53:41 PM:   11 |             image
4:53:41 PM:   12 |             text
4:53:41 PM:   13 |           }
4:53:41 PM:   14 |           heading
4:53:41 PM:   15 |           description
4:53:41 PM:   16 |         }
4:53:41 PM: npm ERR! code ELIFECYCLE
4:53:41 PM: npm ERR! errno 1
4:53:41 PM: npm ERR! gatsby-starter-netlify-cms@1.1.3 build: `npm run clean && gatsby build`
4:53:41 PM: npm ERR! Exit status 1
4:53:41 PM: npm ERR!
4:53:41 PM: npm ERR! Failed at the gatsby-starter-netlify-cms@1.1.3 build script.
4:53:41 PM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
4:53:41 PM: npm ERR! A complete log of this run can be found in:
4:53:41 PM: npm ERR!     /opt/buildhome/.npm/_logs/2018-10-09T23_53_40_996Z-debug.log
4:53:41 PM: Caching artifacts
4:53:41 PM: Started saving node modules
4:53:41 PM: Finished saving node modules
4:53:41 PM: Started saving yarn cache
4:53:41 PM: Finished saving yarn cache
4:53:41 PM: Started saving pip cache
4:53:41 PM: Finished saving pip cache
4:53:41 PM: Started saving emacs cask dependencies
4:53:41 PM: Finished saving emacs cask dependencies
4:53:41 PM: Started saving maven dependencies
4:53:41 PM: Finished saving maven dependencies
4:53:41 PM: Started saving boot dependencies
4:53:41 PM: Finished saving boot dependencies
4:53:41 PM: Started saving go dependencies
4:53:41 PM: Finished saving go dependencies
4:53:41 PM: Error running command: Build script returned non-zero exit code: 1
4:53:41 PM: Failing build: Failed to build site
4:53:41 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
4:53:41 PM: Finished processing build request in 19.209158665s

And here are the errors from Chrome's JavaScript console:

netlify-cms 2.1.2
/.netlify/git/github/contents/src/pages/products/index.md?ts=1539132874341&ref=master:1 Failed to load resource: the server responded with a status of 404 ()
netlify-cms.js:38 failed to load file from GitHub: src/pages/products/index.md
api.readFile.then.catch @ netlify-cms.js:38
netlify-cms.js:178 [Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M71, around December 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.
Hi @ netlify-cms.js:178
4index.js:121 Uncaught ReferenceError: ___loader is not defined
    at index.js:121
    at index.js:51
    at Array.forEach (<anonymous>)
    at IntersectionObserver.<anonymous> (index.js:44)

**Comment by erquhart** [comment]
I believe that means none of your product content files have an `image` field in the frontmatter, but you've defined that field in your graphql query. You just need one of your product content files to have that field.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by klintron** [comment]
Hm, the thing is I deleted the Products page and removed it from the config file. But some of the image files might still be around. Maybe I just need to delete them?

**Comment by klintron** [comment]
OK, got it figured out. Had to delete the product page template. I would expect deleting a page from within the CMS to not cause the build process to break, or if breakage is unavoidable to at least throw a more understandable error message. Should I open a separate bug report for that?

**Comment by talves** [comment]
Unfortunately, we would not be able to help with an issue with a Netlify build. That would need to be reported to Netlify support at https://netlify.com/support

If you think it is a NetlifyCMS app issue, definitely feel free to create a new issue.
