### ISSUE TITLE
Not possible to set `editorial_mode` to `simple`

### ISSUE THREAD

**Issue by bjrn** [netlify/netlify-cms#1811]
**Describe the bug**

I normally have `publish_mode` set to `"editorial_workflow"`, but for local editing I've set up a file-system API. I'm using the `CMS_ENV` variable  in cms.js to provide config overrides during development, and thus I needed to unset the editorial_workflow. I tried setting `publish_mode: null` and `undefined`, found that the default was `simple` in the source code, but neither works.

**To Reproduce**
1. in config.yml, add a line `publish_mode: simple`. 
2. refresh the admin page

**Expected behavior**
Admin should run without editorial workflow enabled. Instead, the following error is shown:

```
Config Errors:
'publish_mode' should be equal to one of the allowed values
Check your config.yml file.
```

**Comment by talves** [comment]
@bjrn did you try to remove the line or comment. Not saying that should be the solution, just want to make sure there is a workaround for now.

**Comment by bjrn** [comment]
You mean in the config.yml? Yes, if I don't want `editorial_workflow`, it works fine if I simply do not add a `publish_mode:` line in config.yml … so there's definitely a workaround (my use case is probably rather uncommon).

If you mean commenting the line out in configSchema.js, no I haven't yet, but will have a go. 

Also, in a related note (as I started out trying to override this way instead `CMS_ENV`), it seems as if there might be a race condition when one wants to provide custom config during the initialisation (eg. passing in the config object in cms.js); if I already have a file located at `admin/config.yml`, it uses that for initialisation, prior to reading my config block, thus ignoring what I pass in. Haven't spend any time debugging it yet though

**Comment by Benaiah** [comment]
@bjrn looks like you're right on - the `publish_mode` should allow `simple` as a value, and adding `'simple'` to that schema is the correct fix (just double-checked). Creating a PR now.

**Comment by Brondahl** [comment]
Ah hah! I've just hit this!

Note that (I think) it's a much bigger problem if you're using manual initialisation. If I leave `publish_mode` undefined in both the `config.yml` and the init code, then it shouts at me with that error.
