### ISSUE TITLE
When trying to login to self-hosted gitlab, it just shows yellow box with [object Object] 

### ISSUE THREAD

**Issue by jakubtomas108** [netlify/netlify-cms#1819]
Hello, 

Few hours ago I started using Netlify CMS on our sites, implicitly connected to our self-hosted gitlab and it worked correctly. Recently I made pull and rebase and now it dont want to let me log in. All configurations are still the same as few hours ago. But now, when I click to 'Login with GitLab' it just show a yellow box with text '[object Object]' and nothing more. I tried to rebuild the sites a few times, also tried to make a new 'Application' on my gitlab account and connect the CMS to it, but still returns the [object Object] error and no login. Any hint please? 

After checking networks tab in dev tools, it shows {error: "404 Not Found"} as one of the response so this will be probably the [object Object] what is in the yellow box. But still... Why it worked few hours ago. I also tried to connect the CMS to other repos which we have, but still the same.

**Comment by erquhart** [comment]
Did you update Netlify CMS between when it worked and when it didn't? What version are you using?
