### ISSUE TITLE
Refactor library build process to output CommonJS build, ES module build, and a bundle

### ISSUE THREAD

**Issue by GabeMedrash** [netlify/netlify-cms#1829]
**Is your feature request related to a problem? Please describe.**

NetlifyCMS is currently only available as a UMD bundle. This works great when included via a script tag, but quickly turns funky when working with it in an application that has its own build/bundling process. For example, it leads to dependency bloat and, because the NetlifyCMS bundle is pre-minified, it must be specifically excluded from further minification if minification is a part of a user's build process. This has additional ramifications for source mapping code in development and for code splitting.

**Describe the solution you'd like**

A common JS library pattern for libraries that can be both imported in source code or required via a script tag is to output the library in three build formats: a CommonJS build, an ES module build, and a bundle. Currently, NetlifyCMS is only outputting a bundle (UMD, yes, but still a bundle). This makes using NetlifyCMS in imports difficult. For example, it requires special casing the NetlifyCMS package in a build process that involves minification.

My suggestion is to update the build process to output all three build formats. At a high level, that means:

*CommonJS*:
In a CommonJS build, you use your transpiler to transpile your source code fully to your transpile target. Often, this means something along the lines of `babel src –out-dir lib`, where (if using `babel-env`) `modules` is set to “commonjs”.
The target use case here is an application that imports NetlifyCMS but does not use a module bundler that understands ES import syntax (e.g., an older version of Webpack). Syntactically, this looks like: `var netlifyCMS = require(“netlify-cms”);`

*ES module*:
An ES module build is very similar to a commonjs build, but differs in that everything except import statements are transpiled down to the transpile target. This enables bundlers like Webpack and Rollup to statically analyze imports and only import chunks of code that are actually used (known as “tree shaking”). Often, this looks like `babel src –out-dir es`, where (again, assuming usage of `babel-env`), `modules` is set to false.
The target use case here is an application that imports NetlifyCMS that uses a module bundler that does understand ES import syntax (e.g., Webpack >= 2, Rollup). Syntactically, this looks like: `import netlifyCMS from “netlify-cms”`.

*Bundle*:
This is what NetlifyCMS is already doing; it bundles the code along with all of its dependencies, excluding peer dependencies. While a UMD bundle can be imported by a tool like Webpack, my understanding (though could be wrong) is that the bundle is not a candidate for static import analysis and can lead to dependency bloat if, for example, an application that depends on NetlifyCMS uses overlapping dependencies, like say, lodash or React. My opinion is that bundles are best used as browser targets.

Lastly, following what seem to have become more or less community conventions, the above build formats should map to the following `package.json` fields:
```
{
  `main`: `lib/index.js`,   // CommonJS build
  `module`: `es/index.js`  // ES module build
  `browser`: `dist/netlify-cms-bundle.js`  // Bundle
}
```

**Describe alternatives you've considered**

Theoretically it's possible to almost solve this problem with a couple UMD bundles output via Webpack with different configurations: one that includes all dependencies and is pre-minified (as is already done), and one that basically treats all dependencies as peers and so excludes them and is not pre-minified (but is transpiled). Don't know for sure, but don't think this covers the ES Module use case--that is, I think we'd be missing out on static import analysis.

**Additional context**

Originally posted in response to https://github.com/netlify/netlify-cms/pull/1770, advocating for this change instead of the change in that PR.

As described in https://github.com/netlify/netlify-cms/issues/589#issuecomment-416009885, this would force some refactoring of the babel config and some decisions would need to be made about how to deal with stylesheets.

**Comment by erquhart** [comment]
Thanks for laying this out so well! We definitely want to start providing useful modules rather than our monolithic UMD, fully agree.

**Comment by erquhart** [comment]
This was completed in #2215.
