### ISSUE TITLE
Allow custom babel configurations

### ISSUE THREAD

**Issue by AryanJ-NYC** [netlify/netlify-cms#1830]
**Is your feature request related to a problem? Please describe.**

As a developer creating websites for clients on older browsers, I would like a way to configure a `.babeljs` or `browserslist`.

**Additional context**

I found `NetlifyCMS` clicking around through Gatsby and such so I will use them as an example. It is very easy to [use a custom .babelrc file](https://www.gatsbyjs.org/docs/babel/) in Gatsby but, after a few days of trying with NetlifyCMS, it seems the babel configuration does not transfer over to the admin page.

**Comment by erquhart** [comment]
Netlify CMS only supports modern browsers, as some of our dependencies also only support modern browsers - it isn't necessarily as simple as altering the build. We're certainly open to efforts for broader browser support.

**Comment by erquhart** [comment]
The Gatsby plugin was created to resolve this: https://www.gatsbyjs.org/packages/gatsby-plugin-netlify-cms/?=
