### ISSUE TITLE
usability: saving doesn't have a good indicator

### ISSUE THREAD

**Issue by rybit** [netlify/netlify-cms#184]
There is not a clear indication that the post is saving. The little line on the top is def useful, but I clicked the save multiple times to make damn sure (which caused some errors)

**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
when you click the save there is a top progress bar, but the save isn't disabled and shows no real 'this happened' indicator

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**
up to you design masters ~ but something like a spinner or just disabling the button until the next edit.

**- Please mention your node.js, and operating system version.**
```
Google Chrome	54.0.2840.98 (Official Build) (64-bit)
Revision	8ee402c67ff2f8f7c746e56d3530b4dcec0709ad-refs/branch-heads/2840@{#829}
OS	Mac OS X 
JavaScript	V8 5.4.500.41
```

**Comment by cassiozen** [comment]
In the last version the save button becomes inactive with the message "saving...".
I will close for now, but please feel free to reopen if needed.
