### ISSUE TITLE
intercom icon blocks the cancel button

### ISSUE THREAD

**Issue by rybit** [netlify/netlify-cms#185]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
the intercom icon blocks some features

![image](https://cloud.githubusercontent.com/assets/406376/20939393/8662af3e-bba3-11e6-87bd-0adae5bce19a.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**
scroll down 

**- What is the expected behavior?**
not sure what to do here, but it impacts the usability 

**- Please mention your node.js, and operating system version.**
```
Google Chrome	54.0.2840.98 (Official Build) (64-bit)
Revision	8ee402c67ff2f8f7c746e56d3530b4dcec0709ad-refs/branch-heads/2840@{#829}
OS	Mac OS X 
JavaScript	V8 5.4.500.41
```

**Comment by rybit** [comment]
cc/ @fool

**Comment by fool** [comment]
I got word that another chat widget, Olark, which is probably the most popular, uses these dimensions by default:

15px from the bottom and 20px from the side
it has dynamic width, but maxes out at  ~280px

Can be easily put on either side, but default is all we should worry about IMHO, and that's bottom right just like intercom's widget.

**Comment by cassiozen** [comment]
Hey Guys, I'll close this issue here and reopen it on the Netlify-www repo, ok?

**Comment by fool** [comment]
@cassiozen I was actually intending for this feedback to apply to the CMS -
if other people use intercom or olark, we want to keep the save button from
being blocked by those.

If the CMS won't look like it does on our site with the save button in
lower right, then you can ignore this, but I think I targeted it correctly
at the CMS so the save button could move for everyone, not just us :)
