### ISSUE TITLE
"Edit this collection" button

### ISSUE THREAD

**Issue by ChrisLasar** [netlify/netlify-cms#1852]
Possibility to show an "Edit this collection" button on each collection related page. And show it just to logged-in users.

**Describe alternatives you've considered**
Similar to those "Edit on Github" buttons which are shown to every user.

**Additional context**
I assume a javascript checking a cookie or a Git-API and a HTML snippet is required here.

**Comment by erquhart** [comment]
You can do this in your site template, not a CMS thing. How you do it will differ depending on your SSG - here's what we do for the Netlify CMS docs, note mentions of `EditLink`: https://github.com/netlify/netlify-cms/blob/master/website/src/templates/doc-page.js
