### ISSUE TITLE
Can I theme/skin/alter the Netlify CMS UI for clients?

### ISSUE THREAD

**Issue by rchrdnsh** [netlify/netlify-cms#1869]
Hi!

Thinking of trying out Netlify CMS and I thought that it would be really cool to be able to skin the CMS for clients, with their co. colors, typography, logos, etc...

Is that a thing that's possible?

**Comment by tomrutgers** [comment]
Closing in favor of #1727. You can post any requests you have in that issue.

**Comment by rchrdnsh** [comment]
ok, thanks :-)
