### ISSUE TITLE
Integration Dependencies

### ISSUE THREAD

**Issue by cassiozen** [netlify/netlify-cms#187]
The Netlify CMS has support for integrations (right now, the only integration available is Algolia, for search, but more integrations will come in the future).

Many of those integrations have their own client libraries instead of providing a complete public API (through REST or whatever). The problem is: we don’t want to include by default all client libraries for each possible integration. At the same time, some integrations might have limited public API (the current Algolia integration is using Rest, but the client library has more functionalities, like keep-alive connections, for example). 

For this reason, we need to investigate the possibility to define and lazy load optional dependencies.

**Comment by biilmann** [comment]
My thoughts on this is that we'll eventually want to move all integrations to separate NPM modules, so using the Algolia integration requires to do a `npm install netlify-cms-algolia-integration` or something similar...
