### ISSUE TITLE
Error: TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by dsusiskin** [netlify/netlify-cms#1875]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by tomrutgers** [comment]
Could you describe the bug, ways to reproduce, your config.yml etc? Just an error doesn't provide enough leads for people to help you out.
