### ISSUE TITLE
Output JSON Object wrapped in Array

### ISSUE THREAD

**Issue by gil--** [netlify/netlify-cms#1877]
Is it possible to somehow output the JSON object in an array? I tried doing that manually but the array wrapper is removed upon saving fields.

## Currently:
```json
{
    "canAdd": true,
    "showBreadcrumbs": true,
    "showSocialSharing": true
}
```

However, I'm using Netlify-CMS with Gatsby  and I'm trying to Query the JSON using `gatsby-transformer-json` but it seems it requires arrays or strings and not an object. If I wrap the Netlify outputted object in an array it works:

```json
[{
    "canAdd": true,
    "showBreadcrumbs": true,
    "showSocialSharing": true
}]
```

That does the trick but the array wrapper `[]` is removed on every save. Without the array wrapper, showBreadcrumbs and showSocialSharing are not query-able:

<img width="288" alt="screen shot 2018-11-13 at 10 16 29 pm" src="https://user-images.githubusercontent.com/3484527/48457756-c8cdba00-e791-11e8-8530-ac19ec3f44ec.png">

Has anyone tried to import JSON into gatsby before and had better luck? I basically need array instead of key-value.

I ended up querying allFile which allows me to filter on a specific file name such as products.json but it's definitely not ideal. Would prefer just wrapping JSON object in an array for a more simplified graphql query.

```
query settings {
  allFile (filter: {
    name: { eq: "products" }
  }) {
    edges {
      node {
        childSettings {
          canAdd
        }
      }
    }
  }
}
```

**Comment by erquhart** [comment]
Definitely a need, could have sworn we had an issue for this.

**Comment by donaldboulton** [comment]
I wish we could use json data sets as I need one for fullCalendar events as a json data set not just a json file.
How to?

**Comment by erquhart** [comment]
@gil-- I think I misread this initially - you can use the list widget for this, defining fields just as you currently do with the object widget.

**Comment by erquhart** [comment]
Finally found it - this is a duplicate of #531, please track there.
