### ISSUE TITLE
Migrate to @reach/router

### ISSUE THREAD

**Issue by alexandernanberg** [netlify/netlify-cms#1884]
**Is your feature request related to a problem? Please describe.**

The current router implementation is not as accessible as `@reach/router` and `react-router-redux` has now been deprecated as well. Reach router also has some neat features that sets it apart from the other routing libraries (like relative links).

**Describe the solution you'd like**

Switch from `reach-router` to `@reach/router`

**Describe alternatives you've considered**

N/A

**Additional context**

https://reach.tech/router

I'd be happy to create a PR for this. But I wanted to check if there is any interest in this first 😄

**Comment by erquhart** [comment]
Definitely open to it if you can get reach router to support our current URL scheme. It only handles trailing wildcards, whereas we require placeholders in between static segments, eg. `collections/blog/:title/edit`. From the [tradeoffs section](https://reach.tech/router/credits) of their docs:

> No complex route patterns. There are no optional params, or anything like them, it’s just static paths, params, and trailing wildcard.



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alexandernanberg** [comment]
Ah I was unaware of the more ”advanced” URL schema being used here. I’m fairly certain that there is no way to get around this – so I’m closing for the time being
