### ISSUE TITLE
The option to add pages to site

### ISSUE THREAD

**Issue by congruentsquare** [netlify/netlify-cms#1893]
Could we add the ability to add additional pages to the website via the cms? For example the cms currently allows the user to post additional blog post like so:
https://imgur.com/a/ZML2pkn
and here is what I am talking about:
https://imgur.com/a/G6JIu3e

**Comment by tomrutgers** [comment]
You already can. In the example you provide, the blog is a folder collection with a `create: true` property. The pages come from a file collection, which is a more static way of handling data. If you want to add pages, convert it to a folder collection. Read more about collections here: https://www.netlifycms.org/docs/collection-types/
