### ISSUE TITLE
Strange bug saving in unpkg 2^ 

### ISSUE THREAD

**Issue by dioptre** [netlify/netlify-cms#1898]
**To Reproduce**
- Save a record

**Expected behavior**
- Saving without an error

**Screenshots**

![image](https://user-images.githubusercontent.com/760216/48885126-f8a53f00-eddb-11e8-975b-8fa2ce13ef0a.png)

**Applicable Versions:**
Latest

**Comment by erquhart** [comment]
A fix is merged already, will be released soon in 2.3.0.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
