### ISSUE TITLE
Show a complete react preview in docs

### ISSUE THREAD

**Issue by dioptre** [netlify/netlify-cms#1899]
The docs hint at how React can be used instead of the bloated h(....) syntax but there's nothing I can find. I don't want to reimport React so perhaps you can share a real example:
https://www.netlifycms.org/docs/customization/
```
export default class ArticlePreview extends React.Component {
  render() {
    const {entry, fieldsMetaData} = this.props;
    const author = fieldsMetaData.getIn(['authors', data.author]);

    return <article><h2>{ entry.getIn(['data', 'title']) }</h2>
      {author &&<AuthorBio author={author.toJS()}/>}
    </article>
  }
}
```

Can you please provide a complete example?

**Comment by erquhart** [comment]
Sure, here's an example: https://github.com/openpracticelibrary/openpracticelibrary/pull/384/files

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dioptre** [comment]
Though isn't react already part of admin? I was almost expecting an internal reference?

**Comment by erquhart** [comment]
Are you using a build system?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
