### ISSUE TITLE
Widget Relations

### ISSUE THREAD

**Issue by hhsnopek** [netlify/netlify-cms#19]
see [TODO.md#relations](https://github.com/netlify/netlify-cms/blob/master/TODO.md#relations)

**Comment by cassiozen** [comment]
Similar to #160?

**Comment by willhackett** [comment]
You just related to a similar post that was closed. This is still an issue.

**Comment by tech4him1** [comment]
@willhackett We have a relation widget: https://www.netlifycms.org/docs/widgets/#relation.
