### ISSUE TITLE
Error: You may not call store.getState() while the reducer is executing.

### ISSUE THREAD

**Issue by darbio** [netlify/netlify-cms#1954]
**Describe the bug**
When I attempt to open `admin` I get the following message:

> Error: You may not call store.getState() while the reducer is executing. The reducer has already received the state as an argument. Pass it down from the top reducer instead of reading it from the store.

**To Reproduce**
Append `admin` to url.

**Expected behavior**
Admin interface to show

**Applicable Versions:**

 - Netlify CMS version: 2.3.0
 - Git provider: GitHub
 - OS: OSX
 - Browser version Chrome

**CMS configuration**

**Additional context**
Quick start from netlify hugo started

**Comment by tomrutgers** [comment]
I cloned your repo and hosted it on Netlify but I can't reproduce this error.
