### ISSUE TITLE
App classes

### ISSUE THREAD

**Issue by Quicksaver** [netlify/netlify-cms#1959]
From v1 to v2, I noticed classnames in the app interface have been uglified, likely because of the move from an external sheet to in-js styles.

We add extra functionalities and tweaks to make the CMS better fit our use-cases, but these rely heavily on CSS selectors. So things like `document.querySelectorAll('.nc-collectionPage-sidebarLink')` will no longer work, because that class is now generated: e.g. the equivalent to that one would be `document.querySelectorAll('.css-187h7lw.el9l68m5`)`.

My questions are:
1) Why? To be honest I don't see a large gain with this on the CMS side, other than perhaps a few kbs less in the final file size?
2) Can this be disabled if I build the script locally? I've been trying to look through the build code but I'm not finding where exactly this is happening, is it a config in webpack I'm missing?
2) How safe can I be that these classes won't change if I start targeting them? I've tried a couple of older releases and the classnames seem to remain unchanged, but still I don't have a lot of confidence in targeting these classes directly.

**Comment by erquhart** [comment]
Sorry to hear this @Quicksaver - really can't wait until we get to an extensible CMS UI, it's just a bunch of React components after all.

Responses:
1. The few kbs I guess. If we can ensure it doesn't increase bundle size much it'd be worth not uglifying the classes.
2. Sure, you could just build it yourself, but again, open to just doing it here.
3. Brings me to the real point, we can't promise anything won't change. But considering we don't have a better solution, I can at least say that it shouldn't.

**Comment by erquhart** [comment]
Not long after this issue was opened we configured Emotion to output partially consistent class names based on the component names they're generated from.

You'll see CSS classes like:
```
css-1t9i08i-ListCardLink
```
You can target them with an attribute selector like:
```
[class$="-ListCardLink"]
```
Again, note that we are still not treating these component/class names as a part of our API, so they can change at any time.

Hope this helps!
