### ISSUE TITLE
Creating new post or page doesnt works

### ISSUE THREAD

**Issue by ronv** [netlify/netlify-cms#1969]
**Describe the bug**
When I create new post or page I get error `TypeError: e.indexOf is not a function`

**To Reproduce**
1. Log into admin
2. Click on New post or page
3. See error `TypeError: e.indexOf is not a function`

**Expected behavior**
Create new post

**Screenshots**
https://imgur.com/U7jYo4t

**Applicable Versions:**
 - Netlify CMS version: netlify-cms 2.3.1
 - Git provider: GitHub
 - OS: MacOS
 - Browser version: Chrome Version 71.0.3578.98
 - Jekyll
 - Netlify

**CMS configuration**
site`config.yml` [here](https://github.com/ronv/www/blob/master/_config.yml)
netlify cms `config.yml` [here](https://github.com/ronv/www/blob/master/admin/config.yml)
Repo [here](https://github.com/ronv/www)

**Comment by tomrutgers** [comment]
The problem lies here: 
```
- {label: "Featured Image", name: "featured_image", widget: "image", default: true}
```
True is not a valid default value. From the docs:
> default: accepts a file path string; defaults to null

Also: You have two lists that do not have `fields` or `field`  defined. It's not causing any errors, but do note these lists are not working. Your tags for instance should look something like this:

```
- label: "Tags"
  name: "tags"
  widget: "list"
  fields:
    - {label: "Tag", name: "tag_item", widget: "string"}
```

Let me know if this fixes your problem! I tested your config with the suggested changes and it seems to work.

**Comment by ronv** [comment]
@tomrutgers Thanks a lot for help! This fixed issue when creating new post/page shows error! But I didn't understood about tags, because like this everything works ok:
`- {label: "Tags", name: "tags", widget: "list", allow_add: true, required: true}`

Br, Ron

**Comment by tomrutgers** [comment]
I made a fork with both examples so you can see the difference: https://codepen.io/tomrutgers/pen/dwvxqm

Closing this since your error is resolved. If you have any questions or things you don't understand feel free to drop by on [Gitter](https://gitter.im/netlify/NetlifyCMS)

**Comment by giordifungula** [comment]
Do you perhaps know if if you create a post from the cms it creates the folder and files inside the directory by on the home page it does not post there, I have to pull the changes locally and edit the categories of the created post to make it the same as the archetypes file.
Here is the github link https://github.com/giordifungula/blog_hugo_francine
https://francinemujinga.online/ here is the app link.
- I am sure it has something to do with when the collections are created online and this is not exactly 
linked to when you create a post locally as this creates the categories as expected.
Would like some help please thanks
