### ISSUE TITLE
Bringing back HMR?

### ISSUE THREAD

**Issue by Maxim-Filimonov** [netlify/netlify-cms#1972]
**Is your feature request related to a problem? Please describe.**
I would like to see component changes without refreshing the page. Even so web pack supports hot reloader for react with the help of react-hot-loader it seemed to be constantly getting removed.
I found 3 PR's of adding react hot loader, this is the [latest one](https://github.com/netlify/netlify-cms/pull/1583/files)

**Describe the solution you'd like**
Add back react hot loader

**Comment by erquhart** [comment]
HMR is in place and functional (including the PR you linked being merged):

https://github.com/tech4him1/netlify-cms/blob/master/packages/netlify-cms-core/babel.config.js#L8

https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-core/src/components/App/App.js#L225

Any particular issues you're finding with it during local development?

**Comment by Maxim-Filimonov** [comment]
As it's merged we can close this one 👍
