### ISSUE TITLE
Any plans for Google AMP support?

### ISSUE THREAD

**Issue by asimqt** [netlify/netlify-cms#1973]
Are we planning to support google AMP pages? I will be a good feature addition. Like whenever we publish a new post, we could generate the AMP version also?

**Comment by Herohtar** [comment]
I would think this would be the responsibility of whatever frontend you're using to generate your site. NetlifyCMS is just a content manager and isn't involved in how your site is presented.

**Comment by asimqt** [comment]
You mean, the generator I'm using (like Hugo) should generate the AMP pages? Like the https://github.com/netlify-templates/one-click-hugo-cms&stack=cms  should create the AMP page?

**Comment by Benaiah** [comment]
This issue seems like it's been resolved, so I'm going to close it. If there's any further issue with editing Google AMP pages from Netlify CMS, please feel free to reopen this issue or open a new one.
