### ISSUE TITLE
How can I search for different post?

### ISSUE THREAD

**Issue by asimqt** [netlify/netlify-cms#1974]
How can we implement search functionality in the front end for users to search for different stories? Can we use GitHub (or other services) search feature and work on it for our needs?

**Comment by Herohtar** [comment]
A good question, but again, probably one you should be asking somewhere else, as frontend stuff isn't part of what NetlifyCMS is responsible for.

**Comment by asimqt** [comment]
Is it entirely front end? We need some kind of API or pages for getting different results, right?

**Comment by Herohtar** [comment]
NetlifyCMS essentially just generates collections of text files in various formats (json, yaml, toml, etc) and it is up to you to implement something to work with it, whether that be displaying it, searching it, or something else. There might even already be something out there that does that.

**Comment by erquhart** [comment]
Folks typically use Algolia: https://www.algolia.com/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
