### ISSUE TITLE
Safari 11 fails with Github API

### ISSUE THREAD

**Issue by 101hawn** [netlify/netlify-cms#1976]
**Describe the bug**
Github API fails on Safari. This is due to the fetch api failing to resend the authorization header after a redirect.

**To Reproduce**
Try to sign in with Github api on Safari with a private repository

**Expected behavior**
Sign in proceeds as usual

**Actual behavior**
Github API for /repo/:repo: returns a redirect which then returns a 404 due to Safari failing add `authorization: token ${token}` header

**Applicable Versions:**

 - Git provider: Github
 - OS: Mac
 - Browser version: safari 11

**Comment by 101hawn** [comment]
#1977 Is my proposed solution as it is the simplest but prehaps something else like manually handling redirects {redirect: manual} would be less of a hack

**Comment by 101hawn** [comment]
https://medium.com/@mrjack/safari-the-fetch-api-and-30x-redirects-23c5610370ca

**Comment by erquhart** [comment]
I'm not able to reproduce this - any chance it's due to a browser extension or using an older version of Safari?
