### ISSUE TITLE
accept_roles configuration seems to be defined at git-gateway level

### ISSUE THREAD

**Issue by jeremyprioux** [netlify/netlify-cms#1979]
Hello,

### Observations
I am using two different branches with different `config.yml` configuration. Each branch have a specific `accept_roles` value.
All of theses branches are related to a netlify site, with one subdomain per branches.
My architecture is fully based on Netlify (deployment, Git-Gateway, Identity) + Github.

- When I setup a role on Git-Gateway level (Netlify site level configuration), then this role filter is applied to all branches.
- When I remove the role on Git-Gateway, then all users are able to login, whatever is set in the `accept_roles` configuration for each subdomain (branches)

### Issue
`accept_roles` configuration is not applied, instead the permission is based on Git Gateway configuration. It means that permissions are handled on a repository level instead of branches.

Can you please advise if this is the expected behavior? How can we achieve to have permissions based on a branch level with netlify cms?

**Comment by jeremyprioux** [comment]
Hello @futuregerald.

The site is not anymore live right now sorry, but i can be reproduced easily.

Is the issue with `accept_roles` is related to git-gateway or netlify-cms ?

**Comment by erquhart** [comment]
Will look into this.

**Comment by jeremyprioux** [comment]
Thank you !

Le jeu. 17 janv. 2019 à 01:43, Shawn Erquhart <notifications@github.com> a
écrit :

**Comment by jeremyprioux** [comment]
Hello,

any news ?

Le jeu. 17 janv. 2019 à 07:45, Jeremy Prioux <jeremyprioux@gmail.com> a
écrit :

**Comment by erquhart** [comment]
`accept_roles` is no longer supported, closing.
