### ISSUE TITLE
Automatically Select Newly Uploaded Image In Media Library

### ISSUE THREAD

**Issue by Undistraction** [netlify/netlify-cms#1983]
**Is your feature request related to a problem? Please describe.**
Currently when a new file is uploaded it is not selected. 

**Describe the solution you'd like**
On most occasions, the newly uploaded file will be the one being added, so it should be selected automatically. Even if it isn't being added, selecting it will do no harm.

**Describe alternatives you've considered**
The only alternative is to find and select the newly uploaded file.

**Comment by erquhart** [comment]
Agreed.

**Comment by maribelduran** [comment]
@erquhart should this issue be closed? It looks fix for this was merged on Aug 20 :)

**Comment by erquhart** [comment]
Good catch

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maribelduran** [comment]
@erquat figured this was another way to contribute to Hacktoberfest! Was looking for an issue to help out with after I found out about this project at the JamStack conf last week. Great talk by the way! :)

**Comment by erquhart** [comment]
Thank you! Completely failed to label issues for hacktoberfest 🤦‍♂️

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
