### ISSUE TITLE
Post being update with public_folder; not media_folder

### ISSUE THREAD

**Issue by mountainstorm** [netlify/netlify-cms#2000]
My Jekyll is hosted on a sub url e.g. www.mysite.com/documents/

My netlify config looks like this:

media_folder: "assets/images"
public_folder: "documents/assets/images"

As far as I can tell, this is right.  In the repo images are found via assets/images/1.jpg, but on the website they are found via documents/assets/images/1.jpg

netlify's UI works as expected; the images show in the media browser, editor etc.  But when updating the page the diff appears to use public_folder; rather than media_folder.  As such Jekyll can't find the files and they appear as broken links e.g. the diff looks like

+ date: 2018-01-11T00:00:00.000Z
- image: assets/images/1.jpg
+image: /documents/assets/images/2.jpg

**Comment by mountainstorm** [comment]
to confirm; (the bullets should be '-'s).  As the image path includes 'documents' Jekyll is unable to find it

**Comment by erquhart** [comment]
`media_folder` is used by Netlify CMS to locate the file in your repo, `public_folder` is used for outputting a link to the live location of the file on your site; what you're describing is by design.

You're saying Jekyll is trying to find your images - are you sure? That isn't default behavior.
