### ISSUE TITLE
Error: The GitLab backend does not support the Editorial Workflow.

### ISSUE THREAD

**Issue by ediano** [netlify/netlify-cms#2003]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by tomrutgers** [comment]
The editorial workflow is not yet available for GitLab 

Duplicate of #568

There’s a PR on the way: #1817

**Comment by johnhashim** [comment]
hey, so what is available right now?

**Comment by talves** [comment]
@johnhashim Editorial Workflow is available for Github.
