### ISSUE TITLE
Error 429: Too Many Requests from createSiteInTeam call

### ISSUE THREAD

**Issue by gustawdaniel** [netlify/netlify-cms#2020]
I installed netlify by `npm install netlify-cli -g` and on first:

    netlify init

I have got:

```
Error 429: Too Many Requests from createSiteInTeam call

Site Created

TypeError: Cannot read property 'ssl_url' of undefined
    at SitesCreateCommand.run (~/.nvm/versions/node/v10.15.0/lib/node_modules/netlify-cli/src/commands/sites/create.js:72:22)
```

I have only one repository that was built only one time.

**Comment by tomrutgers** [comment]
Please report this issue in the Netlify CLI repo: https://github.com/netlify/cli/issues/
