### ISSUE TITLE
how do I use netlify cms when I deployed with netlify

### ISSUE THREAD

**Issue by enersto** [netlify/netlify-cms#2023]
Very newbie question!
I have deployed my site with netlify storage on github,(my [repo](https://github.com/enersto/enersto.github.io) ), but I don't see any file in this file. And I don't know how to configurate as the doc said.
Or EVEN should I add the file to my public file which I draw to netlify to deploy?

**Comment by talves** [comment]
Your repository does not contain a Hugo site.

Steps to help:

- Before attempting to get NetlifyCMS working, first get your Hugo site up and running on Netlify.
- Once the Hugo site is working on Netlify, you will then get NetlifyCMS up and running using the example sites

Going to close. Please use the community site to get help for [Hugo][1] then for [NetlifyCMS][2].

If this is a company project, you always have the option to hit up one of the experts in these communities for some help.

[1]: https://discourse.gohugo.io/
[2]: https://gitter.im/netlify/NetlifyCMS

**Comment by enersto** [comment]
Thanks for the reply. My site is already running on Netlify: stoic-liskov-929121([my site](pauke.live)).
You mean I can use NetlifyCMS right now? Where can I find the gate to NetlifyCMS?

**Comment by tomrutgers** [comment]
Yes. You can start by following the steps outlined here: https://www.netlifycms.org/docs/add-to-your-site/
