### ISSUE TITLE
Pages added through admin ui are saved in content/ and static/ folder outside of site/

### ISSUE THREAD

**Issue by GRMiller** [netlify/netlify-cms#2024]
**Describe the bug**

When I add a page or upload an image in the admin ui it creates a new directory for the content that is on the same level as site/ directory rather than updating the content inside /site/content/**. 
My current structure is: 
- project_name/
  - site/
    - content/
    - data/
    - layouts/
    - static/
    - config.toml
  - src/
    - js/
    - css/
    - index.js
  - netlify.toml
  - package.json

After adding content through the ui, the merged branch creates a structure like:
- project_name/
  - content/
  - site/
  - src/
  - static/

With the rest of the child directories remaining the same.

**To Reproduce**
Steps to reproduce the behavior. For example:
1. Go to AdminUI
2. Add a piece of content, either page or media, and save
3. Go to github repo
4. See the new content/ or static/ directory living on the same level as site/ rather than inside it

**Expected behavior**
I expect the content made through UI to update files in the corresponding existing directories, rather than make new directories

**Applicable Versions:**
 - Netlify CMS version: 2.3.3
 - Git provider: Github
 - OS: Mac OS Mojave
 - Browser version: Chrome 64

 - Node.JS version:

**CMS configuration**

```#
# Settings
#
backend:
  name: git-gateway
  branch: master
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
media_folder: "static/media/uploads"
public_folder: "/media"
display_url: https://zealous-pike-2f4b9b.netlify.com
logo_url: https://zealous-pike-2f4b9b.netlify.com/media/logo-image-text.png
# Beta features
#publish_mode: editorial_workflow
#
# Collections
#
collections:
  # Pages
  - name: "Pages"
    label: "Page"
    folder: "content/pages"
    create: true
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Menu Weight"
        name: "weight"
        widget: "number"
        default: "0"
        valueType: "int"
        min: 0
        max: 99
        hint: "The higher the number, the lower/further right it will appear in the menu. A 0 leaves a page out of the main navigation."
      - label: "Hero Section"
        name: "hero"
        widget: "object"
        fields:
          - label: "Hero Image"
            name: "image"
            widget: "image"
            required: false
            hint: "Preferred photo dimensions are ### X ###." #@todo
          - label: "Media Overlay/Background Color"
            name: "overlay"
            widget: "select"
            options: ["none","blue","green","red","gray - dark","gray - light"]
          - label: "Hero Title"
            name: "title"
            widget: "string"
            pattern: /^[a-z]{0,75}$/
          - label: "Hero Text"
            name: "text"
            widget: "string"
            pattern: /^[a-z]{0,250}$/
            required: false
          - label: "Alignment"
            name: "alignment"
            widget: "select"
            options: ["left","center","right"]
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "SEO Description"
        name: "seo_description"
        widget: "text"
        required: false
      - label: "Meta Title"
        name: "metatitle"
        widget: "text"
        required: false
```

**Additional context**
I'm using Hugo as my SSG. I know this is most likely an error with my configuration. I can post more files as needed. I've searched all over and tried editing my configs many times over to no avail. Posting here is my last resort. Apologize if this is not the appropriate place for my question.

**Comment by tomrutgers** [comment]
Try updating your collections `folder` to `"site/content/pages"`

**Comment by GRMiller** [comment]
Yes! Thanks Tom! I'm an idiot. knew it was going to be something obvious!
