### ISSUE TITLE
Improve misleading pop-up login

### ISSUE THREAD

**Issue by idiazroncero** [netlify/netlify-cms#2031]
Hello;

I always found the UI design of the attached login pop-up clearly misleading to the end-user:

<img width="389" alt="captura de pantalla 2019-01-25 a las 12 18 10" src="https://user-images.githubusercontent.com/3958741/51742979-972f7400-209b-11e9-9889-3e5449f51f19.png">

I have myself countless times clicked on the "log out" button by impulse. I think this is clearly a bad UI for the following reasons:

- Buttons doesn't give any visual clue of wether they lead to a 'positive' action (i.e.: log in, recover password, yes, continue) or 'negative' (i.e: log out, cancel, back)
- The negative "log out" button appears on the same color, same size and same position than the previous, positive "log in" button.
- There is no other action than "log out" on this modal. To successfully proceed to the admin section, you have to close the modal. The only action that's cleary available on the pop up is the **exact opposite** of what the user might want to do!!

**Proposed solution**

The welcome pop-up (and the whole login) should at least provide the following:
- Visual clues (icons, colors) on wheter the action is considered "positive" (leading towards the goal of login in) or "negative".
- An alternate, bigger "continue" button that closes the pop up and proceeds to the admin section (which is the direction that most users want to take!)

Something like this (but well-designed, of course!)

![diffui](https://user-images.githubusercontent.com/3958741/51743641-9b5c9100-209d-11e9-923a-e3e96ec6e2c1.jpg)

**Describe alternatives you've considered**

Another solution, even clearer, might be to just redirect the user to the administration without any popup. I don't find of any use to present the user the option of logging out just a few milliseconds _after_ logging in.

**Comment by renestalder** [comment]
I would say it would already be better to not style the login like a primary action, but rather like a simple link. Then still the "continue to administration" can be added styled as primary button.

**Comment by danurbanowicz** [comment]
> Another solution, even clearer, might be to just redirect the user to the administration without any popup. I don't find of any use to present the user the option of logging out just a few milliseconds after logging in.

I agree and would prefer the above solution. I find the Logged in modal pretty confusing and unnecessary. Unless there is a reason that it needs to be there, I would suggest removing it and redirecting the user directly to the dashboard on successful login.

Anyone who agrees that this should be looked at, please upvote @idiazroncero 's issue.

**Comment by erquhart** [comment]
The code for this is in an upstream library if anyone is up for proposing a change there: https://github.com/netlify/netlify-identity-widget/blob/2bd364004f48b34852264201c5e2748c7b8e6fe5/src/components/forms/logout.js

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tomrutgers** [comment]
Redirection feels like the most logical solution. If there is a technical need to display buttons I prefer `continue to administration` as a primary button and the log out text as a link

**Comment by erquhart** [comment]
I think the pop up should stay, and be treated as informative, requiring no primary call to action. Just close it via X or clicking outside. "Log out" can be relegated to a small text link in one of the bottom corners.

**Comment by erquhart** [comment]
Just reviewed this, two points and closing:
1. I now agree that this popup is probably unnecessary and should at least be configurable to remove.
2. This is a part of an upstream library (linked above), so no fix would happen in this repo.
