### ISSUE TITLE
"API_ERROR: {"message":"404 File Not Found"}"

### ISSUE THREAD

**Issue by grdpr** [netlify/netlify-cms#2032]
Hi, I'm using `netlify-cms` since a longtime with no major problems or bugs. But since today, I'm confronted with this message:
`"API_ERROR: {"message":"404 File Not Found"}"`
Only the last five posts are shown in the Content Manager. 
I did also an update to the last versions but that didn't resolve the problem:
```
    "gatsby-plugin-netlify-cms": "^3.0.10",
    "netlify-cms": "^2.3.3",
```
I'm using Gitlab.
In the console, I get these three errors:
`GET https://www.mywebsite.org/.netlify/git/gitlab/repository/files/content%2Fabout/raw?ref=master&ts=1548432832213 404`
netlify-cms.js:14 

```
Error: {"message":"404 File Not Found"}
    at new t (netlify-cms.js:14)
    at new o (netlify-cms.js:14)
    at Ze.z [as parseResponse] (netlify-cms.js:54)
```
netlify-cms.js:14 
`Uncaught (in promise) {type: "ENTRIES_FAILURE", error: "Failed to load entries", payload: "API_ERROR: {"message":"404 File Not Found"}", meta: {…}}`
/admin/#/collections/post:1 

Is anyone experiencing the same issue?

**Comment by grdpr** [comment]
netlify-cms seems very sensible at the folder management. I just have created a "posts" folder in my "content" folder and it's working now. Never mix posts and pages markdown in the same folder even if it was working before (in 2018)!

**Comment by tareefdev** [comment]
In my case deleting sub-folders inside the content solves the issue!
