### ISSUE TITLE
How can I add Slate plugins

### ISSUE THREAD

**Issue by ssijak** [netlify/netlify-cms#2033]
**Is your feature request related to a problem? Please describe.**
Formatting features of the default markdown plugins are lacking. And instead of writing my own I would like to add existing plugins to the Slate editor.

**Describe the solution you'd like**
I would like to add existing Slate plugins like [https://www.npmjs.com/package/@slate-editor/alignment-plugin](https://www.npmjs.com/package/@slate-editor/alignment-plugin)

**Describe alternatives you've considered**
Implement my own plugin as described here : [custom editor components](https://www.netlifycms.org/docs/custom-widgets/#registereditorcomponent) which I would avoid if I can

**Comment by erquhart** [comment]
You have to consider not what Slate (and its plugins) can do, but what _markdown_ can do. Slate can do pretty much anything. Markdown can do next to nothing, text alignment being one of those things it can't do.

There's been discussion of doing alignment and other non-markdown things with HTML, but that's a tough approach to take in any sort of standard way.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tomrutgers** [comment]
FWIW you can track that discussion here: https://github.com/netlify/netlify-cms/issues/1503
