### ISSUE TITLE
scheduled posts / publish date

### ISSUE THREAD

**Issue by eur2** [netlify/netlify-cms#2034]
Hi, I'm trying to schedule the publishing of a post in the near future with the default widget field "publish date" but it's not working. Anyone has found a solution to schedule a post in netlify-cms?

**Comment by talves** [comment]
The scheduling of a post would be controlled by the SSG you are using.  NetlifyCMS would only be updating the date with a field required in the content for the SSG to use to determine if the post is ready to publish.

**Comment by erquhart** [comment]
I've been considering whether Zapier can do this. I could see the CMS "scheduling" posts by adding an identifier and date/time to a file in a metadata branch, together with a lambda/Netlify Function that publishes posts from the document if the date/time has passed, and activating that function via Zapier webhook hourly.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by erquhart** [comment]
This is also being tracked under https://github.com/netlify/netlify-cms/issues/263.
