### ISSUE TITLE
Last_modified_at jekyll front matter

### ISSUE THREAD

**Issue by sheldonhull** [netlify/netlify-cms#2037]
This may already be achievable by the current system, likely is, but I can't find any documentation on how to do this properly. 

I'm trying to set modified date as a read-only field and have the date automatically reflect the current date when editing a file. This would ensure the `last_modified_at` jekyll front matter property is updated automatically whenever I edit or publish. 

In addition, I'm trying to set the `publish_date` only on initial creation, but still failing. 
Maybe someone could shed a little light on how to set defaults, or ensure it overrides a field value regardless and I could then be able to leverage these correctly.  If I'm missing some part of the documentation, please let me know. I've tried the sections mentioning leaving values blank vs default value and still no luck.

**Comment by erquhart** [comment]
It's not possible right now, unfortunately. Your issue inspired some thoughts on the widget API, though - please check my comment over there and reply back if you have any thoughts!
