### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by SkypLabs** [netlify/netlify-cms#2039]
A dark theme would be very welcome :smiley:

**Comment by tomrutgers** [comment]
Closing in favor of https://github.com/netlify/netlify-cms/issues/1727

**Comment by SkypLabs** [comment]
Sorry I didn't see this issue when I had a look at the preexisting ones.

**Comment by erquhart** [comment]
@SkypLabs no problem! A dark theme would be very cool, agreed.
