### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by DanielRuf** [netlify/netlify-cms#2043]
It seems there is no active CI setup. Is there a good reason that it is not enabled / used?

**Comment by DanielRuf** [comment]
I mean the `test` and `test-ci` scripts.

**Comment by erquhart** [comment]
![GitHawk Upload by erquhart](https://i.imgur.com/v8LBC3j.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by talves** [comment]
@DanielRuf are you familiar with the Netlify CI/CD setup? We would be happy to take a look at a PR to see what you feel would improve upon what we have.

**Comment by erquhart** [comment]
Yeah that's weird, going to look into that

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by erquhart** [comment]
The squash merge commits on master are being built and deployed by Netlify, too, so it's double weird.

**Comment by DanielRuf** [comment]
Here are two with CI status
https://github.com/netlify/netlify-cms/commits/master?after=ade03d09f108e0fe3e0483f9c5e47f9eb89e9f26+139

**Comment by erquhart** [comment]
More weirdness. Can't see anything that makes those stand out. I'll ask support about it on Monday.

**Comment by DanielRuf** [comment]
Not stale.
