### ISSUE TITLE
JSON Widget

### ISSUE THREAD

**Issue by IgorBelyayev** [netlify/netlify-cms#2046]
**Is your feature request related to a problem? Please describe.**
The ability to save collection files as JSON files exists. However, there is no way to add nested JSON objects, nor is is there a way to add `null` values to a file. For example, if you paste JSON into a text widget, the resulting collection file contains a value for that text widget key which is a stringified version of the pasted JSON.

**Describe the solution you'd like**
A widget which supports JSON editing, and does not stringify the input upon saving.

**Additional context**
This seems like it might be a common use case so I'm wondering if I missed an existing solution.

**Comment by erquhart** [comment]
The code widget can do this: https://www.netlifycms.org/docs/widgets/#code

**Comment by alihardan** [comment]
@erquhart, it won't because stores whole JSON as string not as nested object.
