### ISSUE TITLE
"add to your site" link broken on docs page

### ISSUE THREAD

**Issue by betatim** [netlify/netlify-cms#2061]
**Describe the bug**
Links to the "add to your site" tutorial on https://www.netlifycms.org/docs/intro points to https://www.netlifycms.org/add-to-your-site/ instead of https://www.netlifycms.org/docs/add-to-your-site/ when visited from the "Docs" entry in the navbar on https://www.netlifycms.org/. If I directly open the docs page (or refresh it) the links are correctly generated.

Same for https://www.netlifycms.org/configuration-options (look at config options)

This is with Firefox 65.0b10 (64-bit) on OSX.

I'm not quite sure where to go to fix this. If you have some pointers I'd happy to make a PR.

**Comment by tomrutgers** [comment]
I can not reproduce this. Can you test if clearing your cache helps?

**Comment by erquhart** [comment]
Not sure if this is Firefox specific or just coincidence, but if I hit the link to go to the docs intro page in Chrome, I end up at `/docs/intro/`, while Firefox goes to `/docs/intro` - note the lack of a trailing slash.

Many of our internal links are relative, eg. `../add-to-your-site` - from `/docs/intro/` that's `/docs/add-to-your-site`, but from `/docs/intro` it's `/add-to-your-site`.

We either need to stop using relative links or ensure that all links include a trailing slash. Not sure why Gatsby even supports both versions, maybe just a config thing.

**Comment by erquhart** [comment]
Lol aaaand of course there's a plugin: https://www.gatsbyjs.org/packages/gatsby-plugin-force-trailing-slashes/

**Comment by erquhart** [comment]
Didn't work.

I did find the actual actual issue though: we were explicitly setting the links for the top nav with no trailing slash, so if you navigate to a page using those links, the relative links on that page will be incorrect as described above. Happens in Chrome, too.

Also found a gem of a link that goes to the contributors guide in a very old version of the site, from which point all links also point within the same very old version of the site. Need some kind of linting for links.

PR forthcoming. Thanks for reporting @betatim!
