### ISSUE TITLE
Error: Loading chunk 1 failed. (error: …/admin/dist/1.netlify-cms.js

### ISSUE THREAD

**Issue by hamandhoney** [netlify/netlify-cms#2074]
I’ve started getting this message after logging in.

Latest version.

Sorry!

There's been an error - please report it!

Error: Loading chunk 1 failed. (error: https://www.example.com/admin/dist/1.netlify-cms.js)

**Comment by erquhart** [comment]
Working on a fix right now.

**Comment by BintLopez** [comment]
Also experiencing this behavior

**Comment by ostrebler** [comment]
Same here

**Comment by erquhart** [comment]
Fixed in [2.4.1](https://github.com/netlify/netlify-cms/compare/2.4.0...2.4.1).

**Comment by sanjogpandey** [comment]
Sorry!
There's been an error - please report it!

Error: Loading chunk 1 failed. (error: http://localhost:1313/admin/dist/1.netlify-cms.js)

**Comment by hamandhoney** [comment]
Thanks for the quick fix
