### ISSUE TITLE
Support OSS Documentation Contributors

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#2093]
Most OSS Docs sites direct content editors directly to GitHub for contributions. Netlify CMS could work really well as an open CMS if we add a few features. Because most OSS Docs are currently on GitHub, we can focus support efforts on that backend for now.

## Issues

- https://github.com/netlify/netlify-cms/issues/2096: Forking in the editorial workflow
- https://github.com/netlify/netlify-cms/issues/1344: Feature Request: Media committed with Post / Collection Item
- https://github.com/netlify/netlify-cms/issues/245: Syntax highlighting in Markdown (or HTML) editor
- https://github.com/netlify/netlify-cms/issues/697: Open content editor to a specific entry by path
- https://github.com/netlify/netlify-cms/issues/1423: GitHub Backend o-auth permissions set too widely

**Comment by verythorough** [comment]
As brought up in the community dev call this week, one consideration we'll want to keep in mind for this is how to have contributions show on the contributor's GitHub profile.

**Comment by erquhart** [comment]
@verythorough turns out the GitHub backend _does_ open the PR with the user's own account, so we're covered 👍
