### ISSUE TITLE
Generate markdown files locally

### ISSUE THREAD

**Issue by Tasemu** [netlify/netlify-cms#2094]
**Is your feature request related to a problem? Please describe.**
I cannot run netlify cms in develop mode locally and create md files from the admin panel.

**Describe the solution you'd like**
I would like to be able to run my gatsby site locally and log in to the admin panel and create some pages, then i would like to be able to have those pages generated on my file system so i can push them straight to github myself, without needing to set it all up in production first.

**Describe alternatives you've considered**
I am unsure of any alternatives available for this. I know i can link github to my hosted netlify production environment, however i would like to be able to work on my content locally and then generate all the static files i need locally too, before pushing them to any static site host i require at the time.

**Additional context**

**Comment by talves** [comment]
@Tasemu I have created a file-system backend for Netlify-CMS and a [starter example here](https://github.com/ADARTA/gatsby-starter-netlify-cms)

There are some things you need to do to make this setup work. I will try to document them in the readme and link here in awhile. Today is a good day for me to get to it.

**Comment by talves** [comment]
@Tasemu I have updated the readme to show how to add it to your Gatsby project that already has Netlify CMS.

I am going to close this issue. If you have any further questions, [you can always also go to the community gitter](https://gitter.im/netlify/NetlifyCMS)
