### ISSUE TITLE
React 16.8.1 `ref=` warning

### ISSUE THREAD

**Issue by talves** [netlify/netlify-cms#2098]
**Describe the bug**

`EditorInterface.js` line 190: `ref={c => (this.controlPaneRef = c)}` seems to be the cause.

![image](https://user-images.githubusercontent.com/784848/52869229-0841d480-30fa-11e9-92a4-37f122c54a4f.png)

**To Reproduce**

Example to be provided.

See: https://reactjs.org/docs/forwarding-refs.html#forwarding-refs-to-dom-components

**Expected behavior**

Not to see a warning in the console.

**Applicable Versions:**

 - Netlify CMS version: 2.4.2

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by erquhart** [comment]
Oh yeah we have to update to the new refs methods, good point.
