### ISSUE TITLE
Missing Images in collections 

### ISSUE THREAD

**Issue by engmagdy87** [netlify/netlify-cms#2099]
**Describe the bug**

images are missing in collections
**To Reproduce**
**Expected behavior**

found images
**Screenshots**

![capture](https://user-images.githubusercontent.com/8473421/52869900-6056f600-314f-11e9-81d0-f2f22bd22724.PNG)

**Applicable Versions:**

 - Netlify CMS version: 2.0.0
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version : chrome 72

**CMS configuration**

https://raw.githubusercontent.com/maimagdy90/mai-magdy-portfolio/master/static/admin/config.yml

**Comment by tomrutgers** [comment]
Try adding `public_folder: /images` to your config

**Comment by engmagdy87** [comment]
@tomrutgers 
not solve the problem

**Comment by erquhart** [comment]
Those are just `img` tags built using the `public_folder` value provided in your config, see what the `src` is for the image and compare that to what it should be, then update your `public_folder` accordingly.

**Comment by tomrutgers** [comment]
@engmagdy87 I cloned your repo and deployed it to Netlify. The images from your data aren't loaded, but if you add the images through the CMS now that you updated the `public_folder` property it works just fine. So upload all the images through the CMS and save the entries, it should solve your problem.

**Comment by engmagdy87** [comment]
@tomrutgers I know that if i upload the image through CMS will appear but if I return to home page of CMS and re-open this new entry, the image didn't appear

**Comment by engmagdy87** [comment]
@erquhart the images are relative to the build version
as u can see, the images path have different paths
_.... static/**hash code**/d11cd_

https//gallant-yalow-4e9586.netlify.com/**static/c099947427c4f5325dc60a1ef0ff478a/d11cd**/46801476_529836307497437_5626754504650129408_n.jpg

https//gallant-yalow-4e9586.netlify.com/**static/f951aaa0fdc38766665de06ed1102cbb/d11cd**/46895052_1935869916507627_714689064929853440_n.jpg

**Comment by engmagdy87** [comment]
@tomrutgers @erquhart 
when I build project locally, i found static folder inside public folder(which is build folder) that each image has many versions and i think this is due to using fluid images in gatsby

**Comment by tomrutgers** [comment]
Yeah, at this point I'm pretty sure your problem isn't caused by Netlify CMS

**Comment by engmagdy87** [comment]
fixed
transfer images folder from src to static
