### ISSUE TITLE
[QUESTION] Including netlifycms directly in project folder

### ISSUE THREAD

**Issue by ChandlerMBing** [netlify/netlify-cms#2107]
Is it possible to include the CMS directly in the project folder rather than as a package or from cdn for customisation purposes? I tried doing that myself,  but it's way over my head and I couldn't find anything online. If someone could help or point me in the right direction I'd appreciate it.

**Comment by erquhart** [comment]
Are you trying to run your own modified fork of the Netlify CMS repo? If so you'll need to run the [build command](https://github.com/netlify/netlify-cms/blob/master/CONTRIBUTING.md#build) and grab the build output from `packages/netlify-cms/dist`.

**Comment by ChandlerMBing** [comment]
@erquhart appreciate it, I'll try that and get back to you.

**Comment by ChandlerMBing** [comment]
@erquhart so I finally had some time to get down to it. I got a fresh new clone of this repo, did what you said, ran build and didn't change anything thus far. I used the existing website folder to test it and switched the CMS and ran the dev server. Admin page just doesn't build and throws 404 even though in network tab the request is 200. I looked into `./public/admin` and there isn't any `.html` file only `config.yml`, so that explains it. To import the cms I used a relative route `import CMS from '../../../packages/netlify-cms/dist'`. What am I doing wrong?

**Comment by erquhart** [comment]
Steps for adding the CMS to your site are in the docs: https://www.netlifycms.org/docs/add-to-your-site/

You need to provide your own HTML file for the CMS to run from.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ChandlerMBing** [comment]
yes! that worked! Now my cms is beautifully translated! For others who are going to be doing this with Gatsby:
- link to the `netlify-cms.js` file not `cms.js` - that one has a deprecation warning.
- setup a media library, I didn't know how to do it locally so I connected to cloudinary, if there's issues with this part you'll be getting `n is undefined` error in your console.
- put the identity script tag in the head of your `admin/index.html` and also do a script injection in netlify dashboard of the same thing ( maybe there's a better way of doing this, but I couldn't find it)
- Use script injection for the `if statement` block of code provided on [the netlifycms site](https://www.netlifycms.org/docs/add-to-your-site/#add-the-netlify-identity-widget) (same as above, there could be a better way but this has worked for me)
- remember to have at least one valid file in a collection otherwise you may be getting an API error.
- If you're looking to translate your cms go to `packages/netlify-cms-core/src/constants/defaultPhrases.js`

Special thanks to @erquhart, couldn't do this without your help !

One issue I still have on localhost is a git-gateway auth error, do you have an idea what I may have missed? I log in just fine in production. The part in non-english just means "Auth error"
![screenshot 2019-03-05 at 18 02 07](https://user-images.githubusercontent.com/23351348/53823069-4dc32600-3f71-11e9-90c2-cb808861abd3.png)

**Comment by Benaiah** [comment]
@ChandlerMBing have you enabled Git Gateway in the Netlify dashboard (under Settings -> Identity)? If so, has your site deployed at least once since you enabled it? (Git Gateway won't be initialized correctly until a new deploy of the site is made).

If it's only showing in localhost, it could also be an issue with the CMS trying to use the incorrect URL to Git Gateway. You can double check this by setting `backend.gateway_url` to `"https://YOUR-NETLIFY-SUBDOMAIN.netlify.com/.netlify/git"`.

**Comment by ChandlerMBing** [comment]
@Benaiah, that fixed it, thanks!
