### ISSUE TITLE
list widget: change "add 'name' +" to "add 'child name' +" (same for the counter)

### ISSUE THREAD

**Issue by speexy** [netlify/netlify-cms#2109]
**Is your feature request related to a problem? Please describe.**
I have a list with the label "ImageList". the fields are images.
In the CMS I get the box for the list and a button saying "add imagelist". Which is very confusing as I am actually adding an image, not a list. 
The counter tells me that I have X imagelist in my list.
![screenshot from 2019-02-20 17-05-36](https://user-images.githubusercontent.com/14757801/53106792-0c278980-3534-11e9-83d1-83cd2d3b432f.png)

**Describe the solution you'd like**
I'd like the counter and add-button to be labeld with the child's/field label. In my case just "image"

**Additional context**
I am seeing this with a list within a list with variable types. Maybe this is a bug after all?

**Comment by tomrutgers** [comment]
Use `label_singular` to define what is displayed in the list UI

**Comment by speexy** [comment]
@tomrutgers, thanks, I did not know that! 
However, I still think the default behavior is weird.

**Comment by erquhart** [comment]
@speexy if you have specific ideas on how to improve we're all ears, but specifying singular/plural versions of names is a standard pretty much anywhere. If we only have "imagelist" as a name, then that's all we have to use.

Please comment if you have further thoughts!

**Comment by speexy** [comment]
@erquhart, I think I haven't made clear enough what I mean (And my second comment made it even less clear). I am not talking about the count of 1 image, 2 image(s) etc., I am talking about where the count label is coming from. 
I.e.
```
{label: "Gallery", name: "gallery", widget: "list", field: {label: "Image", name: "image", widget: "image"}}
```
--> I would expect the counter to count images, not gallerys. I don't mind that it is '1 gallery, 2 gallery'. I mind that it is gallery instead of image.

**Comment by erquhart** [comment]
That kind of logic could work when using `field`, but not with `fields`, where you have an array of fields.
