### ISSUE TITLE
Ease of use for finding drafts/ blog previews

### ISSUE THREAD

**Issue by cassandraoid** [netlify/netlify-cms#211]
**- Do you want to request a *feature* or report a *bug*?**

Feature

**- What is the current behavior?**

Right now if I see a deploy preview or someone has created a blog post, I have no way of finding that blog post with ease - other than asking the author to send me the link. 

**- What is the expected behavior?**

I'd like to see a 'published' and 'drafts' section below Collections under Blogs, that way I can go to drafts and easily find these. These should also be 'searchable'  as of now I don't believe they are.

**Comment by calavera** [comment]
I think the problem is that we don't have the metadata if a document is not created with the CMS, unless I'm wrong. I created a blog post this morning by adding a new markdown file and I cannot see it in the CMS. Is that correct @cassiozen ?

**Comment by cassiozen** [comment]
That's correct @calavera: The CMS ignores any branches unless they also have metadata. 
This is the expected behavior because the developers of a static site can create new branches and PRs without interfering with the content authors.

**Comment by cassandraoid** [comment]
Hmmm I'd like to test this with someone. Even so, wouldn't I have to go "searching" for the post? All I see is a very, very long list of blogs.

**Comment by cassiozen** [comment]
No, posts that were created in the CMS and not published yet should appear on the home.
I will close this for inactivity.  Please feel free to reopen if needed.
