### ISSUE TITLE
Organise media in subfolders

### ISSUE THREAD

**Issue by chriskirknielsen** [netlify/netlify-cms#2113]
Hi there,

Transitioning from WordPress, I have a decent amount of media uploads to import. Using Netlify CMS makes the experience nearly as simple, but the files are stored in the same folder. This can lead to a bloated `uploads` folder that can be hard to navigate over time.

**Possible idea for how such a feature would work**
If not automatable (with some config setting), I'd love to be able to tell the CMS to place the file I just uploaded in a subfolder such as `2019/02/` in order to keep things simple and clean.

If we could rename the file and use the functionality where you can type in the filename and use a forward slash to place it in a subfolder, it would be very useful: (here is an example from Bitbucket)
![Bitbucket naming feature](https://user-images.githubusercontent.com/6561758/53128945-26f9fe00-3534-11e9-939e-63f7aa81bb10.gif)

**Alternatives**
I could of course add the files via Netlify CMS, then pull the updated repo locally, create the subfolder I want, place the files inside, commit, push and merge. But that's probably an extra few steps I will get tired of very quickly.

I'd be willing to look into CDN-handled files but I have just learned how to use Netlify and Hugo and feel a bit overwhelmed already! But learning new things is fun, so if there is a good resource to learn out there, please share. :)

**Additional context**
From what I've been told, a folder with too many files can become bad for performance, but this might be an outdated insight.

WordPress generates a lot of different sizes for an image, which I would also love as a feature on Netlify CMS, but given it doesn't, the "performance clutter" aspect isn't as much of a problem and thus, not a pressing matter.

Thank you!
Chris

**Comment by h404bi** [comment]
The very first idea comes to my mind is adding template tags to `media_folder` field, which I pointed out in #2281 . But the example from Bitbucket is much more cooler and useful. The feature definitely makes sense, see if we could make it possible!

**Comment by azicchetti** [comment]
+1 for this, would be a super nice feature

**Comment by erezrokah** [comment]
This is available via https://www.netlifycms.org/docs/beta-features/#folder-collections-media-and-public-folder

**Comment by RayHollister** [comment]
OK, so the link is now https://decapcms.org/docs/collection-folder/#media-and-public-folder

But this only gives the ability to organize media file in a collection, not in the root directory. So if I want my images stored in "site.com/posts/2025/01/" I can do that, but I can't store them in "site.com/media/2025/01/". Right?

**Comment by LyubomirVasilev** [comment]
> OK, so the link is now https://decapcms.org/docs/collection-folder/#media-and-public-folder
> 
> But this only gives the ability to organize media file in a collection, not in the root directory. So if I want my images stored in "site.com/posts/2025/01/" I can do that, but I can't store them in "site.com/media/2025/01/". Right?

I'm not sure either, if this is possible... Can media files be automatically placed in a subfolder based on the current year and month when they are uploaded in the root (in Hugo this is the so called "static" top level directory)?
