### ISSUE TITLE
`searchFields` doesn't accept a string value as a single field

### ISSUE THREAD

**Issue by Benaiah** [netlify/netlify-cms#2114]
**Describe the bug**

The relation widget option `searchFields` only accepts a list of values, not a single value. This is despite the fact that `displayFields` _does_ allow for either a list of values _or_ a single value - see the following:

https://github.com/netlify/netlify-cms/blob/722eb8fefec950935893232fd418e126652b334d/packages/netlify-cms-widget-relation/src/RelationControl.js#L121-L126

**To Reproduce**

1. Set up a relation widget with `searchFields` set to a string.
2. Try to use the relation widget in the entry.
3. Observe that the relation widget fails to load search entries with no error message besides an uncaught exception in the console.

**Expected behavior**

Either we should treat a single string value as a list of one search field and proceed as usual, or the `config.yml` validator should warn that the configuration of the relation widget is invalid.

**Screenshots**

The inscrutable JS error caused by the issue in an end user's copy of the CMS:

![image](https://user-images.githubusercontent.com/1425133/53131684-4e47cf80-3522-11e9-83e9-b2042bf2f3d2.png)

**Applicable Versions:**
 - Netlify CMS version: 2.4.2 (current version) and below

**Comment by keanemind** [comment]
Hey there! I took a crack at this error. I made a mistake with the first commit and got rid of it, although it still shows up here. The second commit is the only one in the history that I'm merging.
