### ISSUE TITLE
Preview Not Working in Post Editor

### ISSUE THREAD

**Issue by nsuchy** [netlify/netlify-cms#2120]
**Describe the bug**
The preview pane does not appear properly and instead displays an error.
`TypeError: Cannot read property 'markdownRemark' of undefined`

```
cms.js:343 TypeError: Cannot read property 'markdownRemark' of undefined
    at BlogPostTemplate.render (cms.js:1369)
    at Oi (cms.js:343)
    at ki (cms.js:343)
    at Ii (cms.js:343)
    at Ua (cms.js:343)
    at za (cms.js:343)
    at Ts (cms.js:343)
    at Ss (cms.js:343)
    at Ps (cms.js:343)
    at On (cms.js:343)
ua @ cms.js:343
i.function.i.componentDidCatch.n.callback @ cms.js:343
ta @ cms.js:343
ea @ cms.js:343
ks @ cms.js:343
Ts @ cms.js:343
Ss @ cms.js:343
Ps @ cms.js:343
On @ cms.js:343
cms.js:159 TypeError: Cannot read property 'markdownRemark' of undefined
    at BlogPostTemplate.render (cms.js:1369)
    at Oi (cms.js:343)
    at ki (cms.js:343)
    at Ii (cms.js:343)
    at Ua (cms.js:343)
    at za (cms.js:343)
    at Ts (cms.js:343)
    at Ss (cms.js:343)
    at Ps (cms.js:343)
    at On (cms.js:343)
```

**To Reproduce**
Setup a gatsbyjs starter blog and add Netlify CMS to it. Try to create a post, and watch the preview pane fail. I followed the steps at https://github.com/netlify/netlify-cms/blob/bfa62df589ea7795a097c296b35510f7bfd6f948/website/content/docs/using-netlify-cms-with-gatsby.md exactly as described.

**Expected behavior**
Beside the editor a preview pane will appear.

**Screenshots**
<img width="1280" alt="screen shot 2019-02-22 at 2 34 43 pm" src="https://user-images.githubusercontent.com/8227641/53266552-1621c780-36af-11e9-99b3-3171b4b5b487.png">

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by erquhart** [comment]
Thanks for posting this - that guide is in review and this is valuable feedback.

**Comment by erquhart** [comment]
Fixed in the latest version of the guide 👍
