### ISSUE TITLE
insert field value in another field value in config yml

### ISSUE THREAD

**Issue by engmagdy87** [netlify/netlify-cms#2122]
in config.yml, I have the following

```
fields:
      - {
          label: 'Path',
          name: 'path',
          widget: 'hidden',
          default: '/book/{{title}}',
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }

```
the generate markdown has
`path: '/book/{{title}}'`

title wasn't replaced with title text but still on the form of **{{title}}**

**Comment by erquhart** [comment]
`default` should be a plain value, it doesn't expect any expressions. There's an open issue around this: https://github.com/netlify/netlify-cms/issues/450
