### ISSUE TITLE
White icons w/ transparent backgrounds aren't visible in Media Assets

### ISSUE THREAD

**Issue by sddaniels** [netlify/netlify-cms#2126]
**Describe the bug**
White icons with a transparent background are not visible in media assets because it uses a white background.

**To Reproduce**
1. Upload an image (we are experiencing this with SVG) with a white icon and a transparent bg
2. View the thumbnail of that icon in the Media Assets section of the site

**Expected behavior**
The background for the thumbnail should be something that provides adequate contrast to a wide range of images, such as a white/gray checkerboard pattern:

![screen shot 2019-02-26 at 4 42 54 pm](https://user-images.githubusercontent.com/1263925/53452121-13dca780-39e6-11e9-98cf-422a7f01b8d3.png)

**Screenshots**
![screen shot 2019-02-26 at 4 41 45 pm](https://user-images.githubusercontent.com/1263925/53452075-f8719c80-39e5-11e9-8397-f7d66c13ae8c.png)

**Applicable Versions:**
Netlify CMS 4.2.2

**CMS configuration**
N/A

**Comment by erquhart** [comment]
Agreed! Happy to take a PR for this, the only requirement is that we use a CSS-only solution for the checkered background itself.

**Comment by sddaniels** [comment]
Seems reasonable, based on things like this CodePen:
https://codepen.io/lloeki/pen/Dvkqw

I actually like the gray/dark gray pattern over the pure white checkerboard since that might 50% obscure white icons.

**Comment by erquhart** [comment]
It'll always obscure something, eg. gray icons. The pattern used in google images seems similar to what I've seen elsewhere:

<img width="174" alt="screen shot 2019-02-28 at 2 35 36 pm" src="https://user-images.githubusercontent.com/2112202/53593262-3f869b80-3b66-11e9-87f8-e556dc4eac69.png">

I'm not super opinionated on this though, whatever works.

**Comment by sddaniels** [comment]
Yeah I feel you. I was just thinking that I really like the UI for this SVG optimizer:
https://jakearchibald.github.io/svgomg/

That uses a darker bg which works great for white icons. Down for whatever works though. If I pick this up I'll try a few options with different icons.

**Comment by erquhart** [comment]
Go with that one 👌🏼👍🏼

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sddaniels** [comment]
Opened a PR to address this!
https://github.com/netlify/netlify-cms/pull/2152
