### ISSUE TITLE
Localization of Admin UI

### ISSUE THREAD

**Issue by bkniffler** [netlify/netlify-cms#2128]
**Is your feature request related to a problem? Please describe.**
The admin UI pulls phrases from getPhrases in the core package. Unfortunately, there is no way to overwrite these phrases (translating to German for example). I'd love to have a configuration option to overwrite certain/all phrases for super simple translations.

What do you think?

**Comment by tomrutgers** [comment]
Closing in favor of https://github.com/netlify/netlify-cms/issues/789

You can share your thoughts and requests there
