### ISSUE TITLE
Can't update "Features" field in Netlify's Site of the Week

### ISSUE THREAD

**Issue by imorente** [netlify/netlify-cms#214]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Cannot update a feature in Site of Week

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to https://www.netlify.com/admin/#/collections/site-of-the-week/entries/evanshunt
2. In the "Features" field, change "Deploy preview" to "Deploy Preview"

The preview on the right doesn't get updated, and when saving, the change doesn't get saved.

**- What is the expected behavior?**
The preview on the right should get updated as I type, and the change should be saved.

**- Please mention your node.js, and operating system version.**
(node.js?) Mac OS Sierra (v10.12.1), Chrome Version 55.0.2883.95

**Comment by cassiozen** [comment]
Should have been fixed on the latest version. I will close for now, but please feel free to reopen if needed.
