### ISSUE TITLE
Expose the biweekly development plannning session's audio/video in the website

### ISSUE THREAD

**Issue by ZoltanVeres** [netlify/netlify-cms#2145]
The Development planning session is a live event, i think it would make sense to be able to listen to offline as well, because not everybody can join the meeting live.
I was bringing this issue up in the NetlifyCMS gitter, and @erquhart suggested that i should raise an issue for this.
Let's discuss this and come to a consensus on what would be ideal solution beside what'll mention below. We can also look how other communities are tackling this problem.
I can try and work on this, once we have a good execution plan.

**Is your feature request related to a problem? Please describe.**

Being up to date with the Dev. planning session can only be done if you're participating to the meeting live.

**Describe the solution you'd like**

In the NetlifyCMS website there could be a section for this where each meeting is listed either in audio and/or text format.
We could store the audio files in LFS, and expose it using the website
**Describe alternatives you've considered**

- Continue updating the [Wiki](https://github.com/netlify/netlify-cms/wiki) with the planning notes but with more details
- [bluejeans](http://bluejeans.com) is used for hosting the meeting maybe we could expose the audio from there
- Migrate to a different solution other than BlueJeans, which we can expose recorded audio

**Additional context**

**Comment by tomrutgers** [comment]
Agreed. IMHO the community section would be the best spot to add these recorded sessions to.
Demonstrating new functionality is quite a usual thing in these meetings, so I'd vote for video instead of audio. Audio alone might not be enough to understand what is being discussed in some cases.

**Comment by talves** [comment]
I feel the "community" meetings should draw away from doing demonstrations of new features. These meetings should concentrate on development issues and discuss priorities, strategies, and solving issues.

Demonstration videos are best in content creator locations like Youtube channels which will live on for everyone to watch. They can be linked in the community discussions at the beginning of the meetings.

This will free up time in the community meetings to concentrate on future development and current issues.

**Comment by erquhart** [comment]
I think there's a need for both, often folks come to hear and see what's going on, with no particular agenda. A community meeting is different from a maintainer meeting - maybe we should establish the latter @talves.

**Comment by ZoltanVeres** [comment]
According to this (tweet)[https://twitter.com/mourner/status/1110969399182274560] seeking trough audio files is not possible on Netlify Large Media. Not sure if this is a concern or not, but i'll just stick in here. I think we should really aim for a solution with the less friction possible, we could even store the audio someplace else and have it embedded in the site.
Once a final agreement is established, on how this will be managed, i would prob. need a basic mockup or something similar.

**Comment by ZoltanVeres** [comment]
Is there any reason to use BlueHost apart Google Hangouts? That way we would have a public record about these meeting and we can easily pull in all the records with an oembed gatsby plugin in the netlify cms website.

**Comment by erquhart** [comment]
Honestly can't recall why we went with BlueJeans instead of Hangouts, but there was a really good reason. Perhaps we can try it though since I'm not recalling what that reason was.

**Comment by tomrutgers** [comment]
Closing this since the development sessions do not take place anymore.
