### ISSUE TITLE
Can I install netlify cms on GitHub or gitlab

### ISSUE THREAD

**Issue by bpmottathai** [netlify/netlify-cms#2146]
I was searching for prose alternative and found it. Can I install it on GitHub or gitlab like prose

**Comment by tomrutgers** [comment]
Yes you can! Netlify CMS works with GitHub, GitLab and Bitbucket. Be sure to check out the [documentation](https://www.netlifycms.org/docs/add-to-your-site/) on how to add Netlify CMS to your site or try one of the[ starter templates](https://www.netlifycms.org/docs/start-with-a-template/).
