### ISSUE TITLE
Netlify CMS + Netlify Large Media + Gatsby =  💥during Netlify deployment

### ISSUE THREAD

**Issue by ludwigbacklund** [netlify/netlify-cms#2154]
## Summary

(This might not be the right forum for this but I'm not sure where the problem lies)

I'm trying to get Gatsby working together with Netlify deployment, Netlify CMS and Netlify Large Media. The reason for this using Netlify Large Media is to not bloat my git repository with large images. When Netlify is deploying my app it first tries to build it but fails with a: 

```
8:39:31 PM: error Failed to process image /opt/build/repo/static/images/009-an9qq9c.jpg
8:39:31 PM: 
8:39:31 PM:   Error: Input file contains unsupported image format
```

because Gatsby can't do anything with the file pointers that Git LFS (which Netlify Large Media is built upon) put in my repo. My guess for how this is supposed to work out is Netlify should pull the actual images to let Gatsby use them when building, but it doesn't (it even says in the Netlify deployment log that is uses `GIT_LFS_SKIP_SMUDGE=1` which skips downloading the images on git pull). 

I'm very lost in who to ask for help with this so any relevant information is very appreciated.

### Environment (if relevant)
```
  System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.7.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 3.7.0 - /Users/dash/.pyenv/shims/python
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: 59.0.1
    Safari: 12.0
  npmPackages:
    gatsby: ^2.1.19 => 2.1.19
    gatsby-image: ^2.0.29 => 2.0.29
    gatsby-plugin-manifest: ^2.0.17 => 2.0.17
    gatsby-plugin-netlify: ^2.0.11 => 2.0.11
    gatsby-plugin-netlify-cms: ^3.0.12 => 3.0.12
    gatsby-plugin-netlify-cms-paths: ^1.2.1 => 1.2.1
    gatsby-plugin-offline: ^2.0.22 => 2.0.22
    gatsby-plugin-react-helmet: ^3.0.6 => 3.0.6
    gatsby-plugin-react-svg: ^2.0.0 => 2.0.0
    gatsby-plugin-sharp: ^2.0.20 => 2.0.20
    gatsby-plugin-styled-components: ^3.0.5 => 3.0.5
    gatsby-remark-copy-linked-files: ^2.0.9 => 2.0.9
    gatsby-remark-images: ^3.0.3 => 3.0.3
    gatsby-remark-relative-images: ^0.2.1 => 0.2.1
    gatsby-source-filesystem: ^2.0.20 => 2.0.20
    gatsby-transformer-remark: ^2.2.3 => 2.2.3
    gatsby-transformer-sharp: ^2.1.13 => 2.1.13
```

**Comment by ludwigbacklund** [comment]
I posted this issue in the gatsby repo too, might be interesting to look at: https://github.com/gatsbyjs/gatsby/issues/12438

**Comment by erquhart** [comment]
Netlify doesn't pull down Large Media images in the build environment. Any chance you can accomplish the processing you need via [image transformations](https://www.netlify.com/docs/image-transformation/)?

**Comment by erquhart** [comment]
Final answer for anyone that runs into this: https://github.com/gatsbyjs/gatsby/issues/12438#issuecomment-474113335
