### ISSUE TITLE
URL to non-existent collection breaks the app

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#2155]
**Describe the bug**

Entering a URL to a non-existent CMS collection breaks the app. This could happen on localhost when a collection no longer exists for some reason and the URL autocompletes.

**To Reproduce**

https://cms-demo.netlify.com/#/collections/non-existent-collection

**Expected behavior**

Return to default screen (first available collection)

**Comment by segmentationfaulter** [comment]
I have worked on this issue, now learning your git flow to create a pull request.
