### ISSUE TITLE
Expected 404's should be indicated as such in the console.

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#2158]
**Is your feature request related to a problem? Please describe.**

The CMS often needs to make requests to determine if a resource exists, where a 404 means the resource does not exist, but does not constitute an actual error. Eg. check if a file already exists, and if not, create it. To the developer, these unexplained 404's seem to be errors, and can be especially troublesome during debugging.

**Describe the solution you'd like**

After an expected 404, log a message to the console stating that the previous 404 was intentional and does not constitute an error:

> <404 error>
> The previous 404 error was expected and safely handled.

A more robust solution would be to wrap such checks in messages:

> Checking for folder "new-folder"
> <404 error>
> Folder not found, creating "new-folder"

**Comment by segmentationfaulter** [comment]
Hi @erquhart, I am new to Netlify CMS and want to work on this issue. Can you please help me how I can reproduce this issue. I am very sorry if it is very obvious and I am not able to wrap my head around it. I have tried the followings:

1. Tried to create a blog post after performing a [template installation](https://www.netlifycms.org/docs/start-with-a-template/), thinking that it would give me a `404` in the console, but it didn't.
2. Tried by uploading a file in media sections, it didn't give me a `404` either.

Can you please help me how to reproduce this issue. I want to make my first ever open source contribution. Thanks

**Comment by erquhart** [comment]
Hey @segmentationfaulter - sorry about the delay! A great first step would be to search within the `packages` directory for occurrences of "404". Most of what you'll find are instances of us checking for a 404 that we're expecting.

Excited to be your choice for your first OSS contribution! 🎉🎉

**Comment by talves** [comment]
Explanation for my thumbs down on this issue.

I don't fee we should have "Expected 404's" in the code logic. I feel there should be a simple config that requires the paths or not. Checking for expected or not expected paths as a way to determine if an outside service has been setup is not good practice. We should consider a different solution where are 404 is never expected and is always an error.

**Comment by erquhart** [comment]
Totally agree, but that's far less trivial than it seems at a glance - confirming file existence without 404s, for example, requires fetching the root and crawling the tree, which could be massive, and we'd have to do it a lot as exist/not-exist is not something you can just cache, so many common actions would take even longer than they already do.

If someone wants to take the time to sit down and do this right, I'm totally on board, otherwise this is cheap, makes things better, and doesn't hurt anything.

**Comment by edmundho** [comment]
hi @erquhart  i've filed a PR against this issue for hacktoberfest. please take a look if you can. any feedback is appreciated

**Comment by erquhart** [comment]
Just reviewed, thanks @edmundho!
