### ISSUE TITLE
Unable to rearrange new list items

### ISSUE THREAD

**Issue by unyo** [netlify/netlify-cms#2161]
**Describe the bug**
If you create a list field like this:

          - {name: "sections", widget: "list", required: false, fields: [ ... ] }

And go into netlify-cms, when you click "Add section", if you already have 5 sections, you can't drag it to the 3rd position as when you expand the item it shows the fields for the section that was already there. This behavior has lasted at least a few version, as upgrading didn't help.

**To Reproduce**

**Applicable Versions:**
 - Netlify CMS version: 2.3.2
 - Git provider: github
 - OS: osx
 - Browser version chrome
 - Node.JS version: 10.11.10

**Comment by erquhart** [comment]
This was fixed in 2.6.0.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
