### ISSUE TITLE
meaningful commit messages

### ISSUE THREAD

**Issue by hhsnopek** [netlify/netlify-cms#22]
ability to have a custom commit message for the next save

**Comment by cassiozen** [comment]
The idea for this first version is hiding the complexity from the user. We will revisit this in near future, but for now i'm closing the issue. Please feel free to reopen if you want to add to the discussion.

**Comment by ekoeryanto** [comment]
Hello, I need this

**Comment by tech4him1** [comment]
@ekoeryanto See https://github.com/netlify/netlify-cms/issues/557.
