### ISSUE TITLE
Netlify CMS: About page content preview doesn't work

### ISSUE THREAD

**Issue by charlottekosche** [netlify/netlify-cms#2213]
**Describe the bug**
In Netflify CMS, when I click on the About page and edit content on the left, nothing shows up on the right. Instead, it says "Error. There's been an error - please report it. Details. TypeError: n.get is not a function"

**To Reproduce**
Go to https://vigorous-shaw-9637e0.netlify.com/admin/#/collections/pages/entries/about

**Expected behavior**
Error page instead of content preview on the right

**Screenshots**
![image](https://user-images.githubusercontent.com/29654921/54496628-ca79cc80-48ae-11e9-8256-241492156c7d.png)

**Applicable Versions:**
N/A

**CMS configuration**
I don't know that one, sorry
_(edit - https://vigorous-shaw-9637e0.netlify.com/admin/config.yml, too long to paste here)_

**Additional context**
Let me know if you have any questions, and maybe you already know about this anyway 😉

**Comment by tomrutgers** [comment]
We can't login to the admin panel to take a look at this, for obvious reasons. It could be pretty much anything, probably your data or a custom preview that produces error, not sure. I tested your config, that seems to work ok.

**Comment by erquhart** [comment]
@charlottekosche if you can share the preview template code, or at least enough of it to reproduce the error, we can determine what's causing it.
