### ISSUE TITLE
Missing URL encode on branch name

### ISSUE THREAD

**Issue by lmcorreia** [netlify/netlify-cms#222]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**- Do you want to request a *feature* or report a *bug*?**
BUG

**- What is the current behavior?**
Using a branch with special chars such as `feature/#4_go_hugo` on the *config.yml* file will result in an error when trying to save an entry. The error is:
> Failed to persist entry: API_ERROR: Branch not found

With the debugging tools logging a 404 on: 
> GET https://api.github.com/repos/<user>/<repo>/branches/feature/ 404 (Not Found)`

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Checkout a new branch `feature/#4_go_hugo` (or something else with a hash) and push it
2. Open Netlify CMS and edit an entry
3. Open the debugging console and hit the Save button

**- What is the expected behavior?**
No malfunction, just a nice ride to origin :)

**- Please mention your node.js, and operating system version.**
Not relevant. This should be noticeable on all systems.

**- More info:**
I tried with `feature/%234_go_hugo` but no cigar, the entries won't even load (seems like it's encoding the percentage sign and just doesn't work.

**Comment by cassiozen** [comment]
Hi @lmcorreia , thanks for the bug report. 

This is definitely in our list, but I have other high priority issues I need to work on first.

If someone could help on this, you're more than welcomed - it should be an easy fix. My suggestion: Take a look at src/backends/github/API.js

This file makes the actual API calls for github. It's a Class, and the branch name is setup as a property on the constructor - I think you could URL encode the value there.

**Comment by lmcorreia** [comment]
Hi @cassiozen and thanks for the reply. I'll try to grab a few minutes and see if I can send you a PR ;)

**Comment by cassiozen** [comment]
That would be awesome.

**Comment by lmcorreia** [comment]
^ @cassiozen I hope #232 helps :)
