### ISSUE TITLE
Large Media pointer files replaced with binary files on publish

### ISSUE THREAD

**Issue by Benaiah** [netlify/netlify-cms#2220]
**Describe the bug**

Some users have reported that when an entry is published, the pointer file in the repo is replaced with the binary file that the pointer file referred to, preventing the use of Large Media.

**To Reproduce**

Repro is unkown at this time - reported experience is saving an image, verifying that the image was created as a Large Media pointer, adding it to an entry and publishing it, then discovering that the image pointer in the repo was replaced with the actual binary image.

**Expected behavior**

All Large Media pointer files should remain as pointer files when entries are published.

**Comment by fool** [comment]
customers in our helpdesk to inform of a fix or at least understanding of what is causing this:

- https://app.intercom.io/a/apps/q245f50x/inbox/inbox/1479299/conversations/21222670155
- https://app.intercom.io/a/apps/q245f50x/inbox/inbox/search/conversations/21109850355
