### ISSUE TITLE
yarn bootstrap failing

### ISSUE THREAD

**Issue by segmentationfaulter** [netlify/netlify-cms#2224]
**Describe the bug**

Wanted to make a contribution, cloned the repo and ran `yarn bootstrap` as [per instructions](https://github.com/netlify/netlify-cms/blob/master/CONTRIBUTING.md#install-dependencies), but it exits with an error straight away.

**To Reproduce**

```
$ git clone https://github.com/netlify/netlify-cms
$ cd netlify-cms
$ yarn bootstrap
```

Dependencies will not be installed, rather you will see an error as shown in the screenshot below.

**Expected behavior**

It should install and link all dependencies for all packages

**Screenshots**

![image](https://user-images.githubusercontent.com/784848/54690513-cf24c780-4ade-11e9-9a06-3d0507f41e57.png)

**Applicable Versions:**

 - Netlify CMS version: 2.6.2-beta.0
 - OS: Ubuntu 18.04
 - Node.JS version: 8.15.1
 - Yarn version: 1.15.2

**Comment by erquhart** [comment]
We should update that to `yarn && yarn bootstrap`.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tomrutgers** [comment]
I'll put in a PR @erquhart

**Comment by talves** [comment]
Actually, @segmentationfaulter can you let us know if you have yarn already installed on your system. Run the command `yarn version` from the terminal for us.

If you don't have yarn, you can [go here to read docs on installing on your system](https://yarnpkg.com/en/docs/install).
