### ISSUE TITLE
Validation error throws no matter what when checking range length 

### ISSUE THREAD

**Issue by KyleWiteck** [netlify/netlify-cms#2233]
Tried to add validation for a text widget to make sure that there are no more then 250 characts and no less then five. I tried using pattern: [ '/^[0-9A-Za-z]{5,250}$/', 'This field must be no more than 250 characters and no less then 5 characters', ]

but it didn't work correctly.

Here is what i have:

**Screenshots**
![Captures2](https://user-images.githubusercontent.com/32344195/54847856-f2559f80-4cb5-11e9-8563-108d4e8cb546.PNG)

![Capture](https://user-images.githubusercontent.com/32344195/54847733-87a46400-4cb5-11e9-970c-dfdabfc4866b.PNG)

**Describe the bug**
Validation throwing error with regex and pattern

**Expected behavior**
Allows me to publish if the character length in the text widget equal to or are within the range of 5 and 250.

**Applicable Versions:**

 - Netlify CMS version: 3.0.14
 - Git provider:  GitHub
 - OS: Windows 10
 - Browser version chrome version 73.0.3683.86]

 - Node.JS version: v11.10.0

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    create: true
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'Index Page'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: About Section,
              name: aboutSection,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Paragraph One, name: paragraphOne, widget: text },
                  { label: Paragraph Two, name: paragraphTwo, widget: text },
                ],
            }
          - {
              label: Skills,
              name: skills,
              widget: object,
              fields:
                [
                  {
                    label: Skills,
                    name: skills,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Title, name: title, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Featured Projects,
              name: featuredProjects,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Projects,
                    name: projects,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                        { label: Git Link, name: gitLink, widget: string },
                        {
                          label: Live Link (add \"\no link\" if no link),
                          name: liveLink,
                          widget: string,
                        },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }

      - file: 'src/pages/portfolio/index.md'
        label: 'Portfolio Page'
        name: 'portfolio'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'porftolio-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        {
                          label: Text,
                          name: text,
                          widget: text,
                          pattern:
                            [
                              '/^[a-zA-Z]{1,250}$/',
                              'This field must be no more than 250 characters and no less then 5 characters long',
                            ],
                        },
                      ],
                  },
                ],
            }
```

**Comment by barthc** [comment]
@KyleWiteck could you please change your pattern from ` [ '/^[0-9A-Za-z]{5,250}$/', 'This field must ..]` to ` [ '^[0-9A-Za-z]{5,250}$', 'This field must ..]`

**Comment by KyleWiteck** [comment]
Unfortunately this does not solver the issue. I have tried it in many different way and it seems to be a problem any way I try it. I am using the Gatsby starter template.

**Comment by bastiaan02** [comment]
@KyleWiteck works for me, no need for the slashes, the widget is using the global `RegExp` to validate.

**Comment by barthc** [comment]
@tomrutgers  could you please test this pattern validation from your end using the config file just to confirm, works for me. Just omit the slashes.

**Comment by tomrutgers** [comment]
@barthc @KyleWiteck can confirm that 
```yml
- { name: text, , widget: text, pattern: [ '^[0-9A-Za-z]{5,250}$', 'This field must do stuff']}
```
 works as expected. Gives an error with a 4 letter word (and a 251 letter paragraph for that matter)

**Comment by KyleWiteck** [comment]
@barthc @tomrutgers, does it give you an error if you fall between the two, because if I give 10 letters. It still throughs the error.

**Comment by tomrutgers** [comment]
@KyleWiteck I realize now that I didn't confirm that in my last comment, but no, it does not throw an error. Do you see any errors in your console? Also, what is the version of the CMS that's logged there? You wrote `3.0.14` in your issue, but the latest version is `2.8.0` so that can't be right..

**Comment by KyleWiteck** [comment]
@tomrutgers  
"gatsby-plugin-netlify": "^2.0.6",
"gatsby-plugin-netlify-cms": "^3.0.14",
"netlify-cms": "^2.8.0",

I was looking at the wrong one. So it is 2.8.0 and I do not see any errors.

**Comment by talves** [comment]
@tomrutgers not sure it is related, but [2.8.0 breaks netlify-cms](https://github.com/gatsbyjs/gatsby/issues/12776#issuecomment-476439568) on Gatsby (fyi)

**Comment by tomrutgers** [comment]
@talves Yeah, that's why I'm asking 👍 
@KyleAMathews can you downgrade to `2.6.1` and check if it works?

**Comment by KyleWiteck** [comment]
@barthc @talves  I will downgrade it now and try it, maybe that is why my mark up isn't working correctly with rich-text also. I'll let you know.

**Comment by talves** [comment]
maybe just try @beta would be a better test, since 2.6.1 had an issue.

**Comment by KyleWiteck** [comment]
@tomrutgers  @talves  Downgrading worked!! It definitely broke things. I did not check my markdown yet, but it fixed my pattern issue. Thanks so much!

**Comment by tomrutgers** [comment]
@KyleWiteck like @talves said, you might want to try `2.8.1-beta.1` to get around those broken bits until a proper fix is in place

**Comment by KyleWiteck** [comment]
@tomrutgers  I did not catch that. Ill give it a shot

**Comment by talves** [comment]
We should be releasing fixes soon.

**Comment by KyleWiteck** [comment]
@talves The beta works with the pattern.  Now I will be diving into why the richtext isn't showing, only the markdown characters. If you have any thoughts, please let me know. Thanks

**Comment by tomrutgers** [comment]
@KyleAMathews Netlify CMS uses Rich Text as input and converts that to Markdown (among others) as output, making editing data for static site generators a breeze for technical and non-technical users alike. If you have any questions about that please join us on [Gitter](https://gitter.im/netlify/NetlifyCMS)

**Comment by KyleWiteck** [comment]
@tomrutgers Thanks for providing me with the Gitter
