### ISSUE TITLE
Working on drafts locally?

### ISSUE THREAD

**Issue by SachaG** [netlify/netlify-cms#2236]
Is there a way to create or edit drafts locally? Basically, I would like to start working on a draft locally on my own machine, then make it available to NetlifyCMS so others can contribute. 

I saw that NetlifyCMS saves drafts in their own branch, but trying to create and push a draft branch manually myself doesn't seem to work. Is this part of the workflow documented anywhere?

**Comment by erquhart** [comment]
Editorial workflow entries are created as pull requests, but metadata in an orphan ref is us

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SachaG** [comment]
Oh cool. Btw I'm sure you've considered this but what about having a `status: draft` field in your markdown file's frontmatter? This could coexist with the more complex GitHub branch workflow as a simpler way to work with drafts locally?

**Comment by bjrn** [comment]
@SachaG there's also [netlify-cms-backend-fs](https://www.npmjs.com/package/netlify-cms-backend-fs) which provides an easy way to work on files in the local filesystem when in development mode (although that still doesn't solve integration with the editorial workflow of course).

**Comment by erquhart** [comment]
Yeah I've considered the need for draft functionality as a separate entity from editorial workflow for a while now, less about a workflow and more about parity with built in draft functionality for SSG's like Jekyll and Hugo, which use a flag as you mentioned. Feature request here: https://github.com/netlify/netlify-cms/issues/942

**Comment by erquhart** [comment]
This would be resolved by #2977, closing in favor of that.
