### ISSUE TITLE
[BUG] CMS on Gitlab not displaying photos in media assets

### ISSUE THREAD

**Issue by hkrank** [netlify/netlify-cms#2242]
**Describe the bug**
The image preview in the cms is broken. There is a problem with the gitlab connection.
It all worked perfectly 10 days ago, suddenly the connection throws an error. 
I've tried the same repo on github and there are now problems with the image preview.

**To Reproduce**
Steps to reproduce the behavior. For example:
1. Go to CMS
2. Click on Media
3. Open console 
`TypeError: Cannot read property 'id' of undefined
    at Ut.getMediaDisplayURL (implementation.js:163)
    at getLargeMediaClient.then.o (implementation.js:367)
(anonymous) @ mediaLibrary.js:410`

**Screenshots**
<img width="662" alt="Bildschirmfoto 2019-03-25 um 11 40 43" src="https://user-images.githubusercontent.com/1030255/54914209-b8bea780-4ef4-11e9-9b8c-64417e811002.png">

**Applicable Versions:**
 - Netlify CMS version: 2.1.0. I also tried the newest and others in between
 - Git provider: GitLab
 - OS: Sierra 10.12.6
 - Browser Version Chrome 72.0.3626.121 | Brave Version 0.60.48 
 - Node.JS version: 10

**CMS configuration**
```backend:
  name: git-gateway
  branch: master 
  media_folder: "static/images/uploads"
  public_folder: "/images/uploads"
  collections:
  - name: "blog" 
    label: "Blog" 
    folder: "content/blog/posts"
    create: true 
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date",  widget: "date", format: "YYYY-MM-DD"}
      - {label: "Blog Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"`
```

**Additional context**
The weird thing is that it worked already perfectly for month and I didn't change anything on the setup.
Since it broke down I've tried many cms version by adding them to my index.html file
Last version was the newest.
`<script src="https://unpkg.com/netlify-cms@^2.8.0/dist/netlify-cms.js"></script>`

Thank you.

**Comment by erquhart** [comment]
Looks like you're using Netlify Large Media, can you confirm?

Also, can you try 2.9.1 and see if the issue still persists?

**Comment by hkrank** [comment]
Netlify Large Media
I used it once as a test in one of my apps. The others are don’t use it. 
The app I testet also on Github(image preview works) was the one without the Netlify Large Media feature.

With version 2.9.1
There is no login option then. I only see a white screen.
Error at the console: 
`https://unpkg.com/netlify-cms@%5E2.9.1/dist/netlify-cms.js net::ERR_ABORTED 404`

**Comment by erquhart** [comment]
cc/ @Benaiah

**Comment by hkrank** [comment]
Hello guys,
thank you very much for working on that issue.
I checked my apps today but the error is still there. Can’t the see preview images.
Now I also installed the CMS locally and  pushed the vision to the server.
```
"netlify-cms": "^2.9.0",
"nuxt-netlify-cms": "^4.0.0",
```
That did not solve the problem either. 
What can I do, to support you with that issue?

Best regards.
Hendrik

**Comment by tomrutgers** [comment]
@hkrank I believe that PR has only been released as a beta: `2.9.1-beta.2`.

**Comment by tmcgee** [comment]
:+1: I deployed my site using `2.9.1-beta-2` and it fixed the display of images from the Gitlab repo.

**Comment by hkrank** [comment]
👍image preview is working with version 2.9.1-beta.2.
thanks @all
