### ISSUE TITLE
GraphQL backend with local filesystem

### ISSUE THREAD

**Issue by emilebosch** [netlify/netlify-cms#2251]
**Describe the solution you'd like**
I'd love if netlify CMS can just be ran locally, without any GitHub or external provider integration. Just use the local git repo or any other way of persisting data (i.e just writing yaml files locally.

As simple as running

```
netlify
```

In the current directory.

I'd love to see a graphql backend for Netlify CMS. This way by just implementing the GraphQL schema, anyone can build their own backends easily. Whether the final result will be stored on local fs or in a database is up to the GraphQL schema implementer.

**Describe alternatives you've considered**
Implementing a backend for the local file system based on a node server that takes care of the backend calls and saves data to local FS. But I thought maybe its easier to make a graphql abstraction. As long as you implement the schema you'd have a backend that can talk to Netlify. Whether that's local or online.

**Comment by erquhart** [comment]
Paging doctor @talves

**Comment by erquhart** [comment]
Oh wait he published it! This should do what you're looking for: https://www.npmjs.com/package/netlify-cms-backend-fs

**Comment by talves** [comment]
The backend fs will allow for writing to the local file system. Everything else on the list is definitely outside the scope of the `netlify-cms` project, but could get @emilebosch started on how to create his own solution.

**Comment by erezrokah** [comment]
Closing as stale and due to https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository.

Please comment if you think there's additional significant benefit to a GraphQL backend
