### ISSUE TITLE
Number widget does not display zero

### ISSUE THREAD

**Issue by formidablecmsadmin** [netlify/netlify-cms#2256]
**Describe the bug**
The Netlify CMS  NumberController component does not display 0 if the `value` is 0 as a number type. It looks like the onChange behavior was improved in this PR, but the component will still render an empty string instead of zero:  https://github.com/netlify/netlify-cms/pull/2077/files#diff-d44a27268e6d33826ac9034548e86be2R98 

**To Reproduce**
evaluate ```0 || ''```

**Expected behavior**
Zero should display.

**Applicable Versions:**
Netlify CMS version: 2.9.0 and possibly earlier versions as well. 
**CMS configuration**
```      
- {label: "A Number", name: "a_number", widget: "number", valueType: "int"}
```
**Additional context**
Seems like ```val || (val === 0 ? val : '')``` would work to replace: ```val || '' ```

**Comment by talves** [comment]
@lmcorreia would be great to have you comment if you get some time. Thanks.

**Comment by lmcorreia** [comment]
@talves Checking. Thanks for the mention!
