### ISSUE TITLE
Changing from raw<->markdown can fail to usefully preserve formatting (lists, text style)

### ISSUE THREAD

**Issue by fool** [netlify/netlify-cms#226]
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

when switching rich<->raw view using the markdown editor, formatting can be misinterpreted/lost

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. text style: I had some bold phrases in rich view, switched to markdown (text still surrounded by double-asterisk here, so far so good), edited (or didn't) those phrases and other things, switched back to rich and found that *some of* the text was now literally surrounded by two asterisks instead of being bold anymore.  Don't have a solid repro case but I bet you can make it happen with a big document and embedded **rich bold text like this** in the middle of some normal content
2. list formatting: when using a somewhat complex list with sub-numbers, it can be impossible to get it formatted correctly.  I'm talking about something like the following:

```1
2
  -
  -
  - 
3
4
  a
  b
5
```

What happens then is some version of:
-  that the "3" will become a "4" for the indented list and everything below will also remain indented
- that the "3" will become a new "1"

**- What is the expected behavior?**

it works as expected ;)

**- Please mention your node.js, and operating system version.**

this is the netlify version, installed at https://www.netlify.com/admin

**Comment by erquhart** [comment]
@fool this is one of many oddities related to our current, non-ideal markdown editing scenario, which will be addressed in #246. Closing in favor of that.
