### ISSUE TITLE
Specific `preview_path` per file in file collections

### ISSUE THREAD

**Issue by theoephraim** [netlify/netlify-cms#2262]
**Is your feature request related to a problem? Please describe.**
The `preview_path` setting for a "files" collection doesn't really make sense. Rather I want to be able to specify the preview path _per file_. The common use case would be I have a collection of "Pages" with several entries -- "about", "contact", "home", "404". Each of these has some content for those specific pages. For each one I'd like to be able to specify the correct preview URL which should be able to be arbitrary. For example the "about" page might have a url of "/about-our-company".

Even if the collection is holding content that is not related to a specific page (say contact info of address and phone number that may be displayed the in the footer), you probably want to be able to specify which is the best URL to preview this 

**Describe the solution you'd like**
Allow the `preview_path` configuration option to be set _per file_ if the collection is using the "files" option.

**Describe alternatives you've considered**
- Setting `preview_path: '{{slug}}'` on the collection sort of works but you must keep the name settings in sync with your URLs which is not always doable. Also causes an issue for a "home" page where the url may be just "/"
- Setting `preview_path: '{{preview_url}}'` on the pages collection and using a field on each file entry with a hidden widget and a default value. Might work but pretty clunky...

**Additional context**
@erquhart also mentioned a related issue that "also just occurred to me that, since individual files have their own data model, `preview_date_field` doesn't work across an entire file collection."

**Comment by dancingmonkey** [comment]
A preview_path for pages would be nice. Currently I need to navigate to the page to see the change.
