### ISSUE TITLE
Add Description to Fields

### ISSUE THREAD

**Issue by blubberbo** [netlify/netlify-cms#2267]
For fields in the cms, I see the following objects in the documentation [here](https://www.netlifycms.org/docs/configuration-options/#collections):

```
name (required): unique identifier for the field, used as the key when referenced in other contexts (like the relation widget)
label: label for the field in the editor UI; defaults to the value of name
widget: defines editor UI and inputs and file field data types; details in Widgets
default: specify a default value for a field; available for most widget types (see Widgets for details on each widget type). Please note that field default value only works for folder collection type.
required: specify as false to make a field optional; defaults to true
pattern: add field validation by specifying a list with a regex pattern and an error message; more extensive validation can be achieved with custom widgets
```

for `collections` I can see: `description: optional text, displayed below the label when viewing a collection`, but not for individual fields.

The simple use case for this would be a description next to a `profile picture` field that indicates the desired resolution for the image, so the person editing the item can know what the resolution should be. There is the `label` option, but it just puts the text in the header of the section, which is not the most visually appealing.

Does anyone have a current solution for this use case?

**Comment by tomrutgers** [comment]
@blubberbo You can use the `hint` property: https://www.netlifycms.org/docs/widgets/#common-widget-options

**Comment by blubberbo** [comment]
awesome, thank you so much!
