### ISSUE TITLE
`yarn run start` doesn't work if you haven't run `yarn run build` first

### ISSUE THREAD

**Issue by Benaiah** [netlify/netlify-cms#2270]
**Describe the bug**

`yarn run start` fails to build the CMS if `yarn run build` hasn't already been run in the same directory.

**To Reproduce**

1. Create a fresh clone of the repo:

  `git clone git@github.com:netlify/netlify-cms.git netlify-cms-clean && cd netlify-cms-clean`

2. Run the develop command:

  `yarn && yarn run start`

3. Observe the CMS development version fail to build, with the following output in the console:

  ```
  netlify-cms:  ERROR  Failed to compile with 5 errors11:38:29 AM
  netlify-cms: This dependency was not found:
  netlify-cms: * netlify-cms-core in ./src/index.js, ./src/backends.js and 3 others
  netlify-cms: To install it, you can run: npm install --save netlify-cms-core
  ```

4. Build the CMS

  `yarn run build`

5. Run the develop command again:

  `yarn run start`

6. Observe the CMS development version build properly.

**Expected behavior**

`yarn run start` should start the development version of the CMS correctly even if `yarn run build` hasn't been run yet.

**Applicable Versions:**
 - Netlify CMS version: confirmed with ~2.9.1-beta.1~ and 2.8.0. Could not confirm with 2.7.0.
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: Debian testing
 - Browser version: N/A
 - Node.JS version: 11.13.0

**Comment by erquhart** [comment]
Weird I thought we were running the build in that command.

**Comment by talves** [comment]
@Benaiah it runs fine for me. Difference on the windows machine is we cannot run them with `&&` so do them on own line. The build should not make a difference. I wonder why it does not work for you?

**Comment by talves** [comment]
No reason to run the build in that command.

**Comment by Benaiah** [comment]
Odd that it's not showing up for you, @talves. I'm able to reproduce this consistently with multiple CMS versions.

**Comment by talves** [comment]
did you try it with the commands separated?

**Comment by Benaiah** [comment]
It appears that I was mistaken when I said I could repro this in `2.9.0-beta.1` - it seems to be an issue only in 2.8.0, which I was trying to debug when I ran into this. I thought I'd checked the latest beta tag, but I think I mixed it up with a different branch, since I'm not running into the issue there. As far as I can tell this is fixed on master - my bad for filing an unnecessary issue.

On 2.8.0 I can still consistently repro it, and the `clean` script you mention is _not_ being run on develop, explaining the discrepancy between what I was seeing and the behavior of the build system you mentioned.

**Comment by talves** [comment]
Wait, @Benaiah maybe you need to run `yarn install && yarn bootstrap && yarn start`. I wonder if the bootstrap links are not setup when you run your commands.

**Comment by Benaiah** [comment]
@talves `yarn start` already runs `bootstrap` immediately after `clean`.

**Comment by talves** [comment]
yeah, but we were seeing an issue with yarn start not doing it the first time I thought.

**Comment by talves** [comment]
@Benaiah I believe it would be an issue on 2.8.0
