### ISSUE TITLE
Possible to upload media to sub folder based on date template tags 

### ISSUE THREAD

**Issue by h404bi** [netlify/netlify-cms#2281]
I have a media folder with this structure:

![20190410230947](https://user-images.githubusercontent.com/5764917/55891164-a75ce700-5be6-11e9-9afb-73d253c3a68f.png)

I wonder if it is possible to upload images to a sub folder that based on date template tags in the `uploads` parent folder. I tried such config, and obviously it does not work:

```yaml
media_folder: "public/uploads/{{year}}/{{month}}"
public_folder: "/uploads/{{year}}/{{month}}"
```

Uploaded an image named `20190410002.png`, then got this:

![20190410231945](https://user-images.githubusercontent.com/5764917/55891451-2baf6a00-5be7-11e9-8096-8616ddd5323e.png)

![20190410231932](https://user-images.githubusercontent.com/5764917/55891438-26521f80-5be7-11e9-88de-643feb0cd167.png)

**Comment by tomrutgers** [comment]
@h404bi This isn't currently possible, but definitely makes sense. Your request is pretty closely related to https://github.com/netlify/netlify-cms/issues/2113, do you mind posting your comment there so we can close this?

**Comment by h404bi** [comment]
@tomrutgers Thanks for the quick response! I made searches over issues before opening this one, and didn't find #2113 out. Yeah, the feature requested in that issue is actually the same as what I want. I'll post my idea to that issue and continue the discussion there and close this one.
