### ISSUE TITLE
Basic app with NextJS using netlify-cms-backend-fs throws React hooks error

### ISSUE THREAD

**Issue by tadhgcreedon** [netlify/netlify-cms#2283]
**Describe the bug**

When using `netlify-cms-backend-fs` as the backend, an invalid React hook error is thrown in the browser. From what I can tell, there is only one version of React and React-DOM being used. The issue appears to be with `netlify-cms-backend-fs` (should I create an issue at https://github.com/ADARTA/netlify-cms-components instead?).

**To Reproduce**

Loading Netlify CMS in the browser results in this error:
```
Error
There's been an error - please report it.

Details
Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

**Expected behavior**

**Screenshots**

All code + dependencies:
![image](https://user-images.githubusercontent.com/10144528/55905364-d3a14500-5b9f-11e9-843c-bce28df079e8.png)

**Applicable Versions:**

 - Netlify CMS version: 2.9.1
 - OS: macOS
 - Browser version: Chrome Version 73.0.3683.86

 - Node.JS version: v10.13.0

**CMS configuration**

```
{
        backend: {
          name: "file-system",
          api_root: "/api"
        },
        media_folder: "static/uploads",
        public_folder: "/static/uploads",
        collections: [
          {
            name: "my-collection",
            label: "My Collection",
            folder: "content/my-collection",
            fields: [
              {
                name: "my-field",
                label: "My Field"
              }
            ]
          }
        ]
 }
```

**Additional context**

**Comment by talves** [comment]
@tadhgcreedon You can create the issue on my component if you want.

The issue is that `netlify-cms` is not using React as a peer dependency. You need to be using `netlify-cms-app` instead. https://github.com/ADARTA/netlify-cms-components/tree/master/packages/netlify-cms-backend-fs

**Comment by tadhgcreedon** [comment]
@talves Ah, I see - the README explains this, but I missed the distinction between `netlify-cms` and `netlify-cms-app`. 

Thank you very much!

**Comment by talves** [comment]
Just for clarity.  `netlify-cms-app` as the package with React as a peer dependency, so any implementation of registered components should use this version to be using a single instance of React. 😀
