### ISSUE TITLE
List reorder messes the content

### ISSUE THREAD

**Issue by maliMirkec** [netlify/netlify-cms#2286]
List item content gets messed up when reordering list items.

**To Reproduce**
1. Go to: https://cms-demo.netlify.com/#/collections/settings
2. Update at least one description to be unique
3. Drag a list item to reorder.
4. Drag again
5. See messed up item descriptions

**Expected behavior**
Keep item content consistent during reordering.

**Screenshots**
https://www.loom.com/share/b408569956324a1ea5e170f8d117ddbd

**Applicable Versions:**
Tested in: https://cms-demo.netlify.com/#/collections/settings

 - Netlify CMS version: netlify-cms 2.9.2-beta.0
 - Git provider: GitHub
 - OS: MacOs
 - Browser version Chrome 73.0.3683.103

**Comment by tomrutgers** [comment]
That is a nasty one! Thanks for catching that @maliMirkec

**Comment by barthc** [comment]
@erquhart  the gif shows the markdown is on `Rich Text` mode. On the first reorder the values are consistent, but on the second reorder they are off, a quick fix here #2298
 
But we still need to fix the `Markdown` mode, they are off on the first reorder, we can handle that in a different PR or update this one, thoughts?

**Comment by erquhart** [comment]
@barthc that fix looks good, I'll merge it now and markdown mode can be addressed in a separate PR.

**Comment by unyo** [comment]
This still seems to be occurring with netlify-cms-app@2.9.7. Rearranging a list that contains a markdown item and string items (or any other non-markdown item) re-arranges the non-markdown items but the display of any markdown items shows the initial list value at that index until you toggle Rich Text / Markdown.

Expected: The text inside a markdown item in a list should update on re-order 
Actual: The text inside a markdown item in a list shows the markdown of the list item that was previously there.

eg.
    [{ title: "string1", subtitle: "string1", desc: "markdown1"} , {title: "string2", subtitle: "string2", desc: "markdown2"}]

    when moving string2 from [1] to [0], the display shows { title: "string2", subtitle: "string2", desc: "markdown1"})

**Comment by erquhart** [comment]
Fix forthcoming, stay tuned.
