### ISSUE TITLE
Images are available in the GitHub repository but not displayed in Netlify deploying 

### ISSUE THREAD

**Issue by andresalerno** [netlify/netlify-cms#2288]
Hi!
I'm trying to deploying a static site using an Hugo Theme through GitHub and Netlify, but i do not know why the images aren't displayed.

In a local environment there is not this problem.

https://github.com/andresalerno/hugo-site-v1

Tks!

**Comment by talves** [comment]
@andresalerno this project is specific to https://netlifycms.org

Please try the [community.netlify.com](https://community.netlify.com) site. There are a ton of people using Hugo with Netlify that can help out.

**Comment by talves** [comment]
@andresalerno are you feeding this site from `http://aspartners.com.br` on netlify?

If not change the `config.toml` `baseurl` value to:

```
baseurl = "/"
```

**Comment by talves** [comment]
Actually, I just saw it and that is not the issue. You might want to get help from the Hugo docs and community.
