### ISSUE TITLE
collections repeated

### ISSUE THREAD

**Issue by lpluispacheco** [netlify/netlify-cms#2289]
Hi,

When i try to see in /admin my collections are displayed with the same name, this is my config

collections:
  - name: "en"
    label: "EN"
    files:
      - name: "header"
        file: "src/intl/en.json"
        label: "Header section"
        fields:
          - { label: Title, name: header-section.title, widget: string }

    - name: "Header Section"
        file: "src/intl/en.json"
        label: "Section One"
        fields:
          - { label: Title, name: section-one.title, widget: string }

    - name: "Header Section"
        file: "src/intl/en.json"
        label: "Section Two"
        fields:
          - { label: Titulo, name: section-two.title, widget: string }

A solution that I've to make is create it separated like this:
 
collections:
  - name: "header"
    label: "Header"
    files:
      - name: "header"
        file: "src/intl/en.json"
        label: "Header section"
        fields:
          - { label: Title, name: header-section.title, widget: string }

  - name: "sec1"
    label: "Section One"
    files:
      - name: "sec-one"
        file: "src/intl/en.json"
        label: "Sec One"
        fields:
          - { label: Title, name: section-one.title, widget: string }

I'm creating different sections because I'm creating a multi lang page with Gatsby and I need to separate it in sections like: 'EN', 'ES'..

Any ideas?

Thanks!

**Comment by erquhart** [comment]
You have the same file for every entry, `src/intl/en.json’.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lpluispacheco** [comment]
Hi @erquhart, yes I have the same file to each entry, 'src/intl/en.json'

**Comment by erquhart** [comment]
Sorry should have been more clear: that's the problem, you can only have one file per entry.

**Comment by lpluispacheco** [comment]
> Sorry should have been more clear: that's the problem, you can only have one file per entry.

Thanks, do you have any solution for this?

Or even can I create like separators in the left menu? To create something like this:

EN
------
Home
Services
Contact

ES
------
Home
Services
Contact

FR
------
Home
Services
Contact

Or if you have another idea would me great, thanks!

**Comment by erquhart** [comment]
Check https://github.com/netlify/netlify-cms/issues/716 for some ways folks are handling this.
