### ISSUE TITLE
Broken link to templates in CMS configuration-options.md

### ISSUE THREAD

**Issue by dolmere** [netlify/netlify-cms#2290]
**Describe the bug**

Dead link in file https://github.com/netlify/netlify-cms/blob/master/website/content/docs/configuration-options.md

**To Reproduce**

Steps to reproduce the behaviour. For example:
1. Go to '
2. Look for the text "To see working configuration examples, you can start from a template" Click on the link "start from a template" which points to URL https://github.com/netlify/netlify-cms/blob/master/website/content/start-with-a-template
3. See 404 error page

**Expected behavior**

I expected to find template files where I would find various configuation option examples (and help me solve my issue where the index.html file from static is being copied into the public folder and then promptly written over by another, currently unknown, wave of the build process.)

**Additional context**

GitHub repository documentation.

**Comment by dolmere** [comment]
One might note that the link to authentication-backends is also broken - https://github.com/netlify/netlify-cms/blob/master/website/content/authentication-backends

**Comment by tomrutgers** [comment]
@dolmere The markdown files are being used as data for the docs website. The links work just fine there: https://www.netlifycms.org/docs/configuration-options/

**Comment by dolmere** [comment]
@tomrutgers Thank you very much for the clarification! Apologies for the erroneous report.
