### ISSUE TITLE
Can't save entries with git-gateway

### ISSUE THREAD

**Issue by alexandernanberg** [netlify/netlify-cms#2296]
**Describe the bug**

When trying to publish an entry you get an error message saying `Failed to persist entry: API_ERROR: Not Found`

When looking at the request in the network panel you see that it tries to request `https://www.strateg.se/.netlify/git/github/git/blobs?ts=1555575972837` but receives a 404.

I'm using Gatsby and the `gatsby-netlify-cms` plugin. So not entirely sure where to report this issue. Just let me know if this should be reopened somewhere else.

**Expected behavior**

Being able to save content

**Screenshots**

N/A

**Applicable Versions:**

 - Netlify CMS version: 2.7.0
 - Git provider: GitHub

**Comment by tomrutgers** [comment]
Thanks @alexandernanberg. Can you update to `2.9.1` and test if the problem persists? 
If you are using an github organization account, check this fix: https://github.com/netlify/netlify-cms/issues/1816#issuecomment-445599821

**Comment by alexandernanberg** [comment]
Oh thanks, removing the restrictions in GitHub fixed it. Would be nice to be able to keep them though 🤔
