### ISSUE TITLE
TypeError: e.join is not a function. (In 'e.join(",")', 'e.join' is undefined)

### ISSUE THREAD

**Issue by houjianyu84** [netlify/netlify-cms#2297]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by tomrutgers** [comment]
We are going to need a bit more information to help you with your problem. Can you share your config.yml? (or ideally, fill out the steps in the issue template).

**Comment by erquhart** [comment]
More than likely this came from a CMS user clicking the "open an issue" button in the error overlay.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
