### ISSUE TITLE
Solution to media files browser caching

### ISSUE THREAD

**Issue by Tomekmularczyk** [netlify/netlify-cms#2299]
#2113 Could be a solution to this.

**Is your feature request related to a problem? Please describe.**
If using Gatsby as a static site generator I choose `static` directory as a CMS media folder then I'm risking some browser caching problems. 

Scenario:
1. Admin uploads `xyz.png` file
2. This file is then referenced in a website as `/images/xyz.png`.
3. Users visit the website and browser caches the resource
4. Admin then removes `xyz.png` file and uploads updated image with the same name.
5. User visits the website again and the browser is using a cached image instead of a new one.

Gatsby docs state this [downside too](https://www.gatsbyjs.org/docs/static-folder/):

> Result filenames won’t include content hashes so you’ll need to add query arguments or rename them every time they change.

**Describe the solution you'd like**
* Adding unique hash to the image name - something like Gatsby does for media imported in javascript files.
* Add a date or store them in directories split by date - #2113

**Comment by mrlubos** [comment]
I am facing a related issue I believe. I have recently updated my `src/cms/cms.js` file, but my browser appears to still use the cached version of the generated `admin/index.html` file. I tried redeploying from Netlify with clear cache and I get the proper version when using incognito mode, but the regular browser is still stuck at the old version. Any pointers as to how we can resolve this? Thanks!

**Comment by erquhart** [comment]
Sounds more like a Gatsby issue, no? I'd expect an image changed in static to be picked up by Gatsby and cache busting to be handled.

**Comment by Tomekmularczyk** [comment]
@erquhart nope. Images in a static directory are not processed by Gatsby/Webpack https://www.gatsbyjs.org/docs/static-folder/

**Comment by erquhart** [comment]
Gotcha. I propose we allow media file names to be configurable by template, just like file names of entries. The default would match what you're proposing: `{slug}-{uuid}`.

**Comment by thaihoa-fe** [comment]
this feature should be great to have.

**Comment by KancerEzeroglu** [comment]
I would like to work on that. Do you have any further explanation or recommendation to start?

**Comment by erezrokah** [comment]
Thanks @KancerEzeroglu, I'm not sure if this is still an issue. Our Gatsby's guide recommends using relative media folders:
https://www.netlifycms.org/docs/gatsby/#configuration
which in that case, the media files should be processed by Gatsby.

Regardless, this issue can be done as a part of of https://github.com/netlify/netlify-cms/issues/857
