### ISSUE TITLE
Open publishing?

### ISSUE THREAD

**Issue by thierrybgentile** [netlify/netlify-cms#230]
Is it possible to use Netlify-cms in a way that would make it an open platform so that everybody could use to publish a post on a site?

**Comment by erquhart** [comment]
@thierrybgentile that would be an awesome feature. We're currently working through items based on priority and I don't think we're quite ready to take this step, but I'll add it to the backlog so it remains on our radar.

**Comment by thierrybgentile** [comment]
@erquhart I've been learning React for a bit now and looking for places to apply it so if somebody with more experience is willing to tell me if that's not to complicated for me now and layout some kind of path I'd be willing to try my hand at it!

**Comment by erquhart** [comment]
We'd love to have you make a contribution! This issue would be a pretty major undertaking, but even if we had someone ready to do it, we're too early on to make major changes or add any features. That won't always be the case, so definitely stay tuned!

In the meantime, if you're looking for someone to improve your skill, we have tickets labelled as "good first contribution" - here's the [filter](https://github.com/netlify/netlify-cms/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22good%20first%20contribution%22).

**Comment by erquhart** [comment]
@thierrybgentile just revisiting this issue - not sure what I was thinking when you first posted this, but open publishing should work just great. Each author would simply have to have a GitHub account. Let us know if you have a site like this going, would love to see it!

Closing this, but if you need help at all, please hit is up on the [Gitter](https://gitter.im/netlify/netlifycms)!

**Comment by verythorough** [comment]
@erquhart Don't all users still need to have merging rights on the site repo? I think this issue pertains to people who aren't on the site repo, and would normally fork to make a contribution. This would be super useful on public docs sites.

**Comment by erquhart** [comment]
Ah yep, great point. I assumed GitHub had this as an option, looks like not.

**Comment by erquhart** [comment]
I think the closest we'll come to open publishing is supporting pull requests from forked repos. How much of this we would automate is up for discussion, but it would enable open publishing through the editorial workflow. The difference would be that branches are on the user's fork, and publishing requires permissions. Ideally this would all be enabled through a simple config flag, perhaps by collection.

**Comment by verythorough** [comment]
Yeah, or possibly use a non-GitHub auth method, which can pipe authenticated user actions through a designated GitHub user account. (I'm pretty sure at least one project is handling auth this way, though not for the purpose of allowing "open" editing.)

**Comment by erquhart** [comment]
This is now doable via Git Gateway / Netlify Identity!

**Comment by mmm8955405** [comment]
I don't know what the editing and preview functions have to do with hosting platforms such as GitHub. But you complicate simple functions. It needs to be submitted to GitHub, okay? You don't know how many people talk about your identity authentication in the whole project. Hey, stupid design

**Comment by talves** [comment]
@erezrokah I deleted the comment above. 2nd CoC offense. [Please add to blocked user list](https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization#blocking-a-user-in-the-organization-settings)

**Comment by erezrokah** [comment]
Thanks for raising this @talves, we've blocked the user 🔒
