### ISSUE TITLE
Browser hangs while opening image gallery

### ISSUE THREAD

**Issue by kirill-zhukov** [netlify/netlify-cms#2300]
The issue happens when there are many image files in assets, we have ~750. When in admin the image gallery is opened browser hangs informing that the script takes too much time to execute. After several confirmations to wait the script to finish it opens up a gallery finally. Looks like the gallery tries to load all the images from assets at once.

Netlify version to reproduce: 2.9.1

**Comment by erquhart** [comment]
Man we really need window virtualization for the media library. It's not so bad for paginated backends like GitLab and Bitbucket, but since GitHub returns everything at once, we load it all at once.

**Comment by kirill-zhukov** [comment]
Hello together. Can you please let me know the status of the issue? Do you have any schedule when this is going to be implemented?

**Comment by erquhart** [comment]
No one has claimed this issue yet, so no timeline at the moment.

**Comment by erezrokah** [comment]
Fixed by https://github.com/netlify/netlify-cms/pull/3381
