### ISSUE TITLE
Solution?

### ISSUE THREAD

**Issue by hafiztayab** [netlify/netlify-cms#2301]
![Annotation 2019-04-24 193853](https://user-images.githubusercontent.com/43601015/56668277-b05eb580-66c8-11e9-9911-d73dcc110e03.png)

**Comment by tomrutgers** [comment]
There is a build system outage, but a  fix should already be in place. This issue isn't caused by Netlify CMS.

More info here: https://community.netlify.com/t/build-system-outage-24-apr-14-17-utc-netlify-heartbeat/621/12
