### ISSUE TITLE
Where could we use docs help?

### ISSUE THREAD

**Issue by verythorough** [netlify/netlify-cms#2305]
The [Write the Docs conferences](https://www.writethedocs.org/conf) gather people who care about documentation: technical writers, developers, support engineers, and more. Most of the conferences include a [Writing Day](http://www.writethedocs.org/conf/portland/2019/writing-day/), where attendees come to work together (or alone 😉) on personal or open source writing projects.

This May, @Benaiah, @klavavej, and I will be at the flagship Write the Docs conference in Portland, Oregon, and on Writing Day, we'll have an area where people can learn about and help contribute to docs for Netlify CMS.

So where could we really use some docs help?

I'll definitely be pointing people to the `area: docs` [tagged issues](https://github.com/netlify/netlify-cms/labels/area%3A%20docs), with a few being especially good for folks new to the project:

- We need guides #2092
- Create a user guide for content editors #1340
- Improve contributing guidelines. #1038
- Add a style guide to documentation contributor info #1632
- Add a Requirements & Installation doc #731
- Add markdown widget to docs #637

Anything else we should highlight or request?

**Comment by erquhart** [comment]
I think this is a nice big handful already - thanks for opening this @verythorough!

**Comment by verythorough** [comment]
I've added our description to the [Write the Docs Writing Day page](https://www.writethedocs.org/conf/portland/2019/writing-day/#netlify-cms-give-feedback-and-write-docs), and added a [new tag](https://github.com/netlify/netlify-cms/labels/event%3A%20Write%20the%20Docs) for issues to highlight at the event.

Looking forward to it!
