### ISSUE TITLE
Connecting Netlify Functions to CMS

### ISSUE THREAD

**Issue by elie222** [netlify/netlify-cms#2309]
Is it possible to use easily connect Netlify CMS to Netlify Functions?

For example, scrape a website using a Function and add entries to the CMS from it?

**Comment by talves** [comment]
I am not sure that would be a core functionality of Netlify CMS. Curious what your workflow would be there.

You would have to modify one of the backends, depending on which one you were using to get the entries and put them into the CMS. I don't see that really scaling well and how would you track what you had already put into the CMS.

**Comment by elie222** [comment]
I guess you would check the GitHub repo to see if a certain file exists. If
it doesn’t you’d add a new file. Basically what you can do by hand right
now, just this would run automatically using a Function.

In practice if I look at the network tab when adding an item in the CMS,
that’s the api I’d be looking to use. Or would it make sense to connect
directly to GitHub and use their API?

**Comment by talves** [comment]
The only choice you have, If you want it done through the CMS is to extend one of the backends and do it that way. I am not recommending you do that, but it would be the only option in this case. There is not really an outside API you could plug into to accomplish what you are trying to do.  The outside direct approach might be a better option for you.

**Comment by kennedyrose** [comment]
We do something similar to this using the GitHub API. You can add/remove your markdown files there without needing to go through the CMS.

**Comment by elie222** [comment]
What does the api add beyond just committing and pushing files? Or is that
what you’re talking about?

**Comment by kennedyrose** [comment]
That's it. But I'm assuming that's all you need. Once you've done that they will also be in the CMS since the CMS entries are files.
