### ISSUE TITLE
Image fails to upload - Branch protection rule(s)

### ISSUE THREAD

**Issue by timarney** [netlify/netlify-cms#2310]
**Error:**

When trying to upload an image when Github branch protection rule(s) are in place i.e requires approval we get the following error message.
```
API_ERROR: 2 of 2 required status checks are expected. At least 1 approving review is required by reviewers with write access.
```

<img width="976" alt="Screen Shot 2019-05-01 at 11 29 07 AM" src="https://user-images.githubusercontent.com/62242/57025363-eccc6d00-6c04-11e9-88ae-48b5e5cf8e4c.png">

**To Reproduce:**

- Step 1:  Create a new Post
- Step 2: Try to upload an image (even with no PR at this point)

**Details:**
 - Netlify CMS version:  "netlify-cms": "^2.9.1",
 - GitHub
 
**Notes:**
- If I fork the repo + removing the rules I can upload images.

**Comment by erquhart** [comment]
Will be resolved by https://github.com/netlify/netlify-cms/issues/1344.
