### ISSUE TITLE
'Welcome to Netlify' operation fails on first step

### ISSUE THREAD

**Issue by aplatypus** [netlify/netlify-cms#2311]
On the [`Welcome to Netlify`](https://app.netlify.com/start/deploy?repository=https://github.com/JavaEden/OrchidStarter) quick start web page, After clicking the button: [`Connect to GitHub`], psge:

- https://app.netlify.com/start/deploy?repository=https://github.com/JavaEden/OrchidStarter

The app. opnens a page adn reports that the app. is authorised.  There are no buttons on that page and no menu or indication of what to do next.
- https://api.netlify.com/auth/done?code=XXXXX&state=zzzzzzz

Nothing has been created in github, etc.

Step #2 on the [`Welcome to Netlify`](https://app.netlify.com/start/deploy?repository=https://github.com/JavaEden/OrchidStarter) page states that, I should configure my site.  In that sense I had expected to see something created under my GitHub account or at least something to download and for me to do an edit or configure.

From what I can tell, the operation has not produced a result.

**Describe the bug**

As stated above the [`Welcome to Netlify`](https://app.netlify.com/start/deploy?repository=https://github.com/JavaEden/OrchidStarter) has failed to produce/perform any result/its apparent function.

**To Reproduce**

Steps to reproduce the behaviour:

1. [`Welcome to Netlify`](https://app.netlify.com/start/deploy?repository=https://github.com/JavaEden/OrchidStarter)
  - `https://app.netlify.com/start/deploy?repository=https://github.com/JavaEden/OrchidStarter`
2. Click on '[`Connect to GitHub`]' button
3. Allow the app to open GitHub or check
4. A authorize screen appears
5. Check your git hub account 
   -  nothing has happened.

**Expected behavior**
- Expected a project to be created or
- Some further steps to follow in order to be able to configure my project.

**Screenshots**

(none)

**Applicable Versions:**

(not applicable)

**CMS configuration**

(not applicable)

**Additional context**
- running firefox standards based browser

**Comment by tomrutgers** [comment]
Although the [starter](https://github.com/JavaEden/OrchidStarter) you mention includes Netlify CMS, that repo isn't being maintained by the development team. It seems highly unlikely that this issue is caused by the CMS. Try asking your question in the [community forum](http://community.netlify.com).
