### ISSUE TITLE
Incorrect preview url generated for single repository multi-site setup

### ISSUE THREAD

**Issue by mrlubos** [netlify/netlify-cms#2315]
**Describe the bug**
When using a single repository to deploy multiple sites, Netlify CMS uses an incorrect preview URL in the editor header after saving a draft post.

**To Reproduce**
1. Have sites A (https://a.com) and B (https://b.com) on Netlify.
2. Use a single repository to build these websites. I don't mean have 2 websites in a single repository (2 subfolders), it's a single website (100% shared source code). Site-specific values like target URL change during the build process from environment variables. In Netlify, we do `TARGET_URL=a npm run build` and `TARGET_URL=b npm run build` respectively.
3. Edit an existing post on B and click Save.
4. Observe the preview URL redirects you to A.

**Expected behavior**
Preview URLs should point to the correct pull request preview.

**Screenshots**

N/A

**Applicable Versions:**

 - Netlify CMS version: 2.9.1
 - Git provider: GitHub
 - OS: Netlify
 - Browser version Chrome Version 74.0.3729.131 (Official Build) (64-bit)

 - Node.JS version:
- Gatsby plugin Netlify CMS: 3.0.17

**CMS configuration**

We have `configy_a.yml` and `config_b.yml` which defines its collections. The collection definitions don't use any preview path configuration. Shared configuration is done in `cms/cms.js` like this.

```js
const site = getSite();

init({
  config: {
    backend: {
      branch: 'master',
      name: 'git-gateway',
    },
    display_url: site.displayUrl, // https://a.com or https://b.com
    logo_url: 'path/to/logo.jpg',
    media_folder: 'path/to/media',
    public_folder: 'path/to/public',
    publish_mode: 'editorial_workflow',
    site_url: site.siteUrl, // https://a.com or https://b.com
  },
});
```

**Additional context**

**Comment by erquhart** [comment]
Ah - the CMS grabs the first available status check that contains our internal list of keywords: https://github.com/netlify/netlify-cms/blob/9d5dbcde0a49dd50d0b6672bf424c05810eadca5/packages/netlify-cms-backend-github/src/implementation.js#L12

As you can see, the list currently consists of "deploy", so it will match both of the Netlify status checks on your pull requests, and just return the first one. This very repo also has two Netlify sites, so a PR will receive two statuses - notice the unique context strings for each:

<img width="718" alt="Screen Shot 2019-05-09 at 3 13 25 PM" src="https://user-images.githubusercontent.com/2112202/57480334-6a2f5780-726d-11e9-997f-fc7873f1e4a9.png">

I forgot to document this, but you can configure the exact context to look for amongst the statuses via the backend config using `preview_context`. You'll need to specify the entire context string. Based on the contexts in the image above, for example, I might do:

```yaml
backend:
  name: github
  preview_context: netlify/netlify-cms-www/deploy-preview
```

**Comment by mrlubos** [comment]
@erquhart Great, thank you! I’ll try and update this issue

**Comment by mrlubos** [comment]
Hi @erquhart, I can confirm this fixes the preview issue!

```js
const site = getSite();

init({
  config: {
    backend: {
      branch: 'master',
      name: 'git-gateway',
      preview_context: `netlify/${site.id}/deploy-preview`,
    },
    display_url: site.displayUrl, // https://a.com or https://b.com
    logo_url: 'path/to/logo.jpg',
    media_folder: 'path/to/media',
    public_folder: 'path/to/public',
    publish_mode: 'editorial_workflow',
    site_url: site.siteUrl, // https://a.com or https://b.com
  },
});
```

However, I observed another issue I have not previously noticed. I wonder if you know how to solve this one, too? Assume we have the same websites A and B and they look the same, just using a different copy. Both A and B use template `homepage` to render the homepage content. We go into CMS B and create a draft for updated homepage.

The issue:

If we go into CMS A and open the homepage, it shows us the draft from CMS B. When we inspect the pull request in repository, it is obvious it modifies only content from site B. Why does it then show up in CMS A?

Further observations:

Modifying this file from CMS A works as you'd expect. This means we are able to modify files related to site B from site A. Furthermore, in the Workflow tab, we see all of the drafts from site B.

Expected result:

Complete ability to sandbox sites A and B.

**Comment by erquhart** [comment]
CMS instances don't have any special ownership of the content they edit, they're simply driven by their configuration, just like whatever static site generator your using. However the SSG tells the content apart is likely the same way you'll need to configure the CMS to target the right content.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mrlubos** [comment]
@erquhart Gotcha, it will be Gatsby/GraphQL related issue I suppose. Thanks a lot!

**Comment by erquhart** [comment]
Generally you'll handle it by keeping site A and B content in separate directories, or by using `filter` in your collection configuration to only show entries that have a given value, eg. if all site a entries had `site: "a"` and site b had `site: "b"` in their frontmatter, you could filter for that: https://www.netlifycms.org/docs/collection-types/#filtered-folder-collections

**Comment by mrlubos** [comment]
@erquhart Yes, that's how I handle it! The issue isn't that I see the wrong collections in the CMS, but when I open say page "index" located in `src/pages/a/index.md`, if there is an existing draft (pull request) from `src/pages/b/index.md`, that will get previewed in the CMS editor. Any subsequent changes including save/delete are incorrectly performed on this B file. The only thing that could be wrong that comes to mind right now is checking GraphQL frontmatter query.

**Comment by mrlubos** [comment]
@erquhart I managed to solved the other issue described above. FYI, the problem was that while I was generating different `config.yml` file for sites A and B, it used the same `name` values for `index.md`, i.e. `index`. All I had to do was to namespace `name` keys in `config.yml`, i.e. `site-a-index` and `site-b-index`. Everything works now as expected.
