### ISSUE TITLE
Edit and publish roles per Content type

### ISSUE THREAD

**Issue by ctsimpouris** [netlify/netlify-cms#2319]
**Is your feature request related to a problem? Please describe.**
I want to invite authors to submit an article, but they should have limited functionality.

**Describe the solution you'd like**
It would be ideal if we could set in yml config file CRUD permissions (create/update/delete/publish). For example "create: blog_editor, blog_admin", "update: blog_editor, blog_admin", "delete: blog_admin", "publish: blog_admin"

**Describe alternatives you've considered**
Mixing up GitHub roles/permission is a no-go for me, as authors may come and go in the future

**Comment by erquhart** [comment]
Related: #2

**Comment by erquhart** [comment]
This is now supported through [Open Authoring](https://www.netlifycms.org/docs/open-authoring/).
