### ISSUE TITLE
Failed to deploy

### ISSUE THREAD

**Issue by 8luebottle** [netlify/netlify-cms#2329]
**failed during stage 'building site': Build script returned non-zero exit code: 127**

Please help, I'm stuck on deploy issue.
Here's my deploy log.

11:42:07 PM: Build ready to start
11:42:09 PM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
11:42:09 PM: build-image tag: v3.3.2
11:42:09 PM: buildbot version: 75cd99f62ada9e21edea53208e8baf0eab85a045
11:42:09 PM: Fetching cached dependencies
11:42:09 PM: Starting to download cache of 255.1KB
11:42:09 PM: Finished downloading cache in 124.186146ms
11:42:09 PM: Starting to extract cache
11:42:09 PM: Failed to fetch cache, continuing with build
11:42:09 PM: Starting to prepare the repo for build
11:42:10 PM: No cached dependencies found. Cloning fresh repo
11:42:10 PM: git clone https://github.com/8luebottle/Baby_Tiger
11:42:13 PM: Preparing Git Reference refs/heads/master
11:42:13 PM: Found netlify.toml. Overriding site configuration
11:42:13 PM: Starting build script
11:42:13 PM: Installing dependencies
11:42:15 PM: v10.15.3 is already installed.
11:42:15 PM: Now using node v10.15.3 (npm v6.4.1)
11:42:15 PM: Attempting ruby version 2.6.2, read from environment
11:42:17 PM: Using ruby version 2.6.2
11:42:17 PM: Using PHP version 5.6
11:42:17 PM: Started restoring cached node modules
11:42:17 PM: Finished restoring cached node modules
11:42:17 PM: Installing NPM modules using NPM version 6.4.1
11:42:22 PM: npm
11:42:22 PM: WARN
11:42:22 PM:  deprecated joi@12.0.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
11:42:24 PM: npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
11:42:25 PM: npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
11:42:25 PM: npm WARN deprecated
11:42:25 PM:  topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
11:42:26 PM: npm WARN deprecated
11:42:26 PM:  joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
11:42:27 PM: npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
11:42:31 PM: npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
11:43:17 PM: > sharp@0.22.1 install /opt/build/repo/node_modules/sharp
11:43:17 PM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
11:43:18 PM: info
11:43:18 PM: sharp
11:43:18 PM:  Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linux-x64.tar.gz
11:43:20 PM: > node-sass@4.12.0 install /opt/build/repo/node_modules/node-sass
11:43:20 PM: > node scripts/install.js
11:43:20 PM: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/linux-x64-64_binding.node
11:43:22 PM: Download complete
11:43:22 PM: Binary saved to /opt/build/repo/node_modules/node-sass/vendor/linux-x64-64/binding.node
11:43:22 PM: Caching binary to /opt/buildhome/.npm/node-sass/4.12.0/linux-x64-64_binding.node
11:43:23 PM: > gatsby-telemetry@1.0.9 postinstall /opt/build/repo/node_modules/gatsby-telemetry
11:43:23 PM: > node src/postinstall.js
11:43:23 PM: > cwebp-bin@5.0.0 postinstall /opt/build/repo/node_modules/cwebp-bin
11:43:23 PM: > node lib/install.js
11:43:24 PM:   ✔ cwebp pre-build test passed successfully
11:43:24 PM: > mozjpeg@6.0.1 postinstall /opt/build/repo/node_modules/mozjpeg
11:43:24 PM: > node lib/install.js
11:43:24 PM:   ✔ mozjpeg pre-build test passed successfully
11:43:24 PM: > pngquant-bin@5.0.2 postinstall /opt/build/repo/node_modules/pngquant-bin
11:43:24 PM: > node lib/install.js
11:43:25 PM:   ✔ pngquant pre-build test passed successfully
11:43:25 PM: > node-sass@4.12.0 postinstall /opt/build/repo/node_modules/node-sass
11:43:25 PM: > node scripts/build.js
11:43:25 PM: Binary found at /opt/build/repo/node_modules/node-sass/vendor/linux-x64-64/binding.node
11:43:25 PM: Testing binary
11:43:25 PM: Binary is fine
11:43:30 PM: npm
11:43:30 PM:  notice created a lockfile as package-lock.json. You should commit this file.
11:43:30 PM: npm WARN eslint-config-react-app@3.0.8 requires a peer of babel-eslint@9.x but none is installed. You must install peer dependencies yourself.
11:43:30 PM: npm WARN ts-pnp@1.1.2 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
11:43:30 PM: npm WARN netlify-cms-backend-test@2.2.2 requires a peer of immutable@^3.8.2 but none is installed. You must install peer dependencies yourself.
11:43:30 PM: npm WARN
11:43:30 PM:  react-redux@4.4.10 requires a peer of redux@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
11:43:30 PM: npm WARN slate@0.34.7 requires a peer of immutable@>=3.8.1 but none is installed. You must install peer dependencies yourself.
11:43:30 PM: npm WARN slate-edit-list@0.11.3 requires a peer of immutable@^3.8.2 but none is installed. You must install peer dependencies yourself.
11:43:30 PM: npm WARN slate-edit-list@0.11.3 requires a peer of slate@^0.32.0 but none is installed. You must install peer dependencies yourself.
11:43:30 PM: npm WARN
11:43:30 PM:  slate-edit-table@0.15.2 requires a peer of immutable@^3.8.1 but none is installed. You must install peer dependencies yourself.
11:43:30 PM: npm WARN
11:43:30 PM:  slate-edit-table@0.15.2 requires a peer of slate@^0.33.3 but none is installed. You must install peer dependencies yourself.
11:43:30 PM: npm WARN slate-plain-serializer@0.5.41 requires a peer of immutable@>=3.8.1 but none is installed. You must install peer dependencies yourself.
11:43:32 PM: failed during stage 'building site': Build script returned non-zero exit code: 127
11:43:30 PM: npm WARN slate-react@0.12.9 requires a peer of immutable@>=3.8.1 but none is installed. You must install peer dependencies yourself.
11:43:30 PM: npm
11:43:30 PM: WARN slate-prop-types@0.4.67 requires a peer of immutable@>=3.8.1 but none is installed. You must install peer dependencies yourself.
11:43:30 PM: npm
11:43:33 PM: Shutting down logging, 34 messages pending

**Comment by talves** [comment]
From initial analysis, your build command is `yarn build` in the `netlify.toml` file and you do not have a yarn.lock file in your repository. If you don't want to use yarn, make sure to change the build command to the correct build command.

Netlify uses the yarn.lock to identify that yarn must be installed and setup for the build.

**Comment by 8luebottle** [comment]
Thank you for your help.
I changed the build command as "gatsby build", but still has same error msg.


12:43:36 AM: Different build command detected, going to use the one specified in the toml file: 'yarn build' versus 'gatsby build' in the site
12:44:48 AM: failed during stage 'building site': Build script returned non-zero exit code: 127

**Comment by 8luebottle** [comment]
Solved.
