### ISSUE TITLE
cannot add user

### ISSUE THREAD

**Issue by arashbi** [netlify/netlify-cms#2334]
**Describe the bug**

I invited a new user to my application. When I click on the invite to accept it, it simply goes to my home page. 

When I try to login,it shows me an error page with this content 

`Invariant Violation: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=t%3A%20invalid_grant%3A%20Email%20not%20confirmed&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

**To Reproduce**

I am not really sure how to reproduce it. But it consistently happens in my repo.

**CMS configuration**

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "posts"
    label: "Post"
    folder: "content/post"
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Background", name: "background", widget: "image" }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

**Additional context**

This is a new Hugo site.

**Comment by tomrutgers** [comment]
What version of the cms are you using? It’s being logged in the console.

**Comment by arashbi** [comment]
it was a misconfiguration on my side.

**Comment by rvanzon** [comment]
@arashbi I am facing the same error. Can you maybe explain what you misconfigured? thanks!
