### ISSUE TITLE
Dependency for babel-plugin-inline-svg fails Node >= 12

### ISSUE THREAD

**Issue by talves** [netlify/netlify-cms#2345]
**Describe the bug**

When running `yarn` using Node 12 on Windows (presumably all OS's) the dependencies fail on `gatsby-plugin-inline-svg` for sub dep `deasync` build using node-gyp.

**To Reproduce**

Upgrade local node version to 12

**Expected behavior**

Should download and build dependencies without errors

**Screenshots**

![image](https://user-images.githubusercontent.com/784848/58388306-fd88bc80-7fd1-11e9-8b9d-b506f4dd813b.png)

**Applicable Versions:**

 - Netlify CMS version: latest
 - OS: Windows 10

 - Node.JS version: 12.3.1

**_Caveat_**: The solution here does not solve `netlify-cms-site`. **The website still fails.** See https://github.com/netlify/netlify-cms/issues/2358

**Comment by talves** [comment]
Confirmation there was an issue with `deasync` fixed:
https://github.com/abbr/deasync/issues/114

**Comment by erquhart** [comment]
Ah so that's what's causing it - is there a fix?

**Comment by talves** [comment]
Unfortunately this is a dependency in the website. 

No, there is not a fix for it and would require 2 packages deep to apply the change and update of the dependency. First level in https://github.com/Yukaii/synchronized-promise/issues/6

Maybe a different package for inline svg would be the way to solve this one.

**Comment by talves** [comment]
https://github.com/Yukaii/synchronized-promise/issues/6 fixed. Now on to `babel-plugin-inline-svg`

https://github.com/iest/babel-plugin-inline-svg/issues/3

https://github.com/iest/babel-plugin-inline-svg/pull/4

**Comment by talves** [comment]
Fixing this issue will solve the ability to develop under Node 12 for the monorepo, so I have split the 2 issues (monorepo vs site).

I think since we are building the site in a different build process and can target a lower version of node until it is fixed, these issues can stay separate.

**Comment by talves** [comment]
PR issued for `babel-plugin-inline-svg@v1.0.1` fix. 🎉
