### ISSUE TITLE
Reduce the number of permissions requested from Github

### ISSUE THREAD

**Issue by MrSwitch** [netlify/netlify-cms#2348]
**Problem**
Yes, i have sensitive data on other repositories and am unable to grant access to the Netlify CMS when i go to `/admin` i'm asked for too many permissions.

> This application will be able to read and write all public and private repository data

**Solution**
Change the permissions to be restricted to the current repo.

**Additional context**
![Screen Shot 2019-05-29 at 13 25 54](https://user-images.githubusercontent.com/947163/58557035-509e8180-8215-11e9-99ba-f9b48f1853e6.png)

**Comment by talves** [comment]
Thanks @MrSwitch 

Please track at this issue (duplicate): https://github.com/netlify/netlify-cms/issues/1423
