### ISSUE TITLE
Using netlify-cms-widget-markdown standalone

### ISSUE THREAD

**Issue by tampham47** [netlify/netlify-cms#2349]
**Is your feature request related to a problem? Please describe.**

It's a feature request. 

I really like the `netlify-cms-widget-markdown`, and I would like to use this widget on my website only. It will connect with my universal react application as a component. But I dont know how to init this widget standalone.

**Describe the solution you'd like**
I have no idea

**Describe alternatives you've considered**
I have no idea

**Additional context**
Maybe this request is not required any code changes.

**Comment by erquhart** [comment]
This isn't a use case that we're actively supporting at the moment, but I just happened to have done this in a codesandbox recently, hope it helps!

https://codesandbox.io/s/jl70q5qvmy
