### ISSUE TITLE
Unable to set up Netlify CMS on gitpod.io

### ISSUE THREAD

**Issue by JamesGreenaway** [netlify/netlify-cms#2351]
**Describe the bug**

I have completed all the instructions to set up Netlify CMS on my project.  It works fine when hosted on Netlify.  When I try and authorize Netlify CMS locally on gitpod.io I am unable to authorize it.  I says "Login with Netlify Identity" but when I click it nothing happens, it just goes grey. I have had more success when following the instructions to set up a "Git Gateway without Netlify", but ultimately that did not work either.  Can somebody please have a look at my repo (linked below), and explain to me like I'm five if I am doing something wrong.  
**To Reproduce**

Follow the instructions on https://www.netlifycms.org/docs/add-to-your-site/#app-file-structure and https://www.netlifycms.org/docs/authentication-backends/
**Expected behavior**

I would expect the go through some form of authorization and then for that window to close and for the Netlify CMS to start.  
**Screenshots**

![Screenshot 2019-05-30 at 6 36 15 PM](https://user-images.githubusercontent.com/16066511/58651707-e0bdf300-8309-11e9-9300-c59deb3afbed.png)

**Applicable Versions:**

 - Netlify CMS version:  2.9.1
 - Git provider:  GitHub
 - OS: Linux (gitpod.io)
 - Browser version Chrome 74

 - Node.JS version: 10.15.3

**CMS configuration**

https://github.com/JamesGreenaway/victor-hugo

**Additional context**

 
I am using gitpod.io as opposed to localhost.

**Comment by erquhart** [comment]
You won't be able to do this from gitpod, or any online ide, without setting up your own auth solution. Using actual localhost is supported by an auth setup specifically for localhost urls by Netlify, but on Gitpod you're not using a localhost url. There are community libraries for setting up an auth server if you're interested: https://www.netlifycms.org/docs/authentication-backends/#external-oauth-clients

Setting up Git Gateway on your own is not currently for the faint of heart, but if you want to try your hand, here's the best resource I'm aware of to get your started: https://github.com/hfte/netlify-cms-with-selfhosted-gotrue-and-git-gateway

**Comment by JamesGreenaway** [comment]
ok thanks for your help
