### ISSUE TITLE
[netlify-cms-site]: Fails to build - Node 12

### ISSUE THREAD

**Issue by talves** [netlify/netlify-cms#2358]
**To Reproduce**

Upgrade local node version to 12

Run terminal in `website` directory and run yarn && yarn build

**Expected behavior**

Should setup the dependencies and build the site.

**Considerations**

This is a Gatsby site and not part of the monorepo. Upgrading Gatsby and plugin to newer versions would be the first thing to try and see if the dependency issues (under Node 12) get resolved.

**Comment by erquhart** [comment]
Should be resolved by #2068.

**Comment by erezrokah** [comment]
Closing as stale
