### ISSUE TITLE
TypeError: Cannot read property 'publicURL' of undefined

### ISSUE THREAD

**Issue by a18wheeler** [netlify/netlify-cms#2361]
**Describe the bug**

TypeError occurs in the Netlify CMS preview panel despite the fact that the property 'publicURL' is properly read and used to display a pdf on the index page. Netlify CMS works for changing the URL, but does not work to view it.

**To Reproduce**
1. [Clone this repo](https://github.com/a18wheeler/gatsby-starter-netlify-cms.git)
2. Set it up for Netlify CMS and Netlify
3. Use `yarn`
4. Go to Netlify URL for page.
5. Add a '/admin/' at the end of your URL
6. Click on Pages -> Landing Page
7. Error should be visible on the preview panel

**Expected behavior**

I expect the pdf to show without any error.
**Screenshots**

![image](https://user-images.githubusercontent.com/10427186/59144317-cd5ef780-899b-11e9-9f41-748f56b5de1b.png)

**Applicable Versions:**

 - Netlify CMS version: 2.9.0
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version Chrome 75.0.3770.80

 - Node.JS version: 10.5.1

**CMS configuration**

Only including the important part.
```markdown
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: File, name: file, widget: file}
```

**Additional context**

**Comment by erquhart** [comment]
It's saying `file` isn't defined. In your template you have your query set up to look for a `publicURL` field on the `file` value, but `file` is a string: https://raw.githubusercontent.com/a18wheeler/gatsby-starter-netlify-cms/72b8fa7e2b768184c1490280849981989ec8b15c/src/pages/index.md

**Comment by erquhart** [comment]
Wherever `publicURL` is coming from (maybe a Gatsby plugin handling the PDF?), Netlify CMS doesn't have it, you'll need to provide it.

**Comment by a18wheeler** [comment]
> It's saying `file` isn't defined. In your template you have your query set up to look for a `publicURL` field on the `file` value, but `file` is a string: https://raw.githubusercontent.com/a18wheeler/gatsby-starter-netlify-cms/72b8fa7e2b768184c1490280849981989ec8b15c/src/pages/index.md

How should it be interpreted if not as a string? I was just trying to copy was already done with the images in this template, since the file widget isn't that dissimilar. 
 
> Wherever publicURL is coming from (maybe a Gatsby plugin handling the PDF?), Netlify CMS doesn't have it as it isn't in your content file, which is the only thing Netlify CMS looks at.

How do you add it to the content file? As you said, Gatsby is handling this using a plugin. The plugin is **gatsby-transformer-remark**.

**Comment by erquhart** [comment]
You're importing `IndexPageTemplate` from the browser, I honestly don't know how it got this far. That module imports Node stuff like `gatsby-link`. You'll need to customize your preview template to work in the browser.

**Comment by erquhart** [comment]
*checks the stock gatsby netlify cms template*

😱 

I do not know when that was introduced but it shouldn't be working. Looking into it now.

**Comment by erquhart** [comment]
Ah, that template is fine, been away from this repo for too long.

It's saying `file` is undefined because it is - you have to pass `file` as a prop into `IndexPageTemplate`: https://github.com/a18wheeler/gatsby-starter-netlify-cms/blob/master/src/templates/index-page.js#L83

Going to close this as it's an implementation issue, but feel free to reach out in Gitter chat or the [Netlify community](https://community.netlify.com/c/netlify-platform/netlify-cms) if you need further assistance on it.
