### ISSUE TITLE
HTTP/2 protocol not implemented correctly

### ISSUE THREAD

**Issue by ioquatix** [netlify/netlify-cms#2369]
https://github.com/socketry/async-http/issues/23

According to RFC7540:

>   An endpoint that receives a SETTINGS frame with any unknown or
>   unsupported identifier MUST ignore that setting.

But when using the [new setting defined by RFC8441](https://tools.ietf.org/html/rfc8441#section-3) results in `Goaway` on any connection using HTTP/2.

**Comment by erquhart** [comment]
This is the repo for Netlify CMS. It looks like Netlify support is in the loop in the issue you linked, so I'll go ahead close this.
