### ISSUE TITLE
Image upload does not work in Microsoft Edge

### ISSUE THREAD

**Issue by marcojakob** [netlify/netlify-cms#2379]
**Describe the bug**
The media library image upload does not work in Microsoft Edge (tried with version 42.17134.1.0 but I think it does not work in any version).

**To Reproduce**
1. Open Edge browser
2. Open the media library in the Netlify CMS
3. Click on `Upload new` and choose an image.
4. Nothing happens. The button just stays on `Upload new`.

**Applicable Versions:**
 - Netlify CMS version: netlify-cms-core 2.11.0
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version: Microsoft Edge 42.17134.1.0

**Additional context**
I know most developers won't use Edge but it is very relevant for schools and companies where content editors sometimes have to use Edge.

**Comment by erquhart** [comment]
Understood - we'll need someone with a Windows machine to check this out.

**Comment by austincondiff** [comment]
This may be related to #2425. Can you open your console and show us the output after you click the `Upload New` button?

**Comment by marcojakob** [comment]
@austincondiff This is the output in the console before I click the `Upload New` button. When I click on the Upload New button the file chooser is opened. Then when I choose an image and click `open`, the file dialog closes and I'm back to the media library. There is **no additional output on the console**. 

```
netlify-cms-app 2.9.5
netlify-cms.js (13,29247)

 netlify-cms-core 2.12.1
netlify-cms.js (143,12195)

 netlify-cms 2.9.5
netlify-cms.js (840,288492)

 ajv-errors: Ajv option jsonPointers changed to true
netlify-cms.js (187,81439)

 HTTP404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI (Uniform Resource Identifier) gefunden.
(Fetch)GET - https://www.marco-jakob.ch/.netlify/git/github/contents/.gitattributes?ts=1562353596542&ref=master

 HTTP404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI (Uniform Resource Identifier) gefunden.
(Fetch)GET - https://www.marco-jakob.ch/.netlify/git/github/contents/.lfsconfig?ts=1562353596542&ref=master
```

**Comment by barthc** [comment]
Looks like the `file` input issue has been fixed on the browser side. Tried on Microsoft Edge `44.18362.10` and the upload does work.

**Comment by marcojakob** [comment]
@barthc You are right! Awesome. Now I just need to convince the schools to update the Edge browser (or change it...).
