### ISSUE TITLE
Is it possible to give posts to a separate file name other than post title

### ISSUE THREAD

**Issue by sandhyadevadas** [netlify/netlify-cms#2384]
Is it possible to give posts to a separate file name other than post title? My title name is too long to accept gitlab shared runner, any way to give a small file name to the post?

**Comment by marcojakob** [comment]
See https://github.com/netlify/netlify-cms/issues/445

**Comment by marcojakob** [comment]
Current workaround: Save with a small title first and then go back to the post and change the title.

**Comment by sandhyadevadas** [comment]
Thanks for the fix...

**Comment by erquhart** [comment]
Actually you can configure the slug to use any field, so one option is to have a field specifically for that purpose: https://www.netlifycms.org/docs/configuration-options/#slug

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
