### ISSUE TITLE
Footnote and abbreviation markdown syntax unnecessarily escaped

### ISSUE THREAD

**Issue by acrawford13** [netlify/netlify-cms#2386]
First off, thanks for all your hard work on this project :tada:

I'm having an issue with the markdown widget, I'm not sure if there's a reason for this behaviour?

**Describe the bug**
- Footnote and abbreviation syntax is escaped unnecessarily by the rich text editor

**To Reproduce**
- Go to any `markdown` field
- With "Rich text" setting selected, type a footnote or abbreviation:
```
some text[^ this is a footnote]
*[abbr]: this is an abbreviation
```
- Switch to "Markdown" setting, and the footnote and definition appear as follows:
```
some text\[^ this is a footnote]
\*\[abbr]: this is an abbreviation
```
- Try to fix in "Markdown" setting, by removing the slashes:
```
some text[^ this is a footnote]
*[abbr]: this is an abbreviation
```
- Switch back to "Rich text" setting and change some unrelated text, the characters will be escaped again.

**Expected behavior**
Character combinations `[^` and `*[` should not be escaped

**Applicable Versions:**
 - Netlify CMS version: 
`netlify-cms-app 2.9.1`
`netlify-cms-core 2.11.0`
 - Git provider: GitHub
 - OS: Ubuntu 18.04
 - Browser version: Chrome 73

 - Node.JS version: 10.15.0

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "src/images/uploads"
collections:
  - name: "all-guides"
    label: "All guides"
    folder: "src/content/guides"
    slug: "{{slug}}"
    create: false
    fields:
      - {label: "Language", name: "language", widget: "select", options: [{label: "English", value: "en"}, {label: "Portuguese", value: "pt"}]}
      - {label: "Template key", name: "templateKey", widget: "hidden", default: "guides"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {
          label: "Translations",
          name: "translations",
          widget: "relation",
          collection: "all-guides",
          displayField: ["title", "language"],
          searchField: "title",
          valueField: "title",
          required: false,
          multiple: true
        }
```

**Additional context**

- I worked around the abbreviation issue by registering an editor component (see below), this stops the rich text editor from escaping the characters, but I can't do the same for the footnote because it needs to be inline with the rest of the text.
```
CMS.registerEditorComponent({
  id: 'definition',
  label: 'Definition',
  fields: [
    { name: 'text', label: 'Text', widget: 'string' },
    { name: 'definition', label: 'Definition', widget: 'string' },
  ],
  pattern: /^\*\[(.*?)\]: (.*?)$/,
  fromBlock: function(match) {
    return {
      text: match[1],
      definition: match[2],
    };
  },
  toBlock: function(obj) {
    return '*[' + obj.text + ']: ' + obj.definition;
  },
  toPreview: function(obj) {
    return '*[' + obj.text + ']: ' + obj.definition;
  },
});
```
If anyone knows of a workaround other than changing to a `text` widget instead of `markdown` I would be eternally grateful :bowing_woman:

**Comment by erquhart** [comment]
That's due to a [custom plugin](https://github.com/netlify/netlify-cms/blob/f801b192211b1e1953ced969a3093eab9e04e14d/packages/netlify-cms-widget-markdown/src/serializers/remarkEscapeMarkdownEntities.js) that I wish I could eliminate, I can't imagine it not having bugs - there's no lib out there for escaping the proper markdown characters from a string of plain text. I may be able to resolve this in #2402.

**Comment by grdpr** [comment]
Hey @acrawford13! Did you find a trick to fix this escape bug between markdown and rich text editor? 
I'm facing the same problem. For now, I'm doing the footnotes manually with Link to #footnote1, #footnote2 ...

**Comment by shihokambara** [comment]
Facing the same problem, too.

**Comment by acrawford13** [comment]
Sorry @grdpr, I never found a way around this :disappointed:... I ended up getting rid of the rich text editor altogether.

**Comment by grdpr** [comment]
Indeed it's a good solution but not for clients or editors :-(

**Comment by erquhart** [comment]
Reread this and I think there's a misunderstanding. I should have mentioned this earlier, but the rich text editor does not support footnotes currently. If you leave it in markdown mode, the footnotes will be left alone and will not be escaped, but they will be interpreted literally in the preview pane.

So the workaround is to leave the editor in raw markdown mode.

**Comment by grdpr** [comment]
It's totally clear that the rich text editor doesn't support. 
The only weird behavior is when you pass from markdown editor to rich editor. The rich editor is adding a escape character "/" to the footnotes written in the markdown editor. 
Indeed it's better to stay in markdown mode but we're loosing some users…

**Comment by erquhart** [comment]
Fair, our escaping is being overzealous - if you're up for taking a swing, the replacements are happening here: https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-widget-markdown/src/serializers/remarkEscapeMarkdownEntities.js

**Comment by Undistraction** [comment]
@erquhart I'd like to take a run at fixing this. Please could you give me a brief overview of the issue from your perspective? 

We need to allow non-technical users to add images etc via the rich-text mode, but this results in all our footnotes and refs being escaped.
