### ISSUE TITLE
Netlify Forms: Invalid HTML of the hidden input element

### ISSUE THREAD

**Issue by JakubKoralewski** [netlify/netlify-cms#2396]
According to [this](https://www.netlify.com/docs/form-handling/#ajax-form-submissions) you add a hidden input element.[ A valid HTMLInputElement has no closing tag and is void, i.e. it's never closed.](https://www.w3schools.com/tags/tag_input.asp) However, for some reason inside my Netlify App using Netlify Forms when inserted the hidden HTMLInputElement looks like this:
```xhtml
<input type='hidden' name='form-name' value='contact-form' />
```

I've marked the above code snippet as XHTML, because this ^ is not valid HTML:
```
In HTML, the <input> tag has no end tag.
In XHTML, the <input> tag must be properly closed, like this <input />.
// https://www.w3schools.com/tags/tag_input.asp
```

It's causing an unexplicable error in Nuxt (Vue):
`DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.`

Because it's invalid Chrome tries to guess what's happening and does this:
![image](https://user-images.githubusercontent.com/43069023/59931569-8b2ac100-9445-11e9-8dc2-cccea5c35805.png)

It nests a text node and another HTMLInputElement inside of an HTMLInputElement, but since an Input Element is void it cannot have anything inside it and Vue does not know what's going on at this point!

It's very frustrating, because everything works fine on my development machine and the reason something goes wrong is something I cannot control. It's been a major source of frustration in my life for the last few hours :dagger:

**Comment by JakubKoralewski** [comment]
This may be the wrong place. Sorry! 

I've sent a message to the support here: https://www.netlify.com/support/
If anyone on the Netlify team can push this through faster I'd be much grateful so I'm not gonna close the issue until someone sees this and closes it themselves so it's not lost and you can push it through 😄

**Comment by tomrutgers** [comment]
You can also try the Netlify community: https://community.netlify.com/
