### ISSUE TITLE
Post limits?

### ISSUE THREAD

**Issue by HackGibson** [netlify/netlify-cms#2406]
Is there a limit on how many total posts NetlifyCMS can handle? The content/blogs folder in my Github repo can only handle displaying 1000 files. So does this mean NetlifyCMS can only allow me to access the last 1000 posts?

**Comment by erquhart** [comment]
We're only limited because we're using GitHub's Contents API instead of their Git Data API for fetching collections. Thanks for opening this, folks are running into it a lot lately.

**Comment by wildfalcon** [comment]
I ran into this problem too, so +1

I was able to work round it by putting my content into several collections. I'm lucky that this makes sense with my content. 

I also have the same issue with the media library, max 1000 images - which I assume is the same root cause

**Comment by wing5wong** [comment]
+1 on this - just ran into it

good to see an already open issue for it

**Comment by neilkinnish** [comment]
Has anyone worked around this issue?

**Comment by barthc** [comment]
@neilkinnish  you can try enabling the graphql [option](https://www.netlifycms.org/docs/beta-features/#github-graphql-api) which uses the `tree` object to list entries, limit should be more than 1k. @erezrokah, please confirm.

**Comment by erezrokah** [comment]
Good thinking @barthc. We do list the files using the `tree` object, but we still use the REST API for some other operations (mostly mutations).

Running this query in [GitHub GraphQL explorer](https://developer.github.com/v4/explorer/):

```
query { 
  repository(owner: "erezrokah", name:"gatsby-netlify-cms-aws-test") { 
    id
    object(expression: "test/many_files:content/posts") {
      id
      ...on Tree {
        entries {
          name
          
        }
      }
    }
  }
}
```

Does return 2000+ entries I created for this test.

@neilkinnish  do you mind changing to graphql to see if that works?

**Comment by barthc** [comment]
Nice, according to @erquhart  [here](https://github.com/netlify/netlify-cms/issues/68#issuecomment-355144258) limit should be 100k.

**Comment by erezrokah** [comment]
Haven't tested it, but the GraphQL limits seem to go by nodes:
https://developer.github.com/v4/guides/resource-limitations/

![image](https://user-images.githubusercontent.com/26760571/68412977-f4616580-0195-11ea-8e1c-0f1cba761125.png)

So maybe even 500k :)

**Comment by neilkinnish** [comment]
@barthc this works great! thanks.
