### ISSUE TITLE
my error

### ISSUE THREAD

**Issue by alanlengkoan** [netlify/netlify-cms#2412]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by tomrutgers** [comment]
Can you fill out the issue steps please? Otherwise we'll have to close this.

**Comment by alanlengkoan** [comment]
Done!

Pada tanggal Jum, 28 Jun 2019 23.17 Tom Rutgers <notifications@github.com
menulis:
