### ISSUE TITLE
Placeholder content for `test-repo` backend

### ISSUE THREAD

**Issue by lewnelson** [netlify/netlify-cms#2423]
**Is your feature request related to a problem? Please describe.**

I've been using the `test-repo` backend name value in the CMS config when running the CMS locally for developing the configuration file. However any collections referencing folders don't appear as obviously `test-repo` doesn't know where the content is.

Maybe I'm missing something, but the `test-repo` option doesn't seem to add much value.

**Describe the solution you'd like**

It would be nice for the CMS config to be fully fleshed out so you can test all the configurations. Each widget could have a placeholder value.

**Describe alternatives you've considered**

An alternative at the moment is working from deployment links using `git-gateway` (etc.) however it would be nice to do it all locally.

**Additional context**

How it looks in localhost
<img width="784" alt="localhost" src="https://user-images.githubusercontent.com/11139198/60664864-d5a33900-9e5a-11e9-91e1-6595aa4678a0.png">

How it looks on a deployment link
<img width="910" alt="deployment_link" src="https://user-images.githubusercontent.com/11139198/60664865-d63bcf80-9e5a-11e9-97de-6f85029d4cef.png">

Ideally localhost using `test-repo` would replicate how it looks on the deployment link, with the exception of the actual content value. These of course would need to be placeholder values.

**Comment by erquhart** [comment]
You're ultimately looking for local development support - it won't look the way you're describing, but it should meet your general requirements. You can track it here (thumb up the issue to vote for it as a priority): https://github.com/netlify/netlify-cms/issues/2335
