### ISSUE TITLE
Hide entry, list-item from Netlify CMS

### ISSUE THREAD

**Issue by austincondiff** [netlify/netlify-cms#2426]
I am using Gatsby. Gatsby generates Graphql queries based on the data in my markdown files. If a client goes and clears out a specific field in all entries in a collection, that will not be included in the generated query and break the site because I am referencing these fields in my queries. (gatsbyjs/gatsby#2392)

It seems like a workaround for now is to create a ghost entry and/or ghost item in a list input with all fields filled so that those fields are included in generated queries even though they may not exist at any given time.

Feels a little hacky but I am okay with doing this. I just need a way to hide the ghost entry from Netlify CMS so that clients do not delete it thinking that it is clutter or useless.

Maybe there is a different solution to the larger problem, but regardless it might still be beneficial to be able to hide entries and items in a list that you do not want to be editable/deletable.

So I propose there be different statuses for entries and list items: editable, editable but not deletable, hidden. You would manually add this in the markdown file of the entries or list items that you want to apply this status to. 

Thoughts?

**Comment by mrozilla** [comment]
I’m currently solving this through [manually defining the schema types](https://www.gatsbyjs.org/docs/schema-customization). This solves the issue, however, it requires a lot of duplicate data (the types are in the `config.yml` and have to be repeated in the Gatsby type def).

I can imagine this being a more elegant solution—solving it on the CMS’s end.

I’d be willing to take a stab at this if the maintainers point me in the right direction :) Regarding your proposal I don’t see a need for this field to be in the file as it’s only Netlify CMS that needs to know about this. The only need I can think of is preventing Gatsby from publishing this “demo” page which can be achieved through different means.

**Comment by erquhart** [comment]
I don't see us going this route, but the solution discussed in the comments of https://github.com/gatsbyjs/gatsby/issues/15707 would be viable. Closing in favor of that.
