### ISSUE TITLE
Poor handling of code blocks in the built-in renderer

### ISSUE THREAD

**Issue by fool** [netlify/netlify-cms#244]
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

when editing, the "rendered" version of the page on the right side live updates.  Some code blocks are interpreted as HTML despite being saved appropriately.

**- If the current behavior is a bug, please provide the steps to reproduce.**

put this in a code block:

```
<h1>GitHub Auth Demo:</h1>
      <p><a href="#" id="login">Authenticate</a></p>
```

and observe that it is parsed instead of being rendered as code.

**- What is the expected behavior?**

code looks like code in the preview :)

**- Please mention your node.js, and operating system version.**

built on netlify's installation (https://www.netlify.com/#/admin) on 23 Feb, so whatever version is there.  Built on linux/ubuntu 14.04 via netlify's build system

**Comment by erquhart** [comment]
Closing in favor of #246.
