### ISSUE TITLE
Broken search

### ISSUE THREAD

**Issue by bert-bruggeman** [netlify/netlify-cms#2441]
The search returns no results at all (Netlify-cms 2.9.6)

**Comment by erquhart** [comment]
Woah, when did that happen?? Confirmed.

**Comment by barthc** [comment]
@erquhart  #2391 broke the search, particularly these changes https://github.com/netlify/netlify-cms/pull/2391/files#diff-0a4edec7fc3efe854619b74a6a9aa300R133-R138

**Comment by bert-bruggeman** [comment]
Nice job!
