### ISSUE TITLE
Navigating away from page error.

### ISSUE THREAD

**Issue by EthosKyle** [netlify/netlify-cms#2443]
ERROR MESSAGE:
---
pathKey: health
templateKey: blog-single-template
title: Eat Healthier In 5 Easy Steps
url: eat-healthier-in-5-easy-steps
pageMetadata:
  metaPageDescription: >-
    With the countless myths and fad diets flooding the health industry, it can
    seem difficult to fix your diet. Learn how to get started in 5 easy steps. 
  metaPageKeywords: 'cooking, health, wellness'
  metaPageTitle: Eat Healthier In 5 Easy Steps
  pageMetaRobots: crawl
  pageSocialImage: >-
    https://res.cloudinary.com/getethos/image/upload/v1563216643/01_Lifestyle/life-insurance-01-older-couple-cooking.jpg
pageLayout:
  - authorName: Diana Murphy
    categoryLabel: Health
    displayAuthorName: true
    displayCategoryLabel: true
    displayPublishDate: true
    heading: Eat Healthier In 5 Easy Steps
    publishDate: July 15 2019
    type: HeaderSemiversatile
  - image: >-
      https://res.cloudinary.com/getethos/image/upload/v1563216643/01_Lifestyle/life-insurance-01-older-couple-cooking.jpg
    imageStyle: FullWidth
    type: BlogImage
  - blogIntro: >-
      With the countless myths and fad diets flooding the health industry, it
      can seem difficult to fix your diet—but it doesn’t have to be. Whether the
      goal of eating healthier was your New Year’s resolution or has been a
      lifelong goal, there are small adjustments you can make today that will
      get your nutrition in tip-top shape.

      Below, we outlined a few easy steps for eating better into your daily
      routine and the immediate and long-term benefits of doing so. 
    blogMarkdown: >-
      ## How To Start Eating Healthier

      Eating healthy isn’t always easy (or, at times, even possible depending on
      your circumstances). But there are a few simple steps you can take to help
      you get started. Committing to a goal of incorporating more “health” foods
      into your diet can be as simple as trading in a mid-afternoon candy bar
      for an apple.

      Start small. Making incremental changes to your daily habits is difficult
      at first, and [it can take more than a month to make a new habit
      stick](https://science.howstuffworks.com/life/inside-the-mind/human-brain/form-a-habit1.htm).

      ## 1. Change Your Mindset

      It’s a common misperception that healthy foods are bland. However, by
      incorporating more colorful vegetables, fruits, and assorted spices into
      your diet, you may discover new tastes—and your palate will adapt to
      healthier foods over time. 

      ## 2. Control Your Portions

      For many Americans, the problem isn’t so much what we’re eating, but how
      much. This is especially the case when eating out. A simple trick here is
      to ask your server for a to-go container when you receive your order. That
      way, you can immediately set aside a portion of your dish to avoid
      overeating. Plus, you’ll have tomorrow’s lunch already prepared—it’s a
      win-win.

      ## 3. Check Your Intake Of Fat, Salt, And Sugar

      There are a few relatively simple ways to reduce the amount of fat, salt,
      and sugar in your daily diet. The best tip, however, is to prepare more of
      your meals at home. Restaurants typically add more fat, salt, and sugar to
      increase flavor. When you are eating out, consider opting for the grilled
      or baked option instead of something fried. Skip the heavy desserts, and
      instead ask for a bowl of fruit at the end of your meal.

      ## 4. Eating Healthy On The Road

      Being on-the-go doesn’t have to mean compromising your healthy-eating
      goals. Prepare your meals at home in advance of traveling (and avoid the
      overpriced airport or train station fare) or research some restaurant or
      cafe options that serve healthier dishes in the area. Just because you’re
      traveling doesn’t mean you’re stuck with fast food.

      ## 5. Eating Healthy At Work

      The same advice for preparing your own food applies here, too. However, if
      you find yourself scrambling in the morning to get out the door, gravitate
      toward the colorful fruits and vegetables at your local cafe. You can also
      keep healthy snacks at your desk to resist that 3 pm sugar craving—nuts,
      trail mix, and fruit are all better options.

      ## The Benefits Of A Healthy Diet

      A healthy diet full of fruits, vegetables, lean proteins, whole grains,
      and [“good”
      fats](https://www.healthline.com/nutrition/10-super-healthy-high-fat-foods)
      has many benefits—both mental and physical. One of the [leading causes of
      death in the
      U.S.](https://www.cdc.gov/nchs/fastats/leading-causes-of-death.htm) is
      heart disease followed closely by cancer, and [studies have shown that
      diet contributes to these sometimes fatal
      ailments](https://www.nejm.org/doi/full/10.1056/NEJMra054035). Changing
      your diet for the better can be a tremendous help in weight loss, reducing
      the risk of being diagnosed with cancer and heart disease, and it can even
      help with managing diabetes. 

      If that doesn’t convince you, a healthy diet also profoundly elevates your
      mood and improves cognitive function—making you a more effective human
      being. Having trouble sleeping? By eating better, you can sleep better
      since your body won’t be busily trying to digest that pizza and beer in
      the middle of the night. Also, remember to drink plenty of water—at least
      two liters per day. Sometimes, feeling hungry can actually indicate that
      you’re just dehydrated. 

      Ready to get started? Better eating habits are a quick way to a happier,
      healthier you.
    type: BlogStory
---

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by erquhart** [comment]
What happened when you saw this error? What exactly did the error say?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EthosKyle** [comment]
I was navigating away from the page and that little red rectangle pop up, but I didn't catch what it said because it loaded a second page (gray with the text above) before I could take a screenshot.

**Comment by erquhart** [comment]
Understood. Not much to go on here - if you get more info please comment and we can re-open.
