### ISSUE TITLE
Using array in valueField of relation widget causes TypeError

### ISSUE THREAD

**Issue by shumiyao** [netlify/netlify-cms#2445]
**Describe the bug**
If you use array type for the valueField in the "relation" widget of collection, it shows an error screen when you access to the collection record in the admin dashboard.

**To Reproduce**
Steps to reproduce the behavior. For example:
1. In a collection configuration in config.yml, add "relation" widget
2. For "valueField", use array to set a value.
3. Publish
4. When you try to access to the collection for editing, it shows an error screen: Type error: t.split is not a function.

**Expected behavior**
I am not quite sure.

**Screenshots**
![Screen Shot 2019-07-16 at 19 06 38](https://user-images.githubusercontent.com/50849841/61318882-f75ad380-a7fd-11e9-98eb-4e31dc3e5170.png)

**Applicable Versions:**
 - Netlify CMS version: [2.9.1]
 - Git provider: [GitHub]
 - OS: [MacOS 10.14.5]
 - Browser version [chrome 75]
 - Node.JS version: 12.5.0

**CMS configuration**
```
          - label: "Agent"
            name: "agent"
            widget: "relation"
            collection: "agents"
            searchFields: ["agent_name", "direct_phone", "email_address"]
            valueField: ["direct_phone"]
            displayFields: ["agent_name", "direct_phone", "email_address"]
```

**Comment by WJXHenry** [comment]
I believe that the `valueField` parameter only allows for a single field, so the input wouldn't have to be in an array. Try changing `valueField: ["direct_phone"]` to simply: `valueField: "direct_phone"`.

**Comment by shumiyao** [comment]
Thank you. It works. 

I think that it would be nice if someone that has and access to this doc page could kindly add a note on it: https://www.netlifycms.org/docs/widgets/#relation

**Comment by talves** [comment]
@shumiyao you can definitely do a PR to improve the docs, that would be awesome!

**Comment by shumiyao** [comment]
Where is the branch for the doc?

[Master branch](https://github.com/netlify/netlify-cms/blob/master/website/content/docs/widgets.md) does not seem to have the Default widgets section.

**Comment by WJXHenry** [comment]
The file is [here](https://github.com/netlify/netlify-cms/blob/master/website/content/docs/widgets/relation.md).

**Comment by shumiyao** [comment]
Thank you @WJXHenry , @talves 
I have opened a PR.

**Comment by erezrokah** [comment]
closing as stale
