### ISSUE TITLE
Draft post can't be seen in admin

### ISSUE THREAD

**Issue by sarunw** [netlify/netlify-cms#2457]
**Describe the bug**
I try to create a draft post in https://cms-demo.netlify.com/#/collections/posts but after save it won't show up in the list.

**To Reproduce**
1. Go to https://cms-demo.netlify.com/#/collections/posts
2. Click new post
3. Fill in title and body
4. Click save

**Expected behavior**
The draft post show up in https://cms-demo.netlify.com/#/collections/posts

**Screenshots**

**Applicable Versions:**
netlify-cms-app 2.9.6
netlify-cms.js:sourcemap:143 netlify-cms-core 2.12.1
netlify-cms.js:sourcemap:840 netlify-cms 2.9.6
Chrome Version 75.0.3770.142
macOS 10.14.4 (18E226

**Comment by tomrutgers** [comment]
The CMS demo uses the `test-repo` backend, which doesn't save data. This way everyone can try out the CMS without obscuring the data. Saving data works perfectly fine if you [add Netlify CMS to your own site](https://www.netlifycms.org/docs/add-to-your-site/).

**Comment by sarunw** [comment]
I tried on my own site, but also not work. I see it create branch cms/slug-name in my repo, but nothing shows up in the dashboard.

**Comment by tomrutgers** [comment]
Can you share your repo?

**Comment by talves** [comment]
If you have editorial workflow turned on, it is showing up as a draft under the workflow tab.

![image](https://user-images.githubusercontent.com/784848/61537348-c93ae680-a9eb-11e9-9559-f0986d6db900.png)

**Comment by barthc** [comment]
@sarunw check the `Workflow` page https://cms-demo.netlify.com/#/workflow if the post is not yet published.

**Comment by sarunw** [comment]
@talves @barthc Thanks! I thought it would show up in contents at first.
