### ISSUE TITLE
Gatsby Site Starter Landing Page Error

### ISSUE THREAD

**Issue by cotyhamilton** [netlify/netlify-cms#2459]
**Describe the bug**
After deploying the gatsby site starter to netlify, the landing page preview shows this error:
`ReferenceError: Can't find variable: ___loader`

**To Reproduce**
1. Go to https://www.netlifycms.org/docs/start-with-a-template/
2. Click on Deploy to Netlify under Gatsby Site Starter
3. Follow instructions to create/build site
4. Go to \<your-site\>.netlify.com/admin
5. Click on pages in the left panel, then landing page

**Expected behavior**
The preview loads and there is no error

**Screenshots**
<img width="1392" alt="Screen Shot 2019-07-20 at 9 18 23 AM" src="https://user-images.githubusercontent.com/13724650/61579786-56a33700-aacf-11e9-8f30-af989e80f4e5.png">

**Applicable Versions:**

 - netlify-cms-app 2.9.6
- netlify-cms-core 2.12.1
 - Git provider: GitHub
 - OS: MacOS Mojave
 - Browser version Safari 12.0.3

**Additional context**
All files are default, I haven't altered any code nor saved any changes in the cms editor, just followed the instructions to get a gatsby site up

**Comment by cotyhamilton** [comment]
This seems to be localized to safari, the actual landing page of the site loads fine, it's only in the admin preview of the page.

I just tried firefox and chrome and it works as expected. I did hard refresh, empty caches, etc. on safari and the error still shows

**Comment by erquhart** [comment]
It isn't Safari, worked for me (in 12.1.1) following the steps, but the error is present in the console - looks to be gatsby-link, which it seems we're erroneously importing into the landing page preview template. Porting this to the starter repo.
