### ISSUE TITLE
Better Markdown serialization/deserialization 

### ISSUE THREAD

**Issue by biilmann** [netlify/netlify-cms#246]
The current Rich Text Editor is based on ProseMirror.

ProseMirror has an internal document model that we need to serialize to and from in order to get Markdown in and out of the editor.

Apart from that we need to turn the Markdown from any Markdown widget (whether in visual or raw mode) into a virtual DOM tree in order to show it in the live preview.

Right now our preview displays markdown via MarkupIt - via the component found [here](https://github.com/netlify/netlify-cms/blob/master/src/components/MarkupItReactRenderer/index.js). The Markdown serialization into 
ProseMirrors format is handled via MarkdownIt in a slightly tweaked version of [ProseMirror's Markdown serializer](https://github.com/ProseMirror/prosemirror-markdown/blob/master/src/from_markdown.js) found [here](https://github.com/netlify/netlify-cms/blob/master/src/components/Widgets/MarkdownControlElements/VisualEditor/parser.js).

There are currently some problems with both the serialization and deserialization of Markdown and it would be great to rely on just one library for both.

Things that are currently causing problems:

* Fenced code blocks: when editing Markdown with fenced code block in rich text mode they get stripped #209 
* Code examples with embedded HTML misbehaves in the live preview #244 
* Pasting from Dropbox paper mangles the document (both in rich text and raw mode)
* There might be problems with nested lists

**Comment by erquhart** [comment]
Update: this issue has evolved into a replacement of Prosemirror with Slate, and a lower level implementation of Unified (which Remark is built on). Development is happening right now and is close to completion.
