### ISSUE TITLE
Failed to persist entry: API_ERROR: Reference does not exist

### ISSUE THREAD

**Issue by JaydnEdwards** [netlify/netlify-cms#2461]
**Describe the bug**

Every time I try to publish a post, it fails to save. I have to click save, set status to ready and click publish before it 'saves'. This throws the error 'Failed to persist entry: API_ERROR: Reference does not exist'.

Saving on its own doesn't throw an error, however it doesn't actually save anything. 

**To Reproduce**

**Expected behavior**

The post should save and publish.

**Screenshots**

<img width="389" alt="Screenshot 2019-07-21 at 21 23 20" src="https://user-images.githubusercontent.com/38818499/61596724-25c21f80-abff-11e9-9849-216b808c3240.png">

**Applicable Versions:**

 - Netlify CMS version: 2.9.6
 - Git provider: GitHub
 - OS: MacOS Mojave 10.14.4
 - Browser version Chrome 75.0.3770.100

**CMS configuration**

[config.yml](https://github.com/JaydnEdwards/hylia-portfolio/blob/master/src/admin/config.yml)

**Comment by gitjul** [comment]
@JaydnEdwards could you shed some light on how you've dealt with the issue? why did you close it?

**Comment by gvmohzibat** [comment]
I got this error when I was publishing multiple files at the same time. Publishing them one by one solved the issue
