### ISSUE TITLE
Editor Markdown

### ISSUE THREAD

**Issue by fenchi** [netlify/netlify-cms#2462]
Hello,

How can we manage the size of the images (width and height) in the Markdown editor of Netlify-CMS?

Yours truly,

**Comment by marcojakob** [comment]
That's not something you can express in Markdown. Some static site generators might have an option for transforming images (like [Hugo's image processing](https://gohugo.io/content-management/image-processing/)). But this is usually done in the template and not in the Markdown content.

So, it's best to resize the image before you upload it in an image editor (I teach my editors to use https://www.iloveimg.com/) to a reasonable size. Then use CSS in the template to make it responsive.

If you really need to put some style on one specific image in the content, you could add the image as HTML.

**Comment by tomrutgers** [comment]
The external media libraries support in browser image editing. Check their docs to see which solution fits best. 

You could make your own editor component with extra options for width and height, and use them in combination with Netlify Large Media image transformations as well.

**Comment by fenchi** [comment]
Hello,

Thank you for your answers.
I wanted to talk about how to mention the size in the Markdown like this:
`![alt](/assets/netlify.jpg "Netlify"){ width=50% }`

Since my message, I have created an editorComponent that supports:
```
{
  label: 'Image',
  id: 'image',
  fromBlock: match => match && {
    image: match[2],
    alt: match[1],
    title: match[3],
    attr: match[4],
  },
  toBlock: ({ alt, image, title, attr }) =>
    `![${alt || ''}](${image || ''}${title ? ` "${title.replace(/"/g, '\\"')}"` : ''})${attr ? `{ ${attr} }` : ``}`,
  pattern: /^!\[(.*)\]\((.*?)(?:\s"(.*)")?\)(?:\{\s(.*)\s\})?$/,
  fields: [
    {
      label: 'Image',
      name: 'image',
      widget: 'image',
      media_library: {
        allow_multiple: false,
      },
    },
    {
      label: 'Alt Text',
      name: 'alt',
    },
    {
      label: 'Title',
      name: 'title',
    },
    {
      label: 'Attributs',
      name: 'attr',
    }
  ],
}
```
When I use the component it is ok but once I go to "Markdown" then "Rich Text", the "Rich text" part shows this :
![Capture](https://user-images.githubusercontent.com/2248789/61788200-d0aa2780-ae11-11e9-8817-3e9f76a249c7.png)

**Comment by erezrokah** [comment]
Closing as several solutions have been suggested. Please comment if still relevant
