### ISSUE TITLE
Netlify form not working?

### ISSUE THREAD

**Issue by mrlubos** [netlify/netlify-cms#2468]
**Describe the bug**

First of all, despite the title, the form _is_ working. The problem is with receiving submissions in the Netlify dashboard. Nothing shows up there. I tried from both localhost and deployed website on Netlify, no luck. The response in network tab looks fine. I have another website deployed using the same code and that one works, although not from localhost either. Any hints what am I doing wrong please?

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4] 2.9.5
 - Git provider: [e.g. GitHub, BitBucket] Github
 - OS: [e.g. Windows 7] MacOS
 - Browser version [e.g. chrome 22, safari 11] Chrome 75.0.3770.142

 - Node.JS version:

**Comment by tomrutgers** [comment]
Your problem isn't related actually to Netlify CMS and the maintainers of this project can't help you with it. Try asking at the community forum, so the Netlify staff can help jump in: https://community.netlify.com
