### ISSUE TITLE
Make it obvious when test repo is in use

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#2470]
**Describe the bug**

The test repo backend is indistinguishable from other backends in the UI. If a user doesn't know they're using it, the whole experience is confusing. 

**Expected behavior**

It should be explained in the UI that a test backend is in use, probably with a link to the docs for more info.

**Comment by sgarcia30** [comment]
Can I take a crack at this?  I'm fairly new to development, but would enjoy a chance to contribute.

**Comment by erquhart** [comment]
@sgarcia30 thanks for that! Looks like somebody beat you to the punch: https://github.com/netlify/netlify-cms/pull/2678

Feel free to find another ticket you'd like to try though, our priorities board has a bunch:  https://github.com/netlify/netlify-cms/projects/7
