### ISSUE TITLE
Pattern validation on list widget always invalid if untouched

### ISSUE THREAD

**Issue by marcojakob** [netlify/netlify-cms#2482]
**Describe the bug**
Pattern validation on a list of strings was (almost) fixed (see #2382)

Now the problem is that the list widget is always marked as *invalid* when the user tries to save - except if the user changes anything in this particular field.

**To Reproduce**
1. Use the a `tag` field as described in the config below.
2. Open an entry with this field.
3. Change something other than the `tag` field (don't touch the `tag` field)
4. Click "publish".
5. `tag` field is marked as invalid even if it matches the pattern.
6. (If `tag` field is edited in any way, it is validated correctly again.)

**Expected behavior**
`tag` field should only be invalid if it doesn't match the pattern.

**Applicable Versions:**
- netlify-cms-app 2.9.6
- netlify-cms-core 2.12.1
- netlify-cms 2.9.6
- Git provider: GitHub
- OS: Windows 10
- Browser: Chrome

**CMS configuration**
```
{
  label: "Tags",
  name: "tags",
  widget: "list",
  pattern:
    [
      "^[^\\s#]+$",
      "No spaces and # allowed in tags. Please separate multiple tags with comma.",
    ]
}
```

**Comment by erquhart** [comment]
@barthc this is about #2385, have you run into it at all?

**Comment by barthc** [comment]
@erquhart #2599 should fix this issue.

**Comment by barthc** [comment]
The issue was, on initial save the list input widget value(array) is passed to the test function [here](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js#L135)  and that works. But on subsequent edit, the value passed to the test function is now a `list`  so validation fails, edit the list input, value back to `array`, validation works again. So the PR just converts the value(array or list) to `string` before pattern test.

**Comment by erquhart** [comment]
Merged the fix, but it's backed up in beta at the moment. Should be released soon.

**Comment by marcojakob** [comment]
Awesome, thanks for the great work!

About the releases: I don't quite understand how I can track if and when something like this gets released. The CHANGELOG is a list of 20 sub-changelogs and the releases page contains a huge list of relases of individual plugins without any comments. Can you give me a hint about how to keep track of what is happening?

**Comment by erquhart** [comment]
We need a releases page. For now, because everything gets squashed into master, and helped by our use of conventional changelog for descriptive commit messages, the commits on master are the best overall changelog we have: https://github.com/netlify/netlify-cms/commits/master
