### ISSUE TITLE
Prompt to save unsaved changes when navigating away

### ISSUE THREAD

**Issue by cassandraoid** [netlify/netlify-cms#249]
**Feature**

Protect from accidentally leaving the page. 

**- What is the current behavior?**

If I currently am writing in the CMS I'mm able to:
- close the page 
- hit the back tab and leave
- swoop my fingers or palm across the track pad
This results in **loosing all data.**

**- If the current behavior is a bug, please provide the steps to reproduce.**

See above.

**- What is the expected behavior?**

Possibly a pop-up that roadblocks you from leaving the page before saving.

**Comment by Benaiah** [comment]
Took longer than I expected, as I kept ending up on docs for the wrong `react-router` version, but I have the navigation confirmation working at https://github.com/Benaiah/netlify-cms/commit/9e863b7ae831d06150db54bc737ade3fd0fcd622. Once I have unsaved change detection working, I can hook that into this and make a PR to close this issue.
