### ISSUE TITLE
[Resolved] Using Netlify CMS without GitHub credentials?

### ISSUE THREAD

**Issue by bmaclean** [netlify/netlify-cms#2497]
Hey there,

If I have non-technical users that want to manage site content through the Netlify CMS, is there some way to handle authentication without requiring GitHub credentials?

Thanks!

**Comment by talves** [comment]
Yes, if hosting on Netlify using Netlify Identity, you can use the `git-gateway` backend to have users who do not need to know about GitHub.

https://www.netlifycms.org/docs/authentication-backends/#git-gateway-with-netlify-identity

You can also ask questions like this in: https://gitter.im/netlify/NetlifyCMS

**Comment by bmaclean** [comment]
@talves Thanks!

**Comment by abdullahe** [comment]
Necroing the thread. 
Is it possible to do that if you are not using Netlify? If so, where can I learn more about it?

Thanks.

**Comment by erezrokah** [comment]
@abdullahe see https://github.com/hfte/netlify-cms-with-selfhosted-gotrue-and-git-gateway
