### ISSUE TITLE
CMS Erroring

### ISSUE THREAD

**Issue by adambschroeder** [netlify/netlify-cms#2498]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by talves** [comment]
Once you have the details you can reopen.

**Comment by adambschroeder** [comment]
I was on my phone and accidentally reported - hence no details. Sorry for the inconveniences!
