### ISSUE TITLE
How to insert image inside body?

### ISSUE THREAD

**Issue by bsde1245** [netlify/netlify-cms#2501]
If I use image widget , can I place image inside the body of post?

**Comment by ntmk** [comment]
use a markdown widget 
`- { label: "Body", name: "body", widget: "markdown" }`
 - then use the drop down seen in the image 
<img width="470" alt="Screen Shot 2019-08-06 at 3 56 42 PM" src="https://user-images.githubusercontent.com/25558862/62582910-e0d6f380-b862-11e9-957b-4d4badda2bd1.png">
- this will insert an image widget inside the markdown field
<img width="717" alt="Screen Shot 2019-08-06 at 4 02 13 PM" src="https://user-images.githubusercontent.com/25558862/62583095-a3269a80-b863-11e9-9eb3-76d134c3cef2.png">
Hope this is what your looking for.
