### ISSUE TITLE
Why should I see a React Error if I'm using a Netlify services? 

### ISSUE THREAD

**Issue by Slieocode** [netlify/netlify-cms#2504]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by tomrutgers** [comment]
Netlify CMS is built with react. What error are you experiencing? Please fill out the issue details, otherwise we can't assist you with resolving it.

**Comment by Slieocode** [comment]
Hi, the issue is fixed now, it gave me "Invariant Violation: Minified React error."
but my question was rhetorical one, I meant why should Netlify Service error get mixed up with React Error? I think it would be more useful to have a coherent error, rather than React-based Warning signs
