### ISSUE TITLE
No error toast on fields with regex validation editorial workflow

### ISSUE THREAD

**Issue by ntmk** [netlify/netlify-cms#2508]
**Describe the bug**
Any field not in view or nested collapsed fields (ie list) does not through an error toast at the top of the screen. Errors only appear over the fields themselves.
If nested field is collapsed the field will still throw error but will not expand to show

**To Reproduce**
Got to the admin panel
With a field out of view (ie you must scroll down to it)
Force a field with regex pattern to fail
Scroll back to top 
Save -> will not save or display anything (no response)

**Expected behavior**
Should a regex field fail display error toast at the top of screen

**Applicable Versions:**
<script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
Found in [Netlify cms docs](https://www.netlifycms.org/docs/add-to-your-site/)

**Additional context**
Found similar issue on required fields #1202

**Comment by barthc** [comment]
@ntmk  this issue already reported in #2320, you can follow up there. Closing this, thanks.
