### ISSUE TITLE
Relation Widget: Provide ability to customize slice

### ISSUE THREAD

**Issue by zslabs** [netlify/netlify-cms#2519]
**Describe the solution you'd like**
It looks like we may be capping the relation widget at 20 entires; via https://github.com/netlify/netlify-cms/blob/b4041d39713a781bc7a1e29acf2622df50f9b5c1/packages/netlify-cms-widget-relation/src/RelationControl.js#L144

Has it been considered at all to allow this to be a configurable option? We just went over that limit in a certain situation with authors; and introduced a bit of confusion since the UX around searching wasn't super-clear.

Thanks as always!

**Comment by erquhart** [comment]
Infinite loading could work, not sure how well that's supported in react-select, though.

**Comment by zslabs** [comment]
@erquhart Thanks for the response! I [created a PR](https://github.com/netlify/netlify-cms/pull/2520) in case someone would want to add a specified limit instead of the hardcoded one provided.

**Comment by erquhart** [comment]
Nvm, looks like react-select is **not** supporting that ever lol

**Comment by zslabs** [comment]
Merged in, so closing this one 🎉
