### ISSUE TITLE
Ability to Delete a card

### ISSUE THREAD

**Issue by cassandraoid** [netlify/netlify-cms#252]
**Feature**
Let me delete a card from the Editorial workflow

**- What is the current behavior?**

I can't delete anything w/out going into Github... or publishing.

**- If the current behavior is a bug, please provide the steps to reproduce.**

n/a

**- What is the expected behavior?**

Let me delete a card... but don't forget to ask me if I am sure!

**Comment by bdougie** [comment]
FYI, I am going to get @americool to look at this. He is looking for his first open source contrib and this seems approachable

**Comment by americool** [comment]
Hi all, 
I’m trying to follow the bread crumbs so to speak in the hopes of creating delete button with  functionality that is parallel, or nearly identical to that of the publishing feature. Ultimately the hope is to have a button that deletes the card and also closes the PR via github API. Here are my steps so far in tracing the publishing functionality (while making a mirrored delete functionally with various console logs):

I'm starting with UnpublishedListing.js which calls requestPublish from the button. The function requestPublish calls this.props.handlePublish - which is a function passed down as a prop. 

Next I see that UnpublishedEntriesPanel.js renders the UnpublishedListing component and passes publishUnpublishedEntry to the handlePublish prop. Here I can see that publishUnpublishedEntry from editorialWorkflow in the Actions folder. The function references a differently (identically) named function off of backend.js, which I believe ultimately ends up pointing to the API.js file, though I'm still unclear on the steps to get there. Though I feel confident with some more poking around I will figure it out. 

That being said, I'm very open to any direction or suggestions.

**Comment by americool** [comment]
Update: I've got functional Delete Button. It closes the PRs and removes cards. Going to do some testing and clean up now. I should have PR coming very soon.

**Comment by calavera** [comment]
Fixed by #274.
