### ISSUE TITLE
Create/Modify Constants Files

### ISSUE THREAD

**Issue by Skillz4Killz** [netlify/netlify-cms#2529]
**Is your feature request related to a problem? Please describe.**
It would be amazing to allow users to be able to submit values for data which then get made into a `.js` file inside the constants folder.

Let's take an example, I want to have users add new heroes onto my wiki when they are released. Or even update current values on it. I have Netlify CMS working great for writing guides and posts but I was wondering if it would be possible to do it in a way it could be used to update constants. This would allow the wiki to be entirely maintained by the community.

**Describe the solution you'd like**

```js
collections:
  - name: "hero"
    label: "Hero"
    folder: "src/constants/heroes"
    create: true
    editor:
      preview: true
    fileType: ".js"
    fields:
      - { label: "File Name", name: "id", widget: "string" }
      - { label: "Hero Name", name: "heroName", widget: "string" }
```
Instead of making a markdown file if we added `fileType` that could tell the CMS that we want this as a `.js` constant file. Which could then convert the data and create a file:
```js
export default {
  heroName: "whatever they entered",
  // Add other fields here.
}
```

**Describe alternatives you've considered**
I tried to find a tool that could convert Markdown into Javascript constant files but then i asked myself if that was even a good idea. It would be a much bigger pain to try and convert Markdown to JS and then JS back to markdown when JS is updated. Netlify CMS does most of the heavy lifting for all of this already.

**Additional context**

N/A

**Comment by solomonpierce** [comment]
Are you specifically looking to output to JavaScript, or are you looking for functionality similar to [Forestry's Blocks](https://forestry.io/docs/settings/fields/blocks/)? It isn't quite clear to me. This could be an [XY Problem](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem/66378#66378).

**Comment by gungorbudak** [comment]
Can those files be JSON files? Because JSON outputs are already supported, you don't have to parse Markdown to JS but can easily parse JSON in JS: https://www.netlifycms.org/docs/configuration-options/#extension-and-format

**Comment by Skillz4Killz** [comment]
@gungorbudak Thank you so much I was not aware it could be done with JSON.
