### ISSUE TITLE
"Oops, you are missing a required field" message improvement

### ISSUE THREAD

**Issue by Nexuist** [netlify/netlify-cms#2530]
**Is your feature request related to a problem? Please describe.**

Building off of #650 and #649, I'd like to make a suggestion to the default "Oops, you are missing a required field" dialog you get if you leave a required field empty. For the particular project I'm working on, there are lots and lots of nested fields and it's very hard (borderline impossible) to figure out which required field was left empty. Yes, they get highlighted in red once the error message appears, *but* you have to dig deep into the hierarchy to find the specific widget that is giving you problems. Our users are not tech savvy and so this is actually a large impediment to their workflow because they don't know where to start looking.

**Describe the solution you'd like**

* One helpful solution would be to provide a link next to the message that takes you straight to the empty field. This would save a lot of time searching, but it would only really work for situations where a single field is empty. 

* I think a more robust solution would be to expand on the highlight idea and make entire sections red, so that the user can keep unfolding the red parts until they get to the problem fields. 

* At the very least, it would be very nice if the dialog indicated how many fields are empty ("Oops, you are missing 3 required fields") or even what they are called ("Oops, you are missing 3 required fields: Post Title, Post Body, Post Categories"). 

**Describe alternatives you've considered**

I tried to fork the netlify-cms package and play with part of the code that generates the error dialog to see if I could implement some of the solutions above, but frankly I am too time constrained at the moment to make any real progress. If we were provided an API that we could catch events with (for example, to deal with errors in a custom way when they pop up) that could provide even more flexibility.

**Additional context**

N/A

Thank you!

**Comment by erquhart** [comment]
Linking to erroneous or somehow auto-scrolling/revealing erroneous fields would be superb, but it'll take more consideration to do well, and likely cause this to not get implemented any time soon.

Error field count would be nice, but might take more work than you'd think. All for it, though.

As the lowest hanging fruit approach, I like the idea of highlighting ancestors of error fields in red.

**Comment by Nexuist** [comment]
Thanks for the acknowledgement. I appreciate all the work you've all put in so far, and I'm excited to use Netlify CMS for many more projects in the future.
