### ISSUE TITLE
FIle manager attepts to render preview for non-previewable files

### ISSUE THREAD

**Issue by austincondiff** [netlify/netlify-cms#2532]
### Bug

When opening the file manager manually or via a file widget, non-image files attempt to render a preview and show up as broken images where the preview would be.

### Potential Solution 

For documents such as PDF's, word documents, etc., we could use third party libraries to render these files and store these generated images in browser cache.

### Expected Behavior

Do not render anything for non-previewable files. 

### Actual Result

Broken image is displayed in place of preview image for non-previewable files.

**Comment by barthc** [comment]
@austincondiff  this issue already fixed in #2089 but I think there was a regression introduced by #2124, looking into it.
