### ISSUE TITLE
Rendering bug after resizing preview pane

### ISSUE THREAD

**Issue by austincondiff** [netlify/netlify-cms#2533]
After resizing the edit pane / preview pane, once you scroll in the edit pane, ghosting occurs and some fields are not visible.

![image](https://user-images.githubusercontent.com/806104/62892446-e7a3b180-bd0d-11e9-8baa-95ccb7e741d0.png)

And this is how it looks normally
![image](https://user-images.githubusercontent.com/806104/62892520-191c7d00-bd0e-11e9-93f1-22eed2cdb60f.png)

**Comment by barthc** [comment]
@austincondiff  I can't seem to reproduce this issue. If it's still an issue from your end, please add a gif.

**Comment by erquhart** [comment]
Gotta fill out the issue template - if this still happening, please provides steps to reproduce.
