### ISSUE TITLE
I am having an error when I am trying to create a new post

### ISSUE THREAD

**Issue by giordifungula** [netlify/netlify-cms#2541]
This is what the error says
Sorry!
There's been an error - please report it!

TypeError: e.join is not a function
![screen](https://user-images.githubusercontent.com/27930281/63057640-5857f300-bef3-11e9-81af-e595e40a1578.png)

**Comment by tomrutgers** [comment]
Can you have a look here and see if it helps? https://github.com/netlify/netlify-cms/issues/2540
There's probably a list widget in your admin config, that isn't represented in your data.

**Comment by giordifungula** [comment]
Thanks, will do. I am aware I have been playing around with the admin config files
