### ISSUE TITLE
Uploading an image

### ISSUE THREAD

**Issue by cassandraoid** [netlify/netlify-cms#256]
**- Bug**
 
_(Could be just in our blog set up)_

**- What is the current behavior?**

When you want to upload an image you have to be sure there is no text below it. So, if I have a body of text and I want to insert an image between two paragraphs - I can't. I have to get rid of whichever paragraph is below and repaste. 

**- If the current behavior is a bug, please provide the steps to reproduce.**

See above. 

**- What is the expected behavior?**

I should be able to insert an image at any point no matter if there's text or not.

**Comment by bdougie** [comment]
@cassandraoid can you confirm if you are able to add a new image if you create a new line between the paragraphs. The `+` widget currently does appear unless you are on a new line. 

![ezgif com-video-to-gif 3](https://cloud.githubusercontent.com/assets/5713670/23588688/f5b3b988-0175-11e7-839e-6d2843e9445a.gif)

**Comment by bdougie** [comment]
Thinking about this more and I believe this is the expected behavior. You should create the space for where the image will be placed.

**Comment by brionz** [comment]
I have some issue when adding image, the prefix should be dist/img, but in my panel, it seem dist/example.jpg
