### ISSUE TITLE
Finding the special spot for text box

### ISSUE THREAD

**Issue by cassandraoid** [netlify/netlify-cms#257]
**- Bug**

Not able to click anywhere in text box to start writing. 

**- What is the current behavior?**

- There is only one special area you can click into text boxes to start typing. And it's not quite right below the header... so I miss it often even with heavy use. 

**- If the current behavior is a bug, please provide the steps to reproduce.**

See above.

**- What is the expected behavior?**

I'd like to click where ever my heart desires inside the text box to start typing.

**Comment by bdougie** [comment]
I have noticed this and it seems like the click target is not large enough. Curious if a min-width can be added to Markdown/VisualEditor body

**Comment by bdougie** [comment]
🙌
