### ISSUE TITLE
Order of cards for collection pages

### ISSUE THREAD

**Issue by cassandraoid** [netlify/netlify-cms#258]
**- Feature**
Ability to reverse order of cards. 

**- What is the current behavior?**

If I go to a collection page I see the oldest first w/out the ability to reverse.

**- If the current behavior is a bug, please provide the steps to reproduce.**

N/A

**- What is the expected behavior?**

I'd like to see the newest content first not the oldest.

**Comment by erquhart** [comment]
The UI refresh will address this, but we can default sort newest first as a stopgap.
