### ISSUE TITLE
Making edits after content is published

### ISSUE THREAD

**Issue by cassandraoid** [netlify/netlify-cms#259]
**- Bugish...**

**- What is the current behavior?**

If you go back and edit a content piece it goes back to draft in your editorial workflow. There's no clear indication of what happens after you hit save, one might think it's already saved and ready. 

**- If the current behavior is a bug, please provide the steps to reproduce.**

See above

**- What is the expected behavior?**

I'd like to see a card go to "Ready for review" after you've updated a previously published piece. More importantly, IMO, *it should be different within the editorial workflow*, a different color, highlight, or popping to the top - or a different column would all be helpful.'

In addition, if you're editing a piece that's already been published, but it's going back to the editorial workflow - it may be nice to have something that tells you that once you hit save.

**Comment by cassandraoid** [comment]
Also, once you edit a published piece of content, it shouldn't take you back to the homepage of the content you were editing - it should take you to the editorial workflow.

**Comment by erquhart** [comment]
For now let's just go with rerouting the user to the editorial workflow when saving a post.

**Comment by erquhart** [comment]
Just reread this and noticed I missed some requirements. I now see three:

* Indicate previously published posts - we now have the "New" indicator, so this is taken care of.
* Move edited posts that were previously published to _Waiting For Review_ instead of _Draft_.
* Indicate to the user that the edited post is now in the editorial workflow - we can do this by simply navigating there on save.

@cassandraoid let me know if this sounds right.

**Comment by verythorough** [comment]
Routing the user to the editorial workflow on save may not be enough to communicate that the item is still waiting for review, especially if there's a large number of items in the workflow.

**Comment by erquhart** [comment]
@verythorough true. I actually think the optimal answer is the contextual save button requested under #260 and depicted in #180, so expectations are inherently set.

**Comment by erquhart** [comment]
Here's another, simpler approach: display publishing status for entries in the collection view. 
Assigning a color code to the three publishing phases will help to improve clarity here.

The more I've considered this, the more I think we *shouldn't* put users in the workflow after saving a post. What if the user is editing multiple posts and doesn't want to change their review status?
 For those that do, #260 is the right approach. Instead, the user should always be returned to the page they were on before editing the post.

**Comment by erquhart** [comment]
As of 1.0 we no longer automatically transition you away from the editor when you save.
