### ISSUE TITLE
Saves not working for Open Authoring

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#2593]
**Describe the bug**

Only the initial save works for Open Authoring entries. Subsequent saves (without publishing) appear to work in the UI, but are not reflected in the remote repository.

**To Reproduce**

1. Enable Open Authoring
2. Create a new entry
3. Without publishing the new entry, make a change and save.

**Expected behavior**

Unpublished entry branch should show a new commit with latest changes.

**Applicable Versions:**

 - Netlify CMS version: 2.9.8-beta.1

**Comment by erezrokah** [comment]
Please see https://github.com/netlify/netlify-cms/pull/2456/files#r318009080

**Comment by erezrokah** [comment]
I believe this is fixed:
https://github.com/netlify/netlify-cms/blob/7ca528b20ae7457c5901370e48d1cc2b12369d1c/packages/netlify-cms-backend-github/src/API.js#L656

And actually also here https://github.com/netlify/netlify-cms/blob/7ca528b20ae7457c5901370e48d1cc2b12369d1c/packages/netlify-cms-backend-github/src/API.js#L662 too

I'll remove the code duplication and make sure it still works

**Comment by erezrokah** [comment]
Closing as fixed
