### ISSUE TITLE
Smart button within content piece

### ISSUE THREAD

**Issue by cassandraoid** [netlify/netlify-cms#260]
**- Feature**

Smart button where the 'save' button is when creating or editing a piece of content

**- What is the current behavior?**

All you're able to do is save so it goes into the editorial workflow.

**- If the current behavior is a bug, please provide the steps to reproduce.**

N/A

**- What is the expected behavior?**

I'd like to have the option to Save, Publish, (in the future draft), or put directly ready for review. The most ideal for me would being able to Publish directly from the content piece.

**Comment by erquhart** [comment]
@eliwilliamson included that in his [mockup](https://github.com/netlify/netlify-cms/issues/180#issuecomment-289151867) on #180.

**Comment by erquhart** [comment]
This is now live in 1.0 🎉
