### ISSUE TITLE
Add configuration option to define a separator for relation widget displayFields

### ISSUE THREAD

**Issue by wing5wong** [netlify/netlify-cms#2606]
**Is your feature request related to a problem? Please describe.**
When using multiple displayFields in a relations widget it can be difficult to visually parse the output in the admin interface.
for example, you may use `displayFields: ["id", "type", "title"]` which results in 
`29678 Internal Demonstrate knowledge of an important function`
As this is just 3 fields jammed together, it can sometimes be confusing to quickly scan related items.

**Describe the solution you'd like**
The ability to define a separator string in the config, e.g `separator: " - "` or `separator: "/"`
This would give `29678 - Internal - Demonstrate knowledge of an important function` as the resultant output

**Describe alternatives you've considered**
Currently i cant think of any other available alternative.

**Additional context**
for example, from a school website (in this case i already removed some of the excess information and only display number/title)
![image](https://user-images.githubusercontent.com/4406993/63729032-fb2c4c00-c8b9-11e9-863e-bd3e54698cf2.png)

**Comment by erquhart** [comment]
**displayFields** should probably be a string template with field replacements, similar to the [**summary** field](https://github.com/netlify/netlify-cms/pull/2140).

**Comment by wing5wong** [comment]
That would work as well, thanks

**Comment by barthc** [comment]
Fixed in https://github.com/netlify/netlify-cms/pull/3659
