### ISSUE TITLE
logon issue

### ISSUE THREAD

**Issue by edmundf32** [netlify/netlify-cms#2612]
**Describe the bug**
new Netlify account, existing site logon

**To Reproduce**
go to twbi.ie/admin
type in username and password
this error occurs

**Expected behavior**
logon to the account

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by tomrutgers** [comment]
@edmundf32 You need to include the Netlify Identity widget: https://www.netlifycms.org/docs/add-to-your-site/#add-the-netlify-identity-widget

**Comment by edmundf32** [comment]
@tomrutgers  thanks Tom, i tried that - I am now getting a 'Logon with Netlify Identity' button but when i click it i am getting  'Failed to load settings from /.netlify/identity'

I used the script injection and adding the code by hand

Am i missing something?

Thanks

**Comment by tomrutgers** [comment]
In your Netlify dashboard, enable Identity, and Git Gateway: https://www.netlify.com/docs/identity/

**Comment by edmundf32** [comment]
@tomrutgers 
Already done, registration set to open Google Oauth and git connected

although twbi.netlify.com/admin does not work, where as twbi.ie/admin does?

**Comment by wommy** [comment]
im having the same problem:

if i access the site from my site.netlify.com it works, but when i do local development i get the `Failed to load settings from ./netlify/identity`

i think it has something to do with localhost not being SSL?

**Comment by erquhart** [comment]
If anyone has further issues please reach out in chat: https://netlifycms.org/chat

**Comment by erezrokah** [comment]
Closing as stale, please comment if problem persists
