### ISSUE TITLE
`TypeError: e is undefined` in page preview

### ISSUE THREAD

**Issue by aidalgol** [netlify/netlify-cms#2616]
**Describe the bug**
When I edit a certain page on my site based upon netlify-templates/gatsby-starter-netlify-cms, I get the following error in the preview pane:
```
TypeError: e is undefined
```

**To Reproduce**

1. Go to https://quizzical-tesla-b8c593.netlify.com/admin
    (Built from https://gitlab.com/aidalgol/netlify-cms-gatsby-preview-bug)
2. Create a Netlify Identity user through Netlify CMS
3. Log in to the Netlify CMS admin panel
4. Edit the page named "Landing Page"
5. The preview pane on the right-hand side will show the error described earlier.

**Expected behavior**
The page's component to render normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/2313201/63830257-d5896a80-c9bf-11e9-9c39-c7b1e402e6ae.png)

**Applicable Versions:**

 - Netlify CMS version: 2.9.7
 - Git provider: GitLab
 - OS: Debian 10
 - Browser version Firefox 60.8.0esr

**CMS configuration**
https://gitlab.com/aidalgol/netlify-cms-gatsby-preview-bug/blob/master/static/admin/config.yml

**Comment by erquhart** [comment]
Your CMS preview template is getting raw data, the same as you see in your frontmatter.

So lines like this one, where you expect your photos (an array of string paths to images) to be objects with a `childImageSharp` property, will fail: https://gitlab.com/aidalgol/netlify-cms-gatsby-preview-bug/blob/master/src/pages/index.md

This sort of mismatch in expectations is generally the cause of preview failures in Gatsby sites. Gatsby runs on the server, so a lot of things your templates normally lean on won't be available in the preview pane.

**Comment by aidalgol** [comment]
Ah, that makes sense.  Thanks to your information, I was able to fix the component under the preview.

Why was the error complaining about a variable `e`?  Is it because Netlify CMS runs from minified JS?

**Comment by erquhart** [comment]
Yep, exactly.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aidalgol** [comment]
Is there anything I can do in future to get a more useful stacktrace, such as running a local dev build of Netlify CMS?

**Comment by erquhart** [comment]
It's better running locally, but still goes to the built es modules rather than source. Very readable, not minified.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
