### ISSUE TITLE
Markdown footnotes and links unproperly escaped?

### ISSUE THREAD

**Issue by DirtyF** [netlify/netlify-cms#262]
Hi all,

First of all, thanks for working on improving the authoring experience on static websites, your CMS seems very promising. 👏 

I gave a it quick shot and have some feedback related to Markdown parsing. 
I'm not sure if it's a prosemirror issue or if its belong to this repo though.

I simply edited a post containing some Markdown footnotes to fix a typo and it escaped the footnote and some Markdown links, breaking up the links in the generated HTML file.

Diff commit is accessible here: https://github.com/DirtyF/frank.taillandier.me/commit/a551c3db20d2852ae8bf2fac2fdf56a95df65ad4

**Comment by erquhart** [comment]
@DirtyF thanks for the heads up on this bug, and we appreciate the positive feedback!

**Comment by erquhart** [comment]
Possibly related to #246

**Comment by erquhart** [comment]
Closing in favor of #246.
