### ISSUE TITLE
Entries are failing to load from local storage on chrome after a page reload.

### ISSUE THREAD

**Issue by kylekirkby** [netlify/netlify-cms#2632]
I've checked for duplicates but couldn't find anything exactly the same as this. Please move/delete if a duplicate. 

**Describe the bug**
I've got a collection of 16 pages added to an _pages folder collection. On the initial load of the collection within netlify-cms, I'll see all pages with no issues. But if the page is requested again over half the pages are failing to load with 404 issues. I started debugging the issue and I think it's something to do with the localforage.js implementation/a bug with chromium. After a [little hack](https://github.com/netlify/netlify-cms/compare/master...kylekirkby:fixing_localforage_issue) around with GitHub API file I managed to get all entries to load on every refresh. But a *small* side effect is that all pages are requested/cached to local storage every page load - which is no way near ideal. Any thoughts all? Happy to submit a PR if someone can point me in the right direction :D 

**To Reproduce**

1. Create a `_pages` folder collection with more than 16 entries.
2. Refresh the _pages collection in the netlify-cms app on Chromium 76 on Linux.
3. Most of the pages 404 and fail to load again. 
 
**Expected behavior**
All entries in the `_pages` collection to load from localstorage on every request to the netlify-cms /admin/ app on Chromium 76 on Linux.

**Screenshots**
Testing on staging.connect.linaro.org:
![staging-pages-not-loading](https://user-images.githubusercontent.com/4564433/64167291-dea38d00-ce40-11e9-8ab0-772f8749da0e.png)

Testing on localhost:
![localhost-pages-loading](https://user-images.githubusercontent.com/4564433/64167299-e19e7d80-ce40-11e9-884a-ac1476fa3857.png)

**Applicable Versions:**

 - Netlify CMS version: netlify-cms-app 2.9.6 / netlify-cms-core 2.12.1 / netlify-cms 2.9.6
 - Git provider: GitHub
 - OS: Ubuntu 18.04
 - Browser versions: Chromium 76 on Linux 

**CMS configuration**
https://github.com/Linaro/Connect/blob/develop/admin/config.yml

**Additional context**
This issue doesn't affect Firefox :D

**Comment by kylekirkby** [comment]
@erquhart @tomrutgers

**Comment by erquhart** [comment]
This seems pretty specific to Ubuntu/Chrome. @kylekirkby can you confirm whether this is still happening for you? Not seeing anything about it in the localforage repo.

**Comment by kylekirkby** [comment]
@erquhart My colleagues were having the same issue on Windows + Chrome :/ Just tested and the bug still occurs. Simply opened up the pages collection we've got and then hit refresh to see around half disappear?! Thanks for looking at this @erquhart 

I did have a little hack at this:
https://github.com/kylekirkby/netlify-cms/commit/24c1b8151295fe3ed9138d27b7ef9463f7dd141f
This worked but it meant that every entry was fetched constantly.

**Comment by erezrokah** [comment]
Might be related https://bugs.chromium.org/p/chromium/issues/detail?id=354963.
Regardless, this looks like a Chrome issue.
Closing as stale. Please comment if still relevant
