### ISSUE TITLE
Can't use an image from CMS with gatsby

### ISSUE THREAD

**Issue by velezhanski** [netlify/netlify-cms#2653]
Hey, this might sound a bit dumb for some people, but I am relatively new to react, and I am facing an issue with using an image from netlify cms in a page.
Basically I uploaded the image into the netlify cms after creating the custom record for it in the config file.
But when trying to actually display the image through the template it just wont work.
I have imported the gatsby Img
And i am trying to display the image with 
<Img fluid={intro.sideimage} />
its intro.sideimage as this is my config value
- {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}, {label: SideImage, name: sideimage, widget: image}]}

**Comment by erquhart** [comment]
Happy to help, but you'll need to open a new issue and fill out the issue template, that way we have the info we need to assist.
