### ISSUE TITLE
There is problem on netlify cms

### ISSUE THREAD

**Issue by TahsinProduction** [netlify/netlify-cms#2655]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by erquhart** [comment]
Can you share what happened?

Note to observers: this kind of ticket likely results from a user clicking the "open an issue" link when the CMS crashes, and they're not sure how issues work.

**Comment by TahsinProduction** [comment]
On mobile Chrome Browser when I try to use netlify cms it randomly stops working and shows error codes. Using Nelify CMS with GatsbyJS.

**Comment by erquhart** [comment]
Netlify CMS doesn't support mobile browsers yet. Track #441 for updates.
