### ISSUE TITLE
media-library-uploadCare :I uploaded the svg image, but uploadcare rejected me. I have set `imagesOnly`: `false` but it's not working.

### ISSUE THREAD

**Issue by tranthaison1231** [netlify/netlify-cms#2657]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by erquhart** [comment]
Uploadcare doesn't currently treat svg files as images (no image processing available for them), so you'll need to set `imagesOnly` to `false` to get it working.

**Comment by tranthaison1231** [comment]
@erquhart  I have set it, But is not working?

**Comment by erquhart** [comment]
What exactly is happening? Any chance your repo is public and can be shared?
