### ISSUE TITLE
Move published docs (netlify/netlify-cms-www) into this repo

### ISSUE THREAD

**Issue by verythorough** [netlify/netlify-cms#266]
**- Do you want to request a *feature* or report a *bug*?**
Feature

**- What is the current behavior?**
The markdown files for docs are currently duplicated in two places: here in `/docs`, and in [netlify-cms-www](https://github.com/netlify/netlify-cms-www), which is the repo behind [netlifycms.org](https://www.netlifycms.org).

**- What is the desired behavior?**
Not maintaining docs in two places! 😄 We could consider a webhook/submodule solution to keep things synced in both places, but I think I'd prefer to keep the docs in one place, with the code. Thoughts?

The current netlifycms.org repo seems a bit bulky to store in the code repo, so the change will probably involve either simplifying `netlify-cms-www`, or splitting docs from "marketing" content, and building the docs from a folder in `netlify-cms` to something like `docs.netlifycms.org`.

**Comment by bdougie** [comment]
I would love to try out https://github.com/DavidWells/markdown-magic

I believe it would only require us to add it to the cms-www and pull the docs from this repo. I am a believer that the docs should live near the code and don't need to necessarily need to be in the cms-www.

https://github.com/DavidWells/markdown-magic

**Comment by verythorough** [comment]
This is currently being handled in the netlify-cms-www repo using bdougie's markdown magic suggestion. We may choose a different strategy in the future, but I think we can close this issue for now.
