### ISSUE TITLE
Open Authoring showing account does not have access to this repo

### ISSUE THREAD

**Issue by lief2** [netlify/netlify-cms#2660]
**Describe the bug**
After deploying [gatsby-starter-netlify-cms](https://github.com/netlify-templates/gatsby-starter-netlify-cms) and following [docs on open authoring](https://www.netlifycms.org/docs/open-authoring/), the admin page shows "Your GitHub user account does not have access to this repo." when trying to log with a non-owner GitHub account.

**To Reproduce**
1) Deploy  [gatsby-starter-netlify-cms](https://github.com/netlify-templates/gatsby-starter-netlify-cms).
2) Setup config.yml with GitHub backend, editorial workflow and open authoring.
3) Try to log into /admin/ with another GitHub account.

**Expected behaviour**
After logging with another GitHub account, the CMS should ask to create a fork.

**Applicable Versions:**
 - Netlify CMS version: netlify-cms-app 2.9.7
 - Git provider: GitHub
 - OS: Windows 10
 - Chrome version: 76.0.3809.132
 - Node.JS version: 10.16.3

**CMS configuration**
[config.yml](https://github.com/lief2/Gittpad/blob/master/static/admin/config.yml)

Is this an issue related to the template?

**Comment by erquhart** [comment]
You have to use the beta release - `netlify-cms-app@beta`.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lief2** [comment]
Thanks, that was it. I did not know there were beta versions of the package itself. Maybe it should be added as a prerequisite to the beta features on the docs.
