### ISSUE TITLE
Has netlify cms deleted content without my knowledge?

### ISSUE THREAD

**Issue by bert-bruggeman** [netlify/netlify-cms#2675]
Yesterday I used the cms until 23:00 and then crawled into bed, this morning I saw that 2 pages were deleted at 01:00 with my account. This is the third time in 3 weeks that a page has suddenly disappeared from one of my websites while me and my computer where sleeping... From the commit messages I see that this is always coming from the cms with my user account.

After the first time I changed my password on netlify identify, my github password, switched on two-factor authentication and checked all github sessions for suspicious things, because I was afraid someone had hacked me. Nobody else has my data or password,...

Am I getting crazy or sleepwalking at night or could there be something wrong with the cms?

Browser:  Firefox 68.02
Os (computer is off or suspended while this happens) Fedora 30

netlify-cms-app 2.9.7
netlify-cms-core 2.12.2
netlify-cms 2.9.7

**Comment by bert-bruggeman** [comment]
It seems another user deleted the posts but my account is mentioned in the commit message...
happy I'm not hacked or crazy! But this is still an issue, i like to know who removes stuff...

**Comment by erquhart** [comment]
Confirmed, we're doing something strange with deletion.

**Comment by erquhart** [comment]
Covered in #2676.
