### ISSUE TITLE
Wrong user mentioned in git commit when content is deleted 

### ISSUE THREAD

**Issue by bert-bruggeman** [netlify/netlify-cms#2676]
When users (with git-gateway and netlify identify) delete content, the commit message says that I deleted the content, first I thought I was hacked or something, it's scary seeing your account doing something while you're asleep : )

In the future I would like to know who removed something...

**Comment by minyangu-bgl** [comment]
Pls can we have an update. Otherwise it is super confusing for content auditing.

**Comment by erezrokah** [comment]
@minyangu-bgl, can you share your `config.yml` and whether you're using `git-gateway` with GitHub or GitLab?

Looks like we are setting the commit author (information taken from identity):
https://github.com/netlify/netlify-cms/blob/ba18f4a99fcae42caf1b03794e3f4a219d70f016/packages/netlify-cms-backend-github/src/API.ts#L944

But we might need to set the committer:
https://developer.github.com/v3/repos/contents/#delete-a-file

**Comment by KancerEzeroglu** [comment]
@erezrokah If nobody is working on this issue, I would like to work on this.

**Comment by erezrokah** [comment]
This was fixed in https://github.com/netlify/netlify-cms/pull/4139 by switching to the commits API instead of the delete file API)

**Comment by minyangu-bgl** [comment]
thanks guys!
