### ISSUE TITLE
Update docs - example project does not support editorial workflow

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#268]
The in-memory back end used for the example project does not support the editorial workflow. Documentation should be updated to reflect this, and brief instructions should be added to indicate how to go about local development of the editorial workflow.

Local development instructions should consist of 1) setting up a test project, and 2) using `yarn link` to link the cms project. Again, these instructions can be very, very brief and non-detailed.

This documentation update is a stopgap until #267 is complete.

**Comment by kurtgcollins** [comment]
Looks like #267 is closed. Should this issue be closed as well?
