### ISSUE TITLE
Display error message when no entries are loaded

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#269]
The [`ENTRIES_FAILURE`](https://github.com/netlify/netlify-cms/blob/330667045934a06ae3a9bb444d9935f2062155b9/src/actions/entries.js#L88) action is not consumed by a reducer - we should show helpful error messaging for this case. Currently, attempting to view entries in a new project results in an endless spinner. This is a case that new users may encounter regularly.

**Comment by techpeace** [comment]
I'm currently hitting `ENTRIES_FAILURE` in an existing project with content. I can see the requests to the GitHub content API going through, then recursing down through each subdirectory, but `ENTRIES_FAILURE` is nonetheless hit, and I have an endless spinner.

Seen behavior like this before? I can provide any additional info needed to run this down, and I'd also be happy to open a new issue, if needed. Thanks!

**Comment by techpeace** [comment]
Oh never mind, looks like I was running into #313 - since [Middleman Blog](https://github.com/middleman/middleman-blog) nests images in subfolders by default. I just moved these to `/images/blog` instead, and all's well.
