### ISSUE TITLE
Labels on cards in editorial workflow

### ISSUE THREAD

**Issue by cassandraoid** [netlify/netlify-cms#270]
**- Do you want to request a *feature* or report a *bug*?**

Feature

**- What is the current behavior?**

As of now if you look at a card there's no indication of which type of content it is nor whether it was previous published and pending an update. 

**- What is the expected behavior?**

Ideally a card would have more information about the content in addition to what's there:
- What type of content is it?
- What is the pending 'published' date?
- If it was already published and pending an update (meaning it's been re-entered into the editorial workflow) - that should be clear.

**Comment by calavera** [comment]
We should also add the collection information, so people know whether what they are reviewing is a blog post, docs changes, a new page and so on.

**Comment by Benaiah** [comment]
@cassandraoid, @calavera here's a (very) early screenshot - any suggestions on the UI?

![image](https://cloud.githubusercontent.com/assets/1425133/23983680/ad56c6f2-09d2-11e7-85d3-e33bb048892b.png)

**Comment by erquhart** [comment]
Per our Slack convo, our initial approach can be:

* All entries have a light gray bar at the top containing the entry type, left aligned, all caps
* For new posts, a very small "NEW" badge in place of "Last updated: <date/time>"
* "NEW" badge should be very small text, with a heavily rounded, 2px border and transparent background. Minimal padding.
* For modified published posts: "Originally published: <date/time>", followed by the existing "Last updated: <date/time>"

Feedback welcome.
