### ISSUE TITLE
Allow image order to be changed when multiple images are selected

### ISSUE THREAD

**Issue by nadiTime** [netlify/netlify-cms#2701]
**image widget should have a way to control images order,
 in case you inserted multiple images.**

solution should be a control over the images thumbnails
which allow reordering them
just like the "list" widget

**Comment by erquhart** [comment]
Makes sense - our handling of multiple images is currently limited to media library integrations with services like Cloudinary and Uploadcare, so not certain exactly how it should look moving forward. May coincide with #2243.

**Comment by johnpuddephatt** [comment]
In addition to re-ordering, it would be helpful to also be able to remove a single image from a selection of multiple images.

It would also be helpful to be able to add additional images to a selection.
