### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by andresvil** [netlify/netlify-cms#2719]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by TacoCraftxD** [comment]
What is this about?

**Comment by tomrutgers** [comment]
@TacoCraftxD This issue is most likely opened from the admin panel. There's a 'report an error' link when an issue occurs. 

@andresvil Going to close this, if you need help please reach out.
