### ISSUE TITLE
Cannot save changes (API_ERROR: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data)

### ISSUE THREAD

**Issue by pudymody** [netlify/netlify-cms#2725]
**Describe the bug**
I have setup it with the github backend. I can view, load, and delete collections items, but whenever i try to save o create a new one, i get this error:
```
Failed to persist entry: API_ERROR: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```
For what i could see in the network panel, this is happening beacuse the github api returns a 500 error.

As per the docs, i have created and linked the Oauth github app, and added it to the netlify settings.

**To Reproduce**

**Expected behavior**
Be able to create or edit content files.

**Screenshots**

![Sin título](https://user-images.githubusercontent.com/814791/66230493-abac1d80-e6ba-11e9-8f7e-6f9e1ed48f53.jpg)

**Applicable Versions:**

 - Netlify CMS version: 2.9.7
 - Git provider: GitHub
 - OS: Windows 7
 - Browser version: Firefox Nightly 2019-10-04 also happens with Chrome 77

**CMS configuration**

[https://github.com/pudymody/pudymody.github.io/blob/master/static/admin/config.yml](https://github.com/pudymody/pudymody.github.io/blob/master/static/admin/config.yml)

**Additional context**

This bug is similar to #2544, but with a different error message.

**Comment by erquhart** [comment]
As far as I can tell, GitHub's `trees` API returns a 500 internal server error when creating trees over a base tree with around 6,000 or more files. Your `content/streams` directory has around 8,000 files. I have an email in to their support team. For now, you'll need to reduce the number of files in the directory to around 5,000 or less.

**Comment by pudymody** [comment]
You are right, I have reduced the number of files and now everything is working.
Thanks for the workaround, you can close this if you like.
