### ISSUE TITLE
'Unexpected end of JSON input' on deploy with Gatsby

### ISSUE THREAD

**Issue by sunny-kim-92** [netlify/netlify-cms#2726]
**Describe the bug**
I'm trying to build my site made with Gatsby. A previous build was successful and is currently running (some-light-musings.netlify.com), but the most recent commit creates the following error:

```
7:46:49 PM: "gatsby-transformer-json" threw an error while running the onCreateNode lifecycle:
7:46:49 PM: Unexpected end of JSON input
7:46:49 PM: See our docs page for more info on this error: https://gatsby.dev/issue-how-to
7:46:49 PM: 
7:46:49 PM:   SyntaxError: Unexpected end of JSON input
7:46:49 PM:   
7:46:49 PM:   - JSON.parse
7:46:49 PM:   
7:46:49 PM:   - gatsby-node.js:63 Object.onCreateNode
7:46:49 PM:     [repo]/[gatsby-transformer-json]/gatsby-node.js:63:30
```
I've posted this on the Gatsby issues as well, but after reading through all the issues I can, I believe it might be at least partially related to Netlify. I can successfully run `gatsby build` and `gatsby serve` without issue. I used to get the above error upon `gatsby develop`. Unfortunately, I'm not sure what I changed to fix it on my end, it must have involved updating dependencies including 'gatsby-transformer-json'.

I apologize if this is in the wrong place, but after reading a number of issues, including https://github.com/netlify/cli/issues/174, and the fact that `gatsby build` works as intended, I'm not sure where to go.

**To Reproduce**
The repo can be found at https://github.com/sunny-kim-92/amici-site. Continuous Deployment is set up, so that version is the one that produces the above error. A repo of a previous commit that successfully built can be found at https://github.com/sunny-kim-92/amici-site/commit/8664a257f49a7ff109522fb2fd4895d2d24e62b8. The link to that version of the site some-light-musings.netlify.com.

**Expected behavior**
Site deploys successfully

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: 
 - Git provider: Github
 - OS: OSX 10.14.4
 - Browser version: Chrome 77.0.3865.90

 - Node.JS version: v10.16.0

**CMS configuration**

**Additional context**

**Comment by erquhart** [comment]
Guessing you figured it out?

**Comment by sunny-kim-92** [comment]
Yeah, there was a blank, unused JSON file in the 'gatsby-source-system' root folder. When I deleted it, the build worked!
