### ISSUE TITLE
Error when logging in via GitLab

### ISSUE THREAD

**Issue by Juhannuspukki** [netlify/netlify-cms#2736]
**Describe the bug**
When trying to log in via Gitlab (implicit grant) while the Netlify identity widget is enabled, the system gives an error message that is not helpful when debugging the issue (see attached picture).

**To Reproduce**
1. Set up the CMS with Gitlab implicit grant.
2. Add the Netlify identity widget somewhere.
3. Try to log in.

**Expected behavior**
The CMS will tell me to remove the Netlify identity widget.

**Screenshots**
<img width="493" alt="Screenshot 2019-10-08 at 13 24 01" src="https://user-images.githubusercontent.com/25532806/66389763-d86d7700-e9d1-11e9-8da2-2e55397a42bb.png">

**Applicable Versions:**
 - Netlify CMS version: ^2.1.3
 - Git provider: Gitlab
 - Browser version: Safari 13.0.2

**Comment by erquhart** [comment]
Actually the identity widget just shouldn't activate at all. Definitely need to address. Any errors printed to console?

**Comment by Juhannuspukki** [comment]
I believe there was, something like:

`Failed to parse tokenResponse claims: {"access_token":"5994e5b48102775876cd16190f85f5480ad6c4c4d886fc1af83e73b9df3d561e","token_type":"bearer","state":"3e2c8465-7614-4887-a2be-c66eb7f2316f"}`

Or that is what I googled after the error occurred anyway. I believe this is related to [#1690](https://github.com/netlify/netlify-cms/issues/1690).

**Comment by erquhart** [comment]
Looks like we're tracking this under #1824, can you comment there?
