### ISSUE TITLE
Feature: Ability to change which branch config.yml is grabbed from

### ISSUE THREAD

**Issue by ent3r** [netlify/netlify-cms#2740]
**Is your feature request related to a problem? Please describe.**
When doing development work, there is the problem that NetlifyCMS grabs the config.yml file from the `production` branch instead of the `dev` branch. This makes development for the config really hard, as I have to work on the `production` branch which is meant to be used for the production version of the website.

**Describe the solution you'd like**
It would be great if CMS grabbed the current branch from the netlify branch deploy. Currently i have netlify make a branch deploy to `dev.example.com` and a production deploy to `example.com`. If netlify CMS talked to netlify about what branch it was on, and then grabbed the corresponding config.yml file from the repo this would be much easier.
Another solution may be to have a `<meta>` tag you can add to the `index.html` to tell netlify CMS what branch to get the config file from?

**Describe alternatives you've considered**
I have considered having another repo for development, but this just adds another layer of difficulty.

**Additional context**
May be related to #770

**Comment by erquhart** [comment]
With the setup you're describing, `dev.example.com` would get `dev.example.com/admin/config.yml` and `example.com` would get `example.com/admin/config.yml`. Are you referring to local development?

**Comment by ent3r** [comment]
@erquhart kind of both, maybe prioritizing the kind you were describing? I am able to git commit+pull pretty often, so local development may not be so important

**Comment by erquhart** [comment]
What I’m describing is how it currently works. If you’re deploying your branches, you’ll get whatever config.yml was in the deployed branch.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ent3r** [comment]
That's weird. For me I always get the same config, on `dev` and `production`

**Comment by erquhart** [comment]
I guess I'm not tracking here. In the title you reference "the branch config.yml is grabbed from" - config.yml is just a file like any other file. If your dev site is being deployed from your dev branch, the config.yml from the dev branch is the one that will be used.

**Comment by ent3r** [comment]
Yea, for me i always get the same config.yml. I'll make a new site now, just to test how it works, and to see if there is a bug on my end

**Comment by ent3r** [comment]
Seems the problem was that i hadn't configured stuff properly. Closing now
