### ISSUE TITLE
HTML5 video widget

### ISSUE THREAD

**Issue by julienchazal** [netlify/netlify-cms#2744]
**Describe the solution you'd like**
After uploading a video in the media library, a "video widget" would be great to choose the video from media library.
It should be an extended image widget i think. 'cause right now image widget does not allow to choose a video from the media library. It would return the file path to use it in the templates with a `<video>` tag 

**Describe alternatives you've considered**
I tried to add code from Instagram to embed a video in the markdown editor, but the `<script>` tag is removed when saving

**Comment by tomrutgers** [comment]
Have you tried using the file widget? https://www.netlifycms.org/docs/widgets/#file

**Comment by julienchazal** [comment]
Holly s***
As simple as that, sorry :)
Thx @tomrutgers
