### ISSUE TITLE
Bug / unexpected behavior with leading zeros - number / string widget

### ISSUE THREAD

**Issue by mistermantas** [netlify/netlify-cms#2745]
Big bug on my side.

I wanna have a color picker / HEX sort of thing. Right now it’s just numbers, but if I have a HEX code that starts with zeros, the end result is wrong.

`008000` generates `8000`. Help.

https://github.com/cstate/cstate/issues/83

![image](https://user-images.githubusercontent.com/11616378/66706760-992b8700-ed3f-11e9-8b59-9446717d14bf.png)

If I try and enter `"008000"`, there’s double quotes which confuse Hugo. In turn, the color HEX becomes `#ZgotmplZ`.

Is there something I can do to prevent the assumption that I don’t need the first two zeros?

**Comment by tomrutgers** [comment]
@mistermantas You can either try a string widget, or this one: https://www.npmjs.com/package/netlify-cms-widget-color

**Comment by mistermantas** [comment]
> You can either try a string widget

The insane thing is that I **am** using the `string` widget.

Okay, actually, I was a little bit wrong in my assessment.

This is, in part, to do with how Hugo handles colors. Because the color code isn’t in quotes, it removes the leading zeros.

_However_, I would expect the string to _always_ be in the quotes, so a bit odd from the CMS in any way.

I will try the color widget. Thank you so much @tomrutgers!

**Comment by tomrutgers** [comment]
> The insane thing is that I am using the string widget.

Ok that is admittedly a bit troublesome. Maybe try adding a trailing '#' to prevent that behavior from happening? 

@erquhart @barthc any clue why this is happening in the first place? The string widget shouldn't remove those zeros really..

**Comment by mistermantas** [comment]
> Maybe try adding a trailing ‘#’ to prevent that behavior from happening?

I’m likely going to have to surrender and do that but the current backend for the code only accepts numbers (without the hash sign). I don’t think the color widget _just_ gives the number. Have you used it / have an example, by chance, @tomrutgers?

**Comment by tomrutgers** [comment]
Can't say that I have, no.

**Comment by erquhart** [comment]
The CMS isn’t removing the zeros. I would expect the double quotes to be from quotes being manually added to the string input.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mistermantas** [comment]
@erquhart This is true and you can see it in the screenshot. But I would expect it to either be:

ok: "008000"
not
ok: 008000

because it's a string. and yes the double quotes do appear after manually entering "008000" as

ok: '"008000"'

**Comment by erquhart** [comment]
Quotes are optional for yaml strings, so they’re not added by the library we use unless required. Because of the leading 0’s, the quotes aren’t required, it is understood to be a string. The issue is Hugo’s parser doesn’t seem to agree. To test this theory try entering a hex value that contains a letter.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mistermantas** [comment]
Okay, is it not possible to put the quotes in manually somehow?
________________________________

**Comment by erquhart** [comment]
The maintainer of the yaml parser we use is averse to adding an option like this, and I guess I have to agree - downstream tools should be able to handle strings in yaml without quotes. Since the output is valid, I would recommend reaching out to the Hugo community for support on this, they may have solutions.

**Comment by erquhart** [comment]
Hmm actually just noticed that parsers _are_ in fact converting `008000` to `8000`. Going to raise this case on the js-yaml repo.

**Comment by mistermantas** [comment]
@erquhart Actually, I think that’s Hugo. I’m not 100% sure, but I *think* that’s Hugo, if I recall correctly. Source code shows the zeros.

**Comment by erquhart** [comment]
The source shows zeroes, but any yaml -> json converters I can find drop the leading zeroes if quotes are not present. That said, I think I found my final recommendation: include the leading hash. A hex code is supposed to begin with a hash to be valid, and doing so ensures leading zeroes never drop. I'd recommend storing hashes in your raw values.
