### ISSUE TITLE
Full stop in title breaks editorial workflow

### ISSUE THREAD

**Issue by biilmann** [netlify/netlify-cms#275]
When you create an entry with a title containing a full stop, and have editorial workflow enabled, the branch name we create doesn't cleanup the full stop and we end up getting a 422 from GitHub's API when trying to create the branch during a save.

We should improve the branch name generation so dots are not allowed

**Comment by Benaiah** [comment]
The issue seems to be here: https://github.com/netlify/netlify-cms/blob/master/src/backends/github/API.js#L240-L241:

```js
      const contentKey = entry.slug;
      const branchName = `cms/${ contentKey }`;
```

I've fixed this with the following change:

```js
      const contentKey = entry.slug.replace(/\./g, "");
      const branchName = `cms/${ contentKey }`;
```

This fixes it *here*, but it seems to me that it'd be better to change the actual generation of the slug - I'm tracking that down now.

**Comment by Benaiah** [comment]
Ok, the following diff of `src/backends/backend.js` will fix the issue:

```diff
  --- L34 ---
       case "slug":
-        return identifier.trim().toLowerCase().replace(/[^a-z0-9\.\-_]+/gi, "-");
+        return identifier.trim().toLowerCase().replace(/[^a-z0-9\-_]+/gi, "-");
       default:
```

I have a couple design questions (CC @biilmann, @erquhart):
- Is this the appropriate place to make the change? This disallows full stops in slugs entirely - it's possible this is a breaking change, or at least one that would cause posts with full stops in the slugs to be renamed. If we don't want to change the allowable characters in slugs, the change in my previous comment will also fix this issue.
- Currently, a trailing full stop is replaced by "-" (for example, "Full. Stop." will end up with the slug "{{date}}-full-stop-") - should the regex change this so trailing dashes aren't left in?

**Comment by calavera** [comment]
maybe doing this to ensure the slug is not a bunch of `-----`?

```
identifier.trim()
  .toLowerCase()
  .replace(/[^a-z0-9\-_]+/gi, "-")
  .replace(/\-+$/, "")
```

**Comment by Benaiah** [comment]
@calavera That behavior is already the case - "Full.%&Stop." will end up as `{{date}}-full-stop-`. this is because the regex `[^a-z0-9\-_]+` matches all *sets* of adjacent non-sluggable characters and replaces them with "-".

**Comment by erquhart** [comment]
@Benaiah let's go with the breaking option. @biilmann please chime in if you disagree.

**Comment by Benaiah** [comment]
@erquhart sounds good. I'll make a PR - if we decide to go with the other change I can modify that.
