### ISSUE TITLE
Hi, I'm having this problem. Can someone help me?

### ISSUE THREAD

**Issue by JuanDelgado06** [netlify/netlify-cms#2754]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by tomrutgers** [comment]
Can you fill out the issue details so we can figure out what's going on @JuanDelgado06?
