### ISSUE TITLE
File format extension

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#2757]
**Is your feature request related to a problem? Please describe.**

I can only edit supported file types.

**Describe the solution you'd like**

An extension point should be added for registering a custom format, consisting of functions for parsing and serialization.

**Comment by erquhart** [comment]
cc/ @cmaxw

**Comment by erezrokah** [comment]
Closing in favor of https://github.com/netlify/netlify-cms/issues/5848
