### ISSUE TITLE
Publish a post generated this weird error

### ISSUE THREAD

**Issue by davidberco** [netlify/netlify-cms#2760]
**Describe the bug**

First attempt to publish a post from the CMS.

**To Reproduce**

1) I create a post from the CMS.
2) first try the post was showed in the website but for no reason in particularly the link of the post points out to a different page. 
3) Then I tried to change the date of the post form the CMS, I save the changes.
4) The post is not showing in the website. And now that I entered the url of the post I have Page Not Found.
5) Finally I try to access the post from the CMS, and I get a CMS error. (See the screenshot)
**Expected behavior**

**Screenshots**

<img width="394" alt="Screen Shot 2019-10-18 at 8 45 38" src="https://user-images.githubusercontent.com/25429106/67100343-19f5e300-f185-11e9-8ba1-52c891b10579.png">
**Applicable Versions:**

 - Git provider: GitHub
 - OS: macOS 10.14.1
 - Browser version: Firefox 69.0.3

 - Node.JS version: 10.15.3

**CMS configuration**

backend:
  name: git-gateway
  repo: davidberco/forsetiabogados
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

publish_mode: editorial_workflow
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "info"
    label: "Información"
    editor:
      preview: false
    delete: false
    files:
      - label: "Información básica"
        name: "info"
        file: "/_config.yml"
        fields:
          - {label: Dirección (1ra. línea), name: "location1", widget: string}
          - {label: Dirección (2da. línea), name: "location2", widget: string}
          - {label: Dirección (3ra. línea), name: "location3", widget: string}
          - {label: Teléfono, name: "phone", widget: string}
          - {label: Email, name: "email", widget: string}
          - {label: Descripción, name: "description", widget: markdown}
          - {label: Misión, name: "mision", widget: text}
          - {label: Visión, name: "vision", widget: text}
          - {label: Twitter, name: twitter, widget: string}
          - {label: Facebook, name: facebook, widget: string}
          - {label: Instagram, name: instagram, widget: string}
          - {label: LinkedIn, name: linkedin , widget: string}
          - {label: Video, name: video , widget: string, hint: Pegar aquí el código del video embebido desde Vimeo.com}

  - label: "Equipo de Trabajo"
    name: "workteam"
    delete: false
    editor:
      preview: false
    files:
      - label: "Socio 1"
        name: "team1"
        file: "/_data/team1.yml"
        fields: 
          - {label: "Titulo de sección", name: "title", widget: "string", required: true, hint: Nota Este es el título de toda la sección}  
          - {label: Nombre, name: name, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: Twitter, name: twitter, widget: string}
          - {label: LinkedIn, name: linkedin , widget: string}
          - {label: Fotografía, name: "image", widget: "image"}
          - {label: Resumen, name: "body", widget: "markdown", required: true}
          - {label: Archivo CV, name: cv, widget: file}
      
      - label: "Socio 2"
        name: "team2"
        file: "/_data/team2.yml"
        fields: 
          - {label: Nombre, name: name, widget: string}
          - {label: Cargo, name: rol, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: Twitter, name: twitter, widget: string}
          - {label: LinkedIn, name: linkedin , widget: string}
          - {label: Fotografía, name: "image", widget: "image"}
          - {label: Resumen, name: "body", widget: "markdown", required: true}
          - {label: Archivo CV, name: cv, widget: file}
      
      - label: "Socio 3"
        name: "team3"
        file: "/_data/team3.yml"
        fields: 
          - {label: Nombre, name: name, widget: string}
          - {label: Cargo, name: rol, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: Twitter, name: twitter, widget: string}
          - {label: LinkedIn, name: linkedin , widget: string}
          - {label: Fotografía, name: "image", widget: "image"}
          - {label: Resumen, name: "body", widget: "markdown", required: true}
          - {label: Archivo CV, name: cv, widget: file}
      
      - label: "Socio 4"
        name: "team4"
        file: "/_data/team4.yml"
        fields: 
          - {label: Nombre, name: name, widget: string}
          - {label: Cargo, name: rol, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: Twitter, name: twitter, widget: string}
          - {label: LinkedIn, name: linkedin , widget: string}
          - {label: Fotografía, name: "image", widget: "image"}
          - {label: Resumen, name: "body", widget: "markdown", required: true}
          - {label: Archivo CV, name: cv, widget: file}
      
      - label: "Socio 5"
        name: "team5"
        file: "/_data/team5.yml"
        fields: 
          - {label: Nombre, name: name, widget: string}
          - {label: Cargo, name: rol, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: Twitter, name: twitter, widget: string}
          - {label: LinkedIn, name: linkedin , widget: string}
          - {label: Fotografía, name: "image", widget: "image"}
          - {label: Resumen, name: "body", widget: "markdown", required: true}
          - {label: Archivo CV, name: cv, widget: file}
      
      - label: "Socio 6"
        name: "team6"
        file: "/_data/team6.yml"
        fields: 
          - {label: Nombre, name: name, widget: string}
          - {label: Cargo, name: rol, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: Twitter, name: twitter, widget: string}
          - {label: LinkedIn, name: linkedin , widget: string}
          - {label: Fotografía, name: "image", widget: "image"}
          - {label: Resumen, name: "body", widget: "markdown", required: true}
          - {label: Archivo CV, name: cv, widget: file}
      
      - label: "Socio 7"
        name: "team7"
        file: "/_data/team7.yml"
        fields: 
          - {label: Nombre, name: name, widget: string}
          - {label: Cargo, name: rol, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: Twitter, name: twitter, widget: string}
          - {label: LinkedIn, name: linkedin , widget: string}
          - {label: Fotografía, name: "image", widget: "image"}
          - {label: Resumen, name: "body", widget: "markdown", required: true}
          - {label: Archivo CV, name: cv, widget: file}
      
      - label: "Socio 8"
        name: "team8"
        file: "/_data/team8.yml"
        fields: 
          - {label: Nombre, name: name, widget: string}
          - {label: Cargo, name: rol, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: Twitter, name: twitter, widget: string}
          - {label: LinkedIn, name: linkedin , widget: string}
          - {label: Fotografía, name: "image", widget: "image"}
          - {label: Resumen, name: "body", widget: "markdown", required: true}
          - {label: Archivo CV, name: cv, widget: file}
      
      - label: "Socio 9"
        name: "team9"
        file: "/_data/team9.yml"
        fields: 
          - {label: Nombre, name: name, widget: string}
          - {label: Cargo, name: rol, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: Twitter, name: twitter, widget: string}
          - {label: LinkedIn, name: linkedin , widget: string}
          - {label: Fotografía, name: "image", widget: "image"}
          - {label: Resumen, name: "body", widget: "markdown", required: true}
          - {label: Archivo CV, name: cv, widget: file}

  - name: "servicios"
    label: "Servicios"
    editor:
      preview: false
    files:
      - name: title
        label: Lista de Servicios Forseti Abogados
        file: /_data/servicios.yml
        fields:
          - label: titleServicios
            name: titleSection
            widget: string
            
          - label: Servicio 1
            name: service1
            widget: object
            fields:
              - {label: Nombre del servicio, name: title, widget: string}
              - {label: Descripción, name: description, widget: markdown}
          - label: Servicio 2
            name: service2
            widget: object
            fields:
              - {label: Nombre del servicio, name: title, widget: string}
              - {label: Descripción, name: description, widget: markdown}
          - label: Servicio 3
            name: service3
            widget: object
            fields:
              - {label: Nombre del servicio, name: title, widget: string}
              - {label: Descripción, name: description, widget: markdown}
          - label: Servicio 4
            name: service4
            widget: object
            fields:
              - {label: Nombre del servicio, name: title, widget: string}
              - {label: Descripción, name: description, widget: markdown}
          - label: Servicio 5
            name: service5
            widget: object
            fields:
              - {label: Nombre del servicio, name: title, widget: string}
              - {label: Descripción, name: description, widget: markdown}
          - label: Servicio 6
            name: service6
            widget: object
            fields:
              - {label: Nombre del servicio, name: title, widget: string}
              - {label: Descripción, name: description, widget: markdown}
          - label: Servicio 7
            name: service7
            widget: object
            fields:
              - {label: Nombre del servicio, name: title, widget: string}
              - {label: Descripción, name: description, widget: markdown}
          - label: Servicio 8
            name: service8
            widget: object
            fields:
              - {label: Nombre del servicio, name: title, widget: string}
              - {label: Descripción, name: description, widget: markdown}
          - label: Servicio 9
            name: service9
            widget: object
            fields:
              - {label: Nombre del servicio, name: title, widget: string}
              - {label: Descripción, name: description, widget: markdown}
          - label: Servicio 10
            name: service10
            widget: object
            fields:
              - {label: Nombre del servicio, name: title, widget: string}
              - {label: Descripción, name: description, widget: markdown}
          - label: Servicio 11
            name: service11
            widget: object
            fields:
              - {label: Nombre del servicio, name: title, widget: string}
              - {label: Descripción, name: description, widget: markdown}

  - name: "post"
    label: "Posts"
    description: info of section
    folder: "_posts"
    create: true
    delete: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Extracto", name: "excerpt", widget: "string"}
      - {label: "fecha", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: false, hint: "Tamaño de imagen sugerida 500x100px"}
      - {label: "Contenido", name: "body", widget: "markdown"}

**Additional context**

**Comment by tomrutgers** [comment]
My best bet is that this is caused by a custom preview template trying to fetch different data than defined in your config.

**Comment by erquhart** [comment]
We may need to reproduce this ourselves to look into this. Any chance the repo is public?

**Comment by erezrokah** [comment]
Closing as stale, please re-open with more info
