### ISSUE TITLE
Frontmatter: Field "image" must not have a selection since type "String" has no subfields

### ISSUE THREAD

**Issue by eur2** [netlify/netlify-cms#2763]
Hi, I just have updated my dependencies to their last public version:
```
    "gatsby": "^2.16.5",
    "gatsby-image": "^2.2.29",
    "gatsby-plugin-manifest": "^2.2.23",
    "gatsby-plugin-netlify": "^2.1.22",
    "gatsby-plugin-netlify-cms": "^4.1.25",
    "gatsby-plugin-react-helmet": "^3.1.13",
    "gatsby-plugin-sharp": "^2.2.32",
    "gatsby-remark-images": "^3.1.28",
    "gatsby-remark-relative-images": "^0.2.2",
    "gatsby-source-filesystem": "^2.1.33",
    "gatsby-transformer-remark": "^2.6.30",
    "gatsby-transformer-sharp": "^2.2.23",
    "netlify-cms-app": "^2.9.7",
    "react": "^16.10.2",
    "react-dom": "^16.10.2",
    "react-helmet": "^5.2.1"
```
After this update, I have deleted cache and node_modules folders and did a fresh install to be on a good base.
I have an image widget in the frontmatter and it was working totally fine until netlify-cms-app 2.9.6. In 2.9.7, with the graphQL explorer, I see that this image field is no longer working as an image but just as a string. So it doesn't have anymore id, publicURL, etc.
Of course now, I'm getting this gatsby error as the image doesn't have subfields anymore:
`Field "image" must not have a selection since type "String" has no subfields
`
Does anyone has encountered this weird behavior with the last version of netlify-cms-app?

**Comment by eur2** [comment]
I have been experimenting around this issue. Here are my observations about the behavior of netlify-cms with a field in the frontmatter, in this case an image widget. 
There are 3 possibilities and one is provoking the famous `Field "image" must not have a selection since type "String" has no subfields`:

**Case 1:** The image is selected and everything is working fine in the markdown:
`image: /assets/image.jpg
`

**Case 2:** The image selected is now deleted through the admin interface. It's rendering this empty string in the markdown file:
`image: ''`
This is causing the error `Field "image" must not have a selection since type "String" has no subfields` in gatsby.

**Case 3:** There is no image at all and the field is empty in the interface. It's rendering no field in the markdown and everything is working fine.

@erquhart What is the best way to avoid this behavior? It's happening often that a user or a client deletes a frontmatter's image in the admin.

**Comment by hppRC** [comment]
I have same problem.
Sometimes I can build locally(a few cases, and I don't understand why), but I can't deploy to Netlify.

**Comment by hppRC** [comment]
@eur2 
I finally solved this problem!
Actually, this is not a Netlify CMS problem.

I found an issue with the same problem. ([https://github.com/gatsbyjs/gatsby/issues/12610#](https://github.com/gatsbyjs/gatsby/issues/12610#))
Although detailed in [this issue](https://github.com/gatsbyjs/gatsby/issues/12610#), here are some critical solutions.

please add this code to gatsby-node.js.
```gatsby-node.js
//top of the file
//--------------please make sure you import this--------------------
const path = require(`path`);
const { createFilePath } = require(`gatsby-source-filesystem`);
const { fmImagesToRelative } = require('gatsby-remark-relative-images');
//-------------------------------------------------------------------

exports.createPages = ({ graphql, actions }) => {
...

...
}


//add this
//-------------------------------------------------------------
exports.onCreateNode = ({ node, actions, getNode }) => {
	const { createNodeField } = actions;
	fmImagesToRelative(node);
// if you use mdx, please change `MarkdownRemark` to `Mdx`
　　 if (node.internal.type === `MarkdownRemark`) {
		const value = createFilePath({ node, getNode });
		createNodeField({
			name: `slug`,
			node,
			value
		});
	}
};
//------------------------------------------------------------

```

and change gatsby-config.js
```gatsby-config.js
module.exports = {
	siteMetadata: {
...
	},
	plugins: [
...
//-----------------add this----------------------------
    {
	resolve: `gatsby-source-filesystem`, // this entry has to be the first or will not work as per FAQ
	    options: {
		path: `${__dirname}/static/assets`,
		    name: `assets`
	     }
     },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          `gatsby-remark-relative-images`,
...
          ]
      }
  },

//--------------------------------------------------------
...

}
```



I would be happy if it would help you.

**Comment by erquhart** [comment]
Guessing you're using the Gatsby Netlify CMS starter? Pretty sure this has something to do with image fields being objects in Gatsby builds (due to sharp/remark), but a string in the CMS preview pane. Some React component code is reused for both cases and I believe there are things being imported in the browser that shouldn't be (Eg. Gatsby, not sure how that isn't breaking literally everything, maybe just silently failing to import).

**Comment by eur2** [comment]
@erquhart Indeed it's probably due to gatsby sharp/remark.
Will try check this image behavior in Gatsby with another CMS (sanity.io for example)
Also will check netlify-cms image behavior with another framework (sapper.js)

**Comment by phil-lgr** [comment]
wow. after hours of searching this problem, I realize I had a special character in one of the image path like:

```
featuredimage: /img/file-with-an-é.png
```

I think that `gatsby-remark-relative-images` is having trouble with special characters in path

**Comment by eur2** [comment]
@phil-lgr Thanks to share this good observation but normally when you upload images with netlify-cms interface, it's sanitizing the name of the image no?

**Comment by phil-lgr** [comment]
No, not with the default settings @eur2 AFAIK

**Comment by hedleysmith** [comment]
Just to add that I encountered the same error message. In my case the image path in my markdown file was incorrect - the image path should have been relative to the markdown file (`../../images/image.png`), when it was a path relative to the project root (`/images/image.png`).

Changing the image path gave a quick fix.

The package `gatsby-remark-relative-images` also helps by allowing paths relative to the project root!

**Comment by erezrokah** [comment]
Hi @hedleysmith, I would recommend trying using relative paths for media folders:
https://www.netlifycms.org/docs/beta-features/#folder-collections-media-and-public-folder.
This way the CMS will populate the markdown with relative values.

**Comment by erezrokah** [comment]
Regardless, this seems more of a Gatsby issue now (since the CMS supports both ways - absolute an relative paths to images)

**Comment by tjscivsav** [comment]
> 

Hi can please send the code and graphql
