### ISSUE TITLE
I am having problem to use netlify CMS on my phone

### ISSUE THREAD

**Issue by TahsinProduction** [netlify/netlify-cms#2765]
Whenever I try to write on my phone I can't edit previous files. And after using it for couple of minutes, it give me this message,

> Error
There's been an error - please report it.

Details
Error: Unable to find a DOM node for "16". This is often because of forgetting to add `props.attributes` to a custom component.

Recovered document
Please copy/paste this somewhere before navigating away!Copy to clipboard
---
title: Background Story Of xxxxxxxxxxxxxxxxxxxx Website
date: 2019-09-06T05:56:34.457Z
draft: false
categories: Posts
tags:
  -xxxxxxxxxxxxxxxxxx
author: xxxxxxxxxxxxxxxxxxxx
type: post
---
The will the post where about when I had the idea of creating this website. I am busy now so will post soon.

Here is a screenshot
![SmartSelect_20191020-195209_Chrome](https://user-images.githubusercontent.com/53980937/67160496-3192be80-f373-11e9-8251-adf2faf85ef1.jpg)

**Comment by tomrutgers** [comment]
The CMS isn't optimized for mobile usage yet. You can track the feature request here: https://github.com/netlify/netlify-cms/issues/441. Closing this as a duplicate
