### ISSUE TITLE
When loading collection entries, ignore non-markdown files

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#278]
Currently every file in a folder based collection is expected to be an entry - even having a `.keep` file will break the app. Instead, the CMS should simply ignore files that are not markdown.

**Requirements**
* Check the extensions of entries when loading files for a folder based collection
* If the file extension is `md`, process as usual
* If the file extension is not `md`, ignore it

**Considerations**
* Some markdown files may also need to be ignored, as mentioned in #218 
* In lieu of formally accepting a list of files to ignore in the config, we could adopt the convention of ignoring markdown files prefixed with an underscore

**Comment by tech4him1** [comment]
We wouldn't to just ignore all markdown files that start with an underscore, because some CMS's such as Hugo use them (for example `content\_index.md`).

**Comment by erquhart** [comment]
@tech4him1 thanks for that - somehow I wasn't considering that you'd want to edit the index file in the CMS 🙄

**Comment by josephearl** [comment]
So the files view of the collection should only show files matching the extension defined in the collection or `.md` if none is defined?

What about `.markdown` files if I have the extension set to `.md` - is that something we should handle, or leave for now (see https://github.com/netlify/netlify-cms/issues/317)?

**Comment by erquhart** [comment]
@josephearl we can keep the two issues separate, but fixing both on one shot is also welcome.

**Comment by josephearl** [comment]
@erquhart one option then is we could allow an array of extensions for a collection (or a string if just a single value) - with the default changing from `'md'` to `['md', 'markdown']`. The first extension would be used when creating files; how does that sound?

**Comment by erquhart** [comment]
@josephearl that works so long as we can still accept a string value (current behavior doesn't break).
