### ISSUE TITLE
Number widgets marked optional with a min/max value are not optional.

### ISSUE THREAD

**Issue by saenglert** [netlify/netlify-cms#2785]
**Describe the bug**
Number widgets marked optional with a min/max value are not optional.

**To Reproduce**
1. Define widget
```
- {name: size, label: Größe, widget: number, valueType: float, min: 1, max: 3, step: 0.01, required: false}
```
2. Try to leave it blank in cms
3. Error `Größe must be between 1 and 3`

**Expected behavior**
Min/Max should only apply if a value was provided

**Screenshots**
![numberWidgetOptional](https://user-images.githubusercontent.com/6491588/67374170-185f5d00-f581-11e9-94ce-61cd4bee39ef.JPG)

**Applicable Versions:**
 - Netlify CMS version: 2.9.7
 - Git provider: GitHub
 - OS: Win 10
 - Browser version: Firefox 69.0.3
 - Node.JS version: 10.15.3

**CMS configuration**
```
- {name: size, label: Größe, widget: number, valueType: float, min: 1, max: 3, step: 0.01, required: false}
```

**Comment by erezrokah** [comment]
Thanks for the issue @saenglert. Should be fixed with #2792 (I would have merged it sooner but we had an issue with GitHub Actions failing due to timeouts when setting up node).
