### ISSUE TITLE
Invisible form validation

### ISSUE THREAD

**Issue by saenglert** [netlify/netlify-cms#2791]
**Describe the bug**
Nested widgets are validated but do not display error feedback unless opened

**To Reproduce**
1. Create nested widget (list, object ...)
2. Add some required fields to it
3. Submit without input
4. Validation Error pops up
5. No red outline on collapsed nested widgets

**Expected behavior**
At the very least a red outline should appear around the containing widget informing the user about the validation error. Even better the nested widget should be opened/focused.

**Screenshots**
![validationNested](https://user-images.githubusercontent.com/6491588/67394272-2d99b300-f5a4-11e9-9533-a708dfae12da.JPG)
![validationNestedOpened](https://user-images.githubusercontent.com/6491588/67394286-32f6fd80-f5a4-11e9-8286-08df2f81281b.JPG)

**Applicable Versions:**
- Netlify CMS version: 2.9.7
- Git provider: GitHub
- OS: Win 10
- Browser version: Firefox 69.0.3
- Node.JS version: 10.15.3

**Additional context**
Sorry for my flurry of new issues today but I'm about to wrap up a project and of course now the nitty-gritty details start to show and I had multiple testers have trouble with this.

**Comment by erquhart** [comment]
Yeah we should at least be expanding widgets whose children have validation errors.
