### ISSUE TITLE
Separate Media Folder for File and Images Widget

### ISSUE THREAD

**Issue by mateuswetah** [netlify/netlify-cms#2794]
**Is your feature request related to a problem? Please describe.**
I know there is a lot of discussion regarding folder organization of media files (#513, #1046, #1472)... But the solution that people have been proposing of having media folders relative to collections may not be enough. I some cases you may want widget-level folder structure.

**Describe the solution you'd like**
I would like to be able to configure `images` and `file` widgets with different folders. The reason for that is that I want to put my images on an Assets folder, that is handled every time by optimization scripts, and the rest of the files, such as PDFs, could go on a Static folder.

**Describe alternatives you've considered**
I might be choosing the harder path here, maybe it should be on Webpack's shoulder to deal with the necessary image file types and the rest could be ignored... Also, I have just received this [recomendation](https://github.com/webpack-contrib/copy-webpack-plugin).

**Comment by jeromecoupe** [comment]
For most of my projects, a single folder for all assets / images is what is keeping me from going fully git-based. I think that the widget level approach might be a good one. I am no React dev but here is what I have in mind.

- keep `media_folder` and `public_folder` as general config option so we keep one base location for all assets
- allow `media_folder_path` and `media_folder_url` as config options per file or image widget that would be concatenated with the general config options

Maybe that would preserve the current behaviour and keep everything in a centralised location which is easier to browse and make sense of for users, while giving developers a bit more flexibility.

**Comment by erezrokah** [comment]
Should be fixed with https://github.com/netlify/netlify-cms/pull/3208
