### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Zinenda** [netlify/netlify-cms#2804]
![Screenshot_2019-10-24 Painel Admin](https://user-images.githubusercontent.com/11368305/67521962-26f66300-f6ac-11e9-929d-a1dc2a3c34f2.png)
![Screenshot_2019-10-24 Painel Admin](https://user-images.githubusercontent.com/11368305/67522146-7dfc3800-f6ac-11e9-95b4-ac833d773656.png)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by danoszz** [comment]
@Zinenda what are the steps you took to get this error? Could you maybe share a bit more information?

**Comment by tomrutgers** [comment]
@Zinenda Assuming [this](https://github.com/Zinenda/CargaDiariaMotivacao/blob/master/admin/config.yml) is the config.yml causing the problem

You need to change your list widget to a select widget:
```
- label: "Categorias"
  name: "category"
  widget: "select"
  options: ["Empreendedores", "Saude", "Pessoal"]
```
