### ISSUE TITLE
Folder Collection pages not displaying

### ISSUE THREAD

**Issue by kingofzeal** [netlify/netlify-cms#2811]
**Describe the bug**
I have a folder collection defined, but no existing content seems to be displaying in the collection. 

**Expected behavior**
When adding a folder collection, any existing content in the defined `folder` should be displayed as an item in the collection.

**Screenshots**
This is the view when I load the Event collection in CMS.
![image](https://user-images.githubusercontent.com/4563328/67639541-dc990000-f8be-11e9-93f6-9280a8642c99.png)

**Applicable Versions:**
 - Netlify CMS version: 2.9.7
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version Chrome 77

**CMS configuration**
https://github.com/ManitowocMarineBand/mmbWebsite/blob/master/static/admin/config.yml
Specifically, the issue is with the `events` collection.

**Additional context**
This is very similar to the issue reported in #1411, however the fix noted there (to specify an extension) does not seem to address the issue I am running into.

I am able to add new items to the collection, but even after publishing it, it still does not show in the list.

**Comment by tomrutgers** [comment]
Try updating your slug:
`slug: "{{fields.startDate}}-{{slug}}"`

**Comment by kingofzeal** [comment]
That does seem to have fixed it for new entries at least. So the `slug` property is not only used to generate the filename, but also determine which content to be read for a collection?

I'll see what I can do about re-working my existing filenames and slugs to work with those constraints. Thanks!
