### ISSUE TITLE
Testing a NetlifyCMS config.yml

### ISSUE THREAD

**Issue by kylekirkby** [netlify/netlify-cms#2818]
Hi all!

Just a quick query, hopefully! Could you point me in the right direction for testing a NetlifyCMS config.yml file? I'm writing a python script to process a Jekyll site and generate a netlifycms config.yml for use across our static sites. It would be good to test the generated config.yml to make sure that it will work with netlifycms.  Any ideas?

[NetlifyCMS Jekyll config generator repo](https://github.com/linaro-marketing/jekyll_netlifycms_config_generator/blob/master/main.py)

@erquhart 

Thanks in advance! 

Best regards,

Kyle

**Comment by tomrutgers** [comment]
You can try the `test-repo` [backend](https://www.netlifycms.org/docs/authentication-backends/#test-repo-backend), which basically ignores your data files.

Or you can edit this brilliant codepen by @erquhart: https://codepen.io/erquhart/pen/dgNEYo

**Comment by kylekirkby** [comment]
Thanks @tomrutgers! I'll look into the above :)

**Comment by tomrutgers** [comment]
Can I close this @kylekirkby?

**Comment by kylekirkby** [comment]
@tomrutgers - Yh sure - do we have documentation listing how to test a config.yml is valid? Maybe we should add something to the docs pointing people in the right place for testing a config?

**Comment by tomrutgers** [comment]
There's not really much of a way to test configs other than trial and error really, so I'm not sure what to document about it.
