### ISSUE TITLE
Add JSON(other) to the readable config formats

### ISSUE THREAD

**Issue by bdougie** [netlify/netlify-cms#283]
**- Do you want to request a *feature* or report a *bug*?**
After consultant with a Netlify/Hexo user I found that by default hexo converts yml to json. This can be fixed by adding the `admin/config.yml` to the `skip_render` section

**- What is the current behavior?**
It would be nice to add other formats, like toml or json for the config.

**Comment by josephearl** [comment]
:+1: TOML support would be great for Hugo. Ideally Netlify CMS should be able to read posts using any supported format and would let me configure which format it writes with.

**Comment by erquhart** [comment]
@josephearl this issue is about the config file format - the front matter issue you're referring to is covered under #227. Definitely something we'd like to see happen. If you're up for making it happen please comment there, and I'm happy to assist if needed.

**Comment by josephearl** [comment]
Thanks @erquhart, front matter was what I was after - I'll give #227 a go.

**Comment by erquhart** [comment]
Closing in favor of #386.
