### ISSUE TITLE
"Invalid hook call" error in Netlify after install and build using Gatsby.js

### ISSUE THREAD

**Issue by Isaaclipse** [netlify/netlify-cms#2830]
Hello everyone,

I'm new to Netlify and I have errors when I try building after I installed Netlify using this tutorial: https://www.gatsbyjs.org/docs/sourcing-from-netlify-cms/

After I try to do **'gatsby develop'** I get this error:

> The above error occurred in the <StoreStateProvider> component:
>    in StoreStateProvider
>    in App
> 
> React will try to recreate this component tree from scratch using the error boundary you provided, App.
> 
> Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
> 
> ERROR
> 
> UNHANDLED REJECTION Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
> 

I did **'NPM ls react'** and **'NPM ls react-dom'** and both my react and react-dom versions are matching, but they both say **UNMET DEPENDENCY** in the top of my tree and in subdirectories and **UNMET PEER DEPENDENCIES** for Netlify. Here is my file tree for reference.

_├─┬ gatsby@2.17.7
│ └─┬ UNMET DEPENDENCY gatsby-cli@2.8.8
│   └── UNMET DEPENDENCY react@16.11.0
├─┬ gatsby-custom-md@1.3.0
│ └── UNMET DEPENDENCY react@16.11.0
└─┬ netlify-cms-app@2.9.7
 └─┬ netlify-cms-core@2.12.2
   └── UNMET PEER DEPENDENCY react@16.11.0
------------------
gatsby-starter-elemental@0.1.0
├─┬ gatsby-custom-md@1.3.0
│ └── UNMET DEPENDENCY react-dom@16.11.0
└─┬ netlify-cms-app@2.9.7
 └─┬ netlify-cms-core@2.12.2
   └── UNMET PEER DEPENDENCY react-dom@16.11.0_

**To Reproduce**

1. Go to https://www.gatsbyjs.org/starters/akzhy/gatsby-starter-elemental/ and install this starter locally then cd into this project directory
2. Install and setup netlify using this tutorial https://www.gatsbyjs.org/docs/sourcing-from-netlify-cms/
3. Run 'gatsby develop' 

**Expected behavior**

Gatsby develop should start up development server and a netlify admin page as laid out in tutorial.

**Applicable Versions:**
 - Netlify CMS version: [2.9.7]
 - Git provider: [GitHub]
 - OS: [MacOS Mojave 10.14.6]
 - Node.JS version: v10.16.0

**CMS configuration**

_backend:
  name: test-repo

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }_

I appreciate any help or suggestions!

**Comment by afucher** [comment]
I don't think that this is related to netlify, I have the same issue building and running locally.

There is an issue on gatsby https://github.com/gatsbyjs/gatsby/issues/19064

**Comment by erezrokah** [comment]
Closing as stale, please comment re-open if issue persists
