### ISSUE TITLE
Loading entries does not work with Github backend

### ISSUE THREAD

**Issue by chrfritsch** [netlify/netlify-cms#2844]
**Describe the bug**
I have an issue very similar to https://github.com/netlify/netlify-cms/issues/2629

After login I can see all my posts, clicking on one I get "Failed to load entry: Access to endpoint not allowed: this part of GitHub’s API has been restricted"

My network looks like:
<img width="1835" alt="netlifycms-error" src="https://user-images.githubusercontent.com/731161/68238404-66587400-0009-11ea-9daa-f90003a8ccc3.png">

**To Reproduce**
Here is my repo https://github.com/TSV-Zorneding-1920/tsv-zorneding-tischtennis and it's connected to https://vigorous-newton-f5373c.netlify.com/

**Expected behavior**

I can edit my existing posts.

**Applicable Versions:**

 - Netlify CMS version: 2.9.8-beta.4
 - Git provider: git-gateway
 - OS: MacOS
 - Browser version Chrome 78

 - Node.JS version: 12.11

**CMS configuration**
[https://github.com/TSV-Zorneding-1920/tsv-zorneding-tischtennis/blob/master/static/admin/config.yml](https://github.com/TSV-Zorneding-1920/tsv-zorneding-tischtennis/blob/master/static/admin/config.yml)

**Additional context**

**Comment by erquhart** [comment]
@erezrokah note: keep in mind that Git Gateway is impacted by all GitHub/GitLab backend changes. We'll need test coverage of the Git Gateway backend to keep pace with the backends that it wraps.

**Comment by erezrokah** [comment]
I think I'm going to prioritize the cypress tests for the other backends once I finish with my current task.

**Comment by chocobuckle** [comment]
Thanks for your work @erezrokah - this bug is a bit of a showstopper for us today, so much appreciated! :)

**Comment by chocobuckle** [comment]
Just wondering is this only an issue with 2.9.8-beta.4? Or was it also in the earlier 2.9.8 betas?

**Comment by erezrokah** [comment]
I might be wrong but I think was also in earlier 2.9.8 betas and was only partially fixed for the latest beta here: https://github.com/netlify/netlify-cms/pull/2631

**Comment by chrfritsch** [comment]
@chocobuckle You can install https://www.npmjs.com/package/patch-package in your project and copy the patches folder from https://github.com/TSV-Zorneding-1920/tsv-zorneding-tischtennis to your project and then it should work. It's a workaround

**Comment by chocobuckle** [comment]
@chrfritsch Interesting! Never heard of patch-package. Sounds super useful! I'll give it a go. Thanks for sharing.
