### ISSUE TITLE
GitHub Draft branches with more then 30 commits get "Editorial workflow branch changed unexpectedly." Error

### ISSUE THREAD

**Issue by tkarssli** [netlify/netlify-cms#2847]
**Describe the bug**
Once a draft branch on github has more than 30 commits the CMS starts showing the error "Editorial workflow branch changed unexpectedly.".

**To Reproduce**

1. Create a draft branch and add 29 commits
2. Try to save a few changes in CMS

**Expected behavior**

"Editorial workflow branch changed unexpectedly." Is shown in the CMS and no changes are saved to the Draft branch.

**Applicable Versions:**

- Netlify CMS: 
  * netlify-cms-app 2.9.7
  * netlify-cms.js:57932 netlify-cms-core 2.12.2
  * netlify-cms.js:168771 netlify-cms 2.9.7
 - Git provider: GitHub
 - Browser version: Chrome Version 78.0.3904.70 (Official Build) (64-bit)

 - Node.JS version: 10.6 ^

**Comment by erquhart** [comment]
Almost definitely a pagination issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by erezrokah** [comment]
As suggested here: https://github.com/netlify/netlify-cms/issues/2406#issuecomment-551155823 by @barthc for another GitHub REST API limit, switching to GraphQL fixes this (assuming you're using `github` backend and not `git-gateway`. 

I tested with 32 commits...
