### ISSUE TITLE
'optionsLength' option no longer working in relation widget

### ISSUE THREAD

**Issue by chocobuckle** [netlify/netlify-cms#2849]
**Describe the bug**
'optionsLength' option no longer working in relation widget. It's just displaying the first 20 (default) results.

**To Reproduce**
Add optionsLength: 100 to a relation widget. It still shows the first 20 results. 

**Screenshots**
I'm using manual initialization here. So all my config is in .js files, not yaml.

'Activities' collection...
```
const activities = {
  label: 'Activities',
  label_singular: 'Activity',
  name: 'activities',
  folder: 'src/cms/data/activities',
  create: true,
  slug: '{{slug}}',
  show_preview_links: true,
  preview_path: '/team-building/',
  editor: {
    preview: false
  },
  fields: [
    {
      label: 'Title',
      name: 'title',
      hint: 'What is the name of the activity?',
      widget: 'string'
    },
    ...
  ]
};

export default activities;

```
'Venues' collection...
```
const venues = {
  label: 'Venues',
  label_singular: 'venue',
  name: 'venues',
  folder: 'src/cms/data/venues',
  create: true,
  slug: '{{slug}}',
  show_preview_links: true,
  editor: {
    preview: false
  },
  fields: [
    {
      label: 'Venue Name',
      name: 'title',
      hint: 'What is the name of the venue?',
      widget: 'string'
    },
    {
      label: 'Services',
      name: 'services',
      widget: 'object',
      fields: [
        {
          label: 'Team Building',
          widget: 'relation',
          optionsLength: 100,
          collection: 'activities',
          searchFields: 'title',
          valueField: 'title',
          multiple: true,
          default: [],
          required: false
        },
        {
          label: 'Event Management',
          name: 'eventManagement',
          widget: 'relation',
          optionsLength: 200,
          collection: 'eventManagementServices',
          searchFields: 'title',
          valueField: 'title',
          multiple: true,
          default: [],
          required: false
        }
      ]
    }
  ]
};

export default venues;

```
cms.js
```
window.CMS_MANUAL_INIT = true;

import CMS from 'netlify-cms-app';
import {
  activities,
  venues
} from 'cms/collections';

CMS.init({
  config: {
    load_config_file: false,
    backend: {
      name: 'git-gateway',
      squash_merges: true
    },
    media_folder: '/static/uploads',
    public_folder: '/uploads',
    site_url: 'https://dynamic-events.netlify.com',
    collections: [activities, venues]
  }
});
```
But as you can see from this screen capture, it's still showing just the first 20. There is at least 50 added, and we hope to add over 100. But not much use if we can only select out of the first 20...

![screen_capture](https://user-images.githubusercontent.com/20409668/68285254-d51fe680-0076-11ea-9251-f1995900c7be.gif)

**Applicable Versions:**
 - Netlify CMS version: netlify-cms-app 2.9.7, netlify-cms-core 2.12.2
 - Git provider: GitHub
 - Node.JS version: v12.13.0

**Comment by barthc** [comment]
@chocobuckle  looks like the CMS version you are using precedes the `optionsLength` feature, could you please upgrade and test again.

**Comment by chocobuckle** [comment]
I'm on netlify cms app 2.9.7, which is the latest published version - https://www.npmjs.com/package/netlify-cms-app

Do you mean upgrade to the latest beta release? 2.9.8-beta.4, yes?

**Comment by barthc** [comment]
Whoops, look like the latest version is 3months old. Yes use the beta instead, you should be good.

**Comment by chocobuckle** [comment]
@barthc Unfortunately, upgrading to 2.9.8-beta.4 results in the following error when using git-gatway... [#2844](https://github.com/netlify/netlify-cms/issues/2844)

**Comment by chocobuckle** [comment]
But I presume once that issue is fixed, then i'll be able to use the optionsLength feature without problems, so i'm gonna close this issue and keep an eye on [#2844](https://github.com/netlify/netlify-cms/issues/2844). Thanks for your help! :)
