### ISSUE TITLE
Enable configuration of github commit status for preview links

### ISSUE THREAD

**Issue by Levino** [netlify/netlify-cms#2850]
We have 2 sites deploying from the same repository (a gatsby homepage and a react storybook). When I create a draft in netlify-cms the preview link goes to the deploy preview of the storybook and not the homepage. I guess netlify-cms just takes the first commit status that looks "promising". As these commit status have different name it would be cool if I could configure which one to use in the /admin/config.yml

**Comment by erezrokah** [comment]
Hi @Levino, you can configure this via https://www.netlifycms.org/docs/github-backend/#specifying-a-status-for-deploy-previews

By deploy the CMS looks for `deploy` in the context: https://github.com/netlify/netlify-cms/blob/0bdddfd43b45e4a7cb2a7d7c90e5eb005b2e317d/packages/netlify-cms-lib-util/src/API.ts#L149
