### ISSUE TITLE
Creating of new posts doesn't work

### ISSUE THREAD

**Issue by chrfritsch** [netlify/netlify-cms#2853]
**Describe the bug**

I can't create new posts. I am getting "Failed to persist entry: API_ERROR: Not Found" 

**To Reproduce**

It can be reproduced in this repo: https://github.com/TSV-Zorneding-1920/tsv-zorneding-tischtennis

I have it with blog posts and static pages.

**Expected behavior**

I can create new pages.

**Screenshots**

<img width="1405" alt="Bildschirmfoto 2019-11-08 um 16 07 38" src="https://user-images.githubusercontent.com/731161/68486696-eb2dd280-0241-11ea-8a8e-9626bc986b99.png">

**Applicable Versions:**

 - Netlify CMS version: netlify-cms-app 2.9.8-beta.5
 - Git provider: git-gateway with GitHub repo
 - OS: macOS
 - Browser version: Chrome 78

 - Node.JS version: v12.11.1

**CMS configuration**

[https://github.com/TSV-Zorneding-1920/tsv-zorneding-tischtennis/blob/master/static/admin/config.yml](https://github.com/TSV-Zorneding-1920/tsv-zorneding-tischtennis/blob/master/static/admin/config.yml)
**Additional context**

**Comment by tomrutgers** [comment]
The org account needs to grant access to your Netlify CMS instance: https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/requesting-organization-approval-for-oauth-apps

**Comment by chrfritsch** [comment]
Thank you @tomrutgers. You saved my day :)
