### ISSUE TITLE
Prompt to save unsaved changes on browser close

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#286]
#249 provided a prompt to save unsaved changes when navigating browser history or cancelling from the UI, but the prompt does not occur if the user attempts to close the browser tab/window. 

*Requirements*
* If a user closes the browser tab/window, they should be prompted and allowed to cancel the action

**Comment by rolfea** [comment]
Hi there, @erquhart ! I'd be happy to work on this.

**Comment by erquhart** [comment]
@rolfea great! 🍻 Feel free to check the pull request I mentioned above as prior art, and reach out on [Gitter](https://gitter.im/netlify/netlifycms) if you have any questions along the way.
