### ISSUE TITLE
End-to-end testing for built in media library

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#2872]
### Overview
This issue outlines paths for testing the built in media library interface with Cypress. All tests should utilize the **test-repo** backend. An [existing Cypress test](https://github.com/netlify/netlify-cms/blob/master/cypress/integration/editorial_workflow_spec_test_backend.js) that uses the test backend can serve as a general example.

See CONTRIBUTING.md for test commands. [**`test:e2e:dev`**](https://github.com/netlify/netlify-cms/blob/master/CONTRIBUTING.md#teste2edev) is especially useful for running Cypress tests locally on watch mode.

### Paths
The live [CMS demo](https://cms-demo.netlify.com) can be used to step through these paths for reference. The same demo runs for Cypress tests locally.

#### Upload image
- Click "Media" in the top bar
- Use the "Upload new" button to upload an image (nothing will be uploaded, only stored in memory)
- Image should appear in the media library

#### Delete image
- Follow "Upload image" steps
- Select an uploaded image by clicking it
- Click the "Delete selected" button to delete the image
- Image should disappear from media libary

#### Insert image
- Click "New Post" to create a new entry
- In the "Cover Image" field, click the "Choose an image" button
- In the media library modal, use the "Upload new" button to upload an image
- Click on an uploaded image to select it
- Click the "Choose selected" button to insert the image
- The modal should close
- The "Cover Image" field should show the selected image.

**Comment by smohtadi** [comment]
Hi, I would like to work on this. Is it open?

**Comment by erquhart** [comment]
Hi @smohtadi - this is assigned to someone but I forgot to actually assign it 🤦‍♂ 

cc/ @bahmutov @amirrustam 

@erezrokah know of any other e2e targets in need of coverage?

**Comment by erezrokah** [comment]
> Hi @smohtadi - this is assigned to someone but I forgot to actually assign it 🤦‍♂
> 
> cc/ @bahmutov @amirrustam
> 
> @erezrokah know of any other e2e targets in need of coverage?

We don't have non-editorial workflow tests for the GitHub backend

**Comment by erezrokah** [comment]
This is covered here https://github.com/netlify/netlify-cms/issues/2872 (expect deletion - I'll add that soon)
