### ISSUE TITLE
Use multiple preview styles on a per file/collection basis without using preview templates

### ISSUE THREAD

**Issue by willdante** [netlify/netlify-cms#2892]
Hi,

I'd like to apply different styles in the preview panel on a per file basis in a simple way.

I've tried to use preview templates but it didn't work properly, maybe because of a bad setup.

But I think it would be overkilled for my needs as I'd just need to add some styles for bold, em, code and headings.
These simple styles should be different regarding the files though.

Is there any simple way to do that ?

Thanks in advance.

**Comment by erezrokah** [comment]
Can you share your preview templates code?
You should be able to set different css class names/previews based on the entry fields.

**Comment by willdante** [comment]
I have deleted my preview templates as they weren't working.
I was asking about the possibility to apply some small styles to a collection without using templates.
It doesn't exist yet I guess, but maybe it could be something useful to add.

**Comment by erezrokah** [comment]
You could register just the styles: https://www.netlifycms.org/docs/customization/#registerpreviewstyle
But I'm not sure you'll be able to control it on a per file basis

**Comment by willdante** [comment]
Yes I know about it and indeed, it's not possible to control it on a per file basis.

That's why I've opened the issue in the beginning 😉

**Comment by erezrokah** [comment]
What do you have in mind? having some way of doing it in the `config.yml`? I think that would be even more complicated and limited

**Comment by willdante** [comment]
Yes, that's what I had in mind but I guess you're right.

I have a special case where a simple css file link in the config.yml would have been great and just wanted to know if it was kinda possible.

But in a normal situation, I suppose it wouldn't be very useful.

My case is when importing markdown content blocks in different places in web pages, with different styles.
But as these are little blocks with only 3 to 5 styles, it would be tedious to create templates for each different content blocks.

**Comment by erezrokah** [comment]
I'm not sure I understand your scenario.
Are you trying to have multiple styles for multiple collections (e.g. need multiple templates), or just one collection with different styles based on the content?

In both case I think you should be able to use a single function to create the template and conditionally set class names to change the styles.

**Comment by willdante** [comment]
I'm going to dig further as I never managed to get my templates and styles working as expecting in the preview panel.

My specific case is that I include different content blocks from Netlify CMS into different <div> in my pages.
And to apply some specific styles to bold, italic, code, etc, I have the parent class on each div.

So I should indeed use preview templates for that, but it seems to tedious and complex for such small css code.

So in my case, every content block that can be modified by the final client could potentially have some specific css for the different tags allowed in the editor.

Preview style can't work as Netlify CMS preview panel is not aware of the parent div that select the good CSS for the block.

And Preview templates seems overkilled and tedious to me.

But I don't want to waste your time more than I already did ;)
I'm going to make some other tests with templates.

Thanks a lot for your time.

**Comment by erezrokah** [comment]
Cool, I'm closing this for now - please re-open if you have other questions
