### ISSUE TITLE
Netlify CMS rendering content in wrong tab on website

### ISSUE THREAD

**Issue by Chizzah** [netlify/netlify-cms#2894]
**Describe the bug**

I have three collections (breakfast, starters and pizza). Each collection has its own tab on the menu page. When I add a new item to pizza it renders on the breakfast tab. When I add a new item for starters it does not render at all. The only one working as intended is the breakfast tab which's content renders on in the correct tab when I add a new breakfast item.

I am using gridsome and vuejs

**To Reproduce**

Make 3 collections
Add 3 collections to tabs on same page
Create new items for each collection

**Expected behavior**

I expect each collection item I add to render in the correct tab.

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: v2.9.7
 - Git provider: Github
 - OS: Windows 10
 - Browser version: v78.0.3904.108

https://github.com/Chizzah/giuseppes/blob/master/src/admin/config.yml

**Additional context**

**Comment by erquhart** [comment]
Netlify CMS doesn’t control rendering, it just creates raw content. You can see in a recent commit, for example, that pizza content is being changed as expected by the CMS: https://github.com/Chizzah/giuseppes/commit/ec49702b07fb3d8d6bb88b7cddd70d99925e2011

You’ll want to look into your Gridsome setup to understand why your site isn’t rendering as expected.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
