### ISSUE TITLE
docs: Locales must to be registered before initialization

### ISSUE THREAD

**Issue by chrfritsch** [netlify/netlify-cms#2895]
We should document that locales must be registered before initialization when manually initializing the CMS without a static admin.yml file.

```
import CMS from "netlify-cms-app";

import { de } from "netlify-cms-locales";

CMS.registerLocale("de", de);

CMS.init({
  config: {
    backend: {
      ...
    },
    locale: "de",
  }
})
```

**Comment by gopchi** [comment]
Is it possible to use locales with CDN loaded netlify-cms-app package? The above code doesn't work for me when init the CMS in Gatsby. I just load the CMS in an admin.html file via CDN.

**Comment by tomrutgers** [comment]
@gopchi this feature is available @ `netlify-cms@2.10.0-beta.3`

**Comment by gopchi** [comment]
@tomrutgers Thanks, I will use that version!

**Comment by erezrokah** [comment]
This is no longer required as all locales are registered in `netlify-cms-app`
