### ISSUE TITLE
vuepress cms problem report

### ISSUE THREAD

**Issue by zahedbri** [netlify/netlify-cms#2907]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by zahedbri** [comment]
issues resport

**Comment by tomrutgers** [comment]
What issue are you encountering? We need some details to help you out
