### ISSUE TITLE
Ability to delete cards outside of editorial workflow

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#291]
Projects that do not utilize the editorial workflow have no way of deleting posts through the interface. We want to provide a way to do this with minimal impact to the current interface, so we'll simply provide the delete button when viewing the post directly, on the Entry page.

*Requirements*
* Add a "Delete Entry" button to the entry page, on the left side of the footer bar, opposite the "Save" and "Cancel" buttons.
* The button can be styled to match the Cancel button - text with no background or border.

**Comment by juliankrispel** [comment]
would love to help with this O_O, any direction?

**Comment by Benaiah** [comment]
@juliankrispel I actually have this working already for the non-editorial workflow - I'm currently trying to figure out a confusing issue with the editorial workflow that's causing the UI to get out of sync with the repo. I'd appreciate a second pair of eyes to try to find the source of the bug, though - if you're still interested, let me know here or on Gitter and I'll push my branch and explain the issue in more detail.

**Comment by juliankrispel** [comment]
@Benaiah I am interested/would like to help!

**Comment by techdot** [comment]
This will be a nice feature. @Benaiah will this have control flag, something like deletable:true/false flag?

**Comment by bdot** [comment]
This will be a nice feature. @Benaiah will this have control flag, something like deletable:true/false flag?

**Comment by tech4him1** [comment]
@Benaiah it doesn't look like you really meant to close this in #485?

**Comment by Benaiah** [comment]
@tech4him1 why not? That PR enabled deletion in the simple workflow, which is the subject of this issue ("Ability to delete cards _outside of_ editorial workflow").

**Comment by tech4him1** [comment]
Oops, I'm sorry, I thought it was for both because you said in #485 that "This does not close #291 completely".

**Comment by Benaiah** [comment]
@tech4him1 my bad, that's a mistake in #485.

**Comment by aleksand88** [comment]
Has this ability added? I receive this message when trying to delete entry - https://prnt.sc/haq723
What this error could be?

**Comment by aleksand88** [comment]
Netlify CMS version 0.7.3
this is from console:
http://prntscr.com/haq909

**Comment by tech4him1** [comment]
@aleksand88 This issue has been closed as deletion was added. For help resolving your issue, please reach out on our Gitter channel: https://gitter.im/netlify/NetlifyCMS.
