### ISSUE TITLE
GitLab as External oAuth client

### ISSUE THREAD

**Issue by y-sumanth** [netlify/netlify-cms#2917]
I want to host the website in gitLab pages, other than netlify.

I could make oAuth with gitHub, using the project, [https://github.com/vencax/netlify-cms-github-oauth-provider](https://github.com/vencax/netlify-cms-github-oauth-provider)

Can you please provide guidance to make oAuth using gitLab?

**Comment by erezrokah** [comment]
That project seems to support GitLab, but you can also avoid setting up a server completely using an implicit grant: https://www.netlifycms.org/docs/authentication-backends/#client-side-implicit-grant-gitlab

**Comment by y-sumanth** [comment]
@erezrokah, I tried. It's saying 'Login: Failed to fetch', from netlify I guess

**Comment by erezrokah** [comment]
Do you mind sharing your site URL/repo/`config.yml` so I can look at the network traffic/CMS settings?
Which method did you try - the one from the project or the implicit auth?

Both method are not supposed to send any requests to Netlify for authentication.
If you want to use Netlify for auth you'll need to follow the instructions here https://www.netlifycms.org/docs/authentication-backends/#git-gateway-with-netlify-identity

**Comment by y-sumanth** [comment]
config.yml
```
backend:
  name: gitlab
  repo: Re*************gn/gatsby-netlify
  auth_type: implicit
  app_id: 826***************************29
```
Redirect URI given at gitLab application is like: 
`https://re*************gn.gitlab.io/gatsby-netlify/admin/`

**Comment by erezrokah** [comment]
Your configuration for implicit auth seems correct. Please make sure it is deployed to your hosting provider.
You can verify you're using the updated config in production by looking at the network traffic in developer tools:

![image](https://user-images.githubusercontent.com/26760571/69716236-54528880-1112-11ea-9ad3-697ec4f98e5a.png)

If you want to use GitLab as an OAuth2 provider you'll need a backend that implements the [Web Application flow](https://docs.gitlab.com/ee/api/oauth2.html#web-application-flow).
The project you mentioned [here](https://github.com/vencax/netlify-cms-github-oauth-provider) should do that. Have you deployed it somewhere?

**Comment by y-sumanth** [comment]
Yes, Its there on glitch. It basically the project I mentioned. But isn't it for github only? Can we can modify, as it works for gitLab also?
[https://netlify-cms-github-oauth-provider-example.glitch.me/](https://netlify-cms-github-oauth-provider-example.glitch.me/)
[https://netlify-cms-github-oauth-provider-example.glitch.me/callback](https://netlify-cms-github-oauth-provider-example.glitch.me/callback)

**Comment by erezrokah** [comment]
The project has instructions on how to make it work with GitLab by supplying some environment variables. Have you tried deploying a GitLab configuration?

**Comment by erezrokah** [comment]
Closing per further information and as this mostly not a CMS issue, but an issue of deploying the right backend service
