### ISSUE TITLE
error coming

### ISSUE THREAD

**Issue by aslamsk** [netlify/netlify-cms#2918]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by erezrokah** [comment]
Hey @aslamsk do you mind adding some more information about the error?

**Comment by erezrokah** [comment]
Please re-open when you have more information
