### ISSUE TITLE
I don't want to use the Image component in the markdown editor

### ISSUE THREAD

**Issue by laurenskling** [netlify/netlify-cms#2921]
The image editor component always gets loaded. 

https://github.com/netlify/netlify-cms/blob/ff4ffd7a70db6251b0cf210ac7830df054a61866/packages/netlify-cms-app/src/editor-components.js#L4

In a project, I don't want editors to be able to add images to the markdown.

Is there a way to disable the image selection in the markdown buttons?

**Comment by erezrokah** [comment]
Hey @laurenskling, you could always create your own version of `netlify-cms-app` and not register the image.

I can't think of an easier way to do it atm

**Comment by laurenskling** [comment]
Thanks @erezrokah , I didn't even realize `netlify-cms-app` was just a small initializer package. I will try to create my own version of a setup, thanks :)
