### ISSUE TITLE
I have next problem: somewhere image appears, but not for a long time. Usually image does not appear at all.

### ISSUE THREAD

**Issue by VasilHamulyak** [netlify/netlify-cms#2953]
I just want know if it problem related to my project configuration or it related to CMS. And how I can fix it?!

Open admin panel, going to some content item (project as example), open it and where image should be shown we just see empty space.

![project](https://user-images.githubusercontent.com/30534198/70320570-c1120500-182d-11ea-93db-80cabb61493e.png)

But sometimes image appears.

![picturemessage_3o3kygjz 5t1](https://user-images.githubusercontent.com/30534198/70320143-a55a2f00-182c-11ea-94a5-bbbf24aac08f.png)

 - Netlify CMS version: 2.9.7
 - Git provider: GitLab
 - OS: Linux Mint
 - Browser version Chrome 72.0.3626.96
Built with Gatsby v. 2.13.54.
Deploy to Netlify.
Also I used gatsby-plugin-netlify-cms v. 4.1.6

**Comment by erezrokah** [comment]
Related https://github.com/netlify/netlify-cms/issues/1750
