### ISSUE TITLE
Docs+Blog: fix external media library usage in blog and update docs

### ISSUE THREAD

**Issue by erezrokah** [netlify/netlify-cms#2954]
Prior issue: https://github.com/netlify/netlify-cms/issues/2950.

When using `netlify-cms-app` it is not clear that one needs to explicitly register the media library.
The information is available here:
https://www.netlifycms.org/blog/2019/07/netlify-cms-gatsby-plugin-4-0-0#using-media-libraries-with-netlify-cms-app

But the code example is wrong.
It should be:

```js
import uploadcare from 'netlify-cms-media-library-uploadcare';

CMS.registerMediaLibrary(uploadcare);
```

And not:

```js
import uploadcare from 'netlify-cms-media-library-uploadcare'

CMS.registerMediaLibrary('uploadcare', uploadcare)
```
See here: https://github.com/netlify/netlify-cms/blob/237a5b1aa65098f9c5b3768a306633a01fa25534/packages/netlify-cms/src/media-libraries.js#L5

We should add a note to it in the documentation as well.

**Comment by tiuweehan** [comment]
Hi, I would like to work on this issue if it is available

**Comment by erezrokah** [comment]
Thanks @tiuweehan, we would love a PR for it.
