### ISSUE TITLE
Failed to publish: API_ERROR: Reference does not exist

### ISSUE THREAD

**Issue by wayferer** [netlify/netlify-cms#2957]
**Describe the bug**
Over the last week or so we've been getting reports from our contributors seeing the toast: `Failed to publish: API_ERROR: Reference does not exist` appear when the publish entries through NetlifyCMS. The entry is still published and there's no issues with the workflow but this is throwing them off and making them worry.

I did some digging through past issues and even the js that gets loaded and it seems like it might be an issue with getting the right status back from github? Not too sure.

Setup:
- Netlify
- Private Organization Github repo
- Netlify Identity Registration turned off
- Git Gateway enabled (no role defined)
- Used through JS
`<script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>`

**Screenshots**
![image](https://user-images.githubusercontent.com/1575559/70649214-4886bc00-1c12-11ea-980c-50ac5bf4f93f.png)

![image](https://user-images.githubusercontent.com/1575559/70648993-e332cb00-1c11-11ea-9fdd-84cdd44aa67f.png)

<img width="751" alt="image" src="https://user-images.githubusercontent.com/1575559/70649078-09586b00-1c12-11ea-8387-992b29da06fe.png">

**Applicable Versions:**
 - netlify-cms-app 2.9.7
 - netlify-cms-core 2.12.2
 - netlify-cms 2.9.7
 - Git provider: GitHub
 - OS: Netlify

**Comment by erezrokah** [comment]
Do you mind sharing your `config.yml` file? If possible also the relevant network traffic from Chrome dev tools when the error occur. 
I tried setting a similar configuration to yours and couldn't reproduce the issue.

**Comment by wayferer** [comment]
@erezrokah thanks for the reply and testing. what part of the `config.yml` file would be useful? It's rather large and I'll have to edit it a bit before sharing. This is what I see in devtools:

![image](https://user-images.githubusercontent.com/1575559/70725670-6e6b9980-1cc2-11ea-9b2a-01255bdeb97a.png)

**Comment by erezrokah** [comment]
Thanks @wayferer the network traffic explains a lot. The `config.yml` is not required as I think I understand the issue.

When someone publishes an entry the CMS will merge the PR, then delete the branch.
Trying to delete a non existent branch will throw an error. This might happen when two users try to publish the same entry at the same time.
In any case this should not be considered as an error.
We have some code to handle it when deleting an entry here:
https://github.com/netlify/netlify-cms/blob/10a735de2fefd37eced720e898b1ebbfa880499b/packages/netlify-cms-backend-github/src/API.js#L944
but not when publishing an entry here:
https://github.com/netlify/netlify-cms/blob/10a735de2fefd37eced720e898b1ebbfa880499b/packages/netlify-cms-backend-github/src/API.js#L958
I'll submit a fix very soon.

**Comment by erezrokah** [comment]
Fixed here: https://github.com/netlify/netlify-cms/commit/1e77d4b7688de795ab1b01c6ce2483a0383bbfb6

**Comment by wayferer** [comment]
@erezrokah thanks so much!
