### ISSUE TITLE
Bug(locales): CMS still has hard coded English strings

### ISSUE THREAD

**Issue by erezrokah** [netlify/netlify-cms#2959]
Related issue: https://github.com/netlify/netlify-cms/issues/2947

Screenshots from that issue:

![Screen Shot 2019-12-04 at 5 05 53 PM](https://user-images.githubusercontent.com/8804935/70133289-61461d80-16b8-11ea-949b-3d1fa0a515b1.png)
![Screen Shot 2019-12-04 at 5 06 01 PM](https://user-images.githubusercontent.com/8804935/70133291-61461d80-16b8-11ea-9d8b-36d42d2ed9d0.png)
![Screen Shot 2019-12-04 at 3 37 01 PM](https://user-images.githubusercontent.com/8804935/70133242-4a073000-16b8-11ea-9eff-0ef7b8864f7d.png)
![Screen Shot 2019-12-04 at 3 37 03 PM](https://user-images.githubusercontent.com/8804935/70133244-4a073000-16b8-11ea-8aff-f8cf380c232e.png)
![Screen Shot 2019-12-04 at 4 54 52 PM](https://user-images.githubusercontent.com/8804935/70133246-4a9fc680-16b8-11ea-9efb-134e2b04fd9d.png)

Please add more relevant screenshots if you identify more hard coded strings.

**Comment by tomrutgers** [comment]
![widget locales](https://user-images.githubusercontent.com/6247534/70704725-e641c000-1cd2-11ea-9ce3-678519a3add9.png)

**Comment by tiuweehan** [comment]
Hi, is this issue available for me to work on?

**Comment by erezrokah** [comment]
@tiuweehan, go for it. I think `Login with Netlify Identity` should be fixed by now, and the login modal might require fixing in https://github.com/netlify/netlify-identity-widget.

**Comment by pniedzwiedzinski** [comment]
As I mentioned in #3186 
![image](https://user-images.githubusercontent.com/19212948/73649909-22fdb800-4681-11ea-9601-55d2c4e67cf3.png)

**Comment by pniedzwiedzinski** [comment]
> As I mentioned in #3186
> ![image](https://user-images.githubusercontent.com/19212948/73649909-22fdb800-4681-11ea-9601-55d2c4e67cf3.png)

I already made this simple fix for that https://github.com/pniedzwiedzinski/netlify-cms/tree/optional-hardcoded, but I added only English and Polish translations. 

Should we add all translations at once? And should we merge all these small fixes in one PR?

**Comment by erezrokah** [comment]
@pniedzwiedzinski your fix is already an improvement so thank you :) As each translation we have was contributed by a different persons(s), I don't think we need to wait. The process so far has been that people would close the gap from the english version when they have the time - we just need to expose a way for them to do so.

**Comment by tiuweehan** [comment]
@pniedzwiedzinski I created a [new branch on my fork](https://github.com/tiuweehan/netlify-cms/tree/remove-hard-coded-strings). Maybe you could make a PR to my fork first, then I will make a PR to this repo after I am done with the rest of the issues?

**Comment by erezrokah** [comment]
Closing as I believe this is fixed
