### ISSUE TITLE
Open authoring UI option to resync a fork

### ISSUE THREAD

**Issue by alexearnshaw** [netlify/netlify-cms#2962]
**Is your feature request related to a problem? Please describe.**
We have been using this beta feature for a while to enable documentation contributors (of all skill levels) to easily propose changes to our documentation via pull request. We (technical writers) then review and merge the PRs. The open authoring functionality is great and meets our use case exactly. 

One problem that we've noticed though is in the following scenario:

- Say we have a contributor who made a change using CMS several weeks/months ago (their fork of our repo was created when they made this change)
- In the meantime our own changes and other PRs merged to our repo have changed things quite a lot
- Today this contributor decides to make a another change using the CMS. This works fine for them because the CMS reads from the master branch of our repo so it doesn't matter that their fork is out of date.
- But for us when we go to review their latest change before merging, we often see conflicts on the PR (which can often be time-consuming for us to resolve), and/or we see a diff that is not accurate (as it shows the diff of all the changes between their outdated fork and our master branch)
- As a result we've started recommending that our contributors either resync their forks or delete and recreate their forks before each new change (to avoid conflicts), and we ask them to add a comment to the PR on Github describing their change (so we can easily identify it in the diff). I don't think this is a reasonable ask for our CMS users as many of them are not technical and the very reason they are using a CMS is because they don't know/don't care about PRs and Git etc etc.

**Describe the solution you'd like**
I think 2 things would help a lot here:

- When opening the CMS check if the user has a fork of the repo already, and if they do how many commits behind the project repo it is. If their fork is behind by any number of commits ask them if they want to resync it with the project repo (if it's technically possible to resync) OR ask them if they want to delete their old fork and recreate it to bring it up to date). 
- Add some mechanism in the CMS UI to enable a user to add a brief description of the change they've made to the document when they send it for review in the CMS UI. This gets added to the Github PR as a comment.

**Describe alternatives you've considered**
As detailed above we've been asking users to delete and recreate their forks and add comments on Github but I think this is poor UX for a workflow that's aimed at non-technical users.

**Additional context**
n/a

**Comment by erquhart** [comment]
This is a bug, the CMS should be creating the new branch based on master from the upstream repo. Thanks for reporting!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
