### ISSUE TITLE
Implement a mechanism for branch switching

### ISSUE THREAD

**Issue by joshdcomp** [netlify/netlify-cms#2964]
**Is your feature request related to a problem? Please describe.**
 I’m building a documentation site for a component library and I’d like to be able to use the CMS to edit content for new components in their feature branch (during merge request time). We have a generator that builds the files necessary for new components, after which it is up to the engineer to document the component in the feature branch.

Branch switching is especially important when you consider a gitflow-based branching strategy (a component may be in develop for a while before hitting master, depending on release cadence) for an NPM package which uses ci-based versioning/releases with documentation deploying to gitlab pages: commits to master trigger a pipeline that determines and releases the next version and by the time a new component hits master, it would be expected that the docs are finished. In the case where NCMS is integrated into the project, the only content that NCMS is aware of would be from master branch. Commits to master would also build/deploy to gitlab pages, so we’d either need to do most of the content creation for new components outside of the editor, or release an undocumented component and fast-follow with the documentation

To underscore the gitlab pages issue, it's not feasible to simply spin up another instance because you get one pages instance per repository.

**Describe the solution you'd like**
Would like to have a dropdown menu option (similar to the combo box used to determine branches when creating a merge request) to pick a branch for NCMS to represent content from. Changes would be committed to the currently-selected branch.

**Describe alternatives you've considered**
If we changed our contribution model from git clone to git fork, contributors could deploy their work in progress build to gitlab pages—but the ergonomics aren’t great there: would either require the developer to change the CMS *and* pipeline config for every component or just work on one component at a time (not feasible for a component library in a growth phase where  development for any given component may wax and wane). And collaborating on the same component becomes much more difficult

**Comment by joelmukuthu** [comment]
Hi @erquhart, 

Was this fixed via #3014 (Feat: editorial workflow bitbucket gitlab)? Also related to that MR, is the feature actually released? The [docs](https://www.netlifycms.org/docs/configuration-options/#publish-mode) still mention that Editorial Workflows only work are only supported for GitHub.

Thanks, 
Joel.

**Comment by erezrokah** [comment]
Hi @joelmukuthu, we should update that part of the docs to point to the beta features:
https://www.netlifycms.org/docs/beta-features/#gitlab-and-bitbucket-editorial-workflow-support

#3014 resolves this issue, as  each content will be added via a specific feature branch (though branch switching can also refer to being able to choose a different default/target branch from the UI).

**Comment by joelmukuthu** [comment]
Thank you for the confirmation @erezrokah! Is there a repo where I can PR the change to the docs?

**Comment by erezrokah** [comment]
You could just fork this repo and PR (docs are under `website/content/docs` or use the "edit this page" link:
![image](https://user-images.githubusercontent.com/26760571/75165318-7f08a900-5722-11ea-9897-4f0b7d7616b3.png)
