### ISSUE TITLE
Preview templates are not rendering

### ISSUE THREAD

**Issue by nelsonreitz** [netlify/netlify-cms#2978]
**Describe the bug**
Preview templates are not registered/rendering in the content manager. No error is the console or in the manager suggests that the templates are not even registered.

This issue has been experienced by myself in the repo [eav-vaud/eav-vd.ch](https://github.com/eav-vaud/eav-vd.ch) and by @tonyjmartinez in the repo [tonyjmartinez/fromwaydowntown](https://github.com/tonyjmartinez/fromwaydowntown)

**To Reproduce**
Try to register a template using the same method as in the [Gatsby + Netlify CMS Starter](https://github.com/netlify-templates/gatsby-starter-netlify-cms).

**Expected behavior**
Preview template should render or at least show an error.

**Applicable Versions:**
 - Netlify CMS version: 2.9.7
 - Git provider: GitHub
 - OS: macOS Mojave 10.14.5
 - Browser version: chrome 79
 - Node.JS version: 12.13.1

**CMS configuration**
[config.yml](https://github.com/eav-vaud/eav-vd.ch/blob/master/static/admin/config.yml)

**Additional context**
This issue was discussed in the Netlify CMS Slack and @erquhart suggested we open an issue.

**Comment by erquhart** [comment]
I cloned your repo and ran it locally, the div with "Test" is output in the preview pane.

<img width="1913" alt="Screen Shot 2019-12-20 at 1 34 48 PM" src="https://user-images.githubusercontent.com/2112202/71283233-921b8900-232d-11ea-95d4-0197c64a94c4.png">

**Comment by nelsonreitz** [comment]
Thanks a lot for helping @erquhart! Since you got this behavior I tried to create a new site instance on netlify (with a new url) and got the preview template to render as expected.

However, on my original netlify site (old url), the preview template still doesn't render:
<img width="1440" alt="preview-template" src="https://user-images.githubusercontent.com/10158587/71306003-77075280-23db-11ea-95ae-92ac5e772939.png">

Could this be cache related then?

**Comment by tapjay** [comment]
Were you guys able to work out what the issue was? It's looking like I am running into the same issue..

**Comment by tomrutgers** [comment]
Maybe a serviceworker or aggressive caching causing some trouble?

**Comment by erezrokah** [comment]
Hi @tapjay, can you share your repo? If not a `config.yml`, any custom previews you're registering and a screenshot will help a lot.
Also, are you experiencing it locally or on the published site?

**Comment by tapjay** [comment]
@tomrutgers I tried doing that again - same result I'm afraid.

@erezrokah Unfortunately I can't share the repo as it is for a client but I am not creating any custom previews. It is just using the Gatsby Netlify template with a subset of what was originally inside the `config.yml`.

In fact, when I try to view the preview of the index page now, I get the following error in the preview panel:

<img width="698" alt="preview-error-netlify-cms" src="https://user-images.githubusercontent.com/2171281/74265597-bc207480-4cfa-11ea-90e7-26f5f2bd67bc.png">

**Comment by nelsonreitz** [comment]
Found some new info for my initial issue. My preview templates were not updating because I couldn't login on my local netlifycms. Since I was using github auth, I was redirected to the live `xxx.netlify.com` instance (related to https://github.com/netlify/netlify-cms/issues/766 and https://github.com/netlify/netlify-identity-widget/issues/86).

I got my preview templates to behave correctly by using email authentification and the `localhost:8000/admin` netlifycms instance.

**Comment by erezrokah** [comment]
> @tomrutgers I tried doing that again - same result I'm afraid.
> 
> @erezrokah Unfortunately I can't share the repo as it is for a client but I am not creating any custom previews. It is just using the Gatsby Netlify template with a subset of what was originally inside the `config.yml`.
> 
> In fact, when I try to view the preview of the index page now, I get the following error in the preview panel:
> 
> <img alt="preview-error-netlify-cms" width="698" src="https://user-images.githubusercontent.com/2171281/74265597-bc207480-4cfa-11ea-90e7-26f5f2bd67bc.png">

Is this the template you're using https://github.com/netlify-templates/gatsby-starter-netlify-cms?

I can see the index page with the latest version of the starter:
![image](https://user-images.githubusercontent.com/26760571/74428359-834edf80-4e61-11ea-9bfe-84b759f7d8ec.png)

**Comment by tomrutgers** [comment]
The preview template probably doesn't match the data defined in `config.yml` anymore.. If you make changes to the data, you have to update your preview template accordingly @tapjay

**Comment by erezrokah** [comment]
Closing as the initial issue seems to be resolved. Please open a new issue with relevant information if still happening
