### ISSUE TITLE
Ability to turn off content in subfolders

### ISSUE THREAD

**Issue by carlmjohnson** [netlify/netlify-cms#2983]
**Is your feature request related to a problem? Please describe.**

Netlify-CMS 2.10 added the ability to see content in subfolders. Unfortunately, there is no way to turn this feature off and it has made my CMS too busy with files to use.

**Describe the solution you'd like**

A configuration to the depth of subfolder search.

**Describe alternatives you've considered**

Moving my root files into some other folder and making crazy hacks to keep their URLs the same?

**Comment by erezrokah** [comment]
We're planning on adding better filtering capabilities. 
You could try using https://www.netlifycms.org/docs/collection-types/#filtered-folder-collections as a workaround

**Comment by carlmjohnson** [comment]
Yes, unfortunately path is not a field understood by the collection filtering, so I'll just have to make up an arbitrary parameter to limit things to one field.

**Comment by erezrokah** [comment]
Marking this as a bug. We should only get items up to the depth of the collection path (and to depth of 1 if not path is configured).

**Comment by carlmjohnson** [comment]
Crosslink: https://github.com/spotlightpa/poor-richard/pull/61

**Comment by tyler71** [comment]
> A configuration to the depth of subfolder search.

I don't mean to be [that one](https://xkcd.com/1172/), but is it possible to specify depth?
I have a wiki located at `/docs`, where I'd like to have all pages listed, eg `/docs/extra/info/site1.md`

**Comment by erezrokah** [comment]
Hi @tyler71 can you share your `config.yml`, repo structure and which files you want to load?

doing something like:

```
folder: docs
path: extra/info/{{slug}}
```

Should infer the correct depth from the path.
This would actually be the same as doing:

```
folder: docs/extra/info
```

**Comment by tyler71** [comment]
I apologize, I meant I could have files anywhere in `/docs/`.

Here is my [config.yml](https://github.com/ledstrain/wiki.ledstrain.org/edit/master/static/contribute/config.yml)
```
collections: # A list of collections the CMS should be able to edit
  - name: "pages" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Pages" # Used in the UI, ie.: "New Post"
    folder: "content/docs" # The path to the folder where the documents are stored
    extension: "md"
    create: false # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "hidden"}
      - {label: "bookToc", name: "booktoc", widget: "hidden"}
      - {label: "Body", name: "body", widget: "markdown"}
```
I'd like all `*.md` files in [this dir](https://github.com/ledstrain/wiki.ledstrain.org/tree/master/content/docs) to be displayed, such as `content/docs/software/ios.md`. The following display, but no others:
```
content/docs/guides.md
content/docs/faq.md
```

**Comment by erezrokah** [comment]
Oh, I get it now. That's a bit more tricky than just exposing the depth as in your case you have `create: false`, but what do we do when someone has `create: true`?
New files will be saved under `content/docs`.

How about you open a new issue for it with this scenario?
