### ISSUE TITLE
Use variables for z-index

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#2989]
Our z-index rules are mostly set with raw values, and we're starting to see collisions between them - especially extensions like widgets. This issue requires all z-index rules across the repo to be driven by a set of variables to ensure against unexpected visibility issues for non-static positioned elements.

**Comment by Manish-Giri** [comment]
Hello, I'd like to work on this.

**Comment by erquhart** [comment]
@Manish-Giri could have sworn we talked about this, maybe in Slack? Anyway, yes, please do!

**Comment by Android0868** [comment]
https://github.com/Android0868/torch.github.io.git
