### ISSUE TITLE
Add content type to "new" button in list widget

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#300]
Because the "new" button is positioned after all list items, it's often unclear what "new" thing you'll create by clicking it:

<img width="683" alt="screen shot 2017-03-17 at 10 31 48 pm" src="https://cloud.githubusercontent.com/assets/2112202/24068293/a34b2d16-0b61-11e7-94d7-da229df29871.png">

We should append the content type to this button, eg. "new ticket".

**Requirements**
* Append the associated content type to the list widget "new" button

**Comment by DrianHillman** [comment]
I'd be happy to take a run at this— I'm new to this project, but this looks like a good starting point.

**Comment by erquhart** [comment]
@DrianHillman awesome! Happy to have you dig in - reach out on [Gitter](https://gitter.im/netlify/netlifycms) if you have any questions along the way :)

**Comment by DrianHillman** [comment]
Great! I already have commit in place that solves this, I'll have an official PR posted soon 😁
