### ISSUE TITLE
TypeError: (0 , o.useEffect) is not a function

### ISSUE THREAD

**Issue by thaind97git** [netlify/netlify-cms#3004]
**Describe the bug**
When I try to use `cms admin preview markdown code`, I received an error : 
`TypeError: (0 , o.useEffect) is not a function`

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/42630357/71469450-c72b4e00-27fb-11ea-91d6-d23308b391a0.png)

**Applicable Versions:**

 - Netlify CMS app version: ^2.10.1
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version: chrome 22
 - Node.JS version: v10.16.0

**CMS configuration**

**Additional context**
```
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog-posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          dateFormat: 'YYYY-MM-DD',
          timeFormat: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - { label: "Description", required: false, name: "description", widget: "string" }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
      - { 
          label: "Tags", 
          name: "tags", 
          widget: "select", 
          options: ['ReactJs', 'JavaScript', 'Redux', 'NodeJs'],
          multiple: true 
        }
```

**Comment by erezrokah** [comment]
Hi @thaind97git can you share your repo or at least the way you register previews (if you register them)?

**Comment by thaind97git** [comment]
Hi @erezrokah, here is my repo:
https://github.com/thaind97git/tech-blog
Thank for your supported !

**Comment by erezrokah** [comment]
Hi @thaind97git, I forked you repo and tried to run it locally. `yarn install` command gave me some weird errors so I deleted the `yarn.lock` file and did `yarn install` again.
After that I was able to load the preview successfully:

![image](https://user-images.githubusercontent.com/26760571/71483321-f8157e00-280f-11ea-8767-2eb206d681bf.png)

**Comment by thaind97git** [comment]
Thank you, I resolved this issue by remove `yarn.log` and `yarn install`.

**Comment by thaind97git** [comment]
Hi @erezrokah, Not very relevant but you can help me how to create a `code block editor` like this image:
![image](https://user-images.githubusercontent.com/42630357/71500721-cac0e280-2898-11ea-8ab8-646d92caec8d.png)

> This image I get from `https://cms-demo.netlify.com/`

Can you help me with a Document or any tutorial to do this?

**Comment by erezrokah** [comment]
You can use the dropdown:
![image](https://user-images.githubusercontent.com/26760571/71553440-5c0a9300-2a18-11ea-881e-c5fce5247500.png)

**Comment by erezrokah** [comment]
Closing this issue, please re-open if any further issues
