### ISSUE TITLE
Add entry type to search results

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#301]
The entry type should be added to entries on the search results page, since entries of all types are represented. The component created in #293 should work for this.

**Requirements**
* Add entry type to each card in the search results page
* Make use of the meta info component created in #293

**Comment by erquhart** [comment]
This will probably be best resolved under #179, when search results are converted to a list.

**Comment by delucis** [comment]
@erquhart As far as I can tell, this has been implemented and this issue can be closed.

**Comment by tech4him1** [comment]
Correct, this was closed by https://github.com/netlify/netlify-cms/pull/1068.
