### ISSUE TITLE
Error when convert a comma character to html inside Code Block

### ISSUE THREAD

**Issue by thaind97git** [netlify/netlify-cms#3020]
**Describe the bug**
Code Block cms admin convert `comma character` to `undefined`

**To Reproduce**
1. Go to cms admin
2. Click on new Code Block in the field Body ( `widget: 'markdown'` )
3. View at Preview fine but deploy to the website error with a comma character

**Expected behavior**
I want to successfully use a comma character inside Code Block when deploying it into the website.

**Screenshots**
Code Block:

![image](https://user-images.githubusercontent.com/42630357/71642530-58f4f880-2cdf-11ea-97bf-099d28c9236b.png)
View it in website:

![image](https://user-images.githubusercontent.com/42630357/71642522-382ca300-2cdf-11ea-92fd-d9f21a5e0b25.png)

**Applicable Versions:**
 - Netlify CMS version: [^2.10.1]
 - Git provider: [GitHub]
 - OS: [Windows 10]
 - Browser version [chrome 22]
 - Node.JS version: [v10.16.0]

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog-posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          dateFormat: 'YYYY-MM-DD',
          timeFormat: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - { label: "Description", required: false, name: "description", widget: "string" }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
      - { 
          label: "Tags", 
          name: "tags", 
          widget: "select", 
          options: ['ReactJs', 'JavaScript', 'Redux', 'NodeJs'],
          multiple: true 
        }
```
My repo: https://github.com/thaind97git/tech-blog

**Comment by erquhart** [comment]
The CMS is committing the right value, you'll need to raise an issue with Gatsby about the build output.

CMS committed raw value here: https://github.com/thaind97git/tech-blog/commit/0b59d86732d3466d5031de5950f48bf2417f59e2
