### ISSUE TITLE
Error deleting pre-existing post

### ISSUE THREAD

**Issue by AimeexJB** [netlify/netlify-cms#3037]
**Describe the bug**
I am encountering an error whenever I click into a pre-existing post on the template. I would like to delete the post as it is unrelated to the website I am making but it will not let me and comes up with "1:1: Incorrectly eaten value: please report this warning on https://git.io/vg5Ft" when it is clicked

**Screenshots**

![image](https://user-images.githubusercontent.com/32738835/71815805-8c85a900-3078-11ea-9215-cb42c0430b22.png)

![image](https://user-images.githubusercontent.com/32738835/71815833-a1fad300-3078-11ea-9217-a15616e327d8.png)

**Comment by erquhart** [comment]
Two questions:
1. Is it giving the error when you open the entry or when you click delete?
2. Can you share the repo?

**Comment by AimeexJB** [comment]
It happened when I clicked in to open the entry! 
https://github.com/AimeexJB/marie-hogan-singer   <--- this is the repo
I had to deleted the page manually from the repo becuase I never found fix for it!
