### ISSUE TITLE
Live preview doesn't display when editing on Safari/Mac

### ISSUE THREAD

**Issue by adrianshort** [netlify/netlify-cms#304]
On Safari 10.0.3/Mac.

![screen shot 2017-03-18 at 19 14 29](https://cloud.githubusercontent.com/assets/120577/24075245/6da5f64c-0c0f-11e7-8f06-550804ab1b50.png)

**Comment by erquhart** [comment]
The preview is displaying, the container just isn't full height.

<img src="https://cloud.githubusercontent.com/assets/2112202/24107937/8d1a6f68-0d62-11e7-8cfd-03e78eacb631.gif" width="600px">

Looks like a flex height issue, Safari doesn't respect a parent's flex height for percentage based children.

**Comment by erquhart** [comment]
Possibly related to https://github.com/tomkp/react-split-pane/issues/167

**Comment by erquhart** [comment]
Going to use a style override to address the immediate issue and backlog an issue for a proper improvement.
