### ISSUE TITLE
z-index of EditorControlBar causes select control options of widget above to appear underneath

### ISSUE THREAD

**Issue by ArthurClemens** [netlify/netlify-cms#3042]
**Describe the bug**

When a page has a select widget followed by a markdown widget, the markdown widget obscures the select options. 

This is caused by style `css-13xgqvl-EditorControlBar eqipg3b0` which has a CSS index of 200.

**Expected behavior**

Select options should always be shown on top.

**Screenshots**
<img width="600" alt="select-options-underneath" src="https://user-images.githubusercontent.com/350303/71902344-26755080-3162-11ea-83cf-0ec71c9ef0bd.png">

**Applicable Versions:**

* netlify-cms-app 2.10.1
* netlify-cms-core 2.13.1
* netlify-cms 2.10.2

**Comment by erquhart** [comment]
Fixed in #2990, released in 2.10.3.
