### ISSUE TITLE
Select widget at bottom of page has unreachable options

### ISSUE THREAD

**Issue by ArthurClemens** [netlify/netlify-cms#3044]
**Describe the bug**

A select widget at the bottom of a group cannot be used because its options are cut off by the browser window.

**Expected behavior**

There should be enough room to show the select options.

**Screenshots**

<img width="829" alt="select-options-bottom-page" src="https://user-images.githubusercontent.com/350303/71911464-064e8d00-3174-11ea-956f-bf2aa69b894a.png">

**Applicable Versions:**

* netlify-cms-app 2.10.1
* netlify-cms-core 2.13.1
* netlify-cms 2.10.2

**Comment by erquhart** [comment]
Fixed in #3026, released in 2.10.3.
