### ISSUE TITLE
Cannot create content

### ISSUE THREAD

**Issue by Delkathes** [netlify/netlify-cms#3048]
**Describe the bug**
I cannot create new content. The "New" buttons don't work. They open a blank page without any widgets (I'm still on the CMS and can navigate it). 
But the old content is reachable and is editable. When I open them, I get the right content and widgets. Everything works.

Some error on Network : 
Error : Request URL: https://cdnjs.cloudflare.com/ajax/libs/rollbar.js/2.4.2/rollbar.min.js
Referrer Policy: no-referrer-when-downgrade

**Expected behavior**
When creating New content, widgets should display instead of empty page.

**Applicable Versions:**

 - Netlify CMS version: ^2.0.0 (lastest)
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version: [chrome, firefox], latests 
 - Node.JS version: 10

**CMS configuration**
[pastebin link](https://pastebin.com/BYXtwcfN)

backend:
  name: git-gateway
  branch: master
  accept_roles:
    - Admin
    - Editor
    - Propriétaire

publish_mode: editorial_workflow
media_library:
  name: cloudinary
  config:
    cloud_name: my_cloudname
    api_key: my_key

site_url: https://simone-duez.fr
logo_url: https://simone-duez.fr/static/SD.ico
display_url: https://simone-duez.fr

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
collections:
  - name: portfolio
    label: Tableaux
    label_singular: "Tableau"
    description: >
      Gestion des tableaux
    folder: content/portfolio
    create: true
    summary: "{{day}}/{{month}}/{{year}}  |  {{style}} -- {{title}}"
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    sort: "date:desc"
    media_library:
      config:
        multiple: true
    fields:
      - { label: Vendu, name: sold, widget: boolean, default: false }
      - { label: "Date de publication/edition", name: "date", widget: "datetime", dateFormat: "DD-MM-YYYY", timeFormat: "HH:mm", required: false}
      - { label: Nom du tableau, name: title, widget: string, hint: "Ne doit pas être modifié une fois publié. Supprime complètement le tableau et republie le !" }
      - { label: Dimension du tableau, name: dimension, widget: string }
      - { label: Type de cadre, name: cadre, widget: string }
      - { label: Matières utilisées, name: material, widget: string }
      - label: "Style"
        name: "style"
        widget: "relation"
        collection: "params"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
      - { label: "Tableau", name: "image", widget: image }
      - { label: "Description du tableau", name: "description", widget: "text", hint: "Apparaît sous le nom du tableau", required: false }
      - { label: "Contenu", name: "body", widget: "markdown", hint: "Texte additionnel pour accompagner l'oeuvre", required: false }
  - name: "params"
    label: "Styles des tableaux"
    label_singular: "Style"
    description: >
      Gestion des styles des tableaux du portfolio
    folder: content/params
    create: true
    identifier_field: title
    slug: "{{slug}}"
    sort: "date:desc"
    media_library:
      config:
        multiple: true
    fields:
      - { label: Titre/Nom du style, name: title, widget: string }
      - { label: "Image", name: "image", widget: image }
      - { label: Description, name: description, widget: markdown, required: false, hint: "Description de la rubrique"}
      - { label: Contenu, name: body, widget: markdown, required: false }
  - name: "expos"
    label: Expositions
    label_singular: "Exposition"
    description: >
      Gestion des expositions
    folder: content/expositions
    create: true
    summary: "{{month}}/{{year}}  |  {{title}}"
    slug: "{{month}}-{{year}}_{{slug}}"
    sort: "date:desc"
    media_library:
      config:
        multiple: true
    fields:
      - { label: Nom de l'exposition, name: title, widget: string }
      - { label: Description de l'évènement, name: description, widget: markdown, required: false, hint: Optionnel }
      - { label: Affiche, name: image, widget: image, required: false }
      - { label: Date de début de l'évènement, name: date, widget: datetime, dateFormat: "DD-MM-YYYY", timeFormat: "HH:mm" }
      - { label: Date de début de l'évènement, name: dateEnd, widget: datetime, dateFormat: "DD-MM-YYYY", timeFormat: "HH:mm" }
      - { label: Horaires, name: times, widget: string, required: false }
      - label: "Coordonnées"
        name: "coordinates"
        widget: "object"
        fields:
          - { label: Ville, name: town, widget: string }
          - { label: Adresse, name: street, widget: string, required: false }
      - { label: Rédaction, name: body, widget: markdown, required: false }
      - label: Photos
        name: photos
        widget: list
        fields: 
          - { label: Photo, name: photo, widget: img, required: false }
          - { label: Description, name: description, widget: markdown, required: false }
  - name: comments
    label: Commentaires
    label_singular: "Commentaire"
    description: >
      Gestion des commentaires
    folder: content/commentaires
    create: true
    summary: "{{day}}/{{month}}/{{year}}  |  {{title}}"
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    sort: "date:desc"
    media_library:
      config:
        multiple: true
    fields:
      - { label: Nom de la personne, name: title, widget: string, hint: "Ne doit pas être modifié une fois publié. Supprime complètement et republie le." }
      - { label: Avatar, name: avatar, widget: image, default: '', required: false }
      - { label: Date du commentaire, name: date, widget: datetime, dateFormat: "DD-MM-YYYY", timeFormat: "HH:mm", required: false }
      - { label: Commentaire, name: comment, widget: markdown }
  - name: "pages"
    label: "Gestion du site"
    files:
      - label: "Accueil"
        name: "accueil"
        file: "content/pages/accueil.md"
        media_library:
          config:
            multiple: true
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Sous-titre", name: "subTitle", widget: "string" }
          - { label: "Image d'accueil", name: "image", widget: image }
          - { label: "Photo de profil", name: "profile", widget: image }
      - label: "Contact"
        name: "contact"
        file: "content/pages/contact.md"
        fields:
          - { label: "Titre de la page", name: "title", widget: "string" }
          - { label: "Sous-titre", name: "subTitle", widget: "string", required: false }
          - { label: "Text d'accueil", name: "landingText", widget: "markdown" }
      - label: "Portfolio"
        name: "portfolio"
        file: "content/pages/portfolio.md"
        fields:
          - { label: "Titre de la page", name: "title", widget: "string" }
          - { label: "Sous-titre", name: "subTitle", widget: "string", required: false }
          - { label: "Text d'accueil", name: "landingText", widget: "markdown" }
      - label: "Expositions"
        name: "expositions"
        file: "content/pages/expositions.md"
        media_library:
          config:
            multiple: true
        fields:
          - { label: "Titre de la page", name: "title", widget: "string" }
          - { label: "Sous-titre", name: "subTitle", widget: "string", required: false }
          - { label: "Text d'accueil", name: "landingText", widget: "markdown" }
      - label: "Livre d'or"
        name: "or"
        file: "content/pages/or.md"
        fields:
          - { label: "Titre de la page", name: "title", widget: "string" }
          - { label: "Sous-titre", name: "subTitle", widget: "string", required: false }
          - { label: "Text d'accueil", name: "landingText", widget: "markdown" }
      - label: "Simone Duez - Artiste peintre"
        name: "artiste"
        file: "content/pages/artiste.md"
        fields:
          - { label: "Titre de la page", name: "title", widget: "string" }
          - { label: "Sous-titre", name: "subTitle", widget: "string", required: false }
          - { label: "Text d'accueil", name: "landingText", widget: "markdown" }
          - { label: Contenu, name: body, widget: "markdown" }
  - name: blog
    label: Blog
    label_singular: "Publication"
    description: >
      Gestion du blog
    folder: content/blog
    create: true
    preview_path: "blog/{{slug}}"
    summary: "{{day}}/{{month}}/{{year}} à {{hour}}:{{minute}} | {{title}}"
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    sort: "date:desc"
    media_library:
      config:
        multiple: true
    fields:
      - { label: Titre, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, dateFormat: "DD-MM-YYYY", timeFormat: "HH:mm", default: "" }
      - { label: Image, name: "image", widget: image }
      - { label: Nom de l'image, name: "imageTitle", widget: string, required: false }
      - { label: Description de l'image, name: "imageDescription", widget: text, required: false }
      - { label: Description de la publication, name: description, widget: markdown, required: false }
      - { label: Contenu, name: body, widget: markdown }

Sorry for terrible formating of YML. Don't know how to paste it properly.

**Comment by Delkathes** [comment]
I fixed the CDN import to 2.10.2. Seems like switching back to version 2.10.2 fixed my issue, but that's not a satisfying fix..

**Comment by erezrokah** [comment]
You're correct it is not a fix. Can you share your repo/link to your deploy CMS? I tried going to https://simone-duez.fr/admin, but that didn't work.

**Comment by Delkathes** [comment]
CMS path: https://simone-duez.fr/static/admin

The repo is private due to cloudinary API key in config.yml.

[pastebin link again](https://pastebin.com/BYXtwcfN) if that's helpful.

Sorry for giving you half of what you need.

**Comment by erezrokah** [comment]
Fixed an released in `netlify-cms@2.10.4`
