### ISSUE TITLE
Format code with Prettier?

### ISSUE THREAD

**Issue by KyleAMathews** [netlify/netlify-cms#305]
Any interest in setting up a `format` npm script? I've been using it recently for my projects and ❤️ it.

React just recently switched over to it as have a number of other projects.

Helps standardize your code formatting far more than ESlint does. Also really fun with editor integration as you don't have to fiddle with spacing and other formatting concerns with your code. You just bang out something ugly, save, and it'll be prettified.

https://github.com/prettier/prettier

**Comment by erquhart** [comment]
Makes sense. Interested to see how things would come out on first run.

**Comment by erquhart** [comment]
Closing in favor of #363, prettier being included in the PR.
