### ISSUE TITLE
String templating for collection level media_folder/public_folder

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#3054]
Prerequisite: #3053 

**Is your feature request related to a problem? Please describe.**

Collection level **media_folder**/**public_folder**, specifically for folder type collections, may require variable replacements for per-entry images. For example, the hugo docs site has a hosting and deployment section, and each entry has its own [subdirectory of images](https://github.com/gohugoio/hugoDocs/tree/master/static/images/hosting-and-deployment). The paths in the content files are absolute.

**Describe the solution you'd like**

The ability to reference values like `{{title}}` and `{{slug}}` in collection level **media_folder**/**public_folder**.

**Comment by caseykey** [comment]
This would be great for a folder collection of json files. The relative media_folder would allow us to reference the json files using allFolderJson, then access the image by accessing JsonFolder/media_folder/{{slug}}/image.1png. 

Current solution is to have subdirectories for folder collections using the `path` with a slug, but this makes it difficult to query the entries in the collection with GraphQl. With the subdirectories, no longer can we access all entries with `allFolderJson`. With subdirectories via path + slug fields, entries have to be queried individually with `allEntryJson`, which is impossible as the entries are dynamic and therefor the query name is unknown.
