### ISSUE TITLE
When changing a post title, a duplicate page is published at a different URL

### ISSUE THREAD

**Issue by rbriski** [netlify/netlify-cms#3061]
I am using the "editorial workflow" with the Netlify CMS.  When I update the title on an already published post, the CMS updates the URL slug and publishes a duplicate post at the new URL.  Instead, it should update the title but leave the URL alone.  

**Describe the bug**
I am using the "editorial workflow" with the Netlify CMS.  When I update the title on an already published post, the CMS updates the URL slug and publishes a duplicate post at the new URL.  Instead, it should update the title but leave the URL alone.  

**To Reproduce**
Steps to reproduce the behavior. For example:
1. Make sure you're in editorial mode in the CMS
2. Make sure title is part of your URL slug creation in the config
3. Go to an already published post
4. Change the title and save
5. Work your way through the editorial workflow, eventually hitting "Publish"
6. Error : There will be a post at the old URL as well as the new one.

**Expected behavior**
The URL should not change for a published post.  

**Applicable Versions:**
 - Netlify CMS version: [e.g. 2.10.4]
 - Git provider: [GitHub]
 - Browser version: Chromium: 79.0.3945.79 (Official Build) (64-bit)

**CMS configuration**
backend:
  name: git-gateway
  repo: xxx
  branch: xxx

publish_mode: editorial_workflow
media_folder: "site/content/uploads" # Folder where user uploaded files should go
public_folder: "/uploads"
show_preview_links: true
site_url: "xxx"

# A list of collections the CMS should be able to edit
collections:
  # RANKING : Dynamic - Dynamic ranking pages
  - label: "RANKING : Dynamic"
    name: "ranking-dynamic"
    folder: "site/content/ranking"
    filter: { field: "type", value: "ranking-dynamic" }
    create: true
    preview_path: "/ranking/{{title}}"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Type",
          name: "type",
          widget: "hidden",
          default: "ranking-dynamic",
          required: false,
        }
      - {
          label: "Visible in Netlify CMS?",
          name: "visible",
          widget: "hidden",
          default: "true",
          required: false,
        }
      - { label: "Title", name: "title", widget: "string", required: false }
      - {
          label: "Subtitle",
          name: "subtitle",
          widget: "string",
          required: false,
        }
      - { label: "Publish Date", name: "date", widget: "datetime", required: false }
      - label: "Featured Image"
        name: "thumbnail"
        widget: object
        fields:
          - { label: "Image", name: "image", widget: "image", required: false }
          - { label: "Alt Text", name: "alt", widget: "string", default: "", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Query", name: "query", widget: "query-widget", required: false }
      - { label: "Categories", name: "categories", widget: "list", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - label: "Author"
        name: "author"
        widget: object
        fields:
          - { label: "Name", name: "name", widget: "string", required: false }
          - { label: "About", name: "about", widget: "text", required: false }
          - { label: "Avatar", name: "avatar", widget: "image", required: false }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "description", widget: "text", required: false }
      - { label: "Social", name: "social", widget: "text", required: false }

  # RANKING : Static - Manually built ranking pages
  - label: "RANKING : Static"
    name: "ranking-static"
    folder: "site/content/ranking"
    # filter: { field: "visible", value: "true" }
    filter: { field: "type", value: "ranking-static" }
    create: true
    preview_path: "/ranking/{{title}}"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Visible in Netlify CMS?",
          name: "visible",
          widget: "hidden",
          default: "true",
          required: false,
        }
      - { label: "Type", name: "type", widget: "hidden", default: "ranking-static", required: false }
      - { label: "Title", name: "title", widget: "string", required: false }
      - {
          label: "Subtitle",
          name: "subtitle",
          widget: "string",
          required: false,
        }
      - { label: "Publish Date", name: "date", widget: "datetime", required: false }
      - label: "Featured Image"
        name: "thumbnail"
        widget: object
        fields:
          - { label: "Image", name: "image", widget: "image", required: false }
          - { label: "Alt Text", name: "alt", widget: "string", default: "", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - label: "Page Items"
        name: "page_items"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "", required: false }
          - label: "Image"
            name: "image"
            widget: object
            fields:
              - { label: "Image", name: "src", widget: "image", required: false }
              - { label: "Alt Text", name: "alt", widget: "string", default: "", required: false }
          - label: "Feature List"
            name: "feature_list"
            widget: "list"
            fields:
              - { label: "Attribute", name: "attribute", widget: "string", required: false }
              - { label: "Value", name: "value", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Categories", name: "categories", widget: "list", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - label: "Author"
        name: "author"
        widget: object
        fields:
          - { label: "Name", name: "name", widget: "string", required: false }
          - { label: "About", name: "about", widget: "text", required: false }
          - { label: "Avatar", name: "avatar", widget: "image", required: false }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "description", widget: "text", required: false }
      - { label: "Social", name: "social", widget: "text", required: false }

  # LANDING : Current FB - Updated FB landing page
  - label: "LANDING : Current FB"
    name: "landing_page2"
    folder: "site/content/landings2"
    filter: { field: "visible", value: "true" }
    create: true
    preview_path: "/{{title}}"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {
          label: "Visible in Netlify CMS?",
          name: "visible",
          widget: "hidden",
          default: "true",
          required: false,
        }
      - { label: "Type", name: "type", widget: "hidden", default: "landing2", required: false }
      - {
        label: "Title",
        name: "title",
        widget: "string",
        default: "xxx",
        required: false,
      }
      - {
        label: "Content",
        name: "content",
        widget: "markdown",
        default: "",
        required: false,
      }
      - { label: "Thumbnail", name: "featured", widget: "image", required: false }
      - {
        label: "Highlighted text",
        name: "highlighted",
        widget: "markdown",
        default: "",
        required: false,
      }
      - {
        label: "Above button text",
        name: "above_button",
        widget: "markdown",
        default: "",
        required: false,
      }
      - {
        label: "Button label",
        name: "button_label",
        widget: "string",
        default: "xxx",
        required: false,
      }
      - {
        label: "Button link",
        name: "button_link",
        widget: "string",
        default: "xxx",
        required: false,
      }
      - {
        label: "Button 2 label",
        name: "button_2_label",
        widget: "markdown",
        default: "Use Website >",
        required: false,
      }
      - {
        label: "Button 2 link",
        name: "button_2_link",
        widget: "string",
        default: "xxx",
        required: false,
      }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "description", widget: "text", required: false }
      - { label: "Social", name: "social", widget: "text", required: false }

  # LANDING : Original FB - Original FB landing page in unbounce
  - label: "LANDING : Original FB"
    name: "landing_content"
    folder: "site/content/landings"
    filter: { field: "visible", value: "true" }
    create: true
    preview_path: "/{{title}}"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Visible in Netlify CMS?",
          name: "visible",
          widget: "hidden",
          default: "true",
          required: false,
        }
      - { label: "Type", name: "type", widget: "hidden", default: "landing", required: false }
      - {
          label: "Title",
          name: "title",
          widget: "string",
          default: "xxx",
          required: false,
        }
      - label: "Intro"
        name: "intro"
        widget: "object"
        fields:
          - {
              label: "Background Image",
              name: "background_image",
              widget: "image",
              required: false,
            }
          - {
              label: "Logo Image",
              name: "logo",
              widget: "image",
              required: false,
            }
          - {
              label: "Slogan",
              name: "slogan",
              widget: "string",
              default: "xxx",
              required: false,
            }
          - {
              label: "Content",
              name: "content",
              widget: "markdown",
              default: "xxx",
              required: false,
            }
          - {
              label: "Button label",
              name: "button_label",
              widget: "string",
              default: "Get Started Now",
              required: false,
            }
          - {
              label: "Button link",
              name: "button_link",
              widget: "string",
              default: "#",
              required: false,
            }
          - {
              label: "Button 2 label",
              name: "button_2_label",
              widget: "string",
              default: "Use Website >",
              required: false,
            }
          - {
              label: "Button 2 link",
              name: "button_2_link",
              widget: "string",
              default: "xxx",
              required: false,
            }
      - label: "Content Section"
        name: "content"
        widget: object
        fields:
          - {
              label: "Top text",
              name: "top_text",
              widget: "text",
              default: "xxx",
              required: false,
            }
          - {
              label: "Teasers Title",
              name: "teasers_title",
              widget: "string",
              default: "How It Works",
              required: false,
            }
          - label: "Teasers"
            name: "teasers"
            widget: "list"
            fields:
              - {
                  label: "Teasers Title",
                  name: "title",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Content",
                  name: "content",
                  widget: "markdown",
                  required: false,
                }
          - {
              label: "Bottom Block Title",
              name: "bottom_block_title",
              widget: "string",
              default: "How It Works",
              required: false,
            }
          - {
              label: "Bottom Block Text",
              name: "bottom_block_text",
              widget: "markdown",
              default: "xxx",
              required: false,
            }
      - label: "Bottom Section"
        name: "bottom_section"
        widget: object
        fields:
          - {
              label: "Background",
              name: "background",
              widget: "image",
              required: false,
            }
          - {
              label: "Content",
              name: "content",
              widget: "markdown",
              required: false,
            }
          - {
              label: "Button label",
              name: "button_label",
              widget: "string",
              default: "Get Started Now",
              required: false,
            }
          - {
              label: "Button link",
              name: "button_link",
              widget: "string",
              default: "#",
              required: false,
            }
          - {
              label: "Button 2 label",
              name: "button_2_label",
              widget: "string",
              default: "Use Website >",
              required: false,
            }
          - {
              label: "Button 2 link",
              name: "button_2_link",
              widget: "string",
              default: "xxx",
              required: false,
            }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "description", widget: "text", required: false }
      - { label: "Social", name: "social", widget: "text", required: false }

  # INFO - These are text heavy pages like the privacy policy and TOS
  - label: "PAGE : Info"
    name: "default"
    folder: "site/content/pages/"
    filter: { field: "visible", value: "true" }
    create: true
    preview_path: "/{{title}}"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Visible in Netlify CMS?",
          name: "visible",
          widget: "hidden",
          default: "true",
          required: false,
        }
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "description", widget: "text", required: false }
      - { label: "Social", name: "social", widget: "text", required: false }

  # PAGE : Centered Content - centered pages with h1 and h2 titles
  - label: "PAGE: Centered"
    name: "centered_content"
    folder: "site/content/centered"
    filter: { field: "visible", value: "true" }
    create: true
    preview_path: "/{{title}}"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Type", name: "type", widget: "hidden", default: "centered", required: false }
      - {
          label: "Visible in Netlify CMS?",
          name: "visible",
          widget: "hidden",
          default: "true",
          required: false
        }
      - { label: "Title", name: "title", widget: "string", required: false }
      - {
          label: "Subtitle",
          name: "subtitle",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "description", widget: "text", required: false }
      - { label: "Social", name: "social", widget: "text", required: false }

  # BLOG : Post - regular blog post
  - label: "BLOG : Posts"
    name: "posts"
    folder: "site/content/posts"
    create: true
    preview_path: "/posts/{{title}}"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string", required: false }
      - {
          label: "Subtitle",
          name: "subtitle",
          widget: "string",
          required: false,
        }
      - { label: "Publish Date", name: "date", widget: "datetime", required: false }
      - label: "Featured Image"
        name: "thumbnail"
        widget: object
        fields:
          - { label: "Image", name: "image", widget: "image", required: false }
          - { label: "Alt Text", name: "alt", widget: "string", default: "", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Categories", name: "categories", widget: "list", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - label: "Author"
        name: "author"
        widget: object
        fields:
          - { label: "Name", name: "name", widget: "string", required: false }
          - { label: "About", name: "about", widget: "text", required: false }
          - { label: "Avatar", name: "avatar", widget: "image", required: false }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "description", widget: "text", required: false }
      - { label: "Social", name: "social", widget: "text", required: false }

**Comment by erezrokah** [comment]
Hi @rbriski do you mind sharing your repo? I tried reproducing and wasn't able to.
See these PRs updating existing posts:
https://github.com/erezrokah/gatsby-starter-netlify-cms/pull/17/files
https://github.com/erezrokah/gatsby-starter-netlify-cms/pull/19/files

**Comment by rbriski** [comment]
I can't share the repo, it's not mine and it's private.  However, my commits look the same.  It's only changing the "Title" value.  The problem is that the URL for the page is updated and the old page still exists.

One thing I noticed is that `preview_path` is set to title.  So it might be that the preview path is the problem.  However, when I look at the XML sitemap, the URL for the page is the `preview_path` URL, not what is defined in the slug.  Does preview_path actually create a URL?

**Comment by erezrokah** [comment]
If I remember correctly `preview_path` only affects the preview links (the screenshot here https://www.netlifycms.org/docs/deploy-preview-links/#using-deploy-preview-links) and when editing entries (not published ones).
Can you share  screenshots of `actual` vs `expected` so I can be sure I'm understanding you correctly?

**Comment by rbriski** [comment]
I'm going to close this.  It was a mistake in how the hugo config was set up.

**Comment by tomrutgers** [comment]
Thanks for reporting back, glad it's resolved 👍
