### ISSUE TITLE
Live preview doesn't work on Firefox/Mac

### ISSUE THREAD

**Issue by bellamystudio** [netlify/netlify-cms#307]
**- Bug -**

The live preview flashes up and then disappears on Firefox. No errors in browser console.

![netlify-admin](https://cloud.githubusercontent.com/assets/457677/24079548/80526f00-0c82-11e7-9dca-cc6472722594.jpg)

**Comment by DirtyF** [comment]
Here is the console message I get in latest Firefox on MacOS:

```
 Checking for MetaData files  cms.js:41:30228
 2017-03-17-smashing-mag-va-dix-fois-plus-vite does not have metadata  cms.js:41:30551
```

**Comment by erquhart** [comment]
So it seems this is an iframe issue - removing the iframe from the equation works. A developer from Zendesk ran this whole React iframe rendering gauntlet back in 2014 and created [react-frame-component](https://github.com/ryanseddon/react-frame-component) to as a packaged solution. I think our next step is to give that a shot.
