### ISSUE TITLE
Failure to load more than 43 entries for a Jekyll post collection

### ISSUE THREAD

**Issue by kylekirkby** [netlify/netlify-cms#3078]
**Describe the bug**

Failure to display more than 43 entries for a collection. 

**To Reproduce**

Steps to reproduce the behaviour. For example:
1. Go to https://staging.linaro.org/admin/
2. Click on [Older Posts](https://staging.linaro.org/admin/#/collections/older_posts)
3. Compare list of entries with the list of posts in the repo here: https://github.com/Linaro/website/tree/develop/_posts/previous

**Expected behaviour**

All posts should be displayed so content editors can update older posts and fix broken links.

**Applicable Versions:**
NetlifyCMS 2.10.4
NetlifyCMS 2.10.2

**CMS configuration**
https://github.com/Linaro/website/blob/develop/admin/config.yml

**Additional context**
We require all posts to be listed in a collection for content editors to update and fix broken links in our older posts. I've tried with and without the graphql GH endpoint option toggled with the same result. I've seen these issues which says to me that at some point or another this has worked. Am I missing something or is this feature broken? Any help would be greatly appreciated!!

Kind regards,

Kyle

**Comment by erezrokah** [comment]
Hi @kylekirkby, some of those files have an `md` extension while others have `markdown`. The CMS shows the `md` files by default.
You can change the default by following https://www.netlifycms.org/docs/configuration-options/#extension-and-format

**Comment by kylekirkby** [comment]
@erezrokah - awesome spot! Let me test that now :)

**Comment by erezrokah** [comment]
@kylekirkby can we close this?

**Comment by kylekirkby** [comment]
Yes please close! - thanks for the help on this! Should have seen this myself!
