### ISSUE TITLE
configure deploy preview path when the file name doesn't match the page title

### ISSUE THREAD

**Issue by andreamussap** [netlify/netlify-cms#3084]
The deploy preview link on Netlify CMS opens the **home** page of the preview, and a user has to navigate to the topic they changed.  

I've read on [Netlify CMS docs](https://www.netlifycms.org/docs/deploy-preview-links/#configuring-preview-paths) that you can configure the preview paths to a specific page.  

The instructions assume that you use a [slug](https://www.netlifycms.org/docs/configuration-options/#slug), which uses a field value eg. {{title}} as the identifier of the collections. 

The way the slug works is by compiling the identifier, eg. "My New Post!" to "my-new-post". 

In [Axway open docs](https://github.com/Axway/axway-open-docs), though, we create specific names to the *.md files, and the names don't match the heading/title of the pages, eg. the title of a file called `apimgr_concepts.md` is '[API management concepts](https://axway-open-docs.netlify.com/docs/apimgr_concepts/)' 

Therefore, I didn't find a way to configure my collections to redirect to an specific topic, and I don't even know if this is possible in my case.

**Is your feature request related to a problem? Please describe.**
It's a bad user experience to send the user to the home page of the docs, and make them to navigate to the topic that they've updated so they can see the preview. It can be challenging, confusing, and frustrating for the user to find the topic. 

**Describe the solution you'd like**
I'd like to be able to redirect the deploy preview links to the specific topic/page that was changed by a user.

**Describe alternatives you've considered**
/

I'm looking forward to your help.
Thanks
Andrea

**Comment by erezrokah** [comment]
Hi @andreamussap, can you share your `config.yml`? Are you using a folder type collection or a files based collection?

**Comment by erquhart** [comment]
#3055 will introduce a {{filename}} variable, that’s likely the only way to address this.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andreamussap** [comment]
Thanks @erquhart I'm looking forward to this improvement :)

**Comment by zslabs** [comment]
@erquhart If we instead have an optional `slug` field that should influence the preview link, is there anyway to set a fallback by chance to  `title`?

**Comment by dancingmonkey** [comment]
Is this possible for files under collections i.e. pages ?

This one works

    - name: 'work'
        label: 'Works'
        label_singular: 'Work'
        folder: '_work'
        preview_path: '/work/{{slug}}'  // this works
    .....

But this one doesn't

    collections:
      - name: 'pages'
        label: 'Pages'
        files:
          - name: 'photography'
            label: 'Photography'
            preview_path: '/photography/'  // this doesn't work?   base_url/photography/
        .....
