### ISSUE TITLE
An error occurred while trying to 'edit' my drafted content via 'Workflow editorial' mode

### ISSUE THREAD

**Issue by kmariko-kanmu** [netlify/netlify-cms#3086]
![image](https://user-images.githubusercontent.com/47440880/72407690-be4aee00-37a3-11ea-999a-b613bc15090d.png)

 (this issue has been revised by reporter)

**Comment by erezrokah** [comment]
Hi @kmariko-kanmu, can you share some more information regarding this error? For example: `config.yml`, console log messages, network traffic when the error occurs and possibly a repo reproducing the issue.

**Comment by kmariko-kanmu** [comment]
Hi Erez-san,

Thank you for your support. Actually I am an editorial staff and not much capable of go deeper about the situation - my colleague pointed https://github.com/netlify/netlify-cms/commit/6f221ab3c18a0bb4ebff7269e16d21f89e119531 and told me that it seems there may be some error regarding Markdown treatment. 
Yesterday (JST, 20-30 hour ago) did not encountered the error.

Transition was almost the same as https://github.com/netlify/netlify-cms/issues/3037 . When I tried to open the area (immediately after I clicked that area in yellow).
![image](https://user-images.githubusercontent.com/47440880/72411446-38807000-37ae-11ea-96dc-b3b4fe5e1785.png)

Hope it will help.

Regards,
Kiyono MARIKO

**Comment by kmariko-kanmu** [comment]
^ @erezrokah -san

**Comment by erezrokah** [comment]
Hi @kmariko-kanmu, this issue https://github.com/netlify/netlify-cms/issues/3037 was opened before https://github.com/netlify/netlify-cms/commit/6f221ab3c18a0bb4ebff7269e16d21f89e119531 was released so I don't think they are related.

I'll try to reproduce that issue as they have a repo I can use.

**Comment by kmariko-kanmu** [comment]
@erezrokah -san, @erquhart -san

Confirmed, thank you!
