### ISSUE TITLE
Error when adding image

### ISSUE THREAD

**Issue by alexanderroidlhhs** [netlify/netlify-cms#3092]
Suddenly my netlify website is not working anymore.
Pages with images give the following error:

Error
There's been an error - please report it.

Details
1:1: Incorrectly eaten value: please report this warning on https://git.io/vg5Ft

Using:
netlify-cms@2.10.6
gridsome-plugin-netlify-cms@1.0.9

All the best,
Alex

**Comment by erezrokah** [comment]
Thanks for opening this. Closing as duplicate https://github.com/netlify/netlify-cms/issues/3088
