### ISSUE TITLE
Using git gateway on localhost still points to localhost for authentication

### ISSUE THREAD

**Issue by jtan25** [netlify/netlify-cms#3094]
**Describe the bug**
Using git gateway locally renders the login page. But after clicking submit it still trys to authenticate through localhost/.identity/ .. instead of netlify identity gateway.

I've tried setting the netlifySiteUrl in localstorage but this will append this url to localhost --> localhost/{netlifySiteUrl} ...

React throws an error for the page with the following:
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=t%3A%20Not%20Found&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**To Reproduce**

I have already set up netlify identity on the website and have deployed this project and it works via the deployed site. But I want to be able to use the cms locally and am running into issues pointing to my netlify identity.

**CMS configuration**
backend:
  name: git-gateway
public_folder: /netlify_assets
media_folder: public/netlify_assets
collections:
  - name: pages
    label: Pages
    files:
      - label: "Page"
        name: page
        file: src/data/page.json
        fields:
          - {name: title, widget: string}
          - {name: subtitle, widget: string}
          - {name: content, widget: string}
          - {name: warning, widget: string}
          - {name: successText, widget: string}

**Additional context**

**Comment by erezrokah** [comment]
The storage key should be `netlifySiteURL` (all uppercase URL) and absolute path (e.g. `https://site-id.netlify.com`.
Can you share your the value you're setting for the site URL?
