### ISSUE TITLE
Markdown body widget has inconsistent copy/paste behavior

### ISSUE THREAD

**Issue by bever1337** [netlify/netlify-cms#3096]
**Describe the bug**
The Netlify CMS appears to intercept keyboard commands. When trying to copy/paste content inside a markdown widget, Netlify sometimes encounters an error and pastes the wrong content instead of what is stored in the clipboard.

**To Reproduce**
1. I have only reproduced this on locally hosted production builds.
2. Go to add content to a folder collection with a markdown body widget
3. Netlify offers to restore previously unpublished content
4. Click cancel
5. Content appears in the markdown body anyways
6. Cut text from the body
7. Copy different text from the body
8. Attempt to paste clipboard from step 7 into body, instead the text that was cut in step 6 is pasted

**Expected behavior**
The user should never know that Netlify is intercepting keyboard commands. These features pose an accessibility risk.

**Screenshots**
[cms_ui_bug.mov.zip](https://github.com/netlify/netlify-cms/files/4066101/cms_ui_bug.mov.zip)

**Applicable Versions:**
 - netlify-cms-app 2.10.1
 - netlify-cms-core 2.13.1
 - Backend: Gitlab
 - OS: Catalina
 - Firefox 72.0.1 (64-bit)
 - Node.JS version: ^8.12.0 LTS

**Comment by erezrokah** [comment]
Hi @bever1337, do you mind trying with latest versions, there have been some related fixes https://github.com/netlify/netlify-cms/issues/3081

**Comment by bever1337** [comment]
@erezrokah Thanks for the heads up. Any specific version I should test against? I first experienced this about a week ago and was too busy to write a ticket, but that's awesome someone else reproduced and fixed this so quickly.

**Comment by erezrokah** [comment]
`netlify-cms@2.10.7` or `netlify-cms-app@2.11.4`.
Bonus: you get editorial workflow for GitLab

**Comment by bever1337** [comment]
I'm no longer able to reproduce any of the above behavior, but I'll let y'all know if I do find another way to reproduce. Thanks for the support!
