### ISSUE TITLE
Folder Collections break with trailing / whilst using GraphQL API

### ISSUE THREAD

**Issue by kylekirkby** [netlify/netlify-cms#3098]
**Describe the bug**
Trailing slashes seem to break the loading of an individual collection item.

We recently enabled the `use_graphql` backend option in our NetlifyCMS config but it seems this breaks when a folder collection's path contains a trailing slash. I toggled this option and items were again loading correctly. It's strange as the collection items are listed fine but as soon as an attempt is made to load and edit one of these NetlifyCMS reports a `File not found` error. 

It appears the issue is that the UI is creating links to the page with trailing slash included:

https://staging.linaro.org/admin/#/collections/authors/entries//author

Simply removing the extra slash fixes this issue:

https://staging.linaro.org/admin/#/collections/authors/entries/author

**To Reproduce**
Enabled the use_graphql option in the backend options of a NetlifyCMS config and create a folder collection that contains a trailing / in the path. 

**Expected behavior**
The collection items should be rendered as they do without the use_graphql option toggled. 

**Screenshots**

**Applicable Versions:**

- netlify-cms-app 2.11.1
- netlify-cms-core 2.14.1
- netlify-cms 2.10.4
 - Git provider: GitHub

**CMS configuration**
https://github.com/Linaro/website/blob/develop/admin/config.yml

**Comment by erezrokah** [comment]
Thank you for reporting this!

**Comment by kylekirkby** [comment]
> Thank you for reporting this!

No problem! Team effort!
