### ISSUE TITLE
Add Storybook

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#3102]
**Is your feature request related to a problem? Please describe.**

The Netlify CMS UI is difficult to reason about, test, and change due to lack of documentation.

**Describe the solution you'd like**

S t o r y b o o k

**Describe alternatives you've considered**

Other solutions like Docz, but Storybook is ridiculously stable and much better suited for handling both component documentation and testing.

**Additional context**

Supports #2557

**Comment by erquhart** [comment]
@erezrokah will complete this issue with the initial integration of Storybook to the repo so that stories can be added by the community.

**Comment by dreampulse** [comment]
I found the deployed storybook here: https://storybook.netlifycms.org/
