### ISSUE TITLE
default hugo +netlify install error message

### ISSUE THREAD

**Issue by mrmikszath** [netlify/netlify-cms#3119]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by erezrokah** [comment]
Hi @mrmikszath can you share more information on the error you're experiencing and how to reproduce it? For example, your `config.yml`, `package.json`, hugo setup and if possible your repo.

**Comment by mrmikszath** [comment]
Hi Erez, 

 

i just clicked the hugo site starter here:

https://www.netlifycms.org/docs/start-with-a-template/

 

followed the original docs (click+deploy), and there was an error message.

Finally I deleted the site, and tried middleman script, and it works better. 

 

Thanks for your quick reply!

Robbie

**Comment by erezrokah** [comment]
Tried deploying the hugo starter from the link and it worked. Please re-open if you have more information about the error.
