### ISSUE TITLE
Mobiledoc support

### ISSUE THREAD

**Issue by busstram** [netlify/netlify-cms#312]
**- Do you want to request a *feature* or report a *bug*?**
This is a feature request!

**- What is the current behavior?**
Old-school content

Mobiledoc seems quite groundbreaking. The folks over at Ghost are implementing it as well into their new editor. I think it'd fit in nicely with the platform-agnostic approach of Netlify-CMS.

Link: https://github.com/bustlelabs/mobiledoc-kit

**Comment by erquhart** [comment]
This is _very_ interesting. At the least it's worth keeping open for discussion and seeing how interested the community is in making this happen.

**Comment by maartenbusstra** [comment]
It is! I believe Mobiledoc has the potential to be the de facto data format for content. Being able to store everything in an abstract way opens up all kinds of possibilities.

**Comment by maartenbusstra** [comment]
Here is the new Ghost editor, by the way: https://github.com/TryGhost/Ghost-Admin/tree/master/lib/gh-koenig

**Comment by erquhart** [comment]
@maartenbusstra the CMS can currently handle JSON files and JSON frontmatter as well.

**Comment by erquhart** [comment]
Closing as stale due to lack of activity and/or interest. Please comment if you feel this should be reopened.
