### ISSUE TITLE
Gitlab backend does not respect a repository permission given to a user from its group memberships 

### ISSUE THREAD

**Issue by hugurp** [netlify/netlify-cms#3120]
*Following https://github.com/netlify/netlify-cms/issues/2069*

**Describe the bug**
With the backend `gitlab`, netlifycms refuses login to a user which has write access given through its membership of group, which has itself write permission.

**To Reproduce**
On Gitlab:
1. create a group (organization) `test-group`
2. create a subgroup, `test-group/test-subgroup`
3. to `test-subgroup` add a `user` (do not use the user ownder of the root group `test-group`) as a member, with write access, `developer` (which should be enough for netlifycms to write into a repository)
4. create a new project repository to the root group, `test-group/test-repository`
5. on the repository settings of `test-group/test-repository`, at `settings/members`, click `invite group`, and invite the group `test-group/test-subgroup` with `developer` access
6. be sure that your `user`, member (developer) of the `test-group/test-subgroup`, is not a member/owner of `test-group`; otherwise this user will already inherit write permissions to all projects nested under the root group `test-group`

On your machine:
1. clone netlifycms, and follow the contribution instructions at https://github.com/netlify/netlify-cms/blob/master/CONTRIBUTING.md to setup the project
2. at the path `netlify-cms/dev-test/ replace the files `config.yml` and `index.html` by the files with the same name, located at the path `netlify-cms/dev-test/backends/gitlab/
3. in the new file `netlify-cms/dev-test/config.yml`, replace the value of the key `backend.repo`, by `test-group/test-repository` (create at the step 4. of the previous "reproduce" section)
4. run the netlifycms server locally, the homepage should show a `login with Gitlab` button. Click it to log in with your user account, the one that has been added as a member of `test-group/test-subgroup`.
5. It should show the error `Your GitLab user account does not have access to this repo.`
6. Even with this netlifycms error, your user should have read/write access to `gitlab.com/test-group/test-repository`; this is Gitlab's web interface.

**Expected behavior**
Following Gitlab's security model, the permissions allowing this user to write to the `test-group/test-repository` are granted from its membership to `test-group/test-subgroup`. Since this subgroup has been added as a `member` (developer) in `test-group/test-repository`, it should give write access. 
With this setup, Gitlab's interface allows the user to see and write to the repository.

**Applicable Versions:**
 - Netlify CMS version: latest from master
 - Git provider: Gitlab
 - OS: linux
 - Browser version: firefox, chromium

**CMS configuration**
The one located here, https://github.com/netlify/netlify-cms/blob/master/dev-test/backends/gitlab/config.yml, with the `backend.repo` key from the test repo described in the reproduce steps above.

**Test notes**
The issue seems to be coming from here https://github.com/netlify/netlify-cms/blob/0755f90142525d94158c1d112a5549e21eef77c2/packages/netlify-cms-backend-gitlab/src/API.ts#L176-L186

In the request's response, there are no permissions under the key `permissions`, but authorized groups are listed under the key `shared_with_groups`. This issue also seems to reference this aspect of Gitlab's api https://gitlab.com/gitlab-org/gitlab-foss/issues/39154

From Gitlab's documentation, this point seems to be of interest https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project-including-inherited-members

A query to this endpoint returns an array of users, each of them having a key `access_level` (number). Maybe we can use this to check if the user trying to log in has the permission to write to the netlifycms backend repository

Notes:
- Hope this is clear! Not the easiest to reproduce with all this group/sub-group mess. 
- I think I am understanding Gitlab's security model with group and sub-group permissions correctly, but I am also maybe making an appreciation mistake.

Cheers!

**Comment by erezrokah** [comment]
Tried to reproduce and I'm getting a valid `permissions` object:
![image](https://user-images.githubusercontent.com/26760571/72805023-8f78c000-3c5a-11ea-9065-415ebab07a84.png)

![image](https://user-images.githubusercontent.com/26760571/72805041-999abe80-3c5a-11ea-965d-b88bbb58ec7a.png)

When I login with `erezrokah-test`:
![image](https://user-images.githubusercontent.com/26760571/72805072-acad8e80-3c5a-11ea-8395-30b5dba598eb.png)

![image](https://user-images.githubusercontent.com/26760571/72805097-c2bb4f00-3c5a-11ea-8890-c46c328bc9d2.png)

What am I missing from my setup?

**Comment by hugurp** [comment]
Thanks for trying to reproduce!

It seems on the screenshots that your two users are member of parent groups, and not only of the `test-subgroup`.

The user you are testing the login with, should not be added as a member of the project, but only as a member of the subgroup. The subgroup itself, is added as a member of the project, so your test user inherits permissions to write on the project from the subgroup.

**Comment by erezrokah** [comment]
Oh I think I got it to reproduce with your help:
![image](https://user-images.githubusercontent.com/26760571/72810063-893c1100-3c65-11ea-9a27-4b07f67aee9f.png)
![image](https://user-images.githubusercontent.com/26760571/72810106-978a2d00-3c65-11ea-82d1-8612c120a320.png)
![image](https://user-images.githubusercontent.com/26760571/72810144-a53fb280-3c65-11ea-98c2-23a7000a470e.png)

**Comment by erezrokah** [comment]
@hugurp Looking at `shared_with_group` is not enough as the branch can be protected:
![image](https://user-images.githubusercontent.com/26760571/72811992-66abf700-3c69-11ea-9469-867f9dbb0e59.png)

Trying to test [this](https://docs.gitlab.com/ee/api/protected_branches.html#get-a-single-protected-branch-or-wildcard-protected-branch) now.

**Comment by hugurp** [comment]
Wow! Thank you for all this, it has been extremely fast!
I am currently looking at the PR.
Will test it now locally to see if it works with my test groups and repo.

I don't think I am capable of giving an expert review on the PR though, as I do not know the project's code.

All in all, thank you!

**Comment by erezrokah** [comment]
Testing it locally is already a huge help, thanks :)
