### ISSUE TITLE
Bug from  /admin

### ISSUE THREAD

**Issue by Hasan-Shaker** [netlify/netlify-cms#3125]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by erezrokah** [comment]
Hi @Hasan-Shaker, can you share some information about this issue?

**Comment by erezrokah** [comment]
Closing due to lack of info
