### ISSUE TITLE
Integration with Netlify Community

### ISSUE THREAD

**Issue by futuregerald** [netlify/netlify-cms#3127]
We would like to add an integration so that when a user opens a PR in this repo and they have a netlify community, we automatically assign a Netlify OS Contributor badge to their user. 

This integration would not use any private information, it will only use public github API's. It also does not require any additional permissions, it will just read the github user from a webhook, and send that to a function that pulls all PUBLIC commit's by that user, correlating that with activity on this specific repo and if there's a match AND if they have a netlify community account, it will assign the badge. This will not create new profiles or save any PII information.

Please share your thoughts. Thanks!

cc @erquhart 

Note that this integration is live on gotrue and gotrue-js

**Comment by erquhart** [comment]
@futuregerald ah this adds a badge on the Netlify Community side, got it. I’ll reach out separately to get the URL.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
