### ISSUE TITLE
Subfolders under collection's folder causes "Loading Entries" indefinitely (Github backend)

### ISSUE THREAD

**Issue by DomtronVox** [netlify/netlify-cms#313]
Disclaimer: I'm very new to netlify-cms (started yesterday with about 6 hours of playing with it) and may be completely off on this, but it seems to consistently happen. 

**- Do you want to request a *feature* or report a *bug*?**
Bug most likely

**- What is the current behavior?**
With a github backend, having a sub-folder in the folder that is a collection folder target causes the collection's entries to never load.

I.e. I am adapting an existing static site setup to used the cms. I have the folder src/documents/posts. The files in my src/documents folder are my "main pages" and the sub-folders under that are related to each main page. I have one collection for posts that loads fine, but my "main pages" collection does not load. If I create a sub-directory under src/documents/posts then my posts collection no longer loads.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Use Github backend. Have a collection pointing to a folder. Have a sub-folder in that collection's folder.

**- What is the expected behavior?**
The collections should ignore folders and only deal with files.

**- Please mention your node.js, and operating system version.**
version v7.7.3, I'm using netlify for the testing.

**********************

As for fixing it I tried to track down the place in the code that should maybe change. https://github.com/netlify/netlify-cms/blob/master/src/backends/github/API.js#L155 the ListFiles could have a for loop that strips out folders from the JSON pulled from github since it is only supposed to list *files* according to it's name not folders also.

Example: https://api.github.com/repositories/85621207/contents/ shows that the json has a field called "type" which is "file" or "dir". The for loop would look for and remove anything not having the file type.

As i said at the start I am new to netlify-cms so this may not be the actual issue or the right way to fix it. I do know that when a collection has sub-folders it loads entries indefinitely and when I remove those subfolders it loads fine. I tweaked my configuration so my main pages were in their own folder and it fixed the issue, but is causing me some other problems since I have to move those files to the right place afterwards (for the quick fix I used [this](https://github.com/DomtronVox/StaticFarmSite/blob/master/build.js#L62) hacky function to move main pages where they need to be). 

Some extra information:
- I am using metalsmith to generate the site
- My testing repository is https://github.com/DomtronVox/StaticFarmSite/
- I have edited the repository since I had the bug to work around it. commit 07caa6f11dbbf9589917912b861011b7b220c30b is where I was having the issue. 

Thank you, btw I am really liking the project so far.

**Comment by erquhart** [comment]
Seems related to #218

**Comment by josephearl** [comment]
Fixed by #370
