### ISSUE TITLE
Duplicate WebHook created when enabling editorial mode for GitLab

### ISSUE THREAD

**Issue by dubble-G** [netlify/netlify-cms#3138]
**Describe the bug**

I use GitLab.  My theory is that when I made a commit with a config change to enable editorial mode, a duplicate webhook was created in GitLab, resulting in duplicate builds.

**To Reproduce**

Yesterday afternoon, I added editorial mode to my config for use with GitLab.  Was not 100% sure the feature was ready, but decided to give it a try.  It seemed to work, as I could now see the workflow in my admin.  

Woke up this morning and saw that my build minutes had been exceeded. Today is last day of the cycle and I was manually trying to manage my minutes and had plenty minutes left to get through today, or so I thought...

Upon researching why my build minutes went way over my prediction,  I observed that duplicate builds began happening, right after the commit I made of the updated config file with editorial mode enabled.  

I checked my gitlab webhooks and I now had two netlify (duplicate) webhooks, which I read on a thread should not be, and the solution is to delete one, which I did.  So hopefully that solves the duplicate build problem going forward...

Not sure if that is the intended behavior?

This is all based on my observation of my builds on the Netlify builds screen.  I see the commit with the config change, and the duplicate builds began happening with the very next build.

**Expected behavior**

I would not expect a duplicate webhook to be created in GitLab upon adding editorial mode to my config, thus resulting in duplicate builds.

**Applicable Versions:**

 - Netlify CMS version: 2.10.12
 - Git provider: GitLab
 - OS: Mac OS Mohave 10.14.6
 - Browser version: Chrome 79.0.3945.130

 - Node.JS version:  v10.15.3  

**CMS configuration**
backend:
  name: git-gateway
  branch: development # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"

collections:
  - name: "adventure" # Used in routes, e.g., /admin/collections/blog
    label: "Adventure" # Used in the UI
    folder: "src/markdown-pages/adventures" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{fields.slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Place Display Name", name: "displayName", widget: "string"}
      - {label: "Blog Type", name: "blogType", widget: "string", default: "adventure"}
      - {label: "Google Places ID", name: "placeId", widget: "string"}
      - {label: "Video ID", name: "videoId", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Alt Image Text", name: "alt", widget: "string"}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "list", default: ["all"]}
      - {label: "Nearby Camping and Lodging", "name": "camping", widget: "list", required: false}
  - name: "camping" # Used in routes, e.g., /admin/collections/blog
    label: "Camping" # Used in the UI
    folder: "src/markdown-pages/camping" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{fields.slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Place Display Name", name: "displayName", widget: "string"}
      - {label: "Blog Type", name: "blogType", widget: "string", default: "camping"}
      - {label: "Google Places ID", name: "placeId", widget: "string", required: false}
      - {label: "RIBD Facility ID", name: "facility_id", widget: "string", required: false}
      - {label: "Video ID", name: "videoId", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Alt Image Text", name: "alt", widget: "string"}
      - {label: "Summary", name: "summary", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "State", name: "state", widget: "string"}
      - {label: "Accessible", name: "accessible_sites", widget: "boolean", required: false}
      - {label: "Number of Campsites", name: "number_of_campsites", widget: "string", required: false}
      - {label: "Max Vehicle Length", name: "max_vehicle_length", widget: "string", required: false}
      - {label: "Rates", name: "rates", widget: "string", required: false}
      - {label: "Reservation Page", name: "reservation_page", widget: "string", required: false}
      - {label: "Amenities", name: "amenities", widget: "list", default: ["none"], required: false}
      - {label: "Overview", name: "overview", widget: "text", required: false}
      - {label: "Nearby Activities", name: "nearby", widget: "list", default: ["none"], required: false}
      - {label: "Categories", name: "categories", widget: "list", default: ["all"]}

**Additional context**

**Comment by erezrokah** [comment]
Hi @dubble-G and thank you for opening this. Did you make a commit directly using the GitLab interface? Locally and pushed it push to the branch?
I attempted to reproduce this issue by creating this repo https://gitlab.com/erezrokah/netlify-cms-reproductions/commits/netlify_cms/issue_3138, deploying to Netlify and pushing a commit to enable editorial workflow and only observed a single hook being created.
Regardless the CMS shouldn't create any hooks as it doesn't listen to events sent from GitLab.

A way to get some more information it to use this API request `https://gitlab.com/api/v4/projects/:project_id/hooks` (https://docs.gitlab.com/ee/api/projects.html#list-project-hooks) to get the creation date of the hooks and correlate with the commit.

**Comment by dubble-G** [comment]
@erezrokah Thanks for the quick response!  I made the config change locally, committed it directly to my local development branch, and then did a git push to my gitlab repo.  

I hit the api you gave me and the response only shows the original hook created on: Tue Nov 26 2019 11:37:51 GMT-0700

I'm assuming that even though I deleted the duplicate hook I found earlier today, it would still show a created data for it, right?  Any any rate, I only see the one in the response.

Thanks!

**Comment by erezrokah** [comment]
My guess is that if the API returns deleted hooks it should have some kind of field to specify, so probably they only return current ones.

**Comment by dubble-G** [comment]
Thanks again for your response.  I tell you what.  I'm wondering if there is something on my end that caused the duplicate hook.  I have a few ideas to try and repro on my end.  I'm going to try and play around with this and try a few things out and ensure that my workflow is correct.  I'll let you know either way.  I have some urgent api work I need to tend to (might eat up my entire day), but will circle back around on this afterwards.  Thanks!

**Comment by erezrokah** [comment]
Thanks for the update @dubble-G , closing this as it doesn't seem CMS related (though is Netlify related). Please re-open if needed when you have more info.
