### ISSUE TITLE
CMS Manual Initialization is not working

### ISSUE THREAD

**Issue by mushkin-v** [netlify/netlify-cms#3159]
**Describe the bug**
I have added manual init for my CMS and now it shows an error when I am trying to open mysite.com/admin/ on my Amazon S3 bucket(locally everything works fine).
Error msg:

> Error loading the CMS configuration
> Config Errors:
> config should have required property 'collections'
> config should have required property 'media_folder'
> config should have required property 'media_library'
> config should match some schema in anyOf
> Check your config.yml file.

Before manual init everything worked fine. I didn't add any changes to config.yml and it works great without manual init. I add changes only to my cms.js, now it looks like that:
```
import CMS from 'netlify-cms-app'
import AboutPagePreview from './preview-templates/AboutPagePreview'
import BlogPostPreview from './preview-templates/BlogPostPreview'
import IndexPagePreview from './preview-templates/IndexPagePreview'

// This global flag enables manual initialization.
window.CMS_MANUAL_INIT = true;

const CMS_BRANCH_DEFAULT = 'develop';
const GATSBY_ACTIVE_ENV_DEFAULT = 'development';
const { CMS_BRANCH } = process.env;
const activeEnv = process.env.GATSBY_ACTIVE_ENV || process.env.NODE_ENV || GATSBY_ACTIVE_ENV_DEFAULT;
const API_ID =  activeEnv===GATSBY_ACTIVE_ENV_DEFAULT ? 'secret-code1' : 'secret-code2';

const config = {
  backend: {
    name: 'bitbucket',
    repo: 'my-repo',
    auth_type: 'implicit',
    branch: CMS_BRANCH || CMS_BRANCH_DEFAULT,
    app_id: API_ID,
  },
  load_config_file: true,
};

CMS.init({ config });

CMS.registerPreviewTemplate('indexpage', IndexPagePreview);
CMS.registerPreviewTemplate('about', AboutPagePreview);
CMS.registerPreviewTemplate('blog', BlogPostPreview);

```
And I also added _manualInit: true_ to gatsby-config.js:
```
{
      resolve: 'gatsby-plugin-netlify-cms',
      options: {
        manualInit: true,
        modulePath: `${__dirname}/src/cms/cms.js`,
      },
    },

```
**Expected behavior**
CMS shows a login page.

**Screenshots**
https://monosnap.com/file/ekysMvPYXGu7CgMUTrcs7lvxAXiIfa

**Applicable Versions:**
 - Netlify CMS version: ^4.1.37
 - Git provider: BitBucket
 - OS: MacOS
 - Browser version: Chrome 79.0.3945.130 (Official Build) (64-bit)
 - Deployed to: Amazon S3 bucket

Thanks for the help! 
PS NetlifyCMS is awesome!

**Comment by erezrokah** [comment]
Hi @mushkin-v, thank you for reporting this. Can you share the developer tools network traffic (request/response) for the `config.yml`. It should be one of the first requests when you refresh the page.

**Comment by erquhart** [comment]
An error in the console indicates that /admin/config.yml does not respond with a yaml file, likely as 404.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mushkin-v** [comment]
@erezrokah @erquhart config.yml code 200, screenshot:
https://monosnap.com/file/QqHDbbIVmH3qeFKYfoTDmxUAZaM1kH
Let me know if you need anything more. Thanks.

**Comment by mushkin-v** [comment]
First I thought that the issue is because of this msg in the console:
 
> Response for config.yml was not yaml (Content-Type: binary/octet-stream).

This is because Amazon does this with yml files. But without manual init I have the same msg and CMS works fine :(
When I am visiting mysite.com/admin/config.yml browser starts to download config file, so seems it is on its place.

**Comment by erezrokah** [comment]
> @erezrokah @erquhart config.yml code 200, screenshot:
> https://monosnap.com/file/QqHDbbIVmH3qeFKYfoTDmxUAZaM1kH
> Let me know if you need anything more. Thanks.

Can you make sure the response for the `config.yml` file is identical to the one you have in your repo? 200 response code might also be when the site redirects to a custom error page.

If you could share at least part of the `config.yml` I could try to create a reproduction

**Comment by mushkin-v** [comment]
@erezrokah thanks for helping, I can download config.yml with url https://mysite.com/admin/config.yml and it looks fine(its the same, like in my repo). I deployed the project several times to S3 with different fixes and still have this error with manual init. When I turn off manual init, config.yml works fine for CMS, I can login edit fields and save them to repo. It was working fine for the last month, and now if I turn off manual init it works fine again. Also manual init works fine for me on localhost in develop mode but don't wont to work after deploying to Amazon S3.
This is my config.yml, I removed a few collections but the big picture is the same:
```
backend:
  name: bitbucket
  repo: myrepo
  branch: master
  auth_type: implicit
  app_id: secretcode
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: 'metaData'
    label: 'Metadata Info'
    editor:
      preview: false
    files:
      - file: 'src/pages/meta/index.md'
        label: 'Common Info'
        name: 'commonInfo'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'meta' }
          - {
            label: 'Site Metadata',
            name: siteMetadata,
            widget: object,
            fields:
              [
              { label: 'Site Title', name: siteTitle, widget: string },
              { label: 'Description', name: description, widget: text },
              ],
          }
          - {
            label: 'OpenGraph Tags',
            name: openGraphTags,
            widget: object,
            fields:
              [
              { label: 'og:url', name: ogurl, widget: string },
              { label: 'og:title', name: ogtitle, widget: string },
              { label: 'og:site_name', name: ogsitename, widget: string },
              { label: 'og:description', name: ogdescription, widget: text },
              { label: 'og:image', name: ogimage, widget: image },
              ],
          }
          - {
            label: 'Twitter Tags',
            name: twitterTags,
            widget: object,
            fields:
              [
              { label: 'twitter:title', name: twitterTitle, widget: string },
              { label: 'twitter:description', name: twitterDescription, widget: text },
              { label: 'twitter:image', name: twitterImage, widget: image },
              { label: 'twitter:image:alt', name: twitterImageAlt, widget: string },
              ],
          }
      - file: 'src/pages/meta/social.md'
        label: 'Social links'
        name: 'social'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'social' }
          - {
            label: Facebook,
            name: facebook,
            widget: object,
            fields: [{ label: Url, name: url, widget: string }, { label: Icon, name: icon, widget: image }],
          }
          - {
            label: Twitter,
            name: twitter,
            widget: object,
            fields: [{ label: Url, name: url, widget: string }, { label: Icon, name: icon, widget: image }],
          }
          - {
            label: YouTube,
            name: youtube,
            widget: object,
            fields: [{ label: Url, name: url, widget: string }, { label: Icon, name: icon, widget: image }],
          }
          - {
            label: Pinterest,
            name: pinterest,
            widget: object,
            fields: [{ label: Url, name: url, widget: string }, { label: Icon, name: icon, widget: image }],
          }

  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blog-post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Featured Post', name: 'featuredpost', widget: 'boolean' }
      - { label: 'Featured Image', name: 'featuredimage', widget: image }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

```

**Comment by mushkin-v** [comment]
@erezrokah @erquhart I have solved my issue. The problem was in a content-type which Amazon S3 sets by default for yml files(Content-Type: binary/octet-stream). I added to my CI/CD pipeline:

> aws s3 cp s3://mysite-master/ s3://mysite-master/ --exclude '*' --include '*.yml' --no-guess-mime-type --content-type=\"text/yaml\" --metadata-directive=\"REPLACE\" --recursive

And now CMS works fine. S3 returns config.yml with proper content-type text/yaml:
https://monosnap.com/file/ybOOvBGVjyBbe2kjITkk4ZB4waO4AN

I was confused in the beginning because without manual init everything was working fine even with this msg in console "Response for config.yml was not yaml (Content-Type: binary/octet-stream)." So I thought this is not important for CMS. It seems that the validation of config.yml for manual and auto init mode works differently. 
Guys, thanks again for your help! I think you can close this issue.

**Comment by erezrokah** [comment]
Oh, thank you for letting us know. I just realized I has to do something similar in the past with AWS S3: https://github.com/erezrokah/gatsby-netlify-cms-aws-test/blob/c3e9d4ed55ee9531b01c50bd201d70afcd0601c1/.circleci/config.yml#L64 but forgotten about it. Closing
