### ISSUE TITLE
'Unable to access identity settings' when trying to log in to Netlify CMS

### ISSUE THREAD

**Issue by Johnnybar** [netlify/netlify-cms#3164]
**Describe the bug**
Receiving an error 'Unable to access identity settings. When using git-gateway backend make sure to enable Identity service and Git Gateway', when adding Netlify CMS to a Github Pages website. 

**Detailed background and steps already tried**
Git Gateway is enabled in Netlify dashboard + added to backend name field in config, and required scripts have been added to index.html. I have also added 'Enforce HTTPS' to my  github pages' repo's settings and added CNAME with the specified input to my domain's DNS. 
When sending invite to users from 'Identity' the invite link sends me to the subdomain ([username].github.io) instead of the actual site, which (as it should) lets me know that **'There isn't a GitHub Pages site here.'**

**To Reproduce**
1. Github pages site created, with a bought www domain.
2. Created Netlify account.
3. Followed steps on https://www.netlifycms.org/docs/add-to-your-site/, adding scripts , modifying config.yml, enabling Identity and Git Gateway. Primary domain in Netlify dashboard: [username].github.io, domain alias: www.[mysite].com.
4. Added CNAME to www domain's DNS settings.
5. Ticked 'Enforce HTTPS' on Github pages settings

**Expected behavior**
Logging in and using the Netlify CMS.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/32452833/73349384-60ca9d00-428b-11ea-8e07-5112765a7282.PNG)

**Applicable Versions:**
netlify-cms-app 2.11.11
bootstrap.js:82 netlify-cms-core 2.15.4
index.js:27 netlify-cms 2.10.14

**CMS configuration**
config.yml
```
backend:
  name: git-gateway
  repo: [repo-name]/[username].github.io
  branch: master
  site_domain: [username].github.io

media_folder: "img"
publish_mode: editorial_workflow

collections:
...
```

site's index.html
```
<head>
...
 <script src="https://identity-js.netlify.com/v1/netlify-identity-widget.js"></script>
...
 </head>
...
 <body>
...
 <script>
    if (window.netlifyIdentity) {
      window.netlifyIdentity.on("init", user => {
        if (!user) {
          window.netlifyIdentity.on("login", () => {
            document.location.href = "/admin/";
          });
        }
      });
    }
  </script>
</body>
```

admin index.html:
```
...
<head>
  <title>Content Manager</title>
  <script src="https://identity-js.netlify.com/v1/netlify-identity-widget.js"></script>
</head>
<body>
  <!-- Include the script that builds the page and powers Netlify CMS -->
  <script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
</body>
...
```

**Additional context**

Please let me know if there's anything I'm missing here, I've looked at previous issues and other solutions did not solve my issue, so would appreciate any help.
Thanks!

**Comment by erezrokah** [comment]
Hi @Johnnybar, when you refresh the page you should see a request to retrieve the identity settings.
Something similar to:
![image](https://user-images.githubusercontent.com/26760571/73396340-04b94600-4296-11ea-8c13-0c36e31526de.png)
![image](https://user-images.githubusercontent.com/26760571/73396360-0daa1780-4296-11ea-88e6-0c3eff41bf0b.png)
Can you share that request/response?

**Comment by Johnnybar** [comment]
Hi @erezrokah, these are my request/responses
![1](https://user-images.githubusercontent.com/32452833/73441318-16145800-4353-11ea-8e2a-5a2e7d10da47.PNG)
![2](https://user-images.githubusercontent.com/32452833/73441491-5bd12080-4353-11ea-82f7-134b322d9b06.PNG)
![3](https://user-images.githubusercontent.com/32452833/73441496-5e337a80-4353-11ea-9da8-666a01db9765.PNG)
Thanks

**Comment by erezrokah** [comment]
@Johnnybar the identity widget should be loaded before the CMS. Not sure how you're seeing it load after as your `index.html` has it in the head tag, while the CMS is in the body tag.
Can you make sure the `index.html` that is returned from the server reflects the one in your issue. You can do that by looking at the page source.

**Comment by Johnnybar** [comment]
@erezrokah yes, based on the page source,  it's the same `index.html` as the one under my admin directory.
Just to add some more info, in case it could be related to my Netlify dashboard, here's my domain config there:
![6](https://user-images.githubusercontent.com/32452833/73531127-14fa2e00-441a-11ea-94ce-0f0a7ebc4cc8.png)

**Comment by erezrokah** [comment]
@Johnnybar, sorry for the late reply. Do you have the same issue when accessing the default domain? I'm getting 404 when try to access `https://laughing-pare-df22f2.netlify.com/admin`. Also you should probably resolve those DNS configuration issues.

I'm still missing the `identity/settings` request/response I attached earlier. They should appear right after you click `Login with Netlify Identity`. If you don't see them, please try after clearing browser cache.

**Comment by Johnnybar** [comment]
@erezrokah you should now be able to access `https://laughing-pare-df22f2.netlify.com/admin`, but i'm getting a cryptic error after trying to log in with Github. 
![loginerror](https://user-images.githubusercontent.com/32452833/73668810-b39abf00-46a6-11ea-8541-b26472cd40f2.png)

 I've set up a netlify DNS in the meanwhile, so not really sure if this is DNS-related.
Will it help to send you an invite from identity? I'm not sure I know what to look for here.
I've changed my config to 
```backend:
  name: git-gateway
  repo: hila-amit-website/johnnybar.github.io
  branch: master
  site_domain: https://laughing-pare-df22f2.netlify.com/
```
and modified the www CNAME entry in the site's domain to `https://laughing-pare-df22f2.netlify.com/`.

**Comment by Johnnybar** [comment]
@erezrokah Thanks for your help, I was finally able to log in, after fully configuring Netlify DNS and changing DNS settings on my domain. However, just wanted to check things are configured properly, since I'm getting the following error after logging in:
![error](https://user-images.githubusercontent.com/32452833/73670189-142afb80-46a9-11ea-850f-3187210244de.PNG)
Is this an issue on my side or netlify's?

**Comment by erezrokah** [comment]
Thanks for the update @Johnnybar, if you don't have any blog entries it should be find (usually happens when the CMS tries to access a non existing folder on GitHub).
I'm closing this issue - please re-open if necessary.

**Comment by Darksoulsong** [comment]
@erezrokah Is it mandatory to have my website deployed at Netlify to be able to use Identity?

**Comment by erezrokah** [comment]
@Darksoulsong you can self host identity:
https://github.com/hfte/netlify-cms-with-selfhosted-gotrue-and-git-gateway

You can also deploy on another hosting platform and just use Netlify for the identity service (and `git-gateway`).

You don't need a custom domain in order to use identity.

**Comment by ro-brook** [comment]
Am getting the same problem 

![Screen Shot 2022-03-03 at 1 37 49 PM](https://user-images.githubusercontent.com/100825678/156570919-60cb9b70-9d9b-49c6-8e7d-839eb00b115d.png)

I have added an admin folder with "index.html"  and  "config.yml"  in it 

1) This's the how the index.html looks like 


<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>PDC | Content Manager</title>
  <script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>
</head>
<body>
  
  <script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
</body>
</html>

2) And this's how the config.yml looks like 

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow


# These lines should *not* be indented
media_folder: "assets/upload" # Media files will be stored in the repo under static/images/uploads NEW_UPLOADS
public_folder: "assets/images" # The src attribute for uploaded media will begin with /images/uploads  FORMER_PHOTOS


#layout: blog
#title: "Let's Party"
#date: 1999-12-31 11:59:59 -0800
#thumbnail: "/images/prince.jpg"
#rating: 5


collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "assets/upload" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
     

My site is static website made with HTML,CSS & JS  , i wanna use Netlify's CMS 

ANY HELP !
