### ISSUE TITLE
Entries with .markdown extension don't work

### ISSUE THREAD

**Issue by techpeace** [netlify/netlify-cms#317]
**- Do you want to request a *feature* or report a *bug*?**

Report a bug.

**- What is the current behavior?**

If your entries end with the `.markdown` extension, rather than `.md`, links are generated improperly. This type of file naming scheme is the default for [middleman-blog](https://github.com/middleman/middleman-blog).

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a blog source entry with a name ending in `.markdown`
2. Attempt to access the entry from the Netlify CMS UI.

**- What is the expected behavior?**

It should load the entry.

**- What is the actual behavior?**

It throws an "Entry not found" error.

**- Please mention your node.js, and operating system version.**

node version: 6.9.5
OS: Mac OS X 10.12.3

Using Middleman

**Comment by techpeace** [comment]
The easy workaround here is to just change the filename extension on your entries to `.md`, instead. This is still supported by middleman-blog.

**Comment by erquhart** [comment]
Thanks @techpeace, this makes sense.

**Comment by erquhart** [comment]
If anyone is up for taking this on, it should be a simple fix.

**Comment by josephearl** [comment]
I took a look quick look at this. `selectEntryPath` assumes all files in the collection have the same extension. The list view can display them fine.

So one option that seems relatively easily is to include another path or query parameter in the route to optionally provide the extension. If provided, netlify-cms should use that as the file extension.

This would mean Netlify can support extensions with multiple extensions, but would only write out a single extension. It might be worth raising a separate to issue to add a chooser for file extension when creating a file for the first time.

**Comment by josephearl** [comment]
So another workaround currently is to add `extension: "markdown"` to your collection.

**Comment by erquhart** [comment]
The CMS should still support `.markdown` files by default.

**Comment by erquhart** [comment]
@Benaiah @tech4him1 is this still an issue?

**Comment by tech4him1** [comment]
I believe so, the issue still is that `selectEntryPath` assumes all files in the collection have the same extension, and it filters out every file that does not have the same extension. `md` is the default, or whichever one is set for `extension` in the config.

**Comment by Benaiah** [comment]
After an attempt at implementing default support for `.markdown` as well as `.md` via allowing multiple extensions, we've concluded that it's not feasible to do in a performant and unobtrusive manner. You can still use `.markdown` as the extension, but you must set it explicitly in the collection as noted above.

**Comment by bostonaholic** [comment]
Somewhat related, since upgrading to v4, I have noticed that my `title.md` files aren't being picked up, only `title.html.md` files are.

**Comment by tech4him1** [comment]
@bostonaholic Can you reach out on our [Gitter channel](https://gitter.im/netlify/NetlifyCMS)?

**Comment by wayferer** [comment]
For others that stumble here, i fixed it by adding `extension: "html.md"` and `format: frontmatter` to the netlify-cms `config.yml`.
