### ISSUE TITLE
React error 

### ISSUE THREAD

**Issue by mm0325kka** [netlify/netlify-cms#3178]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by erezrokah** [comment]
Hi @mm0325kka, can you share some more information on the error you're seeing?
