### ISSUE TITLE
"(optional)" field not translatable

### ISSUE THREAD

**Issue by pniedzwiedzinski** [netlify/netlify-cms#3186]
**Is your feature request related to a problem? Please describe.**
When a field is not required then `(optional)` string is appended to its label. It looks like it happens here:
https://github.com/netlify/netlify-cms/blob/92cad45120a327671e8ebe420c36f0d3278c1547/packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js#L232

**Describe the solution you'd like**
The solution would be to add a field to locales and then use it. I would like to work on it.

**Describe alternatives you've considered**
I think that this is the best solution 😛

**Additional context**
None

**Comment by erezrokah** [comment]
Hi @pniedzwiedzinski, we're tracking such bugs here https://github.com/netlify/netlify-cms/issues/2959.
Do you mind closing this and moving your comment to that issue?

**Comment by pniedzwiedzinski** [comment]
Ok then, this will be in #2959
