### ISSUE TITLE
!!

### ISSUE THREAD

**Issue by ab180-wontakkim** [netlify/netlify-cms#3194]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by erezrokah** [comment]
Hi @ab180-wontakkim can you share some more information on the issue you're experiencing?

**Comment by ab180-wontakkim** [comment]
@erezrokah Oh sorry 'Netlify' directly guided to here when it crashed. I even didn't realize that I created ticket. I couldn't check what was issue so you can ignore this ticket.
Thanks for your help though
