### ISSUE TITLE
Feature suggestion: Fix broad github permissions

### ISSUE THREAD

**Issue by joshka** [netlify/netlify-cms#320]
I understand and acknowledge that this is a known bug and is documented at https://www.netlify.com/docs/github-permissions/. I've presented it here as a feature suggestion due to the nature of the bug being the best available solution at the time it was implemented.

Github has enabled finer grain access permissions via integrations (currently in early access). Perhaps these would help solve some of the pain points of having to give netlify overly broad permissions.

https://developer.github.com/early-access/integrations/

**Comment by erquhart** [comment]
Thanks for the request @joshka - I agree, we definitely want to go here. GitHub's GraphQL API is also on our radar, and also in early access. We'll keep it open and see who's interested in making it happen!

**Comment by erquhart** [comment]
I don't think I realized initially that this is a Netlify issue and not a CMS issue. If anyone has thoughts we can re-open, but closing for now.
