### ISSUE TITLE
Uncaught TypeError when removing empty list item

### ISSUE THREAD

**Issue by matthensley1** [netlify/netlify-cms#3209]
**Describe the bug**
We have a simple list field on one of our collections which is used to build a photo gallery. The list item has a single field that is an image upload. When editing a post through the CMS, if the user adds multiple new list items to be populated, in some scenarios a javascript error prevents empty items from being removed (and if the image field is a required field within the list item, prevents the page from being saved at all).

**To Reproduce**
1. On a list field with an image subfield, add two empty new list items
2. Upload an image into one of the two fields (it doesn't matter which)
3. Try and remove the other field from the UI (nothing happens)
4. Console reports Uncaught TypeError: Expected iterable or array-like: null in immutable.js line 3620

Note: selecting an image for the empty field does then allow you to remove it. 

**Expected behavior**
Empty list items should be removed without problem. 

**Applicable Versions:**

 - Netlify CMS version: 2.10.17 (but have tried over other 2.10 minor releases, and even pinned previous versions (2.9, 2.8) to make sure it wasn't a new bug
 - Git provider: Github
 - OS: OSX
 - Site Backend: Jekyll
 - Browser version: Chrome 79, but have tested with others. 

**CMS configuration** (relevant portion)
`  - label: 'Gallery'
        label_singular: 'Gallery Image'
        name: 'gallery'
        widget: 'list'
        field: {label: Image, name: image, widget: image, required: false}
`

**Comment by adrian5** [comment]
Can confirm. Image members of lists cannot be removed if they are empty/left untouched.
