### ISSUE TITLE
<title> should be 'site description' + ‘sitename‘

### ISSUE THREAD

**Issue by indysigner** [netlify/netlify-cms#321]
**- What is the current behavior?**
The current `<title>` remains static regardless of the article or site we are on.

**- What is the expected behavior?**
The title should include the title of the article (or page) + a separator + the site name. This would be so much easier for working with bookmarks. The desired behavior of `<title>` would look like e.g. "The Road To Resilient Web Design – Smashing Magazine".

**Comment by erquhart** [comment]
@indysigner this isn't actually a CMS issue - can you re-open in the smashing repo?

**Comment by indysigner** [comment]
Sure, thanks!
