### ISSUE TITLE
Add default non-git file handling to proxy server

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#3211]
**Is your feature request related to a problem? Please describe.**

Local development support is primarily about supporting setup and experimentation during site development, local content authoring is a secondary use case. Our current local development support is ideal for the latter, but not the former.

For example, a developer should be able to:
- edit their local cms config
- make changes in the cms ui to test against the config

without experiencing:
- errors due to uncommitted changes (the config file changes)
- having to first commit their experimental config file changes
- having to revert or undo content commits made by the cms for ephemeral development testing

**Describe the solution you'd like**

- add an additional mode to the proxy backend that touches files direct, no cognizance of Git
- make this new mode the default, and allow git based file handling to be optionally enabled

**Additional context**

Partially based on [this Slack convo](https://netlifycms.slack.com/archives/CPRR0PQ9E/p1581020867215300) with @micahgodbolt

**Comment by micahgodbolt** [comment]
awesome! Can i try this in the current release?

**Comment by erezrokah** [comment]
We'll update here once we get it published with the version

**Comment by erquhart** [comment]
@micahgodbolt this is released in netlify-cms@2.10.18 / netlify-cms-app@2.11.15, let us know how it works for you.

**Comment by micahgodbolt** [comment]
I don't see 2.11.15 in the app yet https://www.npmjs.com/package/netlify-cms-app

**Comment by micahgodbolt** [comment]
Ok, i was able to install .15 - odd that it hasn't shown up yet. I'll take a peak!
