### ISSUE TITLE
Allow Custom Route for CMS Admin

### ISSUE THREAD

**Issue by jtwillis92** [netlify/netlify-cms#3238]
**Is your feature request related to a problem? Please describe.**

When adding netlify-cms to an existing project, or using it in concert with a different admin panel it may make sense to put the CMS on a different route than `/admin`. For example, that route may already be taken by an existing application that adds in netlify-cms after the fact. In the current implementation I do not see a way to specify the route dynamically, without producing a custom fork of the repo.

**Describe the solution you'd like**

Allow a configuration option in the YAML file to specify the route the CMS Admin will be served on.

**Describe alternatives you've considered**

**Additional context**

**Comment by erezrokah** [comment]
Hi @jtwillis92 can you share your site configuration (how you're integration the CMS into your site)?

The CMS is a self contained Web App and changing the route usually means just moving it to a directory with a different name than `admin`

**Comment by jtwillis92** [comment]
@erezrokah thanks for the quick response!

The site was originally pulled from the Gatsby netlify-cms starter and just has a folder under `/static` labelled `admin` with the config.yml file located inside.

**Comment by erezrokah** [comment]
You should be able to rename that directory and set the public path in the plugin options change the route:
https://www.gatsbyjs.org/packages/gatsby-plugin-netlify-cms/#publicpath

**Comment by jtwillis92** [comment]
Awesome! I didn't know about that config option - thanks so much.

**Comment by tizzle** [comment]
How would this work with a configuration that is 100% handled in the cms.js file?
