### ISSUE TITLE
Publishing using editorial workflow does not merge with correct branch when using Github backend

### ISSUE THREAD

**Issue by eamonnbell** [netlify/netlify-cms#324]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

Publishing using editorial workflow using the Github backend creates a PR with 'master' as the base branch, even though a different branch is specified in config.yml

**- If the current behavior is a bug, please provide the steps to reproduce.**

I am using netlify-cms to edit static page content generated and served by Github Pages (jekyll), meaning that source must be committed to the gh-pages branch of the hosted repo. So my [config.yml](http://www.eamonnbell.com/netlify-cms-test/admin/config.yml) begins as follows

~~~
backend:
    name: github
    repo: eamonnbell/netlify-cms-test
    branch: gh-pages

publish_mode: editorial_workflow

# etc
~~~

1. Sign into admin interface
2. Create post
3. Move from 'Draft' to 'Waiting to go live'
4. Publish
5. Programmatically generated PR changes from temporary branch to effect publication of draft post is merged with master branch of eamonnbell/netlify-cms-test

**- What is the expected behavior?**

Programmatically generated PR should merge changes from draft branch with the branch specified in config.yml

**- Please mention your node.js, and operating system version.**
Node: v.7.7.3
Linux x86_64  4.7.4-1-ARCH

**Comment by eamonnbell** [comment]
This is where the PR is created in the API call

https://github.com/netlify/netlify-cms/blob/master/src/backends/github/API.js#L389

**Comment by calavera** [comment]
Thanks for reporting this @eamonnbell. It looks like the called to that function is not taking the branch value from the configuration. This could be a great first contribution if you want to give it a try. I think the `persistFiles` call in GitHub's implementation should send that information:

https://github.com/netlify/netlify-cms/blob/master/src/backends/github/implementation.js#L81
https://github.com/netlify/netlify-cms/blob/master/src/backends/github/implementation.js#L16

**Comment by eamonnbell** [comment]
Sure, I'll give it a go.

**Comment by erquhart** [comment]
Hey @eamonnbell - did you gain any ground on this? We've got your back if you need help 😉

**Comment by josephearl** [comment]
The `branch` is set in the constructor to `API`, and available from `getBranch()` there.
