### ISSUE TITLE
Unable to set password on first time login to Netlify CMS

### ISSUE THREAD

**Issue by zzrez** [netlify/netlify-cms#3247]
**The problem**
I used the Deploy to Netlify button to configure Netlify with git-gateway and user by invitation, but cannot login after receiving the invitation email. Clicking the link in the email opens the home page, not the CMS page with the Login by Netlify Identity button. 

The repo was originally based on the Gatsby demo https://www.gatsbyjs.org/tutorial/blog-netlify-cms-tutorial/.

I tried to fix this with Snippet Injection as suggested in the Netlify docs, but did not work. It seemed overkill to put a snippet on every page when it was only needed on the home page; and the only login needed is for the CMS.

Just before doing all above with my repo, I did the simple starter tutorial described in https://www.gatsbyjs.org/docs/sourcing-from-netlify-cms/. This worked fine for accessing the CMS.  In both, all steps of https://www.netlifycms.org/docs/add-to-your-site/#authentication were followed.

**To reproduce**
Click on link "Accept the invite" from the email below:-
You have been invited to create a user on http://friendly-goodall-661b1b.netlify.com. Follow this link to accept the invite:
[Accept the invite](https://mandrillapp.com/track/click/31128206/friendly-goodall-661b1b.netlify.com?p=eyJzIjoiYl9FcEZDLWJJQ0JoUVhPYjdDYTM0eFJmOGtnIiwidiI6MSwicCI6IntcInVcIjozMTEyODIwNixcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvZnJpZW5kbHktZ29vZGFsbC02NjFiMWIubmV0bGlmeS5jb21cXFwvI2ludml0ZV90b2tlbj10N0pzM2I2NUFPWUZuSW1aYTZjUjVnXCIsXCJpZFwiOlwiM2YyZWQ3OTg3Njk2NDM3MTgxYjc0MDhjZjBmNmY2ODNcIixcInVybF9pZHNcIjpbXCIyMDIyMmZhODUzMmU2Yzk1NWNhZDIzMGYxYmVlMWQ0ZGVlOGMxZWI1XCJdfSJ9)
The public repo is [here](https://github.com/tristpc/seedrez11)

**Expected behavior**
Clicking the link should go to the /admin/ page where a popup form lets me set my password.

**Applicable Versions:**
gatsby-plugin-netlify-cms version: 4.1.26
Git provider: GitHub
OS: Windows
Browser Opera Version:66.0.3515.72
Node.JS version: 12.13.0

**Other context**
config.yml includes:- 
backend:
  name: git-gateway
  repo: tristpc/seedrez11

4 plugins are set:-
"gatsby-plugin-netlify-cms": "^4.0.0",
"gatsby-plugin-netlify-identity": "0.0.3"
"netlify-cms-app": "^2.9.1",
"react-netlify-identity-widget": "^0.2.5",

**Comment by erezrokah** [comment]
Hi @zzrez, are you using this plugin: https://github.com/tristpc/seedrez11/blob/82852216febaf1bf2dd3e13a73b661c05a3ea1fa/gatsby-config.js#L20

Looks like removing it solves it.

**Comment by zzrez** [comment]
Hi @erezrokah , great removing that plugin really did solve the problem. Thanks, much appreciated.
