### ISSUE TITLE
Error when accessing collection entry

### ISSUE THREAD

**Issue by gcutrini** [netlify/netlify-cms#3251]
**Describe the bug**
When accessing a collection entry, getting:
"Failed to load entry: t.has is not a function. (In 't.has("media_folder")', 't.has' is undefined)"

**Screenshots**
<img width="1253" alt="ee982877-1202-4905-b714-0e97243e4d09" src="https://user-images.githubusercontent.com/2131727/74444354-82af4c80-4e53-11ea-84e8-f6f49815a74b.png">

**Applicable Versions:**
 - Netlify CMS version: 2.10.^18

**CMS configuration**
https://github.com/AirshipWeb/airship-website/blob/510ad77c1452859935850d4326ea36e1b10cf78e/site/.vuepress/public/admin/config.yml

**Comment by erezrokah** [comment]
Hi @gcutrini, thank you for opening this. I was able to trace this to an invalid field configuration (with previous CMS versions you would have seen `undefined` as the field):
https://github.com/AirshipWeb/airship-website/pull/68

This should actually be handled by better validation of our schema

**Comment by gcutrini** [comment]
Thank you very much @erezrokah for catching our bug.
Hope it helped to raise awareness on schema validation.
I'll just go ahead and close.
Thanks again.
