### ISSUE TITLE
Images nested in lists removed by CMS

### ISSUE THREAD

**Issue by alexearnshaw** [netlify/netlify-cms#3253]
**Describe the bug**
When I edit a topic via CMS that contains images located within a numbered list, the CMS removes the image ref from the Markdown completely. )This is visible in the diff of the PR that is created on Github.

The CMS also makes various other changes, especially in nested lists, which can result in the resulting HTML page not being rendered correctly by Hugo, but maybe that's another issue?

**To Reproduce**

1. Go to any page containing images within numbered lists in our project, for example https://axway-open-docs.netlify.com/docs/contribution_guidelines/ and edit this page using CMS.
2. Make a small obvious change, Save and set status to In Review
3. Go the the PR in Github and see in the diff that all images inside lists are removed. Note other spurious formatting/indentation changes also.

**Expected behavior**
Images should be maintained.

**Screenshots**
See this [test PR](https://github.com/Axway/axway-open-docs/pull/400) where I added a one line change from CMS. This file contains images that are inside and outside lists. The images outside lists are maintained, while the image inside a numbered list is removed - see line 198 of the in the diff:
![image](https://user-images.githubusercontent.com/29064556/74454622-13018780-4e7c-11ea-9af8-7bfa7fd8f001.png)

**Applicable Versions:**

 - Netlify CMS version: 2.10.21
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version Chrome 79.0.3945.130

 - Node.JS version:

**CMS configuration**
https://github.com/Axway/axway-open-docs/blob/master/static/admin/config.js

**Additional context**
@erquhart I noticed this when running some tests after merging your wonderful contribution :) https://github.com/Axway/axway-open-docs/pull/203 but I don't think it's related to your PR nor to images specifically, it seems to be more of an issue around lists/nested lists/indentation?

**Comment by erquhart** [comment]
@alexearnshaw this is likely a markdown processing issue, thank you for raising! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
