### ISSUE TITLE
Bitbucket token dies and CMS fails

### ISSUE THREAD

**Issue by mushkin-v** [netlify/netlify-cms#3288]
**Describe the bug**
I am using a Bitbucket implicit auth. Bitbucket token dies in 1 hour and CMS doesn't handle this, it just shows an error and everything starts to hang. Not the best experience for a user, maybe you can catch 401 error and redirect a user to the login page? 
Maybe you know some other workarounds? Can I handle this situation by myself? 
Note that Bitbucket implicit auth doesn't have a refresh token option.
Thanks.

**To Reproduce**
Open CMS with bitbucket implicit auth, wait 1 hour until bitbucket token dies. 
Open any CMS page with content. 
You will see this error:
https://monosnap.com/file/KLWhskJ5pzEBwDfsAHO5ZqbFqr9ceJ
and in the console:
https://monosnap.com/file/Xq8Yggm998xn8W0RIszbGrGjkSBafR

**Expected behavior**
Catch error and redirect a user to the login page for better user experience.

**Applicable Versions:**
 - netlify-cms-app 2.11.16
 - netlify-cms-core 2.18.1
 - Git provider: BitBucket

**Comment by erezrokah** [comment]
closed in https://github.com/netlify/netlify-cms/pull/3494

**Comment by amarpathak** [comment]
@erezrokah  Is this issue fixed? What is the behaviour and in which version it is available?

**Comment by erezrokah** [comment]
This is better handled in https://github.com/netlify/netlify-cms/pull/3847

The CMS periodically checks if the user has been logged out and will display a proper error.

**Comment by amarpathak** [comment]
@erezrokah  Is this released? Or when can we expect the release?

**Comment by erezrokah** [comment]
Oh, forgot to update - this is released under `netlify-cms@2.10.51` or `netlify-cms-app@2.12.15`
