### ISSUE TITLE
Can't click login button after being logged out.

### ISSUE THREAD

**Issue by bobbymart1n** [netlify/netlify-cms#3295]
**Describe the bug**

After being logged out of the CMS, there seems to be a lot of `z-index` issues with the login flow. I can't click the `Login with Netlify Identity` button at all. 

**To Reproduce**
1. Log out of your admin, or clear your application cache so you are forced to login with Netlify Identity again. 
2. Navigate to your admin dashboard to get to the login flow.
3. Try clicking the Login with Netlify Identity button

**Expected behavior**

Clicking the Login with Netlify Identity button should prompt an email and password modal to pop up over the button

**Screenshots**

![Feb-20-2020 09-44-02](https://user-images.githubusercontent.com/5422085/74962891-9f083780-53c5-11ea-8e3e-24bf4766a38a.gif)

**Applicable Versions:**

 - Netlify CMS version: 2.11.11
 - Git provider: GitHub
 - OS: MacOS 10.14.6
 - Browser version Chrome 79

**CMS configuration**

```
CMS.init({
  config: {
    backend: {
      name: 'git-gateway',
      repo: 'https://github.com/mixmaxhq/mixmax-website',
      branch: process.env.NETLIFY_BRANCH || 'master',
      use_large_media_transforms_in_media_library: true,
    },
    load_config_file: false,
    display_url: 'https://mixmax.com',
    media_folder: 'static/assets',
    public_folder: '/assets',
    publish_mode: 'editorial_workflow',
    show_preview_links: true,
    collections: [
      primary,
      feature,
      integrations,
      useCases,
      blog,
      hub,
      legal,
      landingPages,
    ],
  },
});
```

**Additional context**

**Comment by erezrokah** [comment]
Hi @bobbymart1n, I'm getting all 404 except the main index.html when trying to access the CMS:
![image](https://user-images.githubusercontent.com/26760571/74964034-faace200-5412-11ea-8074-f14f38954254.png)

**Comment by bobbymart1n** [comment]
> Hi @bobbymart1n, I'm getting all 404 except the main index.html when trying to access the CMS:
> ![image](https://user-images.githubusercontent.com/26760571/74964034-faace200-5412-11ea-8074-f14f38954254.png)

This is actually a separate issue I've been having. If you use `/admin/` it should direct properly.

**Comment by bobbymart1n** [comment]
This is aside from the issue, but this isn't a valid CSS property
![Screenshot 2020-02-20 11 07 12](https://user-images.githubusercontent.com/5422085/74969321-358e2600-53d1-11ea-8c4f-7aedba3fcd59.png)
Its on the class `.visuallyHidden`

**Comment by bobbymart1n** [comment]
Is there any way to prompt the login flow via a URL? Other teams that I work with are blocked from entering the CMS currently

**Comment by tomrutgers** [comment]
It seems like the identity widget is initiated twice, I see two instances loaded in the DOM.

**Comment by tomrutgers** [comment]
> This is actually a separate issue I've been having. If you use /admin/ it should direct properly

You can read up on that discussion here: #332

**Comment by bobbymart1n** [comment]
Closing this issue. Adding `enableIdentityWidget: false,` to `gatsby-plugin-netlify-cms` options in `gatsby-config.js` solved the problem. I'm now running into another issue where adding that property breaks page previews in the CMS
