### ISSUE TITLE
Collection Name and "New" buttons should have different labels

### ISSUE THREAD

**Issue by byebyers** [netlify/netlify-cms#3297]
**Is your feature request related to a problem? Please describe.**
It is a discrepancy with naming conventions in the CMS UI. The reason being is for the client experience. This picture should show a Collection named "Blog" with a "New Post" button. This seems nitpicky but I can assure this can affects a user's trust in the developer's work. It seems that both the button and the collection name are pulled from "label" in the config file. 

![image](https://user-images.githubusercontent.com/22160915/74989323-4bb1db80-53fd-11ea-86b6-075bee5e80fc.png)

**Describe the solution you'd like**
The collection name should differ from the name of the button that creates new items. i.e. Blog -> "New Post". Possibly a Collection type called "new"

collections:
    - name: blog
       label: Blog
       new: Post

I hope this helps. So far I am having a blast using Netlify CMS with my GatsbyJS project. Look forward to publishing my first site!

**Comment by tomrutgers** [comment]
I believe you can use `label_singular` for that:

```
- name: blog
  label: Blog
  label_singular: Post
```

https://www.netlifycms.org/docs/configuration-options/#collections

**Comment by byebyers** [comment]
It worked! At first glance of "label_singular", I would not have thought it was for that button. Hopefully, this post will help others asking the same question. Thank you for your response!

**Comment by erezrokah** [comment]
Closing as this seems to be resolved. Thanks @tomrutgers and @byebyers!
