### ISSUE TITLE
Mock GH API to allow testing editorial workflow

### ISSUE THREAD

**Issue by Benaiah** [netlify/netlify-cms#330]
**- Do you want to request a *feature* or report a *bug*?**

New feature.

**- What is the current behavior?**

There is currently no mocking of the GitHub API. The editorial workflow thus has no automated testing.

**- What is the expected behavior?**

We should be able to make mock requests to the GitHub API to test the editorial workflow.

**Comment by erezrokah** [comment]
This is resolved using a recording proxy
