### ISSUE TITLE
load_config_file: false in newer version of gatsby-plugin-netlify-cms causes CMS login issues

### ISSUE THREAD

**Issue by bobbymart1n** [netlify/netlify-cms#3302]
**Describe the bug**

When `load_config_file: false` is set in my CMS configuration (See below) it causes the the `Login with Netlify Identity` button to be unclickable. If you comment that property in the config, the login button works without any issue.

**To Reproduce**

1. Manually init the CMS
2. Add `load_config_file: false` to the config
3. Start your environment
4. Try and login

**Expected behavior**

You should be able to click the login button regardless of that property being set.

**Screenshots**

Apologies for the fast Gif, the non-working version (with `load_config_file: false` uncommented), clicking that login button does nothing. Here it is working like normal with the property commented out.
![working](https://user-images.githubusercontent.com/5422085/75068609-5bd0c600-54a4-11ea-99fd-4d0c956fb4a9.gif)

**Applicable Versions:**

 - Netlify CMS version: 2.11.21
 - Git provider: GitHub
 - OS: MacOS
 - Browser version Chrome 79

 - Node.JS version:

**CMS configuration**

```
CMS.init({
  config: {
    backend: {
      name: 'git-gateway',
      repo: 'https://github.com/mixmaxhq/mixmax-website',
      branch: process.env.NETLIFY_BRANCH || 'master',
      use_large_media_transforms_in_media_library: true,
    },
    load_config_file: false,
    display_url: 'https://mixmax.com',
    media_folder: 'static/assets',
    public_folder: '/assets',
    publish_mode: 'editorial_workflow',
    show_preview_links: true,
    collections: [
      primary,
      feature,
      integrations,
      useCases,
      blog,
      hub,
      legal,
      landingPages,
    ],
  },
});
```

**Additional context**

I'm also on the latest version of `gatsby-plugin-netlify-cms ^4.1.40` a few versions earlier than this seems to work. Though through testing its somewhat inconsistent.

**Comment by erezrokah** [comment]
I believe this should be resolved in https://github.com/netlify/netlify-cms/pull/3660

Please comment if still an issue
