### ISSUE TITLE
Gatsby - NetlifyCMS build fails in remote, while builds in local

### ISSUE THREAD

**Issue by iamshaheenumar** [netlify/netlify-cms#3313]
**Describe the bug**
My project build using Gatsby + Netlify CMS Starter, doesn't build in netlify environment. While the build is successful in local Windows 10 environment.

From the error assuming it is something related building css and js bundles.
Since build is successful in local, guessing the issue could be with netlify.

**Terminal**
12:11:36 PM: Waiting for other deploys from your team to complete
12:15:26 PM: Build ready to start
12:15:28 PM: build-image version: 9cade8af58c2cf3a17a1e9433d2e979149488837
12:15:28 PM: build-image tag: v3.3.5
12:15:28 PM: buildbot version: 6fd888c8d66fd09bb18f09e1728e11fbc555b868
12:15:28 PM: Fetching cached dependencies
12:15:28 PM: Failed to fetch cache, continuing with build
12:15:28 PM: Starting to prepare the repo for build
12:15:29 PM: No cached dependencies found. Cloning fresh repo
12:15:29 PM: git clone git@gitlab.com:shaheen-timesworld/timesworld-website
12:15:32 PM: Preparing Git Reference refs/heads/master
12:15:33 PM: Found Netlify configuration file netlify.toml in site root
12:15:33 PM: Found Netlify configuration file(s). Overriding site configuration
12:15:33 PM: Different functions path detected, going to use the one specified in the Netlify configuration file: 'lambda' versus '' in the Netlify UI
12:15:33 PM: Creating functions prep folder
12:15:33 PM: Starting build script
12:15:33 PM: Installing dependencies
12:15:36 PM: Downloading and installing node v10.19.0...
12:15:36 PM: Downloading https://nodejs.org/dist/v10.19.0/node-v10.19.0-linux-x64.tar.xz...
12:15:37 PM: 
########################                                                  33.7%
12:15:37 PM: 
#################################################
12:15:37 PM: ####################### 100.0%
12:15:37 PM: Computing checksum with sha256sum
12:15:37 PM: Checksums matched!
12:15:39 PM: Now using node v10.19.0 (npm v6.13.4)
12:15:39 PM: Attempting ruby version 2.6.2, read from environment
12:15:41 PM: Using ruby version 2.6.2
12:15:41 PM: Using PHP version 5.6
12:15:41 PM: Started restoring cached node modules
12:15:41 PM: Finished restoring cached node modules
12:15:41 PM: Started restoring cached yarn cache
12:15:41 PM: Finished restoring cached yarn cache
12:15:41 PM: Installing yarn at version 1.9.4
12:15:41 PM: Installing Yarn!
12:15:41 PM: > Downloading tarball...
12:15:41 PM: [1/2]: https://yarnpkg.com/downloads
12:15:41 PM: /1.9.4/yarn-v1.9.4.tar.gz --> /tmp/yarn.tar.gz.gSL2H43cN
12:15:41 PM: v
12:15:41 PM:   % Total    % Received % Xfe
12:15:41 PM: rd  Average Speed   Time    Time     Tim
12:15:41 PM: e  Current
12:15:41 PM:               Dload  Upload   Tot
12:15:41 PM: al   Spent    Left  Speed
12:15:41 PM: 
  0     0    0     0    0
12:15:41 PM:  0      0      0 --:--:-- --:--:-- --:--:--     0
12:15:41 PM: 
  0    78    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
12:15:41 PM:     0
100    78  100    78    0     0    259      0 --:--:-- --:--:-- --:--:--   259
12:15:41 PM: 
100    91  100    91    0     0    146      0 --:--:-- --:--:-- --:--:--   146
12:15:42 PM: 
100   608  100   608    0     0    563      0  0:00:01  0:00:01 --:--:--   563
12:15:42 PM: 
  0     0    0     0    0     0      0
12:15:42 PM:  0 --:--:--  0:00:01 --:--:--     0
12:15:42 PM: 
100  915k  100  915k    0     0   618k      0  0:00:01  0:00:01 --:--:-- 4975k
12:15:42 PM: [2/2]: https://yarnpkg
12:15:42 PM: .com/downloads/1.9.4/yarn-v1.9.4.tar.gz.asc --> /tmp/yarn.tar.gz.gSL2H43cNv.asc
12:15:42 PM: 
100    82  100    82    0     0   2945      0 --:--:-- --:--:
12:15:42 PM: -- --:--:--  2945
12:15:42 PM: 
100    95  100    95    0     0   1715      0 --:--:-- --:--:-- --:--:--  1715
12:15:43 PM: 
100   612  100   612    0     0   2859      0 --:--:-- --:-
12:15:43 PM: -:-- --:--:--  2859
12:15:43 PM: 
100   832  100   832    0     0   3052      0
12:15:43 PM:  --:--:-- --:--:-- --:--:--  3052
12:15:43 PM: > Verifying integrity...
12:15:43 PM: gpg: Signature made Fri 03 Aug 2018 07:53:36 PM UTC using RSA key ID B6FF4DE3
12:15:43 PM: gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
12:15:43 PM: gpg: Note: This key has expired!
12:15:43 PM: Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
12:15:43 PM:      Subkey fingerprint: E219 30C4 D0A4 AA46 1858  1F7A E074 D16E B6FF 4DE3
12:15:43 PM: > GPG signature looks good
12:15:43 PM: > Extracting to ~/.yarn...
12:15:43 PM: > Adding to $PATH...
12:15:43 PM: > Successfully installed Yarn 1.9.4! Please open another terminal where the `yarn` command will now be available.
12:15:44 PM: Installing NPM modules using Yarn version 1.9.4
12:15:44 PM: yarn install v1.9.4
12:15:44 PM: [1/4] Resolving packages...
12:15:45 PM: [2/4] Fetching packages...
12:15:46 PM: (node:1376) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
12:16:12 PM: info fsevents@2.1.2: The platform "linux" is incompatible with this module.
12:16:12 PM: info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
12:16:12 PM: info fsevents@1.2.11: The platform "linux" is incompatible with this module.
12:16:12 PM: info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
12:16:12 PM: [3/4] Linking dependencies...
12:16:12 PM: warning "gatsby > react-hot-loader@4.12.18" has unmet peer dependency "@types/react@^15.0.0 || ^16.0.0".
12:16:12 PM: warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
12:16:12 PM: warning "gatsby > gatsby-cli > ink@2.6.0" has unmet peer dependency "@types/react@>=16.8.0".
12:16:12 PM: warning "gatsby > gatsby-cli > ink > auto-bind@3.0.0" has unmet peer dependency "@types/react@>=16.8.0".
12:16:12 PM: warning "gatsby > socket.io > engine.io > ws@7.2.1" has unmet peer dependency "bufferutil@^4.0.1".
12:16:12 PM: warning "gatsby > socket.io > engine.io > ws@7.2.1" has unmet peer dependency "utf-8-validate@^5.0.2".
12:16:12 PM: warning "gatsby-plugin-netlify > webpack-assets-manifest@3.1.1" has unmet peer dependency "webpack@>=4.4.0".
12:16:12 PM: warning "gatsby-plugin-sass > sass-loader@7.3.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
12:16:12 PM: warning " > lodash-webpack-plugin@0.11.5" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
12:16:12 PM: warning "netlify-cms-app > netlify-cms-widget-code@1.1.2" has unmet peer dependency "codemirror@^5.46.0".
12:16:12 PM: warning "netlify-cms-app > netlify-cms-widget-code > react-codemirror2@6.0.0" has unmet peer dependency "codemirror@5.x".
12:16:12 PM: warning "netlify-cms-app > netlify-cms-core > redux-notifications > react-redux@4.4.10" has incorrect peer dependency "redux@^2.0.0 || ^3.0.0".
12:16:12 PM: warning " > netlify-cms-media-library-cloudinary@1.3.4" has unmet peer dependency "netlify-cms-lib-util@^2.1.3-beta.0".
12:16:12 PM: warning " > slick-carousel@1.8.1" has unmet peer dependency "jquery@>=1.8.0".
12:16:12 PM: warning " > styled-components@5.0.0" has unmet peer dependency "react-is@>= 16.8.0".
12:16:24 PM: [4/4] Building fresh packages...
12:16:31 PM: Done in 46.28s.
12:16:31 PM: NPM modules installed using Yarn
12:16:31 PM: Started restoring cached go cache
12:16:31 PM: Finished restoring cached go cache
12:16:31 PM: unset GOOS;
12:16:31 PM: unset GOARCH;
12:16:31 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
12:16:31 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
12:16:31 PM: go version >&2;
12:16:31 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
12:16:31 PM: go version go1.12 linux/amd64
12:16:31 PM: Installing missing commands
12:16:31 PM: Verify run directory
12:16:31 PM: Executing user command: npm run build
12:16:31 PM: > timesworld-website@0.0.1 build /opt/build/repo
12:16:31 PM: > npm run clean && gatsby build
12:16:32 PM: > timesworld-website@0.0.1 clean /opt/build/repo
12:16:32 PM: > gatsby clean
12:16:32 PM: info Deleting .cache, public
12:16:32 PM: info Successfully deleted directories
12:16:35 PM: success open and validate gatsby-configs - 0.036s
12:16:36 PM: success load plugins - 1.046s
12:16:36 PM: success onPreInit - 0.008s
12:16:36 PM: success delete html and css files from previous builds - 0.013s
12:16:36 PM: success initialize cache - 0.009s
12:16:36 PM: success copy gatsby files - 0.036s
12:16:36 PM: success onPreBootstrap - 0.004s
12:16:36 PM: success createSchemaCustomization - 0.013s
12:16:36 PM: success source and transform nodes - 0.553s
12:16:37 PM: success building schema - 0.406s
12:16:37 PM: success createPages - 0.082s
12:16:37 PM: success createPagesStatefully - 0.106s
12:16:37 PM: success onPreExtractQueries - 0.000s
12:16:37 PM: success update schema - 0.028s
12:16:37 PM: success extract queries from components - 0.559s
12:16:37 PM: success write out requires - 0.004s
12:16:37 PM: success write out redirect data - 0.001s
12:16:37 PM: success onPostBootstrap - 0.000s
12:16:37 PM: ⠀
12:16:37 PM: info bootstrap finished - 5.128 s
12:16:37 PM: ⠀
12:16:39 PM: success Generating image thumbnails - 1.717s - 37/37 21.55/s
12:16:55 PM: failed Building production JavaScript and CSS bundles - 16.996s
12:16:55 PM: error Generating JavaScript bundles failed
12:16:55 PM: Cannot read property 'match' of undefined
12:16:55 PM: not finished run queries - 17.205s
12:16:55 PM: npm
12:16:55 PM:  ERR! code ELIFECYCLE
12:16:55 PM: npm
12:16:55 PM:  ERR!
12:16:55 PM: errno 1
12:16:55 PM: npm
12:16:55 PM: ERR! timesworld-website@0.0.1 build: `npm run clean && gatsby build`
12:16:55 PM: npm ERR!
12:16:55 PM:  Exit status 1
12:16:55 PM: npm
12:16:55 PM: ERR!
12:16:55 PM: npm
12:16:55 PM: ERR! Failed at the timesworld-website@0.0.1 build script.
12:16:55 PM: npm ERR!
12:16:55 PM:  This is probably not a problem with npm. There is likely additional logging output above.
12:16:55 PM: npm ERR!
12:16:55 PM:  A complete log of this run can be found in:
12:16:55 PM: npm ERR!     /opt/buildhome/.npm/_logs/2020-02-24T06_46_55_313Z-debug.log
12:16:55 PM: Function Dir: /opt/build/repo/lambda
12:16:55 PM: TempDir: /tmp/zisi-5e537020b301e20007c76af8
12:16:59 PM: Prepping functions with zip-it-and-ship-it 0.3.1
12:16:59 PM: [ { path: '/tmp/zisi-5e537020b301e20007c76af8/hello.zip',
12:16:59 PM:     runtime: 'js' } ]
12:16:59 PM: Prepping functions complete
12:16:59 PM: Caching artifacts
12:16:59 PM: Started saving node modules
12:16:59 PM: Finished saving node modules
12:16:59 PM: Started saving yarn cache
12:16:59 PM: Finished saving yarn cache
12:16:59 PM: Started saving pip cache
12:16:59 PM: Finished saving pip cache
12:16:59 PM: Started saving emacs cask dependencies
12:17:00 PM: Finished saving emacs cask dependencies
12:17:00 PM: Started saving maven dependencies
12:17:00 PM: Finished saving maven dependencies
12:17:00 PM: Started saving boot dependencies
12:17:00 PM: Finished saving boot dependencies
12:17:00 PM: Started saving go dependencies
12:17:00 PM: Finished saving go dependencies
12:17:02 PM: Error running command: Build script returned non-zero exit code: 1
12:17:02 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
12:17:02 PM: Failing build: Failed to build site
12:17:03 PM: Shutting down logging, 1 messages pending

**Package.json**

{
  "name": "timesworld-website",
  "description": "Timesworld Website with Netlify-CMS",
  "version": "0.0.1",
  "author": "Shaheen Umar & Sreedarsh CP",
  "dependencies": {
    "babel-plugin-styled-components": "^1.10.6",
    "bulma": "^0.8.0",
    "gatsby": "^2.13.31",
    "gatsby-image": "^2.0.23",
    "gatsby-plugin-netlify": "^2.0.6",
    "gatsby-plugin-netlify-cms": "^4.1.6",
    "gatsby-plugin-purgecss": "^4.0.0",
    "gatsby-plugin-react-helmet": "^3.0.4",
    "gatsby-plugin-sass": "^2.0.7",
    "gatsby-plugin-sharp": "^2.2.9",
    "gatsby-plugin-styled-components": "^3.1.17",
    "gatsby-remark-copy-linked-files": "^2.0.7",
    "gatsby-remark-images": "^3.1.6",
    "gatsby-remark-relative-images": "^0.2.1",
    "gatsby-source-filesystem": "^2.0.26",
    "gatsby-transformer-remark": "^2.6.9",
    "gatsby-transformer-sharp": "^2.1.9",
    "lodash": "^4.17.15",
    "lodash-webpack-plugin": "^0.11.4",
    "netlify-cms-app": "^2.9.6",
    "netlify-cms-media-library-cloudinary": "^1.3.2",
    "netlify-cms-media-library-uploadcare": "^0.5.2",
    "node-sass": "^4.11.0",
    "prop-types": "^15.6.0",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-helmet": "^5.2.0",
    "react-slick": "^0.25.2",
    "slick-carousel": "^1.8.1",
    "styled-components": "^5.0.0",
    "uuid": "^3.2.1"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "scripts": {
    "clean": "gatsby clean",
    "start": "npm run develop",
    "build": "npm run clean && gatsby build",
    "develop": "npm run clean && gatsby develop",
    "format": "prettier --trailing-comma es5 --no-semi --single-quote --write \"{gatsby-*.js,src/**/*.js}\"",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.15.3"
  }
}

**Comment by iamshaheenumar** [comment]
Somehow issue is fixed, wasn't able to know root cause of earlier issue.

**Comment by erezrokah** [comment]
Maybe a caching issue, thanks for following up here!
