### ISSUE TITLE
Glob search for collection entries in a folder and all subfolders

### ISSUE THREAD

**Issue by zachleat** [netlify/netlify-cms#3323]
Currently all entries in a Netlify CMS collection need to live in the same top-level folder. It’d be awesome if it could search inside of a folder and return all `*.md` files in there.

Relatedly, it would be _even_ better if the Collection view showed the folders too (e.g. my collection is named pages: `/admin/#/collections/pages`). And _even super better_ if the `Relation` widget showed those folders too (but that is asking a lot)

This is somewhat related to #3227

**Comment by erezrokah** [comment]
The use case for this issue should be covered in https://github.com/netlify/netlify-cms/issues/3227
Please comment if that feature doesn't satisfy the requirements.
