### ISSUE TITLE
logout not logging out

### ISSUE THREAD

**Issue by noogeu** [netlify/netlify-cms#333]
Logout button doesn't log out in Firefox 52.0.1 from Linux. No matter when or how often I click on "Logout" I am still logged in and can still edit or create new posts. 

Also previews don't work. I see a preview for less than a second, but then it disappears. This happens always. I never see previews that persists.

**Comment by erquhart** [comment]
@noogeu the Firefox preview issue is documented in #307. Did not know about the logout (which also appears to be FF specific), thanks for pointing it out!

**Comment by erquhart** [comment]
@noogeu log out should now work in Firefox. Keep an eye on #333 for the preview fix.
