### ISSUE TITLE
Grid view scrolling error on demo site posts page

### ISSUE THREAD

**Issue by shdq** [netlify/netlify-cms#3330]
Hello!

**Describe the bug**
I've explored a demo site and encountered an error.

**To Reproduce**
1. Go to https://cms-demo.netlify.com/#/collections/posts
2. Click on the "grid view" icon (view as)
3. Scroll down to the bottom
4. See the error page

**Expected behavior**
No error page

**Screenshots**
https://www.dropbox.com/s/40nr600rleifjaj/Screenshot%202020-02-27%2016.00.13.png

**Applicable Versions:**
 - OS: MacOS Catalina 10.15.3
 - Browser Chrome 79.0.3945.130 (Official Build) (64-bit) / Safari 13.0.5 (15608.5.11)

**React error description**
"Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops."

I hope it helps!

**Comment by tomrutgers** [comment]
> Scroll down to the bottom

Actually, the error occurs when the last three items reach the viewport (the JSON, TOML and YAML examples)
