### ISSUE TITLE
Feat: Add backend down status indicator

### ISSUE THREAD

**Issue by erezrokah** [netlify/netlify-cms#3334]
**Is your feature request related to a problem? Please describe.**

There is no indication in the CMS when the underlying service (BitBucket/GitHub/GitLab) used as a backend is down.

This can lead to data loss when a user tries to save an entry when the backend is down.

**Describe the solution you'd like**

A backend down status indicator (we could check https://www.githubstatus.com/ for example).

**Describe alternatives you've considered**

A bigger lift will be to add offline support.

**Additional context**

GitHub was down multiple times this week.

**Comment by erezrokah** [comment]
My be related https://github.com/netlify/netlify-cms/issues/3332

**Comment by amarpathak** [comment]
Hey, @erezrokah  I want to take it. Though I am a very starter in opensource and netlify will you help me out a bit .

**Comment by erezrokah** [comment]
Thanks @amarpathak, I would start with adding a method to the [GitHub backend](https://github.com/netlify/netlify-cms/blob/05a1c91a3c671cce8d32d50e4fb5dd8b8bba8dde/packages/netlify-cms-backend-github/src/implementation.tsx) to figure out if the backend is down.

Then probably a new redux [reducer](https://github.com/netlify/netlify-cms/blob/05a1c91a3c671cce8d32d50e4fb5dd8b8bba8dde/packages/netlify-cms-core/src/reducers/index.ts#L17) and [actions](https://github.com/netlify/netlify-cms/tree/05a1c91a3c671cce8d32d50e4fb5dd8b8bba8dde/packages/netlify-cms-core/src/actions) to store and update the backend status.

**Comment by erezrokah** [comment]
Also related to https://github.com/netlify/netlify-cms/issues/68

**Comment by nigel5** [comment]
@erezrokah this is an interesting feature that can be added. did some research and looks like GitHub and BitBucket has a public api for the status. I'll be interested in getting a PR for this if @amarpathak no longer active. Let me know.

**Comment by erezrokah** [comment]
Thanks @nigel5, I've assigned to it.
It should be easier to implement now since https://github.com/netlify/netlify-cms/pull/3847 has been merged

**Comment by nigel5** [comment]
@erezrokah Ok. What do you think about updating the existing status function in Implementation.ts to return `Promise<{ auth: boolean, backend: boolean }>` ?

For the backend providers that don't have a status api we can just assume true for the backend.

**Comment by nigel5** [comment]
When status.backend === false it can show a warning. Similar to #3847 when logged out.

**Comment by erezrokah** [comment]
That sounds good @nigel5, just I would use `Promise<{ auth: boolean, api: boolean }>`

Also, we shouldn't show the `auth` error if `api` fails since most likely `auth` won't work unless `api` is up.

**Comment by nigel5** [comment]
Sure. I have added the functionality to ping the status page for GitHub and BitBucket. When the status page summary is "critical" it shows a toast message, which would need to be localized later.

And as you mentioned, If status.api === false, it will not action the Auth toast message

https://github.com/nigel5/netlify-cms/commit/e779749e7169bc2a5eedce6dd9f2784b73e845cd

This is the commit. I hope to get some feedback before making the pull request. Thanks @erezrokah ,

**Comment by erezrokah** [comment]
Thanks @nigel5, the direction in that commit is very good - added some comments.

**Comment by nigel5** [comment]
@erezrokah Sure. I have made the suggested changes.

- Max 1 danger toast for the api down. When the api is back up, it will dismiss the notification(s) created using the key for api down
- Better status checks for GitHub, BitBucket, and Git gateway. All components in `[backend]_OPERATIONAL_UNITS`array  for these providers need to be in `operational` status.

I added a `en` ui message 'One or more backend components are down. Proceed with caution'. Will the other locales show the `en` value if they don't have it localized?

https://github.com/nigel5/netlify-cms/commit/5c5dc4e0e2e39f62a4736819b4d4c20fe38ebf6b

I think we are working in different time zones 😀. Let me know what you think about this. Thanks for helping out with this. Getting familiar with the code base.

**Comment by erezrokah** [comment]
Thanks @nigel5, appreciate your work especially with the time zones challenge.

This looks very good.

I would consider returning `true` on failure to check statues (let's assume the status page can be down but the service can be up) like here https://github.com/nigel5/netlify-cms/commit/5c5dc4e0e2e39f62a4736819b4d4c20fe38ebf6b#diff-2531b7608fefb0ddd852c544b7579bb4R195
 
Good work on the translation, not sure `backend components` is a familiar term for users.
How about `the backend service is experiencing an outage. Proceed with cation` or something similar?

Regardless I think you can open a PR to get more visibility from the community.
