### ISSUE TITLE
Error: Minified React error #185

### ISSUE THREAD

**Issue by fotovvati** [netlify/netlify-cms#3342]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by erezrokah** [comment]
Hi @fotovvati, can you share some more information regarding this issue?

**Comment by erezrokah** [comment]
Please re-open with more information if required

**Comment by tomrutgers** [comment]
Probably related to #3330
