### ISSUE TITLE
Wait Action timed out

### ISSUE THREAD

**Issue by laurenskling** [netlify/netlify-cms#3345]
I have no idea why, but I'm getting this error on collections that use `relationship` fields after upgrade from 
```
-   "netlify-cms-app": "^2.10.0-beta.3",
+   "netlify-cms-app": "^2.11.0-beta.1",
```
![image](https://user-images.githubusercontent.com/6753724/75566509-11c18480-5a50-11ea-8788-23d8a80c0a5b.png)

**Comment by erezrokah** [comment]
Hi @laurenskling, replied to your issue here https://github.com/netlify/netlify-cms/issues/3344
Please try to update to the latest stable release.

**Comment by laurenskling** [comment]
You are absolutely right, this is fixed by upgrading to a newer version.

**Comment by mncandsons** [comment]
hi @erezrokah. having similar problem, tried few versions of netlify cms, but getting very long page load. other pages work fine, but this some kind of portfolio with large images. any ideas why it could happen and how to fix this?

<img width="1438" alt="Content Manager 2020-05-06 10-52-29" src="https://user-images.githubusercontent.com/60245787/81150182-28bcaf80-8f88-11ea-9d0b-888b16299155.png">

**Comment by erezrokah** [comment]
Hi @mncandsons, do you mind opening a new issue with reproductions steps - it will make it easier to understand the flow that generates this warning. Please share a `config.yml` and the repo (if possible). Thanks
