### ISSUE TITLE
Add support for Custom Webhook Triggers

### ISSUE THREAD

**Issue by kaleabmelkie** [netlify/netlify-cms#3349]
**Feature Request**

Add general support to trigger custom [Webhooks](https://zapier.com/blog/what-are-webhooks/) defined per Collection (and per action type if possible).

This should unlock many possibilities when connected with services like [Zapier](https://zapier.com/).

**Comment by erquhart** [comment]
There’s this, but it’s not peer collection: https://www.netlifycms.org/docs/beta-features/#registering-to-cms-events

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kaleabmelkie** [comment]
Let's say I have two collections, one named Articles, and the other Products.

When an Article is created (not deleted or edited), I want to be able to trigger a webhook that automatically tweets the title and link of the article page.

I believe there are many such possibilities that can be unlocked by allowing webhooks at the per collection per action type level.

(Also, thanks for letting me know about the "registering to cms events" beta feature. I didn't know that existed)

**Comment by kaleabmelkie** [comment]
If there's any way I can use `CMS.registerEventListener` for my use case described earlier, please let me know.

**Comment by erquhart** [comment]
`registerEventListener` is close to what you need. I believe you can get the collection from the entry, so the only other thing you would need to know is whether the entry being published is new.



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kaleabmelkie** [comment]
Thanks for your support.

I'm able to use `registerEventListener` for my use-case like:

```javascript
import CMS from 'netlify-cms-app'

CMS.registerEventListener({
  name: 'postPublish',
  handler: ({ entry }) => {
    console.log(`entry.newRecord:`, entry.newRecord) // true
    console.log(`entry.collection:`, entry.collection) // 'articles'
    console.log(`entry.data:`, entry.data) // { ... }

    // I can handle the conditional logic here and trigger the webhook
  }
})
```

**Comment by erquhart** [comment]
Ah, newRecord is included, nice!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
