### ISSUE TITLE
Add "filename" as a supported template variable to the "summary" configuration

### ISSUE THREAD

**Issue by jelle619** [netlify/netlify-cms#3364]
**Is your feature request related to a problem? Please describe.**
I would like to use the file name as the title for my posts in the Netlify CMS interface. [Extracting the title to be used from the file's body does not appear to be possible](https://github.com/netlify/netlify-cms/issues/2868).

**Describe the solution you'd like**
``{{filename}}`` is a template tag available in Netlify CMS. However, for whatever reason, this variable cannot be used for ``summary`` in the configuration file (it will always be blank). Adding support for this, making it possible to set a file name as the summary of a post, would solve the problem.

(e.g. ``summary: "{{filename}}"``)

**Describe alternatives you've considered**
The file name (without extention) and the first H1 markdown header in my files are in my particular case always equal. I tried to extract this header from the body of the files, [but this does not appear to be possible](https://github.com/netlify/netlify-cms/issues/2868).

**Additional context**
Attempting to use ``summary: "{{filename}}"`` in the ``config.yml`` file results in blank titles.

![Posts are missing titles in the Netlify CMS face with "filename" as a variable to the "summarry" configuration.](https://aws1.discourse-cdn.com/netlify/original/2X/7/7401ec99260529c89f86aeddc6c1d70333858faf.png)

This issue is a result of [this topic](https://community.netlify.com/t/needing-help-with-titles-in-netlify-cms/9780) on Netlify Community.

**Comment by jelle619** [comment]
Thank you very much @erezrokah. 😄🥳

**Comment by erezrokah** [comment]
We added those (filename, extension) recently in other places, but didn't port it to the exiting summary configuration.
