### ISSUE TITLE
Broken link on Netlify Website (Docs).

### ISSUE THREAD

**Issue by yashguptaz** [netlify/netlify-cms#3365]
**Describe the bug**
The link *Authentication & Backends* on the *Add to Your Site* page is broken, it does not work. 

**To Reproduce**
1. Go to https://www.netlifycms.org/docs/add-to-your-site/#authentication
2. Click the link *Authentication & Backends*

**Expected behavior**
It should redirect to the right web page.

**UPDATE: I just realized there are many broken links in the Docs.**

The problem can be fixed at line 225 of
https://github.com/netlify/netlify-cms/blob/master/website/content/docs/add-to-your-site.md

I would really appreciate if I can be assigned this issue.
Thank You :)
- @yashguptaz

**Comment by erezrokah** [comment]
Thanks for opening this @yashguptaz!
