### ISSUE TITLE
Doc/Demo issue - missing files

### ISSUE THREAD

**Issue by cfjedimaster** [netlify/netlify-cms#338]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
The demo site for Netlify CMS includes a blog and a number of other pages as well. For example, the Values page. But when I'm in the CMS Admin, the only page I see is Products. Now if this is just because it's a demo, that's fine I guess, but I'd correct it, or be sure the docs warn folks that this project doesn't support editing everything you see. (I strongly vote for fixing it though.)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Clone the demo site the docs suggest and note you can't really edit everything.

**- What is the expected behavior?**
I want to be able to edit all my pages.

**- Please mention your node.js, and operating system version.**
Not relevant.

**Comment by erquhart** [comment]
Hi Raymond - it could be good to have everything editable on the demo, I think we'd welcome the improvement. It is a common case to have certain parts of a site be editable in a CMS while other parts are just static HTML, and it's not necessarily clear to users how to do that, so this Hugo demo shows both approaches.

Here's the template repo link if you're interested in raising the issue there or submitting a PR: https://github.com/netlify-templates/kaldi-hugo-cms-template

Closing for now, let me know if you feel I'm missing anything.
