### ISSUE TITLE
Using MDX and Registering Block Components to offer users a Page Builder Experience

### ISSUE THREAD

**Issue by austincondiff** [netlify/netlify-cms#3383]
Is a page builder like experience something that is worth considering or discussing? This may not be applicable to every collections but I do think there is a use-case for something like this.

We could include a set of basic registered component blocks in the sample site that developers could modify to fit their needs. I could also see shipping this with a storybook setup to help with the development of these block components. 

I understand that some of this could be setup manually via config.yml but the logic would be complex in these page components. We may be able to leverage [mdx](https://mdxjs.com/) here to avoid this hassle. It already looks like [mdx is supported](https://www.gatsbyjs.org/docs/mdx/) by Gatsby.

I just saw [this](https://www.builder.io/) and thought a feature like this may be a welcome addition.

**Comment by erezrokah** [comment]
Linking https://github.com/netlify/netlify-cms/issues/1776 and https://github.com/netlify/netlify-cms/issues/2064 for context

**Comment by bytrangle** [comment]
Hey @erezrokah ,
What do you think about closing issues about using MDX except for #1776?

**Comment by erezrokah** [comment]
Good point @bytrangle, #2064 is more solution oriented, but I don't want to lose the up votes of #1776.

For this issue, I think we can close it in favor of the existing issues since they are all linked.
