### ISSUE TITLE
Netlify/Nuxt.js Docs Lead to Failure on Nuxt Generate

### ISSUE THREAD

**Issue by nttdataxd** [netlify/netlify-cms#3394]
**Describe the bug**
Following the docs for Nuxt js set up leads to error when generating pages.
Ex: "ERROR  Error generating /blog/2020-03-09-test-blog-1"
Very similar to [this issue](https://github.com/netlify/netlify-cms/issues/2659) but I am not getting "FATAL Invalid left-hand side expression" error, not sure how important that is.
Also when I try with the '--verbose' tag I see "npm verb lifecycle cmsNetlify@1.0.0~generate: unsafe-perm in lifecycle true", not sure if that matters either.

![error-ss](https://user-images.githubusercontent.com/60107006/76242105-1cc0a580-6204-11ea-92dc-0a3565915b65.PNG)

Thanks so much!

**To Reproduce**
1. Follow [docs](https://www.netlifycms.org/docs/nuxt/).
2. The last step is to generate pages, this will fail.

Here is my generate property from nuxt.config.js:

 ```
 generate: {
    routes: function() {
      const fs = require('fs')
      const path = require('path')
      return fs.readdirSync('./assets/content/blog').map(file => {
        return {
          route: `/blog/${path.parse(file).name}`, // Return the slug
          payload: require(`./assets/content/blog/${file}`)
        }
      })
    }
  },
```

**Expected behavior**
Nuxt will generate pages

**CMS configuration**
Copy/pasted from docs:
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    format: 'json'
    folder: 'assets/content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

**Comment by nttdataxd** [comment]
Realized my mapping was wrong because I had the folder as "blogs" instead of "blog".

**Comment by tomrutgers** [comment]
Thanks for reporting back! Good to hear the instructions are still working.
