### ISSUE TITLE
なんやこれ

### ISSUE THREAD

**Issue by bayasshii** [netlify/netlify-cms#3398]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by tomrutgers** [comment]
Seems like you have encountered a problem while accessing the CMS. If you need some help, please fill out the issue form!
