### ISSUE TITLE
Add a "now" button to DateTime widget

### ISSUE THREAD

**Issue by vrabe** [netlify/netlify-cms#3399]
**Is your feature request related to a problem? Please describe.**

I have a field called `updatedTime` in my collection. After I update an entry, I will update the field to the current datetime. It will be convenient if there is a button in the DateTime widget to set the value to current time.

Although the default value of a DateTime widget is current datetime, it only applies to new entries.

**Describe the solution you'd like**

Add a button to the DateTime widget. The button sets the value of the widget to current datetime.

**Describe alternatives you've considered**

YouCanBookMe/react-datetime#524

**Additional context**

**Comment by hcwong** [comment]
Hi can I take a look at this?

**Comment by erezrokah** [comment]
Hi @hcwong, there is already a PR open for that: https://github.com/netlify/netlify-cms/pull/3484. I'll update it to reference the issue.
