### ISSUE TITLE
How to use backend implicit grant on dynamically created deployments

### ISSUE THREAD

**Issue by laurenskling** [netlify/netlify-cms#3402]
So I'm using NetlifyCMS on a Netlify hosted website backed by with a selfhosted gitlab.

We are handling login with the `implicit` feature, like this:

```
backend: {
    name: 'gitlab',
    repo: 'example-repo',
    auth_type: 'implicit',
    app_id: '...', // # Application ID from your GitLab settings
    api_root: 'https://git.example.com/api/v4',
    base_url: 'https://git.example.com',
    auth_endpoint: 'oauth/authorize',
}
```

But this only allows us to log in to the CMS on the URL that was set as redirect URL. `example.netlify.com`. When creating a preview deploy (`netlify deploy` without --prod) I get an url like: https://5e68def6e2114401a92282ae--example.netlify.com, but I cannot login the CMS from this url...

I sends me to the self-hosted gitlab : `https://git.example.com/oauth/authorize?client_id=4bb3bbaa94aa4d61317a6e74ca4fa4d736f5495750935f759f4c9d5....&redirect_uri=https%3A%2F%2F5e68def6e2114401a92282ae--example.netlify.com%2Fadmin%2F&response_type=.....`

which gives me the error: `The redirect URI included is not valid.`

**Comment by erezrokah** [comment]
Hi @laurenskling, I can think of two options:
1. Self hosted gitlab instance per deploy preview.
2. I think GitLab supports multiple redirect URI:
![image](https://user-images.githubusercontent.com/26760571/76428544-1a01b400-63ae-11ea-83e8-3de0b1ffd99c.png)
You can probably set up your build to use GitLab API to add the current preview URL as an additional redirect URL

**Comment by laurenskling** [comment]
Thanks for replying so quick @erezrokah .
1) I'm not quite catching this one. My code is in the selfhosted gitlab, i'm running gitlab pipelines to build my gatsby, and I deploy the build via a pipeline to netlify with the netlify-cli. Netlify gives me my deploy preview URLs.

2) setting the manually will ofcourse not work. Setting them via the API might be a think to look at. Would you have any hints on where to start looking? How would I get the preview URL from the netlify-cli? using `--json                     Output deployment data as JSON` and in some way open that JSON and using the url? And send it how back to Gitlab?

I probably want to do a similair thing for https://www.netlifycms.org/docs/deploy-preview-links/, which is not working for me right now because I'm not sending a "commit status" as the netlify builder probably does. If you could lead me in a direction to get more insights how to use these things, that would be great!

**Comment by erezrokah** [comment]
You can read about Netlify available variables here:
https://docs.netlify.com/configure-builds/environment-variables/#deploy-urls-and-metadata

Getting the CMS to display preview links is another issue, if you're build from Netlify it should set the commit status for you (not sure how it's connecting to the self hosted gitlab).
If you're setting the commit status manually you can see some information here:
https://github.com/netlify/netlify-cms/pull/3318#issuecomment-591902217
and here:
https://github.com/netlify/netlify-cms/pull/3318#issuecomment-594371694
and here:
https://docs.gitlab.com/ee/api/commits.html#post-the-build-status-to-a-commit

**Comment by erezrokah** [comment]
Closing, please comment if you have any more questions
