### ISSUE TITLE
Details TypeError: e.replace is not a function

### ISSUE THREAD

**Issue by LGTMXD** [netlify/netlify-cms#3413]
**Describe the bug**

> Turn on and turn off button `Featured(optional)`,then content manager website crash.

**To Reproduce**
1.  Connect Netlify to your GitHub account to create your [academic-kickstart](https://sourcethemes.com/academic/docs/install/#install-with-web-browser) repository.
2.  Go to https://yourwebsite.com/admin/  log in with github account
3.  Click `New Post`,then turn on `Feature` button twice
4. See error,pic blew:

![image](https://user-images.githubusercontent.com/30213081/76520334-aa6af200-649d-11ea-8f12-a821ad63644a.png)

![](https://user-images.githubusercontent.com/30213081/76502341-cf9c3800-647e-11ea-939a-01d9a1d1452e.jpeg)

**CMS configuration**

[config.yml and index.html](https://github.com/sourcethemes/academic-kickstart/tree/master/static/admin)

gcushen/hugo-academic#1593

**Comment by erezrokah** [comment]
Collections field names should be unique:
https://github.com/sourcethemes/academic-kickstart/blob/3bac8f0494bf35e64fb5943a99ccc377e7cac390/static/admin/config.yml#L24
https://github.com/sourcethemes/academic-kickstart/blob/3bac8f0494bf35e64fb5943a99ccc377e7cac390/static/admin/config.yml#L45

Regardless, we should verify it while loading the configuration and display a proper message

**Comment by LGTMXD** [comment]
> Collections field names should be unique:
> https://github.com/sourcethemes/academic-kickstart/blob/3bac8f0494bf35e64fb5943a99ccc377e7cac390/static/admin/config.yml#L24
> https://github.com/sourcethemes/academic-kickstart/blob/3bac8f0494bf35e64fb5943a99ccc377e7cac390/static/admin/config.yml#L45
> 
> Regardless, we should verify it while loading the configuration and display a proper message

@gcushen

**Comment by erezrokah** [comment]
Closing this as a configuration issue, please re-open/or comment if necessary.
