### ISSUE TITLE
Listing collection folder now included images

### ISSUE THREAD

**Issue by Gargam** [netlify/netlify-cms#3414]
**Describe the bug**
I have a collection setup with media folder and public path. 
Everything was fine until today as it now list all the files from it, not just *.md file but also my images files for example. They are shown as empty title lines.

**To Reproduce**
This is my configuration for the collection
```
collections:
  - name: 'projects'
    label: 'Projets'
    folder: 'content/projects'
    create: true
    media_folder: ''
    public_folder: ''
    fields:
....
```

**Expected behavior**
It should only list file that are editable by netlify cms admin (.md files).

**Screenshots**

**Applicable Versions:**
netlify-cms-app 2.11.14
netlify-cms-core 2.17.0
Git provider: Gitlab

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

```
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'

collections:
  - name: 'projects'
    label: 'Projets'
    folder: 'content/projects'
    create: true
    media_folder: ''
    public_folder: ''
    fields:
      - {
          label: Type,
          name: projectType,
          widget: 'select',
          options: ['standard', 'collab'],
        }
      - { label: Title, name: 'title', widget: 'string' }
      - { label: 'SEO: Description', name: 'seoDescription', widget: text }
      - { label: 'Image', name: 'coverImage', widget: 'image' }
      - label: 'Photos'
        name: 'photos'
        widget: 'list'
        fields:
          - { label: Title, name: title, widget: text, default: '' }
          - { label: Image, name: image, widget: image }
```

**Additional context**
It was already working previously

**Comment by erezrokah** [comment]
I think this might be related a bug that was fixed in latest versions, where paginated entries were not filtered.
Do you by chance have more than 20 entries for that collection? 
If should this issue was fixed here https://github.com/netlify/netlify-cms/pull/3216

**Comment by Gargam** [comment]
I have in the directory 24 files but only 8 md files.
Also the issue is not visible if I use local_backend and a proxy server (launch by `npx netlify-cms-proxy-server`)

**Comment by erezrokah** [comment]
Sorry, I should have been more accurate in my response. This issue is present with old versions of the CMS using GitLab where the directory in the repo has more that 20 files, where some of them are not data files (e.g. md).
In short, this was fixed and updating your version of the CMS should resolve it.
`local_backend` doesn't connect to GitLab at all, thus doesn't have that issue.

**Comment by Gargam** [comment]
Yup, I updated and it's ok now.
Wasn't sure to do that as I needed to rewrite some code because of getAsset changes

Thanks !
