### ISSUE TITLE
Make it possible to download files from the Media page

### ISSUE THREAD

**Issue by ofaklintrafo** [netlify/netlify-cms#3429]
It is not possible to download files from the media page. There are only two buttons, upload and delete. 

It would be very helpful if this was possible. 

Especially if the media page contains non-image files. For example pdf-documents.

The link could for example point directly to the file in the Git-repository.

**Comment by erezrokah** [comment]
Related https://github.com/netlify/netlify-cms/issues/2243

**Comment by tinfoil-knight** [comment]
@erezrokah Can I try this issue out? I'll be updating you on progress regularly.

**Comment by erezrokah** [comment]
@tinfoil-knight, go for it :)

**Comment by tinfoil-knight** [comment]
![image](https://user-images.githubusercontent.com/51631122/79238547-21c0e680-7e8d-11ea-8958-c8039ec364be.png)
@erezrokah I have a question : 
Is the placement of the download button going to be as in the attached image?

**Comment by tinfoil-knight** [comment]
WIP #3604

**Comment by tinfoil-knight** [comment]
WIP #3609

**Comment by tinfoil-knight** [comment]
This issue is closed now. #3609 
@erezrokah Please close this.

**Comment by mauriciabad** [comment]
I noticed that the label download is missing in many languages.
