### ISSUE TITLE
 Unable to access identity settings; identity service and git-gateway ARE enabled

### ISSUE THREAD

**Issue by LeunensMichiel** [netlify/netlify-cms#3430]
Hi!

I've used Netlify, Gatsby and NetlifyCMS in the past, and have never encountered this problem. While setting up my site, I can't seem to access the admin page, nor am I able to invite a user. I have my config.yml correctly set up

```backend:
  name: git-gateway
  branch: master
```

I have reinstalled my site, relinked my github repo, generated a new API key for gateway, but all in vein.

I'm getting this error. I searched the docs and google, but can't seem to find anything.
![image](https://user-images.githubusercontent.com/18447679/76769738-1d75b080-679d-11ea-9889-3cbe14d3d2c3.png)

Thanks in advance!

**Comment by erezrokah** [comment]
Hi @LeunensMichiel, can you share the network traffic from your browser? Specifically there should be a few requests to the identity service `.identity/` and `git-gateway` service `.git/`.

**Comment by LeunensMichiel** [comment]
Okay!
So when I click on **Login with Netlify Identity**, i get this for ./netlify/identify/settings

```
Request URL: https://www.lowatter.com/.netlify/identity/settings
Request Method: GET
Status Code: 404 
Remote Address: 157.230.120.63:443
Referrer Policy: no-referrer-when-downgrade
age: 0
alt-svc: clear
content-length: 56
content-type: application/json
date: Mon, 16 Mar 2020 16:18:10 GMT
server: Netlify
status: 404
vary: Origin
via: 1.1 google
x-nf-request-id: f68f2423-9f50-4da6-a498-26e232b056f6-5714200
:authority: www.lowatter.com
:method: GET
:path: /.netlify/identity/settings
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,nl-BE;q=0.8,nl;q=0.7,en-BE;q=0.6,fr-BE;q=0.5,fr;q=0.4
content-type: application/json
dnt: 1
referer: https://www.lowatter.com/admin/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
```

I can't seem to find something related to ./git though. 

Thank you for looking into this!

**Comment by erezrokah** [comment]
That helps thanks! The `.git/` requests come only after successful identity ones.
Do you have any warnings regarding DNS in your Netlify site?
I'm getting inconsistent results.
Sometimes `curl -i https://www.lowatter.com/.netlify/identity/settings` fails with 404 and sometimes succeeds.
Also does using the Netlify custom domain work? e.g. going to `https://<site-id>.netlify.com/`

**Comment by LeunensMichiel** [comment]
Hey! Yeah that works. I went to lowatter.netlify.com/admin/ and there I was able to see the login dashboard. And for some reason, the 404 disapeared on the normal URL. 

But I still get redirected when I try to invite myself through email, so I can't log in yet. And I'm not seeing any DNS issues. 

I want to provide some errors to you, but I'm not getting any. It's hard to trace if the issue is coming from my code, netlify, or netlify cms.

**Comment by erezrokah** [comment]
not sure, but if `curl -i https://www.lowatter.com/.netlify/identity/settings` returns a correct response consistently for you, it should work in the CMS too (might be DNS records updating).

As for the invites, Netlify invite links redirect the user to the root site by default (and not `/admin`). You can modify it via email templates: https://docs.netlify.com/visitor-access/identity/identity-generated-emails/

**Comment by LeunensMichiel** [comment]
Okay, thank you for that! I will keep this updated if I find a solution.

**Comment by erezrokah** [comment]
Can we close this issue? I think it is more Netlify related than the CMS. Might be better to use the Netlify community: https://community.netlify.com/

**Comment by LeunensMichiel** [comment]
Yes go ahead. Again thank you for your time.
