### ISSUE TITLE
Folder collections fail if the folder does not exist

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#3432]
**Describe the bug**

If the folder for a collection does not exist, the CMS fails, erroring out while attempting to infer fields.

**To Reproduce**

- configure the cms with a folder collection, but for a folder that does not exist
- load CMS
- observe errors in console and no way to add a new entry to the collection

**Expected behavior**

- CMS should recognize that folder does not exist
- CMS should not error
- CMS should allow creation of a new entry

**Applicable Versions:**

 - Node.JS version:

**CMS configuration**

netlify-cms@2.10.32

**Additional context**

I believe this used to work and represents a regression, but not 100% certain.

**Comment by erquhart** [comment]
Update: this seems specific to Git Gateway.

**Comment by erezrokah** [comment]
Tried reproducing on this branch https://github.com/erezrokah/netlify-cms-reproductions/tree/netlify_cms/issue_3432
See PR https://github.com/erezrokah/netlify-cms-reproductions/pull/150/files

https://github.com/erezrokah/netlify-cms-reproductions/blob/netlify_cms/issue_3432/public/config.yml

The folder `content/posts` doesn't exist on the branch.

I might be missing something here.

**Comment by erquhart** [comment]
Alright, will close - thanks for looking into it.
