### ISSUE TITLE
RangeError: Invalid time value

### ISSUE THREAD

**Issue by scottmathson** [netlify/netlify-cms#3434]
was told via CMS prompt to report this, here's what I'm seeing:
![CMS screenshot](https://user-images.githubusercontent.com/25587929/76805855-94af4280-67a5-11ea-91ff-8e6f73037661.png)

upon hard refresh, things did start working.

wanted to report nonetheless, in the case this helps.

**Comment by erezrokah** [comment]
This was fixed by checking for an undefined date in the preview template (it might take the CMS a render cycle to update entry data with the current date).
