### ISSUE TITLE
netlify-cms-widget-date: Failed to compile with 1 errors

### ISSUE THREAD

**Issue by lkaupp** [netlify/netlify-cms#3444]
**Describe the bug**

Trying to contribute but i even can't compile your master branch.

**To Reproduce**

Steps to reproduce the behavior. 
1. Checkout Master
2. yarn installl
3. yarn build

**Expected behavior**
clean build

**Error Log**
````
lerna ERR! yarn run build exited 2 in 'netlify-cms-widget-date'
lerna ERR! yarn run build stdout:
$ cross-env NODE_ENV=production webpack
Building [netlify-cms-widget-date, library: NetlifyCmsWidgetDate]
Build Package: netlify-cms-widget-date
 ERROR  Failed to compile with 1 errors19:42:40

 error  in D:/netlify/netlify-cms-master/node_modules/react-datetime/css/react-datetime.css

Module parse failed: Unexpected token (5:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
|
> .rdt {
|   position: relative;
| }

 @ ./src/DateControl.js 20:0-72 142:28-47
 @ ./src/index.js

Child
     2 assets

    ERROR in D:/netlify/netlify-cms-master/node_modules/react-datetime/css/react-datetime.css 5:0
    Module parse failed: Unexpected token (5:0)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    |  */
    |
    > .rdt {
    |   position: relative;
    | }
     @ ./src/DateControl.js 20:0-72 142:28-47
     @ ./src/index.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```.`

**Applicable Versions:**
Master

**Comment by erezrokah** [comment]
Can you try running `yarn bootstrap` before build?
Also, does `yarn start` work? Which yarn version are you using?
Other useful commands to try can be found here:
https://github.com/netlify/netlify-cms/blob/master/CONTRIBUTING.md#install-dependencies

**Comment by lkaupp** [comment]
yarn bootstrap:
```
\netlify-cms-master>yarn bootstrap
yarn run v1.22.4
$ lerna bootstrap
lerna notice cli v3.20.2
[1/4] Resolving packages...
success Already up-to-date.
Done in 2.19s.
```
yarn start (the only error thrown):
```
netlify-cms:  ERROR  Failed to compile with 4 errors20:48:01
netlify-cms: These dependencies were not found:
netlify-cms: * netlify-cms-app/dist/esm in ./src/index.js, ./src/extensions.js
netlify-cms: * netlify-cms-media-library-cloudinary in ./src/extensions.js
netlify-cms: * netlify-cms-media-library-uploadcare in ./src/extensions.js
netlify-cms: To install them, you can run: npm install --save netlify-cms-app/dist/esm netlify-cms-media-library-cloudinary netlify-cms-media-library-uploadcare
```

**Comment by erezrokah** [comment]
Just did a fresh clone and followed https://github.com/netlify/netlify-cms/blob/master/CONTRIBUTING.md#install-dependencies as was able to build (build also passing on our CI).

Can you share:
1. OS
2. Node+NPM version
3. Try a fresh clone/delete node modules.
4. `yarn cache clean`

FYI, I tested with yarn 1.22.4, node v12.16.1, npm 6.13.4 and MacOS Catalina 10.15.3

**Comment by lkaupp** [comment]
OS: Windows 10
node: v13.11.0
npm: 6.13.7
yarn: 1.22.4

**Comment by erezrokah** [comment]
Thanks @lkaupp, I was able to reproduce on a virtual box with a windows machine. Looking into it.

**Comment by lkaupp** [comment]
i downgraded to your version, problem still persists on Windows 10

**Comment by erezrokah** [comment]
What do you mean by downgraded? I submitted a PR with a fix and waiting for it to be improved.
If you apply this change https://github.com/netlify/netlify-cms/pull/3449/files#diff-cf797e56490cde8743c10775323fd4ddR10 the build should pass.

**Comment by lkaupp** [comment]
i just used the version you used on mac on my windows machine but the error kept the same.

**Comment by erezrokah** [comment]
Can you please try with the latest changes from `master` branch?

**Comment by lkaupp** [comment]
yep, done it, everything builds wonderful! Thank you for your help :) - Issue is solved.
