### ISSUE TITLE
Absolute media paths defined by collection

### ISSUE THREAD

**Issue by dawaltconley** [netlify/netlify-cms#3451]
**Is your feature request related to a problem? Please describe.**

Currently, using the `media_folder` option in a collection seems to make all image widgets upload their files relative to path of the items in that collection. This means it's not possible to specify an absolute path for _all_ media files in a collection to share, or for media in multiple collections to share an absolute folder other than the master `media_folder` folder.

**Describe the solution you'd like**

I think this should be possible. The most intuitive way I see would be for all paths starting with a slash to be absolute, and all lacking it to be relative. I.e.

```
media_folder: /assets/posts
```

would upload files to an `assets/posts` folder relative to the `site_url`, while

```
media_folder: assets/posts
```

would upload files to an `assets/posts` folder relative to the individual collection file.

**Describe alternatives you've considered**

The other solutions I can think of are all less elegant, all involving some other option, like `media_folder_absolute: true`. But I know the proposed solution would be breaking for some.

**Additional context**

For me, this is important because I optimize images differently depending on their file path. But in general, I think it would help with organization for sites where assets don't need to be stored relative to the content referencing them.

**Comment by erezrokah** [comment]
Hi @dawaltconley, that is actually supported (just by prefixing the folder with a slash). Can you share your `config.yml` and CMS version?

**Comment by dawaltconley** [comment]
Well...it is working for me now. Apologies, I must have messed something up. 😳  Great feature!!
