### ISSUE TITLE
can't access netlify cms

### ISSUE THREAD

**Issue by PatrickNugros** [netlify/netlify-cms#3452]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by erezrokah** [comment]
Hi @PatrickNugros, can update your issue per the template here https://github.com/netlify/netlify-cms/issues/new?template=bug_report.md ?

**Comment by erezrokah** [comment]
Please re-open when you have more information
