### ISSUE TITLE
cant make a new post , only defaut post

### ISSUE THREAD

**Issue by blackgunnen** [netlify/netlify-cms#3478]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by erezrokah** [comment]
Hi @blackgunnen, do you mind sharing more information like your `config.yml`/repo and a reproduction scenario?

**Comment by blackgunnen** [comment]
Thanks for quick reply , when i try to do new post i cant see the preview
in the cms netlify like the defaut post . In fact I still make the new post
. Another request , it seems that allowed only 1 photo for every post  so
how can i add more. Should I change the code in the visual studio?
BEST REGARDS

Vào Thứ Năm, 26 tháng 3, 2020, Erez Rokah <notifications@github.com> đã
viết:

**Comment by erezrokah** [comment]
Hi @blackgunnen, can you share your repo/a reproduction scenario like described in the issue template here:
https://github.com/netlify/netlify-cms/issues/new?template=bug_report.md

Not sharing that information makes it very hard to figure out the problem you're having.

**Comment by erezrokah** [comment]
Closing, please comment/re-open with the issue template
