### ISSUE TITLE
Front-matter loading problem with static entries created on Windows

### ISSUE THREAD

**Issue by maximelaboisson** [netlify/netlify-cms#351]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**- Do you want to request a *feature* or report a *bug*?**
Report a bug.

**- What is the current behavior?**
If a static entry for a given collection is created under Windows, the CMS won't load the front matter correctly and will output everything in the body. 
That is because Windows uses CRLF line endings while the CMS seems to only load the front matter properly when using LF line endings.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Create any static entry for any collection under a Windows OS.
Push to GitHub.
Open the entry in the admin dashboard.

**- What is the expected behavior?**
Front matter should be loaded in the according fields instead of the body.

**- Please mention your node.js, and operating system version.**
Node - 6.10
OS - Windows 10

**Comment by erquhart** [comment]
@maximelaboisson I'm wondering if a recently merged yaml parser update may help - I just published 0.3.17, can you update to that and try again?

**Comment by maximelaboisson** [comment]
Sounds good! Trying right now.

**Comment by maximelaboisson** [comment]
Yep, fixed now!

Thanks @erquhart

**Comment by erquhart** [comment]
Shouts out to @josephearl - two birds!

**Comment by josephearl** [comment]
Great news 👏
