### ISSUE TITLE
npx netlify-cms-proxy-server fails (was working yesterday)

### ISSUE THREAD

**Issue by PetroPavlenko** [netlify/netlify-cms#3510]
**Describe the bug**
➔ npx netlify-cms-proxy-server
npx: installed 67 in 3.733s
Cannot find module 'semaphore'
Require stack:
- /Users/XXXXX/.npm/_npx/21426/lib/node_modules/netlify-cms-proxy-server/dist/index.js

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: GitHub
 - OS: mac Os latest

 - Node.JS version:
npm@6.13.4 /Users/petropavlenko/.nvm/versions/node/v12.16.0/lib/node_modules/npm

**CMS configuration**
Private repo

**Additional context**
was working yesterday

**Comment by erezrokah** [comment]
Thanks for opening this @PetroPavlenko, will look into it

**Comment by erezrokah** [comment]
Workaround: `npx netlify-cms-proxy-server@1.2.2`

**Comment by PetroPavlenko** [comment]
Thanks, it helps )

**Comment by erezrokah** [comment]
Fixed in `netlify-cms-proxy-server@1.2.4`
