### ISSUE TITLE
Media gallery not accepting files over ~900kB

### ISSUE THREAD

**Issue by webdevFM** [netlify/netlify-cms#3533]
**Describe the bug**
When trying to upload media (PDF file) whose size is over 900kB through the CMS I get unrecognized error. Toast displaying error is empty so I do not know what is broken. In Chrome developer console I see request being sent at https://<my_url>.netlify.com/.netlify/git/github/git/blobs?ts=<random_number> to which server responds with 500 internal server error. Small files ~50kB are being uploaded correctly and do not experience this specific error.

**To Reproduce**
1. Go to CMS (/admin) of the website. 
2. Upload pdf file weighing around 50kB. You can see file was uploaded.
3. Upload pdf file weighing around ~900kB or more. File is not being sent. When exiting file upload dialog, there is red, empty Toast in the top of the browser.

**Expected behavior**
File whose size is ~900kB should be uploaded similarly to smaller files as it does not exceed github's file upload limit. I couldn't also find any limit for file upload in the docs.

**Screenshots**
API error seen in Network tab of chrome's developer console. 2 requests are being fired upon file upload. Please note that the first one goes through and uploaded file can be accessed under url in request, however the second one fails and file is not uploaded to media gallery.
![image](https://user-images.githubusercontent.com/62745213/77763626-a90ffc80-703b-11ea-9b29-fe7eb6680cf0.png)
![image](https://user-images.githubusercontent.com/62745213/78342951-65b51100-759a-11ea-8ae9-c2f4c4a857ed.png)

Exceptions that are being thrown in console.
![image](https://user-images.githubusercontent.com/62745213/77763815-f0968880-703b-11ea-8ce5-f31dc970bc42.png)
Empty toast not displaying error.
![image](https://user-images.githubusercontent.com/62745213/77763880-073cdf80-703c-11ea-9e9a-7765d17a013d.png)

**Applicable Versions:**

 - Netlify CMS version: netlify-cms-app 2.11.32, netlify-cms-core 2.22.2, netlify-cms 2.10.35
 - Git provider: GitHub
 - OS: macOS Catalina v10.15.3
 - Browser version: Chrome 80.0.3987.149

**CMS configuration**
Not related to the error

**Comment by erezrokah** [comment]
Hi @webdevFM do you mind sharing the response for the failed `blobs` request? That error is coming from the GitHub API so the response might contain useful information

**Comment by webdevFM** [comment]
Hi @erezrokah, thank you for responding to my issue. Unfortunately `blobs` request is not sharing any details. I only receive following response headers as seen in chrome's network tab 
![image](https://user-images.githubusercontent.com/62745213/78537054-27fcf600-77ef-11ea-9960-1deee5f69183.png)

There is no response data
![image](https://user-images.githubusercontent.com/62745213/78537282-875b0600-77ef-11ea-8580-74ca09c2e8f5.png)

Please let me know if there is anything more I can provide to help troubleshoot the issue.

**Comment by webdevFM** [comment]
Hello @erezrokah, did you manage to reproduce the issue? Are any additional logs/information required?

**Comment by erezrokah** [comment]
Thanks you for bumping, got caught up with other stuff and missed this one.
I was able to upload a 3.6MB image:
![image](https://user-images.githubusercontent.com/26760571/80689201-a3dc1c80-8ad5-11ea-919e-ef3e0b664a9e.png)
![image](https://user-images.githubusercontent.com/26760571/80689253-b8201980-8ad5-11ea-8cb0-efd6a9fc829f.png)

Things to try - a different browser, clearing cache, upgrading the CMS.

I tested with:
```
netlify-cms-app 2.12.7
netlify-cms.js:68 netlify-cms-core 2.24.2
netlify-cms.js:183 netlify-cms 2.10.43

Brave: Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)
OS: macOS Catalina v10.15.3
```

**Comment by webdevFM** [comment]
Thank you for response. I've tried different browsers (Firefox, Safari), clearing cache, upgrading the CMS (by fetching newest version from unpkg.com/netlify-cms/dist/netlify-cms.js) but none of that worked.

However, when I've configured the CMS config to use github backend directly instead of git gateway as you suggested, I've managed to upload large files via CMS.
```
    backend:
        name: github
```

Is there any size limit for file upload while using git-gateway? Git-gateway has an advantage that CMS users do not need to have github account.

You mentioned that you managed to upload 3.6MB file, did you use git-gateway or github backend directly?

**Comment by erezrokah** [comment]
Hi @webdevFM, I used `git-gateway`. The advantage of `git-gateway` is that CMS users don't need to have a GitHub account (you can invite them via Identity).
At least we narrowed it down to a git-gateway related issue - how about disabling/enabling it?
Is it a specific file or any big enough file?

**Comment by webdevFM** [comment]
Hello, I've tried disabling and enabling git-gateway but it did not help. It's not specific file but any file over ~900kB causes upload to fail.

**Comment by erezrokah** [comment]
Sorry for the late reply again, does it happen with every site or a specific site? Maybe creating a new site can resolve this?

**Comment by webdevFM** [comment]
Hi @erezrokah, I have not tried creating specific site. My team has decided to migrate to bitbucket repo to maintain all repos in one place, so the problem solved itself in a way. I will close the issue if you don't mind.
