### ISSUE TITLE
publish and duplicate does not work

### ISSUE THREAD

**Issue by jannis701** [netlify/netlify-cms#3544]
**Describe the bug**
The button "publish and duplicate" (German: "Veröffentlichen und Beitrag dublizieren") does not work properly. When you press it, the entry is published, but after loading the form for a new entry with the old content, there will be a redirect to the edit-page of the published entry.
Therefore after pressing the button one will edit the current entry instead of creating a new one.
Happens even in backend: test-repo but also in backend: gitlab

**To Reproduce**
1. config test-repo as backend and define at least 1 collection that allows creating entries and use the default publish_mode 
2. Log in and navigate to create a new entry in the collection
3. enter something and select "publish and duplicate"

The entry is published, you are redirected to form for a new entry and then you are redirected to the form to edit the published entry

**Expected behavior**
entry is published and the form for a new entry with the published content is opened.

**Applicable Versions:**
netlify-cms-app 2.12.3
netlify-cms-core 2.23.3
netlify-cms 2.10.39
 - Git provider: gitlab or test-repo
 - OS: ubuntu
 - Browser version firefox 74.0

**Comment by saschatu** [comment]
HI @erezrokah ,

unfortunately this bug is still reproducable: "New" -> Enter data for first entry ->"Publish and Duplicate" (and waiting for save) ->  change data for 2nd entry -> Publish. This leads to the first entry being updated (instead of second entry creation).

Just upgrade - versions:
netlify-cms 2.10.51 
netlify-cms-core 2.29.0
netlify-cms-app 2.12.15

**Comment by erezrokah** [comment]
Hi @saschatu, I tested https://cms-demo.netlify.com/ and it created two different entries.
Can you open a new issue for it?
