### ISSUE TITLE
Social Widget

### ISSUE THREAD

**Issue by WebAzOps** [netlify/netlify-cms#3547]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by erezrokah** [comment]
Hi @WebAzOps, do you mind following the bug/feature request templates?
https://github.com/netlify/netlify-cms/issues/new?template=feature_request.md
https://github.com/netlify/netlify-cms/issues/new?template=bug_report.md

It makes it very hard to figure out the requested feature without it.

**Comment by erezrokah** [comment]
Closing, please re-open an follow one of the provided templates
