### ISSUE TITLE
JSON handling does not yield predictable orders, generates bad diffs

### ISSUE THREAD

**Issue by djMax** [netlify/netlify-cms#3557]
**Describe the bug**
If the output type is JSON, the fields seem to be written in a mostly random order (it is almost certainly not random, but it's not 'as expected').

**To Reproduce**
1.) Create a JSON format collection with a number of simple string values.
2.) Create an entry - I did this manually, which may be the source of the issue.
3.) Edit the entry with NetlifyCMS by changing a single field
4.) See that the diff is not necessarily as simple as it could be

**Expected behavior**
IF the problem is just that it doesn't respect the order of the keys in the existing content, that seems not horrible. But if it's that it's always non-deterministically ordered, I would suggest that's a bug.

I know this bug report needs more context, and I will try to add that, but wanted to get it created per a Slack discussion.

**Comment by erquhart** [comment]
In the case you outlined, what happens if you edit the entry through the CMS again? It’s expected that the CMS will initially reorder keys, but the order should be stable after that as long as the CMS is used.

**Comment by djMax** [comment]
Ok, great. That seems perfectly reasonable.
