### ISSUE TITLE
Remove pre-commit hook

### ISSUE THREAD

**Issue by josephearl** [netlify/netlify-cms#356]
**- Do you want to request a *feature* or report a *bug*?**

Bug(?) It makes contributing less easy and more confusing new users.

**- What is the current behavior?**

1. Clone fresh repo to contribute.
2. Make changes to a file.
3. Pre-commit hook runs.
4. Raises errors about existing code.

**- What is the expected behavior?**

No errors raised about existing code. Existing code matches pre-commit rules.
Only errors raised about newly added or changed code.

**- Please mention your node.js, and operating system version.**

Node v7.8.0, macOS Sierra.

**Comment by biilmann** [comment]
I'm in favor of getting rid of those hooks completely. They feel very intrusive when doing many small in progress commits that you'll squash and cleanup later.

I would also suggest customizing the eslint settings to make sure they match how the code of the CMS is currently formatted quite closely, so we can get all code to pass linting and then require passing linting before accepting pull requests. Then we can start gradually introducing stricter linting rules little by little, but making sure we make them all pass for each rule added.

**Comment by Benaiah** [comment]
@biilmann I'm also in favor of removing the hooks. Since we do everything through PRs anyway, it really seems unnecessary. Once we *do* have the master fully lint-compatible I think it'd be worth adding to Travis, but a pre-commit hook really seems unnecessary even in that case.

**Comment by josephearl** [comment]
Renamed this issue to "Remove pre-commit hook". Raised new issue #363 to fix the lint issues on master.
