### ISSUE TITLE
User not found error

### ISSUE THREAD

**Issue by eallenOP** [netlify/netlify-cms#3565]
**Describe the bug**

When trying to accept an invite or log in to mysite/admin I get repeated user not found messages.

**To Reproduce**

1. Set up a Jekyll site to use Netlify CMS for blog authoring
2. Use Netlify CMS Identity to invite myself as a user (including the option for Google auth)
3. Follow the link in the email to accept invite
4. Click on the Continue with Google option
5. Browser window shows only `{"code":404,"msg":"User not found"}`
6. Visit my-site/admin and click Continue with Google
7. Get same page but with Not found in a yellow modal (like with #1703 except I didn't change the repo from public to private - it's always been private)

**Expected behavior**

The ability to accept an invite via email link and log in to author posts.

**Screenshots**

![Not found](https://raw.githubusercontent.com/ek-nz/eallenop.github.io/master/img/Screen%20Shot%202020-04-09%20at%2012.05.57%20PM.png)

*^ What I get when I visit my-site/admin*

![User not found](https://github.com/ek-nz/eallenop.github.io/blob/master/img/Screen%20Shot%202020-04-09%20at%2012.25.35%20PM.png?raw=true)

*^ What I get when I click the invite link with no Google auth enabled and try to make a password*

**Applicable Versions:**

 - Netlify CMS version: whatever the docs told me to use (2.0.0 I think)
 - Git provider: GitHub
 - OS: macOS Mojave
 - Browser version: Chrome Version 80.0.3987.149 (Official Build) (64-bit)

**CMS configuration**

```
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
        label: 'Author',
        name: 'author',
        widget: 'relation',
        collection: 'authors',
        displayFields: [display_name],
        searchFields: [display_name],
        valueField: 'name',
      }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'authors'
    label: 'Authors'
    folder: '_authors/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'author' }
      - { label: 'Short Name', name: 'name', widget: 'string' }
      - { label: 'Diplay Name', name: 'display_name', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

```

**Additional context**

- I tried resetting the token (and also resetting it and then triggering a new deploy).
- I tried turning Identify off and on again
- I tried it without the Google option (I get User not found as a red message above the password box after following the email invite link and putting in a password)
- I tried deleting the site from Netlify and then starting again (this was after I thought I had broken it by changing the sites name after turning Identity on but before inviting users).
- I tried clicking the invite link in the email again and it tells me I'm logged in, but I still can't access my-site/admin (it gives me the login page with Not found at the top again)

**Comment by eallenOP** [comment]
**Update:**
I deleted the site again, set the repo to public (not ideal), put the site back up on Netlify and set up Identify. Now it works.

Does Netlify CMS not work at all with private repos? I thought it was supposed to.

**Comment by erezrokah** [comment]
It does work with private repos, but if you change the permissions (e.g. move a repo from public to private) you'll need to re-generate the `git-gateway` token from Netlify site settings.

**Comment by eallenOP** [comment]
Yes, sorry for the very long post. Your original answer is similar to #1703 and would be useful to most people with these symptoms.

I guess I could change the repo to private, regenerate the key and expect one of two things: it’ll work fine (which would be great because that’s how I’d originally wanted it) or the same problem will occur and I can look at the browser network logs. Will let you know how I get on.

**Comment by erezrokah** [comment]
Thanks for the follow up! I'll try with again with a newly fresh private repo and see if I can reproduce. If not I'll just close the issue.

**Comment by erezrokah** [comment]
Closing as stale - I tried setting up `git-gateway` with a private repo and seems to work the first time.
Please comment if relevant
