### ISSUE TITLE
registerPreviewTemplate ComponentType missing generic type declaration

### ISSUE THREAD

**Issue by tafelito** [netlify/netlify-cms#3572]
the types for the registerPreviewTemplate function is missing the Props generic and using it with typescript gives the error  JSX.Element' is not assignable to parameter of type 'ComponentType<{}>'. when the component has props 

I think the easiest way to solve this is to add the generic [here] (https://github.com/netlify/netlify-cms/blob/92e76011e7a9e8b5370088b0a2c065df66b5f7fb/packages/netlify-cms-core/index.d.ts#L207). 

it should be `registerPreviewTemplate: (name: string, component: ComponentType<P>) => void;`

correct me if I wrong

**Comment by erezrokah** [comment]
Thanks @tafelito, we will gladly accept a PR for this.

**Comment by tinfoil-knight** [comment]
@erezrokah I've been meaning to start contributing to netlify-cms. Can I send a PR for this issue?

**Comment by erezrokah** [comment]
@tinfoil-knight, go for it 😄 Thanks!

**Comment by tinfoil-knight** [comment]
@erezrokah Please review #3597.

**Comment by tinfoil-knight** [comment]
@erezrokah Close this issue.

**Comment by erezrokah** [comment]
Closed via https://github.com/netlify/netlify-cms/pull/3597
