### ISSUE TITLE
Use collection summary field in workflow card instead of hardcoded title

### ISSUE THREAD

**Issue by hanneskuettner** [netlify/netlify-cms#3573]
**Is your feature request related to a problem? Please describe.**

I'm trying to use the editorial workflow with a collection that does not (and should not for semantic purposes) have a title field. The problem is that the list in the editorial workflow tab shows a blank list item since it is hardcoded to look for the title of the entry.

https://github.com/netlify/netlify-cms/blob/b9d66322033f4e582fcee05ac03ce267f4826b9b/packages/netlify-cms-core/src/components/Workflow/WorkflowList.js#L235

This leads to unusable UI and should in my opinion not be a restriction imposed by the CMS.

**Describe the solution you'd like**

Since the `summary` field is already plenty customizable and used in the collection list we should use the summary field as the title in the workflow entry card as well.
The precedence for selecting the card title should follow the same rules as the collection entry title selection.

**Describe alternatives you've considered**

Introduce a new field to customize the title in a workflow card, this seems overkill to me though.

**Additional context**

**Comment by hanneskuettner** [comment]
If using the summary field in conjunction with the inferred title field just as done in the entry card is the desired way to handle this I could whip up a PR for this as well.

**Comment by tomrutgers** [comment]
You can set an `identifier_field` property to assign another field than the title: https://www.netlifycms.org/docs/configuration-options/#identifier_field

Does this cover your needs?

**Comment by hanneskuettner** [comment]
I tried that. That did however not work.

Looking at the code I don't think it is expected to work. We would need to use `selectInferedField` to correctly infer the title attribute. But right now it's just a plain lookup in the data for `title`

Or is that done behind the scenes when the entry is passed down to the workflow list? 

A minimal collection that shows up with an empty title for me is is

```yaml
collections:
  - name: test
    label: Test
    identifier_field: id

    create: true
    folder: data/test

    fields:
      - { label: Item ID, name: id, widget: string }
```

**Comment by erquhart** [comment]
Weird that we’re not inferring. Summary makes sense for workflow too, I’d expect us to have the same behavior as the collection view in this regard.

**Comment by hanneskuettner** [comment]
Just FYI I started on a PR for unifying the collection entry tittle.

**Comment by hanneskuettner** [comment]
@erquhart I've got a question regarding this line which I tracked down to a commit from 2 years ago:

https://github.com/netlify/netlify-cms/blob/174d86f0a083a8c89e832962e3bdfe4163def428/packages/netlify-cms-core/src/components/Collection/Entries/EntryCard.js#L125

As far as I can tell (and the typescript types define) an Entry does not have a label. Is this obsolete?

**Comment by erquhart** [comment]
Folder collection entries don’t have labels but file collection entries do.

**Comment by hanneskuettner** [comment]
I see. But why are they not defined in the `Entry` type?

Should we move this discussion to Slack or should I open a PR and we can discuss it over there?

**Comment by erquhart** [comment]
A PR would be great - @erezrokah has a lot more context than I do in recent months, he can follow up with you there.

**Comment by hanneskuettner** [comment]
On a side note: File collection labels are actually broken in the current demo CMS that is online:

![image](https://user-images.githubusercontent.com/4376726/79008373-8e6e7500-7b5d-11ea-9c8c-1fb86e98cb9f.png)

**Comment by erezrokah** [comment]
> I see. But why are they not defined in the `Entry` type?

We've just started typing areas in the code, so some types might be missing.
Thanks for the PR, I'll try to finish reviewing it today.
