### ISSUE TITLE
netlify-cms@2.10.41,@2.10.42 yaml errors

### ISSUE THREAD

**Issue by zdenekdrahos** [netlify/netlify-cms#3574]
**Describe the bug**

config.yml stopped working at https://sokolmorasice.netlify.com

![Screenshot from 2020-04-10 18:11:03](https://user-images.githubusercontent.com/7994022/79005220-a989b680-7b56-11ea-9bc5-d17dd6c4fb9f.png)

**To Reproduce**

1. Go to https://sokolmorasice.netlify.com
2. See error at page, console...

**Expected behavior**

Login page

![Screenshot from 2020-04-10 18:10:11](https://user-images.githubusercontent.com/7994022/79005180-9aa30400-7b56-11ea-85b1-f5d3cd9e8c76.png)

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: netlify-cms 2.10.41, netlify-cms 2.10.42
 - Git provider: gitlab

**CMS configuration**

* https://gitlab.com/sokolmorasice/web/-/blob/master/source/admin/config.yml
* https://gitlab.com/sokolmorasice/web/-/blob/master/source/admin/index.html

**Additional context**

It works, if I use `<script src="https://unpkg.com/netlify-cms@2.10.40/dist/netlify-cms.js"></script>`. Other versions don't work. 

> 2.24.0
> yaml: support comments
> https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-core/CHANGELOG.md#2241-2020-04-09

**Comment by erquhart** [comment]
@erezrokah probably worth adding a test case or two for this.
