### ISSUE TITLE
Editor Component string fields cursor jumps to end of line after each keypress

### ISSUE THREAD

**Issue by kwyoung11** [netlify/netlify-cms#3578]
**Describe the bug**
In any Editor Component registered via CMS.registerEditorComponent(), the cursor in string fields jumps to the end of the line after every keypress, making it difficult to edit.

**To Reproduce**
1. Go to https://cms-demo.netlify.com/#/collections/posts/new
2. In the body (the markdown widget), click the '+' dropdown in the markdown toolbar and add a Youtube block
3. Add any text to the id field. Now place your cursor at the beginning of that text, and add a character.
4. See the cursor jump the end of the line.

**Expected behavior**
The cursor should not jump the end of the line when editing the text.

**Screenshots**
https://imgur.com/a/8JCbZgA

**Applicable Versions:**
 - Netlify CMS version: Since at least 2.10.32
 - Git provider: GitHub
 - OS: Mac OSX
 - Browser version Chrome 80.0.3987.149
 - Node.JS version: 12.x

**Comment by kwyoung11** [comment]
This bug was introduced in https://github.com/netlify/netlify-cms/pull/2828. Is it possible to get that branch restored so that I can pull it down locally? I want to try a git bisect on it to narrow down what caused it.

**Comment by erezrokah** [comment]
Hi @kwyoung11, thank you for looking into this. The restore branch option is no longer available. You could checkout the commit prior to that PR merge.

**Comment by sn3h** [comment]
Hello,

described behavior is happening again at Image widget text fields (alt and description). Cursor jumps to the end of the field after each keystroke

**Comment by idrisadetunmbi** [comment]
Getting this same behavior.

**Comment by 1alexvash** [comment]
@kwyoung11 Still recurring, it's embarrassing 😐

**Comment by wjh18** [comment]
I have a similar issue with the body content on every page. The cursor moves to the end of the element where content was changed. I do have a handful of custom shortcodes defined, but it happens even on pages without any. A few months ago it was working fine.

**Comment by tcbcn** [comment]
@1alexvash I have what appears to be the same problem, in the main CMS window. Happens in both Chrome and Safari. Is this the same bug or a different one, do you think?

**Comment by mz-mc** [comment]
Confirming this is still an issue, and that the fix mentioned by @tcbn works.

**Comment by crs1138** [comment]
Was this ever resolved?
