### ISSUE TITLE
Add ability for individual files to override preview setting in file collections

### ISSUE THREAD

**Issue by Pearce-Ropion** [netlify/netlify-cms#3581]
**Is your feature request related to a problem? Please describe.**

Currently, we can enable/disable the editor preview on a collection. However, this doesn't make much sense for `file` type collections where each file has a different configuration and might require a different preview. I would like to be able to override a collection's editor settings in an individual file's settings

**Describe the solution you'd like**

 I would like to be able to override a collection's editor settings in an individual file's settings. Please see the config snippet for the `pages` collection below.
```javascript
// cms.js
import AboutPagePreview from "templates/AboutPagePreview";
CMS.registerPreviewTemplate("about", AboutPagePreview);

// config
{
    label: "Pages",
    name: "pages",
    extension: "yml",
    editor: {
        preview: false,
    },
    files: [
        {
            label: "About",
            name: "about",
            file: "src/content/pages/about.yml",
            editor: {
                preview: true,
            },
            fields: [
                // some fields ...
            ],
        },
    ],
}
```
The above would disable the preview of the pages collection as a whole but enable the preview on the about page which would then be able to use the preview template specified when initializing the CMS.

**Describe alternatives you've considered**

You could make a new collection for the individual page that has a preview but there would only ever be one entry in the collection.

**Additional context**

**Comment by Pearce-Ropion** [comment]
@erezrokah Is there any progress on this? And if not, could you point me in the right direction within the repo so that I could attempt a PR myself? I had a look around but couldn't find where the `editor: { preview }` config option gets used.

**Comment by erezrokah** [comment]
Hi @Pearce-Ropion, I don't think anyone started working on this.
This https://github.com/netlify/netlify-cms/blob/6042383b9db696902f34636f12f44cbfea30562e/packages/netlify-cms-core/src/components/Editor/EditorInterface.js#L192 should be a good place to start.
You should be able to check if a collection has a `files` key and filter a specific file by using `entry.get('slug') === file.get('name')` (if I remember correctly).
