### ISSUE TITLE
Chore: add timeout mechanism to our fetch API calls

### ISSUE THREAD

**Issue by erezrokah** [netlify/netlify-cms#3605]
On some occasions fetch API calls can hang for quite some time before they fails.
We should implement a timeout mechanism around our fetch calls to fail faster.

See:
![image](https://user-images.githubusercontent.com/26760571/79312133-1e6a4100-7f07-11ea-885a-5b83799fa6ab.png)
 The last request took a couple of minutes to fail while showing nothing in the CMS UI.

**Comment by tinfoil-knight** [comment]
@erezrokah Can I try this issue?

**Comment by erezrokah** [comment]
> @erezrokah Can I try this issue?

Sure, thanks!

**Comment by tinfoil-knight** [comment]
@erezrokah Can you point me to the relevant files?

**Comment by erezrokah** [comment]
Most of our `fetch` API calls end up here:
https://github.com/netlify/netlify-cms/blob/72b26f4435b428f79805920566678627e60fffaa/packages/netlify-cms-lib-util/src/unsentRequest.js#L52
But there are some flows that don't like the one in the issue coming from:
https://github.com/netlify/netlify-cms/blob/72b26f4435b428f79805920566678627e60fffaa/packages/netlify-cms-backend-git-gateway/src/implementation.ts#L157
I recommend searching for `fetch(` in the repo.
Some calls are not relevant as they reference local resources like:
https://github.com/netlify/netlify-cms/blob/72b26f4435b428f79805920566678627e60fffaa/packages/netlify-cms-backend-test/src/implementation.ts#L308

**Comment by tinfoil-knight** [comment]
@erezrokah 
Since this needs to be done in multiple places(around 14), do I just write up the `AbortController` function in one place and import it or should I use it separately in each file?

If yes, what should be the location of the file?

**Comment by erezrokah** [comment]
I think you can do it in the `unsentRequest` file under `netlify-cms-lib-util`

**Comment by tinfoil-knight** [comment]
WIP #3649

**Comment by tinfoil-knight** [comment]
@erezrokah I tested the fetch abort for creating new posts. It's working. But I think I should add tests. Where do I add tests for checking this ?

**Comment by erezrokah** [comment]
@tinfoil-knight I commented on the PR, thanks

**Comment by tinfoil-knight** [comment]
@erezrokah Help needed.
The pre-defined tests are receiving an empty signal. I don't know how to fix the tests.
```js
github API › request › should fetch url with authorization header

    expect(jest.fn()).toHaveBeenCalledWith(...expected)

    - Expected
    + Received

      "https://site.netlify.com/.netlify/git/github/some-path",
      {"cache": "no-cache", "headers": {"Authorization": "Bearer token", "Content-Type": "application/json; charset=utf-8"}},
    + {"signal": {}},
```

**Comment by tinfoil-knight** [comment]
@erezrokah Help needed.
The pre-defined tests are receiving an empty signal. I don't know how to fix the tests.
```js
github API › request › should fetch url with authorization header

    expect(jest.fn()).toHaveBeenCalledWith(...expected)

    - Expected
    + Received

      "https://site.netlify.com/.netlify/git/github/some-path",
      {"cache": "no-cache", "headers": {"Authorization": "Bearer token", "Content-Type": "application/json; charset=utf-8"}},
    + {"signal": {}},
```
