### ISSUE TITLE
Impossible to create first entry of a collection with version >0.3.14

### ISSUE THREAD

**Issue by MarcCoet** [netlify/netlify-cms#361]
**- Do you want to request a *feature* or report a *bug*?**
bug
**- What is the current behavior?**
With netlify CMS versions from 0.3.15 to 0.3.17 hosted on unpkg.
On a fresh project, when accessing the netlify CMS interface the spinner stays on the screen even though there is no data to fetch.
When trying to create the first entry in a collection, the progress bar never reaches the end and no commit is triggered.
**- If the current behavior is a bug, please provide the steps to reproduce.**
I didn't get much time to test this through but I suspect this would happen on any fresh install...
**- What is the expected behavior?**
A message "no content yet" instead of the spinner.
Being able to create the first entry of a collection.
**- Please mention your node.js, and operating system version.**
Node 6 / Arch Linux

**Comment by josephearl** [comment]
Are there any errors in the JS console?

**Comment by MarcCoet** [comment]
Yep, sorry. After a deeper dive it does not seem to be related with the CMS version. I've got a couple issues still pending that I will follow in the relevant feeds. Thanks for the reply.
