### ISSUE TITLE
/admin not loading settings

### ISSUE THREAD

**Issue by jgudka** [netlify/netlify-cms#3610]
I had the gatsby netlify starter deployed and was able to make changes using netlify cms via the /admin endpoint both on the deployed site and locally.

Today when I tried to log into /admin again locally and without any changes on my end, I was shown the "Unable to access identity settings. When using git-gateway backend make sure to enable Identity service and Git Gateway." error message. Looking at Dev Tools the request to https://beht.netlify.com/.netlify/identity/settings fails straight away without a response.

When trying to access the admin page on my deployed version I get a similar issue of the request to "https://beht.netlify.app/.netlify/git/settings" timing out and I am stuck on the Login with Netlify Identity page.

Can't figure out what has gone on, as it was working the previous day.

Any Ideas?

**Comment by seanpatterson97** [comment]
Hey, I'm experiencing almost the same situation. I have a site based off the starter that I've been working on for a month or so. As of today, when I begin developing locally with gatsby I am shown the "Unable to access identity settings" screen when going to my admin panel.

The console also shows an error request to https://mysite.netlify.com/.netlify/identity/settings, but mine is a Cross Origin Request Block error. Haven't had any issues like this thus far.

The deployed version of my site, however is functioning normally as of now. I've successfully pushed updates from netlify cms to my github.

**Comment by erezrokah** [comment]
Thanks for reporting this @jgudka, looks like both `https://beht.netlify.com/.netlify/identity/settings` and `https://beht.netlify.app/.netlify/git/settings` return a valid response now.

@seanpatterson97 https://twitter.com/NetlifySupport/status/1250476140822593536 might be relevant.

**Comment by jgudka** [comment]
Yes thanks for your help! The deployed site now seems to work, perhaps was temporarily down?

And as for the local version, I needed to change the url to .app from .com as the twitter thread suggests. I know I got an email about this change of url of the deployed app, but maybe this change required for local dev should be highlighted too as others may have a similar issue.

**Comment by jarodpeachey** [comment]
@erezrokah I'm running into the same issue, but I'm using the .app url. Here's my API config:

```
  const auth = new GoTrue({
    APIUrl: 'http://trianglecomments.netlify.app/.netlify/identity',
    audience: '',
    setCookie: true
  });
```.

You can go to https://trianglecomments.netlify.app/signup and test it yourself. You should see some error messages inside the console on submit.

**Comment by erezrokah** [comment]
Hi @jarodpeachey, how are you using the CMS? Regardless I would use the `https://trianglecomments.netlify.app/.netlify/identity` (notice `https` instead of `http`).

**Comment by FloLaco** [comment]
I've the same issue right now : 
![image](https://user-images.githubusercontent.com/1486562/79984638-c2289380-84a9-11ea-802b-9c8e3b9830b9.png)

Easy step to reproduce : 
1. install a hugo (with academic) website with netlify in one click : https://app.netlify.com/start/deploy?repository=https://github.com/sourcethemes/academic-kickstart
2. activate Identity and Git Gateway in Netlify
3. go to GENERATED_NETLIFY_URL.netlify.app/admin/
4. Create an account (fake/alias is ok but still need to access to your email, you can use blabla@yopmail.com)
5. Activate your account (email received)
6. go to GENERATED_NETLIFY_URL.netlify.app/admin/
7. Get error to fetch settings (error are received few minutes later)

**Comment by erezrokah** [comment]
Hi @FloLaco, can you try to access that URL directly and not via the CMS? Does that work?

**Comment by FloLaco** [comment]
@erezrokah Now it's working ... But when i post my comment, no, i wasn't able to get access to that URL (timeout)
