### ISSUE TITLE
Login to admin panel - endless loop

### ISSUE THREAD

**Issue by Kotauror** [netlify/netlify-cms#3621]
**Describe the bug**
I've created a NetlifyCMS website for a GitHub organization. I've tried to log into the admin panel - was shown the login pop up window, after filling it in, I was shown the "Login with Netlify Identity" button. After clicking it nothing happened - no errors on the screen, none in the console, only a request in the network going on (looks like an endless loop).

Randomly, in some cases, around more than 5 minutes I get a "Failed to fetch" error shown on the screen. 

Logging in to the admin panel works locally. 

**To Reproduce**
1. Go to https://cranky-kepler-92ab85.netlify.app/admin/#/ and try to log in. 

**Expected behavior**
Logging in and seeing the admin panel. 

**Screenshots**
![ezgif com-video-to-gif (20)](https://user-images.githubusercontent.com/32749113/79598293-97ba8d00-80db-11ea-9f09-c49a448126cd.gif)

**Applicable Versions:**

 - Netlify CMS version: [netlify-cms-app 2.12.8]
 - Git provider: [e.g. GitHub]
 - OS: [OSX]
 - Browser version [e.g. chrome 80] (I've alaso checked Firefox - same problemn)

**CMS configuration**
backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Subheading, name: subheading, widget: string }
          - { label: Heading, name: heading, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Link, name: link, widget: string },
                        {
                          label: Clinic Name,
                          name: clinicName,
                          widget: string,
                        },
                        {
                          label: Rating,
                          name: rating,
                          widget: select,
                          options: ["green", "yellow", "red"],
                        },
                        { label: "Publish Date", name: "date", widget: "datetime" },
                        { label: Hospital description, name: hospitalDescription, widget: string },
                        { label: Additional information, name: additionalInformation, widget: text}
                      ],
                  },
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

**Comment by Kotauror** [comment]
Lol, I've fixed it by pushing an irrelevant update to the repository and then removing it.

**Comment by erezrokah** [comment]
Thanks for posting the solution! Closing the issue, can you re-open if it happens again and share the requests/responses for those `settings` requests?
