### ISSUE TITLE
Fix lint issues on master

### ISSUE THREAD

**Issue by josephearl** [netlify/netlify-cms#363]
**- Do you want to request a *feature* or report a *bug*?**

Bug. See #356 for original discussion.

**- What is the current behavior?**
**- If the current behavior is a bug, please provide the steps to reproduce.**

Execute `npm run lint` on master. Lint fails.

**- What is the expected behavior?**

Existing code passes lint rules. Lint passes.

**- Please mention your node.js, and operating system version.**

Node v7.8.0. macOS Sierra.

**Comment by josephearl** [comment]
From the discussion on #356.

> biilmann commented a day ago:
> I'm in favor of getting rid of those hooks completely. They feel very intrusive when doing many small in progress commits that you'll squash and cleanup later.
> I would also suggest customizing the eslint settings to make sure they match how the code of the CMS is currently formatted quite closely, so we can get all code to pass linting and then require passing linting before accepting pull requests. Then we can start gradually introducing stricter linting rules little by little, but making sure we make them all pass for each rule added.

**Comment by tech4him1** [comment]
What do you think about adding a system like `prettier` as well? This would eliminate minor formatting issues and ensure that our entire code-base is formatted consistently.

**Comment by erquhart** [comment]
@tech4him1 Prettier doesn't cover everything, but it does cover the annoying little things that we often ask contributors to fix in their PR's. We'll still need ESLint to cover the real stuff, as outlined in your link.

We can start with a PR to implement Prettier and go from there.

**Comment by tech4him1** [comment]
To do list to get everything cleaned up:

- [ ] Manual code fixes from linters:
  - https://github.com/netlify/netlify-cms/pull/1524
- [ ] Get rid of deprecated React code.
- [ ] Remove unused variables/imports.
- [ ] Set up for website code.
- [ ] Add React prop types everywhere?
- [ ] Style fixes (run Prettier).

I'll be taking this on as I have time, but if anyone has a specific item they would like to work on, let me know!
