### ISSUE TITLE
There is a Minified React error on preview panel 

### ISSUE THREAD

**Issue by veryfaraway** [netlify/netlify-cms#3637]
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=Sun%20Apr%2019%202020%2021%3A38%3A20%20GMT%2B0900%20(Korean%20Standard%20Time)&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.13.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 68.6.1
    Safari: 13.1
  npmPackages:
    gatsby: ^2.20.28 => 2.20.29
    gatsby-image: ^2.2.30 => 2.3.4
    gatsby-plugin-google-tagmanager: ^2.1.15 => 2.2.3
    gatsby-plugin-manifest: ^2.2.26 => 2.3.6
    gatsby-plugin-netlify: ^2.1.23 => 2.2.3
    gatsby-plugin-netlify-cms: ^4.2.4 => 4.2.4
    gatsby-plugin-nprogress: ^2.1.12 => 2.2.3
    gatsby-plugin-offline: ^3.0.17 => 3.1.4
    gatsby-plugin-postcss: ^2.2.3 => 2.2.3
    gatsby-plugin-react-helmet: ^3.2.4 => 3.2.4
    gatsby-plugin-sass: ^2.1.20 => 2.2.3
    gatsby-plugin-sharp: ^2.2.36 => 2.5.6
    gatsby-plugin-sitemap: ^2.2.19 => 2.3.5
    gatsby-remark-images: ^3.1.28 => 3.2.5
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0
    gatsby-remark-responsive-iframe: ^2.2.25 => 2.3.3
    gatsby-source-filesystem: ^2.1.35 => 2.2.4
    gatsby-transformer-remark: ^2.6.32 => 2.7.4
    gatsby-transformer-sharp: ^2.3.2 => 2.4.6
    gatsby-transformer-yaml: ^2.2.15 => 2.3.3
  npmGlobalPackages:
    gatsby-cli: 2.10.13

**CMS configuration**

https://github.com/veryfaraway/gatsby-yellowcake-blog3/blob/8ed0e7da178db35bfa577a759ea5de0233cb5251/static/admin/config.yml

**Additional context**

**Comment by erezrokah** [comment]
Thanks for sharing @veryfaraway, if you follow the link you can see that you need to convert the date object in your preview template to a string.
Can you share your repo/preview template code?

**Comment by veryfaraway** [comment]
> Thanks for sharing @veryfaraway, if you follow the link you can see that you need to convert the date object in your preview template to a string.
> Can you share your repo/preview template code?

Thanks for a quick reply. I'm a newbie, so could you tell me how can I find and share the code?
Here is my post source that the error occurs.
https://github.com/veryfaraway/gatsby-yellowcake-blog3/blob/master/content/posts/2020-04-19-iron-man-2008-쿠키-영상.md

**Comment by erezrokah** [comment]
Not sure but maybe here https://github.com/veryfaraway/gatsby-yellowcake-blog3/blob/master/src/templates/SinglePost.js#L36

**Comment by veryfaraway** [comment]
@erezrokah 
That code doesn't seem to be a problem. Published posts can be seen well without problems. (https://3buddies.netlify.app/posts/iron-man-2008-%EC%BF%A0%ED%82%A4-%EC%98%81%EC%83%81/)
![image](https://user-images.githubusercontent.com/21246078/79935691-80d7ba00-8490-11ea-9287-47d41672e9b6.png)

The error occurs in the preview panel when writing a new post in the admin UI.
![image](https://user-images.githubusercontent.com/21246078/79936070-6baf5b00-8491-11ea-9886-5ed7737c8885.png)

Do you have any idea?

**Comment by erezrokah** [comment]
By default the CMS will return a date object when working with the date widget.
You are passing the CMS data as is (meaning the date as an object) here:
https://github.com/veryfaraway/gatsby-yellowcake-blog3/blob/8ed0e7da178db35bfa577a759ea5de0233cb5251/src/cms/cms.js#L42
so new posts break.
For existing posts it looks like they were saved with the dates as strings. For example:
https://github.com/veryfaraway/gatsby-yellowcake-blog3/blame/master/content/posts/2018-05-25-testing-1-8-2.md#L5
except this post which was saved with a full date and also has the preview broken:
https://github.com/veryfaraway/gatsby-yellowcake-blog3/blame/master/content/posts/2018-05-25-testing-1-8-2.md#L5.

You can save the dates as strings by configuring `- { label: Date / Order, name: date, widget: date, format: 'YYYY-MM-DD' }` here:
https://github.com/veryfaraway/gatsby-yellowcake-blog3/blob/8ed0e7da178db35bfa577a759ea5de0233cb5251/static/admin/config.yml#L297

The most important thing is to save the dates in a consistent format (dates or strings) so you can easiliy process them later.
