### ISSUE TITLE
Unable to select image for posts in Safari for iPad on 2.10.46

### ISSUE THREAD

**Issue by webjamco** [netlify/netlify-cms#3639]
As the title suggests, after the release of 2.10.46 I can’t choose the image after uploading it on iPad. Works fine on Chrome.

**Comment by erezrokah** [comment]
Just to confirm, is the issue you're having is this:
![image](https://user-images.githubusercontent.com/26760571/79841970-db094a00-83c0-11ea-97fb-37380d25da53.png)

That is, the "choose select" is hidden by the images on the iPad?

**Comment by webjamco** [comment]
That too. After 4 images the “Choose Select” gets hidden under the images, but even if it’s visible is not clickable.

**Comment by tinfoil-knight** [comment]
@erezrokah We can either replace the text with icons or create a new row below the search for the buttons. Can I claim the issue?

**Comment by erezrokah** [comment]
Thanks a lot @tinfoil-knight, I assigned you to the issue 😄

**Comment by tinfoil-knight** [comment]
@erezrokah I was trying to work on the package but the repo is not starting. I tried `yarn develop` and `yarn start` and both scripts pause at the following log:

```bash
netlify-cms:  warning  in .-widget-code/dist/esm/CodeControl.js
netlify-cms: Critical dependency: the request of a dependency is an expression
netlify-cms:  WAIT  Compiling...5:05:21 PM
netlify-cms:  WARNING  Compiled with 1 warnings5:05:22 PM
netlify-cms:  warning  in .-widget-code/dist/esm/CodeControl.js
netlify-cms: Critical dependency: the request of a dependency is an expression
```

These issues usually pop up after dependency changes.

**Comment by erezrokah** [comment]
Can pull latest the latest master and run `yarn install` again? I also get this warning but able to use `yarn start`.

**Comment by erezrokah** [comment]
Related https://github.com/netlify/netlify-cms/issues/3701

**Comment by tinfoil-knight** [comment]
@erezrokah Since all the `MediaLibraryActions` are in the same file, I think it would be best if we just place all of them in a line below the search bar. What do you think?

**Comment by erezrokah** [comment]
How about we auto shrink the search bar? Maybe that would be easier to implement?

**Comment by tinfoil-knight** [comment]
WIP: #3784
