### ISSUE TITLE
with gatsby-plugin-netlify-cms cannot use staticQuery inside preview

### ISSUE THREAD

**Issue by PetroPavlenko** [netlify/netlify-cms#3641]
Hi all I want to use staticQuery in component that is rendered in preview.
Is it possible ?

For admin that work in build. but doesn't work in development
Page works in both.

I tried to implement [this](https://github.com/gatsbyjs/gatsby/issues/7747) fix. But looks like reason is different And do something like [CSS-in-JS](https://github.com/netlify/netlify-cms/issues/793).
But don't know what to include. 
Any ideas ?

**Comment by erezrokah** [comment]
Closing per https://github.com/netlify/netlify-cms/issues/4004#issuecomment-657224347
