### ISSUE TITLE
[doc] gatsby/#get-to-know-gatsby needs update

### ISSUE THREAD

**Issue by Ir1d** [netlify/netlify-cms#3666]
On https://www.netlifycms.org/docs/gatsby/#get-to-know-gatsby
It said 
![image](https://user-images.githubusercontent.com/10709657/80348321-32ffef00-88a0-11ea-8758-84ca8bd4904a.png)
However #1472 is fixed already.

@erezrokah mentioned that
> also require updating the config.yml yaml to support the starter directory structure

**Comment by lilpolymath** [comment]
I will work on this.
