### ISSUE TITLE
sortableFields not sorting MONTH and YEAR

### ISSUE THREAD

**Issue by menttys** [netlify/netlify-cms#3667]
**Describe the bug**
Sorting the fields by date using `sortableFields` it is only filtering the 
`weekday` and `month day` ignoring the rest of the `TIMESTAMP`.

`ddd, dd MMM yyyy HH:mm:ss K`

**To Reproduce**
Create multiple `*.md` with a `date field` with the timestamp type as mentioned above
and setting `sortableFields: ['date']`

**Expected behavior**
Expect ordering the field accordingly with the timestamp.

**Screenshots**
![Screenshot 2020-04-27 at 11 03 41](https://user-images.githubusercontent.com/11960601/80360133-c7edf280-8876-11ea-9d89-8fde403308ed.png)
![Screenshot 2020-04-27 at 10 06 21](https://user-images.githubusercontent.com/11960601/80360151-cde3d380-8876-11ea-84ea-5aae4f17a910.png)
![Screenshot 2020-04-27 at 10 18 23](https://user-images.githubusercontent.com/11960601/80360161-d0462d80-8876-11ea-966e-e803e8fe4df4.png)
![Screenshot 2020-04-27 at 10 18 45](https://user-images.githubusercontent.com/11960601/80360166-d20ff100-8876-11ea-814c-6565532575c8.png)

**Applicable Versions:**

 - Netlify CMS version: 2.10.47
 - Git provider: GitHub
 - OS: macOs Mojave
 - Browser version chrome 81.0

 - Node.JS version: v12.4

**CMS configuration**

```media_folder: static/images
public_folder: '/images'
publish_mode: editorial_workflow

collections:
  - name: 'blog' # Used in routes, ie.: /admin/collections/:slug/edit
    identifier_field: name
    label: 'Blog' # Used in the UI
    label_singular: Blog Post # Used in the UI, ie: "New Post"
    slug: '{{title}}{{year}}-{{month}}-{{day}}_{{slug}}'
    description: >
      ...
    folder: src/pages/blog/
    preview_path: blog/{{slug}}
    create: true # Allow users to create new documents in this collection
    publish_mode: false
    fields: # The fields each document in this collection have
      - label: Featured
        name: featured
        hint: Toggle on to label this article as featured.
        widget: boolean
        default: false
        required: false
      - label: 'Category'
        name: 'category'
        hint: Select the category you wish to classify the article
        widget: select
        options: ['Innovation', 'Insight', 'Marketing', 'Tech', 'Work/Life']
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        hint: 'To schedule an article to be published you must select a date and time in the future for when you want the article to be available. NOTE: The article must still be published and will only be made available after the date and time specified'
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Description', name: 'description', widget: 'text', required: false }
      - { label: 'Author', name: 'author', widget: 'string', default: 'TotallyMoney' }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
      - label: 'Page Settings'
        name: 'settings'
        widget: 'object'
        fields:
          - { name: 'slug', label: 'Slug', widget: 'string', required: false }
          - { name: 'title', label: 'Title', widget: 'string', required: false }
          - { name: 'description', label: 'Description', widget: 'string', required: false }
          - name: 'opengraph'
            label: 'Open Graph'
            widget: 'object'
            required: false
            fields:
              - { name: 'type', label: 'Type', widget: 'string', required: false }
              - { name: 'image', label: 'Image', widget: 'image', required: false }
    summary: '{{title}}  {{day}}-{{month}}-{{year}}'
    sortableFields: ['date', 'title']```

**Comment by erezrokah** [comment]
Hi @menttys, thank you for reporting this. I tried creating a new entry with your config file and the date is saved in the following format: `date: 2020-04-27T10:47:55.773Z`.
Are the existing files were created by the CMS?
I think if you store the the date value in a yaml [timestamp format](https://yaml.org/type/timestamp.html) the sort should work as expected.
Another option is for the CMS to support extending yaml types to parse that specific format as a date and not as a string.

**Comment by menttys** [comment]
Hi Erez, indeed these files are imported and converted from an `old cms`  I presumed it would parse from a valid `timestamp` format. I will convert and test. 

thanks a lot!
