### ISSUE TITLE
Validation Error When Using Only Relative Media Directories

### ISSUE THREAD

**Issue by Undistraction** [netlify/netlify-cms#3670]
**Describe the bug**
The beta docs [here](https://www.netlifycms.org/docs/beta-features/#folder-collections-media-and-public-folder) outline how collection-specific `media_folder` keys can allow you to use relative paths. This effectively removes the need for a global `media_folder` key. However it appears this is still being validated as a required key. 

> Error loading the CMS configuration
> Config Errors:
> config should have required property 'media_folder'
> config should have required property 'media_library'
> config should match some schema in anyOf
> Check your config.yml **file.**

I think there might be some kind of conflict between local and global dirs causing the bug I have outlined in #3654 which is why I removed the global dir.

**To Reproduce**

**Expected behavior**
No validation error. 

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: netlify-cms-app@2.12.11
 - Git provider: Gitlab self-hosted
 - OS: OSX
 - Browser version Version 81.0.4044.122 (Official Build) (64-bit)

**Comment by erezrokah** [comment]
Hi @Undistraction, the global `media_folder` is required for collections that don't have `media_folder` specified and also since you can use templates to refer to refer to the global one, e.g. under a collection you can specify `media_folder: {{media_folder}}/posts_images` (this is not document yet though).

**Comment by Undistraction** [comment]
@erezrokah Thanks for the explanation. That's a nice feature (being able to organise images within a central media directory). 

I know that relative media directories are only a beta feature but would be great to add something to the docs highlighting that a global for is still required in the config even of you aren't using it.

**Comment by erezrokah** [comment]
Good point @Undistraction, we've recently added the media folder templating and field based media folders. It is not even documented yet since we want to gradually gain confident with the current approach and get more use cases.
Closing this issue, as will open a new one to improve the docs.

**Comment by erezrokah** [comment]
Opened https://github.com/netlify/netlify-cms/issues/3671, please share your thoughts there and let me know if I missed something.
