### ISSUE TITLE
Override slug in frontmatter

### ISSUE THREAD

**Issue by Buzut** [netlify/netlify-cms#3688]
By default, the slug is generated based on the title and can be configured to [a custom string](https://www.netlifycms.org/docs/configuration-options#slug) or to refer to [another element than title](https://www.netlifycms.org/docs/configuration-options#identifier_field).

What would be really convenient is a way to set up a custom slug via frontmatter, but to default to the title generated one if `fields.slug` isn't defined.

**Comment by hanneskuettner** [comment]
Just to clarify. Isn't this a duplicate of #445?

**Comment by Buzut** [comment]
@hanneskuettner you're right. I had missed it, thank you for pointing it out!
