### ISSUE TITLE
How to define Page Path for Single Blog Post

### ISSUE THREAD

**Issue by emmadigital** [netlify/netlify-cms#3698]
I can see path field inside pages For example in About page we have below line of code to define path:/about so the Url becomes:  domain.com/about
templateKey: 'about-page'
path: /about
title: About our values
----------------------------------------------------------------------------------------------------------

But when I check blog page I don't find path field there, and currently the Url is : **domain.com/blog/blog-name**, I want to shorten this url and change it to **domain.com/blog-name** please advise how should I do this?

templateKey: blog-post
title: A beginners’ guide to brewing with Chemex
date: 2017-01-04T15:04:10.000Z
featuredpost: false

**Comment by erezrokah** [comment]
Hi @emmadigital, can you please follow the issue template? This seems more of a Gatsby related question, but it is hard to confirm. If you are using the Gatsby starter this might be a good place to start https://github.com/netlify-templates/gatsby-starter-netlify-cms/blob/d06c3844eb46daafd46fb348422afa8e5317e06e/gatsby-node.js#L34

**Comment by emmadigital** [comment]
> Hi @emmadigital, can you please follow the issue template? This seems more of a Gatsby related question, but it is hard to confirm. If you are using the Gatsby starter this might be a good place to start https://github.com/netlify-templates/gatsby-starter-netlify-cms/blob/d06c3844eb46daafd46fb348422afa8e5317e06e/gatsby-node.js#L34

@erezrokah Thank you for your response. 

How should I change the path here? 

```
posts.forEach((edge) => {
      const id = edge.node.id
      createPage({
        path: edge.node.fields.slug,
        tags: edge.node.frontmatter.tags,
        component: path.resolve(
          `src/templates/${String(edge.node.frontmatter.templateKey)}.js`
        ),
        // additional data can be passed via context
        context: {
          id,
        },
      })
    })

```
Normally gatsby-node.js file have below line of code
```
path: `/blogs${edge.node.link}`, 
//and I can change it to below line
path: `${edge.node.link}`,
```
But here I couldn't figure it out if change anything I get error. Can you please guide what to change here.

**Comment by barthc** [comment]
@emmadigital  add a `path` attribute to the frontmatter of your blog files. For example:
```
templateKey: blog-post
title: A beginners’ guide to brewing with Chemex
date: 2017-01-04T15:04:10.000Z
featuredpost: false
path: 2017-01-04-a-beginners-guide-to-brewing-with-chemex
```
And then modify this [line](https://github.com/netlify-templates/gatsby-starter-netlify-cms/blob/master/gatsby-node.js#L80) to this 
```js
const value = node.frontmatter.path || createFilePath({ node, getNode })
```
After both changes, rebuild the site and the blog url should be shortened.

**Comment by emmadigital** [comment]
> @emmadigital add a `path` attribute to the frontmatter of your blog files. For example:
> 
> ```
> templateKey: blog-post
> title: A beginners’ guide to brewing with Chemex
> date: 2017-01-04T15:04:10.000Z
> featuredpost: false
> path: 2017-01-04-a-beginners-guide-to-brewing-with-chemex
> ```
> 
> And then modify this [line](https://github.com/netlify-templates/gatsby-starter-netlify-cms/blob/master/gatsby-node.js#L80) to this
> 
> ```js
> const value = node.frontmatter.path || createFilePath({ node, getNode })
> ```
> 
> After both changes, rebuild the site and the blog url should be shortened.

 Thanks a lot! @barthc  the above method fixed my issue.

**Comment by barthc** [comment]
> When I add new posts from Netlify CMS will this automatically add the path field to each post or I have to do it manually every time I have total 1500 posts.

Yes, you would have to manually add the path field via the CMS. This approach gives the flexibility to adjust the slug as you see fit instead of relying on filename for the slug. But if you want to automatically use the filename as slugs, You can again switch this [line](https://github.com/netlify-templates/gatsby-starter-netlify-cms/blob/master/gatsby-node.js#L80) to this:

```js
const blogPath = '/blog';
let value = createFilePath({ node, getNode });
value.startsWith(blogPath) && (value = value.replace(blogPath, ''));
```
No need to add the path attribute in the frontmatter.

**Comment by emmadigital** [comment]
> > When I add new posts from Netlify CMS will this automatically add the path field to each post or I have to do it manually every time I have total 1500 posts.
> 
> Yes, you would have to manually add the path field via the CMS. This approach gives the flexibility to adjust the slug as you see fit instead of relying on filename for the slug. But if you want to automatically use the filename as slugs, You can again switch this [line](https://github.com/netlify-templates/gatsby-starter-netlify-cms/blob/master/gatsby-node.js#L80) to this:
> 
> ```js
> const blogPath = '/blog';
> let value = createFilePath({ node, getNode });
> value.startsWith(blogPath) && (value = value.replace(blogPath, ''));
> ```
> 
> No need to add the path attribute in the frontmatter.

I don't want the dates on urls just the post title. To manually add the path field via the CMS do I have to add below line under Blog collection inside config.yml ?

     - label: Path
        name: path
        widget: hidden

If the path is diferent then the file name will it work? Or should I remove dates from the slug field to avoid any confusion.

**Comment by emmadigital** [comment]
I am getting build error everytime I create a blog post in CMS https://prnt.sc/saz1bp

**Comment by barthc** [comment]
> I am getting build error everytime I create a blog post in CMS https://prnt.sc/saz1bp

The `templateKey` value `category` you are using [here](https://github.com/emmadigital/ardalis-newsite/blob/master/static/admin/config.yml#L492) does not exist, Why not use the default `blog-post`  https://github.com/emmadigital/ardalis-newsite/blob/master/static/admin/config.yml#L23

**Comment by emmadigital** [comment]
> > I am getting build error everytime I create a blog post in CMS https://prnt.sc/saz1bp
> 
> The `templateKey` value `category` you are using [here](https://github.com/emmadigital/ardalis-newsite/blob/master/static/admin/config.yml#L492) does not exist, Why not use the default `blog-post` https://github.com/emmadigital/ardalis-newsite/blob/master/static/admin/config.yml#L23

I update the templateKey to default blog-post. Its working now.

How should I make it work to list posts of specific category https://ardalis.netlify.app/category/personal

**Comment by barthc** [comment]
>I add some category using CMS and it again threw build error, probably the same reason as template what template should I use for category? https://prnt.sc/sazmgc

`templateKey` hidden field is missing for that collection here https://github.com/emmadigital/ardalis-newsite/blob/master/static/admin/config.yml#L411-L425

>How should I make it work to list posts of specific category:
https://ardalis.netlify.app/category/personal

It's more of a gatsby question, as it will require written some `graphql` not sure, I suggest you ask in their forum.

**Comment by emmadigital** [comment]
> > I add some category using CMS and it again threw build error, probably the same reason as template what template should I use for category? https://prnt.sc/sazmgc
> 
> `templateKey` hidden field is missing for that collection here https://github.com/emmadigital/ardalis-newsite/blob/master/static/admin/config.yml#L411-L425
> 
> > How should I make it work to list posts of specific category:
> > https://ardalis.netlify.app/category/personal
> 
> It's more of a gatsby question, as it will require written some `graphql` not sure, I suggest you ask in their forum.

How should I manage category inside CMS. It defines Category as a separate collection and  Other categories [personal, productivity, security etc..] as a separate collection. First I have to structure my categories in CMS then I can work on gatsby part. It should be structured as:
-Category
   -Personal
   -Productivity
   -Security
   -etc

**Comment by barthc** [comment]
> It defines Category as a separate collection and Other categories [personal, productivity, security etc..] as a separate collection.

If your category is defined as a separate collection, then used the `relation` widget to pull values from the category collection. And also use the multiple flag `multiple: true`

**Comment by erezrokah** [comment]
This issue seems to have diverged into https://github.com/netlify-templates/gatsby-starter-netlify-cms/issues/565.
Closing in favour of that issue.
