### ISSUE TITLE
CMS Configuration Error

### ISSUE THREAD

**Issue by emmadigital** [netlify/netlify-cms#3700]
I recieve below error when I try to access Netlify CMS Content Manager

Error loading the CMS configuration
Config Errors:
YAMLSyntaxError: Document is not valid YAML (bad indentation?) at line 68, column 1:

- name: "categories"
^^^^^^^^^^^^^^^^^^^^…
Check your config.yml file.

I also used this builder https://netlify-config-builder.marcossi.com/ to fix config.yml file and updated my repro https://github.com/emmadigital/ardalis-newsite/blob/master/static/admin/config.yml the error points out to line no 68 but it doesn't match the line 68 on my repro. Is there any cache issue why CMS is not updating

**Comment by erezrokah** [comment]
Hi @emmadigital, can you make sure your site finished building and published the latest version of your master branch?
Looks like https://ardalis.netlify.app/admin/#/ still loads the old version

**Comment by emmadigital** [comment]
> Hi @emmadigital, can you make sure your site finished building and published the latest version of your master branch?
> Looks like https://ardalis.netlify.app/admin/#/ still loads the old version

Sorry, I just updated the Github repo but haven't published the site from Netlify I thought it will update Netlify CMS automatically when I update the repo but I think I need to publish before I can see any updates. 

Thanks for resolving my issue.
