### ISSUE TITLE
Custom Widget for twitter feed

### ISSUE THREAD

**Issue by emmadigital** [netlify/netlify-cms#3705]
I want to embed twitter feed in Netlify CMS blog post. I am using this gatsby plugin https://www.gatsbyjs.org/packages/gatsby-plugin-twitter/?=twitter and its working when I test locally on one of the markdown file. Now I want to register a netlify cms custom widget so that I can embed twitter feed from the content manager. 

I went through the documentation https://www.netlifycms.org/docs/custom-widgets/#header but couldn't figure out where do I need to add these code in which file do i need to add these codes. please advise. I have used twitter in place of name as that I want to name my widget.

```
// Using global window object
CMS.registerWidget(twitter, control, [preview]);

// Using npm module import
import CMS from 'netlify-cms';
CMS.registerWidget(twitter, control, [preview]);
```

**Comment by smashercosmo** [comment]
Hey @emmadigital that's not an appropriate place to ask such kind of questions. Github issues are supposed to be used for bug reports and feature requests, not for usage questions. Usage questions bloat issues list and distract maintainers. I would advise you to use https://stackoverflow.com/. This site was created specifically for that kind of questions.

**Comment by emmadigital** [comment]
@smashercosmo Stackoverflow is not Netlify CMS community. I want assistance from Netlify CMS team directly as I don't see any community forum or support forum on their website So I had post my queries here If I find difficulty in their documentation. Its Netlify CMS responsiblity to provide a support for its product. Not the stackoverflow. I don't find dedicated team of Netlify CMS in stackoverflow.com where I can ask my queries.

**Comment by erezrokah** [comment]
Hi @emmadigital, posting the same question in multiple places doesn't encourage community members to respond.
As I mentioned here https://netlifycms.slack.com/archives/CPRR0PQ9E/p1588663126379000?thread_ts=1588662926.378900&cid=CPRR0PQ9E you can try using a custom editor component:
https://www.netlifycms.org/docs/custom-widgets/#registereditorcomponent
For custom widgets you can also use https://github.com/netlify/netlify-cms-widget-starter.
Regardless, when opening an issue you should follow the issue template, even for bugs in the documentation. For example detail the steps from the docs you performed, the expected outcome and the actual outcome.
Closing this, and you can ask further questions in the slack thread you initiated.
