### ISSUE TITLE
no content & no images displayed/saveable

### ISSUE THREAD

**Issue by matthiasprieth** [netlify/netlify-cms#3707]
Sorry that I don't have a full bug report in this ticket. I just wanted to ask a general question, before I do a full report.

I tried to use netlify-cms locally today & wanted to test the "CMS" part of it without a GIT connection.
I followed this tutorial: https://www.netlifycms.org/docs/nextjs/

I skipped the "Creating a new project" part & did the "Adding Netlify CMS" part of the tutorial as a I had my next.js blog with all the .md files already from a previous project.

So I added the backend configuration in the `config.yml` file & also made sure that the repo is set to `name: test-repo` for local development.

**I was confused: None of the content pages are being displayed in the CMS, none of my images are being displayed. When I create a new page or add an image it's displayed in the CMS after saving/releasing, but when i refresh the page, all is gone. It seems like it does not create pages/images in my project folder but instead just adds them to the  local state/storage or something**

Do I need a GIT connection to make this work, is this a bug or is this not supported without a GIT connection?

**Comment by erezrokah** [comment]
Hi @matthiasprieth, see https://www.netlifycms.org/docs/test-backend/. I think https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository is what you're looking for.

**Comment by matthiasprieth** [comment]
Hi @erezrokah thanks so much for the quick reply & for pointing me to the right direction. Now it works! 👍 

Based on the nextjs tutorials/docs I didn't understand at all that this is a necessary step to make things work locally. Also I didn't find it at all. I understand that this is a beta feature, but would be cool to include this in the tutorials/Backend Test docs. As someone who tries this for the first time, it's very irritating that a basic cms functionality like show/edit/delete does not work & no errors are being thrown.

**Comment by erezrokah** [comment]
Thanks for the feedback @matthiasprieth, we would gladly accept a PR for it 😄. Closing the issue. Please comment/re-open if still relevant.
