### ISSUE TITLE
Losing spaces when pasting rich text into markdown field

### ISSUE THREAD

**Issue by jeremyzilar** [netlify/netlify-cms#3727]
When copying and pasting rich text with formatting into the 'markdown' widget, spaces get lost around formatted words.

**Example:**
If we copy rich text from [a page](https://www.eventbrite.com/e/the-new-social-environment-40-paul-soulellis-tickets-104539552616)

> **Join us at 1pm ET** for lunch a live conversation over ZOOM with special guest **Paul Soulellis** and host **Megan N. Liberty** to discuss creative life in the context of our new social reality. This gathering will conclude with a poetry reading by a member of our staff.

and paste it into a 'markdown' widget in NetlifyCMS _(in the rich text view)_, we get:

> **Join us at 1pm ET**for lunch a live conversation over ZOOM with special guest**Paul Soulellis**and host**Megan N. Liberty**to discuss creative life in the context of our new social reality. This gathering will conclude with a poetry reading by a member of our staff.

👆Note the missing spaces in `special guest**Paul Soulellis**and host**Megan N. Liberty**to discuss`.

![image](https://user-images.githubusercontent.com/395641/81484342-ca573180-9212-11ea-8a53-4c08d9683227.png)

Same things happening when copying and pasting from any rich text web page. Spaces seem to go missing on either side of `links`, `italicized text`, `bold text`.

**Comment by freshyill** [comment]
I experience this as well.

**Comment by jamgit** [comment]
This is a consistent, and time consuming, issue when pasting from Google Doc or other page or document. As others say, after links, em-dash, bold and italic text, etc.

**Comment by erezrokah** [comment]
Linking https://github.com/rehypejs/rehype-minify/issues/19 for context

**Comment by erezrokah** [comment]
FYI, a fix was released but it requires an additional fix to work https://github.com/rehypejs/rehype-minify/issues/19#issuecomment-638730080
