### ISSUE TITLE
Full width image in 1 column post

### ISSUE THREAD

**Issue by eduayme** [netlify/netlify-cms#3728]
**Describe the solution you'd like**
I would love to have an option to be able to add a full width image in the middle of a post.

**Additional context**
How it looks now:
<img width="1440" alt="Screenshot 2020-05-10 at 00 29 57" src="https://user-images.githubusercontent.com/26260104/81486534-a537e280-9255-11ea-854e-4f6a51f997e7.png">

What I would like:
<img width="1440" alt="Screenshot 2020-05-10 at 00 30 23" src="https://user-images.githubusercontent.com/26260104/81486542-b1bc3b00-9255-11ea-9c8a-1cb2b1156d3b.png">

**Comment by jeremyzilar** [comment]
@eduayme is this for NetlifyCMS, or the front-end of your site?
