### ISSUE TITLE
Error occurs when trying to publish a post that contains a date-like string

### ISSUE THREAD

**Issue by semigura** [netlify/netlify-cms#3737]
**Describe the bug**
When the string widget contains a string in the format of `YYYY-MM-DD`, the following error occurs when I try to Publish and I cannot publish.

```
Objects are not valid as a React child (found: Mon May 11 2020 09:00:00 GMT+0900 (日本標準時)). If you meant to render a collection of children, use an array instead.
```

I expected the strings contained in the string widget to be treated as strings.
However, if you put a date-like string in the string widget, it will appear to be treated as a date.

**To Reproduce**
1. Input the string in the string widget in the format of `YYYY-MM-DD`.
2. Save or Publish

**Expected behavior**
Successfully published

**Screenshots**
After reproduce 1:
(string widget is `URL`)
<img width="1440" alt="スクリーンショット 2020-05-11 19 34 10" src="https://user-images.githubusercontent.com/37991437/81552665-da137900-93be-11ea-913c-35f947ed43a4.png">

After reproduce 2:
(The inside of the red frame has changed automatically)
<img width="1439" alt="スクリーンショット 2020-05-11 19 32 53" src="https://user-images.githubusercontent.com/37991437/81552662-d67ff200-93be-11ea-8051-b3379dab5e5f.png">

**Applicable Versions:**
 - Netlify CMS version: 2.24.1
 - Git provider: GitHub
 - OS: macOS Mojave 10.14.6
 - Browser version: Chrome 80.0.3987.163
 - Node.JS version: v10.13.0

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: 'news'
    label: 'News'
    folder: 'src/pages/news'
    create: true
    slug: '{{fields.slug}}'
    fields:
      - {
          label: 'Template type',
          name: 'type',
          widget: 'hidden',
          default: 'news',
        }
      - { label: 'Publish date', name: 'date', widget: 'datetime' }
      - label: 'URL'
        name: 'slug'
        widget: 'string'
        default: ''
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Description',
          name: 'description',
          widget: 'text',
          required: false,
        }
      - {
          label: 'OGP Thumbnail',
          name: 'ogpThumbnail',
          widget: 'image',
          required: false,
          default: '',
        }
      - {
          label: 'Show Contact Form',
          name: 'showContactForm',
          widget: 'boolean',
          default: false,
      }
      - { label: 'Body', name: 'body', widget: 'markdown' }
```

**Comment by erezrokah** [comment]
Hi @semigura, that error is coming from the custom preview template and not the CMS code.
Can you share your repo?

**Comment by semigura** [comment]
@erezrokah 
I'm sorry, it's hard to share it right away.
I haven't set a custom preview template in my environment, but it uses the default preview template.

**Comment by taskooh** [comment]
I've tried many patterns, but none of them works for me.
this is my repo.
https://github.com/staketechnologies/HP-2020

```
Existing Md
date: 2020-03-08

config.yml
format: "YYYY-MM-DD"
```
"Objects are not valid as a React child (found: Fri May 08 2020 09:00:00 GMT+0900 (日本標準時)). If you meant to render a collection of children, use an array instead." Error while opening existing md.

```
Existing Md
date: '2020-03-08'

config.yml
format: 'YYYY-MM-DD'
```
Able to open existing md in cms
But created new post md will be like `date: 2020-03-08` without single quotation, and cannot open new md.


```
existiong Md 
date: "2020-03-08"

config.yml
format: "'YYYY-MM-DD'"
```

Able to open existing md in cms
But created new post md will be like `date:  "'2020-03-08'"` with single quotation wrapped with double quotation.

Im fining the way to create md by only single quotation.

**Comment by taskooh** [comment]
https://github.com/netlify/netlify-cms/issues/2455
This issue looks related, but it wasn’t a solution for me

**Comment by vrabe** [comment]
I think it relates to #3569 . It makes a date-like string parsed into Date object.

**Comment by vrabe** [comment]
It relates to #3569 and #3567. It parse `YYYY-MM-DD` or date-like string into `Date` object.

**Comment by erezrokah** [comment]
Can we close this since https://github.com/netlify/netlify-cms/pull/3923 was merged?
