### ISSUE TITLE
"Expected [K, V] tuple" when initialising config via JS

### ISSUE THREAD

**Issue by marcwieland95** [netlify/netlify-cms#3743]
**Describe the bug**
When initializing the config via the JavaScript objects Netlify throws an error on load. It doesn't break but immutable.js throws an exception.

**To Reproduce**
1. `CMS.init` within `cms.js`
2. Add any minimal setup object
3. Run NetlifyCMS via `gatsby develop`

**Expected behavior**
`Uncaught (in promise) TypeError: Expected [K, V] tuple: <` : immutable.js:3575

**Screenshots**
<img width="924" alt="Screenshot 2020-05-12 10 22 03" src="https://user-images.githubusercontent.com/6168975/81660441-0d93e900-943b-11ea-94e2-15b18d9b2363.png">

**Applicable Versions:**
 - Netlify CMS version: 2.12.12
 - Git provider: Local
 - OS: MacOS
 - Browser version: Chrome, Firefox
 - Node.JS version: v11.4.0

**CMS configuration**
None. Init via JS

**Comment by erezrokah** [comment]
Hi @marcwieland95, can you please share your `cms.js` file?

**Comment by reimertz** [comment]
I got this issue too till I realized is because 

1. There was no `config.yml` present
2. I needed to add  `load_config_file: false` to my config
3. I had to add ` window.CMS_MANUAL_INIT = true;`

**Comment by marcwieland95** [comment]
Yeah. Those settings are set. The `config.yml` doesn't need to exist since we're turning it off with the setting above.

I noticed that there's an option inside the `gatsby-config.js` which needs to be set and I haven't found it inside the documentation. -> `manualInit: true`

```
{
      resolve: 'gatsby-plugin-netlify-cms',
      options: {
            manualInit: true,
            modulePath: `${__dirname}/src/cms/cms.js`,
      },
},
```

After that, the error is gone.
