### ISSUE TITLE
pattern validation triggered by input event

### ISSUE THREAD

**Issue by magomimmo** [netlify/netlify-cms#3744]
**Is your feature request related to a problem? Please describe.**

The validation of the `pattern` regexp eventually attached to a string field is currently triggered when the user save an entry. 

**Describe the solution you'd like**

 It would be nice to trigger the regexp validation by `onchange` or `oninput` events 

**Describe alternatives you've considered**

Define a custom widget 

**Additional context**

It seems to me that the triggering of the regexp validation eventually attached to `string` widget will improve a lot the user experience, specially if she's filling a complex or long form.

**Comment by BA1RY** [comment]
@magomimmo @erezrokah I would like to work on this. How can I get started?

**Comment by erezrokah** [comment]
Thanks @BA1RY, pattern validation is done here https://github.com/netlify/netlify-cms/blob/d3aaf4ddb326efcaffdbcc5af5c0e5c8bcaa36ea/packages/netlify-cms-core/src/components/Editor/EditorControlPane/Widget.js#L136

This might get tricky as currently validation runs in the core for all widgets once a user saves an entry. So a change might impact all widgets.

**Comment by BA1RY** [comment]
Thanks @erezrokah . How do you suggest me to go about implementing it then?

**Comment by barthc** [comment]
> It would be nice to trigger the regexp validation by onchange or oninput events

I would run the validation on `onBlur` event for performance.

**Comment by erezrokah** [comment]
@BA1RY, I don't have a good answer at the moment, I would first try to move the validation call from https://github.com/netlify/netlify-cms/blob/d3aaf4ddb326efcaffdbcc5af5c0e5c8bcaa36ea/packages/netlify-cms-core/src/components/Editor/EditorInterface.js#L137 to the `onChange` event and see what breaks 😄

**Comment by BA1RY** [comment]
@magomimmo @erezrokah I've made a PR for this issue. Please have a look at it. Thanks :smiley:
