### ISSUE TITLE
make _includes functions available in post body 

### ISSUE THREAD

**Issue by fdq09eca** [netlify/netlify-cms#3751]
I am very new to Netlify CMS, my bad if I am asking some documented question.

I am using Jekyll and I have some helper functions for blogging in the `_includes` folder, How I could make them available to the user in editing the post body like `image` and `code block` like this?
![image](https://user-images.githubusercontent.com/51902242/81820377-1f70ab80-9563-11ea-98dc-6331ab1afe0d.png)

such that they do not have to explicitly type out something like the following?

```
{% include figure image_path="/assets/old_images/ISS_052018.jpg" %}
``` 
Thank you.

**Comment by erezrokah** [comment]
Hi @fdq09eca, welcome 😄 The docs for that are here https://www.netlifycms.org/docs/custom-widgets/#registereditorcomponent

Closing, please re-open/comment if you any issues
