### ISSUE TITLE
preview_path does not appear..

### ISSUE THREAD

**Issue by fdq09eca** [netlify/netlify-cms#3753]
I tried to follow the [doc](https://www.netlifycms.org/docs/deploy-preview-links/#configuring-preview-paths) but the preview link does not appear at all.

![image](https://user-images.githubusercontent.com/51902242/81829504-8abf7b00-956d-11ea-89bd-d0d3ad60e645.png)

Am I missing something? 

here is my setting
```
# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "assets/images"
# publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: blog/{{slug}}
    create: true
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "single" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "tags", name: "tags", widget: "list", default: ["others"] }
      - {
          label: "categories",
          name: "categories",
          widget: "list",
          default: ["APEC Study Centre"],
        }
      - { label: "execept", name: "execept", widget: "string", required: false}
      - { label: "tagline", name: "tagline", widget: "string", required: false}
      - label: "sidebar"
        name: "sidebar"
        widget: "list"
        required: false
        fields:
          - {
              label: "image",
              name: "image",
              widget: "image",
              allow_mulitple: false,
              # default: "",
              required: false
            }
```

Thank you.

**Comment by erezrokah** [comment]
Hi @fdq09eca, `preview_path` is useful when working with `publish_mode: editorial_workflow`.
In `publish_mode: editorial_workflow` the CMS will create a PR instead of committing to the master branch when you create/edit an entry. Then if your CI system creates a preview for that PR the URL should appear.
Since you have editorial workflow disabled you should also set a `site_url` (https://www.netlifycms.org/docs/deploy-preview-links/#preview-links-for-published-content) to show preview paths for published content.

**Comment by erezrokah** [comment]
For it to work you need to make sure the PR is created for that entry and there is a matching commit status on that PR.

**Comment by fdq09eca** [comment]
it did create a PR. and the preview link also appeared. but the link is not working.. it brings me to page not found.
![image](https://user-images.githubusercontent.com/51902242/81835229-98c4ca00-9574-11ea-99db-bfebad515cd3.png)

**Comment by erezrokah** [comment]
Hi @fdq09eca, you can use `sanitize_replacement` https://www.netlifycms.org/docs/configuration-options/#slug-type

**Comment by erezrokah** [comment]
Closing, please comment if nessecary

**Comment by idrisadetunmbi** [comment]
@erezrokah, `sanitize_replacement` with the preview_path shows an error when I use a character like `/` or ` `. The error is `The replacement character(s) (options.replacement) is itself unsafe.`

Basically, when the preview_path resolves to something that includes a `/`, it is replaced with `-` which prevents being able to use something like a slug entry field in the CMS as the preview_path

**Comment by mmkal** [comment]
@erezrokah I know this is n old issue but I'm hitting something similar. I have editorial_workflow enabled, and PRs are being successfully created. The repo is using GitHub actions so commit statuses should be working normally. But no preview url. Is there a way to debug this?

Alternatively, it'd be great to be able to "force" a preview url - we are using next.js and pull content using the github api during static-page generation, so the preview url could work instantly, even before the commit status have turned green.
