### ISSUE TITLE
Newlines stripped when editing in Rich Text mode

### ISSUE THREAD

**Issue by Undistraction** [netlify/netlify-cms#3755]
**Describe the bug**
When text contains newlines, they are are removed when editing in Rich Text Mode and converting back to Markdown.

**To Reproduce**
1. In a Markdown field toggle to Markdown Mode
2. Enter the following:
```
alpha
bravo
charlie
```
2. Toggle to Rich text mode and make some kind of edit (change a letter for example).
3. Toggle back to markdown

This is easy to replicate using `dev-test` in the repo. 

**Expected behavior**
Newlines should be preserved. 

**Screenshots**

![](https://im7.ezgif.com/tmp/ezgif-7-1e55a100c29a.gif)

**Applicable Versions:**
 - Netlify CMS version: netlify-cms-core@2.26.0
 - Node.JS version: v10.20.1

**Comment by jeremyzilar** [comment]
Tested locally myself, and got the same thing: 
![image](https://user-images.githubusercontent.com/395641/81971953-e4688980-95ef-11ea-9868-e3d9c57296e8.png)

**Comment by erezrokah** [comment]
@Undistraction thanks for reporting and @jeremyzilar for confirming. What's the impact of this?
I think new lines at the end of the markdown won't be rendered anyway.

**Comment by Undistraction** [comment]
@erezrokah the following markdown:
```markdown
alpha
bravo
charlie
```
Is rendered correctly by markdown processors, with newlines preserved, and each footnote on a separate line, for example try pasting the above into: https://stackedit.io/app# and viewing the rendered output.

However this bug means Netlify CMS strips the newlines and will render the above footnotes on a single line with each footnote separated by spaces:
```text
alpha bravo charlie
```

The case that case caused me to notice this is footnotes, so instead of rendering a footnote per line, all footnotes are rendered on the same line. However this is true of any text separated by newlines.

**Comment by erezrokah** [comment]
Thanks for clarifying @Undistraction, I misread the bug. I thought it was the behaviour of stripping new lines at the end of the content and not between text lines.

**Comment by Undistraction** [comment]
@erezrokah no problem. If you can point me in the direction of where the issue lies I'm happy to take a run at fixing it.

**Comment by erezrokah** [comment]
Thanks @Undistraction, I can't be sure without investigating, but the conversion from a raw string to slate date structure is done here https://github.com/netlify/netlify-cms/blob/088b1a8ab626498382d6305fa46d174d4f5ba755/packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js#L46
