### ISSUE TITLE
Extending Widgets

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [netlify/netlify-cms#3767]
I am using regular old JavaScript, no NodeJS or React. I have a static site on GitLab using Netlify CMS for our blog. I am trying to create a custom widget that is based off of the string widget, but modifies the user input before it is saved, and also has a custom preview output.

My issue right now is with the control side of things. How do I extend the string widget's control, so the functionality of the string widget is still present while letting me modify how the data is saved to the file?

To further explain what I'm doing, I want to have a string based widget that an editor can input a YouTube URL, and only the video ID is saved to the post in the front matter.

I figured out how to get the ID from the user input with regex, and I have things set up to technically work, but it doesn't extend the string widget, so the styling is not the same as a regular string widget.

**Comment by HeyITGuyFixIt** [comment]
I've seen it done in a similar fashion with React in #2955, but I don't know how that translates to Vanilla JavaScript.

**Comment by barthc** [comment]
> I figured out how to get the ID from the user input with regex, and I have things set up to technically work, but it doesn't extend the string widget, so the styling is not the same as a regular string widget.

Can you show some codes and if necessary screenshots.

**Comment by HeyITGuyFixIt** [comment]
@barthc Here is the control function I have currently:

```
var YouTubeControl = createClass({
    handleChange: function(e) {
	    this.props.onChange(e.target.value.match(/(.*youtu(\.be\/|be.com\/(watch\?v=|embed\/)))*(.*?)(\?t=.+|\?start=.+)*$/)[4]);
    },
    render: function() {
        return h('input', { type: 'text', value: this.props.value, onChange: this.handleChange });
    }
});
```

**Comment by barthc** [comment]
Add the` className` prop.
```js
return h('input', {
  type: 'text',
  value: this.props.value,
  onChange: this.handleChange,
  className: this.props.classNameWrapper,
});
```

**Comment by HeyITGuyFixIt** [comment]
That does the trick

**Comment by HeyITGuyFixIt** [comment]
While the above works fine and all, and is what I needed for that use case, I would still like to know how I can extend widgets. For example, say I want to modify the Markdown widget, what would I need to do to essentially copy that widget and then add to it my own code to override or extend its current behavior?

**Comment by HeyITGuyFixIt** [comment]
Referring back to #2955, what would be the Vanilla JS equivalent of:
> ```js
> import CMS from 'netlify-cms'
> 
> const File = CMS.getWidget('file')
> 
> class JSONControl extends File.control {
>   isValid = () => {
>     // Do internal validation
>     return { error: { message: 'Your error message.' } };
>   };
> }
> 
> 
> export default JSONControl
> ```

**Comment by barthc** [comment]
> Referring back to #2955, what would be the Vanilla JS equivalent of:
 
I assume you mean without es6 `class`. You can try something like so:
```js
import CMS from 'netlify-cms';

const Markdown = CMS.getWidget('markdown');

function JSONControl(props) {
  this.state = {
    value: '',
  };
}
JSONControl.prototype.isValid = () => ({
  // Do internal validation
  error: { message: 'Your error message.' },
});

Object.setPrototypeOf(JSONControl.prototype, Markdown.control.prototype);
export default JSONControl;
```

**Comment by HeyITGuyFixIt** [comment]
I am not using React and NodeJS so I can't use import and export. Experimenting with it last night, I figured out how to do it mostly using the classes. I think I was mostly confused by the export line.

So now I am trying to figure out how to add onto the functionality of the render function. I will have to play around with it later today.
