### ISSUE TITLE
Feature Request: Edit entry slugs

### ISSUE THREAD

**Issue by indysigner** [netlify/netlify-cms#377]
Hey Netlifiers,

It would be quite handy if we could edit the URL of a site / article / page we want to publish or that already has been published.

The current behaviour is that the URL is being generated from the headline of the article, while the desired behaviour is that we are actually able to edit the URL — ideally even the date slug if exisiting (like on Smashing).

- [ ] Add `Edit URL`, including the **date slug** 
- [ ] In Edit mode, add `OK` and `Cancel` 

![2017-04-18_li](https://cloud.githubusercontent.com/assets/4224281/25154269/4bbe0de6-2490-11e7-9d2f-ffabf7413f8e.jpg)

![2017-04-18 1](https://cloud.githubusercontent.com/assets/4224281/25154326/884c655a-2490-11e7-81e0-03d1a946040a.png)

**Comment by erquhart** [comment]
This should definitely happen, probably as a part of a general metadata widget in the entry editor UI.

**Comment by erquhart** [comment]
Note: Netlify CMS isn't capable of setting a URL - your that happens between your build and deployment. What the CMS _can_ influence is the slug. Updating the title accordingly.

Slug editing support is mentioned in (and will potentially land in) #180.

**Comment by erquhart** [comment]
Closing in favor of #445. @indysigner please comment there if you feel that issue won't fully capture your intent and we can expand.
