### ISSUE TITLE
Custom Domains for Local Backend

### ISSUE THREAD

**Issue by amykapernick** [netlify/netlify-cms#3782]
**Describe the solution you'd like**
When using a local backend, `local_backend: true`, it checks if there's a local server by seeing if the hostname is localhost ([/src/actions/config.js](https://github.com/netlify/netlify-cms/blob/39e00261a22e2e3c7f18daf1b2c3c3ec874f2030/packages/netlify-cms-core/src/actions/config.js#L178))
```
  if (location.hostname === 'localhost' || location.hostname === '127.0.0.1')
```
I use a package called [Hotel](https://github.com/typicode/hotel/) to proxy localhost URLs to a user friendly domain (eg. mywebsite.local), so that it's easier to keep track of multiple locally run servers.

When I try and load my site through that eg `mysite.local/admin`, it doesn't pick up that I'm running locally and tries to connect to the remote git integration.

It would be great if you could set a custom domain/TLD to check for as well as just localhost, or checking an environment variable to see if this is running in development.

Note: this isn't about the proxy server running, it's about the website itself

**Comment by erezrokah** [comment]
Hi @amykapernick, thanks for opening this.
Can you suggest how a configuration for this would look like?
A possible workaround would be to force a proxy backend:

```yaml
backend:
  name: proxy
  proxy_url: 'http://<domain>:8081/api/v1'
```

combined with [manual initialisation](https://www.netlifycms.org/docs/beta-features/#manual-initialization) to conditionally set the backend.

**Comment by amykapernick** [comment]
@erezrokah my issue isn't with the proxy server, it's to do with the detection of the Dev server. 

If the check allowed defining another config, or tested for an environment variable instead?

Eg.
```
// src/actions/config.js
 if (location.hostname === 'localhost' || location.hostname === '127.0.0.1' || process.env.LOCAL_BACKEND == true)
```

Alternatively if when defining the local backend in the admin config file, you could set the url there

Eg
```
// admin/config.yml
local_backend: true
local_site: mysite.local


// src/actions/config.js
 if (location.hostname === 'localhost' || location.hostname === '127.0.0.1' || location.hostname === local_site)
```

**Comment by erezrokah** [comment]
Hi @amykapernick, thank you for clarifying, I believe I wasn't making my self clear enough.
The detection mechanism (when it works) will modify the CMS backend configuration to connect to the proxy server here:
https://github.com/netlify/netlify-cms/blob/2f435f875bc139af345080eb8cca6146d27c10f6/packages/netlify-cms-core/src/actions/config.js#L210
You should be able to workaround the current limitation by forcing the CMS to connect to the proxy server directly using my suggestion (until we support specifying a local site).

The additional manual initialisation configuration suggestion was made so you could potentially implement your own detection code and when running against the local site use:
```yaml
backend:
  name: proxy
  proxy_url: 'http://<domain>:8081/api/v1'
```
And when running on production use:
```
backend:
  # original config
```

**Comment by erezrokah** [comment]
Hi @amykapernick, just posted a fix for this issue and would be happy to get your feedback to make sure it handles your use case.
Specifically this line https://github.com/netlify/netlify-cms/pull/3805/files#diff-f195d7cc6573e4193088947ee673daa3R196 that defaults the `url` to the same host configured under `allowed_hosts`.

**Comment by fes300** [comment]
hi @erezrokah and thank you for this feature!
I tried to set it up on my local machine but somehow it is not working for me... 
This is my config:
![image](https://user-images.githubusercontent.com/10383300/114996473-27d21480-9e9f-11eb-9eb7-f2902a9124a7.png)

But it looks like it is not being picked up:
![image](https://user-images.githubusercontent.com/10383300/114996377-0ec96380-9e9f-11eb-8b94-5c7a233f894e.png)
Am I doing something wrong?

**Comment by erezrokah** [comment]
Hi @fes300, can you tryin configuring `url` to the full URL, e.g. prefix it with `http://` or `https://`?

**Comment by fes300** [comment]
I ended up using custom initialization as per your previous suggestion, works like a charm 👍
