### ISSUE TITLE
Question/Advice needed on using multiple branches with Netlify CMS

### ISSUE THREAD

**Issue by alexearnshaw** [netlify/netlify-cms#3790]
We are using Netlify CMS open authoring workflow for our open documentation site https://axway-open-docs.netlify.app/docs/ 

We are using Hugo to generate the site and Netlify to deploy and host. We are using Netlify CMS to enable contributors to edit our docs directly (via pull requests from their own forks)

We now have a requirement to have multiple branches in our Git repo, as we need a way to enable internal contributors to edit docs for new features in our product that are in development/not yet released. We need a way to allow contributors to edit these docs but we don't want to merge them to production until a certain point in time. 

Our repo is https://github.com/Axway/axway-open-docs and our Netlify CMS config is implemented here https://github.com/Axway/axway-open-docs/blob/master/static/admin/config.js

I've read through all of the comments on these existing issues #1737 and #1795 but I think these solutions are not exactly what we need as we are looking for something simpler...

This is what I think we need:

- master branch: this links to our production environment/site on Netlify. Users who click the Edit on Netlify CMS button on pages on this site will edit files on the master branch. This is ideal for external contributors who want to fix bugs, make improvements etc to our production docs. Changes that are made to this branch would also need to be cherry-picked or merged to the development branch so that the 2 branches keep in sync.
- development branch: this links to a staging/dev environment on Netlify. Users who click Edit on Netlify CMS button on pages on this site will edit files on the dev branch. This is ideal for our internal developers to add new doc/changes to doc for new features in development. When these features are released to the public we would need to cherry-pick or merge the all the changes from this branch to the production branch. This would happen every 2 months.

My question is - is this as simple as just having a different Netlify CMS config on each branch, that sets the branch for Netlify CMS to development on the dev branch and to master on the production branch? Will this become a headache when we are trying to keep the two branches in sync? Or is there a better way/recommended way of handling this use case in Netlify CMS?

I'd really appreciate any advice/best practices on how others have done this. Thanks in advance!

**Comment by smashercosmo** [comment]
This what I do on my Gatsby site. Maybe this can help you:

cms.js
```js
const config =
  process.env.NODE_ENV === 'development'
    ? { local_backend: { url: 'http://localhost:8000/api/v1' } }
    : {
        backend: {
          name: 'git-gateway',
          branch: process.env.GATSBY_BRANCH || 'master',
        },
      }

CMS.init({ config })
```

gatsby-config.js
```js
// process.env.HEAD comes from Netlify
process.env.GATSBY_BRANCH = process.env.HEAD
```

**Comment by erezrokah** [comment]
Hi @alexearnshaw, having a separate config or even a separate site per CMS instance should work.
However there might be another way to go around this in the form of having a `draft` boolean field or even a `releaseDate` field  on entries and having the build process ignore `draft` items.
That way they'll still show up in the CMS, but not in the published site while only maintaining a single branch.
This https://github.com/netlify/netlify-cms/pull/3741 upcoming feature should make it easier to filter `draft` entries and publish them when you are ready.

**Comment by alexearnshaw** [comment]
> ```js
> branch: process.env.HEAD || 'master',
> ```

Thanks @smashercosmo I did try various ways of getting the branch from Netlify but I couldn't get any of them to work. See this PR in my repo https://github.com/Axway/axway-open-docs/pull/750 - When I do this the CMS doesn't load and I get an error that `process` is not defined. I don't know where or how to define process when using Hugo with Netlify? (by way of explanation I'm a technical writer not a developer so I don't really understand what's going on here at all!)

**Comment by smashercosmo** [comment]
Yes, you need to find a way to preprocess config.js file and substitute __BRANCH__ with process.env.HEAD value from netlify. I think it should be possible with some build hook.
```
branch: __BRANCH__
```

**Comment by alexearnshaw** [comment]
> Hi @alexearnshaw, having a separate config or even a separate site per CMS instance should work.
> However there might be another way to go around this in the form of having a `draft` boolean field or even a `releaseDate` field on entries and having the build process ignore `draft` items.
> That way they'll still show up in the CMS, but not in the published site while only maintaining a single branch.
> This #3741 upcoming feature should make it easier to filter `draft` entries and publish them when you are ready.

Thanks @erezrokah We did consider using draft or release date. This would work for the creation of new pages, but we didn't think it would work for changes to existing pages, as we would need the older version of the page to still show on production and it wouldn't. 

Also we felt that it would negatively impact on contributor UX as they would have to go directly to the CMS UI to edit any pages in draft/development and wouldn't be able to access them directly from the built site and just click the Edit button on the page (as they wouldn't be built). 

We'd prefer to have the same workflow for contributors regardless of whether they are making changes to production docs or in-development docs. We think the UX is not as negatively impacted by having two different sites as long as the process to edit is the same...

Can you elaborate a bit more on "even a separate site per CMS instance should work."? Is this the same as having 2 different branches linked to 2 different environments/sites or is this something else?

**Comment by erezrokah** [comment]
> Thanks @erezrokah We did consider using draft or release date. This would work for the creation of new pages, but we didn't think it would work for changes to existing pages, as we would need the older version of the page to still show on production and it wouldn't.

That makes sense, thank you for clarifying.

> Can you elaborate a bit more on "even a separate site per CMS instance should work."? Is this the same as having 2 different branches linked to 2 different environments/sites or is this something else?

As @smashercosmo mentioned the CMS environment/branch should be configured during build time.
That is, when the site is deployed to `https://axway-open-docs.netlify.com/` the CMS branch will be the one set on build time, and that is what the users/contributors will update.

You still need to figure out a way to serve users 2 different versions of the CMS.
Open authoring users will login into the version configured with `master` branch, and internal contributors will login into the version configured with `development` branch.

There are multiple ways to do it:
1. Using custom domains, e.g. `https://axway-open-docs.netlify.com` and `https://internal.axway-open-docs.netlify.com` (for the latter you might use Netlify branch preview URL).
2. Using custom paths under the same domain, e.g `https://axway-open-docs.netlify.com/open_authoring` and `https://axway-open-docs.netlify.com/internal`
3. Have a single domain and path, but dynamically serve a CMS with a different config, e.g in you `config.js` figure out a way to know which branch you should use for the user.

I would actually recommend the first one, since you can probably ask your internal contributors just to login to the branch deploy preview `https://development--axway-open-docs.netlify.com`

**Comment by alexearnshaw** [comment]
Ah thank you @erezrokah it's becoming a bit clearer now! I get what you're saying regarding the 3 options to serve the CMS to the users and agree option 1 would work fine for our use case.

The bit I still don't get is how exactly to configure the branch during build time? Is there a way to set this in the Netlify UI or netlify.toml (i.e. by using an env var for the CMS branch and in the prod env set this to `master` and in the dev env set this to `develop`) and then use this variable somehow in my `config.js`? In this case my `config.js` would be the same on both branches so I think this would be the best option if it's possible.

What I was initially thinking of doing was simply hardcoding each branch name in the `backend` section of `config.js` file on each branch (on `master` branch hardcode it to `master` and on `develop` branch hardcode it to `develop`). Of course in this case my `config.js` is different on both branches, which I think might cause issues later if we need to merge one branch into another to keep the changes in sync?

**Comment by erezrokah** [comment]
Hi @alexearnshaw, there are a few way you could go about the config, but first I think you would need to set Netlify to deploy on all branches (or specific branches) to make sure the `develop` branch is built on each commit:
![image](https://user-images.githubusercontent.com/26760571/82462804-b938db00-9ac4-11ea-9a4e-759337831504.png)

Then possibly you could inside `config.js` apply a regular expression on the browser location to match the branch name from the URL and default to master.

Another option is to use @smashercosmo suggestion and do it during the build process.
A simple find replace would do.
Let say you change you `config.js` to:
```js
const config = {
  backend: {
    name: 'github',
    repo: 'Axway/axway-open-docs', //Path to your GitHub repository. For fork testing use alexearnshaw/axway-open-docs.
    open_authoring: true,
    branch: 'REPLACE_ME_DURING_BUILD'
  },
};
```
And then have a script in the build process that replaces `REPLACE_ME_DURING_BUILD` with `process.env.HEAD`

**Comment by alexearnshaw** [comment]
Much appreciated @erezrokah I think I have enough to go on now :) When I get something working I'll post back here in case it might be useful to anyone else.

**Comment by alexearnshaw** [comment]
For anyone interested, here's a summary of how I got Netlify CMS working with a development and production branch.

First set up Netlify to build a `develop` branch as well as production:
![image](https://user-images.githubusercontent.com/29064556/83254500-c3369a00-a1a6-11ea-8490-6ca73013a9d4.png)

Now our production site is available on https://axway-open-docs.netlify.app/ and our development site is available on https://develop--axway-open-docs.netlify.app/

Next, update `config.js` to set the branch name for the CMS based on whether the URL of the site contains `develop` or not.

```
const cms_branch = window.location.hostname.includes('develop') ? 'develop' : 'master';

const config = {
  backend: {
    name: 'github',
    branch: cms_branch,
    repo: 'Axway/axway-open-docs', //Path to your GitHub repository. For fork testing use alexearnshaw/axway-open-docs.
    open_authoring: true,
  },
```

I'm sure there's probably better ways of doing it, but this worked for me and might be of help to someone else :)

**Comment by erezrokah** [comment]
Thanks for sharing @alexearnshaw, this looks 🔥
Linking https://github.com/netlify/netlify-cms/issues/3827 for context
Closing the issue.
