### ISSUE TITLE
file widget with Gatsby/NetlifyCMS - accept image OR video

### ISSUE THREAD

**Issue by stephaniedavidson** [netlify/netlify-cms#3792]
**Is your feature request related to a problem? Please describe.**

Using the [Gatsby Netlify CMS starter](https://github.com/thomaswang/gatsby-personal-starter-blog), and I added a cover image field for each post and in the index. I want to be able to upload an mp4 OR a jpg though. So in my config.yml I replaced the **image widget** with the **file widget**, which can upload any type of file, works great. In my markdown, I get `cover: x.jpg` or `cover: x.mp4`

The problem is: the Gatsby query seems to break it. The Gatsby query is:
```
        cover {
          childImageSharp {
            fluid(maxWidth: 1800) {
              ...GatsbyImageSharpFluid_noBase64
              ...GatsbyImageSharpFluidLimitPresentationSize
            }
          }
        }
```
so it works when I have a Gatsby Image but not with an MP4, because an MP4 doesn't have a childImageSharp property. I also can't simply use `post.frontmatter.cover`, still has the childImageSharp null error . 

It's like I need an if statement in the graphQL query?

**Describe the solution you'd like**
A Gatsby media widget for images or video

**Describe alternatives you've considered**
Tried doing a little templating, doesn't work though:

```
        {post.frontmatter.cover.childImageSharp && (
          <Img fluid={post.frontmatter.cover.childImageSharp.fluid} />
        )}

        {!post.frontmatter.cover.childImageSharp && (
          <video src={post.frontmatter.cover} />
        )}
```

doesn't work.

alternatively could write a custom widget but this seems to advanced for me

**Comment by erezrokah** [comment]
Hi @stephaniedavidson, this is more of a Gatsby question than a CMS question, but I'll try to provide an explanation.
Gatsby does a lot of automatic type inference for fields, which means that if you have different types (for example image file vs movie file) for the same field it might get confused.
I'm not sure what exactly is the error you're getting but I would try to follow https://www.gatsbyjs.org/docs/schema-customization/ and mostly https://www.gatsbyjs.org/docs/schema-customization/#opting-out-of-type-inference

**Comment by stephaniedavidson** [comment]
ah ok thank you, yeah it sounds like I would want to avoid opting out of type inference, let me ask the gatsby community. thanks!

**Comment by erezrokah** [comment]
Sure thing, can we close the issue?
