### ISSUE TITLE
List does not get updated

### ISSUE THREAD

**Issue by liamkeily** [netlify/netlify-cms#3796]
After editing the title of a post, the title does not get updated in the list. Is this expected behaviour?

**Comment by HeyITGuyFixIt** [comment]
Which list? Are you using the editorial workflow?

**Comment by erezrokah** [comment]
Hi @liamkeily, can you please follow the issue template? Not doing so makes it very hard to resolve issues.

**Comment by erezrokah** [comment]
Closing. @liamkeily please follow the issue template
