### ISSUE TITLE
add video to post body

### ISSUE THREAD

**Issue by stephaniedavidson** [netlify/netlify-cms#3798]
**Is your feature request related to a problem? Please describe.**
I want to be able to add video (my own mp4s, not youtube) to my post body, here:
![image](https://user-images.githubusercontent.com/656405/82764798-9d447a80-9ddf-11ea-920f-f598889ce25c.png)

I see that you can use the `file` widget to upload videos, but I can't figure out how to apply this to the post body, which is getting rendered with `gatsby-plugin-mdx`. I'm using [this netlify cms gatsby starter template](https://github.com/thomaswang/gatsby-personal-starter-blog) mostly out of the box. 

I also see that you can create your own CMS extension by making a src/cms/cms.js file, but looking at [examples with youtube ](https://github.com/brooklynrail/brooklynrail-platform/blob/master/themes/brooklynrail/static/workflow/editorComponents/youtube.js)I'm still not sure how to apply that knowledge to effect the mdx body.

**Describe the solution you'd like**

I'd like to be able to insert my own mp4 assets in the body of my posts.

**Describe alternatives you've considered**
No plugins for this seem to exist

**Additional context**
Using [this starter template](https://github.com/thomaswang/gatsby-personal-starter-blog) almost verbatim

**Comment by d4rekanguok** [comment]
Hi @stephaniedavidson, not sure how this'll do in mdx, but here's an example with vanilla markdown:

https://github.com/d4rekanguok/netlify-cms-markdown-video-example/blob/master/src/editor-video.js

You can play with it here: https://sad-lamport-b5c3d0.netlify.app/#/collections/post/new

For more information on what these fields do, [please see this section in the docs](https://www.netlifycms.org/docs/custom-widgets/#registereditorcomponent).

**Comment by stephaniedavidson** [comment]
> Hi @stephaniedavidson, not sure how this'll do in mdx, but here's an example with vanilla markdown:
> 
> https://github.com/d4rekanguok/netlify-cms-markdown-video-example/blob/master/src/editor-video.js
> 
> You can play with it here: https://sad-lamport-b5c3d0.netlify.app/#/collections/post/new
> 
> For more information on what these fields do, [please see this section in the docs](https://www.netlifycms.org/docs/custom-widgets/#registereditorcomponent).

thanks for this, seems like exactly what I'm going for. So I have a `src/cms` directory where I've added your index.js file and editor-video.js file, and that alone doesn't change anything. Is there something I have to do in the configs?

**Comment by d4rekanguok** [comment]
Do you have a `gatsby-plugin-netlify-cms` in your gatsby-config? If you do, you'd have to tell it the location of the cms index file:

```js
  {
    resolve: 'gatsby-plugin-netlify-cms',
    options: {
      manualInit: true,
      modulePath: `${__dirname}/src/cms/index.js`,
    },
  },
```

**Comment by stephaniedavidson** [comment]
> Do you have a `gatsby-plugin-netlify-cms` in your gatsby-config? If you do, you'd have to tell it the location of the cms index file:
> 
> ```js
>   {
>     resolve: 'gatsby-plugin-netlify-cms',
>     options: {
>       manualInit: true,
>       modulePath: `${__dirname}/src/cms/index.js`,
>     },
>   },
> ```

thank you! added that verbatim, but still no video tag in the editor. Using this setup: https://github.com/thomaswang/gatsby-personal-starter-blog

**Comment by d4rekanguok** [comment]
I think we might have gone a bit off-topic for this issue, if you don't mind I can offer more assistance in the community slack.

**Comment by stephaniedavidson** [comment]
will try slack and close the issue, thanks
