### ISSUE TITLE
Can I launch a website that deploys a machine learning model using Django,Keras and Tensorflow on Netlify?

### ISSUE THREAD

**Issue by AdarshPan** [netlify/netlify-cms#3811]
I have surfed a lot but haven't found the answer anywhere . My Website doesn't have any database ..so can i call it a static website and deploy it on Netlify?

**Comment by tomrutgers** [comment]
I fear the answer is no, as you probably need a running server even though you don't have a database, but try asking the [community forum](https://community.netlify.com/). I'm closing this issue since this repository is meant for Netlify CMS related issues and topics.
