### ISSUE TITLE
CMS not loading, blank screen

### ISSUE THREAD

**Issue by alexearnshaw** [netlify/netlify-cms#3819]
**Describe the bug**
When we open the CMS in our project this morning all we see is a blank page. No errors showing in the console. Everything working fine yesterday. This might not be a CMS bug but I can't find anything changed on our side either, so we're at a loss and would appreciate any help!

**To Reproduce**
1. Go to https://axway-open-docs.netlify.app/docs/
2. Click "Edit on Netlify CMS" on any doc page
3. New window launches but shows blank page
![image](https://user-images.githubusercontent.com/29064556/82993752-fdfacf80-9ff8-11ea-8cc9-f2016b997e41.png)
No errors in the console - The babel warning appeared previously so I don't think it's anything to do with that.

**Expected behavior**
CMS should load the appropriate file.

**Applicable Versions:**
 - Netlify CMS version: 2.10.49
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version: Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**CMS configuration**
https://github.com/Axway/axway-open-docs/blob/master/static/admin/config.js

**Additional context**
Going directly to https://axway-open-docs.netlify.app/admin/ gives the same result
Tested also in Firefox and Edge and the same issue

**Comment by erezrokah** [comment]
Thanks for reporting @alexearnshaw.
We haven't released a new version recently so not sure what is the issue.
Did notice the CMS is not initialised via `config.js` and also this:
![image](https://user-images.githubusercontent.com/26760571/82994842-75d1f580-a00b-11ea-8ccd-040cd31c5f61.png)
Which seems related to that warning message regarding `babel`

**Comment by alexearnshaw** [comment]
@erezrokah Thanks, we haven't changed anything in config.js since yesterday when everything was working. I did make some changes to config.js yesterday but that was on a different branch, so I don't think that's the issue. I've also tested some other sites of ours that don't have these changes at all and they all give the same result...

We also have someone working on setting up redirects in our sites on Netlify, but again these changes are on a branch so I don't think that would cause this issue.

So do you think this issue is related to babel then or our config? Are any other sites experiencing issues this morning?

**Comment by erezrokah** [comment]
Maybe this is related https://github.com/babel/babel/issues/11621#issue-625277350

**Comment by erezrokah** [comment]
You can try using `https://unpkg.com/@babel/standalone@7.9.0/babel.min.js` here https://github.com/Axway/axway-open-docs/blob/e7113b55a79b16108f93e1d89294725d9e4c4ea5/static/admin/index.html#L22

**Comment by alexearnshaw** [comment]
Thank you so much @erezrokah changing to version 7.9.0 of babel has fixed our issue!

**Comment by erezrokah** [comment]
That's great @alexearnshaw, closing this issue. I recommend watching the issue I linked from the babel repo so you can go back tp using the latest version when they publish a fix.
