### ISSUE TITLE
Import of netlify-cms-app unconditionally calls init

### ISSUE THREAD

**Issue by zmre** [netlify/netlify-cms#3830]
This may be related to the closed and stale issue #1908.

**Describe the bug**
The [beta docs](https://www.netlifycms.org/docs/beta-features/#manual-initialization) show that you can manually init and that the passed in config will override the values in `config.yml` if you set `window.CMS_MANUAL_INIT = true` before importing CMS.

This was true at one time, but the check for `CMS_MANUAL_INIT` seems to have been lost as the `netlify-cms` package got refactored into multiple packages.

Because of this, when manually calling `CMS.init({...})`, things have already been initialized and you cannot change the backend, for example.

**To Reproduce**
1. In CMS.tsx (typescript version), add these lines:

```typescript
window.CMS_MANUAL_INIT = true;
import CMS from "netlify-cms-app";
const configOverride =
    window.location.hostname === "localhost"
        ? {
              config: {
                 local_backend: true,
                 backend: {
                      name: "proxy",
                      proxy_url: "http://localhost:8081/api/v1"
                 },
              },
           }
        : {
              config: {
                  local_backend: false,
                  backend: {
                       name: "github",
                       repo: "whatever/website",
                       branch: "master",
                  }
              },
          };

CMS.init(configOverride);
```

2. In config.yml, remove all mention of `backend` or `local_backend`.
3. In this variation, when setting the backend in the override, you'll get a `Error: config should have required property 'backend'` error. If you just do the `local_backend` bit, you get a weird mix of behaviors.

In any case, there doesn't seem to be a (documented) way to suppress the automatic running of `init()` on import.

**Expected behavior**
I should be able to have dynamic portions of configuration and to suppress the automatic import so I can manually call it with config overrides.

**Applicable Versions:**
I'm using these:

 - Netlify CMS version: netlify-cms-app 2.12.13, netlify-cms-core 2.27.0
 - Git provider: GitHub or local proxy for devs
 - OS: Mac
 - Node.JS version: 12.16.1

**CMS configuration**
Don't think this matters.

**Additional context**
I couldn't definitively figure out where this was introduced as the code handling `CMS_MANUAL_INIT` bounced around a few times.

**Comment by zmre** [comment]
I'm going to close this. The issue was not coming from netlify-cms, but from `gatsby-plugin-netlify-cms` which needed a `manualInit: true` option. Sorry for the bother.

**Comment by zmre** [comment]
Although it's worth noting that the documentation on the beta page is still outdated...

**Comment by erezrokah** [comment]
Thanks for reporting the issue and solution!
On a side not, you don't need to put `local_backend: true` behind a condition to test for localhost - the CMS handles that already:
https://github.com/netlify/netlify-cms/blob/5bbaf41f73c0debf31636dd38fd536268ae2c0f5/packages/netlify-cms-core/src/actions/config.js#L189
