### ISSUE TITLE
Singular Resource

### ISSUE THREAD

**Issue by Undistraction** [netlify/netlify-cms#3846]
**Is your feature request related to a problem? Please describe.**
Sometimes a resource will only ever be singular, for example you might have a top-level 'Site' that has site-level config. However this can only be represented as a collection. In this case it makes no sense for a collection of 'sites' as there is and will only ever be a single site

**Describe the solution you'd like**
It would be great to be able to define a singular / singleton collection, either in a separate category in the sidebar, or so that clicking on its type in the sidebar opens it for editing. This could be done in the collection config via an `isSingleton` flag.

**Describe alternatives you've considered**
The current workaround is to have a collection with a single item in it, however this is confusing for users of the CMS.

**Comment by erezrokah** [comment]
Hi @Undistraction, can we close as duplicate of https://github.com/netlify/netlify-cms/issues/535?

**Comment by Undistraction** [comment]
@erezrokah Ah. I did look for an existing issue, but didn't see that one.
