### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by PierW** [netlify/netlify-cms#3852]
1) **Netlify-cms is not responsive.**

2) **Make it mobile first**

**Comment by erezrokah** [comment]
Closing in favour of:
https://github.com/netlify/netlify-cms/issues/1358
https://github.com/netlify/netlify-cms/issues/441
https://github.com/netlify/netlify-cms/issues/2984
https://github.com/netlify/netlify-cms/issues/2557
