### ISSUE TITLE
Hugo shortcodes editor Components for the CMS

### ISSUE THREAD

**Issue by sharadcodes** [netlify/netlify-cms#3854]
I've created Editor Components for Hugo shortcodes which users can import in their CMS.
I hope this will get added.

Here is the link of repo: https://github.com/sharadcodes/hugo-shortcodes-netlify-cms

**Comment by erezrokah** [comment]
Hi @sharadcodes, thank you for this!
How about adding it to our examples page https://www.netlifycms.org/docs/examples/ via a PR/edit link?

**Comment by sharadcodes** [comment]
> Hi @sharadcodes, thank you for this!
> How about adding it to our examples page https://www.netlifycms.org/docs/examples/ via a PR/edit link?

Example ? I think its better to add it to the https://www.netlifycms.org/docs/custom-widgets/
page 

What do you say ?

**Comment by erezrokah** [comment]
Adding SSG specific code to that part of the docs might confuse people not using Hugo.
How about https://www.netlifycms.org/docs/hugo/?

**Comment by sharadcodes** [comment]
> Adding Hugo specific code to that part of the docs might confuse people not using Hugo.
> How about https://www.netlifycms.org/docs/hugo/?

Yeah That page is fine, What should I do a PR ?

**Comment by barthc** [comment]
@sharadcodes  start you PR title with `fix`, `chore`,  `feat` or `security` depending on what your PR 
 is for, to add the labels.

**Comment by sharadcodes** [comment]
> @sharadcodes start you PR title with `fix`, `chore`, `feat` or `security` depending on what your PR
> is for, to add the labels.

No luck tried everything @barthc

**Comment by sharadcodes** [comment]
Done @barthc thanks
