### ISSUE TITLE
Netlify is incorrectly adding commit checks/creating deploys for feature branches

### ISSUE THREAD

**Issue by nick-funk** [netlify/netlify-cms#3861]
**Describe the bug**

I've configured Netlify to only deploy the master branch, but it has added commit checks to all of our feature branches and is also creating ghost deploys for them that are not tied to any real Netlify site.

I call them ghost deploys because it appears to have created a new site name called `stupefied-edison-a85716` that does not exist under our Netlify account (we only had a site named `sad-mclintock-0xa...` (since deleted in an attempt to wrest control of our repo back from Netlify).

These commit checks that have been added to target all the feature branches are failing (likely because the site they're deploying to doesn't exist and shouldn't be running). This is preventing us from getting features built and merged into our master branch.

This is all happening despite my explicitly selecting for Netlify to never deploy feature branches and only deploy the master branch.

**To Reproduce**

As far as I can tell, it worked for us like this:

1. Create a netlify app
2. Link it to GitHub repo
3. Tell it to only deploy the master branch
4. Remove all notifications
5. Do a manual deploy or two
6. Watch as it adds a bunch of commit checks to every branch in our GitHub repo
7. See that the commit checks fail on the feature branches
8. Check the logs for the failed commit checks
9. Get redirected to a link on Netlify for an app that doesn't exist

**Expected behavior**

- Set up Netlify to deploy only the master branch
- Have it only set commit checks/deploys on the master branch

**Screenshots**

Failing commit checks on a feature branch:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/5751504/83890653-49079780-a709-11ea-95d3-fbadf479b0b7.png">

Link to one of the failed deploy "ghost apps" logs:
https://app.netlify.com/sites/stupefied-edison-a85716/deploys/5eda5514dcbfcb0008157724
^ This is an app that doesn't really exist and shouldn't have been created

**Comment by erezrokah** [comment]
Hi @nick-funk thank you for reporting this issue.
Do you mind posting it under the Netlify community https://community.netlify.com?
This repo is intended for Netlify CMS related issues.

**Comment by nick-funk** [comment]
Hi @erezrokah, I can actually close this. Apparently someone was fiddling with an app and didn't let me know. This was purely user error, my mistake for not checking more thoroughly before posting an issue.

**Comment by erezrokah** [comment]
Thanks for the follow up!
