### ISSUE TITLE
Default Entries to display in the grid view instead of list

### ISSUE THREAD

**Issue by kylekirkby** [netlify/netlify-cms#3876]
Hi all,

I may have missed this in the documentation but it would be great if we could default collections to display in the _Grid View_ instead of the _List View_.

List View
![Screenshot from 2020-06-08 13-06-22](https://user-images.githubusercontent.com/4564433/84028621-f89e6d00-a988-11ea-803f-6dda5cbef229.png)

Grid View
![Screenshot from 2020-06-08 13-06-33](https://user-images.githubusercontent.com/4564433/84028611-f3d9b900-a988-11ea-8d2e-9fb5e1d61dba.png)

Best regards,

Kyle

**Comment by erezrokah** [comment]
Thanks @kylekirkby, view preference should be persisted between sessions - I think that is not the case at the moment
