### ISSUE TITLE
Unpublish is visible for collections with disabled delete

### ISSUE THREAD

**Issue by todinov** [netlify/netlify-cms#3887]
**Describe the bug**
When editorial workflow is enabled and a collection has `delete: false` the editor is still able to "unpublish" the entry, which essentially does a delete.

**To Reproduce**
1. Enable the editorial workflow
2. Set `delete: false` for a collection
3. Edit an entry in the same collection
4. See that there is an `Unpublish` option in the publish menu

**Expected behavior**
The editor should not see the `Unpublish` menu item.

**Comment by AbdallahAbis** [comment]
@erezrokah I can get this done if you think an entry shouldn't show the `unpublish` button if `delete: false` is set on the collection.
button renders here
https://github.com/netlify/netlify-cms/blob/65343c1238af85e9151abb6bbba3770a08091176/packages/netlify-cms-core/src/components/Editor/EditorToolbar.js#L396

https://github.com/netlify/netlify-cms/blob/65343c1238af85e9151abb6bbba3770a08091176/packages/netlify-cms-core/src/components/Editor/EditorToolbar.js#L539

We should add 
```
const canNotDelete = collection.get('delete') === false
...
(!canNotDelete && canPublish) && (
```

**Comment by erezrokah** [comment]
Thanks @AbdallahAbis, Looks like the button is enabled but will prevent the operation anyway:
https://github.com/netlify/netlify-cms/blob/65343c1238af85e9151abb6bbba3770a08091176/packages/netlify-cms-core/src/actions/editorialWorkflow.ts#L517
https://github.com/netlify/netlify-cms/blob/65343c1238af85e9151abb6bbba3770a08091176/packages/netlify-cms-core/src/backend.ts#L1203

So disabling it as the UI level makes sense

**Comment by AbdallahAbis** [comment]
@erezrokah thanks! Will tackle this tomorrow.

**Comment by AbdallahAbis** [comment]
@erezrokah Should I write a test for this? if yes, how?

**Comment by erezrokah** [comment]
> @erezrokah Should I write a test for this? if yes, how?

Maybe add a new Cypress spec for it? You can see an existing one here https://github.com/netlify/netlify-cms/blob/master/cypress/integration/editorial_workflow_spec_test_backend.js

and an example on how to update configuration (e.g. `delete: true` for a collection) here:
https://github.com/netlify/netlify-cms/blob/b8eea354795729f89e9603d1a8344cb52954bb92/cypress/integration/i18n_editorial_workflow_spec_test_backend.js#L10

**Comment by AbdallahAbis** [comment]
@erezrokah I'm not sure I can implement that. plus I'm getting
```
netlify-cms: [BABEL] Note: The code generator has deoptimised the styling of /Users/abdallahabis/Desktop/forked-netlify-cms/packages/netlify-cms-core/dist/esm/components/Editor/EditorToolbar.js as it exceeds the max of 500KB.
```

**Comment by erezrokah** [comment]
> plus I'm getting

That's a warning you can ignore.

For the tests, I think you can open a PR with your change and we can discuss it on the PR.

**Comment by AbdallahAbis** [comment]
@erezrokah PR in place
