### ISSUE TITLE
Allow drafts to be saved without passing validation

### ISSUE THREAD

**Issue by Benaiah** [netlify/netlify-cms#389]
**- Do you want to request a *feature* or report a *bug*?**

*feature*

**- What is the current behavior?**

If you have a partially-finished post, you can't save it, even if you're using the editorial workflow and trying to save a draft.

**- What is the expected behavior?**

In the editorial workflow you should be able to save, but not publish, drafts that do not pass validation.

**Comment by erquhart** [comment]
The only problem here is the potential for broken deploy previews.

**Comment by erquhart** [comment]
Overlaps with https://github.com/netlify/netlify-cms/issues/464, continuing discussion there.
