### ISSUE TITLE
"fields names must be unique" with 2.10.50, no change in config.yml

### ISSUE THREAD

**Issue by matteocargnelutti** [netlify/netlify-cms#3905]
**Describe the bug**
Trying to access `[url].netlify.app/admin/` using the latest version of Netlify CMS _(`2.10.50`)_ yields the following error:
```
Error loading the CMS configuration
Config Errors:
'collections[1].files[8].fields' fields names must be unique
Check your config.yml file.
```

- `config.yml` hasn't changed
- The issue only arises when using [Netlify CMS 2.10.50](https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js)
- Reverting to [Netlify CMS 2.10.49](https://unpkg.com/netlify-cms@2.10.49/dist/netlify-cms.js) fixes the issue.

**To Reproduce**
I unfortunately can't provide the `config.yml` in question.

**Screenshots**
<img width="579" alt="Screen Shot 2020-06-16 at 10 39 29 AM" src="https://user-images.githubusercontent.com/625889/84790052-ea6ed300-afbe-11ea-8999-7700986eadef.png">

**Applicable Versions:**
- `netlify-cms 2.10.50`
- `netlify-cms-core 2.28.0`
- `netlify-cms-app 2.12.14`

**Comment by erezrokah** [comment]
Hi @matteocargnelutti, can you share your full `config.yml`?
This is not a bug, but a new schema validation that was not checked previously - duplicate field names under the same collection will result in losing that information when the entry is persisted.

**Comment by matteocargnelutti** [comment]
Hi @erezrokah 

> can you share your full config.yml?
I unfortunately can't.

> This is not a bug, but a new schema validation that was not checked previously - duplicate field names under the same collection will result in losing that information when the entry is persisted.

Got it ! Turned out there was indeed a duplicate there, from a merge conflict resolution. 

Thanks a lot and sorry for the noise 👍

**Comment by erezrokah** [comment]
I'm glad the new validation is already paying off!
