### ISSUE TITLE
Search in files collections does not work

### ISSUE THREAD

**Issue by magomimmo** [netlify/netlify-cms#3907]
**Describe the bug**

Search does not take into account files collections. I'm not sure if this has to be considered a bug or a feature request. Considering that you collection menu allows to narrow the search in any type of collection, files collections included, and that the search returns `No Entries` when you search into files collections, I would consider it a bug.

**To Reproduce**

Just search into a any files collection

**Expected behavior**

I would expect the files collections being searchable, or, at least, to not allow you to narrow the search into them.

**Additional context**

I could migrate a file collection to a folder collection to make it searchable. That said, I did the opposite because of the relevant performance issue currently affecting the `relation` widget.

**Comment by felixboet** [comment]
Same here. search works fine for folder-collections, but not for file-collections.

expected result:
<img width="340" alt="Bildschirmfoto 2020-06-24 um 22 36 10" src="https://user-images.githubusercontent.com/62942125/85625310-8bb6f280-b66b-11ea-9b4f-5f13f73d566b.png">

result on relation to file-collection
<img width="316" alt="Bildschirmfoto 2020-06-24 um 22 36 21" src="https://user-images.githubusercontent.com/62942125/85625333-94a7c400-b66b-11ea-92b9-d9592cc2eae8.png">

**Comment by erezrokah** [comment]
Until recently one could only search in all collections so I think this was less evident.
