### ISSUE TITLE
Add instant preview

### ISSUE THREAD

**Issue by inwardmovement** [netlify/netlify-cms#3911]
**Is your feature request related to a problem? Please describe.**
Preview not really synced with the static site generator’s output.

**Describe the solution you'd like**
Take advantage of the static site generator’s built-in “watch” to update the preview pane.

**Describe alternatives you've considered**
\-

**Additional context**
https://forestry.io/docs/previews/instant-previews/ for reference

**Comment by erezrokah** [comment]
Hi @inwardmovement, can you please follow the feature template?

Linking to other resources that might change with time can make it difficult to understand the requested feature.

**Comment by inwardmovement** [comment]
Ok I edited

**Comment by erezrokah** [comment]
Netlify CMS runs in the browser and most of these `watch` features happen during build time and have file system access (which the CMS doesn't have).

Not sure what "preview not really synced with static site generator files" means.
If you're registering custom previews via https://www.netlifycms.org/docs/customization/
it is mostly up to your build setup to make sure they are updated per change.

**Comment by inwardmovement** [comment]
I cannot for now, I think we can close this issue and I'll reopen it when I can provide more details?
