### ISSUE TITLE
Interacting with Media library from Custom Widget

### ISSUE THREAD

**Issue by danielkellyio** [netlify/netlify-cms#3927]
**Describe the bug**
Not really a bug, but no good documentation that I can find on how to accomplish this. I'm building a custom widget and would like to interact with the MediaLibrary. I'd like open the Media library, select an image, get the value of the image, and a base64 encoded preview of the image from within my custom component

**Applicable Versions:**
netlify-cms-app 2.12.12
bootstrap.js:83 netlify-cms-core 2.26.0
index.js:27 netlify-cms 2.10.48
 - Git provider: Github
 - OS: MacOS
 - Browser version chrome

**Comment by erezrokah** [comment]
Hi @danielkellyio, I think the best resource at the moment would be to look at https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-widget-file/src/withFileControl.js

**Comment by danielkellyio** [comment]
I'm able to successfully call `this.props.onOpenMediaLibrary()` to open the media library but it doesn't contain the control to actually insert media

<img width="226" alt="Screen Shot 2020-06-23 at 5 19 41 PM" src="https://user-images.githubusercontent.com/7635209/85471249-cb031780-b575-11ea-8cca-a8e324081377.png">

is there some kind of option I should be passing?

Thanks!

**Comment by erezrokah** [comment]
You'll need to pass in a `controlID` so inserting a file can be linked back to the widget:
https://github.com/netlify/netlify-cms/blob/fb367f22dac6d57d2ae2b4cea270efd7d2a35982/packages/netlify-cms-core/src/reducers/mediaLibrary.ts#L70

https://github.com/netlify/netlify-cms/blob/fb367f22dac6d57d2ae2b4cea270efd7d2a35982/packages/netlify-cms-widget-file/src/withFileControl.js#L167

**Comment by erezrokah** [comment]
Closing as stale, please comment if still relevant
