### ISSUE TITLE
Integrating netlify-cms Identity with Vercel

### ISSUE THREAD

**Issue by thyagoweber-sevenapps** [netlify/netlify-cms#3928]
**Describe the bug**

I'm unable to make my dynamic generated NextJS blog to work in Vercel, even though I went through all the steps. I keep getting an Identity error.
- Hooked up the netlify-cms script into admin/index.html
- Created and configured correctly a config.yml file, setting git-gateway as backend name, the site domain, and the branch
- Was able to create a local_backend to test the settings

When I navigate to the `/admin/` path, a button labeled "Login with Netlify Identity" appears, I click on it and all I see is the message `"Unable to access identity settings. When using git-gateway backend make sure to enable Identity service and Git Gateway.`".

**Expected behavior**

To be able to log in and use the admin area

**Screenshots**

This is what I see in the network tab:
![Seleção_002](https://user-images.githubusercontent.com/58697921/85202991-e43f6600-b2e0-11ea-87ad-6bd9fb1fa8da.png)

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.10.50]
 - Git provider: GitHub
 - OS: Ubuntu 16.04

**CMS configuration**

```
backend:
  name: git-gateway
  branch: master
  site_domain: https://[username].vercel.app/

local_backend: true
publish_mode: editorial_workflow

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'

media_folder: /uploads

collections:
  - name: 'blog'
    label: 'Artigos'
    folder: 'posts'
    create: true
    delete: true

    slug: '{{slug}}'

    fields:
      - {
          label: 'Title',
          name: 'title',
          widget: 'string',
          required: true,          
        }
      - { label: 'Autor', name: 'author', widget: 'string', required: true }
      - {
          label: 'Category',
          name: 'category',
          collection: 'categories',
          widget: 'relation',
          required: true,
          searchFields: 'title',
          valueField: 'title',
          displayFields: ['title'],          
          default: 'Uncategorized',
        }
      - {
          label: 'Publish Date',
          name: 'publishDate',
          widget: 'datetime',
          required: true,          
        }
      - { label: 'Thumbnail', name: 'image', widget: 'image', required: true }
      - {
          label: 'Featured article?',
          name: 'featured',
          widget: 'boolean',
          default: false,          
        }      
      - { label: 'Corpo', name: 'body', widget: 'markdown', required: true }
```

**Additional context**

While I was following the integration steps, I created a Netlify account and could only see the Identity options after I linked my repo. Is this necessary, even though I'll be using another service do deploy it?

**Comment by erezrokah** [comment]
Hi @thyagoweber-sevenapps, identity is a backend service that providers user management and `git-gateway` is a backend service that allows accessing a GitHub/GitLab repo without a GitHub/GitLab account.
Netlify can provide those services for you and you can also self host them:
https://github.com/hfte/netlify-cms-with-selfhosted-gotrue-and-git-gateway

Another option is to use a [GitHub backend](https://www.netlifycms.org/docs/github-backend/) directly (or [GitLab](https://www.netlifycms.org/docs/gitlab-backend/)), but then any CMS user would need a GitHub/GitLab account.

If you use a GitHub backend you'll need a backend service to facilitate authentication either using Netlify as described [here](https://www.netlifycms.org/docs/github-backend/) or use one of these [external solutions](https://www.netlifycms.org/docs/external-oauth-clients/)

**Comment by pacxiu** [comment]
Some example with setting up authentication using - https://github.com/netlify/netlify-identity-widget for Vercel deployment would be great. I want to migrate 4-5 smaller, non-profit projects to use Netlify CMS and  I'm starting playing around with Netlify's services, however 300 mins/build time might not be enough for those so this is why I would also prefer to deploy them on Vercel without creating multiple custom authorization Apps on Github.

@thyagoweber-sevenapps as far as I can tell you have to have it linked on Netlify to use `Identity`. Probably based on linked repo there is system set up to publish in there on your behalf.

**Comment by erezrokah** [comment]
Thanks @pacxiu and sorry for the late reply. Closing this issue as resolved.
Manually configuring the identity widget is documented here (looks like you figured that one out already 😃):
https://github.com/netlify/netlify-identity-widget#netlifyidentityinitopts

**Comment by erezrokah** [comment]
@pacxiu another quick follow up - it would be great if you can share the build limits limitations you're experiencing with Netlify so we can see if there is something we can do to improve it.
A good place to post it is in our community https://community.netlify.com/ (and link the post from this issue).
