### ISSUE TITLE
Version 2.10.51 throws config errors

### ISSUE THREAD

**Issue by malinowskip** [netlify/netlify-cms#3933]
**Describe the bug**
The following config errors are thrown in version 2.10.51:
```
'collections[1].fields[6].fields[1]' should have required property 'name'
'collections[2].fields[7].fields[1]' should have required property 'name'
'collections[3].fields[6].fields[1]' should have required property 'name'
'collections[5].fields[6].fields[1]' should have required property 'name'
'collections[6].fields[8].fields[1]' should have required property 'name'
'collections[7].fields[6].fields[1]' should have required property 'name'
'collections[8].fields[7].fields[1]' should have required property 'name'
'collections[9].fields[7].fields[1]' should have required property 'name'
'collections[10].fields[7].fields[1]' should have required property 'name'
'collections[11].fields[7].fields[1]' should have required property 'name'
'collections[12].fields[6].fields[1]' should have required property 'name'
```
My site uses 15 collections in total.

Everything goes back to normal when I switch back to 2.10.50. Netlify CMS is loaded from a CDN and uses a GitLab backend (although the same error is thrown with a `test-repo`).

If it makes any difference, I am using YAML aliases in my config. 

**Applicable Versions:**
 - Netlify CMS version: 2.10.51
 - Git provider: GitLab, test-repo

**Comment by erezrokah** [comment]
Hi @malinowskip, can you share your `config.yml` or at least a subset of it?

We recently added some config schema validations, mostly for widgets fields configuration, so this is probably the cause.

**Comment by malinowskip** [comment]
Thanks, @erezrokah. You're right. I found a field that was missing a `name` and was previously being rendered as `undefined` in my front matter. This means that the newly-added schema validation is doing its job and the previous version was too lenient.

**Comment by erezrokah** [comment]
Cool, thanks for following up!
