### ISSUE TITLE
Add deploy preview links for GitLab backend

### ISSUE THREAD

**Issue by maxerbox** [netlify/netlify-cms#3942]
**Is your feature request related to a problem? Please describe.**
Deploy preview links are not supported with GitLab

**Describe the solution you'd like**
Add deploy preview links for GitLab

**Describe alternatives you've considered**
Going to GitHub.

**Additional context**
Related pull request : #2028
GitLab Statuses API : https://docs.gitlab.com/ee/api/commits.html#list-the-statuses-of-a-commit

**Comment by erezrokah** [comment]
Hi @maxerbox, this should be supported https://github.com/netlify/netlify-cms/blob/3025e5e8ff735fd1cfac686c2822c5b7d8b79935/packages/netlify-cms-backend-gitlab/src/API.ts#L853

Can you provide a reproduction detailing the steps you're taking and actual vs expected outcome?

**Comment by maxerbox** [comment]
The docs should be updated : https://www.netlifycms.org/docs/deploy-preview-links/
I'm closing the issue

**Comment by erezrokah** [comment]
https://github.com/netlify/netlify-cms/pull/3943
