### ISSUE TITLE
collection list is empty when using folder-collections-path and > 20 subfolders

### ISSUE THREAD

**Issue by betz** [netlify/netlify-cms#3950]
my collection list is always empty for one specific collection.
I have gitlab as backend and I use the 'path' collection parameter because my .md files are within their own dedicated dirs.
 
I see the request to gitlab is something like:
https://gitlab.com/api/v4/projects/foo%2Fbar/repository/tree?path=content%2Fpersons&ref=master&recursive=true

Which returns 20 items, the only 20 first directories.
If i add &per_page=100 to the gitlab request i see the directories and the first markdown files
that's what i guess goes wrong. it doesn't see a single markdown file in the initial request, so it thinks there are none, and doesn't page further

so, could i force it to use the per_page param in its initial request?

**Applicable Versions:**
 - netlify-cms-app 2.12.15
 - netlify-cms-core 2.29.0
 - Git provider: gitlab
 - OS: ubuntu 18.04
 - Browser version chrome Version 83.0.4103.97 
 - Node.JS version: v14.2.0

**Comment by erezrokah** [comment]
Partially related to https://github.com/netlify/netlify-cms/issues/2132.
Since we paginate the endpoints we need to make sure that after applying a filter (in the case of this issue we filter to return only files with a certain extension), we should traverse the pagination cursor until we have enough results.

**Comment by erezrokah** [comment]
A possible workaround - sorting the entries should load all of them

**Comment by betz** [comment]
the markdown files are in their own subdirs, using the 'path param' in netlify config
