### ISSUE TITLE
Accessing built in widgets in custom widgets

### ISSUE THREAD

**Issue by lpoulter** [netlify/netlify-cms#3974]
I couldn't find this documented anywhere is it possible?

**Comment by erezrokah** [comment]
Hi @lpoulter, can you share your use case?

**Comment by lpoulter** [comment]
I'm building a custom widget to add new "sections" of content to a site. I have a new section button that adds a new section each section contains a title, introduction and image.

I'd like to reuse the image widget. I can render that with 

`const ImageControl = CMS.getWidget("image").control`

But I'm not sure which props it need to be passed and how to manage updating the value in my own widget.

I've tried this sort of thing but value does not update in my custom widget.

```|
const { imagePath } = this.state   
const {
      forID,
      value = Map(),
      onChange,
      classNameWrapper,
      ...rest
    } = this.props


        <ImageControl
          value={imagePath}
          t={this.props.t}
          field={this.props.field}
          onChange={onChange}
          {...rest}
        />
```

**Comment by erezrokah** [comment]
Would using a list widget with variable types https://www.netlifycms.org/docs/beta-features/#list-widget-variable-types solve your use case?

**Comment by lpoulter** [comment]
Possibly is there a working example somewhere I can't get the config working from the docs.
``` 
Config Errors:
'collections[0]' should have required property 'files'
'collections[0]' should have required property 'folder'
'collections[0]' should have required property 'fields'
'collections[0]' should match exactly one schema in oneOf
```

**Comment by erezrokah** [comment]
Hi @lpoulter, you'll need to add that to an existing collection configuration:
https://www.netlifycms.org/docs/collection-types/#folder-collections
Can you share your full `config.yml`?

**Comment by lpoulter** [comment]
Hey I worked it out in the end. This article was really helpful
https://matthewshields.co.uk/netlify-cms-variable-types-gatsby
