### ISSUE TITLE
Add MR/PR Label Prefix Config Option

### ISSUE THREAD

**Issue by knoppiks** [netlify/netlify-cms#3977]
**Is your feature request related to a problem? Please describe.**
I'm using GitLab with scoped labels for my projects. As the suggestion is to name labels like `scope::label` I would like to be able to use the same style for my netlify-cms editorial workflow labels. At the moment the prefix for the editorial workflow labels is hard-coded to `netlify-cms/`.

**Describe the solution you'd like**
I would suggest a configuration option at least for the hosted Git Backends (GitLab, GitHub, Bitbucket) named `label_prefix` that is `netlify-cms/` per default but can be adjusted.

**Describe alternatives you've considered**

**Additional context**

**Comment by erezrokah** [comment]
Thanks @knoppiks, if anyone would like to work on this see:
https://github.com/netlify/netlify-cms/blob/c33db099ac56edfd993de0212a8085d8d9243ce4/packages/netlify-cms-lib-util/src/APIUtils.ts#L5

**Comment by KancerEzeroglu** [comment]
Hi, what is the current status of this issue?

**Comment by erezrokah** [comment]
Not currently on the radar of anyone if you're looking to contribute 😄

**Comment by KancerEzeroglu** [comment]
Then I would like to work on this :)

**Comment by KancerEzeroglu** [comment]
I am thinking 2 possible options for the solution:
- First option: 
Passing the prefix to APIUtils.ts from top to bottom. More specifically, I can add a config option to config.yml for label prefix and pass this information for all method calls until it hits the APIUtils
- Second option:
If I can find a way to access config.yml from APIUtils.ts, I can get this prefix easier. 

I prefer the second option, what do you think? 

If we will go with the second option, I need guidance for accessing config.yml. I see some packages access to the global config([here](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-media-library-uploadcare/src/index.js#L116)), should I do the same for this task?

**Comment by KancerEzeroglu** [comment]
I am thinking 2 possible options for the solution:
- First option: 
Passing the prefix to APIUtils.ts from top to bottom. More specifically, I can add a config option to config.yml for label prefix and pass this information for all method calls until it hits the APIUtils
- Second option:
If I can find a way to access config.yml from APIUtils.ts, I can get this prefix easier. 

I prefer the second option, what do you think? 

If we will go with the second option, I need guidance for accessing config.yml. I see some packages access to the global config([here](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-media-library-uploadcare/src/index.js#L116)), should I do the same for this task?

**Comment by erezrokah** [comment]
Hi @KancerEzeroglu, I think you would need to go with the first option.
`APIUtils.ts` are just utility functions and should not have access to the entire config or should be able to read `config.yml` (regardless we also allow initialisation via JavaScript without a `config.yml` https://www.netlifycms.org/docs/beta-features/#manual-initialization).

The link you provided is for media libraries extensions which work similar to the backends (the config is passed to them).
You can see an example here:
https://github.com/netlify/netlify-cms/blob/277a7117a84f4141fbd4af94774c6806e9ff2648/packages/netlify-cms-backend-github/src/implementation.tsx#L113

Following the same pattern should work. WDTY?

**Comment by KancerEzeroglu** [comment]
I agree with you and working on this. fyi

**Comment by KancerEzeroglu** [comment]
Just for the update, I've finished the GitHub part. I need to make an extra one more test. After that, I'll send a PR. And after everything is fine, I'll do the same things for Bitbucket, GitLab, and so on.
