### ISSUE TITLE
Allow netlify-cms-proxy-server to programmatically initialized

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#3980]
**Is your feature request related to a problem? Please describe.**

I'd like to integrate the proxy server into development flows, Eg., in an 11ty plugin. The server currently initializes immediately, making it difficult to use conditionally outside of the CLI.

**Describe the solution you'd like**

Keep the current behavior via binary, but when required programmatically, provide a method for controlling startup and shutdown of the server.

**Describe alternatives you've considered**

Dynamic imports, but would rather not rely on that for this.

**Comment by erezrokah** [comment]
We export the server functionality as an express middleware, so I believe this is already allowed.
For Gatsby one could use:
```js
const { registerLocalFs } = require('netlify-cms-proxy-server/dist/middlewares');

exports.onCreateDevServer = async ({ app }) => {
  await registerLocalFs(app);
};
```

For 11ty this should work:
```js
const express = require("express");
const {
  registerLocalFs,
} = require("netlify-cms-proxy-server/dist/middlewares");

const app = express();

module.exports = function (eleventyConfig) {
  registerLocalFs(app);

  eleventyConfig.setBrowserSyncConfig({
    middleware: [app],
  });
};
```

Note that in both cases you'd probably need to update `config.yml` to:

**Gatsby**
```yaml
local_backend:
  url: http://localhost:8000/api/v1
```

**11ty**
```yaml
local_backend:
  url: http://localhost:8080/api/v1
```

**Comment by erezrokah** [comment]
Closing, please re-open if relevant
