### ISSUE TITLE
Specific media folders for collections

### ISSUE THREAD

**Issue by aperep** [netlify/netlify-cms#399]
It would be awesome to specify its own media_folder for each collection.

**Use case**
A lot of collections consist of chunks of information of different nature with an image attached to each one. 

**Examples:**
* carousel,
* partners' logos,
* testimonials,
* site specific collections.

**Request**
It is plausible to keep images for each collection in a separate folder. This will require either to specify a `media_folder` parameter for each collection separately, or to specify a folder to the field with a widget `image`.

**Comment by erquhart** [comment]
This may be implemented as a part of #350. Keeping open for now.

**Comment by aperep** [comment]
It seems that #350 will take a lot of effort to come into reality. 
May I bump my request to allow its own media folders for collections? It should be relatively simple. Maybe, I'll succeed to produce a viable pull request.

**Comment by erquhart** [comment]
@aperep #350 came out just after your comment, ironically. We'd definitely like to move to asset collections soon after 1.0, which will be out in early December.

**Comment by erquhart** [comment]
Closing in favor of #1046 since discussion is moving on that one.
