### ISSUE TITLE
'collections[0].view_filters' should NOT have fewer than 1 items when NOT using view_filters

### ISSUE THREAD

**Issue by AJTJ** [netlify/netlify-cms#3991]
**Describe the bug**
I'm using the `netlify-cms-app` in order to leverage the cms as a static route within my `react-static` app. I'm very much using this experience as a template => https://formidable.com/blog/2020/oss-cms/

I'm using the `netlify-cms-proxy-server`

For some reason I keep getting this error when I am NOT using `view_filters` at all.
```
Error loading the CMS configuration
Config Errors:
'collections[0].view_filters' should NOT have fewer than 1 items
'collections[0].meta' should NOT have fewer than 1 properties
'collections[1].view_filters' should NOT have fewer than 1 items
'collections[1].meta' should NOT have fewer than 1 properties
Check your config.yml file.
```

My `config.js` file looks like this:

```
module.exports = {
  backend: {
    name: "proxy",
    proxy_url: "http://localhost:8081/api/v1",
    branch: "master" /* optional, defaults to master */,
  },
  media_folder: "public/uploads",
  public_folder: "/uploads",
  collections: [
    {
      name: "blog",
      label: "Blog Post",
      folder: "src/_blog-posts",
      create: true,
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}",
      fields: [
        { label: "Layout", name: "layout", widget: "hidden", default: "blog" },
        { label: "Title", name: "title", widget: "string" },
        { label: "Publish Date", name: "date", widget: "datetime" },
        {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
        },
        { label: "Body", name: "body", widget: "markdown" },
        { label: "test button", name: "testButton", widget: "string" },
      ],
    },
    {
      name: "events",
      label: "Event",
      folder: "src/_events",
      create: true,
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}",
      fields: [
        { label: "Layout", name: "layout", widget: "hidden", default: "event" },
        { label: "Title", name: "title", widget: "string" },
        { label: "Publish Date", name: "publish_date", widget: "datetime" },
        { label: "Event Date", name: "event_date", widget: "datetime" },
        { label: "Featured Image", name: "thumbnail", widget: "image" },
        { label: "Body", name: "body", widget: "markdown" },
      ],
    },
  ],
};
```
My understanding is that `view_filters` is optional, and that `meta` is not even something that can be updated.

**Comment by AJTJ** [comment]
This error doesn't come up all the time. But if I make changes to my config.js, it will definitely come up.

**Comment by erezrokah** [comment]
Hi @AJTJ, can you share your `config.yml` as well and the way you initialise the CMS with the `config.js` file?
A link to the site/repo would help too

**Comment by AJTJ** [comment]
@erezrokah I don't have a `config.yml` (well, I do, but everything is commented out)
the repo is here: https://github.com/AJTJ/ylc_website

Here is how I've initialized the CMS: https://github.com/AJTJ/ylc_website/blob/master/src/CMS/index.js

And it is loaded as a static route here (through `react-static`):
https://github.com/AJTJ/ylc_website/blob/master/static.config.js

**Comment by erezrokah** [comment]
Same comment as https://github.com/netlify/netlify-cms/issues/3996#issuecomment-658061682

**Comment by erezrokah** [comment]
Closing due to https://github.com/netlify/netlify-cms/issues/3996#issuecomment-662981049
