### ISSUE TITLE
Editor view Collection/back button goes back in browser history

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#3994]
**Describe the bug**

Pressing the Collection/back-arrow button in the CMS Editor UI causes the browser to go to the last page in history (even if it's outside of the CMS) rather than going back to the collection view. For sites that link directly into the editor, this provides no UI method for returning to the collection view.

**To Reproduce**

1. Follow this link to open an entry in the CMS demo: https://cms-demo.netlify.com/#/collections/posts/entries/2020-07-09-post-number-20
2. Click the Collection/back-arrow button in the top left
3. Arrive back at this page on GitHub

**Expected behavior**

To go back to the collection view

**Additional context**

I don't believe it always worked this way, and there may have been a reason for the change, but I'm not seeing one.

**Comment by erezrokah** [comment]
The reason for the change was to maintain the filter status when exiting the editor (we use it to display a subset of the entries in nested collections).

Another option would be to keep the routing state in redux and use that (a bigger change) or pass in the filter param down to the editor as a prop for the sake of appending it to the path when clicking the exit

**Comment by erquhart** [comment]
Ah, that makes sense. If passing the prop is a small change it might be worth doing.

**Comment by erezrokah** [comment]
A workaround would be to open the editor in a new tab (`Axway` doest it by default)
