### ISSUE TITLE
Attempting to use `list` widget and it demands a `fields` value

### ISSUE THREAD

**Issue by AJTJ** [netlify/netlify-cms#3996]
`fields` should be optional, shouldn't it?

```
Error loading the CMS configuration
Config Errors:
'collections[3]' should have required property 'files'
'collections[3]' should have required property 'fields'
'collections[3]' should match exactly one schema in oneOf
Check your config.yml file.
```

**Comment by barthc** [comment]
@AJTJ  that error is for your collection not list widget, can you share your config?

**Comment by AJTJ** [comment]
I don't have a `config.yml` (well, I do, but everything is commented out)
the repo is here: https://github.com/AJTJ/ylc_website

my `config.js` (instead of the `config.yml`) is here:
https://github.com/AJTJ/ylc_website/blob/master/src/CMS/config.js

Here is how I've initialized the CMS: https://github.com/AJTJ/ylc_website/blob/master/src/CMS/index.js

And it is loaded as a static route here (through `react-static`):
https://github.com/AJTJ/ylc_website/blob/master/static.config.js

**Comment by erezrokah** [comment]
Hi @AJTJ, not sure how your site (can you link to it?) is set up but I would delete `https://github.com/AJTJ/ylc_website/tree/master/admin` if they are not required.
Also to completely ignore the `config.yml` you need to pass `load_config_file: false`.
See example here:
https://www.netlifycms.org/docs/beta-features/#manual-initialization

**Comment by AJTJ** [comment]
@erezrokah in that example you shared they aren't using `netlify-cms-app`, but I added that line and it didn't seem to change anything. I linked to the site above your comment. If you are asking if it is available online, it is not. Still in production. :)

**Comment by erezrokah** [comment]
I'm able to load the site successfully:
![image](https://user-images.githubusercontent.com/26760571/88286788-f6eef580-ccf9-11ea-91a8-7b8384e59b48.png)

I assume you fixed the issue with your site, closing. Please comment if still relevant
