### ISSUE TITLE
Nuxt/Netlify Docs: Nuxt Generate step is out of date since Nuxt v2.13

### ISSUE THREAD

**Issue by ARuzek** [netlify/netlify-cms#4003]
**Describe the bug**
Step 1 of documentation guide `npx create-nuxt-app <name-of-your-new-project>` will create using Nuxt v2.13 which replaces the `nuxt generate` with` nuxt build && nuxt export` leading to issues with the next steps including:

1. setting up Netlify with the current build step
2. the very last step of updating the generate property 

**To Reproduce**
Follow the current docs at https://www.netlifycms.org/docs/nuxt/ to reproduce

**Expected behavior**
User should be able to follow directions in docs to produce a working Netlify CMS instance on their Nuxt application.

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: following current docs, Netlify CMS is from CDN `<script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>` resulting in:

- netlify-cms-app 2.12.16
- netlify-cms-core 2.30.0
- netlify-cms 2.10.52

 - Git provider: GitHub
 - OS: Windows 10
 - Browser version : Chrome 83
 - Node.JS version: 10.16.0

**CMS configuration**
n/a

**Comment by erezrokah** [comment]
We would love a PR for this

**Comment by ARuzek** [comment]
@erezrokah Sure, docs updated in #4035
