### ISSUE TITLE
User's Session indicator in the CMS panel

### ISSUE THREAD

**Issue by krzysiekhum** [netlify/netlify-cms#4058]
Hello! 👋 

**Our editors sometimes have problems with user sessions using Netlify CMS.** They edit blog posts and in some cases their sessions end.

**I think that would be good option to add an information about active session in top bar.** It could be useful!

**Comment by erezrokah** [comment]
@krzysiekhum thanks for opening this issue.
I think this was covered in https://github.com/netlify/netlify-cms/pull/3847 as the CMS periodically checks if the session is still active and will prompt the user to logout and login if it expires.

**Comment by erezrokah** [comment]
Closing, please comment if you think this is still relevant
