### ISSUE TITLE
Better editor needed

### ISSUE THREAD

**Issue by davegardner** [netlify/netlify-cms#4062]
The problem with the editor is that it is confused about whether you need to understand markdown or not. If I understand markdown then all I need is a plain text editor -- that's why markdown was invented, as a way to concentrate on the content and eliminate the clutter of html!  On the other hand, if I am an artist wanting to edit my most recent post then I want a simple gui editor and I DO NOT want to have to learn markdown or be exposed to it in any way. The current UI tries to do both in a really confusing way.

I am not a fan of markdown as a universal format. It is great for technical people; off-putting for someone used to wysiwyg editors only. There should be a simple wysiwyg editor in Netlify CMS because it is aimed at non-technical people. The back-end format should be irrelevent to the end user.

Something like the Syncfusion HTML5/JavaScript Rich Text Editor (I know, it's commercial, but maybe there are opensource alternatives).

**Comment by erezrokah** [comment]
Hi @davegardner, can you please follow the issue template?
I'm not sure if this is a bug report or a feature request.

Some clarifications are needed:
1. Does the current raw (markdown) editor suits technical people? If not, what's missing.
2. Does the current rich text edit editor suits non technical people? If not, what's missing.
3. Not sure I understand the context of:
> The back-end format should be irrelevent to the end user

as the CMS doesn't expose that to users.

**Comment by davegardner** [comment]
Sorry for the gripe and thanks for listening. I will try to be more specific:
1. The Raw Markdown editor is fine for tech people like us.  But as soon as 'Markdown' is mentioned to people who regard themselves as non-techies the shutters go up and I cannot get them to use it.

2. So non-techies must use the Rich Text Editor, which is horrible. 
  - Links cannot be inserted. I have to switch to Markdown editor to enter them.
  - I can enter code but must switch to Markdown to specify the language (I might use 'code' for special formatting).

3. How do I save a draft? Can you? It seems the only option right now is to publish? That's unacceptable. It means that for any site that requires content review, the review must be done beforehand, meaning an editor isn't even required except for cut and paste, which is via Markdown.

4. Image panel UI is a bit weird and has no 'save' or 'delete' options. 

5. By 'underlying format' I meant the markdown, which obviously **is** exposed.

I hope that makes the issue clearer.

Dave.

**Comment by erezrokah** [comment]
I appreciate the follow up.

> * Links cannot be inserted. I have to switch to Markdown editor to enter them.

Can you please open a bug for this?

> * I can enter code but must switch to Markdown to specify the language (I might use 'code' for special formatting).

You can choose the language using the code block editor component:
![image](https://user-images.githubusercontent.com/26760571/88475221-8d0f5f80-cf36-11ea-97e1-9a5c8a8142a0.png)
![image](https://user-images.githubusercontent.com/26760571/88475207-81239d80-cf36-11ea-980d-b7aed1366a9b.png)

For inline code, not sure how that can be done yet (which UI and format we should use), but a feature request for it will be great.


> How do I save a draft? Can you?

You can use `editorial_workflow` mode: https://www.netlifycms.org/docs/configuration-options/#publish-mode


> Image panel UI is a bit weird and has no 'save' or 'delete' options.

Can you please elaborate?
Are you referring to the Media Library Modal:
![image](https://user-images.githubusercontent.com/26760571/88475367-c399aa00-cf37-11ea-8f5f-060b237bcd1d.png)
Or the field UI:
![image](https://user-images.githubusercontent.com/26760571/88475369-d1e7c600-cf37-11ea-85ea-a3843d410203.png)

This might be better discussed [here](https://github.com/netlify/netlify-cms/issues/2557) and [here](https://github.com/netlify/netlify-cms/issues/2243).
In the same context, media files are committed to the repo with the entry data in a single commit and are not saved immediately.


> By 'underlying format' I meant the markdown, which obviously **is** exposed.

Not sure how this can be handled, maybe by adding an option to hide the different modes?

**Comment by joyously** [comment]
Related: I tried this for the first time by clicking on the Edit link from the docs, and I immediately messed up the links. It seems that clicking on the link icon in Rich mode removes the link. I couldn't see a way to edit the link. So now that the link is gone, I wanted to undo that, and couldn't find an Undo option anywhere. I saw that if I switched to Markdown, I could see the link and edit it, but I didn't know that at first.

As for having Markdown only, I was glad to see that the page that I was editing contained HTML in order to get the logos and the buttons to start a template in various ways. So it shows that you can mix HTML with Markdown, whereas the editor itself doesn't let you know that...only the example page showed that.

**Comment by erezrokah** [comment]
After re-reading the discussion I can't seem to think of any actionable item to extract from it. 
Please comment if still relevant

**Comment by joyously** [comment]
I think this is actionable:
> clicking on the link icon in Rich mode removes the link
> couldn't find an Undo option anywhere

**Comment by erezrokah** [comment]
Thanks @joyously do you mind opening new separate issues for those?
The undo functionality is available via keyboard shortcuts, but adding a button for it is a good idea.

**Comment by everythingcivil** [comment]
Being a technical blogger, edit still lacks, such as 

1. Tables
2. Highlighting text, font color, size, text alignment, subscripts, superscripts
3. Entering math equations, etc.

How to include in the editor?
