### ISSUE TITLE
Using VIEW_STYLE_GRID 

### ISSUE THREAD

**Issue by henval2020** [netlify/netlify-cms#4067]
Is there documentation on how to use or customized the VIEW_STYLE_GRID?
![image](https://user-images.githubusercontent.com/64128179/88388826-d56c3780-cde7-11ea-9454-7552642c9716.png)
I was able to display an image on the Grid view when I set the field "**name**" into "**image**" but when I change it to something else it doesn't work. Does it only work on name: image ?

It is working when I upload the image in here
- {label: "Main Image",    
        name: 'image',
        widget: 'image',
        required: false,
        tagname: ''}
![image](https://user-images.githubusercontent.com/64128179/88388990-2da33980-cde8-11ea-89a3-6bf2d08db7ec.png)

But when I try it here 
![image](https://user-images.githubusercontent.com/64128179/88389183-8c68b300-cde8-11ea-96ec-3d4a2bf0a533.png)

It does not work.
What I tried to do is changing the EntryListing.js into these 3 different approaches. But nothing works.

```
const imageField = selectInferedField(collection, 'more_assets.desktop_image');
const imageField = selectInferedField(collection, 'more_assets[desktop_image]');
const imageField = selectInferedField(collection, 'more_assets[0]desktop_image');
```

**Comment by erezrokah** [comment]
Very good question @henval2020.
We're inferring the image field so any one of the values here:
https://github.com/netlify/netlify-cms/blob/460d1e6835af122f86278b4b2f9c2e3b7bc91488/packages/netlify-cms-core/src/constants/fieldInference.tsx#L63
should work.

I think a good approach will be to implement https://github.com/netlify/netlify-cms/issues/2868.
Another thing we should do is to make inference configurable (related to https://github.com/netlify/netlify-cms/issues/445).

Closing, please comment if more information is needed

**Comment by henval2020** [comment]
Thank you so much @erezrokah. It works now, I was able to retrieve the newly added fields like this.
![image](https://user-images.githubusercontent.com/64128179/88526367-73514380-d02e-11ea-8396-070e688a52a6.png)

By updating this part
![image](https://user-images.githubusercontent.com/64128179/88526507-97ad2000-d02e-11ea-897e-9d7cc4c8e1c0.png)

Last question for this if I may,

I tried to fill out the mobile image instead of desktop but it seems like the **imageField** returns **desktop_image** value on EntryListing.js
![image](https://user-images.githubusercontent.com/64128179/88527513-f626ce00-d02f-11ea-8eed-03d74b76c060.png) 

Then I tried this (setting a hardcoded mobile_field)
`const imageField = selectInferedField(collection, 'image');` into const imageField = **'mobile_image'**
Then mobile image was retrieved. 

I also noticed that when I switch the position of the fields on my config.yml, without changing the `const imageField = selectInferedField(collection, 'image');` Mobile images were retrieved.
![image](https://user-images.githubusercontent.com/64128179/88527896-7816f700-d030-11ea-8468-3fb946d308a1.png)

The main question is, is there a way that I can set the **desktop_image** as the fallback of an image when **mobile_image** is not available (no image were uploaded on mobile_image field)
I also tried setting the field fallbackToFirstField to true but it doesn't do the trick. Am I missing something here
![image](https://user-images.githubusercontent.com/64128179/88528896-d09ac400-d031-11ea-8d10-e9cd691caaf0.png)

**Comment by erezrokah** [comment]
The inference code only looks at field names in the configuration and not their values, so the solution has to be somewhere else.
You could create a new function called `selectInferedFields` to return all possible fields, then use it here:
https://github.com/netlify/netlify-cms/blob/04ccb56e668ce24372675b8e937c773215a6d2d6/packages/netlify-cms-core/src/components/Collection/Entries/EntryListing.js#L43
Then implement the fallback here:
https://github.com/netlify/netlify-cms/blob/04ccb56e668ce24372675b8e937c773215a6d2d6/packages/netlify-cms-core/src/components/Collection/Entries/EntryCard.js#L127

Doing https://github.com/netlify/netlify-cms/issues/2868 however can provide more flexibility in the future

**Comment by henval2020** [comment]
Awesome! I missed checking the EntryCard.js. Thank you so much for your help @erezrokah . I was able to create a fallback with this.
![image](https://user-images.githubusercontent.com/64128179/88606796-3037b480-d0b0-11ea-9cbc-be5c7144ac5a.png)

It's messy right now, but I'll try to refactor this. cheers!
