### ISSUE TITLE
Event callback for post removal?

### ISSUE THREAD

**Issue by thyagoweber-sevenapps** [netlify/netlify-cms#4088]
I self-hosted a comments and likes solution for my netlify-cms blog and I need to remove these likes and comments from my DB when a post gets removed. 

I noticed there's a [callback for post unpublishing](https://www.netlifycms.org/docs/beta-features/#registering-to-cms-events), and it seems this is the place where I should call my post removal endpoint.

Now, to the question: is this callback called only when an item/post is removed from the CMS? I don't want this endpoint to be called on post editing or when the post editorial workflow changes, for example.

**Comment by erezrokah** [comment]
The callback is only called on entry removal:
https://github.com/netlify/netlify-cms/blob/a4b7481a99f58b9abe85ab5712d27593cde20096/packages/netlify-cms-core/src/backend.ts#L1126

It's not called when an entry is edited or changed.

Closing, please comment if more information it needed

**Comment by thyagoweber-sevenapps** [comment]
Awesome! Thanks!
