### ISSUE TITLE
I'm trying to add a timeline to my website. How can I add the following code to the Netlify CMS?

### ISSUE THREAD

**Issue by FGPiano** [netlify/netlify-cms#4089]
Hi,

As the title says, I'm trying to add this timeline to my website: https://codyhouse.co/gem/horizontal-timeline/?

Would I add it by copy-pasting the code into a code block in a text module? Or as html code in the markup of a text module? Or am I totally lost? Ha,

Thank you!

**Comment by erezrokah** [comment]
Hi @FGPiano, the CMS is designed to manage content so I would create a collection to manage the timeline events.
You could have a [folder collection](https://www.netlifycms.org/docs/collection-types/#folder-collections) with multiple entries, or a [file collection](https://www.netlifycms.org/docs/collection-types/#file-collections) with a [list widget](https://www.netlifycms.org/docs/widgets/#list).

Then you could create a build step to transform that content to the required `html` structure

**Comment by FGPiano** [comment]
Hi @erezrokah, thank you very much for the response. I really appreciate it. What is a "build step" and how would I create one? The file I downloaded from the timeline website already has the html structure for timeline. Thank you again.

**Comment by erezrokah** [comment]
Usually one would manage content via the CMS then have some kind of script (build step) to transform that content to `html`.
You can try one of the templates https://www.netlifycms.org/docs/start-with-a-template/ to get a better sense of it.

**Comment by FGPiano** [comment]
I already have the script, I believe, through the website the provided the timeline. Where would I post the script?

Thank you!

**Comment by erezrokah** [comment]
@FGPiano, do you have an existing/example repo that you can share?

**Comment by FGPiano** [comment]
@erezrokah My website I'm trying to install this timeline in is: fgpianoschool.com; the html/code for the timeline is on the website I sent earlier (https://codyhouse.co/gem/horizontal-timeline/); I use the Netlify CMS to update content (text and organization of features); and, I use Cloudinary to store media I use on my site (pictures and videos).

I really appreciate all the help :)

**Comment by erezrokah** [comment]
Hi @FGPiano,
It is hard for me to provide an answer without more details on how your site is configured.
In general you would create content with the CMS and generate the HTML using a script.
I would start by using the example code in https://codyhouse.co/gem/horizontal-timeline/ in your site with the sample data.
Then find the right place to modify it in your script (you can try and search how the other content on the site is generated).

**Comment by erezrokah** [comment]
Closing as this is not a CMS issue
