### ISSUE TITLE
post created - published - on github - don't show up in generated site

### ISSUE THREAD

**Issue by joachimVdH** [netlify/netlify-cms#4093]
While setting up a site and testing post through Netlify CMS, I already notices a few times that post don't show up.

I posted on mondayevening a post through cms 
- got to github ( https://github.com/joachimVdH/TVG-Jekyll-NetlifyCMS/blob/master/_posts/2020-07-27-maandagavond-test-23-40.md ) 
- netlify is triggered
<img width="1219" alt="Schermafbeelding 2020-07-29 om 08 23 52" src="https://user-images.githubusercontent.com/33933/88764314-072d2780-d175-11ea-8cdd-af40208e11c7.png">
- but none shows up : https://optimistic-babbage-aebc91.netlify.app/nieuws

currently I don't know where to start, looking for an anwser or where to best file a bug, since I don't see to what it's related.

thanks in advance

**Describe the bug**

**To Reproduce**

post a blogitem-news item through CMS

**Expected behavior**

that is published through netlify a few minutes later

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: can't find it - https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js
 - Git provider: GitHub
 - OS: Macos catalina 10.15.6
 - Browser version firefox 78.0.1

 - Node.JS version:

**CMS configuration**

https://github.com/joachimVdH/TVG-Jekyll-NetlifyCMS/blob/master/admin/config.yml

**Additional context**

**Comment by erezrokah** [comment]
Hi @joachimVdH, I can see the post when running locally:
![image](https://user-images.githubusercontent.com/26760571/88903369-44b8b000-d25c-11ea-966a-c50eb1e1d350.png)

So this is probably not a CMS issue.
I would try running the build again with clearing cache or ask in the Netlify community (if you haven't done so yet).

**Comment by erezrokah** [comment]
Closing, please comment if still relevant
