### ISSUE TITLE
Editing records on relation widget causes duplicate on dropdown

### ISSUE THREAD

**Issue by henval2020** [netlify/netlify-cms#4098]
Not sure if I just had a misconfiguration on my config.yml but this is how I configure my relation widget

Let's call this "Cta page"
![image](https://user-images.githubusercontent.com/64128179/89098697-74aeb180-d41c-11ea-960f-32171feb70ee.png )

Then I called it like this on another page. let's call it "Content page"
![image](https://user-images.githubusercontent.com/64128179/89098694-68c2ef80-d41c-11ea-818e-0cfa82820660.png)

Everything is working as expected, I was able to create new "labels" on the Cta page and call it on "Content page" then save the record.
The issue is when I try to edit that specific "label" (on CTA page) then go to edit a record that uses that label on the Content page, it shows a duplicate record of the updated label.
![image](https://user-images.githubusercontent.com/64128179/89098625-dc183180-d41b-11ea-8393-b8e59735a847.png)

**Comment by henval2020** [comment]
I'm sorry about this one @erezrokah, I think the main issue on this one is the slug one the 'newlabel'. 
Instead of using **{{en}}** I used **'en'**. Maybe we can tag this now as closed?

**Comment by erezrokah** [comment]
Thanks @henval2020, closing the issue

**Comment by henval2020** [comment]
Hi @erezrokah, can we reopen this one? Seems like this issue is intermittent. There are times that the issue still occurs even if the slug is not being updated on relation widget.

What I thought that was working is the initial load of the page, when there is no selected value on the dropdown of the relation widget, it works fine. Like this one on the screenshot below.

![image](https://user-images.githubusercontent.com/64128179/89387612-535c0700-d735-11ea-8a86-2f8f27b4ecce.png)

After publishing it and browser refresh this is what I got.
![image](https://user-images.githubusercontent.com/64128179/89386813-3115b980-d734-11ea-9107-e3dccd292d14.png)

What I did are the following to replicate the issue.
1. select any value from relation widget (in my case I only set the one record on relation widget )
2. publish
3. refresh the page

So, even without editing the record on relation widget, this happens.

**Comment by henval2020** [comment]
Hi @erezrokah, These are my current findings on this issue.

Using **slug** as **slug: '{{slug}}'** instead of **'{{en}}'**
Tried to use the **identifier_field** to declare the 'en' as the identifier. Not sure though if I use it correctly. (Can't make this to work on my end.)

What is working is setting the slug as **{{slug}}** or adding a new field **title** based on the documentation

![image](https://user-images.githubusercontent.com/64128179/89706178-d4193e00-d995-11ea-9b05-9420f1477499.png)

Hope this helps and for others to see.

**Comment by henval2020** [comment]
Seems like it's just some misconfiguration on our part. Thanks. Fixed after using {{slug}} instead of the field {{en}}
Closing this issue. Thanks again.
