### ISSUE TITLE
subcollections

### ISSUE THREAD

**Issue by JFingert** [netlify/netlify-cms#410]
Feature Request:
"subcollections" - or the ability to access other collections from within a collection.

Current Behavior:
Example - While editing entries in my "blogpost" collection, I can't access my "users" collection for author choices.

Expected Behavior:
The ability to access other collections from within a collection.

**Comment by erquhart** [comment]
@JFingert the relation field does this, but is sadly undocumented. I gave a quick explanation in an issue comment recently: https://github.com/netlify/netlify-cms/issues/192#issuecomment-311133616

Hope it helps! Join us on [Gitter](https://gitter.im/netlify/netlifycms) if you have questions.
