### ISSUE TITLE
Editor: add option to enforce Markdown editing and remove Rich Text toggle

### ISSUE THREAD

**Issue by zyv** [netlify/netlify-cms#4112]
**Is your feature request related to a problem? Please describe.**

I would like to enforce Markdown editing in the editor widget (the way it works on GitHub) and prevent editors from copy & pasting garbage in the rich text editor component.

**Describe the solution you'd like**

Currently there is a toggle to switch between Markdown and Rich Text, but I couldn't find a way to disable this toggle and simply enforce Markdown editing.

/cc @pchorus @dniggemann

**Comment by zyv** [comment]
Apparently was considered in #1304 at some point, but then got abandoned?

**Comment by pchorus** [comment]
Hi @erezrokah I would like to help with this one. I opened the draft PR #4217 just to make a proposal of how it could work.
Please share your thoughts on this approach.
As soon as we can agree on an approach I will add some tests.

**Comment by zyv** [comment]
@erezrokah @pchorus closing this, as apparently you guys sorted it out :) many thanks ❤️

**Comment by somdoron** [comment]
what was the solution?

**Comment by pchorus** [comment]
There is a new option `mode` for markdown widgets taking an array of allowed values `raw` or `rich_text`. Please see [Docs](https://www.netlifycms.org/docs/widgets/#markdown) for more information.
If you allow only one of both, the toggle does not appear in the ui.
