### ISSUE TITLE
Builds of multiple sites have suddenly stopped working at the same time (Aug 6)

### ISSUE THREAD

**Issue by BURROO** [netlify/netlify-cms#4118]
I am working on three different gatsby site simultaneously and they all suddenly fail to build as of today.
There seems to be an isse with finding the right package modules, but the errors seem random and vary from build to build
For example:

```
12:27:12 PM: error An unexpected error occurred: "https://registry.yarnpkg.com/@wordpress/api-fetch/-/api-fetch-3.17.0.tgz: Request failed \"404 Not Found\"".
```

or

```
12:15:42 PM: Error: Couldn't find package "@reach/router@^1.3.4" required by "gatsby@^2.24.8" on the "npm" registry.

```

When I try to rebuild old deploys they also don’t work.
I basically not able to build anymore in multiple projects with builds that worked previously …
Everything works as expected locally.

**Comment by erezrokah** [comment]
Hi, this doesn't seem to be an issue with Netlify CMS and most likely related to an incident with npm:
https://status.npmjs.org/

**Comment by BURROO** [comment]
Thank you for the reference. I was not aware of this.
Everything works as expected again.
