### ISSUE TITLE
Unhandled Rejection (TypeError): r.toJS is not a function

### ISSUE THREAD

**Issue by krzysiekhum** [netlify/netlify-cms#4119]
<img width="1038" alt="Zrzut ekranu 2020-08-6 o 14 52 54" src="https://user-images.githubusercontent.com/13885484/89534203-ddb77000-d7f4-11ea-8e35-f3561ce7db76.png">

Related article form contains the relational widget and after a few seconds complete pages goes to the error screen (as above)

"netlify-cms": "^2.10.55",
"netlify-cms-app": "^2.12.19",

**Comment by erezrokah** [comment]
Hi @krzysiekhum, can you please fill in the missing information from the issue template:
https://github.com/netlify/netlify-cms/issues/new?template=bug_report.md
