### ISSUE TITLE
Use pr base branch to configure editorial workflow for different environments (stage/production)

### ISSUE THREAD

**Issue by rewop** [netlify/netlify-cms#412]
I have been looking at how to configure the cms for different environments `develop` -> `stage` -> `production`.

What I would like to achieve is to have a dedicated repository that will contains the contents. This repository will contain long living branches per environment (master/stage/develop).

At build time I will have a script that builds the yaml configuration assigning the right branch per environment. 

However this configuration wouldn't work with editorial workflow.

I noticed that when retrieving unpublished contents to render the editorial workfloe, the api only looks at [the branch names](https://github.com/netlify/netlify-cms/blob/265146e2d13843e9a455f4566c7b19c05a5f047a/src/backends/github/API.js#L203-L203). However when we retrieve the PRs, we could [filter by base](https://developer.github.com/v3/pulls/#list-pull-requests) by using the configuration. This way we can separate editorial workflows per environments.

I may be missing something, but I wonder if this approach would work.

Would this be a right implementation? If so, I will be happy to contribute on it.

**Comment by calavera** [comment]
That's a very interesting idea. If I understand it correctly, you want to show only PRs with a specific base branch in the editorial workflow, is this correct? I think your approach can work if that's the idea. Feel free to open a PR so we can play with the code.

**Comment by rewop** [comment]
@calavera Yes that is what I mean. I see that the branch in the config is not used to filter the PRs for the editorial workflow. I will try to open a PR asap for this one.

**Comment by erquhart** [comment]
Hmm I'd even say this is a bug - we should be checking the base branch for editorial workflow entries.
