### ISSUE TITLE
[gatsby-plugin-netlify-cms] The CMS router and dependencies activate on every gatsby pages

### ISSUE THREAD

**Issue by arnaud** [netlify/netlify-cms#4124]
**Describe the bug**

When using the `gatsby-plugin-netlify-cms` plugin, every single page of a gatsby instance has a systematic and uncontrollable redirection from `path/` to `path/#/`.

**To Reproduce**

1. Go to <https://www.edulide.fr>
2. Wait for it to load
3. See the path redirection with a sharp in the location bar?

**Expected behavior**

Do not alter the URL anywhere else but in the chosen admin path 🤡 

**Applicable Versions:**

- "netlify-cms-app": "^2.12.19",
- "gatsby-plugin-netlify-cms": "^4.3.11",

**CMS configuration**

The CMS configuration is not at cause here.

**Additional context**

`gatsby-config.ts:`

```yaml
  ...
  plugins: [
    ...
    {
      resolve: `gatsby-plugin-netlify-cms`,
      options: {
        manualInit: true,
        modulePath: require.resolve(`../src/cms/register`),
        // stylesPath: require.resolve(`../src/cms/style`)
        enableIdentityWidget: false,
      }
    },
    ...
```

`src/cms/register.tsx:`

```typescript
import { init } from 'netlify-cms-app'

// Restrict Netlify CMS initialization on /admin/
if (window?.location.pathname === `/admin/`) {
  // 👇 the function is actually NOT called on the index page;
  // but referencing the "init" function seems to have some nasty and shadowy routing side effect
  init({ config })
}
```

Any help would be highly appreciated! (づ￣ ³￣)づ

**Comment by arnaud** [comment]
Well, we found the culprit:

`gatsby-browser.ts:`

```typescript
import './src/cms/register'
```

Calling the Netlify CMS entrypoint directly in the `gatsby-browser.ts` boot file was not the best idea 😅.

It had the intended effect of doing its job: requiring the lib on. every. damn. page.

One less bug for this tracker! 🎉

**Comment by erezrokah** [comment]
Thanks for the follow up!
