### ISSUE TITLE
Docs: migrate netlify-cms-widget-starter to the official docs

### ISSUE THREAD

**Issue by erezrokah** [netlify/netlify-cms#4129]
There are two ways to build a custom widget:
1. Using vanilla JS as described in the docs: https://www.netlifycms.org/docs/custom-widgets/#registerwidget
2. Using JSX syntax with a build step which is covered in https://github.com/netlify/netlify-cms-widget-starter

We should migrate the latter option to the docs.

**Comment by KancerEzeroglu** [comment]
Hi @erezrokah ,
I have checked the document that you shared as a first option. I saw someone has already added a link for the second way (you can check the screenshot). I think it is not enough for you, right? Could you explain the issue a little bit?
If it is possible, I can take this issue.
<img width="614" alt="Screen Shot 2020-08-12 at 14 27 50" src="https://user-images.githubusercontent.com/1583507/90015194-8f98e580-dca8-11ea-9339-36e3f41de38c.png">

**Comment by erezrokah** [comment]
Thanks @KancerEzeroglu, sorry for not being clear with the issue.
We should re-write the repo https://github.com/netlify/netlify-cms-widget-starter as a step by step guide and add it to the docs.
The guide will replace the current forking workflow that is required to create the widget.
One example for a step by step guide is https://www.netlifycms.org/docs/gatsby/.

**Comment by KancerEzeroglu** [comment]
Just to confirm, I'll enrich the current document(https://www.netlifycms.org/docs/custom-widgets/#registerwidget), with the steps mentioned in the repo read me (https://github.com/netlify/netlify-cms-widget-starter).
Is that ok?

**Comment by erezrokah** [comment]
Yes, that's great. I recommend opening a PR (could be a draft) as soon as you have something in order to get some feedback.

**Comment by KancerEzeroglu** [comment]
hi @erezrokah ,
I've started to work on it yesterday, fyi

**Comment by KancerEzeroglu** [comment]
Hi @erezrokah , 
I prepared the first iteration as a draft.
You can check it out. After your investigation, I can change the document if it is not perfect :)

**Comment by erezrokah** [comment]
Thanks @KancerEzeroglu, if you open a PR for it Netlify will generate a preview template with your version of the site. That would make it easier to review.

**Comment by erezrokah** [comment]
Fixed via https://github.com/netlify/netlify-cms/pull/4146

**Comment by silverwebb925** [comment]
@erezrokah ,
I just spent over two hours trying to build a custom widget based on the article in the Docs before giving up.

The article is well written and clear... but the code examples appear to be very out of date. It seems like the code might be pulled verbatim from the netlify-cms-widget-starter project which is depreciated and archive.

If you have not already, can you please walk through the tutorial and see if you can produce a working boilerplate widget?

Guessing it should be a 10-15 minute process to get a generic blank widget put together and previewing, but the build as-written fails to compile, throwing two tokens related to babel-loader.
![Screen Shot 2020-09-11 at 3 15 10 PM](https://user-images.githubusercontent.com/8227367/92977432-e0376600-f441-11ea-8d1e-cfda1ac78cc0.png)

**Comment by erezrokah** [comment]
Re-opening the issue, thanks @silverwebb925

**Comment by silverwebb925** [comment]
Of course! I would love to learn how to do this, and if I'd been able to figure it out, I'd have updated the code and done a PR myself.

**Comment by KancerEzeroglu** [comment]
Hey @silverwebb925 ,
I have tried all steps before made changes to the document.
I think you get the errors because of the library versions which in the package.json.
Can you share with me your package.json content?

**Comment by silverwebb925** [comment]
> Can you share with me your package.json content?
Oh good! I'm actually super glad to hear the error is on my end. Unfortunately I deleted my last attempt out of frustration after capturing that screenshot. I won't make that mistake again, and will circle back today or tomorrow to yet again attempt to build a custom widget based on the docs. I'll let you know how it goes either way and will share the `package.json` if it errors out again.
Lastly, @KancerEzeroglu, it occurs to me that I'm using the latest version of NodeJS... would that make a difference?
Thank you for your response!

**Comment by erezrokah** [comment]
@silverwebb925, there is a pending fix to that doc:
https://github.com/netlify/netlify-cms/pull/4328/files#diff-71cf0183902b4785a350655ed78e3fb2R335

**Comment by erezrokah** [comment]
Fixes via https://github.com/netlify/netlify-cms/pull/4328
