### ISSUE TITLE
Update React Router from v2 to v4

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#413]
Our react-router dependency is way outdated, and documentation gaps abound for v2. We should move to v4 soon.

**Comment by KraigWalker** [comment]
v4 is a complete refactor, something that's lagging behind/buggy right now is the react-router-redux package. Perhaps consider replacing react router with [Redux First Router](https://github.com/faceyspacey/redux-first-router)?

**Comment by tech4him1** [comment]
One note here is that `react-router` will *have* to be updated before React v16, as it uses functions depreciated since v15.5.0: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html.

**Comment by tech4him1** [comment]
@erquhart Do you think it is worth just going to v3 for now, since the deps are stable for that, or should we just wait for v4?
