### ISSUE TITLE
update editor component options value after login 

### ISSUE THREAD

**Issue by dev-b01** [netlify/netlify-cms#4140]
Problem:
I need to update and editor component options after calling an api

One of my custom component is a registration form which has a field
```
      {
        label: 'Mailerlite Group',
        name: 'groupId',
        widget: 'select',
        options: mailerliteGroups,
        hint: 'select the mailerlite group the registrant will belong to',
        required: true
      },
```

What I'd like to happen:
- have a clean method of fetching data after login and component registration without having to create work arounds like this
  void (async () => {
    try {
      mailerliteGroups = await getMailerliteGroups()
    } catch (e) {
      console.info('try catch chain failed::')
    }
  })()

I'd like to have ability to update the options after login to secure the serverless function for some functionality. In this case the response not important, so I'm just looking to do a request update the component options when it is added to a page. 

Something like cms.updateEditorComponent() or a function inside the editorComponent that exposes the options seems very useful.

related issue:
https://github.com/gatsbyjs/gatsby/issues/25950

**Describe alternatives you've considered**
I've tried calling a function in toBlock() function to see if I can update the value. Unfortunately it doesn't work like that because the component is already registered with the options that it got during the manual cms init process. 
 
 const overWriteOptions = async () => {
 const key: number = registerFormSectionConfig.fields.findIndex(
   (o: { name: string }) => o.name === 'groupId'
  ) /   // eslint-disable-next-line @typescript-eslint/no-use-before-define
  registerFormSectionConfig.fields[key].options = await getMailerliteGroups()
// }

**Comment by dev-b01** [comment]
Bit ugly, but I found a solution:

Rewrite EditorComponent config as an async function, then before CMS init in cms.ts
```
// eslint-disable-next-line no-void
void (async () => {
  const [regSectionCfg, contactSectionCfg] = await Promise.all([
    registerFormSectionConfig(),
    contactFormSectionConfig()
  ])
  CMS.registerEditorComponent(regSectionCfg)
  CMS.registerEditorComponent(contactSectionCfg)
 
  ...
  CMS.init()
}
```
This is the part that went wrong for me so, perhaps it can be useful for someone else struggling with the same issue. I tried using an immediately executing function to use a top level await, but didn't place the CMS.init() call inside that function. 

The serverless function authentication works perfectly so I'm going to close this

**Comment by erezrokah** [comment]
Thanks for sharing the solution 👍
