### ISSUE TITLE
Chore: get rid of redux-optimist

### ISSUE THREAD

**Issue by erezrokah** [netlify/netlify-cms#4174]
We use `redux-optimist` only for the editorial workflow which is inconsistent with the rest of the codebase, and makes the code more complicated.
Also, that package is no longer maintained.

We should remove it as unless we can think of a major benefit it produces.

**Comment by KancerEzeroglu** [comment]
I am going to work on that. 
- first I need to understand the code base and how reducers work.
- I will try to run the code and debug locally to get more context. Any advice or direction is welcome 😄

**Comment by erezrokah** [comment]
You've been doing great work so far, so not much I can add.

Just the general concept of redux-optimist:
First update the redux state assuming the operation succeeded. If the operation failed, revert the state, otherwise don't do anything.

I think the idea was to make the UI respond fast when doing backend related operations assuming most of them succeed anyway.
