### ISSUE TITLE
Show branch name in Dashboard

### ISSUE THREAD

**Issue by BasJan81** [netlify/netlify-cms#4215]
Just a thought 💡

What if we showed the current branch name at the bottom of collections. Is there a reason why not to do this?

![CleanShot 2020-08-27 at 11 05 03](https://user-images.githubusercontent.com/10583358/91421131-d7e20700-e855-11ea-9b37-87352313e96a.png)

**Comment by BA1RY** [comment]
@erezrokah I would like to work on this feature. How shall I go about implementing this? Also, how can I get the branch name into react component? Thank you

**Comment by erezrokah** [comment]
The CMS has been very much about hiding `git` specifics from the UI (while keeping those in the `config.yml` under `backend`). Some backends are not even git based (test, fs proxy).
Not sure we would like to add this feature with the current CMS approach.

**Comment by BA1RY** [comment]
@erezrokah Understood. Thank you

**Comment by erezrokah** [comment]
Closing this issue. Don't see a good reason to break the current CMS approach of abstracting the backends
