### ISSUE TITLE
Stop the pluralization of collection name

### ISSUE THREAD

**Issue by damienvdw** [netlify/netlify-cms#422]
Currently an helper module (**pluralize**) handle the pluralization of collection names in the CMS.

However for non-english text, the transformation is often incorrect.

An improvement would be to add a `label_plurialized` settings for each collection in `config.yml` and use it in place of pluralize transformations.

This way we have more control, which result in less typos in the UI.

**Comment by erquhart** [comment]
Hey @damienvdw - this makes sense. I think a nice minimal approach would be to simply stop pluralizing entirely for now, which wouldn't take much work. We'd be open to a PR for this.

**Comment by damienvdw** [comment]
Fixed in #503
