### ISSUE TITLE
Login/Auth screen not being translated by Locale

### ISSUE THREAD

**Issue by gabrielalg** [netlify/netlify-cms#4239]
**Describe the bug**
I changed the locale in my config.yml file but the translation didn't reflect in my Auth/Login screen. After logging in, many labels were translated, so, I presumed the configuration didn't work correctly.

**To Reproduce**

1. Configure an index.html file in the /admin directory, following the CMS doc instructions.
2. Change the config.yml file inserting `locale: 'pt'`
3. Access the website/admin domain
4. See that the language has not changed on the login screen:

![image](https://user-images.githubusercontent.com/50120237/91688189-d2c3d700-eb37-11ea-9729-9e0062530282.png)

5. Log in and see that the language has been updated internally, but some labels (like 'Sort by') have not been translated:
 
![image](https://user-images.githubusercontent.com/50120237/91688254-f8e97700-eb37-11ea-8a51-41c62a0a9429.png)

**Additional context**

I noticed the command `NetlifyCms.getLocale('pt')` in the browser console didn't brought the "auth" object that was expected:

![image](https://user-images.githubusercontent.com/50120237/91688531-9349ba80-eb38-11ea-9e7a-d71ae339f26e.png)

**Applicable Versions:**

 - Netlify CMS version: 2.10.55
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version: Firefox Developer 80

**Comment by erezrokah** [comment]
Hi @gabrielalg, those missing translations were added in https://github.com/netlify/netlify-cms/pull/4173 and released in `2.10.56`
https://github.com/netlify/netlify-cms/compare/netlify-cms@2.10.55...netlify-cms@2.10.56

Please try with the latest version. Closing this - please comment if updating to the latest version doesn't solve this

**Comment by gabrielalg** [comment]
Hi @erezrokah ! I'm using the CDN link to access the cms (https://unpkg.com/netlify-cms@2.10.55/dist/netlify-cms.js) but I can't find the 2.10.56 version. I've tried to find it in npmjs but it wasn't there too. Can you help me with the published link for this new version, pls 🙏?

**Comment by erezrokah** [comment]
Oh, looks like there is an issue with that release as it is not on npm:
https://www.npmjs.com/package/netlify-cms

Working on getting a new one released

**Comment by erezrokah** [comment]
Sorry for the late follow up, `2.10.56` should be available now on npm

**Comment by gabrielalg** [comment]
Hi @erezrokah ! It worked! 🎉 Thank you very much!
