### ISSUE TITLE
Allow date/datetime fields to be formatted from config

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#424]
**- Do you want to request a *feature* or report a *bug*?**

feature

**- What is the current behavior?**

Date and Date/time fields cannot be formatted form config.

**- What is the expected behavior?**

Allow formatting from config.

**Comment by erquhart** [comment]
#525 has better info, closing.

**Comment by tech4him1** [comment]
@erquhart I think this should be for #529?
