### ISSUE TITLE
Relation widget not working with valueField: slug

### ISSUE THREAD

**Issue by rumack** [netlify/netlify-cms#4240]
**Describe the bug**

I'm setting up a simple blog with Sapper and Netlify CMS. I have a 'Posts' collection and an 'Authors' collection. Items in the Posts collection have a Relation widget to select a corresponding author with the following config: 
 ```
 valueField: slug, 
 searchFields: ["title"], 
 displayFields: ["title"]

```
Items also have a Relation widget allowing selection of multiple related posts (from the same Posts collection with the following config:
```
multiple: true, 
valueField: slug, 
searchFields: ["title"], 
displayFields: ["title"]
```
The problem is that the CMS UI will not let me select any authors or related posts when I create a new Post.

I think the problem is the valueField but I'm not sure why as it is a unique field and in theory it should work. Any other issues here seem to relate to non-unique valueFields.

**To Reproduce**

Can reproduce with the below config.yml configuration, then attempting to create new blog post and select a corresponding author.

**Expected behavior**
I expect to be able to select my chosen author from the dropdown (names appearing as 'title' field, but the saved value as 'slug', and to select multiple other posts (again displayed as 'title' field but saved as 'slug'. But I can't. The authors don't appear, or if one does, it cannot be selected.

**Applicable Versions:**

 - Netlify CMS version: 2.10.55
 - Git provider: github
 - OS: KDE Neon
 - Browser version : Firefox 80

**CMS configuration**

```
# Authors Collection
  - name: "author"
    label: "Author"
    folder: "static/data/_authors"
    create: true
    slug: "{{slug}}"
    media_folder: "../../assets/author-thumbs"
    public_folder: "{{public_folder}}/author-thumbs"
    fields: 
      - { label: "Name", 
          name: "title", 
          widget: "string", 
          hint: "The name of the author" }
      - { label: "Role", 
          name: "role", 
          widget: "string", 
          hint: "What's the author's role?" }
      - { label: "Twitter Handle", 
          name: "twitter", 
          widget: "string", 
          required: false, 
          hint: "The author's Twitter handle? (optional)" }
      - { label: "Main Image", 
          name: "image", 
          required: false, 
          widget: "image", 
          hint: "A (small) thumbnail photo of the author (optional)" }
      - { label: "Author Bio", 
          name: "body", 
          required: false, 
          widget: "markdown", 
          hint: "A short bio for the author" }
      

  # Blog Collection
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "static/data/_blogPosts" # The path to the folder where our blog posts are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{slug}}"
    media_folder: "../../assets/blog"
    public_folder: "{{public_folder}}/blog"
    fields: # The fields for each document
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Author Name", name: "authorName", widget: "string" }
      - { label: "Author Data", 
          name: "authorData", 
          widget: "relation", 
          collection: "author",
          required: true,
          valueField: slug, 
          searchFields: ["title"], 
          displayFields: ["title"], 
          hint: "Select the author from the list - if you don't find them, go to the author section, add them, then the name should appear as an option" }
      - { label: "Related Posts", 
          name: "relatedPosts", 
          widget: "relation", 
          collection: "blog", 
          required: true,
          multiple: true, 
          valueField: slug, 
          searchFields: ["title"], 
          displayFields: ["title"], 
          hint: "Add related posts: this should be based on content rather than author though there might be some overlap" }
      - { label: "Date Published", name: "datePublished", widget: "date" }
      - { label: "Campaign",
          name: "campaign", 
          widget: "relation",
          collection: "campaign",
          required: true,
          valueField: "title",
          searchFields: ["title"],
          displayFields: ["title"],
          hint: "Select the relevant campaign from the dropdown list" }
      - { label: "Type", 
          name: "type", 
          widget: "select", 
          options: ["News", "Commentary", "Analysis", "Announcement", "Other"] }
      - { label: "Main Image", 
          name: "image", 
          widget: "image" }
      - { label: "Image Caption", 
          name: "caption", 
          widget: "string"}
      - { label: "Thumbnail Image", 
          name: "thumbnail", 
          widget: "image" }
      - { label: "Body", 
          name: "body", 
          widget: "markdown" }
```

**Additional context**
It seems I can make this work by adding a slug field to the author frontmatter, (following instructions [here](https://www.stackbit.com/docs/best-practices/relationships-netlify-cms/): but that introduces other problems and I'd prefer to avoid it. Plus, my config should work, shouldn't it? Or is it true, as the author of that link suggests, that "Netlify CMS does not allow you to select the filename or slug for the valueField - it must be a field defined in the frontmatter"?

**Comment by rumack** [comment]
Sorry, I'm an eejit. Just figured out a mistake in my config. The valueField in both cases should use the template string, {{slug}}. I've changed the config and it's working now. Thanks and sorry for spamming your issues.

**Comment by erezrokah** [comment]
Thanks for following up with the solution @rumack!
