### ISSUE TITLE
can not connect to netlify CMS [Error loading the CMS configuration]

### ISSUE THREAD

**Issue by NeaamHariri** [netlify/netlify-cms#4254]
im receiving this error when i try to go mywebsite/admin page ::

Error loading the CMS configuration
Config Errors:
'collections[1].fields[1].pattern' should NOT have fewer than 2 items
Check your config.yml file.

i made sure that i follow all steps correctly, im using this starter templet 
https://github.com/W3Layouts/gatsby-starter-delog

i also changed repo in config.yml to my repo

**Comment by barthc** [comment]
@NeaamHariri  the offending config line is https://github.com/W3Layouts/gatsby-starter-delog/blob/master/static/admin/config.yml#L59. The `pattern` config is expecting  two array items, the regex and error message https://www.netlifycms.org/docs/widgets/#common-widget-options

The reason why that config may have worked in the past is that the `pattern`  option wasn't validated but now is. Update your config and you should be good.
