### ISSUE TITLE
Cannot inject google fonts into the html of the iframe created with registerPreviewTemplate 

### ISSUE THREAD

**Issue by AJTJ** [netlify/netlify-cms#4257]
**Describe the bug**
I've tried several methods of ensuring that the `iframe` created by `registerPreviewTemplate` loads my google fonts for the component previews.

You will notice in my CMS index.js I've attempted to use something called `WebFontLoader`, and I've tried applying `Global` fonts via `EmoGlobal`, using Emotion (which I use everywhere else in my project).

**To Reproduce**
You can see the whole repo here: https://github.com/Yukon-Literacy-Coalition/ylc_website
and this is my CMS index.js: https://github.com/Yukon-Literacy-Coalition/ylc_website/blob/master/src/CMS/index.js

**Expected behavior**

I'd expect the preview of the components to use the same fonts as the App (Poppins and Noto Sans), but they are falling back to defaults.

**Screenshots**
First screenshot shows the fonts I desire:
![Screen Shot 2020-09-06 at 7 23 50 PM](https://user-images.githubusercontent.com/29932896/92337290-97189800-f076-11ea-9c54-080ec3765625.png)
This second one is how it is looking in the CMS:
![Screen Shot 2020-09-06 at 7 23 27 PM](https://user-images.githubusercontent.com/29932896/92337308-a0a20000-f076-11ea-8a81-88a1281a41b2.png)

**Applicable Versions:**

 - Netlify CMS version: "netlify-cms-app": "^2.12.15",
 - Git provider: Github
 - OS: MacOS Mojave
 - Browser version: new Chrome

 - Node.JS version:
v10.15.1

**CMS configuration**
I'm not using a `config.yml` I'm using a `config.js`
it can be found here: https://github.com/Yukon-Literacy-Coalition/ylc_website/blob/master/src/CMS/config.js

**Comment by erezrokah** [comment]
Hi @AJTJ, browsers don't allow cross frames scripts injections like:
https://github.com/Yukon-Literacy-Coalition/ylc_website/blob/7085928ce68250cdb8a86d293f93202790c8f4db/src/CMS/index.js#L43

We're passing the frame `document` instance as a prop, so you can use `this.props.document`.
See:
https://www.netlifycms.org/docs/customization/#registerpreviewtemplate

Closing, please comment if `this.props.document` doesn't work for you

**Comment by AJTJ** [comment]
Thanks @erezrokah, this is rather new to me so I'm not sure if I'm missing something or if something is missing.

In my CMS file (https://github.com/Yukon-Literacy-Coalition/ylc_website/blob/master/src/CMS/index.js) if I console log the `previewProps` I get this:
```
boundGetAsset: ƒ boundGetAsset(t, n)
collection: Pe {size: 11, _root: Le, __ownerID: undefined, __hash: undefined, __altered: false}
config: Pe {size: 6, _root: je, __ownerID: undefined, __hash: undefined, __altered: false}
entry: Pe {size: 14, _root: Le, __ownerID: undefined, __hash: undefined, __altered: false}
fields: it {size: 9, _origin: 0, _capacity: 9, _level: 5, _root: null, …}
fieldsMetaData: Pe {size: 0, _root: undefined, __ownerID: undefined, __hash: undefined, __altered: false}
getAsset: ƒ (r, i)
isLoadingAsset: false
widgetFor: ƒ (e)
widgetsFor: ƒ (e)
__proto__: Object
```
but I don't see any reference to the `document`. Thus, my question would be, where is the document and once I get it, how do I update it (does it get returned as a component or something?)

My understanding is that I would like to change the `initialContent` option of the `Frame` referenced here: https://github.com/ryanseddon/react-frame-component#initialcontent, but I'm not sure how to access that.

That way I could add these font `link`s to the document:
```
<link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,700;0,800;1,400;1,700&display=swap"
          rel="stylesheet"
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;700&display=swap"
          rel="stylesheet"
        ></link>
```

**Comment by erezrokah** [comment]
Hi @AJTJ, this was released in `netlify-cms-app@2.12.20`, can you make sure you're using the latest version of the CMS:
https://github.com/netlify/netlify-cms/compare/netlify-cms-app@2.12.19...netlify-cms-app@2.12.20

**Comment by AJTJ** [comment]
Thanks @erezrokah I was at `2.12.15` and updating to `...20` exposed the `document` property. That being said, I'm not sure how to add my scripts to it.

**Comment by erezrokah** [comment]
See https://github.com/netlify/netlify-cms/issues/4142#issuecomment-674505811 and:
https://github.com/erezrokah/netlify-cms-reproductions/blob/d9300a4e970aa47dc4ec2054e7f30a0f85ae3796/public/index.html#L13

**Comment by AJTJ** [comment]
Thanks @erezrokah, I think I'm getting closer, but I actually need to add `link`s to the head and the closest I can think of doing what you are suggesting is this:

```
const DataAndStyleInjection = (
  previewProps,
  Component,
  dataName,
  isContained
) => {
  useEffect(() => {
    const { prevDocument = document } = previewProps;
    const link1 = prevDocument.createElement("link");
    link1.href =
      "https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;700&display=swap";
    link1.rel = "stylesheet";
    prevDocument.head.appendChild(link1);
    const link2 = prevDocument.createElement("link");
    link2.href =
      "https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,700;0,800;1,400;1,700&display=swap";
    link2.rel = "stylesheet";
    prevDocument.head.appendChild(link2);
  }, [previewProps]);

  const iframe =
    typeof document !== "undefined"
      ? document.getElementsByTagName("iframe")[0]
      : {};

  const iframeHead = iframe?.contentDocument?.head || "noIframeHead";
  const cache = createCache({ container: iframeHead });
  const { entry } = previewProps;

  const data = { [dataName]: entry.get("data").toJS() };
  const ContainedComponent = ({ data }) => {
    if (isContained) {
      return (
        <MarginedContainer>
          <Component {...data} />
        </MarginedContainer>
      );
    } else {
      return <Component {...data} />;
    }
  };

  return (
    <StyleSheetManager target={iframeHead}>
      <CacheProvider value={cache}>
        <Global />
        <ThemeProvider theme={theme}>
          <ComponentContainer>
            <ContainedComponent data={data} />
          </ComponentContainer>
        </ThemeProvider>
      </CacheProvider>
    </StyleSheetManager>
  );
};

// Here is my function in use
...
CMS.registerPreviewTemplate("events", (previewProps) =>
  DataAndStyleInjection(previewProps, Event, "event")
);
...
```
That being said, this isn't really appending any `link`s to the `document`'s `head`.

**Comment by erezrokah** [comment]
I would first try to use the example I linked as is (without any changes), make sure it works and then add any custom code.

**Comment by AJTJ** [comment]
Thanks for the suggestion. I was able to figure it out! Got my fonts injecting correctly.
