### ISSUE TITLE
Image widget for images hosted in the cloud.

### ISSUE THREAD

**Issue by dindinet** [netlify/netlify-cms#426]
Hi Just had my first play with netlify-cms
We like to host all of our images in the cloud and not in the site repo.

The image widget want s to upload a local file but i want to add a url to my cloud hosted image.

I changed the image field to use a text widget which allowed me to enter the url but the
preview of course does not display an image.

Is there a quick change to the image widget that could make it possible to use a url instead of uploading an image?

**Comment by nikvm** [comment]
Referencing #432.

**Comment by dindinet** [comment]
#432 I vote for that

**Comment by erquhart** [comment]
Closing in favor of #432 (came later, but more descriptive).
