### ISSUE TITLE
Define pages that are not collections

### ISSUE THREAD

**Issue by marcnewport** [netlify/netlify-cms#427]
*feature*

There may already be a way to do this, but I couldn't find anything in the docs...

It'd be great to be able to define pages that aren't collections so they show up in the cms. Eg. you only have one home page and one about page, but they may have different fields.

**Comment by erquhart** [comment]
@marcnewport there is a way to do this, and you're right, the documentation for it isn't great. You would use a "file" collection type as depicted in the repo [example](https://github.com/netlify/netlify-cms/blob/6996045cbf5c34c522d2cb4a629c6c3bbce43797/example/config.yml#L29).
There you'll see the `settings` collection is made up of two files, json and yaml (markdown files w/ frontmatter are also supported).

**Comment by erquhart** [comment]
Going to close this, but if you have issues getting it going, hit us up on our [Gitter channel](https://gitter.im/netlify/NetlifyCMS).
