### ISSUE TITLE
Document "netlify-auth" backend

### ISSUE THREAD

**Issue by mraerino** [netlify/netlify-cms#429]
To use the full potential of NetlifyCMS people need to know how to use the `netlify-auth` backend.

I was able to guess some parts from the source.
- The backend needs a `auth_url` and a `github_proxy_url` configured in `config.yml`
- There is no public service providing functionality for `github_proxy_url`
- If you want to roll your own custom authing, you need to roll a service for `auth_url`

Can you provide more details of how to implement those services?

**Comment by erquhart** [comment]
cc/ @biilmann, we should link to Gotiator docs here once they're published, and we can extend CMS docs to round out this specific use case.

**Comment by mryellow** [comment]
Also need to know how to use `netlify-cms-github-oauth-provider`... To my eyes this should be the primary use-case rather than a specific after-thought. All components with one easy setup rather than being pushed into netlify.com.

**Comment by erquhart** [comment]
@mryellow we provide Netlify's auth service as a convenience - if you're up for contributing toward a more flexible authentication path, it'd be more than welcome :)

**Comment by mryellow** [comment]
Think I found an approach where everything plays nice, something I can just throw on an instance somewhere:

https://github.com/vencax/netlify-cms-github-oauth-provider/pull/3/files

With `base_url` available in config things start making sense.
