### ISSUE TITLE
"summary" for object widget

### ISSUE THREAD

**Issue by acarnwath** [netlify/netlify-cms#4291]
**Is your feature request related to a problem? Please describe.**
Our "object" widgets have a lot of content in them, so authors typically view them in the "collapsed" view but have to open them regularly to remind themselves what is inside.

**Describe the solution you'd like**
If we could provide a summary, similar to how lists have, for a quick overview. This would save authors time, as they could simply scan over all of the collapsed widgets and understand what they have to work with at a high level.

**Describe alternatives you've considered**
Could make a custom widget, but seems like overkill for just one field.

**Comment by KoljaTM** [comment]
How about something like the displayFields property used in the relations widget, that would specify what would be displayed in the collapsed state.
