### ISSUE TITLE
"Publish and create new" does not work

### ISSUE THREAD

**Issue by stefanprobst** [netlify/netlify-cms#4294]
**Describe the bug**

in a folder collection, when editing an entry, clicking "Publish and create new" does not work as expected

**To Reproduce**
1. in a folder collection, add a new entry
2. edit, press "publish and create new" menu button

**Expected behavior**

i had expected the currently edited entry to be saved, a new draft entry created, and the form to be cleared

**Applicable Versions:**
 - Netlify CMS version: 2.10.56

**Comment by erezrokah** [comment]
@stefanprobst, can you please share a `config.yml` and also the current behaviour. I assume this behaves and expected to behave differently if using/not using editorial workflow.

**Comment by stefanprobst** [comment]
i've created a small repro [here](https://github.com/stefanprobst/netlify-cms-issue-4294)

**Comment by jsl15c** [comment]
@stefanprobst I see that `branch` is not specified in `config.yml`.  Netlify CMS still defaults to `master` branch, so you have to specify: 
```
backend:
  name: git-gateway
  branch: main
```

**Comment by stefanprobst** [comment]
@jsl15c i think when running locally with `netlify-cms-proxy-server` the branch name should not matter? i'll check, thanks!
