### ISSUE TITLE
Use drag handles for list control drag/drop

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#431]
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

Each object in a list control can be dragged from any point. When attempting to select text inside of a list control, you'll often drag the entire object of controls instead.

**- If the current behavior is a bug, please provide the steps to reproduce.**

* Open the editor for a CMS entry that utilizes the list widget (list widget must contain a text field
* Hit the "+ new" button in the list widget to create a new list item
* Enter text in a text field for the newly created item
* Attempt to select entered text using a mouse or touchpad

**- What is the expected behavior?**

* Text should be selected without activating drag mode on the list item

**- Requirements**
* Limit drag mode activation to a drag handle area (a handle is already depicted at the top of each list item in the UI, but it's just styling).
* When a list item is collapsed, the entire item should still be treated as a drag handle.

**Comment by andreasvirkus** [comment]
Is this at a `good first contribution` label level? I'd like to take a crack at this to get my foot in the door on contributing to this repo.

**Comment by erquhart** [comment]
Hey @andreasvirkus, that'd be awesome! I don't imagine it'd be too difficult - it _should_ be supported by the drag/drop library we're using, but I haven't looked into it. Definitely take a crack at it, you can post questions in Gitter if you run into issues.

**Comment by andreasvirkus** [comment]
I hit a small road block with the react-sortable lib we use. It's easy to disable dragging for all children of the draggable, fixing the initial bug described. But I've found no way to re-enable it for a specific child element afterwards.

I also asked for help under the lib's [issues](https://github.com/danielstocks/react-sortable/issues/77), but haven't received any feedback yet. I reached out to Daniel (owner) on his e-mail, but if that doesn't amount to anything, would it be ok for me to try out a different lib [react-draggable](https://github.com/mzabriskie/react-draggable)? They've got the drag handles in their example as well so it's definitely a feature they support.

**Comment by erquhart** [comment]
@andreasvirkus I'm not against using a different lib - for our purposes, this one seems the most promising: https://github.com/clauderic/react-sortable-hoc

**Comment by andreasvirkus** [comment]
@erquhart Good find, will dive into it tonight!

**Comment by erquhart** [comment]
@andreasvirkus just a heads up, @Benaiah seems to have included this in some recent work that required this fix: https://github.com/netlify/netlify-cms/pull/468. If you're up for reviewing, it'd be a great help! Or we can point you toward another issue if you don't already have one mind - just reach out on Gitter :)
