### ISSUE TITLE
Repeated edits result in repeated escape characters in markdown

### ISSUE THREAD

**Issue by verythorough** [netlify/netlify-cms#433]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
![screen shot 2017-05-03 at 6 15 16 pm](https://cloud.githubusercontent.com/assets/6111186/25687608/898a28d8-302c-11e7-8974-55a2a5b524d6.png)

^ The screenshot above is taken from a page that has been edited several times using the CMS. Each time, it appears to add a new escape character to the beginning of the code string.

**- If the current behavior is a bug, please provide the steps to reproduce.**
I haven't experimented yet to see which characters trigger this or why. I suspect if you have a code block that starts with `~`, and you edit the file repeatedly using the CMS, it will add a new `\` before it each time.

**- What is the expected behavior?**
Probably shouldn't do this. ;)

**- Please mention your node.js, and operating system version.**
This occurs in the browser, on live sites using the CMS. The problem pictured above was caused by CMS web edits made by several different people, on different machines—likely using Chrome on Mac OS.

**Comment by erquhart** [comment]
This should be resolved under #246, we'll need this tested again once that's closed.

**Comment by erquhart** [comment]
No longer an issue in the updated editor.
