### ISSUE TITLE
location / map widget. Any interest?

### ISSUE THREAD

**Issue by NaNdreas** [netlify/netlify-cms#434]
Hi, first of all thanks for a great CMS, I just started using it as an experiment for a blog, and let someone else do the editing. Looks great so far!

I was wondering if there is any interest in a map / location widget? It would probably be mostly useful for blogs, but maybe also company sites with office / store locations. 

In Contentful CMS they use a google map where you can add a pin. You can also fill in fields manually (either by address or coordinates).  

![map-widget](https://cloud.githubusercontent.com/assets/11990635/26606657/a543fe0a-458a-11e7-83a8-8fce0eaa61e8.jpg)

Just curious if this would ever be implemented (maybe with enough interest?) or if I should look at extending one myself. Thanks

**Comment by calavera** [comment]
That can be a cool widget @NaNdreas. We'll take it if you open a pull request with the implementation 😉

**Comment by NaNdreas** [comment]
Alright sounds good to me, thanks for the reply @calavera  

I will try to get the time to get it working well first, and then I can try to implement it nicely in a PR as well. Will just need to familiarize myself with the code base too.

If anyone else feels like doing this let me know though. And any suggestions on how it should work are most welcome

**Comment by erquhart** [comment]
The Boolean widget was recently added, serves as a good example. It includes a default value, which you'll probably also want to do. Also, there's a React component that you may be able to use: https://github.com/tomchentw/react-google-maps.

**Comment by erquhart** [comment]
@NaNdreas also, if you hit any snags or need assistance, join us on [Gitter](gitter.im/netlify/netlifycms/), happy to help!

**Comment by rriemann** [comment]
I have some coordinates in my yaml-frontmatter:

```yml
geo: 37.1809,-3.6198
```

it would be nice to have such a component to create this. I render in Jekyll markers with these geo positions on a leaflet map.

**Comment by NaNdreas** [comment]
Unfortunately I don't think I will get the time for this, it's already been a few months. Sorry about that, but maybe someone else feel like giving it a shot.

**Comment by erick2014** [comment]
I would like to give it a try, but I still not sure what's this all about? including a map? or something?

**Comment by rriemann** [comment]
The idea is to display a map with a pointer that can be dragged around (or the map is moved under the pointer). Using some configuration options for formatting, the coordonates of the pointer are then turned into a string, e.g. `37.1809,-3.6198`.

possible configuration options:
- separator between both numbers
- long,lat or lat,long

**Comment by erick2014** [comment]
@rriemann I still not sure, about what todo, do you want to add a pointer to the map and move that pointer to other places in the map?
