### ISSUE TITLE
Error loading the CMS configuration

### ISSUE THREAD

**Issue by chefcookng** [netlify/netlify-cms#4351]
I am new to netlify cms but ive compared my code with the code of the guide i followed to creating my blog but can't seem to be able to get past this error.
Would any one mind helping?
Thanks.
![netlify cms error](https://user-images.githubusercontent.com/68485536/93745802-08feee80-fbec-11ea-9312-32fae6fe8da3.png)
Above is a picture of the error im facing.
Thanks

**Comment by erezrokah** [comment]
Hi @chefcookng, the `pattern` configuration takes an array of `[pattern, error-message]`.
See https://www.netlifycms.org/docs/widgets/#common-widget-options
Closing the issue, please comment if configuring an array doesn't work.
