### ISSUE TITLE
netlify-cms-app.js.map file is to large for Cloudflare Workers deployment

### ISSUE THREAD

**Issue by aholtzman** [netlify/netlify-cms#4357]
**Describe the bug**
When trying to publish a deployment to Cloudflare Workers it fails with
 
```Error: File `./public/admin/netlify-cms-app.js.map` of 18766797 bytes exceeds the maximum value size limit of 10485760 bytes```

**Applicable Versions:**

 - Netlify CMS version: 2.12.24
- Gatsby version 2.20.25
 - Git provider: GitHub

**Comment by erezrokah** [comment]
Closing this as a duplicate of https://github.com/netlify/netlify-cms/issues/3946.
Please see and https://github.com/netlify/netlify-cms/issues/3946#issuecomment-648848394 and solution https://github.com/netlify/netlify-cms/issues/3946#issuecomment-648866212
