### ISSUE TITLE
Editor scrolls to the top with every stroke under certain conditions

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#436]
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

When an image in the editor preview pane is taller than the viewport, and there's not much other content, whenever the preview pane rerenders (every input change and field focus change) the remaining content finishes rendering before the image, causing the preview pane to scroll to the top due to lack of content. The control pane then scrolls to stay synced.

**- If the current behavior is a bug, please provide the steps to reproduce.**

In the CMS example project:

* shrink the viewport height to something short, maybe 1000px or so
* upload a large image as the featured image
* try to enter text in the body field

**- What is the expected behavior?**

Not this.

**Comment by erquhart** [comment]
cc/ @jholmes033169

**Comment by Dammmien** [comment]
In the Kitchen Sink entry you can note that the editor is scrolled to the bottom when the page is loaded. If you disable the visual editor component and replace it by the raw editor, the issue disappear. It seems to be linked to a prosemirror [issue](https://discuss.prosemirror.net/t/prosemirror-is-causing-a-scroll-to-the-whole-page) and more generally to the contenteditable behavior ...

Any idea of workaround ?
Maybe set the editor in raw mode by default, but it's not a very user-friendly.

**Comment by Dammmien** [comment]
In the Kitchen Sink entry you can note that the editor is scrolled to the bottom when the page is loaded. If you disable the visual editor component and replace it by the raw editor, the issue disappear. It seems to be linked to a prosemirror [issue](https://discuss.prosemirror.net/t/prosemirror-is-causing-a-scroll-to-the-whole-page) and more generally to the contenteditable behavior ...

Any idea of workaround ?
Maybe set the editor in raw mode by default, but it's not a very user-friendly.

**Comment by tortilaman** [comment]
I ran into this bug this morning when I was a text widget within a list widget. If I was editing any of the widgets that ended up down the page, it would scroll to top for every letter I typed in the text widget. I'll do some more thorough testing on the page later I think.

**Comment by Dammmien** [comment]
In fact this is 2 differents issues :
- The editor is scrolled to the bottom when the page is loaded due to prosemirror.
- When you have a large image the rendering of the preview trigger a scroll event. It makes the editor scrolls to the top due to syncing.

**Comment by verythorough** [comment]
Added #532 as a possibly lower-hanging stopgap for this issue.

**Comment by erquhart** [comment]
I believe this may be addressed under #254:

- Using Slate instead of Prosemirror, so no more jumping to bottom on load
- Widgets in the preview pane are now only updating when their value has changed

**Comment by erquhart** [comment]
Closed in #254.
