### ISSUE TITLE
Cannot get the Netlify CMS to work from Github

### ISSUE THREAD

**Issue by lsolesen** [netlify/netlify-cms#4361]
**Describe the bug**

I cannot get the Netlify CMS to work when serving the site from Github itself.

The exact same code works when I go to the Netlify hosted development site, which I have on https://mysite.netlify.app/

**To Reproduce**

1. I have added information to the config.yml be able to access /admin from my Github-hosted site. 
2. When clicking on the button, I get the error shown in the screenshot below.

**Expected behavior**

I was hoping to be able to access the CMS directly from the Github hosted site going to domain.dk/admin/

**Screenshots**

![Screenshot (7)](https://user-images.githubusercontent.com/148026/94476975-840a6b00-01d1-11eb-92da-97674333dc43.png)

![Screenshot (6)](https://user-images.githubusercontent.com/148026/94476737-28d87880-01d1-11eb-9616-eab77b8afc97.png)

**Applicable Versions:**

 - Netlify CMS version: [2.10.16]
 - Git provider: [GitHub]
 - OS: [e.g. Windows 10]
 - Browser version [e.g. chrome 85.0.4183.102]

 - Node.JS version:

**CMS configuration**

https://github.com/motionsplan/motionsplan-dk-jekyll/blob/master/admin/config.yml

**Additional context**

**Comment by erezrokah** [comment]
Hi @lsolesen, do you mind adding the missing parts from the issue template?

**Comment by lsolesen** [comment]
@erezrokah Is it sufficient?

**Comment by erezrokah** [comment]
Thanks @lsolesen, I think it just might be sufficient.
Can you verify you've done the first step about setting up an authentication provider here:
https://www.netlifycms.org/docs/github-backend/

**Comment by lsolesen** [comment]
I have done that step?

**Comment by lsolesen** [comment]
Were you able to debug why it is not possible to add the /admin to a Github-hosted site?

**Comment by lsolesen** [comment]
I figures this one out. Even though I am not using the the site from Netlify, I still have to setup the domain-name on Netlify to get the editor to work.
