### ISSUE TITLE
Allow creating relation content "on the fly"

### ISSUE THREAD

**Issue by andre-brdoch** [netlify/netlify-cms#4369]
**Is your feature request related to a problem? Please describe.**
Let's say the blog collection has a **required relation** to the author collection, and there are no authors created yet. If an editor wants to create a blog article, he might fill out the hole thing, just to find that he also must set an author. But he can not select any, since none was created yet. Since the author field is required, he can not save, and has to rewrite the whole article.

Another scenario is, that there are already authors created, but not the one needed for the new article. The editor just picks another one to be able to save, and then forgets to update it to the correct one.

**Describe the solution you'd like**
Creating the author from within the article.

**Describe alternatives you've considered**
Or, alternatively, allow to refresh the presented selection of authors in the current article. That way the author can still be created in a new tab, and in the article tab the new author can be set after refreshing.

**Additional context**
Our editors usually fill in a lot of content. Losing a full article just because of a missing required relation would be very painful.

I am not sure if either suggested solution would be easily achievable with git. However, at least for us our editors would probably consider this a dealbreaker (we are currently evaluating if we want to migrate to netlify-cms)

**Comment by erezrokah** [comment]
Thanks @andre-brdoch, I think this relates to https://github.com/netlify/netlify-cms/issues/192.
Should we close this issue in favour of that one?

**Comment by erezrokah** [comment]
Closing in favor of https://github.com/netlify/netlify-cms/issues/192
