### ISSUE TITLE
Failed to persist entry: API_ERROR: "params.entry" is required

### ISSUE THREAD

**Issue by codeitlikemiley** [netlify/netlify-cms#4390]
Hi Im Using Netlify CMS local Proxy Server on my project....

Ive wanna update and add features to it , but 

i keep getting error 

Failed to persist entry: API_ERROR: "params.entry" is required

Prior months i dont have issue on this....

I dont know if there is a breaking changes that is not mentioned on the documentation....

or its me thats do something wrong...

so,  i keep rolling back to older commits and 

reinstall node_modules 

and re run server and the netlify cms proxy server

All instances of my rollback produces the same error...

I dont have any solution until now....

But my Production is Working Normal...

I think this is a bug on either the netify cms proxy server or the with the cdn 

https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js

Someone please fix this messed

**Comment by barthc** [comment]
@codeitlikemiley this error shouldn't surface unless you are not using the latest version of the `netlify-cms-proxy-server` package. Not sure how you are setting up the proxy server,  according to [docs](https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository)  re-run `npx  netlify-cms-proxy-server` should setup the latest version of the proxy server package.

If a re-run of the `netlify-cms-proxy-server` package doesn't work, you would need to double-check whether a specific version of the server package is installed locally.

**Comment by codeitlikemiley** [comment]
I vendor lock my netlify-cms-proxy-server in my package.json file....
totally make sense now what this is happening...
I know the only problem here is the proxy server since the production site is working smooth....

Its very important to version lock both proxy and the netlify-cms cdn both having same version...
i know the proxy server is on beta but it worth to note this topic since i think majority of proxy server user will face this issue

Problem is solved when i npm install again , i think the global proxy server is being over written by my per project installation of the proxy server...

@barthc is there a way i can use a local netify cms compiled version instead of using 
https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js

i really need to make netlify cms work even with no internet connection...
and referencing this cdn link must be replace , can you sugguest a way how get the same compiled js
and if there is a big difference on using cdn and a compiled one thanks

**Comment by barthc** [comment]
> Problem is solved when i npm install again , i think the global proxy server is being over written by my per project installation of the proxy server...

Upgrading the `netlify-cms-proxy-server` package to the latest version(1.3.6) in your package.json should be enough.

> @barthc is there a way i can use a local netify cms compiled version instead of using
https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js

You would have to compile it yourself, take a look at the manual initialization sample here https://www.netlifycms.org/docs/beta-features/#manual-initialization

**Comment by codeitlikemiley** [comment]
I think using the compiled version litterally has some benefits in performance since you wont be reading any yml file?
Hope i can migrate 3k lines of code from my config.yml 

can you suggest a service that can easily trans-pile yaml to json?
that would be a time saver...

thanks for help

**Comment by erezrokah** [comment]
Hi @codeitlikemiley, and thanks for responding @barthc.

> Its very important to version lock both proxy and the netlify-cms cdn both having same version...
> i know the proxy server is on beta but it worth to note this topic since i think majority of proxy server user will face this issue

The guarantee for `netlify-cms-proxy-server` is for it to be backwards compatible with older CMS versions, not forward compatible.
You can pin the CMS version by using `https://unpkg.com/netlify-cms@2.10.61/dist/netlify-cms.js` for example or by installing from npm:
https://www.netlifycms.org/docs/add-to-your-site/#installing-with-npm

In both approaches the CMS will read you config `yml`, unless you switch to https://www.netlifycms.org/docs/beta-features/#manual-initialization

As for migrating your config - I would open a new issue for that since it is off topic for this one, or ask in our Slack https://www.netlifycms.org/chat

Closing this as resolved.
