### ISSUE TITLE
Boolean widget not working properly when set to true

### ISSUE THREAD

**Issue by felixdb** [netlify/netlify-cms#440]
**- Do you want to request a *feature* or report a *bug*?**
bug
**- What is the current behavior?**
When a boolean widget is used in a collection, the items with the boolean value set to true won't fully load in the CMS (loading just hangs forever). Also, when trying to set the field value to true in an item which as this field set to false, the item won't save (the save action just hangs forever). Tested to make sure and if the boolean stays false, saving and loading works flawlessly
**- If the current behavior is a bug, please provide the steps to reproduce.**
Use a boolean field and set it to true in frontmatter. Also, try setting it to true in CMS.
**- What is the expected behavior?**
Being able to set to true and save properly :)
**- Please mention your node.js, and operating system version.**
Using node v6.10.3 and using netlify cms v0.4.2

**Comment by erquhart** [comment]
@felixdb this should be fixed in 0.4.3, please re-open if not.
