### ISSUE TITLE
Error 401 Unauthorized when accessing backend over https

### ISSUE THREAD

**Issue by TomDeS** [netlify/netlify-cms#443]
I'm getting an error 401 unauthorized when accessing the backend over https, however it loads fine over http.

![error 401](https://cloud.githubusercontent.com/assets/1459091/26764954/d20d9c12-4971-11e7-80af-6cf5479b2a42.PNG)

I noticed this behaviour only for sites on my organization account. It works fine for sites on my personal account. I was able to reproduce this error multiple times on my organization account.

Update: this appear to only be a problem in Chrome, it works fine in Firefox. Please let met know if I you require additional information.

**Comment by erquhart** [comment]
Try this:

1. Log out (dropdown in the top right)
2. Close the tab
3. Open new tab and load the CMS

**Comment by TomDeS** [comment]
Thank you @erquhart your solution works fine!
