### ISSUE TITLE
Load other collection in registerPreviewTemplate

### ISSUE THREAD

**Issue by PetroPavlenko** [netlify/netlify-cms#4431]
Hi all,
Is it possible to load other collocation (like header configuration) inside registerPreviewTemplate
?

**Comment by erezrokah** [comment]
Hi @PetroPavlenko, can you please follow the issue template? It is hard for me to understand what is your use case.

**Comment by PetroPavlenko** [comment]
Sure. Sorry it's more like feature than issue, I'll fill issue template.

**Comment by PetroPavlenko** [comment]
@erezrokah here it is
**Describe the problem**
Access different collection inside `CMS.registerPreviewTemplate`. I would expect it to be like this:
So if we have blog collection and header collection, it would be nice to have something like this
```
export const BlogPagePreview: ComponentType> = ({ entry, loadOtherEntry }) => (
  <BlogPageTemplate
    header={loadOtherEntry("header")}
    body={entry.getIn(["data", "body"])}
    title={entry.getIn(["data", "title"])}
  />
);

CMS.registerPreviewTemplate("blog", BlogPagePreview);
```

**Comment by erezrokah** [comment]
If you link those via a `relation` widget you can use:
https://www.netlifycms.org/docs/customization/#accessing-metadata

**Comment by PetroPavlenko** [comment]
Thanks, I'll try that
