### ISSUE TITLE
Cloudinary is not working properlly with blogs feature image

### ISSUE THREAD

**Issue by TasTing** [netlify/netlify-cms#4435]
**Describe the bug**
Image from cloudinary not showing in feature image section,
it works properlly in blog's content section

**To Reproduce**
1. create new blog.
2. insert image from cloudinary for both feature and content.
3. return to blog list page.

**Expected behavior**
an article with feature image should have a thumbnail 
```
<article>
   <header>
        <thumbnail>
        <title>
```

**Screenshots**
![capture](https://user-images.githubusercontent.com/25785579/95645048-06b2f480-0b07-11eb-8caa-3f08bb5b3e54.PNG)
![blog](https://user-images.githubusercontent.com/25785579/95645242-f6037e00-0b08-11eb-95be-8404606fedb7.PNG)
![html](https://user-images.githubusercontent.com/25785579/95645245-f865d800-0b08-11eb-8ce0-2616519f0e34.PNG)

**Applicable Versions:**
 - Netlify CMS version: netlify-cms-core 2.30.3
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version chrome

**CMS configuration**

```
config: {
        media_library: {
            name: 'cloudinary',
            config: {
                cloud_name: 'xxxxxxx',
                api_key: 'xxxxxxxxxxxxxxx',
            },
        },
        media_folder: '/static/uploads',
        public_folder: '/uploads',
        collections: [

        ]
    },
```

**Comment by TasTing** [comment]
Well, I've found a way to fix this..
because default blogs were using image as image type. I had to remove all default use of images 
then modify graphql query to remove all subfield of image. because after we use cloudinary, the image becomes a string link to cloudinary. 

build locally with ```netlify build``` to check before deploy will save a lot of time.

**Comment by erezrokah** [comment]
Closing this as resolved. Please comment if still needed
