### ISSUE TITLE
Adding Authors as a collection  

### ISSUE THREAD

**Issue by cassandraoid** [netlify/netlify-cms#444]
**- Do you want to request a *feature* or report a *bug*?**
feature
**- What is the current behavior?**
Right now you have to to into GitHub to add a new author
**- If the current behavior is a bug, please provide the steps to reproduce.**
N/A
**- What is the expected behavior?**
Would be nice to add authors directly into the CMS rather than having to go to GitHub

**Comment by oncletom** [comment]
Agreed. 

I don't know if it exists but it looks like a `<select>` widget which values are populated from the content of another collection.

**Comment by erquhart** [comment]
The CMS already supports this through the relation widget, we're just not using it in the netlify.com CMS instance.

@cassandraoid closing this, but do comment if I'm missing your intent.
