### ISSUE TITLE
Markdown widgets in lists are duplicated when content changed after prior item is removed

### ISSUE THREAD

**Issue by toxsick** [netlify/netlify-cms#4460]
**Describe the bug**

When adding multiple markdown widgets to a list and removing an item at the beginning afterwards, a change on a remaining item triggers the recreation of that list item on it's original index (an duplicating the content). This is a pretty nasty bug because uses can unintentionally change entire parts of the page without even noticing.

A simple string list behaves as expected.

**To Reproduce**

![screencast 2020-10-14 19-55-29 2020-10-14 20_04_25](https://user-images.githubusercontent.com/951466/96028113-2de82980-0e59-11eb-8ef8-0df2852a3678.gif)

I have created a codesandbox, it uses the latest version of netlify cms to date (2.12.27):

https://codesandbox.io/s/netlify-cms-app-example-forked-9xn5s?file=/src/NetlifyCMS/config.json (PLEASE TRY IN CHROME)

I have tracked down the issue to this release:

https://github.com/netlify/netlify-cms/commit/b151bdfd7311472eaa1861e9fc17546a3658a083

specificly to `netlify-cms-widget-list@2.4.4` and I think the bug was likely introduced in #3611, but I don't know where to start debugging this. When I change the dependency `netlify-cms-app` in my codesandbox to `2.12.9` which uses `netlify-cms-widget-list@2.4.3` the problem is gone. I double checled this by installing `netlify-cms-widget-list@2.4.3` in a local project with the latest netlify cms version and using it for lists instead and the problem disappeared also.

So I am pretty sure `netlify-cms-widget-list@2.4.4` broke somthing here, but I am not sure why only in combination with the markdown widget.

**Expected behavior**
Should not duplicate list items after remove on change.

**Applicable Versions:**
 - Netlify CMS version: latest (2.12.27)
 - Git provider: all
 - OS: MacOS
 - Browser version: chrome 85
 - Node.JS version: 12lts

**CMS configuration**
see codesandbox

Thanks a lot guys!

**Comment by toxsick** [comment]
perhaps @barthc some more insights in this?

**Comment by toxsick** [comment]
Hey guys,

any update on this? Even a guess where the problem is caused would help. This is a pretty bad one, because it can unintentionally mess up a lot of content.

regards and thanks!

**Comment by barthc** [comment]
@toxsick  PR  #4492 would fix this issue.

**Comment by toxsick** [comment]
hey @barthc, very cool that you have looked into this so fast. I will test this later and write back here.

regards and have a good week!

**Comment by toxsick** [comment]
Ok looks good to me, i can not reproduce the issue anymore with #4492.

Thank you very much @barthc, hope it get's merged quickly

**Comment by AaratiAkkapeddi** [comment]
I'm experiencing this exact issue again
