### ISSUE TITLE
Image file name validation to prevent overwrites

### ISSUE THREAD

**Issue by bdot** [netlify/netlify-cms#453]
**- Do you want to request a *feature* or report a *bug*?**

Feature

**- What is the current behavior?**

If we create an article with an image "test.jpg" it gets uploaded to public_folder configured in collection settings. It's great.
But if another user creates a different article with same image name "test.jpg" it overwrites an already existing image. 

**- What is the expected behavior?**

@erquhart says
There are a few potential approaches but they all require a PR. Optimally, we should check for the image when validating the entry and provide an error message.

**Comment by erquhart** [comment]
@bdot I just noticed we already have an issue open for this, #247.

This is most likely to be addressed under #350.
