### ISSUE TITLE
Dependencies with Vulnerabilities

### ISSUE THREAD

**Issue by Robotsalesmen** [netlify/netlify-cms#4532]
I'd like to forward a list of out of date, linked dependencies that contain vulnerabilities.  The list includes the "fixed version" of the dependent code.  Can I email this list to the repository maintainers?

**Comment by dustincrogers** [comment]
hi @Robotsalesmen: 
Netlify actively updates dependencies in all our "actively maintained" code bases, and we prioritize those upgrades using internal processes. If you have a particular vulnerability patch (or multiple patches) you would like expedited, we would be happy to consider it if you open a specific issue with some reasoning/justification.
Thank you!
We will most likely close this issue, and we look forward to vulnerability-specific issues you might open.

**Comment by Robotsalesmen** [comment]
I understand.  The process you described is more than adequate.

Please close this issue.
