### ISSUE TITLE
Remove code optimizations from webpack base and dev configs

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#454]
The webpack base config contains the ExtractText plugin, which is generally a production optimization, and increases build time. This and any other production optimizations should only be applied to the production config.

**Comment by Benaiah** [comment]
It looks like `ExtractTextPlugin` also disables HMR for the CSS it affects: see https://www.npmjs.com/package/extract-text-webpack-plugin for more details.

**Comment by erquhart** [comment]
Makes sense.

**Comment by Benaiah** [comment]
Looked into it more, and as far as I can tell we're already disabling this in dev. See https://github.com/netlify/netlify-cms/blob/upgrade-to-webpack-2/webpack.dev.js#L53.

**Comment by Benaiah** [comment]
Looks like this issue was already taken care of - closing.
