### ISSUE TITLE
Bullet list is broken after first enter. Requires 2 enters to create 2nd bullet.

### ISSUE THREAD

**Issue by stevemarksd** [netlify/netlify-cms#4540]
**Describe the bug**

Bullet list is broken after first enter. Requires 2 enters to create 2nd bullet.

**To Reproduce**

![image](https://user-images.githubusercontent.com/58653359/98457912-4af8e980-21c6-11eb-898f-3ad1d11907e8.png)

I press enter
![image](https://user-images.githubusercontent.com/58653359/98457916-53512480-21c6-11eb-9cc1-82992b9baf79.png)

I press enter again

![image](https://user-images.githubusercontent.com/58653359/98457919-6237d700-21c6-11eb-979c-052e827f54e9.png)

**Expected behavior**

I should press enter once for next bullet. Twice to go back to paragraph mode.

**Applicable Versions:**

 - Netlify CMS version: `"netlify-cms-app": "2.13.1",`
 - Git provider: gitlab (AWS lightsail bitnami)

**CMS configuration**

    # https://www.netlifycms.org/docs/gitlab-backend/
    backend:
      name: gitlab
      repo: root/site.com
      branch: master
      api_root: https://mygitlab.com/api/v4
      base_url: https://mygitlab.com/
      auth_type: implicit
      app_id: 222
      auth_endpoint: oauth/authorize
    # Where to save image
    media_folder: src/content/images/cms
    # Prefix image url (gatsby-remark-relative-images staticFolderName + media_folder = image)
    public_folder: /images/cms
    publish_mode: editorial_workflow
    collections:
      - name: default
        label: Default
        folder: src/content/pages
        create: true
        media_folder: ''
        public_folder: ''
        path: '{{path}}/{{path}}'
        preview_path: '{{path}}'
        fields:
          - { name: path, label: Path, widget: 'string' }
          - { name: createdAt, label: Created Date, widget: 'datetime' }
          - { name: updatedAt, label: Last Updated Date, widget: 'datetime' }
          - { name: title, label: Title, widget: 'string' }
          - { name: description, label: Description, widget: 'string' }
          - { name: keywords, label: Keywords, widget: 'string' }
          - { name: tags, label: Tags, widget: 'list' }
          - { name: featuredImage, label: Featured Image, widget: 'image' }
          - { name: content, label: Show on home page, widget: 'boolean', default: true }
          - { name: body, label: Body, widget: 'markdown' }

Note the `path: '{{path}}/{{path}}'`. This will create pr with the name `/slug1/slug1/`, maybe having that slash breaks? but sometimes works... so should be something else.

**Additional context**

**Comment by erezrokah** [comment]
Hi @stevemarksd, this is a duplicate. See https://github.com/netlify/netlify-cms/issues/3474#issuecomment-607549091
