### ISSUE TITLE
When I click on an article from workflow page and then I press back button goes to home page instead of workflow page

### ISSUE THREAD

**Issue by stevemarksd** [netlify/netlify-cms#4541]
**Describe the bug**

When I click on an article from workflow page and then I press back button goes to home page instead of workflow page

**To Reproduce**

When I click on 

![image](https://user-images.githubusercontent.com/58653359/98457977-f0ac5880-21c6-11eb-8dbf-3d174178eabd.png)

And I came from workflow, the back brings me back to home page instead of workflow page.

**Expected behavior**

Go to workflow page where I came from.

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: `"netlify-cms-app": "2.13.1",`
 - Git provider: gitlab (AWS lightsail bitnami)

**CMS configuration**

    # https://www.netlifycms.org/docs/gitlab-backend/
    backend:
      name: gitlab
      repo: root/site.com
      branch: master
      api_root: https://mygitlab.com/api/v4
      base_url: https://mygitlab.com/
      auth_type: implicit
      app_id: 222
      auth_endpoint: oauth/authorize
    # Where to save image
    media_folder: src/content/images/cms
    # Prefix image url (gatsby-remark-relative-images staticFolderName + media_folder = image)
    public_folder: /images/cms
    publish_mode: editorial_workflow
    collections:
      - name: default
        label: Default
        folder: src/content/pages
        create: true
        media_folder: ''
        public_folder: ''
        path: '{{path}}/{{path}}'
        preview_path: '{{path}}'
        fields:
          - { name: path, label: Path, widget: 'string' }
          - { name: createdAt, label: Created Date, widget: 'datetime' }
          - { name: updatedAt, label: Last Updated Date, widget: 'datetime' }
          - { name: title, label: Title, widget: 'string' }
          - { name: description, label: Description, widget: 'string' }
          - { name: keywords, label: Keywords, widget: 'string' }
          - { name: tags, label: Tags, widget: 'list' }
          - { name: featuredImage, label: Featured Image, widget: 'image' }
          - { name: content, label: Show on home page, widget: 'boolean', default: true }
          - { name: body, label: Body, widget: 'markdown' }

Note the `path: '{{path}}/{{path}}'`. This will create pr with the name `/slug1/slug1/`, maybe having that slash breaks? but sometimes works... so should be something else.

**Additional context**

**Comment by iansinnott** [comment]
Can confirm this is also the case when using Github.

**Comment by KancerEzeroglu** [comment]
I want to work on that 😄
