### ISSUE TITLE
Yarn installs 122 thousand dependencies

### ISSUE THREAD

**Issue by jhabdas** [netlify/netlify-cms#456]
Am I reading this right? Does this CMS really have 122,000 dependencies? I thought React Native with Webpack was naughty at ~800. Is this for real? How do you expect to maintain this?

<img width="641" alt="screen shot 2017-06-16 at 1 30 56 pm" src="https://user-images.githubusercontent.com/440298/27213285-733b8296-5298-11e7-9b51-3199ff17182e.png">

`yarn instal && (cd node_modules && tree -h)` reports.

**13461 directories, 120765 files**

**Comment by erquhart** [comment]
Yep, it's a big project. I'm sure not every dependency is necessary, but staying on top of that will be a community effort for sure.

**Comment by jhabdas** [comment]
No doubt about it. If it hasn't been brought up yet, my suggestion for an ambitious project of this size and number of dependencies would be to add https://snyk.io/. Beyond that Yarn caching and SHA-sums should handle the rest I suppose. Cheers.

**Comment by Benaiah** [comment]
We have 114 direct dependencies in `package.json`, including optional and dev dependencies. A count of all our dependencies, direct and indirect, retrieved with `yarn && cd node_modules && ls | wc -l`, returns 1201 for me. The 122k number you're seeing is _all the files in the node_modules directory_, which is totally different than the dependency count.

**Comment by jhabdas** [comment]
I'd only really be concerned about the directs in production from a security perspective. I know dev pipelines have gotten pretty gnarly these days. Thanks for checking. Updated title.

**Comment by tech4him1** [comment]
I would vote for Snyk as well, it really helps stay on top of any security problems and updates in dependencies.

**Comment by erquhart** [comment]
@tech4him1 agreed, this is worth it's own issue.
