### ISSUE TITLE
Drag and Drop File Uploads?

### ISSUE THREAD

**Issue by iansinnott** [netlify/netlify-cms#4563]
Does Netlify CMS support drag and drop file uploads? 

Perhaps I'm missing an obvious feature, but this doesn't seem to work based on my local usage and on the demo site. I see "drag-and-drop media uploads" listed as a feature on the homepage, but have not seen how to use this functionality.

**Comment by erezrokah** [comment]
Hi @iansinnott drag and drop is not supported.
See https://github.com/netlify/netlify-cms/issues/2243 for more information.

The information on the homepage is wrong (I'll submit a PR to fix it)

**Comment by iansinnott** [comment]
Thanks for the heads up @erezrokah. 

Looking at associated issues it seems it was pretty close to completion at one point: https://github.com/netlify/netlify-cms/issues/1032#issuecomment-460069329

I'm curious what happened, since it seems like things were moving towards completion but then suddenly stopped. 

Anyway, I'll close this out as it's not relevant. Thanks for the answer.

**Comment by erezrokah** [comment]
Small correction, drag and drop is available if you're using an external media library:
https://www.netlifycms.org/docs/cloudinary/

**Comment by iansinnott** [comment]
> drag and drop is available if you're using an external media library

Oh interesting. Is there an underlying limitation of the Github API that makes upload-to-repo difficult or impractical?

**Comment by erezrokah** [comment]
This is not an API limitation, but work needed to be done on the frontend size to add this functionality to our core media library.
