### ISSUE TITLE
Allow for control over outputted text for boolean values in 'summary' string template transformations

### ISSUE THREAD

**Issue by pmpinto** [netlify/netlify-cms#4566]
**Is your feature request related to a problem? Please describe.**
I have a `boolean` field that I want to be able to glance at on a `list`. So I do:
```yml
summary: '{{title}} {{is_featured}}'
```

And I get a list like this:
```
Item 1 true
Item 2 true
Item 3
Item 4 true
Item 5
```

**Describe the solution you'd like**
I would like to be able to control the text that gets outputted when the value of a `boolean` is `true`. For instance:
```yml
summary: '{{title}} {{is_featured | true: "🌟"}}'
```

**Describe alternatives you've considered**
The usual ternary operator would be fine too:
```yml
summary: '{{title}} {{is_featured ? "🌟" : ""}}'
```

So the list would end up like:
```
Item 1 🌟
Item 2 🌟
Item 3
Item 4 🌟
Item 5
```

**Comment by erezrokah** [comment]
Hi @pmpinto, I think this can be done as a part of https://github.com/netlify/netlify-cms/issues/3677.
Can you move your comment to that issue?
I'm closing this one
