### ISSUE TITLE
doco uses version 3.X ( instead of 4.X? )

### ISSUE THREAD

**Issue by client9** [netlify/netlify-cms#457]
hi

Working my way through an installation and found this:

In the intro doc such as https://www.netlifycms.org/docs/quick-start/ we see a sample `index.html` file.

It uses `netlify-cms@^0.3` which is "use last version of the 0.3.X series".

Not sure if you want that to be `@^0.4` or just get rid of it all together?

thanks team

n

```
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Content Manager</title>
  
  <link rel="stylesheet" href="https://unpkg.com/netlify-cms@^0.3/dist/cms.css" />
  
</head>
<body>
  <script src="https://unpkg.com/netlify-cms@^0.3/dist/cms.js"></script>
</body>
</html>
```

**Comment by verythorough** [comment]
Hi, this is addressed by PR #455.

For your own installation, you can either pin to 4 or remove, though if you remove, there's always the chance that a breaking change will come along in a major version that breaks your setup.

**Comment by client9** [comment]
thanks @verythorough   yeah not a blocker for me, just though it was odd pointing to an old version.

other ideas:
*  "get the latest version by curl -L -o admin/index.html SOME-URL-HERE" instead of cut-n-paste from editor.
* also display the version in the UI ideally with a call to action to update.  Hate to have people stuck on 0.3 or whatever the last cutnpaste they did.

thanks all... still working my way through all this...

n

**Comment by verythorough** [comment]
Yeah, we're working on our routines for making docs updates an integral part of code changes.

I like the idea for an update call to action in the UI!
