### ISSUE TITLE
Order of cards for collection pages 

### ISSUE THREAD

**Issue by client9** [netlify/netlify-cms#459]
see also #258 and #345 

**- Do you want to request a *feature* or report a *bug*?**

Unclear.  To me it's a bug, but perhaps it's user error or documentation bug or just a feature request.

**- What is the current behavior?**

collection card page appears random.  It's definitely not:

* Alphabetical -- because I can see the titles
* Front-Matter `date` -- I have Apr, May, Apr as the first three
* Last added -- I added a file (from the CMS) and it appears in the middle of the cards
* Last updated -- I updated a file, it's not at the top.

but perhaps I'm missing something or need to add something in front matter?

My backend is Hugo on Github.

I do see in #345  a `reverse()` being done, but assumes the provider is returning a sorted collection in the first place?  It seems like a sort needs to be done as well to be robust?  That's my guess after scanning the code base.

I see this for your search:

```
 const sortedResults = localResults.entries.sort((a, b) => {
            if (a.score > b.score) return -1;
            if (a.score < b.score) return 1;
            return 0;
          })
```

but I don't see the equiv for the card collections page.  It's probably hiding from me.

**- If the current behavior is a bug, please provide the steps to reproduce.**

View any collection card page. No errors in console.

**- What is the expected behavior?**

Some type of ordering of cards.

**- Please mention your node.js, and operating system version.**

Running on mac os x.  same behavior in latest chrome and safari.  Both produce same output.

**Comment by erquhart** [comment]
I believe GitHub is sending files ordered alphabetically by filename (may be different from title). Using your site as an example, you should be getting back posts in reverse of [this order](https://github.com/client9/client9-website-2017/tree/master/content/post).
