### ISSUE TITLE
Hitting rate limits with multiple users

### ISSUE THREAD

**Issue by lukeocodes** [netlify/netlify-cms#4603]
**Describe the bug**

Working in the CMS as a team, we appear to get some odd errors every now and then, errors unhandled and not really clear. 

![image](https://user-images.githubusercontent.com/956290/99387081-4bcb0300-28cb-11eb-928f-7bfc57be785e.png)

When checking the console, we see we're being rate limited by GitHub.

Is there any way to avoid this? 

Using the PR workflow and GitHub for OAuth, would uses use their own tokens rather than the Git Gateway app token which has its own rate limit?

**Comment by erezrokah** [comment]
Hi @lukeocodes, can you please fill in the missing information from the issue template (e.g. CMS configuration)?
See https://github.com/netlify/netlify-cms/issues/4097 for more information

**Comment by erezrokah** [comment]
Closing per missing information
