### ISSUE TITLE
netlify cms scripts are included on home page of the website (non admin pages)

### ISSUE THREAD

**Issue by stevemarksd** [netlify/netlify-cms#4605]
**Describe the bug**

netlify  script included on non admin pages

**To Reproduce**

Follow these steps: https://www.netlifycms.org/docs/gatsby/

**Expected behavior**

Dont include script on all pages.

**Screenshots**

![image](https://user-images.githubusercontent.com/58653359/99477632-e2f88f00-298d-11eb-8b8d-1555815ca973.png)
![image](https://user-images.githubusercontent.com/58653359/99477683-f9064f80-298d-11eb-92be-4bae82ece4a9.png)

**Applicable Versions:**

 - Netlify CMS version: "netlify-cms-app": "2.13.1",
 - Git provider: gitlab (AWS lightsail bitnami)

**CMS configuration**

    # https://www.netlifycms.org/docs/gitlab-backend/
    backend:
      name: gitlab
      repo: root/site.com
      branch: master
      api_root: https://mygitlab.com/api/v4
      base_url: https://mygitlab.com/
      auth_type: implicit
      app_id: 222
      auth_endpoint: oauth/authorize
    # Where to save image
    media_folder: src/content/images/cms
    # Prefix image url (gatsby-remark-relative-images staticFolderName + media_folder = image)
    public_folder: /images/cms
    publish_mode: editorial_workflow
    collections:
      - name: default
        label: Default
        folder: src/content/pages
        create: true
        media_folder: ''
        public_folder: ''
        path: '{{path}}/{{path}}'
        preview_path: '{{path}}'
        fields:
          - { name: path, label: Path, widget: 'string' }
          - { name: createdAt, label: Created Date, widget: 'datetime' }
          - { name: updatedAt, label: Last Updated Date, widget: 'datetime' }
          - { name: title, label: Title, widget: 'string' }
          - { name: description, label: Description, widget: 'string' }
          - { name: keywords, label: Keywords, widget: 'string' }
          - { name: tags, label: Tags, widget: 'list' }
          - { name: featuredImage, label: Featured Image, widget: 'image' }
          - { name: content, label: Show on home page, widget: 'boolean', default: true }
          - { name: body, label: Body, widget: 'markdown' }

**Comment by erezrokah** [comment]
Hi @stevemarksd, including the identity widget script is intended as that guide is meant to be used with a `git-gateway` backend which requires Netlify Identity for authentication.
You can disable it via https://www.gatsbyjs.com/plugins/gatsby-plugin-netlify-cms/#enableidentitywidget

**Comment by stevemarksd** [comment]
So if you do `enableIdentityWidget: false,`, it will just not work at all on `/admin` page. How is supposed to make it work on `/admin` but don't include in the regular pages?

**Comment by erezrokah** [comment]
Hi @stevemarksd, this is explained [here](https://answers.netlify.com/t/common-issue-netlify-cms-git-gateway-email-not-confirmed/10690).

By default Netlify Identity emails redirect to the root of the site, so the widget has to be included under the root path.
If you're using identity only for the CMS you can configure emails templates per the above thread and also [exclude the widget from the site bundle](https://github.com/gatsbyjs/gatsby/tree/f9e93ad06749d5357307d3f8a0635d0c2a26069a/packages/gatsby-plugin-netlify-cms#disable-widget-on-site).
