### ISSUE TITLE
Too many malicious sites being hosted

### ISSUE THREAD

**Issue by drveresh** [netlify/netlify-cms#4609]
Hi,

Your site is getting abused a lot through fake websites hosted on your site and shared through short links around.  Can you please block them and terminate those users?

Examples:
https://amz.run/4068
https://amz.run/408u
https://amz.run/40Cn

There are 1000s of these fakes sites are being hosted on your platforms and reported by numerous security companies worldwide.  You must take care of this asap.

Thanks.

**Comment by erezrokah** [comment]
Hi @drveresh, this repo is for Netlify CMS - a content management system.
Can you please report these sites via https://www.netlify.com/support/. 
There is a `Report Fraud or Abuse` in the dropdown.

**Comment by drveresh** [comment]
Ok, thanks.
