### ISSUE TITLE
Netlify adding // instead of single /

### ISSUE THREAD

**Issue by rushichaudhari** [netlify/netlify-cms#4648]
**Is your feature request related to a problem? Please describe.**

When I'm uploading image, it isn't getting displayed. After debugging i realized it is adding two // in image section like shown below 
[image](https://imgur.com/a/yBVPXkv)

The website on which I'm trying netlify is available [here](https://github.com/rushichaudhari/rushichaudhari.github.io)

**Describe the solution you'd like**
I didn't find anything in the documentation to remove that extra slash. Would anyone spare some time to explain ?

**Comment by tomrutgers** [comment]
Could you post the contents of your config.yml?

**Comment by erezrokah** [comment]
Hi @rushichaudhari, the content file looks ok:
https://github.com/rushichaudhari/rushichaudhari.github.io/commit/0a02673767ac96a7b15087babffaa8d0a71b1da3#diff-f3a5199fab91e697b6ea8b39bbbc5967416bac4b40588f2d639d0b811b358a51R12

This seems to be an issue with the way your site is built and not how the CMS saves the path to images.

I'm closing the issue, please comment if you need more information in debugging this.
