### ISSUE TITLE
The Road to 1.0

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#465]
This issue is a discussion forum for the [1.0 Milestone](https://github.com/netlify/netlify-cms/milestone/1). We'll be working together as a community to achieve this milestone through issues, pull requests, and [Gitter](https://gitter.im/netlify/netlifycms). We'll also be having bi-weekly, open planning sessions, so check out the [event page](https://www.eventbrite.com/e/netlify-cms-planning-session-bi-weekly-tickets-35794058994) and join us!

The high level priorities for 1.0 include:

* **A predictable, reliable experience across common interactions for users.**
The CMS has to be enjoyable for users, period. It should do what's expected without beta bugs and poorly communicated errors, and provide a top notch editing experience.
* **Greatly simplified implementation experience for devs.**
Getting started with CMS from an implementation standpoint should be quite easy. It already is to an extent, but there's plenty of improvement opportunity, such as setting configuration through the UI and greatly improving documentation and tutorials.
* **Completely decouple the CMS from Netlify service dependencies.**
It's important that the CMS be truly platform agnostic, so baked in services like Netlify auth need to be moved to plugins, and other options should be made available for features like auth and asset storage.

We have many issues open to cover the first bullet, and not very many for the other two. Creating those issues (and resolving them) is a 1.0 effort.

We're determined to see our first major release happen in a matter of months, and it's going to take all of us who use and love the CMS to make it happen! Let's discuss refinement of the 1.0 milestone items below.

---

## Update - Sep 7, 2017
So it's been a few months and we still have a ways to go before 1.0. In that time, our goals have become a bit more clear: 1.0 has to be about facilitating widespread adoption of the CMS. Here's why:

* More implementations should mean more contributors. More contributors means a better CMS for everyone. Increasing the level of contribution is critical for anyone that benefits from this project.
* Increased adoption means people can start building things around the CMS, like templates. Proliferation of templates will result in simpler and higher quality entry points for anyone implementing the CMS.
* More interest in the CMS means more willingness to use the CMS, which is another important point for implementors. Right now developers have to help the people get on board with the static approach to web development, and the CMS is a crucial part of that consideration. If the CMS is in greater demand, it can help developers who prefer static development get buy-in for that approach wherever they are.

All of that said, these are the new priorities centered around this goal of adoption:

* Bugfixes and improvements only (a complete redesign, new markdown editor, and media library excluded). New features will be merged to a beta/canary branch so that folks who need them can have access, but we need to ensure that supporting new features doesn't delay 1.0 any further.
* Create docs for users. Right now all CMS docs are for developers, but there is a need for content creators to have some sort of reference.
* Help developerss implement the CMS by writing tutorials. There are many cases that folks don't think can be done static, so we need to show them how.
* Create templates that cover different use cases. This may come down to a handful of flexible templates, but we need to cover solid use cases when 1.0 is released.

As before, 1.0 issues are being tracked in the [milestone](https://github.com/netlify/netlify-cms/milestone/1), and discussion of the milestone itself can happen in comments below.

Please chime in with thoughts!

**Comment by ChrBach** [comment]
Agreed. Just summarizing:

Milestone 1.0 = when Smashing goes live = Sept 5th.

- Developer experience: An easy painless way to get up and running and basic configuring / handover to a non-tech client.

- User experience: Basically Cassandra's current use free of issues.

- A true usecase off of Netlify services. With a blog. Not sure if the pirate party already does the job...

**Comment by tech4him1** [comment]
What about splitting the GitHub integration off into a plugin as well, that way there would be a standard interface for other integrations when they come along (like GitLab, BitBucket, or an enterprise VC)? That would also help make the CMS more platform agnostic.

**Comment by erquhart** [comment]
@tech4him1 the backend system is already pluggable, actually! If you have a look in the [backends](https://github.com/netlify/netlify-cms/tree/cdf7c3a2beaa058247b52166102afa19e7b72c87/src/backends) directory, you'll see how it works. Additional backends can follow the GitHub integration as a template.
