### ISSUE TITLE
Can't join Public Slack Channel as per NPM Instructions

### ISSUE THREAD

**Issue by jcarroll-ceo** [netlify/netlify-cms#4695]
When browsing NPM, there is a link at the bottom about joining the public Slack for NetlifyCMS.
https://www.npmjs.com/package/gatsby-plugin-netlify-cms

However, when going to that link, it prompts to sign into a slack account (which I have a few of) but then ultimately says "I need to be an @netlify user" to join.  I suspect it's not public anymore and maybe NPM might need to be updated to reflect that? Else Im having a hella of a time joining using either my three slack accounts (@gmail, etc). 

<img width="626" alt="image" src="https://user-images.githubusercontent.com/72282139/101435271-4c065f00-38c9-11eb-83a9-ced5183c7622.png">

**Comment by erezrokah** [comment]
Hi @jcarroll-ceo, good catch we need to update that link on the Gatsby repo.
You can use the [link](https://www.netlifycms.org/chat) from this page https://www.netlifycms.org/

**Comment by erezrokah** [comment]
Fixed in https://github.com/gatsbyjs/gatsby/pull/28529

**Comment by jcarroll-ceo** [comment]
awesome thank you @erezrokah

**Comment by arctiqtim** [comment]
Hi there ... this link still takes you to a signup requiring a netlify.com email address.  :(

**Comment by erezrokah** [comment]
Thanks @arctiqtim, the link had expired - https://github.com/netlify/netlify-cms/pull/4799 should fix it.

**Comment by christopherjbaker** [comment]
The link is broken again.

**Comment by erezrokah** [comment]
Thanks @chadwithuhc - this should be fixed (again). Slack links are valid for 30 days. We'll try to find a way to automate it.
