### ISSUE TITLE
Netlify CMS hacked

### ISSUE THREAD

**Issue by nolafs** [netlify/netlify-cms#4728]
Hi,

Not entirely sure how this could have happened but somebody was able to create post on one of our clients website. After further investigation, we could see a pull request from the cms from a GitHub use. Obviously a fake GitHub account.  Luckily it only created deploy preview. After checking the Netfliy account, we notice to new accounts under Identify of the site and the registration preference set to open. We never ever set this to open. Not sure how this was happened unless the admin login got compromised.

Should the CMS be accessible so easily? What about if like to use the identify for comment feature allow them to register to site. I surely do not want them all having access to the CMS. 

What is best way to secure your CMS?

Olaf

**Comment by erezrokah** [comment]
> We never ever set this to open. Not sure how this was happened unless the admin login got compromised.

Hi @nolafs, if Netlify Identity is set to open than means anyone can register and use the CMS - so good thing you disabled it.

> Should the CMS be accessible so easily?

You could use a different authentication mechanism (I'm assuming you're using `git-gateway` backend):
https://www.netlifycms.org/docs/github-backend/

That way only users with a GitHub account that has access to the repo can use the CMS.

> What about if like to use the identify for comment feature

I'm not sure I understand this.

> What is best way to secure your CMS?

You could set up [branch protection](https://docs.github.com/en/enterprise-server@2.20/github/administering-a-repository/configuring-protected-branches) as an additional measure so only approved (reviewed) PRs can be merged.
That would require approving CMS PRs in GitHub before someone could publish it via the CMS.

**Comment by erezrokah** [comment]
Closing the issue as I believe it is answered. Please comment if you have further questions.

**Comment by nolafs** [comment]
Thanks
