### ISSUE TITLE
Relation field with list widget

### ISSUE THREAD

**Issue by afunnydev** [netlify/netlify-cms#473]
**- Do you want to request a *feature* or report a *bug*?**
Feature
**- What is the current behavior?**
The relation widget can look for fields in collection.
 
**- What is the wanted behavior?**
It would be nice if it could also look into the "subfields" of a list field in a collection. 
For example, I have a collection named "catalog", which contain a list field named "product", and this field as 3 fields: id, name and author. It would be awesome to be able to be able to use id, name and author in searchFields or valueField to retrieve the "subfields" of this list field.

**Comment by barthc** [comment]
This is now supported, you can do:
 `searchFields: ['list.0.title']`  and
 ` valueField: '{{fields.list[0].title}}'`

We still need to document though.
