### ISSUE TITLE
Error loading the CMS configuration

### ISSUE THREAD

**Issue by shaiktaabish** [netlify/netlify-cms#4732]
Getting this error even after rechecking all my fields 
<img width="520" alt="Screenshot 2020-12-16 at 7 58 11 PM" src="https://user-images.githubusercontent.com/51703228/102361251-08060f00-3fd9-11eb-9741-1a2a32d12e0a.png">

Config Errors:
'collections[2].fields' fields names must be unique
'collections[3].fields' fields names must be unique
Check your config.yml file.

**Comment by erezrokah** [comment]
Hi @shaiktaabish, can you please follow the issue template and share your `config.yml`?
