### ISSUE TITLE
Next.JS Starter Template is Not Allowing for An Admin Invite 

### ISSUE THREAD

**Issue by bigcurry** [netlify/netlify-cms#4739]
**Describe the bug**
When creating a new Next.JS blog from the starter template, the admin email does not actually have an admin registration modal pop up. 

**To Reproduce**

**Expected behavior**
I tried this out with Gatsby and it works 

I believe this is a bug, I am still new to Netlify so please excuse me if this is inappropriate.

**Comment by erezrokah** [comment]
Hi @bigcurry, this seems like a duplicate of https://github.com/wutali/nextjs-netlify-blog-template/issues/13
I'm closing this issue in favor of that one.

**Comment by tengkuzulfadli** [comment]
I have the same issue with Nextjs-Netlify Blog template
