### ISSUE TITLE
Don't discard edits when receiving an API_ERROR from git

### ISSUE THREAD

**Issue by fool** [netlify/netlify-cms#4760]
**Describe the bug**
In case I receive an API_ERROR when hitting "save" on edits to an existing doc, my edits are discarded (page gets reloaded from git after the error, I think?)

Further, If I am not "watching" the CMS screen after hitting save, I don't even see the error, but it is not obvious that the save failed, so I can hit "publish now" but my edits do not get published (nothing does, it's a no-op), and I am a sad man.

This happened to me for the 20th time today so I finally am opening an issue.

**To Reproduce**
Steps to reproduce the behavior.
1. connect CMS via git_gateway to GitHub
1. enable editorial workflow, to allow drafts to be saved.
1. Create a PR (for instance, a draft for review) with a branch name that conflicts with one that the CMS would create for a doc (for instance: ` cms/collectionname/doc-title`).  You can do this via the CMS or outside of the CMS, but it is less likely outside the CMS to hit the namespace collision.  In my case it was created through the CMS (but then I was pinged out of band for a review + merge so I did it in GitHub not realizing it was a CMS-created draft vs a direct PR on some content).
2. Merge manually in GitHub instead of through the editorial workflow. Don't delete the branch!
3. Attempt to edit the doc
4. See API_ERROR error (if you watch carefully, since it only shows for a few seconds and then is gone completely without sign)
5. realize that you'll need to recreate the edit...but the content showing is PRE-EDIT;  your edits that you just tried to save, were not persisted EVEN IN THE EDITOR, and are gone forever.

In case you want to fix, the error could be better (I don't think this case is covered in https://github.com/netlify/netlify-cms/issues/1693 exactly) - you have to delete the branch at GitHub to unblock further ability to edit that doc through the CMS.

**Expected behavior**
failure to save would not remove changes from my editor session, and would perhaps even show a big red persistent warning about this not-saved, saved state.

**Applicable Versions:**

netlify-cms-app 2.11.29
netlify-cms-core 2.22.0
netlify-cms 2.10.32
GitHub.com, Chrome latest

**CMS configuration**
https://github.com/netlify/internal-docs/blob/master/static/admin/config.yml (but that won't be visible to folks not working at Netlify.  I don't think it's super relevant here beyond the details above but LMK if I am wrong and I can excerpt the config outside of our dozens of internal collection names)

**Comment by erezrokah** [comment]
Hi @fool I believe this was fixed in https://github.com/netlify/netlify-cms/pull/3418 and we also handle branch names conflicts - the CMS will back up the existing branch instead of failing. This was done in https://github.com/netlify/netlify-cms/pull/3879/files#diff-5775cb662532fea58aa1be37c40e9714d5634b182126d96542cff4602b2d41e0R1284

https://github.com/netlify/netlify-cms/pull/3418 was fixed in [netlify-cms-app@2.11.30](https://github.com/netlify/netlify-cms/commits/netlify-cms-app%402.11.30) and https://github.com/netlify/netlify-cms/pull/3879 was fixed in [netlify-cms-app@2.12.15](https://github.com/netlify/netlify-cms/commits/netlify-cms-app%402.12.15).

Do you mind trying this with a newer CMS version?

**Comment by fool** [comment]
awesome news!  I think that is a one-change replacement, right?  Changing
this line:

`  <script src="https://unpkg.com/netlify-cms@2.10.32/dist/netlify-cms.js
"></script>`

to...something newer?  Am I reading here (
https://github.com/netlify/netlify-cms/releases) correctly that `2.10.77`
is the latest and will that include those cms-app updates?

**Comment by erezrokah** [comment]
Yes, you're correct on both.

You can also use `<script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>` (notice the `^`) to get `semver` based updates.

**Comment by erezrokah** [comment]
Closing this issue. Please comment if still relevant
