### ISSUE TITLE
netlfiy-cms-locales | German "der / die / das" fix on newButton

### ISSUE THREAD

**Issue by danielmoessner** [netlify/netlify-cms#4778]
In German there can be der / die and das in front of a word.

English | German
the car | das Auto
the woman | die Frau
the man | der Mann

The current translation for newButton is Neue(r) which misses "das", because Neues Auto would be correct and Neue or Neuer Auto is wrong.

Therefore a better translation would be:
Neue(r/s)

**Comment by erezrokah** [comment]
Hi @danielmoessner, thank you for reporting this issue.
I believe this should be fixed in this file:
https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-locales/src/de/index.js
You can edit it directly in GitHub if you're up to it.

**Comment by danielmoessner** [comment]
I've created a pull request:
[https://github.com/netlify/netlify-cms/pull/4801](https://github.com/netlify/netlify-cms/pull/4801)

**Comment by mirko-kienle** [comment]
Hi, sorry for commenting on a closed issue. I just switched locales to German for a client and was a bit taken aback by the "Neue(r/s)" button, which just looks strange to me. Could I suggest using "{ itemLabel } hinzufügen" instead? It seems to be a fairly common translation method and doesn't hinder the reading flow as much. I'm happy to open a corresponding PR.

**Comment by erezrokah** [comment]
@mirko-kienle I don't know German so I can't contribute to this discussion.
I'd be happy to accept a PR if the community things it's the right thing to do.

**Comment by stefan-wiebe** [comment]
I concur with @mirko-kienle
"Bild hinzufügen" is easier to read and more common than "Neue(r/s) Bild".
"Neues Bild" would also be okay, but that would require Netlify to know the grammatical gender of the item.
