### ISSUE TITLE
missing type: registerEventListener in netlify-cms-core

### ISSUE THREAD

**Issue by logemann** [netlify/netlify-cms#4782]
**Describe the bug**

while trying to use CMS Events via (/cms/cms.js) in my gatsby project:

```
import CMS from 'netlify-cms-app'
import BlogPostPreview from './preview-templates/BlogPostPreview'
import { de } from 'netlify-cms-locales';

CMS.registerPreviewTemplate('blog', BlogPostPreview)
CMS.registerLocale('de', de);

CMS.registerEventListener({
  name: 'prePublish', // or preSave
  handler: ({ entry }) => {
    console.log(entry);
  }
})
```

I saw that **registerEventListener** is not part of the TS typings in netlify-cms-core as opposed to other methods like the ones i used before the registerEvent call. Furthermore it seems i cant even register the listener. No console output fired.

**Expected behavior**
some console logging on publishing an entry in the CMS UI.

**Applicable Versions:**
netlify-cms-app 2.14.8
netlify-cms-core 2.36.7

 - Git provider:  GitHub

**Comment by erezrokah** [comment]
Thanks for opening the issue, linking https://github.com/netlify/netlify-cms/blob/5fc1e840733cced6ce9143bf10b04210b82ed94b/packages/netlify-cms-core/index.d.ts#L446 as the types fix should be in that file.

**Comment by hkennyv** [comment]
hello @erezrokah, do you mind if i pick this one up?

love netlify cms & want to get more acquainted with the codebase starting with this issue

**Comment by logemann** [comment]
really? Hmmm. Thats weird. I tried it with github backend and expected to see the event being called when triggering "publish" in the Netlify-CMS UI.

**Comment by hkennyv** [comment]
@logemann I can try checking with my git-gateway backend connected to github sometime in the next couple days. Maybe you can try testing it locally by changing your backend to `test-repo`(more details [here](https://www.netlifycms.org/docs/test-backend/)) in your `config.yml` this way you don't have to keep pushing commits to test things.

**Comment by logemann** [comment]
@hkennyv no luck with "local_backend: true" (while running the proxy) either regarding getting the event handler to work. 
Can you show me your test code? Mine is pretty simple:

```
import CMS from 'netlify-cms-app'
import BlogPostPreview from './preview-templates/BlogPostPreview'

CMS.registerPreviewTemplate('blog', BlogPostPreview)

CMS.registerEventListener({
  name: 'prePublish', // or preSave
  handler: (data) => {
    console.log(data);
  }
})
```

**Comment by hkennyv** [comment]
Sure @logemann, I was just using the dev setup from this repository.

There are some basic instructions [here](https://github.com/netlify/netlify-cms/blob/master/CONTRIBUTING.md). Basically, it uses the files in the `dev-test/` directory.

Here is the [config.yml](https://github.com/netlify/netlify-cms/blob/master/dev-test/config.yml) and the [index.html](https://github.com/netlify/netlify-cms/blob/master/dev-test/index.html).

I added your snippet to the end of the script in `index.html` like this.

```javascript
    CMS.registerPreviewTemplate("posts", PostPreview);
    CMS.registerPreviewTemplate("general", GeneralPreview);
    CMS.registerPreviewTemplate("authors", AuthorsPreview);
    CMS.registerPreviewStyle(previewStyles, { raw: true });
    // Pass the name of a registered control to reuse with a new widget preview.
    CMS.registerWidget("relationKitchenSinkPost", "relation", RelationKitchenSinkPostPreview);
    CMS.registerEditorComponent({
      id: "youtube",
      label: "Youtube",
      fields: [{name: 'id', label: 'Youtube Video ID'}],
      pattern: /^{{<\s?youtube (\S+)\s?>}}/,
      fromBlock: function(match) {
        return {
          id: match[1]
        };
      },
      toBlock: function(obj) {
        return '{{< youtube ' + obj.id + ' >}}';
      },
      toPreview: function(obj) {
        return (
          '<img src="http://img.youtube.com/vi/' + obj.id + '/maxresdefault.jpg" alt="Youtube Video"/>'
        );
      }
    });

    // added snippet
    console.log("registering prePublish event listener...");
    CMS.registerEventListener({
      name: 'prePublish', // or preSave
      handler: ({ entry }) => {
        console.log(entry);
      }
    });
```

I haven't been able to get this setup to work with a different backend than `test-repo`, but I have some other repositories I can test it out on for you

**Comment by mikestopcontinues** [comment]
This issue should be re-opened. The merged types are wrong. Right now, the type for `handler` is `{entry, author}` rather than `({entry, author}) => void`.

**Comment by erezrokah** [comment]
Hi @mikestopcontinues, nice catch! A PR to fix this would be great, the code is here:
https://github.com/netlify/netlify-cms/blob/157851e9c4f0123e2018c74f6be54a543f2645ab/packages/netlify-cms-core/index.d.ts#L485

**Comment by hkennyv** [comment]
Whoops, my mistake.. thank you for pointing that out @mikestopcontinues! How does #5353 look? @erezrokah

**Comment by mikestopcontinues** [comment]
@hkennyv that's spot on. Thanks!
