### ISSUE TITLE
Support for multiple branches

### ISSUE THREAD

**Issue by Benaiah** [netlify/netlify-cms#479]
Ideally the CMS would support publishing to multiple branches, so you can have alternate versions of the site. This would be useful in particular for split testing based on Git branches. It'd also be nice to be able to have alternate versions of content available when the two branches differ, so you can, for instance, handle split-testing content through the CMS.

**Comment by erquhart** [comment]
@benaiah why closed?

**Comment by brunodbo** [comment]
Is it possible to reopen this issue (if not, I'll happily create a new one for this request)? It would be great to have support for multiple branches in Netlify CMS, so we could use it together with Netlify's (branch based) split testing functionality.

**Comment by erezrokah** [comment]
Hi @brunodbo, I recommend opening a new issue with a detailed feature request.
I can't understand how multiple branches support will look like based on this issue, or if it is covered by the solution here https://github.com/netlify/netlify-cms/issues/3790#issuecomment-635920266
