### ISSUE TITLE
Create new post should initiate a "pull request" workflow

### ISSUE THREAD

**Issue by phae** [netlify/netlify-cms#48]
Note: The action of creating a new item should map onto the Github concept of a PR. 
- Create new item == create a branch
- Submit item for review == Submit pull request
- Mark as OK to go live == Approve and merge pull request
- Publish == Master deployed

Acceptance criteria:
- [x] Creating a new post should create a branch in the repository
- [x] Branched items should be noted in the UI as "Draft"
- [ ] A user can click a button to mark the post as "For review", flagging the branch as a PR that is ready for approval
- [ ] A user can click a button to mark the post as "Ready to go live", approving the PR and merging it into master (but not actually live!).
- [x] A user can click a button to publish the post, deploying master.

Technicalities of when PR is merged in are up to implementer - the stuff I said are just suggestions - it might make some sense to simply use a comment on a PR to note if something is "good to go live" rather than merge at that point, but I'll let those that know best decide. :)

**Comment by biilmann** [comment]
Some thoughts around this:

Right now the way we show entries in the list view, is looking at our `config.yml`, determining which collections we have and what folders/files they correspond to, and then loading those from the main branch of the repository.

This will still work fine for the "Published" cards in the list below the dashboard in this view: https://phae.github.io/netlify-sketch/

However, for the 3 columns of Drafts, Waiting for review, Waiting to go live - we need some other way of handling the git integration.

One idea: we pick a branch naming convention (netlify-cms-entry-2016-08-10-some-thing) that lets us generate this list by querying the branches in the repository.

This would handle the Drafts column.

I'm a bit in doubt about the two next columns, it seems that these columns would be pull requests from branches following our naming pattern, but how do we determine which ones are waiting for review and which one are waiting to go live?

**Comment by phae** [comment]
Could you use the commit subject line or description + a naming convention to flag those other types of status?

**Comment by phae** [comment]
Or git notes? 😕 https://git-scm.com/docs/git-notes

**Comment by cassiozen** [comment]
<img width="778" alt="editorial-workflow" src="https://cloud.githubusercontent.com/assets/33676/19452442/d10d9002-948f-11e6-9463-06955b6c15c8.png">
