### ISSUE TITLE
Incorrect default value for cms_label_prefix listed in docs

### ISSUE THREAD

**Issue by fkohrt** [netlify/netlify-cms#4811]
**Describe the bug**

The docs [state](https://github.com/netlify/netlify-cms/blob/89848e034451baed52fb8911d3778a2f469462f8/website/content/docs/backends-overview.md#L21) that the default value for `cms_label_prefix` is `netlify-cms/`, but it seems to me it is only `cms/`.

**Comment by erezrokah** [comment]
Hi @fkohrt, that value is for PR labels (not branch names prefix). See:
https://github.com/netlify/netlify-cms/pull/3947
![image](https://user-images.githubusercontent.com/26760571/103882601-bd157e00-50e4-11eb-8413-d7791eb5a800.png)

Closing the issue. Feel free to comment if you have additional questions

**Comment by fkohrt** [comment]
Oops, my bad!
