### ISSUE TITLE
Use of Emojis in Identity Generated Email Subject

### ISSUE THREAD

**Issue by kylesloper** [netlify/netlify-cms#4820]
### This is purely aesthetics but I think it would be cool to be able to use emojis in the subject of Identity Generated emails.

![image](https://user-images.githubusercontent.com/45979758/104095708-53d26e00-5290-11eb-93ea-b95fa4d3704e.png)

**Comment by talves** [comment]
@kylesloper This feature is actually driven by the netlify identity open source project. Closing since you already posted the feature request and [Discussion Here](https://community.netlify.com/t/use-of-emojis-in-identity-generated-email-subject/29782)
