### ISSUE TITLE
Unable to access identity settings. When using git-gateway backend make sure to enable Identity service and Git Gateway.

### ISSUE THREAD

**Issue by tate2301** [netlify/netlify-cms#4821]

**Comment by talves** [comment]
Try starting with [these recommendations](https://community.netlify.com/t/problems-to-identify-git-gateway/10670)

**Comment by erezrokah** [comment]
Hi @tate2301, also https://docs.netlify.com/visitor-access/identity/ and https://docs.netlify.com/visitor-access/git-gateway/.
If that doesn't work please fill in the missing parts from the [issue template](https://github.com/netlify/netlify-cms/issues/new?assignees=&labels=type%3A+bug&template=bug_report.md&title=Please+replace+with+a+clear+and+descriptive+title) as they help us find the cause for the issue.

**Comment by tate2301** [comment]
Thanks, that solved my issue.
