### ISSUE TITLE
Cover Image Via Links

### ISSUE THREAD

**Issue by greatwarlive** [netlify/netlify-cms#484]
In Jekyll you can use the cover image as a link instead of saving the image to your github repo. How can you do this in Netlify CMS?

**Comment by erquhart** [comment]
You can simply save the url as a string (via the default string widget). If you want the CMS to preview it in the editor, you'll need to add a custom preview component for that field.

**Comment by erquhart** [comment]
Going to close this, but you should check out our Gitter: https://gitter.im/netlify/netlifycms

Someone is almost always on, fastest way to get questions answered :)
