### ISSUE TITLE
Error message for config issues

### ISSUE THREAD

**Issue by ziburski** [netlify/netlify-cms#487]
When there is an issue with the config.yml (e.g. syntax), there should be an error message stating that.

I had a double colon in mine, and the CMS failed to load at all — nothing happened after clicking the GitHub login button.

#368 doesn’t seem to have fixed my case.

**Comment by tech4him1** [comment]
@ziburski Can you provide an exact case for testing?

**Comment by tech4him1** [comment]
OK, we do throw errors on most config issues, double colons are a special case though, as the YAML parser assumes that it is part of the key name. The only way I see to check this is to validate the config at load time by checking that every value that we need exists.

**Comment by erquhart** [comment]
I wonder how this looks with the error boundary in place.

**Comment by erquhart** [comment]
Actually we should just wrap config parsing in a try/catch (as a fallback after checking for required values). We could output the error in the UI, too. The current error boundary component can maybe be triggered by us and used for general purpose errors that are showstoppers, or at least CMS load stoppers like this one.

**Comment by tech4him1** [comment]
@erquhart The reason this specific error isn't caught is because the config actually parses without failure.  The problem comes when we assume a key exists, but it does not. That's a case where we have to explicitly check that the required keys exist.

**Comment by erquhart** [comment]
Agreed, let's check for all required keys, then. It'll be nice to have that in one place for reference, too.
