### ISSUE TITLE
NetlifyCMS: Login status

### ISSUE THREAD

**Issue by krzysiekhum** [netlify/netlify-cms#4874]
**Problem:**
When content is edited by authors in Netlify CMS, the session is sometimes interrupted without warning. For example: the text is edited and saved as a draft. Then, after some time, the author returns to editing the entry, but after saving he gets the information that **he is not logged in** (although he was :/).

Could you add a feature, that informations about current session (when it is going to expire etc.)

**Comment by erezrokah** [comment]
Hi @krzysiekhum do you mind phrasing your feature request per the [feature template](https://github.com/netlify/netlify-cms/issues/new?assignees=&labels=type%3A+feature&template=feature_request.md&title=Please+replace+with+a+clear+and+descriptive+title)?

That helps us better understand your use case. Please share your CMS configuration too.
