### ISSUE TITLE
Link button in editor malfunctioning

### ISSUE THREAD

**Issue by cassandraoid** [netlify/netlify-cms#488]
** *bug*? **

**- What is the current behavior?**

When I attempt to create a link for text by highlighting desired text, then click the link button - the box to insert the web address does not pop up. However, if you switch to markdown, it's clear that the 'link' functionality was triggered. 

**- If the current behavior is a bug, please provide the steps to reproduce.**

See above
**- What is the expected behavior?**

**- Please mention your node.js, and operating system version.**

**Comment by verythorough** [comment]
When @cassandraoid pointed this issue out to me, I was able to repro on my own machine as well.

**Comment by erquhart** [comment]
Addressed in #254, will close when released.

**Comment by erquhart** [comment]
Fixed in the new editor.
