### ISSUE TITLE
API_ERROR: Timed out rebasing merge request - when making edits to draft via editorial workflow

### ISSUE THREAD

**Issue by lbarker** [netlify/netlify-cms#4890]
**Describe the bug**

We are getting errors when users attempt to edit a draft in Netlify CMS and save their changes.

The error is `Failed to persist entry: API_ERROR: Timed out rebasing merge request`

![Screen Shot 2021-01-27 at 3 55 09 PM](https://user-images.githubusercontent.com/1869546/106335811-606c3580-6242-11eb-9508-b184145ea975.png)

[about.gitlab.com-1611960359181.log](https://github.com/netlify/netlify-cms/files/5896766/about.gitlab.com-1611960359181.log)

**To Reproduce**
1. Login to the admin
2. Switch to the workflow tab
3. Make an edit to any draft
4. Click the "save" button
5. Error received in console.

**Expected behavior**

Edit to draft is saved, commit is made to branch on origin

**Screenshots**

![api_error_jan-21](https://user-images.githubusercontent.com/1869546/106335224-3c5c2480-6241-11eb-8feb-5524e45a5f8e.gif)

**Applicable Versions:**
 - Netlify CMS version: 2.14.14
 - Git provider: GitLab
 - OS: Chrome 88 on macOS (Catalina)

**CMS configuration**

https://gitlab.com/gitlab-com/www-gitlab-com/-/blob/master/sites/marketing/source/admin/config.yml

**Additional context**

[Link to issue on GitLab](https://gitlab.com/gitlab-com/marketing/inbound-marketing/growth/-/issues/929)
[Repository](https://gitlab.com/gitlab-com/www-gitlab-com)
[Our documentation for this implementation of Netlify CMS](https://gitlab.com/gitlab-com/www-gitlab-com/-/blob/master/doc/netlifycms.md)

**Comment by lbarker** [comment]
This also triggers a pipeline in our GitLab repo and the MR displays that it was successfully rebased. 
For example, [this MR](https://gitlab.com/gitlab-com/www-gitlab-com/-/merge_requests/73207) shows 16 pipeline triggered but only 1 commit. I

**Comment by erezrokah** [comment]
Thanks for opening the issue @lbarker.
The CMS rebases the draft PR before making new commits, see:
https://github.com/netlify/netlify-cms/blob/d30a45cc522fa468d4e00c906d16b889c637f19d/packages/netlify-cms-backend-gitlab/src/API.ts#L681

Maybe a timeout of 10s is too short for the operation?

Also, we set the `skip_ci` flag when doing the rebase. This was fixed recently in https://github.com/netlify/netlify-cms/pull/4802.

I'll fork the repo and see if I can reproduce.

**Comment by erezrokah** [comment]
FYI, I increased the rebase timeout to 30 seconds with the latest release

**Comment by lbarker** [comment]
@erezrokah increasing the timeout to 30 seconds fixed this issue! Successfully made an edit to a draft in this [MR](https://gitlab.com/gitlab-com/www-gitlab-com/-/merge_requests/73207). 

Thank you!
