### ISSUE TITLE
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. Th...

### ISSUE THREAD

**Issue by qb-rivkyb** [netlify/netlify-cms#4967]
**Describe the bug**
When using react hooks in a component that is used with CMS.registerWidget. I get this error since the version of React in `netlify-cms-app` is lower than in my project which uses the latest version

**To Reproduce**
create a next-app. create an admin page. Add `netlify-cms-app` to the project. Create a component with a hook in it which is used when I do `CMS.registerWidget()`. 

**Expected behavior**
The version of react should be updated to the latest.

**Screenshots**
![Screen Shot 2021-02-17 at 4 47 18 PM](https://user-images.githubusercontent.com/75636699/108272328-16d78200-7140-11eb-9dbd-81c5bc29b6a8.png)

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.14.23`
 - Git provider: `github`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36`

**CMS configuration**
```
backend:
  name: github
  repo: [my user name]/[my repo]
  branch: main
...and rest of config.
...

**Comment by banyudu** [comment]
Should react and react-dom be peer-dependencies of `netlify-cms-core` instead of dependencies?

**Comment by erezrokah** [comment]
Hi @qb-rivkyb The CMS is a self contained React app, so per the limitations of using hooks you probably need to use the React copy the CMS uses (regardless of the version).
We could expose it the same way we expose `moment` https://github.com/netlify/netlify-cms/blob/4d296ed77e48ff49fde9041ead0c63d1f93e1b56/packages/netlify-cms-app/src/index.js#L14 or you can try importing the `esm` module from `netlify-cms-app/dist/esm`.
Sharing a public repo with your setup will help find a solution.

@banyudu I think it's more about supplying 2 versions of the CMS - one with React bundled with it, and one that users can bring their own version (as peer-dependencies are also bundled).

**Comment by qb-rivkyb** [comment]
Hi,
I ended up adding this to my `package.json` and it fixes it for now. I cannot share my repo but if I have time I can try to create a test repo.

```
"resolutions": {
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  }
```

**Comment by erezrokah** [comment]
Thanks @qb-rivkyb that's useful. I'm going to close the issue. Please comment if still relevant.

**Comment by banyudu** [comment]
For those who are developing a custom widget

Change
```js
import CMS, { init } from 'netlify-cms'
```
to
```js
import CMS from 'netlify-cms-app';
const { init } = CMS
```
may help.
