### ISSUE TITLE
TypeError: Cannot read property 'alt' of undefined

### ISSUE THREAD

**Issue by bhargavmoveo** [netlify/netlify-cms#4970]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.12.19`
 - Git provider: `bitbucket`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36`

**CMS configuration**
```
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
backend:
  name: bitbucket
  repo: bhargavmoveo/holistic-strane
  branch: master
  auth_type: implicit
  app_id: fa4uUrwyrA4zJQrWH8
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"
media_folder: static/img
public_folder: /img
collections:
  - view_filters: []
    meta: {}
    name: blog
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    folder: src/pages/blog
    publish: true
    sortableFields:
      - commit_date
      - title
      - date
      - commit_author
      - description
    label: Blog
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: blog-post
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: text
      - label: Featured Post
        name: featuredpost
        widget: boolean
      - label: Featured Image
        name: featuredimage
        widget: image
      - label: Body
        name: body
        widget: markdown
      - label: Tags
        name: tags
        widget: list
    create: true
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Home Page
        name: index
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: index-page
          - label: Homebanner
            name: homebanner
            widget: object
            fields:
              - label: Bannertitle
                name: bannertitle
                widget: string
                required: false
              - label: Stranebannerlogo
                name: stranebannerlogo
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Eyehybridimage
                name: eyehybridimage
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Homeblackflowerblock
                name: homeblackflowerblock
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Homegreydiamondblock
                name: homegreydiamondblock
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Alt
                    name: alt
                    widget: string
                    required: false
              - label: Homegreydiamondtextblock
                name: homegreydiamondtextblock
  
...

**Comment by erezrokah** [comment]
Hi @bhargavmoveo, can you share a screenshot of the error, the full `config.yml` file and possibly a repo reproducing the issue?

**Comment by bhargavmoveo** [comment]
@erezrokah here you go.
![Screenshot 2021-02-18 at 4 30 58 PM](https://user-images.githubusercontent.com/76469453/108347602-b4958480-7206-11eb-9b6f-ff1c09a94078.png)


media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages" 
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Homebanner, name: homebanner, widget: object, fields: [{label: Bannertitle, name: bannertitle, widget: string, required: false},{label: Stranebannerlogo, name: stranebannerlogo, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, {label: Eyehybridimage, name: eyehybridimage, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},{label: Homeblackflowerblock, name: homeblackflowerblock, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},{label: Homegreydiamondblock, name: homegreydiamondblock, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},{label: Homegreydiamondtextblock, name: homegreydiamondtextblock, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},{label: Homeyellowcartblock, name: homeyellowcartblock, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},{label: Iconcrownblack, name: iconcrownblack, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, {label: Bannerbottomtext, name: bannerbottomtext, widget: string, required: false}]}
          - {label: Stranetwoblocks, name: stranetwoblocks, widget: object, fields: [{label: Stranefirstblock, name: stranefirstblock, widget: object, fields: [{label: Straneblocklogo, name: straneblocklogo, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},{label: Content, name: content, widget: string}, {label: Buttontext, name: buttontext, widget: string},{label: Straneblockpattern, name: straneblockpattern, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}]}, {label: Stranesecondblock, name: stranesecondblock, widget: object, fields: [{label: Straneblocklogo, name: straneblocklogo, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},{label: Content, name: content, widget: string}, {label: Buttontext, name: buttontext, widget: string},{label: Straneblockpattern, name: straneblockpattern, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}]} ]}
          - {label: Threetab, name: threetab, widget: object, fields: [{label: Tab1, name: tab1, widget: object, fields: [{label: Vapcloud, name: vapcloud, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, {label: Vapitimage, name: vapitimage, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},{label: Paxicon, name: paxicon, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, {label: "Leftcontent", name: "leftcontent", widget: "markdown"},{label: Leftlinktext, name: leftlinktext, widget: string},{label: Leftlink, name: leftlink, widget: string},{label: "Rightcontent", name: "rightcontent", widget: "markdown", required: false},{label: Rightlinktext, name: rightlinktext, widget: string, required: false}, {label: Rightlink, name: rightlink, widget: string, required: false}]},
                {label: Tab2, name: tab2, widget: object, 
                fields: [
                        {label: Smokecloud, name: smokecloud, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, 
                        {label: Smokeimage, name: smokeimage, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, 
                        {label: Smokejoint, name: smokejoint, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, 
                        {label: "Leftcontent", name: "leftcontent", widget: "markdown"}, 
                        {label: Leftlinktext, name: leftlinktext, widget: string}, 
                        {label: Leftlink, name: leftlink, widget: string},  
                        {label: "Rightcontent", name: "rightcontent", widget: "markdown", required: false}, 
                        {label: Rightlinktext, name: rightlinktext, widget: string, required: false}, 
                        {label: Rightlink, name: rightlink, widget: string, required: false}  
                        ]
                },
                {label: Tab3, name: tab3, widget: object, 
                fields: [
                        {label: Dabrig, name: dabrig, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, 
                        {label: Dabimage, name: dabimage, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, 
                        {label: Dabtool, name: dabtool, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, 
                        {label: Dabtorch, name: dabtorch, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, 
                        {label: "Leftcontent", name: "leftcontent", widget: "markdown"}, 
                        {label: Leftlinktext, name: leftlinktext, widget: string}, 
                        {label: Leftlink, name: leftlink, widget: string},  
                        {label: "Rightcontent", name: "rightcontent", widget: "markdown", required: false}, 
                        {label: Rightlinktext, name: rightlinktext, widget: string, required: false}, 
                        {label: Rightlink, name: rightlink, widget: string, required: false} 
                        ]
                },
                ],
          }
      - file: "src/pages/strane/index.md"
        label: "Strane"
        name: "strane"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "strane-page"}
          - {label: Stranetoppart, name: stranetoppart, widget: object,
              fields: [
                {label: Stranelogo, name: stranelogo, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, 
                {label: Stranetopcontent, name: stranetopcontent, widget: text},
              ]
            }
          - {label: Stranepagesections, name: stranepagesections, widget: list,  default: [{ stranepagesectionname: '' }, { stranepagesectionlink: '' }, { stranesectionimage: '' }, { stranesectionimage2: '' }, { stranesectioncontent: '' }],
              fields: [
                {label: Stranepagesectionname, name: stranepagesectionname, widget: string},
                {label: Stranepagesectionlink, name: stranepagesectionlink, widget: string},
                {label: Stranesectionimage, name: stranesectionimage, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, 
                {label: Stranesectionimage2, name: stranesectionimage2, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, 
                {label: Stranesectioncontent, name: stranesectioncontent, widget: markdown},
              ]
            }
      - file: "src/pages/live/index.md"
        label: "Live"
        name: "live"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "live-page"}
          - {label: Livetoppart, name: livetoppart, widget: object,
              fields: [
                {label: Livepagelogo, name: livepagelogo, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, 
                {label: Livetopcontent, name: livetopcontent, widget: text},
              ]
            }
          - {label: Livepagesliderheading, name: livepagesliderheading, widget: string}  
          - {label: Livepageslider, name: livepageslider, widget: list,
              fields: [
                {label: Livepagesliderimage, name: livepagesliderimage, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, 
                {label: Livepageslidercontent, name: livepageslidercontent, widget: markdown},
              ]
            }
          - {label: Livepagesections, name: livepagesections, widget: list,
              fields: [
                {label: Livepagesectionname, name: livepagesectionname, widget: string, required: false},
                {label: Livepagesectionlink, name: livepagesectionlink, widget: string, required: false},
                {label: Livesectionimage, name: livesectionimage, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, 
                {label: Livesectionimage2, name: livesectionimage2, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, 
                {label: Livesectioncontent, name: livesectioncontent, widget: markdown},
              ]
            }
          - {label: Livepagebottomcontent, name: livepagebottomcontent, widget: markdown}
      - file: "src/pages/pax/index.md"
        label: "Pax"
        name: "pax"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "pax-page"}
          - {label: Paxtoppart, name: paxtoppart, widget: object,
              fields: [
                  {label: Paxpagelogo, name: paxpagelogo, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, 
                  {label: Paxpagelogoright, name: paxpagelogoright, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, 
                  {label: Paxtopcontent, name: paxtopcontent, widget: text},
                ]
            }
          - {label: Paxpagesections, name: paxpagesections, widget: list,
              fields: [
                {label: Paxsectionimage, name: paxsectionimage, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, 
                {label: Paxsectionimage2, name: paxsectionimage2, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, 
                {label: Paxsectioncontent, name: paxsectioncontent, widget: markdown},
              ]
            }
          - {label: Paxpagesliderheading, name: paxpagesliderheading, widget: string}  
          - {label: Paxpageslider, name: paxpageslider, widget: list,
              fields: [
                {label: Paxpageslidercontent, name: paxpageslidercontent, widget: markdown},
              ]
            }
          - {label: Paxpagesections2, name: paxpagesections2, widget: list,
              fields: [
                {label: Paxsectionimage, name: paxsectionimage, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]}, 
                {label: Paxsectioncontent, name: paxsectioncontent, widget: markdown},
                {label: Paxsectioncontentlink, name: paxsectioncontentlink, widget: string, required: false},
                {label: Paxsectioncontenturl, name: paxsectioncontenturl, widget: string, required: false},
                {label: Paxsectioncontentlinkmobile, name: paxsectioncontentlinkmobile, widget: string, required: false},
                {label: Paxsectioncontenturlmobile, name: paxsectioncontenturlmobile, widget: string, required: false},
                {label: Paxsectioncontentimage, name: paxsectioncontentimage, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},
                {label: Paxsectioncontentimagelink, name: paxsectioncontentimagelink, widget: string, required: false},
              ]
            }
      - file: "src/pages/faq/index.md"
        label: "Faq"
        name: "faq"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "faq-page"}
          - {label: Faqpageheading, name: faqpageheading, widget: string}
          - {label: Faqcategorylist, name: faqcategorylist, widget: list,
              fields: [
                  {label: Faqcategoryheading, name: faqcategoryheading, widget: string},
                  {label: Faqcategoryheadername, name: faqcategoryheadername, widget: string},
                  {label: Faqcategoryheaderlink, name: faqcategoryheaderlink, widget: string},
                  {label: Faqcategorycontentlist, name: faqcategorycontentlist, widget: list,
                    fields : [
                      {label: Faqcontenttitle, name: faqcontenttitle, widget: text},
                      {label: Faqcontentbody, name: faqcontentbody, widget: markdown},
                    ]
                  }
                ]
            }      
      - file: "src/pages/process/index.md"
        label: "Process"
        name: "process"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "process-page"}
          - {label: Goingback, name: goingback, widget: object,
              fields: [
                {label: Goingbacksectionname, name: goingbacksectionname, widget: string, required: false},
                {label: Goingbacksectionlink, name: goingbacksectionlink, widget: string, required: false},
                {label: Journeyheading, name: journeyheading, widget: string, required: false},
                {label: Goingbacktitle, name: goingbacktitle, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},
                {label: Goingbackcontent, name: goingbackcontent, widget: text, required: false},
                {label: Goingbackcrownimage, name: goingbackcrownimage, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},
                {label: Goingbackcrowntext, name: goingbackcrowntext, widget: text, required: false},
                {label: Goingbackstars, name: goingbackstars, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},
              ]
            }
          - {label: Seedsection, name: seedsection, widget: object,
              fields: [
                {label: Seedsectionname, name: seedsectionname, widget: string, required: false},
                {label: Seedsectionlink, name: seedsectionlink, widget: string, required: false},
                {label: Searchseedtitle, name: searchseedtitle, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},
                {label: Searchseedtitlestar, name: searchseedtitlestar, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},
                {label: Searchseedcontent, name: searchseedcontent, widget: text, required: false},
                {label: Seedyellowafterline, name: seedyellowafterline, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},
              ]
            }
          - {label: Cultivatesection, name: cultivatesection, widget: object,
              fields: [
                {label: Cultivatesectionname, name: cultivatesectionname, widget: string, required: false},
                {label: Cultivatesectionlink, name: cultivatesectionlink, widget: string, required: false},
                {label: Cultivatetitle, name: cultivatetitle, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},
                {label: Cultivatewatering, name: cultivatewatering, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},
                {label: Cultivatestar, name: cultivatestar, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},                
                {label: Cultivatestar2, name: cultivatestar2, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},                
                {label: Cultivatecontent, name: cultivatecontent, widget: text, required: false},
                {label: Cultivatecontent2, name: cultivatecontent2, widget: text, required: false},
                {label: Cultivateflower, name: cultivateflower, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},
                {label: Cultivateflowerstar, name: cultivateflowerstar, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},
              ]
            }
          - {label: Harvestsection, name: harvestsection, widget: object,
              fields: [
                {label: Harvestsectionname, name: harvestsectionname, widget: string, required: false},
                {label: Harvestsectionlink, name: harvestsectionlink, widget: string, required: false},
                {label: Harvestsectiontitle, name: harvestsectiontitle, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},
                {label: Harvesttitleblackdots, name: harvesttitleblackdots, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},
                {label: Harvestcontent, name: harvestcontent, widget: markdown, required: false},
                {label: Harvestcontent2, name: harvestcontent2, widget: markdown, required: false},
                {label: Harvesthappyimage, name: harvesthappyimage, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},                
                {label: Harvesthappyimageline, name: harvesthappyimageline, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},
                {label: Harvesthappyimagesmall, name: harvesthappyimagesmall, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},                
                {label: Harvesthappyimagestar, name: harvesthappyimagestar, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},                
              ]
            }
          - {label: Labmagicsection, name: labmagicsection, widget: object,
              fields: [
                {label: Labmagicsectionname, name: labmagicsectionname, widget: string, required: false},
                {label: Labmagicsectionlink, name: labmagicsectionlink, widget: string, required: false},
                {label: Labmagicsectiontitle, name: labmagicsectiontitle, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},
                {label: Labmagicsectiontitlestar, name: labmagicsectiontitlestar, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},
                {label: Labmagicsectioncontent, name: labmagicsectioncontent, widget: text, required: false},
                {label: Labmagicsectioncontentsmall, name: labmagicsectioncontentsmall, widget: text, required: false},
                {label: Labdiamondimage, name: labdiamondimage, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},                
                {label: Labdiamondstar, name: labdiamondstar, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},                
                {label: Labdiamondstar2, name: labdiamondstar2, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},                                
                {label: Labwhipimage, name: labwhipimage, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},                
                {label: Labproductimage, name: labproductimage, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},                
                {label: Labbadderimage, name: labbadderimage, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},                
                {label: Labstarimage, name: labstarimage, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},                
              ]
            }
          - {label: Allyourssection, name: allyourssection, widget: object,
              fields: [
                {label: Allyourssectionname, name: allyourssectionname, widget: string, required: false},
                {label: Allyourssectionlink, name: allyourssectionlink, widget: string, required: false},
                {label: Allyourssectiontitle, name: allyourssectiontitle, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},
                {label: Allyourssectiontitleline, name: allyourssectiontitleline, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},
                {label: Allyourssectioncontent, name: allyourssectioncontent, widget: text, required: false},
              ]
            }
          - {label: Signaturesection, name: signaturesection, widget: object,
              fields: [
                {label: Signaturesectionleft, name: signaturesectionleft, widget: object,
                  fields: [
                    {label: Signaturecontent, name: signaturecontent, widget: markdown, required: false},
                    {label: Signaturesectionleftimage, name: signaturesectionleftimage, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},    
                    {label: Signaturesectionleftimage2, name: signaturesectionleftimage2, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},    
                  ]
                },
                {label: Signaturesectionright, name: signaturesectionright, widget: object,
                  fields: [
                    {label: Signaturecontent, name: signaturecontent, widget: markdown, required: false},
                    {label: Signaturesectionrightimage, name: signaturesectionrightimage, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},    
                    {label: Signaturerightdiamondimage, name: signaturerightdiamondimage, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},      
                    {label: Signaturerightdiamond2image, name: signaturerightdiamond2image, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},
                    {label: Signaturerightdiamond3image, name: signaturerightdiamond3image, widget: object, fields: [{label: Image, name: image, widget: image, required: false}, {label: Alt, name: alt, widget: string, required: false}]},
                  ]
                }
              ]
            }  
      - file: "src/pages/findastore/index.md"
        label: "Findstore"
        name: "findastore"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "findastore-page"}
          - {label: Storeaddress, name: storeaddress, widget: list,
              fields: [
                  {label: Storename, name: storename, widget: string},
                  {label: Storeaddress, name: storeaddress, widget: text},
                  {label: storeCity, name: storecity, widget: string},
                  {label: Storestate, name: storestate, widget: string},
                  {label: Storezip, name: storezip, widget: string},
                  {label: Storenumber, name: storenumber, widget: string, required: false},
                  {label: Storeemail, name: storeemail, widget: string, required: false},
                  {label: Storeurl, name: storeurl, widget: string, required: false},
                  {label: Storelat, name: storelat, widget: string},
                  {label: Storelng, name: storelng, widget: string},
              ]
            }                 
  - name: "themeoptions" 
    label: "Themeoptions"
    files:
      - file: "src/pages/footer.md"
        label: "Footer"
        name: "footer"
        fields:        
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "footer"}
          - {label: Leftpart, name: leftpart, widget: object,
              fields: [
                {label: Contactus, name: contactus, widget: string, required: false},
                {label: Email, name: email, widget: string, required: false},
              ]
            }
          - {label: Rightpart, name: rightpart, widget: object, 
              fields: [
                {label: Pagewithlink, name: pagewithlink, widget: object, 
                  fields: [
                    {label: Pagename1, name: pagename1, widget: string, required: false},
                    {label: Pagelink1, name: pagelink1, widget: string, required: false}, 
                  ]
                },
                {label: Pagewithlink2, name: pagewithlink2, widget: object, 
                  fields: [
                    {label: Pagename2, name: pagename2, widget: string, required: false},
                    {label: Pagelink2, name: pagelink2, widget: string, required: false},
                  ]
                },
                {label: Copyright, name: copyright, widget: string, required: false},
              ]
            }

**Comment by erezrokah** [comment]
Thanks @bhargavmoveo, can you provide some information on when does the error occurs? When you try to edit a collection entry? Is the screenshot of the editor pane (left pane) or the preview pane (right pane).?

**Comment by bhargavmoveo** [comment]
@erezrokah Default showing this error without any edit.

**Comment by erezrokah** [comment]
> @erezrokah Default showing this error without any edit.

Can you explain what you mean by `Default`? Does it happen when you open root route (e.g `admin`) of the CMS?
Can you provide a step by step reproduction on a public repo?

**Comment by bhargavmoveo** [comment]
@erezrokah I edit directly .md file so that is showing an error now it's working. Thanks !
