### ISSUE TITLE
Custom editor component sometimes not rendered correctly

### ISSUE THREAD

**Issue by p-goetz** [netlify/netlify-cms#4976]
**Describe the bug**
I have created two custom editor components and defined them inside my `admin/index.html`. When I use them in an empty page they are getting parsed correctly and don't throw any errors in the Javascript console. 
But when I have an empty page and add one of each components sometimes one component won't be rendered correctly and the second component in the page throws a Javascript error. 

**To Reproduce**
1. Create two components in your ´admin/index.html´: 

```javascript
CMS.registerEditorComponent({
  id: "b",
  label: "B",
  fields: [
    {name: 'content', label: 'Content', widget: 'string'}],
  pattern: /{{< b >}}([\s\S]*?){{< \/b >}}/,
  fromBlock: function(match) {
    return {
      content: match[1] ? match[1].trim() : ''
    };
  },
  toBlock: function(obj) {
    return `{{< b >}}\n${obj.content}\n{{< /b >}}`;
  },
  toPreview: function(obj) {
    return (
      `<section class="b">
        ${obj.content}
      </section>`
    );
  }
});
CMS.registerEditorComponent({
  id: "a",
  label: "A",
  fields: [
    {name: 'content', label: 'Content', widget: 'string'}],
  pattern: /{{< a >}}([\s\S]*?){{< \/a >}}/,
  fromBlock: function(match) {
    return {
      content: match[1] ? match[1].trim() : ''
    };
  },
  toBlock: function(obj) {
    return `{{< a >}}\n${obj.content}\n{{< /a >}}`;
  },
  toPreview: function(obj) {
    return (
      `<section class="a">
        ${obj.content}
      </section>`
    );
  }
});
```
2. Add the two components into an empty page: 

```markdown
{{< a >}}TEST{{< /a >}}

{{< b >}}TEST{{< /b >}}
```
3. The first component will not be rendered correctly inside the Netlify CMS markdown editor, the second one will (s. Screenshot): 
![image](https://user-images.githubusercontent.com/1272377/108540258-42de3900-72e1-11eb-9133-a913ea6d145c.png)
4. The second component added to the page will create a Javascript error: 
```
remarkShortcodes.js:53 Sent invalid data to remark. Plugin: b. Value: {{< b >}}TEST{{< /b >}}. Data: {"content":"TEST"}
(anonymous) @ remarkShortcodes.js:53
```

**Expected behavior**
Both components should render correctly in the markdown editor and no error should be thrown. 

**Screenshots**
See above. 

**Applicable Versions:**
 - Netlify CMS version: 2.10.93
 - Git provider: GitLab
 - OS: Ubuntu 20.04
 - Browser version chrome 88.0.4324.150

**CMS configuration**
```yml
backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Page"
    folder: "content"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
```

**Additional context**
One thing that might be interesting is that it depends on both the sequence the editor components are defined in `admin/index.html` and the sequence in which they are added to the page: 

Declaration Sequence | Content Sequence | Throws JS error | correctly rendered
--- | --- | --- | ---
A-B | A-B | no-yes | yes-yes
A-B | B-A | no-yes | no-yes
B-A | B-A | no-yes | yes-yes
B-A | A-B | no-yes | no-yes

So it seems as if the sequence of declaration in `admin/index.html` and the sequence in the page is the same, both will be rendered correctly by the markdown editor. If this sequence is different, only the second will be rendered correctly. 
No matter the sequences it is always the second component in the page that causes the Javascript error. 

I am at a loss but would like to know what I can do to avoid this error. At first it seemed to me that this was a random glitch, until I had it tracked down to the above minimal example. 

If you need any more information, please don't hesitate to reach out to me. Thank you very much for your support!

**Comment by smashercosmo** [comment]
Without digging into the issue I would say that it's probably not a very good idea to use html-like syntax in your custom components, because markdown parser might mistake it for html. Can you try to change syntax to use curly braces only? Like: 
```
{{ a }}TEST{{ /a }}
{{ b }}TEST{{ /b }}
```
And tell if error still persists.

**Comment by p-goetz** [comment]
Thanks for your reply! The problem is that this is Hugo's shortcode syntax that I need to use in order for it to correctly render my content. 
How do other Hugo users do this?

**Comment by smashercosmo** [comment]
Hm... according to docs this should work https://www.netlifycms.org/docs/hugo/#using-hugo-shortcodes-in-the-markdown-editor

**Comment by p-goetz** [comment]
Thanks for checking the docs with me. I have based my editor components on the examples you mentioned in the documentation. To be on the safe side I have also tried your suggestion from yesterday and removed the '<' and '>' from my shortcodes. Obviously they won't work with Hugo, but I wanted to check what Netlify CMS does. 
The bad news: the error is still there. So I guess it has nothing to do with the opening and closing tags themselves, but with something else. When I use the editor components and shortcodes in isolation or the 'right' sequence, they work as expected. 
Do you have any other idea?

**Comment by erezrokah** [comment]
Hi @p-goetz this is where those patterns are used https://github.com/netlify/netlify-cms/blob/b0fcaec4c30e3e7028206de1d83ffdd4a6fdbba8/packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js#L14

**Comment by p-goetz** [comment]
Thanks, @erezrokah! I had briefly looked at this module when I first got these Javascript errors but don't really understand what they are trying to do. I think it is especially the function `eat` that I don't get. Who passes it into the function and what does it do?

**Comment by erezrokah** [comment]
Hi @p-goetz, there's actually a lot of stuff going into that.
To summarize - this is the place where strings from the markdown content are parsed into objects and serialized back to string using the `pattern` and `toBlock` values you provide.
See also https://github.com/netlify/netlify-cms/blob/b0fcaec4c30e3e7028206de1d83ffdd4a6fdbba8/packages/netlify-cms-widget-markdown/src/serializers/remarkShortcodes.js#L59

**Comment by smashercosmo** [comment]
@p-goetz I can look into the issue if you create test repo where this issue can be reliably reproduced

**Comment by p-goetz** [comment]
Thanks for the explanation @erezrokah. I will have a look to get a better understanding. 

@smashercosmo thank you very much for your offer! I have created a simple repository here: https://github.com/p-goetz/netlify-cms-sandbox

It contains one page `test.md` that currently shows the error. That file currently has shortcodes `a` and `b` in the sequence b-a, while the `admin/index.html`defines them in sequence a-b. If you change the sequence in the page to a-b, the markdown editor will correctly show the two shortcodes in the custom editor component. If you leave it as it is, it only shows the second (a) and shows the markup for b. 

If you have any questions or if I can help you in any way, please reach out.

**Comment by smashercosmo** [comment]
@p-goetz I thing I figured out the problem with your code. Try to change your regexes to these
```js 
/^{{< a >}}([\s\S]*?){{< \/a >}}/
```
```js 
/^{{< b >}}([\s\S]*?){{< \/b >}}/
```
and tell me if the error still persists.

**Comment by smashercosmo** [comment]
I think this can also be solved by using lazy quantifiers, but I haven't tried it yet.

**Comment by smashercosmo** [comment]
Oh, I've just noticed that your regexes are actually using lazy quantifiers :) Well, this probably answers the question.

**Comment by p-goetz** [comment]
Thanks for much for this help. The `^` indeed solves this specific problem. I remember having read about it in some related issue here on GitHub. It didn't work for my more complicated use case, though. 
I will now step by step make the example more complicated and check if the wrong behavior reappears. If it won't that means I will have found an error in my initial example, otherwise I will have a new example that doesn't work. Not matter what, I will come back as soon as I have something relevant to add here. This will most probably be the day after tomorrow! 
Thanks again for your support!

**Comment by smashercosmo** [comment]
Well, I tested your custom components with changed regexes and it solved the issue for me

**Comment by smashercosmo** [comment]
I guess this particular issue can be closed now
