### ISSUE TITLE
Relation widget should support min and max attributes if multiple is true

### ISSUE THREAD

**Issue by greatislander** [netlify/netlify-cms#5026]
**Is your feature request related to a problem? Please describe.**

The [relation widget](https://www.netlifycms.org/docs/widgets/#relation) supports selecting multiple items when the `multiple` attribute is true. Other fields that support multiple items, such as [list](https://www.netlifycms.org/docs/widgets/#list) and [select](https://www.netlifycms.org/docs/widgets/#select), allow item length to be constrained by `min` and `max` attributes which are ignored if `multiple` is false (in the case of the select widget):

- `multiple`: accepts a boolean; defaults to `false`
- `min`: minimum number of items; ignored if **multiple** is `false`
- `max`: maximum number of items; ignored if **multiple** is `false`

**Describe the solution you'd like**

Adding `min` and `max` attributes to the relation widget would bring its behaviour in line with the multiple select widget and provide helpful constraints for relationships in the CMS.

**Describe alternatives you've considered**

Not applicable.

**Additional context**

Not applicable.

**Comment by Pratik1234agarwal** [comment]
I wanted to take on this issue. Can someone guide my how can I start looking into this.
