### ISSUE TITLE
Record Netlify identity information in commits when using git backend.

### ISSUE THREAD

**Issue by belmarca** [netlify/netlify-cms#5031]
**Is your feature request related to a problem? Please describe.**
I woud like to have netlify-identity user information in git commit messages. Current PRs and merges only contain the repo owner's information.

**Describe the solution you'd like**
Simply appending the logged-in user's username or email to the commit message would be fine.

"Changes made by $FOO" works too.

**Describe alternatives you've considered**
I tried building my own package but it's not worth keeping it updated for one client. I'd rather be allowed to customize this in a script tag on my admin page, after loading the CMS from a CDN.

**Comment by tomrutgers** [comment]
Does this cover your needs? https://www.netlifycms.org/docs/beta-features/#commit-message-templates

**Comment by belmarca** [comment]
@tomrutgers I have just tested and that does it.

It's been hard to find this information. The beta features page did not appear in my search results. Maybe I should have checkd just in case, but it didn't occur to me.

Thanks

**Comment by tomrutgers** [comment]
The docs definitely need some work, glad it's working 👍

**Comment by erezrokah** [comment]
Thanks for providing the information @tomrutgers!

Also, we do set the commit author based on Identity information when using `git-gateway`:
https://github.com/netlify/netlify-cms/blob/36608f8d7560649f3a6475da2603b206d1db6b55/packages/netlify-cms-backend-git-gateway/src/GitHubAPI.ts#L105

However, that only works if the Identity information matches an actual GitHub account.
