### ISSUE TITLE
Unable to extend editor toolbar buttons (like "h3", "blockquote",...)

### ISSUE THREAD

**Issue by bert-bruggeman** [netlify/netlify-cms#504]
I can't find a way to extend the editor toolbar buttons...

**Comment by erquhart** [comment]
The buttons on the toolbar can't be added to, but you can add shortcode plugins that are accessed through the `+` icon. Here's the [documentation](https://www.netlifycms.org/docs/extending/#registereditorcomponent) for adding shortcode plugins to the editor, and here's an [example](https://github.com/netlify/netlify-cms/blob/6af9a3155c794cec697bc0722907c738200e292b/example/index.html#L168) where we implement a plugin for adding YouTube video shortcodes in Hugo syntax in a way that can be previewed through the CMS.

**Comment by bert-bruggeman** [comment]
I do think this is still an issue, H3, h4, blockquote, ul, ol,... should be default buttons on the editor...

**Comment by erquhart** [comment]
@bert-bruggeman agreed! This makes sense as a feature request.

We do have a few more buttons coming in #254, check it out in the deploy preview: https://deploy-preview-254--cms-demo.netlify.com/#/collections/posts/entries/new

**Comment by tortilaman** [comment]
@bert-bruggeman I'll be working on adding all the buttons you mentioned in addition to a couple others in a new PR in the coming days.

**Comment by erquhart** [comment]
I should also clarify - I'm viewing this as a feature request to allow the toolbar to be configured. I don't think headers higher than h2 should be in the toolbar by default, but it should be possible to add them by config.

**Comment by bert-bruggeman** [comment]
Nice! Looking forward to the next version!

**Comment by erquhart** [comment]
This was mostly addressed in #1236. The remaining issue of header levels 3 - 6 is covered specifically in #1851.

**Comment by bublick** [comment]
Shortcodes definitely are cool, but is extend of the editor toolbar still blocked?
I just need some formatting like "underline". Shortcodes are my single solution.
