### ISSUE TITLE
List widget default value

### ISSUE THREAD

**Issue by damienvdw** [netlify/netlify-cms#505]
This isn't so much a bug as it is a question : 

Is it possible to assign a `default` value to a `list` widget ?
If it is, what is the correct way to use it with a single or multiple values ?

The documentation is light on examples and I could not figure it out reading the source code...

Thanks a lot !

**Comment by erquhart** [comment]
This should work but doesn't, I'd consider it a bug. Default values in list fields should be set by adding a "default" property to the individual fields in the list.

**Comment by damienvdw** [comment]
So the right syntax would be something like that ?

`- {label: "listTest", name: "listTest", widget: "list", default: "['term_1', 'term_2']"}`

**Comment by erquhart** [comment]
List widgets contain other fields, not multiple strings - here's an [example](https://github.com/netlify/netlify-cms/blob/b294110db7f7a28279f5737a3f3b17052829da72/example/config.yml#L102) from the docs.

Your best option currently if you need an array of strings is to create a custom widget. I believe the default value syntax you're using would work, except the array should not be wrapped in a string.

**Comment by damienvdw** [comment]
You were right, I removed the doubles quotes around the array and it worked.

For reference : 

`- {label: "listTest", name: "listTest", widget: "list", default: ['term_1', 'term_2']}`

Apparently, if not setup to contains other fields, the list widget can contain multiples strings !

There is no preview though. But this is perfect for Hexo's categories and tags !

It's a nice default, please don't change it 😃

**Comment by erquhart** [comment]
Man, I could have sworn that more than one issue/Gitter convo has taken place about this specifically not working. It's definitely a great default, glad you got it figured! We need to update the docs with this info for sure.
