### ISSUE TITLE
Cannot upload images with `onAddAsset`

### ISSUE THREAD

**Issue by banyudu** [netlify/netlify-cms#5082]
**Describe the bug**

I'm developing a custom widget, which accepts html code (from third party rich editor) and store remote images( img.src and background-image ) to mediaPath.

`onAddAsset` seems like the props I needed, but it doesn't work as expected.

![image](https://user-images.githubusercontent.com/2416493/110456619-be731f00-8104-11eb-9050-66c97b84c29c.png)

**To Reproduce**

```javascript
const { onAddAsset, config, entry } = this.props
let res
try {
  res = await axios.get(url, {
    responseType: 'blob'
  })
} catch (error) {
  console.error(error)
  return
}
const mimeType = res.headers['content-type']
const ext = extName.mime(mimeType)?.[0]?.ext || 'raw'
const public_folder = config.get('public_folder') // => /assets
const localFilename = Base64.encodeURI(url) + `.${ext}`
const imageFile = new File([new Blob([res.data])], localFilename, { type: mimeType })
const mediaFile = createAssetProxy({file: imageFile, path: localFilename })
mediaFile.draft = true
onAddAsset(mediaFile)
```

According to `actions/entry.ts` in `netlify-cms-core`:
```typescript
export function getMediaAssets({ entry }: { entry: EntryMap }) {
  const filesArray = entry.get('mediaFiles').toArray();
  const assets = filesArray
    .filter(file => file.get('draft'))
    .map(file =>
      createAssetProxy({ path: file.get('path'), file: file.get('file'), url: file.get('url') }),
    );

  return assets;
}
```
assets should be append to entry.mediaFiles to persist to git server.

While `onAddAsset` only modifies `store.medias`:
```typescript
case ADD_ASSETS: {
  const assets = action.payload;
  assets.forEach(asset => {
    state[asset.path] = { asset, isLoading: false, error: null };
  });
  break;
}
```

So I doubt whether `onAddAsset` is the props I need.

I have tried `entry.update('mediaFiles')`, but it's immutable.

If `onAddAsset` isn't the thing I need, could you provide another solution?

Currently I transform images to base64 to bypass this problem, but it's definitely not a good option.

Thanks very much!

**Expected behavior**

Append file to `entry.mediaFiles so it can be persisted.`

**Applicable Versions:**

 - Netlify CMS version: [2.10.96]
 - Git provider: [Gitlab]
 - OS: [e.g. macOS Big Sur]
 - Browser version [chrome 88]

**Comment by erezrokah** [comment]
Hi @banyudu, can you describe in 1 sentence the problem you're trying to solve?
Is it - "I would like to add images to a draft entry without going through the media library?"

I don't believe there's an **_official_** way to do it yet.

I would be nice to open that capability to widgets if you'd like to put a contribution up.

**Comment by banyudu** [comment]
> Is it - "I would like to add images to a draft entry without going through the media library?"

Yes!

>I would be nice to open that capability to widgets if you'd like to put a contribution up.

I'd like to have a try.

Is it ok to add a new props to EditorControl, which dispatches `mediaLibrary`.`persistMedia` action ?

**Comment by erezrokah** [comment]
> Is it ok to add a new props to EditorControl, which dispatches `mediaLibrary`.`persistMedia` action ?

I'll have to see some code to understand this better
