### ISSUE TITLE
On creating a new entry, slug ignores changes in field "date"

### ISSUE THREAD

**Issue by aperep** [netlify/netlify-cms#509]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
New entry slug ignores "date" field of the post, puts current date instead.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Take your Hugo-generated site on Github, connect NetlifyCMS as in docs, by adding index.html and config.yml exactly as in https://www.netlifycms.org/docs/quick-start/ to the folder ./static/admin/
In particular, there is a collection named "blog" with a slug field "{{year}}-{{month}}-{{day}}-{{slug}}"
Then create a new blog post at yoursite.com/admin, change field labeled "Publish date" (which has name "date") to any other date, put random data to other fields, and save a new entry.
Then the new file name starts with a current date.

**- What is the expected behavior?**
The new file name should start with the provided date.

**- Please mention your node.js, and operating system version.**
Hugo v0.22.1 on Ubuntu 16.04 in WSL of Windows 10. node.js not installed.

**Comment by erquhart** [comment]
This isn't actually a bug - the slug template _is_ referring to the current date. The "Publish Date" field isn't related to the slug at all.

That said, the ability to control slugs is definitely a priority, https://github.com/netlify/netlify-cms/issues/445 is the issue to watch.
