### ISSUE TITLE
For CMS.registerWidget method the control and preview component Typescript props are untyped

### ISSUE THREAD

**Issue by eliasm307** [netlify/netlify-cms#5143]
**Describe the bug**

From the Typescript declarations [here](https://github.com/netlify/netlify-cms/blob/6623740a8c59004684b441d47503d1870a9881ef/packages/netlify-cms-core/index.d.ts#L536) the CMS.registerWidget method has arguments for control and preview components which have props that are typed as any. This means when working in Typescript and creating the control and preview components there is no existing type to use for the props of these components and either:
- users need to use any for the props, which means typescript complains with messages e.g. `Unsafe call of an any typed value` when trying the onChange function provided in the props, 
- users need to create custom types for the props. 

However the props for these components are defined on the Netlify CMS website [here](https://www.netlifycms.org/docs/custom-widgets/), so they just need to be added to the type declarations and applied.

**To Reproduce**
Try to create a control or preview component in Typescript.

**Expected behavior**
Types should be defined such that when using Typescript to create the control or preview components the appropriate type can be assigned and then intellisense and other Typescript features work as expected with no messages.

**Screenshots**
Warning when trying to use onChange function from any type props: 
![image](https://user-images.githubusercontent.com/13420359/111919928-2b32d580-8a84-11eb-99ce-6837ea834259.png)

Components with any type props defined [here](https://github.com/netlify/netlify-cms/blob/6623740a8c59004684b441d47503d1870a9881ef/packages/netlify-cms-core/index.d.ts#L536):
![image](https://user-images.githubusercontent.com/13420359/111923341-95547600-8a96-11eb-8876-d42e8f0b03af.png)

**Applicable Versions:**

 - netlify-cms-app 2.14.14
 - netlify-cms-core 2.36.13

**Comment by DavidAmmeraal** [comment]
I would like to pick this up. I'm also noticing the ```schema``` argument isn't typed?
 
<img width="867" alt="Screenshot 2021-03-24 at 22 24 44" src="https://user-images.githubusercontent.com/1423154/112389758-8dded800-8cf5-11eb-84f3-242dc6745dc7.png">

**Comment by eliasm307** [comment]
@DavidAmmeraal that looks good! However, I have a few queries:

- Shouldnt these control and preview component props be applied to the alternative CmsWidgetParam prop object for the registerWidget method also, ie [here](https://github.com/DavidAmmeraal/netlify-cms/blob/8c70c6f759d6bd18f8d7bec2163b909d0c390d2f/packages/netlify-cms-core/index.d.ts#L444)
- Also, would it be worth adding JsDoc comments of what the different values represent? I think this would make the dev experience a bit more friendly and easier to understand if the props have descriptive context. For the custom props I had made for my project, I did this based on the descriptions on the Netlify CMS website, see below. @erezrokah what are your thoughts on adding JsDoc comments, at least for typescript declarations? I don't think I have seen these yet in this repo and I'm not sure if that's on purpose?
![image](https://user-images.githubusercontent.com/13420359/112395390-2c6b3900-8cf6-11eb-8d5a-fdac95abdf83.png)

**Comment by DavidAmmeraal** [comment]
I also noticed [CmsWidget](https://github.com/DavidAmmeraal/netlify-cms/blob/8c70c6f759d6bd18f8d7bec2163b909d0c390d2f/packages/netlify-cms-core/index.d.ts#L468) has similar properties, I've updated them as well. 

In regards to your second point @eliasm307, yeah I agree some extra documentation wouldn't hurt.
