### ISSUE TITLE
registerEditorComponent: Weird scrolling issue happening with components that are taller than markdown field

### ISSUE THREAD

**Issue by heathervv** [netlify/netlify-cms#516]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
When a block level component is open, I'm unable to scroll the entire length of it (scroll jumps). You can view a video of the issue here: http://bokeh-staging.netlify.com/img/example.mp4

**- If the current behavior is a bug, please provide the steps to reproduce.**
- Using `registerEditorComponent`, create a component that is quite a bit taller than the markdown field
- Open that component in the admin
- Witness bug when scrolling

**- What is the expected behavior?**
You should be able to scroll and view the entire component.

**- Please mention your node.js, and operating system version.**
OS X 10.12.4 & node.js v6.10.3

**Comment by tortilaman** [comment]
Without really diving in, this seems like it could be related to #436.

**Comment by heathervv** [comment]
@tortilaman Possibly! I'm not quite sure it's the exact same thing though.

Was digging around into this, and it has to do with the `stickyAtBottom` status in `/src/components/UI/Sticky/Sticky.js` for the toolbar. I'm noticing that the moment the scrolling is jumping, that state is being triggered and then is immediately "un-triggering". 

What are the options for disabling this behaviour when a component block is open?

**Comment by tortilaman** [comment]
There isn't really an "option" currently to disable such behaviour. I think with some styling and a bit of javascript though a solution could be found. If you're interested, this could be a good opportunity for a contribution and pull request.

**Comment by erquhart** [comment]
Update: in 1.0, we're dropping the entire form into the editor as a block, which will solve this issue. It also means you'll be able to edit this stuff after the fact instead of deleting and recreating!

@heathervv we'd love for you to test out your use case in our upcoming 1.0 release candidate, stay tuned for that :)

**Comment by erquhart** [comment]
Final update: Fixed in 1.0!! 🎉
