### ISSUE TITLE
relative pathes doesn't work as expected in previewPane

### ISSUE THREAD

**Issue by banyudu** [netlify/netlify-cms#5185]
**Describe the bug**

Relative pathes inside preview pane has a base of `myhostname/admin/`, instead of `myhostname`.

**To Reproduce**

Set a file field's value to relative path, such as 'download/my-attachment.pdf', and the link points to `/admin/download/my-attachment.pdf` in preview pane, which is not correct.

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [2.10.102]

**CMS configuration**

**Additional context**

**Comment by banyudu** [comment]
```javascript
const initialContent = `
<!DOCTYPE html>
<html>
  <head><base target="_blank"/></head>
  <body><div></div></body>
</html>
`;
```
should be 

```javascript
const initialContent = `
<!DOCTYPE html>
<html>
  <head><base target="_blank" href="/" /></head>
  <body><div></div></body>
</html>
`;
```

in https://github.com/netlify/netlify-cms/blob/d614d4bd569fc65c3f520139ce33994afd311ca8/packages/netlify-cms-core/src/components/Editor/EditorPreviewPane/EditorPreviewPane.js#L217-L223

**Comment by erezrokah** [comment]
Hi @banyudu, I was unable to reproduce this issue with the file widget.
How are you setting the path to a relative one? Manually in the markdown (e.g. not using the CMS)?

Also I believe the fix in https://github.com/netlify/netlify-cms/pull/5186 only works if the files are deployed under the root path.

It won't work if the files are deployed under a sub path (e.g. `https://www.domain.com/site1`).

Ideally we should use `public_folder` from the config as the base, but that's tricky since you can configure that per collection and per field.

**Comment by banyudu** [comment]
This issue occurs to me when I migrate an old system to netlify-cms. 

In my case, the `download` directory was not my `media_folder`, so the files in it didn't get resolved. `download/my-attachment.pdf` 

```bash
- app
  - img
    - a.png
  - download
    - b.pdf 
```

I prefer using `app/img` as my public_folder, while don't want to move files from `app/download` to `app/img`, so links like `download/my-attachment.pdf` won't be resolved as a local blob.

My config.yml file is: 
```yaml
media_folder: "app/img"
public_folder: "/img
```

**Comment by banyudu** [comment]
> Also I believe the fix in #5186 only works if the files are deployed under the root path.

You are right, do you have any suggestions?

**Comment by erezrokah** [comment]
> I prefer using `app/img` as my media_folder, while don't want to move files from `app/download` to `app/img`, so links like `download/my-attachment.pdf` won't be resolved as a local blob.

How would that work when you add new files? Won't they'll be added to `app/img`?

FYI, You can set a `media_folder` and `public_folder` at the file field level to `app/download` and `/download`.
Also you could run a script to migrate the old content to the expected CMS format.

**Comment by banyudu** [comment]
OK, it makes sense. Thanks!
