### ISSUE TITLE
Using NetlifyCMS with Next.js or Nuxt.js? 

### ISSUE THREAD

**Issue by abattenburg** [netlify/netlify-cms#519]
While not exactly static site generators, both Next.js and Nuxt.js have the option to export as a static site. Is it possible to integrate NetlifyCMS with these tools? 

I've tried to implement NetlifyCMS with Nuxt.js by following the quick start, but keep getting an error about not being able to find a 'media_folder' when navigating to the 'admin' page. As Nuxt.js has a "static" folder for assets, I think pointing to **_media_folder: "static/images/"_** in the **config.yml** should work, but can't get past the error. Is implementing NetlifyCMS with an exported static site possible, or am I misunderstanding the project a little bit?

**Comment by Benaiah** [comment]
Netlify CMS is intended to work with your _source_ files, not the product of a build. It talks to GitHub's API to edit content, but doesn't have any other involvement with how you build, host, or deploy the project. It just provides an interface for editing the content, it doesn't actually turn the content into a completed site. That's where a static site generator would fit in (though the CMS doesn't actually require you to use a static site generator, that's what it's intended to work with).

The only requirement to use the CMS is to host the content in a format that the CMS understands, which is currently either structured data such as JSON or YAML or Markdown with front-matter. If your content is in that format, and on GitHub, the CMS can work with your project.

Looking at Next.js and Nuxt.js, they seem to be focusing on rendering React or Vue-based UIs to a static form. The CMS won't understand any of your React code, but if you're pulling the actual content from source files as JSON/YAML/Markdown it will be able to edit _those_ files.

**Comment by tech4him1** [comment]
@abattenburg Are you still having issues getting this working? If you have an example project I can take a look.

**Comment by abattenburg** [comment]
Thanks for the clarifying what the CMS accepts @Benaiah. I knew that the CMS obviously wouldn't read my React/Vue code directly, but I wasn't sure if there was a limitation to what the CMS could be built with. My plan is to use Markdown with Nuxt.js, but I first wanted to make sure I could setup the CMS to integrate in general. Still trying to get past the 'Media_folder' error before introducing any content. 

Thank you for offering to take a look @tech4him1! My very simple repo is at https://github.com/abattenburg/netlify-vue-boilerplate. I've currently removed the "Collections" part of the config.yml entirely trying to see if I can get past the 'media_folder' error, and move onto the next error. I've placed the 'admin' folder under the "static" folder at the root of the project. I'm thinking that the "media_folder" error may just be a blanket error for an incorrect config.yml, so I'll mess with setting up the 'collections' section again to see if that fixes the error.

**Comment by tech4him1** [comment]
@abattenburg Only the actual repo information should be nested under `backend`. Try this:
```yaml
backend:
  name: github
  repo: abattenburg/netlify-vue-boilerplate
  branch: master # Branch to update

publish_mode: editorial_workflow
media_folder: "static/images/"
```

**Comment by abattenburg** [comment]
Wow. Thank you so much. Not sure how I didn't notice that I made that huge formatting error. Thank you so much again and glad to know it can integrate!

**Comment by tech4him1** [comment]
@abattenburg Great, I'm glad it works! I've never heard of Nuxt/Next before, so thanks for bringing then up!
