### ISSUE TITLE
yoga-layout-prebuilt error on gatsby build while deploying on netlify 

### ISSUE THREAD

**Issue by jaymehta20** [netlify/netlify-cms#5228]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.14.40`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36`

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"
media_folder: static/img
public_folder: /img
collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: blog-post
      - label: Title
        name: title
        widget: string
      - label: Slug
        name: slug
        widget: string
        required: true
        pattern:
          - ^[a-z0-9]+(?:-[a-z0-9]+)*$
          - A slug can have no spaces or special characters
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: text
      - label: Thumbnail
        name: thumbnail
        widget: image
      - label: Body
        name: body
        widget: markdown
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - date
      - commit_author
      - description
    view_filters: []
    view_groups: []
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
isFetching: false
error: null

```
https://github.com/jaymehta20/gatsby-netlify-cms
**Additional context**

**Comment by tomrutgers** [comment]
https://github.com/gatsbyjs/gatsby/issues/1499#issuecomment-327104956

This seems to be a common thing. Do you have any unused content in your directories?

**Comment by jaymehta20** [comment]
I can't confirm now cause I have made a lot of changes and it's giving me some error. Could you pls take a look into it. I updated my gatsby version to 3 and now I can't downgrade it and it's all a mess now I can't fix it. You can take a look at the code here: https://github.com/jaymehta20/gatsby-netlify-cms

**Comment by jaymehta20** [comment]
The template the @erezrokah gave me is gatsby v2 and I was using gatsby-image-plugin which requires v3 so I tried to upgrade it but it messed up something and unfortunately, I can't downgrade it and go back to how it was.

**Comment by erezrokah** [comment]
Hi @jaymehta20, can you update the issue with the missing information:
![image](https://user-images.githubusercontent.com/26760571/114064613-7cbfca80-98a2-11eb-91de-af7cb10fc3b2.png)

From the current description and comments it's hard to know what is the current issue you're experiencing.

> I can't downgrade it and go back to how it was.

Also, it would be helpful if you share the commit hash that started messing things up.

**Comment by jaymehta20** [comment]
Bug: Can't run my dev server cause I tried to update gatsby to V3 but it didn't work out and I tried to downgrade but started causing some issue so now I can't basically run my website
The reason why I upgrade gatsby cause gatsby-plugin-image needs V3 gatsby and the Kaldi template has gatsby V2
Now I can't basically revert back to how it was. This is the reason that I was not able to see childImageSharp property on my image uploaded on netlify cms cause my gatsby-plugin-image is not working due to this

**Comment by jaymehta20** [comment]
Also when I tried to deploy on netlify it gave me this error

![image](https://ibb.co/6FJjmB1)

**Comment by jaymehta20** [comment]
![image](https://user-images.githubusercontent.com/23277339/114128704-91d84000-991a-11eb-92d7-7ef0ec1db6a2.png)

**Comment by jaymehta20** [comment]
I can run local dev server of Gatsby but when i deploy i get that yoga layout error and now i can't use netlify cms because of that

**Comment by jaymehta20** [comment]
For a beginner like me, this feels super complex and hard to debug cause I update one thing, and the whole site breaks.

**Comment by jaymehta20** [comment]
and I revert back, some other stuff breaks

**Comment by jaymehta20** [comment]
Ok, I fixed the issue by updating my dependencies.

`- npm outdated`
`- npm install some-package@latest`
`- gatsby clean`
`- gatsby develop`
