### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by tech4him1** [netlify/netlify-cms#524]
Currently, many of the CMS' dependencies (`dev` and normal) have updates available (use `yarn outdated`). We should probably go through them and determine which should be updated, and which should not. This issue will track progress.

Related to #542, #589.

Separate Issues: #478, #413, #664.

**Comment by tech4him1** [comment]
The CMS' `node-sass` version does not support Node v8.
`autoprefixer` should be updated to add/remove browser prefixes.

**Comment by tech4him1** [comment]
Also `yarn` has some perr-dependency errors from https://github.com/yarnpkg/yarn/issues/2688 and https://github.com/yarnpkg/yarn/issues/2387 that we don't need to worry about too much.

**Comment by tech4him1** [comment]
React depreciations: `prop-types` and `react-create-class` will need to be installed as separate packages.

**Comment by tech4him1** [comment]
Yarn warning's (w/`react-toolbox@2.0.0-beta`):
```
warning "react-frame-component@1.1.1" has incorrect peer dependency "prop-types@^15.5.9".
warning "react-sidebar@2.3.2" has incorrect peer dependency "prop-types@>=15.5.0".
warning "react-dnd-html5-backend@2.4.1" has incorrect peer dependency "react-dnd@^2.4.0".
warning "react-toolbox@2.0.0-beta.12" has incorrect peer dependency "prop-types@^15.5.7".
warning "react-toolbox@2.0.0-beta.12" has incorrect peer dependency "react-transition-group@^1.1.3".
warning "ajv-keywords@1.5.1" has incorrect peer dependency "ajv@>=4.10.0".
warning "eslint-config-airbnb@12.0.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@^2.2.2".
warning "eslint-config-airbnb@12.0.0" has incorrect peer dependency "eslint-plugin-import@^1.16.0".
warning "eslint-config-airbnb@12.0.0" has incorrect peer dependency "eslint-plugin-react@^6.3.0".
warning "eslint-import-resolver-webpack@0.6.0" has incorrect peer dependency "eslint-plugin-import@>=1.4.0".
warning "eslint-config-airbnb-base@8.0.0" has incorrect peer dependency "eslint-plugin-import@^1.16.0".
warning "eslint-import-resolver-webpack@0.8.3" has incorrect peer dependency "eslint-plugin-import@>=1.4.0".
warning "postcss-cssnext@2.11.0" has incorrect peer dependency "caniuse-db@^1.0.30000652".
```

**Comment by tech4him1** [comment]
@erquhart So for dependency updates, I'm thinking of going through two stages:

1. Upgrade packages that are currently giving depreciation warnings or are no longer supported, ad get those out of the way.
2. Figure out if we want to upgrade any major versions that are still working (`react-router`), etc.

What do you think?

**Comment by erquhart** [comment]
@tech4him1 sounds like a plan.

**Comment by tech4him1** [comment]
Packages with minor or patch updates available:

| Package                           | Current | Minor Update  |
| ----------------------------------|---------|---------|
| js-base64                         | 2.1.9   | 2.3.2   |
| react-datetime                    | 2.9.0   | 2.10.1  |
| slate                             | 0.21.4  | 0.21.6  |
| slate-edit-table                  | 0.10.1  | 0.10.2  |

**Comment by tech4him1** [comment]
Dependency updates will be split into three categories:

1. **UI dependencies.** (React, Redux, Notifications) These should be really easy to test -- either the UI is broken or it is not.
2. **Dev dependencies.** (WebPack, Babel) These are fairly easy to test whether they break something or not, we'll just need to watch the transpilers and make sure the output still supports older browsers.
3. **Backend/Internal dependencies.** (`gotrue-js`, `uuid`) These will need fairly intensive testing to make sure that they still work for everybody.

**Comment by tech4him1** [comment]
OK, I think the bulk of this is done. @erquhart @Benaiah are you good with me closing this?

**Comment by erquhart** [comment]
Agreed.
