### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by jaymehta20** [netlify/netlify-cms#5240]
Had a yoga layout error so I just googled and found a solution on GitHub which said to update gatsby-plugin-netlify-cms and gatsby-remark-relative-images to the latest. After doing that I am getting this error.

**Screenshots**

![image](https://user-images.githubusercontent.com/23277339/114302940-0bbe2400-9ae9-11eb-904f-8984493c7ef4.png)

**CMS configuration**
backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          required: true,
          pattern:
            [
              "^[a-z0-9]+(?:-[a-z0-9]+)*$",
              "A slug can have no spaces or special characters",
            ],
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Thumbnail", name: "thumbnail", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }

**Comment by jaymehta20** [comment]
Public repo if you want to take a look further: https://github.com/jaymehta20/gatsby-netlify-cms

**Comment by smashercosmo** [comment]
From looking at the call stack, I would that it's a problem with gatsby-plugin-netlify-cms, and not with netlify-cms. So you better open this issue in Gatsby repo.

**Comment by jaymehta20** [comment]
Ok, I fixed the error:

- rm -rf node_modules
- rm package-lock.json This is important, the fix doesn't work without this
- npm install

Now I'm able to run develop without the error
