### ISSUE TITLE
Decide yourself whether to use - or * for lists in Markdown

### ISSUE THREAD

**Issue by lsolesen** [netlify/netlify-cms#5254]
**Is your feature request related to a problem? Please describe.**

After editing a markdown with the Netlify CMS the marker for the lists are changed from - to * like in this example - https://github.com/motionsplan/motionsplan-dk-jekyll/pull/85/commits/de011ebb79444ae95746ab217477f1bc8716c6d5#diff-c9808a953d6ec002a541961d4a2611d8cce232a4efd31a3104c1cc0d43ccf2d4R143

**Describe the solution you'd like**

It would be nice if the Editor would leave the list marker alone, or you could have a setting with your preferred list marker for the markdown file.

**Describe alternatives you've considered**

**Additional context**

**Comment by erezrokah** [comment]
Closing this as I believe it is covered by https://github.com/netlify/netlify-cms/issues/4601.
Please comment if you feel this is a separate issue
