### ISSUE TITLE
Allow setting default value of a field to that of a field in same collection

### ISSUE THREAD

**Issue by lfracalossiFA** [netlify/netlify-cms#5256]
**Is your feature request related to a problem? Please describe.**
This is similar in nature to #1975, but does not involve UUIDs, so I'd hoped it might be easier to achieve!

Many times when I'm creating a collection, I want to set the default value of a field to the value of a different field. For example, if I had a collection with `title` (for title of an article) and `name` (the short name/slug) fields, I'd like the default value of `title` to be set to the value of `name`. However, currently this is not possible.

**Describe the solution you'd like**

I'd like to be able to reference another field using something like `default: '{{fields.name}}'` or `default: '{{slug}}'`

**Additional context**
Here's an example of the use case I have in mind, where I have appended (see highlighting) what I expected to be possible:

![Screen Shot 2021-04-12 at 5 37 46 PM](https://user-images.githubusercontent.com/72401230/114466025-ec40fd00-9bb5-11eb-894a-7d890749a120.png)

**Comment by erezrokah** [comment]
Hi @lfracalossiFA, I believe you can do that using the CMS `preSave` event:
https://www.netlifycms.org/docs/beta-features/#registering-to-cms-events

You can get the value from the `name` field and set it on the `title` field if the latter doesn't exist.

The thing is that default values are currently applied before the editor is opened and the entry is saved for the first time, so it's the default value for the field.

This suggestion can be classified as a fallback value.

Closing this issue as I think it is covered by the first bullet in #1975:
> 1. Generalise the use of placeholders so that they can be used in places other than in generating the slug field.

**Comment by lfracalossiFA** [comment]
Ooh, I didn't know about the preSave event. Thanks for the info there!
