### ISSUE TITLE
Editor component is not recognized when reloading

### ISSUE THREAD

**Issue by lsolesen** [netlify/netlify-cms#5261]
**Describe the bug**

I have created a custom EditorComponent like this https://github.com/motionsplan/motionsplan-dk-jekyll/blob/master/admin/index.html#L169

```
CMS.registerEditorComponent({
    // Internal id of the component
    id: "figure",
    // Visible label
    label: "Figure",
    // Fields the user need to fill out when adding an instance of the component
    fields: [
      {name: 'image_path', label: 'Image Path', widget: 'string'},
      {name: 'caption', label: 'Caption', widget: 'string'},
      {name: 'alt', label: 'Alt', widget: 'string'}
    ],
    // Pattern to identify a block as being an instance of this component
    pattern: /^\{% include figure image\_path=\"(\S+)\" caption=\"(\S+)\" alt=\"(\S+)\" %\}$/,
    // Function to extract data elements from the regexp match
    fromBlock: function(match) {
      return {
        image_path: match[1],
        caption: match[2],
        alt: match[3]
      };
    },
    // Function to create a text block from an instance of this component
    toBlock: function(obj) {
      return '{% include figure image_path="' + obj.image_path + '" caption="' + obj.caption + '" alt="' + obj.alt + '" %}';
    },
    // Preview output for this component. Can either be a string or a React component
    // (component gives better render performance)
    toPreview: function(obj) {
      return (
        '<figure><img src="' + obj.image_path + '" alt="' + obj.alt + '"><caption>' + obj.caption + '</caption></figure>'
      );
    }
  });
```

I have doublechecked the pattern with https://regex101.com/

![Screenshot - 2021-04-13T080917 295](https://user-images.githubusercontent.com/148026/114504696-901abf00-9c2f-11eb-8ecb-cc528255aa57.png)

I can properly put the code into the page, but when coming back and forth from the Markdown and Rich Text it is not rendered as a component.

![Screenshot - 2021-04-13T081303 317](https://user-images.githubusercontent.com/148026/114505136-38308800-9c30-11eb-9b1b-cc7855819395.png)

![Screenshot - 2021-04-13T081337 357](https://user-images.githubusercontent.com/148026/114505152-3d8dd280-9c30-11eb-98e0-1929ee3ecb75.png)

![Screenshot - 2021-04-13T081356 755](https://user-images.githubusercontent.com/148026/114505159-3ff02c80-9c30-11eb-8623-f41cd5a033b6.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by arpadgabor** [comment]
You are are using the `any non-whitespace character` matcher `\S` but your alt and caption can contain whitespace characters. Try this:

```js
const regex = /^\{% include figure image\_path=\"(\S*)\" caption=\"(.*)\" alt=\"(.*)\" %\}$/

regex.test('{% include figure image_path="assdd" caption="my cool caption" alt="my cool alt" %}')
// true
```

**Comment by lsolesen** [comment]
@arpadgabor  You were completely right. Your regex worked.
