### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by pranaliImagin** [netlify/netlify-cms#5275]
**I'm getting issue only with the Github preview**

**Screenshots**
![image](https://user-images.githubusercontent.com/80769307/114743335-34a11c00-9d6a-11eb-8dbc-3a71cee31c88.png)

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.14.40`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36`

**CMS configuration**
```
backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"
media_folder: static/img
public_folder: /img
logo_url: ../img/MT-Logo.png
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: _
collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: blog-post
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: text
      - label: Featured Post
        name: featuredpost
        widget: boolean
      - label: Featured Image
        name: featuredimage
        widget: image
      - label: Body
        name: body
        widget: markdown
      - label: Tags
        name: tags
        widget: list
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - date
      - commit_author
      - description
    view_filters: []
    view_groups: []
  - name: settings
    label: Settings
    editor:
      preview: false
    files:
      - label: General
        name: general
        file: src/data/general.json
        fields:
          - label: Marketing Email
            name: marketingEmailID
            widget: string
      - label: Navigation Menu
        name: nav
        file: src/data/nav.json
        fields:
          - label: Nav Items
            label_singular: Nav Item
            name: topLevelItems
            widget: list
            fields:
              - label: Display Text
                name: displayText
                widget: string
              - label: URL
                name: url
                widget: string
              - label: Item Type
                name: itemType
                widget: select
                options:
                  - Link
                  - Button
      - label: Footer
        name: footer
        file: src/data/footer.json
        fields:
          - label: Subscription Section
            name: subscriptionSection
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Text Content
                name: content
                widget: text
          - label: Social Media
            name: socialLinks
            widget: list
            fields:
              - label: platform
                name: platform
                widget: string
              - label: link
                name: link
                widget: string
              - label: icon
                name: icon
                widget: image
          - label: Footer Base text
            name: footerBase
            widget: string
    publish: true
    type: file_based_collection
    sortable_fields:
      - commit_date
      - commit_author
    view_filters: []
    view_groups: []
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Home Page
        name: index
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: index-page
          - label: Title
            name: title
            widget: string
          - label: Heading
 
...

**Comment by pranaliImagin** [comment]
I just Debug the code and found that , issue is somewhere with the lines of code below

`{(testimonialSection.testimonials.length < 1) ? "" : 
          <Carousel 
            responsive={responsive}
            infinite={true}
            autoPlaySpeed={1000}
          >
            {testimonialSection && testimonialSection.testimonials.map((data, index) => {
              return (   
                <div className="t-content-wrap">
                  <h4 className="title">{data.tesTitle}</h4>
                  <p className="content">{data.tesContent}</p>

                  <div className="client-bio">
                    <div className="client-pic-wrap">
                      <img 
                        src={data.clientPic.publicURL}
                        className="client-pic"
                        alt={`${data.clientName} picture      `}
                      />
                    </div>
                    <div className="client-details">
                      <h5 className="client-name">{data.clientName}</h5>
                      <p className="client-location">{data.clientLoc}</p>
                    </div>
                  </div>
                </div>
              )
            })}
          </Carousel> 
        }`

**Comment by erezrokah** [comment]
Hi @pranaliImagin, looks like you need `Array.isArray(testimonialSection.testimonials) && testimonialSection.testimonials.length < 1`

**Comment by pranaliImagin** [comment]
@erezrokah Thanks for your help, I'll try this out right away and get back to you with the output

**Comment by pranaliImagin** [comment]
@erezrokah Now I'm getting this error
TypeError: Cannot read property 'testimonials' of undefined

I have added the check then why is still giving error

**Comment by erezrokah** [comment]
I'm not sure. Maybe check that `testimonialSection` is defined before accessing `testimonialSection. testimonials`?

**Comment by pranaliImagin** [comment]
[carousal-loop.txt](https://github.com/netlify/netlify-cms/files/6312573/carousal-loop.txt)
Check this I have added every condition possible but now its giving the length undefined error

**Comment by erezrokah** [comment]
Hi @pranaliImagin, case you inline the code per my previous comment? For example:

```
Put your code here 
```

instead of attaching a file.

That makes it much easier to debug the issue and also keeps all the information in the issue.

**Comment by pranaliImagin** [comment]
`{/* Testimonial Section */}
    <section className="testimonial-section">
      <div className="testimonial-wrap">
        <img
          src={quote}
          alt="quote icon"
          className="icon quote-icon"
        />
        <h2 className="section-title purple-grad-title">{testimonialSection && testimonialSection.sectionTitle}</h2>
        
        {(testimonialSection && testimonialSection.testimonials && Array.isArray(testimonialSection.testimonials) && testimonialSection.testimonials.length < 1) ? "" : 
          <Carousel 
            responsive={responsive}
            infinite={true}
            autoPlaySpeed={1000}
          >
            {testimonialSection && testimonialSection.testimonials && Array.isArray(testimonialSection.testimonials) && (testimonialSection.testimonials.length > 0) && testimonialSection.testimonials.map((data, index) => {
              return (   
                <div className="t-content-wrap">
                  <h4 className="title">{data.tesTitle}</h4>
                  <p className="content">{data.tesContent}</p>

                  <div className="client-bio">
                    <div className="client-pic-wrap">
                      <img 
                        src={data.clientPic.publicURL}
                        className="client-pic"
                        alt={`${data.clientName} picture      `}
                      />
                    </div>
                    <div className="client-details">
                      <h5 className="client-name">{data.clientName}</h5>
                      <p className="client-location">{data.clientLoc}</p>
                    </div>
                  </div>
                </div>
              )
            })}
          </Carousel> 
        }
        
      </div>
    </section>`

**Comment by pranaliImagin** [comment]
@erezrokah I have added my code above^^

**Comment by erezrokah** [comment]
Hi @pranaliImagin I don't see an issue with the code you share, so either you have an issue with another area of your code or you haven't deployed you changes.

I recommend adding a reproduction scenario per our issue template https://github.com/netlify/netlify-cms/issues/new?assignees=&labels=type%3A+bug&template=bug_report.md&title=Please+replace+with+a+clear+and+descriptive+title

**Comment by erezrokah** [comment]
Closing as stale
