### ISSUE TITLE
Add notes for drafts

### ISSUE THREAD

**Issue by phae** [netlify/netlify-cms#53]
User needs: 
- to be able to discuss issues, changes and ideas for a draft with others
- to see any feedback received from others 
#52 is a pre-requisite for this ticket.

Acceptance criteria:
- [ ] User can type in a comment box and hit "send" to add a comment to the notes panel

**Comment by erquhart** [comment]
Proposing we roll this into #52.

**Comment by erquhart** [comment]
Just realizing this is an additional use case that simply uses the space created by a Notes pane, keeping it separate and subsequent makes sense.

**Comment by rdebeasi** [comment]
Related: https://github.com/netlify/netlify-cms/issues/1850

**Comment by erquhart** [comment]
Going back to my comment from like two years ago - this is going to be rolled together with #52.
