### ISSUE TITLE
Add ability to turn off auto-scroll in editor

### ISSUE THREAD

**Issue by verythorough** [netlify/netlify-cms#532]
**- Do you want to request a *feature* or report a *bug*?**
a *feature* that would help mitigate a *bug* (#436)

**- What is the current behavior?**
Auto-scrolling can be frustrating, as described in #436.

**- What is the desired behavior?**
Improving auto-scroll would be awesome, but it's a big job. Adding a button to the UI to disable it would be a nice stopgap, and possibly useful going forward as well.

**Comment by erquhart** [comment]
I'm envisioning this going together with the "hide preview" button (which itself needs design improvement and better placement).
