### ISSUE TITLE
Add "All Contributors" listing to repo & docs

### ISSUE THREAD

**Issue by verythorough** [netlify/netlify-cms#533]
Following the model of Kent C. Dodd's https://github.com/kentcdodds/all-contributors, I'd like to recognize contributions to Netlify CMS, in all of their various forms.

Implementation details are in the link above, and mostly involve markdown changes to the README, along with research to gather all of the contributors to include initially.

**Comment by DirtyF** [comment]
@verythorough Working on a PR, I went with defaults options, is it OK?

![all-contributors](https://user-images.githubusercontent.com/103008/30389342-daf9a3f8-98b2-11e7-90a8-c15df7db8684.png)

**Comment by verythorough** [comment]
I think that's awesome for getting us started. Thanks so much!

**Comment by tech4him1** [comment]
How does the auto-commit work?

**Comment by DirtyF** [comment]
@tech4him1 I removed it for now, cause I had to add manually each contributor and it was generating a commit for each.
