### ISSUE TITLE
Cannot delete test post(s) in example seed data

### ISSUE THREAD

**Issue by niculistana** [netlify/netlify-cms#537]
**- Do you want to request a *feature* or report a *bug*?**
Bug
**- What is the current behavior?**
Cannot delete post from test example.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Create new post under `posts/entries/new`.
2. Write a post with a title and a body (title and body are both required here and does not alert the user that the fields are empty)
3. Hit save.
4. Once loaded, hit delete.

**- What is the expected behavior?**
The post should be deleted. @erquhart Mentioned that the posts are stored in-memory, so this should clear the entry in-memory and re-render the deleted post.
**- Please mention your node.js, and operating system version.**
This build has been deployed to netlify. I am not sure what Node version/OS they use to host the app.

**Comment by tech4him1** [comment]
This looks to me like a bug introduced in #485 -- the GitHub implementation got a `deleteFile` method, but the testing backend got a `deleteEntry` method.

**Comment by Benaiah** [comment]
@tech4him1 yup, looks like that's exactly what it is.
