### ISSUE TITLE
Bulleted and Numbered List Create Only One List Item.

### ISSUE THREAD

**Issue by bytrangle** [netlify/netlify-cms#5377]
**Describe the bug**

**To Reproduce**

**Expected behavior**

As common with rich text editor, when you create either bulleted list or numbered list, hitting the Enter key will create a new list item indicated by a bullet symbol or a number.

I suspect that the culprit is the custom plugin for toggling lists attached to the Slate editor. The file is located at *netlify-cms-widget-markdown/src/MarkdownControl/plugins/List.js*

**Screenshots**

![bulleted-list-not-creating-new-list-item](https://user-images.githubusercontent.com/28924121/118079499-84631980-b3e2-11eb-9f91-9378f031b230.gif)

![bulleted-list-one-list-item](https://user-images.githubusercontent.com/28924121/118079136-d0fa2500-b3e1-11eb-9d53-3ffbcfd24e2b.png)

**Applicable Versions:**

 - Netlify CMS version: 
   - Netlify CMS-app: 2.15.6
   - Netlify CMS core: 2.40.3
   - Netlify CMS: 2.10.126
 - Git provider: GitHub
 - OS: Mac Catalina
 - Browser version: Chrome 90

 - Node.JS version: 12.6

**CMS configuration**

Just a bare minimum config:
```
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "assets/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["software development", "programming"],
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

```

**Additional context**

**Comment by erezrokah** [comment]
Hi @bytrangle, I believe this is the same as https://github.com/netlify/netlify-cms/issues/3474#issuecomment-607549091.

Closing - please comment if this is not a duplicate

**Comment by bytrangle** [comment]
Hi @erezrokah Sorry, I have searched if an issue like exists, but didn't notice that that one was the same as mine. Good catch.
