### ISSUE TITLE
405 when publishing (merging) on gitlab

### ISSUE THREAD

**Issue by Yajo** [netlify/netlify-cms#5387]
**Describe the bug**

Cannot merge Gitlab MR with Client-Side PKCE Authorization.

    Cannot publish: API_ERROR: 405 Method Not Allowed

**To Reproduce**

1. Configure netlify-cms with gitlab backend
2. Follow these instructions for auth https://www.netlifycms.org/docs/gitlab-backend/#client-side-pkce-authorization
3. Enable editorial workflow
4. Create a new entry
5. Set it ready
6. Try to publish

**Expected behavior**

MR merged, entry published.

**Screenshots**

![Captura de pantalla de 2021-05-14 07-51-50](https://user-images.githubusercontent.com/973709/118233073-5b499400-b489-11eb-81d0-9746c4c91062.png)

**Applicable Versions:**

 - Netlify CMS version: 2.10.126
 - Git provider: gitlab.com
 - OS: fedora 34 silverblue
 - Browser version firefox 88.0.1

**CMS configuration**

https://www.recallstack.icu/admin/config.yml

**Additional context**

**Comment by erezrokah** [comment]
Hi @Yajo, I'm able to successfully publish using `PKCE` authentication.

Is you default branch protected? If that's the case you'd need `maintainer` permissions.
See note here https://www.netlifycms.org/docs/gitlab-backend/
![image](https://user-images.githubusercontent.com/26760571/118392900-a3f97c80-b644-11eb-986a-69516dfe9ca4.png)
