### ISSUE TITLE
Add handling to avoid case insensitivity issues with image uploads

### ISSUE THREAD

**Issue by verythorough** [netlify/netlify-cms#540]
**- Do you want to request a *feature* or report a *bug*?**
A feature to help avoid bugs? 😛 

**- What is the current behavior?**
It's possible to upload images with identical names if taken case-insensitively. For example, IMAGE.jpg and image.jpg can be uploaded without conflict. Of course GitHub is fine with this, as it's case sensitive, but local machines and hosting environments may not be.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Create or edit a post, and add two different images with file names that only differ by capitalization.

**- What is the expected behavior?**
I'm not sure how we want to handle this (and of course it certainly changes some with the coming Media Library UI). Perhaps the simplest is when the media library uploader checks for existing files with the same name, we make sure the check is case insensitive, and handle it in the same way as we would when a user tries to  upload an identically-named file (append a 1, ask the user to rename or overwrite, whatever).

**- Please mention your node.js, and operating system version.**
n/a

**Comment by tech4him1** [comment]
Related to #247.

**Comment by erquhart** [comment]
Related to #350.

**Comment by erquhart** [comment]
Planning to fix in #853.

**Comment by tech4him1** [comment]
@erquhart Is this fixed now?

**Comment by erquhart** [comment]
@tech4him1 good catch, yes it is.
