### ISSUE TITLE
Use block editor like craft.js ?

### ISSUE THREAD

**Issue by chrisschaub** [netlify/netlify-cms#5409]
Would it be possible to swap out the markdown editor with something like craft.js, a more block style editor? What would be involved? Thanks for any advice.

**Comment by erezrokah** [comment]
Hi @chrisschaub, can you please follow the [feature template](https://github.com/netlify/netlify-cms/issues/new?assignees=&labels=type%3A+feature&template=feature_request.md&title=Please+replace+with+a+clear+and+descriptive+title)?

That would make it easier to understand the reason(s) for the suggested change.

The current editor is based on [slate](https://github.com/ianstormtaylor/slate) and replacing it is a big undertaking.

**Comment by erezrokah** [comment]
Closing as missing information
