### ISSUE TITLE
The browser Safari indicated that there is a missing image

### ISSUE THREAD

**Issue by Pageboy** [netlify/netlify-cms#5411]
**Describe the bug**
In the editor at the point of editing a post or page, there is a missing image displayed top left.
This only seems to happen in Safari on MAC

**To Reproduce**

Use Safari Version 14.1 (16611.1.21.161.6) on MAC 11.3.1

![Screenshot 2021-05-18 at 19 59 19](https://user-images.githubusercontent.com/619455/118708445-a52cd400-b813-11eb-8d24-9ba1178205c3.png)

![Screenshot 2021-05-18 at 19 59 42](https://user-images.githubusercontent.com/619455/118708473-acec7880-b813-11eb-8d32-8708eacf98c3.png)

**Comment by ViktorYermak** [comment]
Safari does not support **:: before** **:: after**. This is the cause of this issue.

**Comment by Pageboy** [comment]
So I put
`*:before,
*:after {
  display: none;
}`
in my responsive css and that seems to fix it. Did it break anything else?

**Comment by ViktorYermak** [comment]
No, everything else works as expected. It looks like the issue has been resolved.

**Comment by tienpham241** [comment]
I figured out that the SVG code need to be encoded before using it in pseudo CSS. Use [URL-encoder](https://yoksel.github.io/url-encoder/) to encode the svg, I had a try and it is displayed correctly. Can this fix be applied?

**Comment by iChenLei** [comment]
Maybe this issue has beend fixed ? @erezrokah
