### ISSUE TITLE
Error: Could not find "store" in the context of "Connect(ComponentName)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(ComponentName) in connect options.

### ISSUE THREAD

**Issue by miguelt1** [netlify/netlify-cms#5420]
**Describe the bug**
I have several components from FE to be rendered in the preview mode that have a redux connected but when I call one to be in the preview I get this error: **Error: Could not find "store" in the context of "Connect(ComponentName)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(ComponentName) in connect options.**

**To Reproduce**
1. Setup a component from FE with redux connected 
2. Setup that component to the preview mode 
3. See error

**Expected behavior**
I would like to reuse the same component and not create other one without redux because the component can change in the future and with that I have to change in two places.

Is there any way to connect a provider with store to the cms or any other way to workaround with this?

**Comment by erezrokah** [comment]
Hi @miguelt1, can you provide a public repo reproducing the error?

It's hard for me to understand if you're trying to connect your application redux store or the CMS redux store to the preview template component.

The CMS is a self contained React application so it doesn't have access to your redux store.

**Comment by erezrokah** [comment]
Closing as missing information
