### ISSUE TITLE
Sign up and Log in not working for www.netlify.com

### ISSUE THREAD

**Issue by xarielx** [netlify/netlify-cms#5440]
**Describe the bug**
Sign up and Log in Page redirect to star background and nothing more, can not log on or sign up.

**To Reproduce**

1. Go to 'https://www.netlify.com/'
2. Click on 'Sign Up'
3. See how no forms or anything appears

**Expected behavior**
You should be able to sign up for an account

**Screenshots**
![image](https://user-images.githubusercontent.com/36430592/119829216-02d2b780-bec9-11eb-9062-44ad852f324c.png)

**Applicable Versions:**

 - OS: Windows 10
 - Browser version Version 90.0.4430.212 (Official Build) (64-bit)

**Additional context**
This is trying to access as a user

**Comment by erezrokah** [comment]
Hi @xarielx, this is a repo to report issues with Netlify CMS.
For Netlify related issues I recommend reaching out in https://answers.netlify.com/.

Regardless, I'm able to both login and get to the sign up page.

I recommend:
1. Trying in incognito mode
2. Trying in a different browser.
3. Checking you don't have any browser extensions that can block the site

**Comment by xarielx** [comment]
My apologies, closing it
