### ISSUE TITLE
when 2 collections share a directory on disk, search can be confused about what type an entry is

### ISSUE THREAD

**Issue by fool** [netlify/netlify-cms#547]
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior? If the current behavior is a bug, please provide the steps to reproduce.**

We have blogs and events configured to share a folder on disk.

When I search for a blog, it is found, and when I click to edit it, the URL returned to edit it uses it as an event instead.  Changing the URL to rename the collection (`/events/` -> `/blog/`) works to allow me to edit the entry as its proper type.

I can search in the netlify-www CMS for 'build' and find "how our build bots build sites" and this is the URL that I get to edit it:

https://www.netlify.com/admin/#/collections/events/entries/2016-10-18-debugging-builds-on-netlify

**- What is the expected behavior?**

https://www.netlify.com/admin/#/collections/blog/entries/2016-10-18-debugging-builds-on-netlify would be the URL returned

**- Please mention your node.js, and operating system version.**

netlify CMS on 22 Aug @ 1640 pacific

**Comment by fool** [comment]
cc @Benaiah

**Comment by verythorough** [comment]
This is being caused by a faulty config. Filing an issue in the affected repo.
