### ISSUE TITLE
Config option to disable search

### ISSUE THREAD

**Issue by bradystroud** [netlify/netlify-cms#5501]
**Is your feature request related to a problem? Please describe.**
The search functionality does not work for our content. It hits the GitHub API limit after 2 searches. see https://answers.netlify.com/t/cms-search-hitting-github-api-limit/39124

**Describe the solution you'd like**
1. A configuration option to disable search entirely so our users don't hit the API limit
     This should be pretty easy to implement
2. Search that doesn't hit the API limit
     This could be a bit more difficult

**Comment by bradystroud** [comment]
Hi @erezrokah,
Currently, the search queries every item in the collection. Why can't it just use the search endpoint?https://docs.github.com/en/rest/reference/search#search-code

**Comment by erezrokah** [comment]
Hi @bradystroud, that's a very good point.
The search in the CMS works a bit different - it reads the files, deserializes the content (e.g. parses the markdown/json/yaml/toml files) into the CMS collections representation (based on the configuration) and search in specific fields:
https://github.com/netlify/netlify-cms/blob/bac132e7f6699fb8c3287c3becb2cc66f09d36a3/packages/netlify-cms-core/src/backend.ts#L592

Using the search API might give good results too pending:
1. It should work in a similar for all backends (GitLab, Bitbucket, Azure, etc)
2. Searching the whole content of files still give good results (it might actually give better ones)
3. We can limit the search per collection using the search API

**Comment by erezrokah** [comment]
More context,
You should be able to access the config state here:
https://github.com/netlify/netlify-cms/blob/bac132e7f6699fb8c3287c3becb2cc66f09d36a3/packages/netlify-cms-core/src/components/Collection/Collection.js#L151

then pass it to the `Sidebar` component as a prop here:
https://github.com/netlify/netlify-cms/blob/bac132e7f6699fb8c3287c3becb2cc66f09d36a3/packages/netlify-cms-core/src/components/Collection/Collection.js#L111

Finally conditionally render the `CollectionSearch` here:
https://github.com/netlify/netlify-cms/blob/bac132e7f6699fb8c3287c3becb2cc66f09d36a3/packages/netlify-cms-core/src/components/Collection/Sidebar.js#L111

**Comment by bradystroud** [comment]
Hey @erezrokah,

Please review https://github.com/netlify/netlify-cms/pull/5509

Thanks :)

**Comment by bradystroud** [comment]
> 1. A configuration option to disable search entirely so our users don't hit the API limit

Done - The config option to disable search is now available. 
https://www.netlifycms.org/docs/configuration-options/#search

I am leaving this issue open as further investigation is needed to see if it's possible to have search that doesn't make requests for every entry. 
See https://github.com/netlify/netlify-cms/issues/5501#issuecomment-861354125 for details on a potential solution to this.

Thanks,

-Brady

**Comment by erezrokah** [comment]
> I am leaving this issue open as further investigation is needed to see if it's possible to have search that doesn't make requests for every entry.
> See [#5501 (comment)](https://github.com/netlify/netlify-cms/issues/5501#issuecomment-861354125) for details on a potential solution to this.

Do you mind opening a new issue for that? I'd rather keep things separate so it's easier to track and follow
Closing this issue as resolved.

**Comment by bradystroud** [comment]
> > I am leaving this issue open as further investigation is needed to see if it's possible to have search that doesn't make requests for every entry.
> > See [#5501 (comment)](https://github.com/netlify/netlify-cms/issues/5501#issuecomment-861354125) for details on a potential solution to this.
> 
> Do you mind opening a new issue for that? I'd rather keep things separate so it's easier to track and follow
> Closing this issue as resolved.

See #5549
