### ISSUE TITLE
TypeError: e.join is not a function

### ISSUE THREAD

**Issue by qb-rivkyb** [netlify/netlify-cms#5506]
**Describe the bug**
Log in as admin and open a collection to edit it
**To Reproduce**
This error showed up, don't know what I did wrong
**Expected behavior**
This should not be happening, it was working fine until now
some collections I am able to edit but one specific one is not working
**Screenshots**
![image](https://user-images.githubusercontent.com/75636699/122087717-0627d780-cdd3-11eb-9717-244ddf3c7dbd.png)

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.14.23`
 - Git provider: `github`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36`

**CMS configuration**
```
backend:
  name: github
  repo: [MY-REPO]
  branch: staging
  base_url: [MY_URL]
  auth_endpoint: api/auth
media_folder: public/assets
public_folder: /assets
collections:
     ...the whole collection here

**Comment by qb-rivkyb** [comment]
Seems like the error is happening when I don't reload the page and I am just clicking the back button to get to my collections and then I open a new collection to edit and the error shows up. Does this make sense at all?

**Comment by erezrokah** [comment]
Hi @qb-rivkyb, as we don't have access to your instance of the CMS can you provide a step by step guide we can follow to reproduce your issue? If possible please share a public repo reproducing it.

**Comment by qb-rivkyb** [comment]
When I don't reload between editing collections and just use the back button, I get this error.

**Comment by qb-rivkyb** [comment]
I am finding something common between the items that get this error. They all have a certain attribute/collection that they belong to. I don't know why though I would be getting that error. I noticed each of them have some text that contains `™`.
Anyway this can be researched why it's breaking all of a sudden?

**Comment by erezrokah** [comment]
> Anyway this can be researched why it's breaking all of a sudden?

Can you share the full `config.yml` per our [issue template](https://github.com/netlify/netlify-cms/issues/new?assignees=&labels=type%3A+bug&template=bug_report.md&title=Please+replace+with+a+clear+and+descriptive+title) and also share a reproduction scenario we can follow?

This usually happens when the markdown files don't match the structure defined in the CMS config, but can also come from custom widgets.

**Comment by qb-rivkyb** [comment]
I'm afraid I cannot share my config. I will see if I don't have matching structure there. Its just confusing since it does work sometimes and I am working with the same structure.

**Comment by erezrokah** [comment]
My recommendation is to remove collection by collection until you find the one that is causing the issue.
Then add the collection and repeat for each field in that collection.

**Comment by qb-rivkyb** [comment]
I think I see that the issue was that the structure was different in my json files than the config. I used to have it as a number and now I would like it to be a list. How would I update it now in the CMS If I cannot access my data since I get the error?

**Comment by erezrokah** [comment]
Hi @qb-rivkyb, you can always access you data directly in the git repo.

You can use the [local dev](https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository) flow to iterate on your changes.

**Comment by qb-rivkyb** [comment]
If I change the data directly from my code will it show on the CMS when the content managers enter the data?

**Comment by erezrokah** [comment]
> If I change the data directly from my code will it show on the CMS when the content managers enter the data?

Yes, the CMS loads the data directly from the git repo. If you change it locally you'll have to commit and push it.

**Comment by qb-rivkyb** [comment]
ok 👍 . I think I'm good for now. Thanks for your help.
