### ISSUE TITLE
Increase sign in token expiration or make variable

### ISSUE THREAD

**Issue by anagio** [netlify/netlify-cms#5507]
Logins to the CMS expire in an hour, it would be great if we can customize the tokens expiration with `JWT_EXP` or similar

**Comment by erezrokah** [comment]
Hi @anagio, can you please follow the [feature request template](https://github.com/netlify/netlify-cms/issues/new?assignees=&labels=type%3A+feature&template=feature_request.md&title=Please+replace+with+a+clear+and+descriptive+title).

Without it it's hard to understand the context of your request.

**Comment by erezrokah** [comment]
Closing as missing information
