### ISSUE TITLE
Add Docs for Publii - A desktop app for static website and blog

### ISSUE THREAD

**Issue by ilearnbydoing** [netlify/netlify-cms#551]
Hi,
you can add support for https://getpublii.com An open source desktop CMS for static websites and blog.
thanks

**Comment by tech4him1** [comment]
@w3update The CMS itself already supports most any static site generator, are you wanting this added to the docs? or do you need help setting up the CMS on your site?

**Comment by tech4him1** [comment]
@w3update If Publii is a CMS, how are you planning on using it with Netlify CMS as well?

**Comment by w3update** [comment]
@tech4him1 Its a new Desktop based static website CMS a similar like what https://www.siteleaf.com/ does as a web app CMS for static website generator, Publii can only be access from machine it is installed whereas Netlify CMS is web app and can be access via browser from internet. So probably Netlify already supporting  many static site generator and Publii too may be a simple guide can help to integrate easily or may custom develop may simplify the process. If Netlify integrated too in Publii the post can be managed via Desktop app and in web browser as well.

**Comment by tech4him1** [comment]
@w3update It looks like Publii builds the site directly on the desktop app, is that correct? If so, I'm not sure if they actually could be integrated well. Netlify CMS works by committing directly to GitHub, then assumes a build step will be run automatically to build and deploy the site (via Netlify, Travis CI, etc.).

**Comment by erquhart** [comment]
@ilearnbydoing we've added very brief notes on integrating with certain static site generators, nothing major. I don't think we'll be adding anything for Publii, but I definitely encourage you to blog about any integration opportunities you've come across!

Join us on [Gitter](https://gitter.im/netlify/netlifycms) if you want to discuss further.
