### ISSUE TITLE
Focus issues with editor component using markdown widget 

### ISSUE THREAD

**Issue by stefanprobst** [netlify/netlify-cms#5514]
**Describe the bug**

I am trying to use the `markdown` widget in an editor component. Clicking inside the markdown widget should focus it and allow text entry. However, when the widget is in richtext mode, it loses focus immediately.

**To Reproduce**

1. clone [this repo](https://github.com/stefanprobst/issue-netlifycms-focus)
2. `yarn && yarn start`
3. on `localhost:5000` click "New post" and add a `Block` component in the `Content` field.
4. try to focus the markdown widget in the `Block` component by clicking once in the bottom-half area of the `Block` component's `Content` field.

**Expected behavior**

Markdown widget in editor component should be able to receive focus.

**Screenshots**

https://user-images.githubusercontent.com/20753323/122524969-09aca000-d019-11eb-9fbe-749faa46e205.mp4

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4] current master
 - Git provider: [e.g. GitHub, BitBucket] n/a
 - OS: [e.g. Windows 7] Ubuntu 20.04
 - Browser version [e.g. chrome 22, safari 11] Firefox 88
 - Node.JS version: 14.17.0

**CMS configuration**

see linked repo above

**Additional context**

**Comment by stefanprobst** [comment]
observations:

- it seems to be an issue only when clicking on the `InsertionPoint` area (which calls `ForceInsert#moveToEndOfDocument` - when clicking the small actual slate area it seems to work

**Comment by Nrestrepo05** [comment]
Hey, I would like to work on this, but I couldn't reproduce it

**Comment by stefanprobst** [comment]
hi, just tried again and can still reproduce - i updated the instructions a bit.
in firefox, sometimes after clicking a couple of times i am able to focus it, but initially it always fails.
in chrome, i am able to focus with first click, but focus is lost after one character is entered.

**Comment by Nrestrepo05** [comment]
I could reproduce it on firefox but I still can't on chrome :/
