### ISSUE TITLE
List Widget Variable Types: Add Type as Heading when item is expanded

### ISSUE THREAD

**Issue by MirkoLenz** [netlify/netlify-cms#5515]
**Is your feature request related to a problem? Please describe.**

I make use of the variable lists feature to enable block-based content editing for my clients. A major issue for me is that the CMS does not show the editor the type of the widgets. Using a summary is only a partial solution, because it gets hidden if the object is expanded.

**Describe the solution you'd like**

I also experimented with custom components for the markdown widget. Here, the type/name of the component is clearly stated in the top left corner of the editing interface. That way, the editor always knows what type of content he is currently authoring.

**Describe alternatives you've considered**

I considered using markdown files with custom widgets, but this combination has some issues when combined with Gatsby. For instance, I need a gallery widget having multiple images. If I use a markdown component, Gatsby does not automatically link the respective file and requires manually adding and maintaining an "assets" field.

**Additional context**

- Custom Markdown component with the type (formular) visible in the top left cornder: <img width="768" alt="Screenshot-2021-06-19T23-26-08" src="https://user-images.githubusercontent.com/5160954/122655817-d7548d00-d155-11eb-84d6-f8e91c7ac268.png">
- Variable Types with no type information when expanded: <img width="779" alt="Screenshot-2021-06-19T23-26-18" src="https://user-images.githubusercontent.com/5160954/122655836-f18e6b00-d155-11eb-9a87-1c1b3f24f99b.png">

**Comment by erezrokah** [comment]
If anyone would like to pick this up the place to start is here:
https://github.com/netlify/netlify-cms/blob/879e03b6f16feb23b49ba4248f2ad1eb3da4d259/packages/netlify-cms-widget-list/src/ListControl.js#L501

**Comment by sj-rai** [comment]
@erezrokah I'd like to give this a try

**Comment by MirkoLenz** [comment]
Thank you all for resolving this issue in such a short amount of time!
