### ISSUE TITLE
markdown widget should avoid serializing links as autolinks for mdx compatibility

### ISSUE THREAD

**Issue by stefanprobst** [netlify/netlify-cms#5516]
**Describe the bug**

The markdown widget currently defaults to serializing links as autolinks if possible, i.e. `[https://example.com](https://example.com)` will be serialized as `<https://example.com>`. This is the default behavior of `remark-stringify` (and an option to change this behavior only exists in newer versions of `remark-stringify`).

Unfortunately, autolinks are [not compatible with MDX](https://github.com/micromark/mdx-state-machine#723-autolinks), which means that trying to render the content of a markdown widget as mdx might throw unexpectedly.

**To Reproduce**

1. Enter the following in a markdown widget in "markdown" mode: `[https://example.com](https://example.com)`
2. switch to richtext mode and press enter (or add any other random character)
3. switch back to markdown mode, see that the links has changed to `<https://example.com>`

**Expected behavior**

While autolinks are valid md, it would be great if md could be serialized to something mdx-compatbile

**Possible solution**

i made a plugin for `remark-stringify` which enforces resource links and avoids autolinks (slightly modified upstream visitor for `link` nodes), which could be added [here](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-widget-markdown/src/serializers/index.js#L134-L138)

these would be the necessary changes: https://github.com/stefanprobst/netlify-cms/commit/fa54da5df4a84d98c3eeb42c68fbe02373336830 happy to contribute if you think this makes sense.

**Comment by erezrokah** [comment]
Hi @stefanprobst, how about tying this into https://github.com/netlify/netlify-cms/issues/4601?

We could provide a way to dynamically register plugins so this would be opt-in.

**Comment by stefanprobst** [comment]
> how about tying this into #4601?

sure, making all this configurable sounds :+1:

two potential issues: (i) netlifycms uses a pretty old version of remark and current plugins may or may not be compatible with it, (ii) i'm not sure about the manual slate-ast<=>mdast transformations the md widget does, and how well these play with random plugins (a plugin in remark can be a plugin to the parser, the compiler or a transformer plugin)

**Comment by erezrokah** [comment]
Great points - I think we can classify this feature as beta/experimental (to set some expectations) as it's mostly will be used to unblock specific use cases.
