### ISSUE TITLE
Open authoring option should be available to all users

### ISSUE THREAD

**Issue by bradystroud** [netlify/netlify-cms#5526]
**Is your feature request related to a problem? Please describe.**
Currently, the editorial workflow for users with write access does not work how we would like it to for PR workflows with protected branches and reviewers. When users are editing an entry, it is unclear what changing the save button, status dropdown and publish buttons actually do and when they should be used.

See SSWConsulting/SSW.Rules/issues/564

**Describe the solution you'd like**
A configuration option that would make all users use the open authoring editorial workflow.

As explained here https://www.netlifycms.org/docs/open-authoring/#usage, there are 2 different UI's that users see depending on their access level to the repository. 
Users with write (or higher) access see this interface

![Screen Shot 2021-06-28 at 9 59 48 am](https://user-images.githubusercontent.com/38869720/123563366-96184900-d7f7-11eb-841a-39756f1e6698.png)
**Figure: Write access UI - Lots of buttons 👎🏻** 

Users without write access see this interface:

![2021-06-28_10-23-12](https://user-images.githubusercontent.com/38869720/123563977-dcbb7280-d7fa-11eb-881e-fef63c3fe118.png)
**Figure: No write access - Less buttons 👍🏻**

The open authoring editorial workflow (2nd one) has less buttons which makes it less confusing for users.

This config option would give all users the UI shown in the second screenshot even if they have write access.   

**Describe alternatives you've considered**
Our current solution is only giving a small portion of our users write access so the majority of them see the open authoring editorial workflow.
The downside of this solution is that users without write access cannot review other peoples PR's.  

**Additional context**
https://github.com/SSWConsulting/SSW.Rules/issues/557

**Comment by erezrokah** [comment]
Hi @bradystroud, I'm having a hard time understand this feature request and the use case it is trying to solve.
Can you follow the [template](https://github.com/netlify/netlify-cms/issues/new?assignees=&labels=type%3A+feature&template=feature_request.md&title=Please+replace+with+a+clear+and+descriptive+title)?

Is [this](https://github.com/netlify/netlify-cms/pull/5204) what you want?

**Comment by bradystroud** [comment]
Hi @erezrokah,

I have updated the issue using the template provided and added some additional info. 

> Is [this](https://github.com/netlify/netlify-cms/pull/5204) what you want?

No - This makes all users fork instead of branching. We want users with write access (or higher) to still be able to use branches, but see the UI that readonly users see.

Thanks,

-Brady
