### ISSUE TITLE
Ship source code with npm package

### ISSUE THREAD

**Issue by BerkeleyTrue** [netlify/netlify-cms#553]
Currently running into an issue with an unhelpful help message:  `Collection must have a field name that is a valid entry identifier`

While investigating I found that ncms only ships with the minified source code. Also, the source mapping comment is missing from the js source so the source map provided will not be loaded by default.

It be great to be able to use the actual source code while I am debugging the cms with our apps.

**Comment by erquhart** [comment]
@Benaiah can you update this with the latest on how we (might) approach this?

cc/ @biilmann

**Comment by BerkeleyTrue** [comment]
@erquhart We should be able to accomplish this by adding a .npmignore that copies .gitignore minus the src directory

**Comment by tech4him1** [comment]
The sourcemaps are now included with the NPM package, and include the linked source code (excluding external modules). Is there any other ways that you would suggest expanding on this?

**Comment by erquhart** [comment]
Ah, nope, we aren't shipping source 🤦‍♂️. @BerkeleyTrue we'd definitely take a PR to finish enabling sourcemaps.

**Comment by tech4him1** [comment]
@erquhart If we're going to start shipping the source code, then we don't need to have the source code bundled as part of the `cms.js.map`, right?

**Comment by erquhart** [comment]
@tech4him1 right, we should not need that, only the map itself.

**Comment by snirp** [comment]
Google brought me here. Got the same message: `Collection must have a field name that is a valid entry identifier`. Any suggestions as to what causes this?

**Comment by snirp** [comment]
Resolved it by adding a field named `title` to the collection. I presume that Netlify needs this field to generate a filename slug.
