### ISSUE TITLE
Redirect Subdomain to Domain After Connecting

### ISSUE THREAD

**Issue by yousafblogger** [netlify/netlify-cms#5530]
That's a big issue that if we attach a custom domain with our netlify account then the sub domain given by netlify.app doesn't redirect to the domain. 

This hurt SEO factors and resulted duplicate content. Like my website is [try10.com](https://try10.com), but it's subdomain try10.netlify.app doesn't redirected to my main primary domain. 

I discoved it when my website's ranking were decreased and then I've done this with public/_redirects file.

**_This must need to be done by default._**

**Comment by erezrokah** [comment]
Hi @yousafblogger, this repo is intended for Netlify **CMS** related issues.
I suggest you post your issue on https://answers.netlify.com/.

Please comment on the issue if you have any further questions.
