### ISSUE TITLE
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### ISSUE THREAD

**Issue by miguelt1** [netlify/netlify-cms#5543]
**Describe the bug**
So I followed a tutorial to create a new custom widget for the cms but after I compile gives me an error when I access to the netlify cms like the title shows.
Here is the tutorial: https://dev.to/room_js/create-a-custom-widget-for-netlify-cms-4gl9

**To Reproduce**

1. Create a control widget
2. Create a preview widget
3. Register the widget
4. Add the field to the schema

**Expected behavior**
Shows the custom widget(the editor) and work as expected.
I assume this tutorial is out of date so if so you could give me support in that sense.

**Comment by erezrokah** [comment]
Hi @miguelt1, if you follow the error link you can see the error:
![image](https://user-images.githubusercontent.com/26760571/123623604-51e87100-d816-11eb-873f-2ea705413995.png)

It looks like the custom widget is trying to render an `undefined` value.

Can you share a public repo reproducing the issue? I believe this doesn't happen with every custom widget, so the reproduction scenario you shared only works with the specific widget you're building.
