### ISSUE TITLE
Hide 'CHANGES SAVED' message and 'Save' button if no changes have been made

### ISSUE THREAD

**Issue by bradystroud** [netlify/netlify-cms#5553]
**Is your feature request related to a problem? Please describe.**
When the editor loads, it shows 'CHANGES SAVED' and the 'save' button before any changes are made.  

**Describe the solution you'd like**
Instead of showing 'CHANGES SAVED', it should be blank until a change is made. After a change has been saved, this message should show. The 'Save' button should be disabled in all cases unless there are unsaved changes. 

**Describe alternatives you've considered**
none

**Additional context**
![2021-06-30_09-16-29](https://user-images.githubusercontent.com/38869720/123881260-ad863c00-d987-11eb-8a33-34860e1909d3.png)
**Figure: Message 'CHANGES SAVED' and the 'save' button shown before anything was changed**

![Screen Shot 2021-06-30 at 4 51 21 pm](https://user-images.githubusercontent.com/38869720/123915043-69b12800-d9c3-11eb-87a1-16e837fbcb10.png)
**Figure: Mockup - Proposed UI**

**Comment by erezrokah** [comment]
Hi @bradystroud, this would make a nice improvement. We would need to avoid layout shifting when hiding/showing the button. For example in the UI mockup the `Writing in...` text is centered and in the actual UI it is pushed a bit up due to the existing `Changes saved` text.
