### ISSUE TITLE
Hide 'Delete published entry' button if using the open authoring editorial workflow

### ISSUE THREAD

**Issue by bradystroud** [netlify/netlify-cms#5554]
**Is your feature request related to a problem? Please describe.**
If you are an Open Authoring user, the 'Delete published entry' button is shown in the header but just shows an error when it is pressed.

**Describe the solution you'd like**
To improve the UX, the 'Delete published entry' button should be hidden if you are an Open Authoring user.
'Delete unpublished changes' will still show up.

**Describe alternatives you've considered**
None

**Additional context**
![Screen Shot 2021-06-30 at 8 23 43 am](https://user-images.githubusercontent.com/38869720/123875133-7d856b80-d97c-11eb-9929-05a5d7e34636.png)
**Figure: Error message shown after pressing button**

See this YouTube video that goes through this as well as some related changes - https://youtu.be/8vhHKf0nCS4

**Comment by erezrokah** [comment]
That's a great improvement! How about disabling it instead of hiding and adding a tooltip on hover that explains why the button is disabled?

**Comment by bradystroud** [comment]
Hi @erezrokah,

If you are an Open Authoring user the publish dropdown button is hidden. To keep it consistent, I think that this one should be hidden as well.

**Comment by erezrokah** [comment]
> If you are an Open Authoring user the publish dropdown button is hidden. To keep it consistent, I think that this one should be hidden as well.

Good point. Let's go with hiding it
