### ISSUE TITLE
Add info ℹ   hover tooltip next to 'Set status' dropdown

### ISSUE THREAD

**Issue by bradystroud** [netlify/netlify-cms#5556]
**Is your feature request related to a problem? Please describe.**
It is unclear what changing the status on an entry does and whether users have completed all actions they need to do for their change to be reviewed. 

**Describe the solution you'd like**
A small info icon next to the 'Set status' that shows a tooltip explaining what 'Draft' and 'In review' mean.

This is the suggested contents of the tooltip:

> **Draft:** Your changes have been saved. To finalise your change and submit it for review, set the status to ‘In review’
**In Review:** Your changes are being reviewed, no further actions are required. However, you can still make additional changes while it is being reviewed.

We have only considered this for the Open Authoring workflow, but this could also be added for the normal workflow in the future.

**Describe alternatives you've considered**
None

**Additional context**
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/38869720/123912246-230dfe80-d9c0-11eb-9643-c766fdf79c0e.png)

See our YouTube video that goes through this as well as some related changes - https://youtu.be/8vhHKf0nCS4

**Comment by erezrokah** [comment]
Thanks @bradystroud, that would indeed make things clear for open authoring contributors.

Since both in `Draft` and `In Review` there can be unsaved changed can we re-phrased it a bit?

```
Draft: Entry status is set to draft. To finalize and submit it for review, set the status to ‘In review’
In Review: Entry is being reviewed, no further actions are required. However, you can still make additional changes while it is being reviewed.
```

**Comment by bradystroud** [comment]
Hi @erezrokah, that sounds good 👍🏻
