### ISSUE TITLE
Add current status to button label

### ISSUE THREAD

**Issue by bradystroud** [netlify/netlify-cms#5557]
**Is your feature request related to a problem? Please describe.**
The set status dropdown is confusing for users becuase they cannot see what the current status is without opening the dropdown. As such, when they set the status, it is unclear what has happend.

**Describe the solution you'd like**

### Option 1 (preferred)
A label should be added to the left of the button that says 'Status:' and the label on the button should become the current status e.g. Draft

![2021-06-30_16-33-56](https://user-images.githubusercontent.com/38869720/123913253-5604c200-d9c1-11eb-9efb-567d40040fb5.png)
**Figure: Mockup - Option 1**

The dropdown menu would still function the same.

**Describe alternatives you've considered**
### Option 2
The 'Set status' dropdown should be labeled with the current status instead e.g.
'Status: **Draft**' 

![2021-06-30_11-41-16](https://user-images.githubusercontent.com/38869720/123889084-1f668180-d998-11eb-88e5-3370d8e7353e.png)
**Figure: Mockup - Option 2**

'Current status: **Draft**'  - Feel free to suggest different wording.

**Additional context**
See our YouTube video that goes through this as well as some related changes - https://youtu.be/8vhHKf0nCS4

**Comment by erezrokah** [comment]
See my comment here https://github.com/netlify/netlify-cms/issues/5555#issuecomment-871259430

**Comment by pcanof** [comment]
Hey! I'm a new developer looking for issues and I would like to work on this issue

**Comment by pcanof** [comment]
Hi, I made a PR and I want to mention that there is a text in my code ("Current Status:") that is not using the locales variables, so I think it will necessary to add another variable in en.editor.editorToolbar that is in the file /packages/netlify-cms-locales/en/index.js and the translate for the other languages

**Comment by erezrokah** [comment]
Closes via https://github.com/netlify/netlify-cms/pull/5574 (and [released](https://github.com/netlify/netlify-cms/releases/tag/netlify-cms%402.10.144)). Thanks everyone!
