### ISSUE TITLE
Support markdown in widget hint texts

### ISSUE THREAD

**Issue by awesomephant** [netlify/netlify-cms#5559]
I'd like to make widget help texts more useful by adding links to external documentation, and using bold and italics for emphasis. 

**Describe the solution you'd like**
I'd like the ```hint``` option to support a subset of markdown so I can add links, bold, and italics. Alternatively, I'd also be okay with writing straight HTML to do the same thing.

At the moment neither of these options work: Markdown isn't processed and HTML is escaped by React:

![image](https://user-images.githubusercontent.com/2758247/124029861-e52bcd00-d9f5-11eb-9dc4-46e7cc2f57f9.png)

Thanks!

**Comment by timtorres** [comment]
Is it possible to add support for strikethroughs?

I'm using the hint to give the editors instructions on how to format an external link, showing the whole context and which parts to remove:
`https://www.linkedin.com/pulse/complex-world-early-interventions~~?trk=public_profile_article_view~~`

**Comment by erezrokah** [comment]
Hi @timtorres, how about opening a new feature request issue for that?
You can link this code as reference:
https://github.com/netlify/netlify-cms/blob/610421ea6722276e37fe3c6123386d20fbbac1cf/packages/netlify-cms-core/src/components/Editor/EditorControlPane/EditorControl.js#L333

That will make it easier to submit a contribution for it.
