### ISSUE TITLE
feature: Add commit message templates

### ISSUE THREAD

**Issue by BerkeleyTrue** [netlify/netlify-cms#557]
**- Do you want to request a *feature* or report a *bug*?**
feature
**- What is the current behavior?**
Currently the user has no control of how the application writes commit messages. 
**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**
It be awesome for users to provide templates through the config. This would allow users to stick with popular commit message formats like [conventional-changelog-angular](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md).

**- Please mention your node.js, and operating system version.**

**Comment by tech4him1** [comment]
@BerkeleyTrue That's an awesome idea, thanks for filing this!

**Comment by knpwrs** [comment]
This is something that I am potentially interested in implementing. @BerkeleyTrue, were you thinking something in the admin interface or something in the configuration? My idea was for something in the configuration, either globally or perhaps at the collection level, that would allow the commit message to say something like `User ${user} updated page ${page}`.

It looks like [right now the commit message is hard-coded between "Create" and "Update".](https://github.com/netlify/netlify-cms/blob/756d562c6651b1634143f1f7d47ffc8119fe59bb/src/backends/backend.js#L259-L260) I could imagine something like this in the configuration to support different commit messages without having to build out an interface:

```yml
commit:
  type:
    # Override default uppercase verbage for conventional changelog
    update: update
    create: create
  message: "${type}: ${file} by ${user}"
```

My main interest is tying each individual commit to a user, so my use-case has no need for a UI.

**Comment by erquhart** [comment]
@knpwrs this looks solid as a general approach, feel free to take a stab.

I think the simplest configuration option would be to just accept a separate message for each type and not try to combine them. This provides max configurability and less room for confusion about what the config keys do:

```
commit_messages:
  update: "update: {{file}} by {{user}}"
  create: "create: {{file}} by {{user}}"
```
