### ISSUE TITLE
How to get in touch about a security issue?

### ISSUE THREAD

**Issue by zidingz** [netlify/netlify-cms#5570]
Hey there,

As there isn't a `SECURITY.md` with an email on your repository, I am unsure how to contact you regarding a potential security issue.

Would you kindly add a `SECURITY.md` file with an e-mail to your repository? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this as the best way to ensure security issues are responsibly disclosed, and it would massively help security researchers get in touch next time.

Thank you so much and I look forward to hearing from you!

**Comment by erezrokah** [comment]
Hi @zidingz, thank you for raising this.

You can report to `security@netlify.com` or via [Hacker one](https://hackerone.com/netlify?type=team).

Keeping this issue open until we add a `SECURITY.md`.

**Comment by zidingz** [comment]
Thank you for your quick response!

An email will be with you shortly.

**Comment by erezrokah** [comment]
Closing per https://github.com/netlify/netlify-cms/security/policy.

We've added an organization wide policy to our repos. Thank you for raising this!
