### ISSUE TITLE
Feature to Apply Classes in fields and define them in identity file!

### ISSUE THREAD

**Issue by yousafblogger** [netlify/netlify-cms#5573]
Hi,

I want to customize the netlify CMS by doing 50% width of some fields. So I wanted to add class to that field. but didn't found anything!

I want this featured!

**Comment by erezrokah** [comment]
Hi @yousafblogger, can you please follow the [issue template](https://github.com/netlify/netlify-cms/issues/new?assignees=&labels=type%3A+feature&template=feature_request.md&title=Please+replace+with+a+clear+and+descriptive+title)?

Without it it's very hard to understand what you're trying to accomplish.

Closing this issue as I believe it is covered by https://github.com/netlify/netlify-cms/issues/1727.

If that's not the case please comment
