### ISSUE TITLE
markdown characters not escaped in new editor

### ISSUE THREAD

**Issue by tech4him1** [netlify/netlify-cms#558]
**- Do you want to request a *feature* or report a *bug*?**
bug, caused by #254 

**- What is the current behavior?**
If a user types (#) pound character(s) at the beginning of a line in the regular editor, then switches to the markdown editor (and edits anything), the editor will convert the line to a heading.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. In the regular editor, add a line like this: `## this is a test`.
2. Switch to the markdown editor and change any line (doesn't have to be the same line).

**- What is the expected behavior?**
The pound sign should be escaped, like in the old editor (`\## this is a test`).
**We should probably check all other special MD characters as well.**

**Comment by erquhart** [comment]
Great catch - we need to escape any markdown characters entered in the visual editor, we're currently escaping none of them.

Characters to always escape: `_`, `*`, `[`
Characters to escape when at the beginning of a block: `#`, `-`
Characters to escape when more than one present: `~`
