### ISSUE TITLE
TypeError: e.join is not a function

### ISSUE THREAD

**Issue by ZDVokoun** [netlify/netlify-cms#5590]
**Describe the bug**
When you add tags to an article as a space-separated string, the article won't open in Netlify CMS.

**To Reproduce**
1. Create a new article with tags written as *a space-separated string* (`tags: foo bar` instead of `tags: [foo, bar]` )
2. Try to edit the article in Netlify CMS

**Expected behavior**
I can edit the article in Netlify CMS as usual.

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.144`
 - Git provider: `proxy`
 - Browser version: `Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0`

**CMS configuration**
```
backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
local_backend: true
media_folder: assets/img/uploads
publish_mode: simple
collections:
  - name: post
    label: Post
    folder: _posts
    sort: date:desc
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: post
      - label: Title
        name: title
        widget: string
        tagname: h1
      - label: Description
        name: description
        widget: string
        required: false
      - label: Publish Date
        name: date
        widget: datetime
        format: YYYY-MM-DD HH:mm:ss
      - label: Categories
        name: categories
        widget: string
        required: false
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Body
        name: body
        widget: markdown
        required: false
    publish: true
    type: folder_based_collection
    sortable_fields:
      - title
      - date
      - description
    view_filters: []
    view_groups: []
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
public_folder: /assets/img/uploads
isFetching: false
error: null

```

**Additional context**

**Comment by erezrokah** [comment]
Hi @ZDVokoun, how are you creating the space separate value?

This is [not currently supported](https://github.com/netlify/netlify-cms/issues/4646) via the UI

**Comment by ZDVokoun** [comment]
> Hi @ZDVokoun, how are you creating the space separate value?
> 
> This is [not currently supported](https://github.com/netlify/netlify-cms/issues/4646) via the UI

I haven't created it via UI but via text editor. I haven't known that it isn't supported

**Comment by erezrokah** [comment]
I'll open a PR to better handle this can (not fail). I'll close this issue in favor of https://github.com/netlify/netlify-cms/issues/4646
