### ISSUE TITLE
Markdown editor - minor issues

### ISSUE THREAD

**Issue by biilmann** [netlify/netlify-cms#56]
I'm grouping a bunch of minor issues for the text editor here to avoid creating a bunch of small tickets. Feel free to split them up if any of them need more discussion.
- [ ] Newline should always start paragraph block. If you're in a H1 and press enter, new block should be normal paragraph text.
- [ ] Pressing backspace or delete when a component (like the youtube embed) should delete the component
- [x] Paste needs to format text properly (right now all text becomes H1)
- [ ] Type something, press shift+enter creates line-break, typing more deletes everything before the line break
- [ ] Make a paragraph with an internal line break in raw mode. Switch to rich mode. After line break, press enter. Now change block before line break to H1. Both paragraphs becomes H1.
- [x] We will need to fix the flickering since it gets real bad when there's an image component

**Comment by okonet** [comment]
Flickering is fixed in #82. I think I'll tackle the rest of these as far as I can.

**Comment by okonet** [comment]
I feel like

> Newline should always start paragraph block. If you're in a H1 and press enter, new block should be normal paragraph text.

is conflicting with

> Type something, press shift+enter creates line-break

Why do we even need a soft-break in the editor?

**Comment by okonet** [comment]
> Pressing backspace or delete when a component (like the youtube embed) should delete the component

I agree and this also should handle media removal. Right now if I add an image and then remove the reference in text, it stays in the repository. This might need a separate ticket. Thoughts?

**Comment by cedricdelpoux** [comment]
Do you plan to add header bar to control our markdown instead of the tooltip ?

The `SiteLeaf` markdown editor is very great : 
![Siteleaf editor](https://www.dropbox.com/s/eva75qvn5ad3a6p/Capture%20d%27%C3%A9cran%202016-10-15%2012.28.21.png?dl=1)

It enable possibility to switch from markdown to visual feedback and we can add some images and links directly. 
So the preview panel could be useless #113 

What do you think ?

**Comment by okonet** [comment]
We probably will at some point. We'll also provide a WYSIWYG editor later.

**Comment by cedricdelpoux** [comment]
Super, thank you very much

**Comment by cassiozen** [comment]
I'm closing this due to the change of plans regarding editor. Right now we're using a code view editor and will revisit the WYSIWYG editor in near future.

Please feel free to reopen if you want to add to the discussion.
