### ISSUE TITLE
Feature Request: Sorting Collections

### ISSUE THREAD

**Issue by jholmes033169** [netlify/netlify-cms#561]
Prior to the move from Ember to React, collections apparently supported a "sort" property, which would order the cards visually by the supplied property value.

Apparently that functionality got dropped, as the property is no longer honored. I guess that makes this a kinda sorta bug.

Ideally we should be able to specify the sorting property and ascending/descending:

sort: "date:desc"

Even more ideally, multiple sort properties could be specified:

sort: "sequence:asc,date:desc,title:asc"

**Comment by erquhart** [comment]
Closing in favor of #54
