### ISSUE TITLE
Submissions at huntr.

### ISSUE THREAD

**Issue by B3EF** [netlify/netlify-cms#5610]
Reports at Huntr
[report : 1](https://huntr.dev/bounties/1625858382797-netlify/netlify-cms/)
[report : 2](https://huntr.dev/bounties/1625079955087-netlify/netlify-cms/)
[report : 3](https://huntr.dev/bounties/1625079232522-netlify/netlify-cms/)

**Comment by erezrokah** [comment]
Thanks @B3EF. for the first report see:
https://github.com/netlify/netlify-cms/issues/4099

Looking into the others ones

**Comment by B3EF** [comment]
hi @erezrokah the pr #4099 
seems that its been fixed but , lately while i was testing in the new one , it seems to be popping up alerts for objects other than custom strings in the alert box.

**Comment by erezrokah** [comment]
> hi @erezrokah the pr #4099
> seems that its been fixed but , lately while i was testing in the new one , it seems to be popping up alerts for objects other than custom strings in the alert box.

Are you setting the `sanitize_preview` configuration for the markdown field?

**Comment by B3EF** [comment]
yes i have tried changing the preview from rich text to md , then also the alert pops up.

**Comment by erezrokah** [comment]
Can you share your `config.yml`?

**Comment by B3EF** [comment]
yes you are right seems like i haven't set the sanitize_preview in the config.yml file ?
how can i add it ? is there any syntax to be followed like sanitize_preview : true ?

**Comment by erezrokah** [comment]
On your markdown field add `sanitize_preview: true`
e.g.

```yaml
- { label: 'Body', name: 'body', widget: 'markdown', sanitize_preview: true }
```

**Comment by B3EF** [comment]
Is your demo site configured with sanitize_preview true ? Because I am getting pop up in that.
![IMG_20210712_224347.jpg](https://user-images.githubusercontent.com/43377443/125329047-a802fb80-e362-11eb-9046-544a87ce6e6a.jpg)

**Comment by erezrokah** [comment]
> Is your demo site configured with sanitize_preview true ? Because I am getting pop up in that.

No it's not - see https://github.com/netlify/netlify-cms/blob/b94d5f6e7fe07a2816098b377b30a4ddd39c9520/dev-test/config.yml

**Comment by B3EF** [comment]
then you are right , it was a mistake from my side thanks for your time.

**Comment by B3EF** [comment]
i will close the first report , or you can invalidate it.
cheers 👍🏻

**Comment by B3EF** [comment]
have you checked the other ones?

**Comment by erezrokah** [comment]
> i will close the first report , or you can invalidate it.
> cheers 👍🏻

Thanks!

> have you checked the other ones?

I've passed them to our security team for further analysis. I'll add my thoughts on the specific reports too.

**Comment by B3EF** [comment]
Hi @erezrokah , huntr have reduced the severity level for both.

**Comment by B3EF** [comment]
hi , any updates.

**Comment by erezrokah** [comment]
Hi @B3EF, sorry for the delay. I was out of office for a few days. I'll follow up this week

**Comment by B3EF** [comment]
No problem , take your time.

**Comment by erezrokah** [comment]
Closing per my latest comments on huntr
