### ISSUE TITLE
Netlify CMS constantly rewrites DOM nodes when the preview content has an image

### ISSUE THREAD

**Issue by madhavan-sundararaj** [netlify/netlify-cms#5612]
**Describe the bug**
I am using Netlify cms with NextJS and Emotion. Recently added custom styling to preview pane and while adding images / videos, the content keeps on refreshing even without focusing or changing the input causing high CPU usage.

**Expected behavior**
The content should not refresh without the input being changed

**Screenshots**

https://user-images.githubusercontent.com/42700140/125428696-540dca75-6a8f-4766-9bdc-40b2f18c9c32.mov

As you can see from the above video - when an image is in the content, the preview panel constantly rewrites it's DOM nodes.

**Applicable Versions:**

 - Netlify CMS version: 2.15.26
 - Git provider: GitHub
 - OS: macOS
 - Browser version: Chrome Version 91.0.4472.114 

 - Node.JS version: 14

**Additional context**

**Comment by erezrokah** [comment]
Hi @madhavan-sundararaj, can you please post a reproduction scenario? Ideally a public repo with the issue

**Comment by stefanprobst** [comment]
for me, it helped to wrap the preview component in `React.memo`, e.g. `CMS.registerPreviewTemplate('posts', memo(PostPreview))`.
