### ISSUE TITLE
Global format parameter

### ISSUE THREAD

**Issue by Honatas** [netlify/netlify-cms#5618]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be nice to have a global level format configuration that overrides the default, so I don't need to add format: json to every collection.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by erezrokah** [comment]
Hi @Honatas, thank you for opening the issue.

Closing this as a specific case of https://github.com/netlify/netlify-cms/issues/1342.

You could use `yaml` aliases to get a behavior that's close to this request, [or use JS based config](https://www.netlifycms.org/docs/beta-features/#manual-initialization).

**Comment by Honatas** [comment]
Yaml aliases do not solve the problem. I want to avoid local (collection) configuration. With the aliases I would have to add them to the collections, which invalidates my request.

**Comment by erezrokah** [comment]
> Yaml aliases do not solve the problem. I want to avoid local (collection) configuration. With the aliases I would have to add them to the collections, which invalidates my request.

Would switching to JS based configuration work? You can write a function that generates the config to reduce duplication.
