### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by SlashArash** [netlify/netlify-cms#5619]
**Describe the bug**
by opening a page editor the page breaks with the following error
`TypeError: Cannot read property 'push' of undefined`

I checked the console on devtools and there were two errors that I attached to the screenshots section. it seems the issue is from `react-datetime@^3.0.0` that is a dependency for `netlify-cms-widget-date@^2.6.2`.
I'm using latest version of netlify-cms-app ("netlify-cms-app": "^2.15.27")

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_20210716_221003](https://user-images.githubusercontent.com/3456305/125987739-f0a47ced-3142-4f10-be60-92d52acee503.png)

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.15.27`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36`

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    slug: "{{slug}}"
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: blog-post
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Body
        name: body
        widget: markdown
      - label: Tags
        name: tags
        widget: list
      - label: Keywords
        name: keywords
        widget: list
      - label: Description
        name: description
        widget: text
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - date
      - commit_author
      - description
    view_filters: []
    view_groups: []
  - name: page
    label: Pages
    folder: src/pages
    create: true
    slug: "{{slug}}"
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: single-page
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Body
        name: body
        widget: markdown
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - date
      - commit_author
    view_filters: []
    view_groups: []
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
isFetching: false
error: null

```

**Additional context**

**Comment by erezrokah** [comment]
Hi @SlashArash, can you provide a reproduction scenario? This is probably related to existing data the CMS tries to load, so sharing a public repo with the issue will make it much easier to debug.

**Comment by SlashArash** [comment]
@erezrokah thank you for following up. I rebuild it and there is no error! I'm going to close this ticket.
