### ISSUE TITLE
Select widget displays first option by default, but behaves as if empty

### ISSUE THREAD

**Issue by verythorough** [netlify/netlify-cms#562]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
When you start a new item in a collection, select widgets (without a set default - haven't tried with a default yet) will display the first option, as if they are selected. However, when you try to save, the field behaves as if it's blank: saving is blocked, and the label turns red.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Make a new Kitchen Sink item in the CMS demo site: https://cms-demo.netlify.com/#/collections/kitchenSink/entries/new

Note that the Select field appears to be set to the first choice, "a". Click save, watch it fail, and see the red label for the select entry:
![filledselect](https://user-images.githubusercontent.com/6111186/29798822-50ade1aa-8c14-11e7-852f-dadae892aacf.PNG)

Select any option (inlcuding "a"), and it will save properly.

**- What is the expected behavior?**
Normally, I would expect the dropdowns to be blank in their initial state. If not, they should actually be set to the option they display.

**- Please mention your node.js, and operating system version.**
Current Chrome on Windows 10, CMS 0.4.6

**Comment by JacobMillward** [comment]
If you add a `default` option with the same value as the first select choice, it works around it. In my case, my select only had one option though.

**Comment by moshie** [comment]
What happens in the event you want an empty option and a different label simply setting:
```
options:
  - { label: "Not featured", value: "" }
  - { label: "Featured", value: "featured" }
```

This shows the extra hidden option and the empty one instead of overwriting it.

**Comment by tech4him1** [comment]
@moshie Feel free to open a new issue and request support for that.
