### ISSUE TITLE
Question: Netlify CMS + NextJS

### ISSUE THREAD

**Issue by d1vshar** [netlify/netlify-cms#5634]
I'm using Netlify CMS with NextJS (in JS). I have a collection named `events`.

Now I have a page called events where I'd like to display a list of events.

I used a webpack plugin https://www.npmjs.com/package/babel-plugin-wildcard. It expands imports during compile time.

```js
import * as allEvents from '../content/events';

export const getAllEvents = () => {
  const eventSlugs = Object.keys(allEvents);

  const eventList = [];

  eventSlugs.forEach((slug) => eventList.push(
    {
      slug,
      ...(allEvents[slug]),
    },
  ));

  return eventList;
};
```
This works for a clean build.

But here's the issue: NextJS caches build files too. Both on Netlify and on local. When a change with a new event is pushed, the code in the above JS file is never "expanded". This results in no changes in the list displayed on the page.

What's a better way to solve this use case?

**Comment by erezrokah** [comment]
Hi @d1vshar, this seems more of a Next.js/Babel question than a CMS question as I assume the CMS writes the correct content to the repo.
You might want to look into the plugin's code and try its clear cache command:
https://github.com/vihanb/babel-plugin-wildcard/blob/e9256b9d833e32bd635cbdcff3f1f4e4adf8b307/index.js#L9

Once you figure out how to clear the cache, [this tool](https://github.com/M-Zuber/npm-watch) might help for local development.

**Comment by erezrokah** [comment]
On a completely other note, I believe Next.js should be able to source data from content files (e.g. Markdown) directly.
See https://nextjs.org/blog/markdown

**Comment by d1vshar** [comment]
Thanks for responding!

I actually figured it out. NextJS's data fetching works through getStaticProps, getStaticPaths, getServerSideProps. I wasn't using them at all! (Cause I'm new to next).

You can use node modules (like `fs`) in these functions cause compilation happens in a node environment.

**Comment by erezrokah** [comment]
Cool, thanks for the follow up. Closing the issue. Please comment if you have further questions
