### ISSUE TITLE
option for object widget to be hidden when all of its fields are hidden

### ISSUE THREAD

**Issue by smakinson** [netlify/netlify-cms#5636]
**Is your feature request related to a problem? Please describe.**

Hugo has a few build options that allow preventing render & list, etc
https://gohugo.io/content-management/build-options/

I want to be able to add this to front matter via an object widget with hidden fields but show nothing to the cms user.
Currently it still shows the object widget.

```
_build:
  render: false
  list: false
```

**Describe the solution you'd like**

I'm thinking one of these options:

1. Add a hidden property to the object widget.
2. The object widget detects if all of its fields are hidden and if so it is also hidden.

**Describe alternatives you've considered**

* A summary on the object widget telling the cms user to ignore it.  😄 
* targeting some class name on the widget with `display: none`.

**Additional context**

**Comment by erezrokah** [comment]
Hi @smakinson, can you share a bit more information on your use case?

If the set of values is fixed and hidden what is the value of having it in the CMS?
Shouldn't this be part of the build configuration?

**Comment by smakinson** [comment]
@erezrokah Unless I'm mistaken, I need to add those properties to each of the content files created for the section. I'm looking for this to be for a single section, but still have those available via `GetPage` in hugo. I had tried ignoring the section in the site config but it did not work out. I'm using the content for something other than a full page so I don't want them rendered as a page or included in a listing.

**Comment by erezrokah** [comment]
> @erezrokah Unless I'm mistaken, I need to add those properties to each of the content files created for the section. I'm looking for this to be for a single section, but still have those available via `GetPage` in hugo. I had tried ignoring the section in the site config but it did not work out. I'm using the content for something other than a full page so I don't want them rendered as a page or included in a listing.

Hi @smakinson, I'm not sure I understand your use case.
Can you share your full `config.yml`, the content you'd like to generate and the UI you expect to be shown/hidden in the CMS?

**Comment by smakinson** [comment]
@erezrokah Config:
```
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]
disableHugoGeneratorInject = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.75.0"

[build]
# Used by PurgeCSS
writeStats = true
```

The collection item:
```
{
      name: 'top_banners',
      label: 'Top Banners',
      label_singular: 'Top Banner',
      folder: 'content/top-banners',
      identifier_field: 'name',
      create: true,
      fields: [
        { label: 'Name', name: 'name', widget: 'string', hint: 'Name is not shown on the front end' },
        {
          label: 'Image',
          name: 'image',
          widget: 'image',
          allow_multiple: false,
          choose_url: false
        },
        { label: 'Link', name: 'link', widget: 'string' },
        {
          label: '_build',
          name: '_build',
          widget: 'object',
          collapsed: true,
          summary: 'Please ignore this section',
          fields: [
            { label: 'render', name: 'render', widget: 'hidden', default: false },
            { label: 'list', name: 'list', widget: 'hidden', default: false }
          ]
        }
      ]
    }
```

The generated frontmatter from one Top Banner:
```
---
name: My Banner
image: uploads/images/my_banner.jpeg
link: https://www.netlify.com
_build:
  render: false
  list: false
---
```

**Comment by erezrokah** [comment]
To clarify `_build` tells Hugo how to render the markdown page?

I think it would be easier to manage those using the `preSave` event https://www.netlifycms.org/docs/beta-features/#registering-to-cms-events

**Comment by smakinson** [comment]
The props under `_build` are telling it not to render or list it at all and I would pull it via `GetPage` manually.

Does `preSave` allow me to identity the collection as it comes through? If so it seems I could potentially add some data there. `entry.name`? 

and?
```
entry.get('data').set({
  _build: {
    render: false
    list: false
  }
});
```

**Comment by erezrokah** [comment]
It should be under `entry.get('collection')` if I remember correctly

**Comment by erezrokah** [comment]
Closing the issue per my comment. I believe the `preSave` event is a better solution for this use case.
Please comment if you have any other questions/the suggestion solution doesn't address the use case.
