### ISSUE TITLE
Login modal window disappears on login 

### ISSUE THREAD

**Issue by nolafs** [netlify/netlify-cms#5655]
# Bug report

**What is the current behavior?**

When clicking the Login with Netlify Identity, the modal window flashes and disappears. The actual netlify-identity-widget is set to display: none.

**What is the expected behavior?**
Should keep the login modal window open.

**Other relevant information:**

I am using Angular with Netlify CMS which could be root of problem. I load the CMS from the CDN. Latest version and angular just renders the CMS on the admin route. Everything else works, once I change  netlify-identity-widget to display: block in the inspector. It seems the switching it display:none is something the CMS is actually doing.

**Comment by madsem** [comment]
@nolafs check out my issue, yours sound similar:

https://github.com/netlify/netlify-cms/issues/5657

Maybe it's the same problem :)

**Comment by nolafs** [comment]
Yeah, apart from the modal window shows less than second for me and I am loading the CMS from the CDN.

**Comment by madsem** [comment]
Yup, you need to install the npm version of identity too, that solves it.

**Comment by nolafs** [comment]
I do load it on the index page. I rather like to avoid initialising the CMS through npm.

```
  <script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>
<!-- src/index.html -->
<script>
  if (window.netlifyIdentity) {
    window.netlifyIdentity.on("init", user => {
      if (!user) {
        window.netlifyIdentity.on("login", () => {
          document.location.href = "/admin/";
        });
      }
    });
  }
</script>
```

**Comment by madsem** [comment]
I see, then I guess you could initialize it in an event listener that is fired when the cms window object exists.

**Comment by nolafs** [comment]
Actually, you might have given me an idea. The CMS is loaded and initialised by an angular component. The identify widget is on the index page to allow the invites to work.  I will try if i can initialise it after the CMS is loaded.

Thanks

**Comment by madsem** [comment]
Yeah cool :) I think as long as it's loaded afterwards it should work!

**Comment by erezrokah** [comment]
Closing this per the discussion in https://github.com/netlify/netlify-cms/issues/5657.

Please comment if this is a separate issue
