### ISSUE TITLE
Automatically remove invisible characters in the Markdown editor

### ISSUE THREAD

**Issue by TheOddler** [netlify/netlify-cms#5658]
**Is your feature request related to a problem? Please describe.**

I made a website for my mom, and she copied some text from Word into the Markdown editor, and managed to add a [line separator](https://www.fileformat.info/info/unicode/char/2028/index.htm) into the text.
This in turn broke Jekyll.

Is there a way to remove invisible characters automatically? If not, could this be added?

**Describe the solution you'd like**

Automatically remove invisible characters in the Markdown editor.

**Describe alternatives you've considered**

Automatically removing those characters with a Jekyll plugin. Though I'd prefer it if they weren't in the source in the first place.

**Comment by erezrokah** [comment]
Hi @TheOddler, I believe you can sanitize fields using the `preSave` event.
See https://www.netlifycms.org/docs/beta-features/#registering-to-cms-events

Closing. Please comment if that doesn't solve your use case

**Comment by TheOddler** [comment]
That worked! I'm now removing all whitespace except space and newline in the preSave event for my body! Works like a charm.

Thanks!
