### ISSUE TITLE
Re-Auth Error Messages for GitHub

### ISSUE THREAD

**Issue by dopry** [netlify/netlify-cms#569]
This is a bit of a bug report and feature request. 

When you get logged out of github there is no error message letting you know to log in. It would be nice if failed http requests triggered some sort of login dialog or notice.

**Comment by tech4him1** [comment]
This should be addressed in #560. It will open a login modal/popup whenever a GitHub request returns a "401 Not Authorized" error.

**Comment by tech4him1** [comment]
This should be addressed in #560.

**Comment by tech4him1** [comment]
@erquhart @neutyp @ziburski I'd like some input on the design, I'm not sure exactly what the sizing should be. Should it adapt to the different sizes of the backend logins? Or just be a standard size (maybe like the media library).
![localhost_8080_](https://user-images.githubusercontent.com/20345941/33861154-859baae6-de99-11e7-807b-302b88246e94.png)

**Comment by neutyp** [comment]
Logo should be about as wide as the button— but overall, this needs a total redesign

**Comment by tech4him1** [comment]
> this needs a total redesign

The main login interface, or just this re-auth addition?

**Comment by neutyp** [comment]
This, as well as the whole login experience 😅 — I don't have specific recommendations at this time. I'd like to carve out some hours to think about and design for this

**Comment by tech4him1** [comment]
@dopry Can you explain how to reproduce this?

**Comment by dopry** [comment]
I think I had left the tab open for days and came back to it. Or reloaded from cache with an expired login.  If you can't reproduce it may be worth closing.

**Comment by tech4him1** [comment]
@erquhart Can you still reproduce this, or is it worth closing (and seeing if we get other reports)?

**Comment by erquhart** [comment]
I'm okay with closing until we have a solid repro case.
