### ISSUE TITLE
Markdown editor fast fixes - 0.5.0 beta

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#575]
This issue can be appended to include various bugs that are found in the new editor. When fast fixes are complete, any remaining issues here can be converted to standalone issues.

#### Inline node processing issues
Inline nodes need to be processed alongside surrounding text, and be subject to surrounding marks, while still having their children processed as required.
- [x] inline images become text in the visual editor
- [x] markdown images within links used to display as images, now they display as text
- [x] marks around links cause the links to become text in the visual editor
- [x] marks applied to inline code, e.g. \*\*\`test\`\*\*, break in the visual editor

#### Escaping issues
- [x] when converting markdown to Remark, don't parse markdown entities within raw html
- [x] when converting Slate to Remark, escape all markdown entities except those in raw html
- [x] markdown images broken by unintelligent escaping because `![` becomes `!\[`
- [x] visual editor doesn't distinguish between newline sequence (literal `\n`) and line break
- [x] html entities are decoded by the visual editor (not just visually, but in the source)
- [x] line break entities (trailing backslash) are visible in visual editor
- [x] markdown entities within code blocks should not be escaped
- [x] markdown entities within raw html should not be escaped
(trailing double space or backslash)
- [x] inactive markdown entities (like a literal asterisk or backslash) are unnecessarily escaped

#### UX issues
- [x] clicking below a trailing shortcode block in the visual editor should set focus in a paragraph
- [x] trim trailing empty paragraphs during remark -> markdown

#### Parsing issues
- [x] standalone URLs in markdown are converted to links in the visual editor
- [x] links containing images break the visual editor when attempting to backspace them
    (addressed here: https://github.com/ianstormtaylor/slate/pull/1202)
- [x] what do we do with footnotes?

#### Related issues
- [x] https://github.com/netlify/netlify-cms/issues/605 - can't edit data files
- [x] breaks sibling field updates when nested in a list as of https://github.com/netlify/netlify-cms/commit/c25a7c4abb76ed3ac041b18b86768fe94b70206f

**Comment by tech4him1** [comment]
After the new editor was added, the `authors.yml` file on the example site (`test-repo` backend) can no longer be saved. The console error is: `Uncaught TypeError: Cannot read property 'reduce' of undefined`.

**Comment by erquhart** [comment]
@tech4him1 thank you, added to the list.
