### ISSUE TITLE
Relation widget does not change when referenced item is deleted

### ISSUE THREAD

**Issue by ConnorGDevelopment** [netlify/netlify-cms#5750]
Context:
I currently have a site where the products are managed in a folder collection (will refer to this as the "Catalog"), this is where the base data for a product is stored. I also have a file collection that includes a file for managing the order in which the products are displayed (will refer to this as the "Display Order"). In the "Display Order", I have a list widget where the list items are relation widgets.

Bug:
When a product is removed from the "Catalog" any relation widgets referencing that deleted product in the "Display Order" are not updated.

Expected Behavior:
There should be some kind of error or behavior for when an item referenced by a relation widget is removed.

Applicable Versions:
 - Framework: Nuxt (Followed the Nuxt guide here https://www.netlifycms.org/docs/nuxt/)
 - Netlify CMS version (copied from console):  netlify-cms-app 2.15.39, netlify-cms-core 2.47.2, netlify-cms 2.10.159
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version: Google Chrome Version 92.0.4515.159
 - Node.JS version: v14.16.0

CMS configuration:
Note: This is an abbreviated version as the file is quite large.
```
---
backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - label: Urn Catalog
    name: urns
    folder: content/catalog/urns
    label_singular: Urn
    create: true
    slug: "{{fields.title}}"
    editor:
    preview: false
    fields:
      - {
          label: Collection Name,
          name: title,
          widget: string,
          hint: Ex. Maus - Earth",
        }

  - label: Data
    name: data
    editor:
      preview: false
      files:
        - label: Urn Display Order
          name: urn-display-order
          file: content/data/urn-display-order.md
          fields:
            - { label: Title, name: title, widget: hidden }
            - label: Urn Display Order
              name: order
              widget: list
              label_singular: "Urn"
              summary: "{{fields.item}}"
              field:
                {
                  label: Urn Collection,
                  name: item,
                  widget: relation,
                  collection: urns,
                  value_field: "{{slug}}",
                  search_fields: [title],
                  display_fields: [title],
                }
---
```
Additional:
I know my setup may be unusual and would appreciate information on how to improve it.

**Comment by erezrokah** [comment]
Hi @ConnorGDevelopment, closing this issue in favor of https://github.com/netlify/netlify-cms/issues/192.

Specifically see https://github.com/netlify/netlify-cms/issues/192#issuecomment-350428804 and https://github.com/netlify/netlify-cms/issues/192#issuecomment-636440531
