### ISSUE TITLE
add fields validation before publish

### ISSUE THREAD

**Issue by trfv** [netlify/netlify-cms#5753]
**Is your feature request related to a problem? Please describe.**

I want to use custom datetime widget only allows future date for publish datetime. Ideally, publish datetime should be future.
With editorial workflow mode, the publish datetime will not always be future when published though it was when its pull request was created.
As above, publish datetime validity will change day by day, so validation before publishing is needed.

**Describe the solution you'd like**

Add this logic to Editor.js to check there are no fields error. like this (l263-l265)
https://github.com/netlify/netlify-cms/blob/a0bcc6a56ae50a0f2ddb33dc9f59fdb4181808d9/packages/netlify-cms-core/src/components/Editor/Editor.js#L257-L268

**Describe alternatives you've considered**

**Additional context**

I created pull request for trial, and I found it was difficult to validate entry fields on publishing from editorial workflow. So I also want to add the workaround that enables us to set publish availability for each of editor and workflow.
https://github.com/netlify/netlify-cms/pull/5751

In addition, in this pull request, I did a small change for on publish that enabled validation for fields before publish.
https://github.com/netlify/netlify-cms/pull/5751/files#diff-d60bcbab79c6239e45e8b6b5f276da8e8e1685a318215b0a34e1a0dc58b6e329R335

**Comment by erezrokah** [comment]
Hi @trfv, sorry I was out for a few days. I'll try to look into it until early next week

**Comment by erezrokah** [comment]
Hi @trfv, what do you think about using the existing [`prePublish`](https://www.netlifycms.org/docs/beta-features/#registering-to-cms-events) event for pre-publish validation?

We could change the code to throw on event handler failure and have the event throw to stop publishing.
See https://github.com/netlify/netlify-cms/blob/972e3074a4c3ee3d1a07f18f5892e18edd954fe1/packages/netlify-cms-core/src/lib/registry.js#L256

It could be considered a breaking change, but that feature is still in Beta.
Also, if we want to be more explicit we could create a specific Error class/code that stops publishing.

**Comment by trfv** [comment]
hi, @erezrokah 

> what do you think about using the existing prePublish event for pre-publish validation?

Yes, I also thought this was another way to accomplish my use case, and I avoided the breaking change... :pray:
I am working on creating new Pull Request. Thank you.

https://github.com/netlify/netlify-cms/pull/5813

**Comment by trfv** [comment]
resolved
