### ISSUE TITLE
Support title fallback when custom override field is not present or empty

### ISSUE THREAD

**Issue by doompadee** [netlify/netlify-cms#5773]
**Is your feature request related to a problem? Please describe.**
I'm using Hugo to create a website and use the "linkTitle" frontmatter variable to provide concise titles for use in menus when necessary. If the variable is not present, Hugo falls back to "title". See https://gohugo.io/content-management/front-matter

**Describe the solution you'd like**
When present, I'd like to have Netlify display the "linkTitle" in summaries and collections trees (i.e. when using "summary" and "identifier_field"), but fallback to using "title" when "linkTitle" is not present.

I would propose to support a fallback to use when the first alternative is not available.

E.g. `summary: {{linkTitle}} | {{title}}`

**Describe alternatives you've considered**
Currently, I would have to duplicate the "title" field for all files, when it should be sufficient to only provide the additional "linkTitle" when it indeed differs from "title". That is tedious and error prone.

**Comment by doompadee** [comment]
Looking at the code, I decided to only add a fallback for the `title` field in collection fields for now. This yields already a sizeable improvement with minimal code changes.

Instead of  of the longish full title

![image](https://user-images.githubusercontent.com/31240866/131625495-96a0e38a-c6f5-4969-b01a-4a9c96814238.png)

It now displays the shorter `linkTitle` (as defined via `identifier_field` defined in config.yml)

![Screenshot 2021-09-01 at 06-46-14 Netlify CMS Development Test](https://user-images.githubusercontent.com/31240866/131625826-d0efea22-179e-425a-bbec-12d3448816c2.png)

Please let me know if you think this is acceptable before I submit a pr. Thanks.

**Comment by erezrokah** [comment]
> I decided to only add a fallback for the `title` field in collection trees for now.

What were the other considerations? I thought this was only about the collection view.
What are the other places we should be having this behavior?

**Comment by doompadee** [comment]
> What were the other considerations?

The summary on the right, but I can live with the current behavior for that. For the collection tree on the left, the desired change is crucial to me. I would therefore vote for having this rather simple change integrated now, instead of looking for a more complex solution that might be rejected because it does not apply to a majority of users.

**Comment by erezrokah** [comment]
So the sidebar and the entries list could display a different summary?

**Comment by doompadee** [comment]
You can already customize the summary, but when the field is not present or empty, netlify currently displays an empty string for summaries, when I would prefer a fallback.

But as I said, this aspect is less important for me and as the implementation would get more complex, I'm fine to concentrate on the collection sidebar entries. As shown in the screenshots above, this change can have a big impact on the tree (I'm using the nested depth feature obviously, not sure how well received it already is, I love it apart from the title defect).

**Comment by erezrokah** [comment]
Cool, I think you can open a PR so I can see this live
