### ISSUE TITLE
Use an alternative to `ref` for the GitLab backend

### ISSUE THREAD

**Issue by wjharney** [netlify/netlify-cms#5774]
**Is your feature request related to a problem? Please describe.**
The ClearURLs browser extension strips the `ref` query parameter from URLs. The GitLab backend relies on the `ref` query parameter to function properly, and posts cannot be changed without it.

**Describe the solution you'd like**
The APIs for the GitLab backend should use an alternative query parameter (perhaps `reference`), to avoid being removed by ClearURLs or other tracker blockers.

**Describe alternatives you've considered**
I have also filed bugs with [ClearURLs](https://github.com/ClearURLs/Addon/issues/135) and [GitLab](https://gitlab.com/gitlab-org/gitlab/-/issues/339688) to address the issue.

**Additional context**
* ClearURLs has 80k users in [Chrome](https://chrome.google.com/webstore/detail/clearurls/lckanjgmijmafbedllaakclkaicjfmnk/), and 66k in [Firefox](https://addons.mozilla.org/en-US/firefox/addon/clearurls/). It is also officially recommended by Mozilla.
* Stripping `ref` is a fairly basic tracker protection. I don't know of any extensions other than ClearURLs that do it, but I suspect that it is not the only one.

**Comment by erezrokah** [comment]
Hi @wjharney, this doesn't seem like an issue with Netlify CMS and impacts other sites as well (not just GitLab). See https://github.com/ClearURLs/Addon/issues/93.

My expectation is that ClearURLs should be smart enough not to remove all `ref` parameters, but only those that are used for tracking, or at least provide a way to opt out from certain rules for specific hosts.

Even if we find a solution to `ref` this might come up for other existing parameters, or even new ones when we add new features.

Closing the issue. Please comment if you have more questions/feedback.
