### ISSUE TITLE
Document the "collapsed" parameter for "registerEditorComponent"

### ISSUE THREAD

**Issue by doompadee** [netlify/netlify-cms#5779]
**Describe the bug**
https://www.netlifycms.org/docs/custom-widgets/#registereditorcomponent does not document the optional `collapsed` parameter.

**To Reproduce**
Visit said documentation page and check whether the parameter is documented.

**Expected behavior**
The `collapsed` parameter should be documented.

**Screenshots**

![Screenshot 2021-09-04 at 12-47-10 Creating Custom Widgets Netlify CMS Open-Source Content Management System](https://user-images.githubusercontent.com/31240866/132095163-ab7fb6c2-8401-48ce-af0d-5aa31e68fdd5.png)

**Additional context**

Pages with custom editor components can get overwhelming pretty fast. I therefore prefer to have the objects collapsed initially to provide a better experience. Unfortunately, I had to study the source code and do some experimenting to learn about the `collapsed` parameter, but I think this parameter might be useful to others and should be documented.

**Comment by iChenLei** [comment]
I think this issue can be closed ? @erezrokah
