### ISSUE TITLE
TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by sandro-git** [netlify/netlify-cms#5781]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.160`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36`

**CMS configuration**
```
backend:
  name: git-gateway
  branch: main
media_folder: static/img
public_folder: /img
collections:
  - name: jeux
    label: Jeux
    folder: content/jeux
    format: frontmatter
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - label: Titre
        name: titre
        widget: string
      - label: Date de Pubication
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: string
      - label: Corps
        name: corps
        widget: markdown
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - titre
      - date
      - commit_author
      - description
    view_filters: []
    view_groups: []
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
isFetching: false
error: null

```

**Additional context**

**Comment by bytrangle** [comment]
Hello @sandro-git . Can you provide the steps of actions that lead to the TypeError issue? There have been three report of this issue in the past week, so it's probably not trivial. The more information you give, the faster it takes for our amazing contributors to fix it.
