### ISSUE TITLE
Use keyboard shortcuts to insert bullet point lists in the Rich Text editor

### ISSUE THREAD

**Issue by taineriley1** [netlify/netlify-cms#5794]
**Is your feature request related to a problem? Please describe.**

In the markdown editor, you can insert bullet point lists using '* ' (asterisk-space) or '- ' (dash-space). However, this is not available in the rich text mode. Users have to click the bullet points formatting button at the top of the widget to add the formatting.

The rich text editor allows other keyboard shortcuts such as Ctrl+B for bold and Ctrl+I for italics. Common applications with similar functionality like Microsoft Word convert these combinations into bullet point lists. It would be great if the rich text editor also had this functionality.

**Describe the solution you'd like**

Add functionality to the rich text editor to convert '* ' and '- ' into a bullet point list.

**Describe alternatives you've considered**

**Additional context**

See this video demo: https://www.youtube.com/watch?v=4hdOAEMWRw0

**Comment by abxhr** [comment]
I'll be happy to work on this, but I'm not sure how this could be achieved.

**Comment by pawan43563** [comment]
Can you assign me? Would love to contribute!

**Comment by erezrokah** [comment]
Hi all and sorry for the late reply. Not sure who's still ready to pick this up, but https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-widget-markdown/src/MarkdownControl/VisualEditor.js would be a good place to start.

**Comment by nipeshkc7** [comment]
I'd love to work on this one if not already taken.
