### ISSUE TITLE
i18n issue when the number of locale is more than 8

### ISSUE THREAD

**Issue by kenkoy** [netlify/netlify-cms#5846]
Good day everyone.

May I ask if you can spare some time to validate my concern and perhaps guide me on the correct solution.

Post gets duplicated when the number of locale used is more than 8. Only 1 of the 2 posts is clickable and loadable. The incorrect one generates a wrong slug, instead of just the slug it appends the locale used (slug.locale) which is not existing and so it failed loading the post.

Netlify CMS version: 2.15.44
Backend: GitLab
Feature used: i18n with multiple_files as structure

<img width="563" alt="issue_i18n" src="https://user-images.githubusercontent.com/4005294/135009857-cf9fd69b-df9b-43da-b544-a015d2b3add0.png">

**Comment by erezrokah** [comment]
Hi @kenkoy, do you mind following the bug report per https://github.com/netlify/netlify-cms/issues/new?assignees=&labels=type%3A+bug&template=bug_report.md&title=Please+replace+with+a+clear+and+descriptive+title?

It's hard to reproduce your issue at the moment.
