### ISSUE TITLE
Widget number return a string

### ISSUE THREAD

**Issue by rzecchini** [netlify/netlify-cms#587]
**- Do you want to request a *feature* or report a *bug*?**
bug
**- What is the current behavior?**
I type a number in a number widget but the output I get is a string
**- If the current behavior is a bug, please provide the steps to reproduce.**
configure a collection with a number field, access to the /admin interface, create an entry, inspect/check the entry in github
**- What is the expected behavior?**
widget number should return a number
**- Please mention your node.js, and operating system version.**
setup: jekyll, github, netlify
![image](https://user-images.githubusercontent.com/2392233/30217976-0db34f8c-94b8-11e7-99fd-f9e2ace4e71b.png)

**Comment by tech4him1** [comment]
This was fixed in #541. You can now set the NumberControl's `valueType` to be 'string', 'int', or 'float'.
