### ISSUE TITLE
Delete flag in configuration

### ISSUE THREAD

**Issue by bdot** [netlify/netlify-cms#593]
**- Do you want to request a *feature* or report a *bug*?**

Feature request

**- What is the current behavior?**

Currently an user can delete any file that's available via CMS. If you have important files like settings.json and home.md, you may want to restrict  deletion action to minimise the chaos.

**- What is the expected behavior?**

Ideally a *delete* on/off flag in config.yml at file/section level.

**Comment by verythorough** [comment]
Was just coming here to file this! I think this field would make a great partner to the `create` field.
