### ISSUE TITLE
Subdomain like netlify help needed 

### ISSUE THREAD

**Issue by Chetan11-dev** [netlify/netlify-cms#5958]
Greetings Netlify Developers, I am solving a problem similar to what you have solved and I thought you  would may like to help.
I want to dynamically create subdomain sites such as "user1.example.com", "user2.example.com" and serve static html and css based on subdomain. For a real world example blogger.com servers html and css for different users on blogspot domain link https://althouse.blogspot.com/. I want to do exactly the same thing like blogger.com does.

Questions:

    What code do I need to write for determining subdomain (using js). For example user1.example.com the subdomain is user1.
    Should I store user html, css in s3 by creating folders such as user1/, user2/.

**Comment by talves** [comment]
Hi @Chetan11-dev this repo is intended for Netlify CMS (the content management system) related issues.

For Netlify build related issues I suggest to reach out in the forums: https://answers.netlify.com/

Closing the issue, and please comment if you have any other questions.

**Comment by Chetan11-dev** [comment]
Actually there is nothing wrong with netlify. I needed help for implementing a feature which netlify has. Thought that a netlify backend developer could help. See if is it possible.
