### ISSUE TITLE
no prompt to create a password

### ISSUE THREAD

**Issue by reydelshit** [netlify/netlify-cms#5968]
I'm trying to create an account for my cms website. I used the template Next.js Blog Template. So then, I followed the documentation [https://www.netlifycms.org/docs/start-with-a-template/] then I waited until the deployment is complete.  After that, I go visit my email and got received this from my email : 

1. You have been invited
  You have been invited to create a user on _http://competent-tesla-bc9fa0.netlify.app._ Follow this link to accept the invite:
_Accept the invite_

2. So then, I clicked the accept the invite and got redirected to the page _[http://competent-tesla-bc9fa0.netlify.app]_ . However, I'm expecting that there would be a prompt to appear in order to set the password.

3. I have been waiting for it for minutes and kept repeating/retrying the steps and still, the prompt didn't appear. I also used different browsers like chrome and firefox, my main is brave.

**Expected behavior**

I expected that there would be a prompt to appear in order for me to set my password but unfortunately, there's nothing

**Screenshots**

1. I click this
![image](https://user-images.githubusercontent.com/40355669/140774517-d640872f-1ce2-40e1-be6e-db60bcf45d86.png)

2.  You would see the time differences below. None of the prompts is appearing 
![image](https://user-images.githubusercontent.com/40355669/140775135-a7f0bf18-42a9-49c2-9336-b66f508a3d99.png)

Ps. I'm new to the industry so please bare with my explanation

**Comment by jlouiss** [comment]
The same thing happens using the password reset link from https://<name>.netlify.app/admin

**Comment by jlouiss** [comment]
@reydelshit as per #5109 this is not an issue with netlify-cms - to fix this just add a `/admin` before the `#token=xyz` in the URL.
#5109 also has instructions on how to fix this
