### ISSUE TITLE
Build a more organized outline for docs

### ISSUE THREAD

**Issue by verythorough** [netlify/netlify-cms#598]
The current docs organization was hastily pulled together from what was available in the repo at the time, plus minor updates to content. 

To aid discoverability and reduce repetition, I'd like to re-organize the docs files. We can start by discussing here and developing an outline, and then start implementing.

**Comment by erquhart** [comment]
This should be treated as a story with a set of related issues for the various underlying efforts.

**Comment by verythorough** [comment]
Agreed! The purpose of this issue was more for discussion about the outline as a whole, before breaking it up into smaller tasks and tying them to related code/design/etc. efforts. It's more about the organization than as a starting point for the actual writing.

However, since there's been no discussion, I guess I'll just start breaking it up.

**Comment by verythorough** [comment]
I've broken out the major implementation sections into separate issues. PRs for each of these should include links added to the appropriate section of the Quick Start, because at the moment, it's our main intro. When all of these sections are ready, we can create the Implementation Intro section of the outline, and adapt the Quick Start/Test Drive content to match that outline.

Here's a handy list of the issues to complete for this first round:

- [ ] Backends & Authentication (**high priority**) #600 
- [ ] Widgets #619 
- [ ] Collections #679 
- [ ] Configuration #685 
- [ ] Installation #731
