### ISSUE TITLE
Form action is showing default "thank-you" page when "action" path is set

### ISSUE THREAD

**Issue by breathe-org** [netlify/netlify-cms#6036]
**Describe the bug**
I've added an `action="/success"` to the netlify form but when I submit a form it still shows the `thank-you` message. However the url is `mywebsite.com/success`. Somehow the link is correct but the action isn't working?

**To Reproduce**
1. Add an `action="/success"`
2. Ensure you have a vue file for this page and that nuxt generates it on build.
3. Submit a form
4. See the default `thank-you` message, but the path should include `/success`

**Expected behavior**
I'm expecting it to navigate to the `/success` page that I've created.

**Screenshots**
Thank you message:
<img width="466" alt="Screenshot 2021-12-08 at 11 34 08" src="https://user-images.githubusercontent.com/92378003/145193466-7b204d72-1780-49ac-9c40-91d6d77afee8.png">
Path: 
<img width="71" alt="Screenshot 2021-12-08 at 11 33 37" src="https://user-images.githubusercontent.com/92378003/145193485-9877d454-a695-49a5-9b4f-1c833a4c1e0d.png">

**Applicable Versions:**

- netlify-cms-app 2.15.60
- netlify-cms-core 2.54.1
- netlify-cms 2.10.180
- nuxt 2.15.8
- provider: github
- Node.JS: v12.22.1

Relevant files:
**index.html**
```
<form name="newsletterForm" data-netlify="true" netlify-honeypot="bot-field" hidden>
    <input type="email" name="email" />
  </form>
```

**form.vue**
```
<form name="newsletterForm" method="POST" :action="successfulSubmissionLink" data-netlify="true">
        <input type="hidden" name="form-name" value="newsletterForm" />
        <input
            type="email"
            name="email"
            :placeholder="placeholderText"
            required
        />
        <button type="submit">{{ buttonText }}</button>
    </form>

<script>
export default {
    props: {
        buttonText: { type: String, required: true },
        placeholderText: { type: String, default: '' },
        successfulSubmissionLink: { type: String, default: '/' }
    }
}
</script>
```
- I'm fetching the action link from the CMS, and it is being passed as a prop to my `form.vue`. When I inspect the element, in the action I see the correct path.
<img width="437" alt="Screenshot 2021-12-08 at 11 43 34" src="https://user-images.githubusercontent.com/92378003/145194893-6a771c34-39c1-4d07-9810-217bee4a3f72.png">
- The form data is also correctly arriving in netlify.

Thank you, let me know if you need anything else.

**Comment by erezrokah** [comment]
Hello @breathe-org, this repo is intended for issues related to Netlify CMS (not Netlify the platform).

The best place to post this issue about Netlify Forms is our [support forums](https://answers.netlify.com/). Do you mind posting it there?

>I'm fetching the action link from the CMS, and it is being passed as a prop to my form.vue. When I inspect the element, in the action I see the correct path.

I'm not sure how this is related to Netlify CMS.

Since this seems like a Netlify Forms issue, closing it. Please comment if I got this wrong

**Comment by breathe-org** [comment]
You're right, my mistake, will post it there: https://answers.netlify.com/t/form-action-is-showing-default-thank-you-page-when-action-path-is-set/48477
