### ISSUE TITLE
Switch to a smaller slugifier.

### ISSUE THREAD

**Issue by tech4him1** [netlify/netlify-cms#607]
Currently, we use the `slug` module for creating URL slugs from titles. The problem is that `slug` bundles an entire Unicode lookup table, and that gets bundled into our distributable. it currently accounts for 30.5% of our bundle size. This should probably be changed to something a little lighter weight.

Related to #328.

**Comment by tech4him1** [comment]
@biilmann suggested using `urlize` from `lib/urlHelper`:
https://github.com/netlify/netlify-cms/blob/04ae5051ceafc0c600eace5e88671b2766f81fe6/src/lib/urlHelper.js#L15-L20

**Comment by tech4him1** [comment]
The `slugify` package is a port of `slug` without the Unicode lookup table.

**Comment by erquhart** [comment]
If urlize can indeed do the trick, we should use it.

**Comment by tech4him1** [comment]
Possible slugifier tests:
[urlize.spec.js](https://github.com/netlify/make-wp-epic/blob/master/__test__/urlize.spec.js)
https://github.com/netlify/netlify-cms/issues/501#issue-245930865
https://github.com/netlify/netlify-cms/pull/414#issue-227276693

**Comment by tech4him1** [comment]
So here is what WordPress does slugification:
1. Accented letters get the accents removed: [remove_accents()](https://developer.wordpress.org/reference/functions/remove_accents/).
2. - All other unsafe characters (Japanese, Chinese) get URL-encoded. Newer browsers will convert them on the fly, so to the user they still appear as normal characters.
   - The other option here is just to remove the unsafe characters.

**Comment by erquhart** [comment]
> Newer browsers will convert them on the fly, so to the user they still appear as normal characters.

Not sure when this conversion would occur - would the resulting filename have these characters encoded?

**Comment by tech4him1** [comment]
> Not sure when this conversion would occur - would the resulting filename have these characters encoded?
@erquhart Yes, in almost every case they would have to.

**Comment by tech4him1** [comment]
Just testing -- both DatoCMS and Forestry strip unsafe chars from the slug.

**Comment by erquhart** [comment]
If it's par for the course and simpler, let's do it.

**Comment by tech4him1** [comment]
So we have three options:
1. Stay with the current `slug` package, just tell it not to worry about converting emojis (this would remove the hash table).
2. Switch to the `slugify` package, it is pretty much the same expect more maintained and without hash table.
3. Use the `urlize` function that Matt ported, use the `remove-accents` package on top.

**Comment by tech4him1** [comment]
I also think we should throw an error if the slug is going to be blank.

**Comment by tech4him1** [comment]
@biilmann @erquhart I'm trying to understand why the urlize function seems to leave some reserved characters in the URL. The list of RFC3986 unreserved characters is `\w-._~`, but urlize uses `\w./\_#+-`. Obviously those need to be kept for the entire URLs, but not for slugification. Is there something that I am missing here?
