### ISSUE TITLE
Image widget: suggestions for allow_multiple == true (Cloudinary)

### ISSUE THREAD

**Issue by martinjagodic** [netlify/netlify-cms#6087]
This is how an image widget with multiple entries looks now:

initial
![Screenshot 2021-12-29 at 08 55 39](https://user-images.githubusercontent.com/42938138/147639754-114aeb18-9a0a-45dd-8533-f7aab6c84e87.png)

populated
![Screenshot 2021-12-28 at 15 33 07](https://user-images.githubusercontent.com/42938138/147576685-2e7ba90b-92e6-49ad-9cdb-e2f3e2af19c8.png)

**Problem**
1. In frontmatter, it is an array of strings (URLs), but Replace with URL replaces it with a single string. If you click it and cancel, it will still clear all previous entries.
2. Text on buttons is not in sync with what they really do
3. The only editing option right now is to replace all images or reorder, which works ok but is not enough.

**Proposed solution**
1. remove the general "Insert from URL" / "Replace with URL" button. If it must exist, let it be for each image
2. Add a delete button on each image
3. Rename buttons:
    - "Chose an image" to "Choose images"
    - "Choose different image" to "Edit images"
    - "Remove image" to "Remove all images"
4. Pre-populate the media library widget with existing values

**Alternatives**
Use a list of images with `multiple: false`. We use that now but it's a very slow editing experience.

**Additional context**
I was playing around a little to fix nr. 4 for Cloudinary but I didn't find an option to send values with `openMediaLibrary()` method. Even if this can't be achieved, points 1 - 4 would be great. I am ready to work on this, but I would like to hear some opinions and suggestions first.

**Comment by martinjagodic** [comment]
Dear maintainers, do you have any comments?

**Comment by erezrokah** [comment]
Hi @martinjagodic, thank you for the proposal and sorry for the delayed response.

Will it make sense to remove all buttons and use a single "open media library" button?
It probably makes sense to give the Cloudinary widget full control of the UI.

>remove the general "Insert from URL" / "Replace with URL" button. If it must exist, let it be for each image

I agree this seems redundant for the Cloudinary use case

The rest of the proposal makes sense to me as well.

**Comment by martinjagodic** [comment]
> Will it make sense to remove all buttons and use a single "open media library" button?

Good idea!

Hopefully, we will start working on this next week.

**Comment by demshy** [comment]
Hi, I have started working on this. 

Our idea is to add replace & remove buttons to every item in the list. Remove is quite trivial while replace would open the media library with select single file option.
As for the global buttons - "choose different image" would be changed to "add a new image" and "remove image" would be changed to "remove all images".
