### ISSUE TITLE
Control editorial workflow status by commenting on bitbucket PRs

### ISSUE THREAD

**Issue by calebwilson706** [netlify/netlify-cms#6139]
We would like to be able to update the editorial workflow status of a post from inside bitbucket by commenting `netlify-cms/pending_publish`

When you comment `netlify-cms/draft` on the PR it moves the changes to draft however this does not work for the other 2 statuses

For now we have to review content inside bitbucket then open the cms to change the status of the post

**Comment by erezrokah** [comment]
Hi @calebwilson706, can you please follow the [issue template](https://github.com/netlify/netlify-cms/issues/new/choose), either the bug report or feature request.

That ensures we have enough information to understand it.

**Comment by calebwilson706** [comment]
Sorry i didn't really have any info at the time, did some digging and created a new issue https://github.com/netlify/netlify-cms/issues/6140
