### ISSUE TITLE
Issue with trailing slash on the _posts path

### ISSUE THREAD

**Issue by alteducation** [netlify/netlify-cms#615]
**- Do you want to request a *feature* or report a *bug*?**
       Bug Report

**- What is the current behavior?**
      Content Manager Admin Wont Open Posts is the Post Path has A trailing Slash

**- If the current behavior is a bug, please provide the steps to reproduce.**
      Set Post Path to '_posts/' in the config.yml file and open the posts/collections from the admin UI

**- What is the expected behavior?**
      When clicked on an error message gets displayed "file not found"

**- Please mention your node.js, and operating system version.**

**Comment by tech4him1** [comment]
Also see https://gitter.im/netlify/NetlifyCMS?at=59bd2210177fb9fe7eca9bf8

**Comment by tech4him1** [comment]
Here is the relevant code: https://github.com/netlify/netlify-cms/blob/caa5c69522e5446e8677775d7ea25fdbb0e2b36e/src/reducers/collections.js#L44-L46 The problem is that the folder and a slash is added directly to the string without checking whether the folder name already contains a trailing slash.

**Comment by tech4him1** [comment]
We should just be able to do:
```js
collection.get('folder').trim().replace(/\/$/, '')
```
