### ISSUE TITLE
Saving Collection items fails if existing front matter is faulty

### ISSUE THREAD

**Issue by rriemann** [netlify/netlify-cms#624]
**- Do you want to request a *feature* or report a *bug*?**

This is a bug. I think Netlify should be robust enough to cope with faulty front matter.

**- What is the current behavior?**

I try to edit a file as part of a collection with the following content:

```md
---
slug: meu-glasgow-2017
title: MEU Glasgow 2017
partner-slug: beta-scotland
conference: meu-glasgow
mail: president@meu.scot
website: http://www.meu.scot
year: 2017
begin: 2017-10-19
end: 2017-10-24
participants: ca. 100
town: Glasgow
country: UK
location: University of Strathclyde
geo: 48.59746,7.76780
excerpt: Paris Agreement and fisheries

```

As you can notice, the last dash-dash-dash (`---`) is missing.

When I click save, nothing happens and the following error appears in the console:

> Netlify CMS version 0.4.6
> /admin/#/collections/conference/entries/meu-glasgow-2017:1 Uncaught (in promise) undefined

When I install a pause on caught exceptions, I find that the error occurs here in the last line:

```js
            return function(a, t) {
                var n = t()
                  , r = n.entryDraft;
                if (!r.get("fieldsErrors").isEmpty())
                    return Promise.reject();
```

**- If the current behavior is a bug, please provide the steps to reproduce.**

I believe it can be reproduced by removing from any post the `---`.

**- What is the expected behavior?**

It corrects the front matter by adding the dashes and saves.

**Comment by rriemann** [comment]
I have to check the reproducability. Things are weird here and I ran into other issues, to.

**Comment by tech4him1** [comment]
@rriemann Is this still a problem that you want solved?

**Comment by rriemann** [comment]
I cannot reproduce the issue anymore. A corrupt front matter gets repaired.

**Comment by tech4him1** [comment]
@rriemann We switched the front-matter parser recently, so that might be why. Glad it is working for you!
