### ISSUE TITLE
Double Dash in a "INTRO BLURB" Field Is Not Expanded (Feature)

### ISSUE THREAD

**Issue by ilyaigpetrov** [netlify/netlify-cms#625]
![Screenshot of non-expanding double dash](https://user-images.githubusercontent.com/1090811/30747620-3f7f3dfe-9fc7-11e7-9b93-8a35d53e23b0.png)

**- Do you want to request a *feature* or report a *bug*?**

Feature, I guess

**- What is the current behavior?**

Double dash (--) is expanded/replaced only in editor of BODY, but not inside editor of INTRO BLURB.

**- If the current behavior is a bug, please provide the steps to reproduce.**

Create new post and try to fill the fields accordingly.

**- What is the expected behavior?**

Double dash should be expanded in editors of both fields (and in __title editor__ too!).

**- Please mention your node.js, and operating system version.**

One that is used by netlify when currently deployed.

**Comment by tech4him1** [comment]
@ilyaigpetrov The reason for this is that the body is a rich text editor, while the intro blurb is set to plain text. If you want the intro blurb to have the same behavior, you can set its type to `markdown`.

**Comment by Benaiah** [comment]
I don't think we should be doing _any_ processing on the output of a plain text control, so I'm going to go ahead and close this. @ilyaigpetrov, @tech4him1's suggestion to set `type: markdown` on that widget in the `config.yml` will get you the behavior you want. Feel free to ask here or [on Gitter](https://gitter.im/NetlifyCMS) if you need any further pointers on how to do that.
