### ISSUE TITLE
Pagination next button doesn't work as expected

### ISSUE THREAD

**Issue by kerimcet** [netlify/netlify-cms#6266]
**Describe the bug**
Pagination next page button doesn't work as expected on tagged posts page. 

**To Reproduce**
1. Go to '[Netlify's Blog, tagged posts](https://www.netlify.com/blog/tags/React/)'
2. Scroll down to 'pagination'
3. Click on 'next page' button
4. See error (it redirects you to '/page/1')

**Expected behavior**
Next page button should redirect user to the second page if current page is the first one.

**Applicable Versions:**
 - Netlify CMS version: -
 - Git provider: -
 - OS: MacOS
 - Browser version: Chrome 98.0.4758.109

**Additional Context:**

Also if you are on second page, then click on previous page button, it redirects you to `/blog/tags/React/` (not `/blog/tags/React/page/1`)

But in this [Netlify's Blog page](https://www.netlify.com/blog/), that button works as expected.

**Comment by erezrokah** [comment]
Thanks @kerimcet, as this repo is intended to report issues on Netlify CMS, I'll close this issue.
I'll pass on your useful report to the team that handles the Netlify blog.
