### ISSUE TITLE
function "now" not defined

### ISSUE THREAD

**Issue by sogen** [netlify/netlify-cms#627]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Get error: 
function "now" not defined
Current theme does not support Hugo version 0.18.1. Minimum version required is 0.2
Failed at the victor-hugo@1.0.0 start script 'gulp server'.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Install theme **Crab**

**- What is the expected behavior?**
NPM START runs

**- Please mention your node.js, and operating system version.**
OSX Sierra, 
node v6.9.4 
npm 3.10.10

**Comment by tech4him1** [comment]
@sogen This doesn't sound like a CMS-related issue. Please see the [Victor Hugo](https://github.com/netlify/victor-hugo) or [Crab theme](https://github.com/thomasheller/crab) repos.
