### ISSUE TITLE
在Windows 11使用Chrome/Edge/Firefox时，使用微软拼音输入法于“Body”文本编辑框输入中文会出现光标飘移错位等现象等两个问题

### ISSUE THREAD

**Issue by Songyon** [netlify/netlify-cms#6283]
问题一、在Windows 11使用Chrome/Edge/Firefox时，使用微软拼音输入法于“Body”文本编辑框输入中文时会出现光标飘移错位等现象。

终端：Windows 11

浏览器：Firefox/Edge/Chrome

输入法：微软拼音输入法

问题二、手机端使用Chrome/Edge/Firefox编辑“Body”文本编辑框时几乎无法输入任何文字。

终端：MIUI 13（Android 12）

浏览器：Firefox/Edge/Chrome

输入法：百度输入法Android

请原谅我使用中文，因为我英语很菜😭

> The following text was translated from Chinese to English by "DeepL".

Problem 1: When using Chrome/Edge/Firefox in Windows 11, the cursor drifts and is misaligned when using Microsoft Pinyin Input Method to input Chinese in the "Body" text editing box.

Terminal: Windows 11

Browser: Firefox/Edge/Chrome

Input method: Microsoft Pinyin Input Method

Problem 2: When using Chrome/Edge/Firefox to edit the "Body" text editing box on the cell phone, it is almost impossible to enter any text.

Terminal: MIUI 13 (Android 12)

Browser: Firefox/Edge/Chrome

Input method: Baidu Input Method for Android

Please forgive me for using Chinese, because I'm not good at English 😭

Translated with www.DeepL.com/Translator (free version)

**Comment by erezrokah** [comment]
Hi @Songyon, I'm unable to understand the issue you reported.

I understand there's a language barrier, but can you follow the structure in https://github.com/netlify/netlify-cms/issues/new?assignees=&labels=type%3A+bug&template=bug_report.md&title=Please+replace+with+a+clear+and+descriptive+title?
