### ISSUE TITLE
Basic image upload

### ISSUE THREAD

**Issue by phae** [netlify/netlify-cms#63]
A user needs to
- be able to easily upload an image to an article
- specify where in the article the image should appear

Acceptance criteria
- [ ] User can click "upload", navigate to an image file (png, gif or jpg), and it should be included by default at the top of the article
- [ ] File browser should not show non-image formats
- [ ] User can move the image up or down in the article

For first pass, it's fine that the image is exactly the size that was uploaded (scaled to fit 100% inside the container element).  More detailed controls/potions will come in a later ticket.

**Comment by cedricdelpoux** [comment]
It could be great to add an image directly from the markdown editor

**Comment by okonet** [comment]
It's implemented but not yet merged. Check out https://github.com/netlify/netlify-cms/pull/82

**Comment by webriqdemo** [comment]
Great ! thank you very much

**Comment by cedricdelpoux** [comment]
Great ! Thank you
