### ISSUE TITLE
Entries cannot be deleted in the editorial workflow

### ISSUE THREAD

**Issue by zachylimwl** [netlify/netlify-cms#632]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
There is only a save and cancel button shown after clicking the publishes page on the CMS ui

**- If the current behavior is a bug, please provide the steps to reproduce.**
Create a page through the editorial workflow

**- What is the expected behavior?**
There should be a delete button instead of just save and cancel

**- Please mention your node.js, and operating system version.**
For my local computer, node version is v8.4.0, os version is macOS Sierra version 10.12.6

![screen shot 2017-09-25 at 5 20 35 pm](https://user-images.githubusercontent.com/15140377/30836915-2c07371c-a216-11e7-9c3b-d4a594fa33fb.png)

**Comment by tech4him1** [comment]
@erquhart @Benaiah How would this even work?

**Comment by Benaiah** [comment]
Deletion is currently disabled in the editorial workflow; this is a known issue. I've done some work towards this, but there's some issues with how GitHub's API handles deletion which make me worry about breakage on large repos. I'll go ahead and leave this issue open until this functionality is merged.

**Comment by erquhart** [comment]
Solved in 1.0! 🎉
