### ISSUE TITLE
Delete does not work if config is pointing to a branch other than master

### ISSUE THREAD

**Issue by VitaminDAgency** [netlify/netlify-cms#635]
**- Do you want to request a *feature* or report a *bug*?**
Report a Bug

**- What is the current behavior?**
When the api does a GET to show the collection or look at a specific item in the collection from github it includes a `ref` GET param specifying which branch to use for the request, but the delete workflow does not specify this GET param. The resulting behavior is you can only delete content on the master branch and if you have a multi branch configuration you will mistakenly have content deleted on master instead of the branch you are working on or if it does not exist on master then an error will be surfaced.

**- If the current behavior is a bug, please provide the steps to reproduce.**
To reproduce, setup the config pointing to a non master branch. 

```
backend:
    name: github
    repo: # Path to your Github repository
    branch: develop
```
Then in the CMS
1. Create a new piece of content 
2. Click to edit it
3. Delete it

You will see an error message and network logs will show a request with a 404 to the master branch verifying that it cannot verify the content is present. Deleting will not proceed. If that content was on master it would be deleted.

**- What is the expected behavior?**
The expected behavior is that a `ref=develop` GET param would be passed for the GET confirmation and subsequent deletion.

**- Please mention your node.js, and operating system version.**
This is the case running on Netlify production

**Comment by Benaiah** [comment]
@VitaminDAgency are you running off a released version? This should be fixed as of #604 being merged, but the fix hasn't been released yet.

**Comment by VitaminDAgency** [comment]
I am running on release 0.4. I searched open tickets. I should have search all tickets. That is my oversight. My apologies.

**Comment by Benaiah** [comment]
@VitaminDAgency no problem, thanks for filing an issue when you ran into a bug!
