### ISSUE TITLE
Contributing - Forking

### ISSUE THREAD

**Issue by michael-proulx** [netlify/netlify-cms#6445]
**Describe the bug**
I would like to contribute to the project, but it's not possible because, we can't fork the repo anymore, I did ask on the Slack Channel but I didn't have any answer about that issue.

**To Reproduce**
Click on `fork` in the neltify-cms repo or go here: https://github.com/netlify/netlify-cms/fork.
You'll be prompt with no more forks can be created. View existing forks.

**Screenshots**
![image](https://user-images.githubusercontent.com/23478544/164719727-6e9a620b-225a-4795-9b37-0d9a48d7a1f9.png)

Here is a small snippet
https://user-images.githubusercontent.com/23478544/164720062-25c9afea-6a4a-4616-8833-560acc6aaa03.mp4

**Comment by Aholicknight** [comment]
not related to this repo but this issue is appearing on other GitHub repos as well

![image](https://user-images.githubusercontent.com/7843719/165151714-0a3a7b83-9b2a-4e6a-a378-40799d61ffd2.png)

as an example, I tried to copy the ShareX repo, and it won't let me...maybe we both reached a fork limit (if there is such thing)?

**Comment by michael-proulx** [comment]
@Aholicknight It's weird now I have a fork under my own repo out of nowhere...
I guess it was related to GitHub
![image](https://user-images.githubusercontent.com/23478544/165157277-c4db1639-9455-45bc-8060-6a73e0d5c0b2.png)

**Comment by Aholicknight** [comment]
> @Aholicknight It's weird now I have a fork under my own repo out of nowhere... I guess it was related to GitHub ![image](https://user-images.githubusercontent.com/23478544/165157277-c4db1639-9455-45bc-8060-6a73e0d5c0b2.png)

@michael-proulx Github support told me the same thing, for some reason it did not tell me I had an existing fork created. 

![image](https://user-images.githubusercontent.com/7843719/165180951-25e6fdf6-e053-4357-ba80-c8581313161f.png)
