### ISSUE TITLE
All entries in the CMS disappeared

### ISSUE THREAD

**Issue by hkrank** [netlify/netlify-cms#6474]
**Describe the bug**
Shown message in the CMS.
`Failed to load entry: TypeError: Cannot read property 'split' of null`

**To Reproduce**
All my entries disappeared. No content shown in the CMS.

**Screenshots**

<img width="801" alt="69134256-7d8e6b80-0ab7-11ea-99fa-fdb9f07bb21c" src="https://user-images.githubusercontent.com/1030255/169004486-72709fd6-f036-4943-9c76-e6d1e74800e7.png">
<img width="1371" alt="69134140-559f0800-0ab7-11ea-8137-e7cc3ead5df8" src="https://user-images.githubusercontent.com/1030255/169004520-db643958-7f7b-4f7d-b4ef-0447ade4d8d5.png">

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: GitLab
 - OS: Monterey
 - Browser version Chrome Version 101.0.4951.64

 - Node.JS version: 16

**CMS configuration**
backend:
```
name: git-gateway
branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog

```

**Additional context**
We had the same problem back in 2019
https://github.com/netlify/netlify-cms/issues/2896
Last working blog update was the 14th of may. Yesterday my client informed me about the error.
Hope that helps to solve the issue.
Best regards

**Comment by wouter-muller** [comment]
I had the same issue, a temporary fix is to disable and then enable the Git gateway. Then all entries are back, but it happened again a few hours later...

**Comment by localden** [comment]
Thanks for the feedback @hkrank and @wouter-muller - we've identified a potential root cause to the issue and are working on a remediation path. This is related to #6475 and is caused by how GitLab handles key rotation.

**Comment by wouter-muller** [comment]
Thanks @localden for the feedback 👍  

The Netlify status update channel tells me that i should follow the steps listed in https://answers.netlify.com/t/how-to-mitigate-changes-to-gitlab-version-15-0-support-for-oauth-tokens/56613May but this URL returns a 404...

**Comment by wouter-muller** [comment]
I followed the steps listed in https://answers.netlify.com/t/how-to-mitigate-changes-to-gitlab-version-15-0-support-for-oauth-tokens/56613 and this seems to have resolved the issue for me. @hkrank
