### ISSUE TITLE
ability to edit an object widget's "name" attribute via the CMS

### ISSUE THREAD

**Issue by markjohnson4** [netlify/netlify-cms#6479]
Hi!  I want the CMS to generate something like this in TOML with the option of creating many languages:

```
[languages]
[languages.en]
    languageName = "English"
    weight = 1
    contentDir = 'content/en'
[languages.es]
    languageName = 'Español'
    weight = 2
    contentDir = 'content/es'
```

on the CMS side, this as a list widget ("languages") with two object widgets (with the names "en" and "es").  

Currently I have to hardcode the object widgets to have these names.  Ideally, their names can be edited via the CMS.  That way a CMS user can make as many objects as they want.

Is this possible?

Thanks!

**Comment by martinjagodic** [comment]
Hi @markjohnson4 this is not possible.
