### ISSUE TITLE
How to port gatsby-netlify-cms site to cloudflare pages

### ISSUE THREAD

**Issue by globalkonvict** [netlify/netlify-cms#6483]
**Is your feature request related to a problem? Please describe.**

I am looking to host my gatsby netlify blog on Cloudflare pages, not sure how to handle authentication and other things for netlify cms. I find Cloudflare pages to offer more diverse features and rich env for further enhancements.

**Describe the solution you'd like**

I was hoping for guidance on how to port my project to Cloudflare pages and make it work.

**Describe alternatives you've considered**

I've looked around the docs but seem to be stuck and confused about how to proceed further with the task.

**Comment by johnabroad42** [comment]
Pls why i don'tget help multiple

**Comment by globalkonvict** [comment]
@johnabroad42 I just wanted to do it from start. Netlify is just for me to test things. Recently they auto charged, should have suspended services. Anyways I don't mind how they do things. Cloudflare is bringing new goodies for serverless and static hosting tech, once in a while. Again, from when they introduced workers they have already launched far more features and products to the ecosystem. Pages, Storage and for auth they have zero trust zone. 

CF is cheaper too, and has more features and integrate with many services do. That's all, I am interested in experimenting with CF now.

**Comment by saskenuba** [comment]
Well, you can do what I did, perhaps not it's not the best way to do it but it is certainly the most practical one.

1. Create a page on Cloudflare pages and push your project
2. Push the exact same project on Netlify (both will re-build when you push changes)
3. Enable Netlify Identity and Git Gateway on Netlify
4. On Cloudflare DNS, set up a CNAME with "admin" or else, and point it to your free project domain E.g: https://something-0123.netlify.app/admin
5. Enjoy your CMS on Cloudflare

Hope this helps.
