### ISSUE TITLE
Saving fails *almost* silently when required fields are left empty

### ISSUE THREAD

**Issue by verythorough** [netlify/netlify-cms#649]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
If a user tries to save an item with an empty required field, the save button appears to do nothing at all. If you look closely (and aren't color blind), you may notice that one or more field labels have turned red. This is the only indication of why saving fails, and it can be really easy to miss, especially if the fields in question are offscreen.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a new post on [cms-demo](https://cms-demo.netlify.com/#/collections/posts/entries/new). (<--That link will take you straight to the new post page.)
2. Without adding any content, click Save.
3. See that Title and Body labels turn red, but no other feedback is given.

**- What is the expected behavior?**
At minimum, a general error message that says something like, "Oops, you've missed a required field. Please complete before saving." It would also be helpful to have a more noticeable, accessible indicator on the offending fields.

**- Please mention your CMS, node.js, and operating system version.**
True on all versions I know of, in any browser.

**Comment by dardub** [comment]
I don't have any fields marked as required, still running into this issue.

**Comment by neutyp** [comment]
Video snippet from a user test wherein this bug was seen. It's a bit confusing to watch as you only hear me speaking and not the test participant as well.

http://share.neutyp.com/1k393r2o0V1m

**Comment by verythorough** [comment]
@dardub Do you have all of your fields marked as `required: false`? It's not immediately obvious that all fields are required by default.

**Comment by aquibm** [comment]
Hi, I'd love to pick this one up if it hasn't been assigned already.

**Comment by verythorough** [comment]
Sweet! If you have any questions, feel free to ask here or in [Gitter](https://gitter.im/netlify/NetlifyCMS).

**Comment by dardub** [comment]
I didn't realize that fields are required by default. That seems like an
anti-pattern to me. For instance in html fields are not required until
specifically added.

**Comment by erquhart** [comment]
[Totally agree](https://github.com/netlify/netlify-cms/issues/464).

@aquibm great to hear! Be sure to consider which fields play critical roles, and what happens when they're missing. I believe this only applies to the title field, but there may be edge cases that I'm not thinking of.

**Comment by aquibm** [comment]
Hey @erquhart, I've done a [quick first pass](https://streamable.com/2evve) by surfacing up errors for fields that are required and flashing a notification when we back out of persisting the entry due to validation errors.

If we wish to flash a notification specially for empty required fields, we could modify the `fieldsErrors` map in the `entryDraft` to include a type for each error against a field rather than just a string describing the error to the user. This way, when persisting the entry we could select whether there have been any empty required field errors and flash the notification before backing out.

Please let me know if I'm headed in the right direction or if you have a better approach.

**Comment by dioptre** [comment]
This happens for me when all the fields are complete too. Definitely seems like a bug.

**Comment by erquhart** [comment]
@dioptre this issue centered around the old 0.x UI, if you're experiencing something like this in the current CMS (2.0 or newer), please open a new issue so we can hunt it down 👍.
