### ISSUE TITLE
Option to show related posts

### ISSUE THREAD

**Issue by phae** [netlify/netlify-cms#65]
A user needs to be able
- to easily link to other related posts along side their article
- to not have to manually create links to posts
- to be able to easily remove a related post from an article

Acceptance criteria:
- [ ] There is an input that lets a user search for other, previously published, posts
- [ ] User can select a post from the search to add it to the list of related posts
- [ ] User can click "remove" to take the link off the related posts list.

**Comment by cassiozen** [comment]
Version 0.1.10 implemented a search relation widget. Closing for now.
