### ISSUE TITLE
How can remove the unwanted part on the top navigation bar

### ISSUE THREAD

**Issue by Leo-T-Zang** [netlify/netlify-cms#6533]
Hi,
I want to remove the talk section in the picture below, which is the top navigation bar from the academic resume template.

thank you.

![image](https://user-images.githubusercontent.com/85547488/184361399-282e5b56-f21b-4ede-8020-c3d9a9057f87.png)

**Comment by MindInSky** [comment]
Hey this is likely something that can be done inside of the template, generated content or in the worst case scenario config.yml , have you tried to check if theres a place to remove them there? Also please provide a repo, or link to it so anyone can review the code, I believe this is not a bug but would like to see the code for it, thanks

**Comment by talves** [comment]
If this has anything to do with netlify-cms then it can be re-opened.

**Comment by Leo-T-Zang** [comment]
Ok, thank you. Let me try. I am really new to web programming. Is there a forum to ask such questions?
