### ISSUE TITLE
No documentation on how to test config.yml locally?

### ISSUE THREAD

**Issue by 96312** [netlify/netlify-cms#6545]
Hello fellow users,

I want to test my `config.yml` configuration and how my admin panel looks like on `localhost` before deploying the website. Lots of googling and sifting through the docs has led me here.

Any resources to help me figure it out?

**Comment by RoneoOrg** [comment]
Hi @96312,

I don't like Youtube tutorials, but [this one](https://www.youtube.com/watch?v=byFBKrM9MNY&list=WL&index=7) answered this question.
Do not forget to run `npx netlify-cms-proxy-server` every time you need to run tests locally

**Comment by 96312** [comment]
@RoneoOrg Brilliant! Thank you, that answered my question.
