### ISSUE TITLE
Is project dead?

### ISSUE THREAD

**Issue by sanch941** [netlify/netlify-cms#6559]
Please, tell me that the project is still in development, how can i support you?

**Comment by amantulsyan35** [comment]
I'd like to contribute to the development of this too

**Comment by martinjagodic** [comment]
This project is not dead anymore 🥳 It is rebranded as Decap CMS. Read more at [Netlify blog](https://www.netlify.com/blog/netlify-cms-to-become-decap-cms/) or [Decap blog](https://decapcms.org/blog/2023/02/introducing-decap)
