### ISSUE TITLE
Netlify's function is reading project folder without permission

### ISSUE THREAD

**Issue by 1alexvash** [netlify/netlify-cms#6560]
In my app I have a search feature which goes to the content folder, grabs markdown posts, and displays them

![image](https://user-images.githubusercontent.com/46556479/192146076-631e275d-ae70-4475-8cfe-f2ca76de6420.png)

The [repository](https://github.com/1alexvash/AlexCodeBlog)

[The Netlify Search Function](https://alex-code.com/api/getAllPosts)

How does it able to do so, **outside** build folder on **staging**?

I was getting errors here, and there, then I suddenly realized to access this folder on staging, I have to create the following Netlify file, so on staging Netlify has access to the content folder, but currently if you check my [repository ](https://github.com/1alexvash/AlexCodeBlog)it does not have this file, and works magically without it, can somebody explain to me what is going on?
![image](https://user-images.githubusercontent.com/46556479/192146192-07d89635-b9e7-450b-a415-0f05525701eb.png)

**Comment by martinjagodic** [comment]
Hi @1alexvash, this repo is intended for Decap CMS related issues.

For Netlify build related issues I suggest to reach out in the forums: [https://answers.netlify.com/](https://answers.netlify.com/)

Closing the issue, and please comment if you have any other questions.
