### ISSUE TITLE
Support for audio and video files

### ISSUE THREAD

**Issue by 1alexvash** [netlify/netlify-cms#6561]
Is there a way to add audio or video file inside Netlify CMS?

I'm not seeing it in the editor:
![image](https://user-images.githubusercontent.com/46556479/192155291-ad4afe8e-33ca-4d29-b607-27d310f85a71.png)

I saw this option on Medium and other websites, and it looks cool

**Comment by RoneoOrg** [comment]
The file widget could be a starting point: https://www.netlifycms.org/docs/widgets/file/
