### ISSUE TITLE
Outdated News Section 

### ISSUE THREAD

**Issue by ShalokShalom** [netlify/netlify-cms#6574]
The news sections on the homepage contains zero updates since over 2 years. 

![Screenshot_20221011-131403](https://user-images.githubusercontent.com/6344099/195075990-8cfd94df-b81a-4afe-80e5-6dd66b6ea634.png)

netlifycms.org/

**Comment by mordonez** [comment]
@ShalokShalom perhaps Netlify is not interested anymore. Because there are a lot of pull requests and issues without response

**Comment by martinjagodic** [comment]
Netlify CMS is now Decap CMS. More news will follow!
