### ISSUE TITLE
Error loading existing content

### ISSUE THREAD

**Issue by theverylastjuan** [netlify/netlify-cms#658]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Attempting to edit existing MD files in the content folder results in an error.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Once in the CMS for the live site, I click the content tab, click on an existing post/file, then I get a "Not Found" page with and error pop-up saying "Failed to loaf entry: Not found"

FYI: This is content that was created prior to adding the CMS to the page.

**- What is the expected behavior?**
Should be able to modify existing files as they are in the proper subdirectory with accident front matter.

**- Please mention your CMS, node.js, and operating system version.**
<img width="1440" alt="screen shot 2017-10-06 at 12 35 40 pm" src="https://user-images.githubusercontent.com/13276705/31288570-75ae394e-aa93-11e7-828c-b55061799d6f.png">

CMS 0.4
Hugo Static-Stie Generator

**Comment by erquhart** [comment]
@theverylastjuan sorry I'm just now seeing this - first of all, your CMS version is way behind! We just dropped 1.0, you should check it out. I forked your repo and tried it with 1.0 and this bug no longer occurs - but your entries still don't have titles! Update your Title field's `name` prop from "site-title" to just "title", and the CMS will pick it up.
