### ISSUE TITLE
Clearing Netlify CMS cache in branch deploys

### ISSUE THREAD

**Issue by svvimming** [netlify/netlify-cms#6581]
I'm having in issue with my netlify CMS cache not clearing when making changes in a branch set up with a build preview. 

I can manually clear 'cache and redeploy' from within the netlify admin panel but I'd like the option to automate clearing the cache or to not cache content at all between deploys.

I've seen some solutions [outlined here](https://answers.netlify.com/t/how-to-clear-cache-on-branch-deploy/5521), specifically appending `&& rm -rf /path/to/cache` to the build command but I'm unable to find the exact path to the cache - some insight on this would be helpful.

Thanks.

**Comment by martinjagodic** [comment]
Hi @svvimming, this repo is intended for Decap CMS related issues.

For Netlify build related issues I suggest to reach out in the forums: [https://answers.netlify.com/](https://answers.netlify.com/)

If you want to clear cache of the admin panel, just hard refresh your browser.

Closing the issue, and please comment if you have any other questions.
