### ISSUE TITLE
Deploy failed Next.js on Netlify

### ISSUE THREAD

**Issue by unnimona** [netlify/netlify-cms#6594]
7:12:23 PM: Creating deploy upload records
7:12:23 PM: Failing build: Failed to prepare repo
7:12:23 PM: Failed during stage 'preparing repo': git ref refs/heads/master does not exist
7:12:23 PM: Finished processing build request in 1.153506718s

**Comment by martinjagodic** [comment]
Hi @unnimona, this repo is intended for Decap CMS related issues.

For Netlify build related issues I suggest to reach out in the forums: [https://answers.netlify.com/](https://answers.netlify.com/)

Closing the issue, and please comment if you have any other questions.
