### ISSUE TITLE
[template.environment] does not work now

### ISSUE THREAD

**Issue by Daemonxiao** [netlify/netlify-cms#6599]
**Describe the bug**

I set the template.environment in my netlify.toml file but it does not export env in deployment.
![pfPLIrq86q](https://user-images.githubusercontent.com/35677990/202617617-2801fa60-42c7-4f5f-ac58-61e28123caf5.jpg)
![hMetVKeWFZ](https://user-images.githubusercontent.com/35677990/202617701-ece80c27-e2ab-4e95-92af-3f990bc36935.jpg)

👀 Does this configuration is deprecated?
**Expected behavior**

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

**Additional context**

**Comment by martinjagodic** [comment]
Hi @Daemonxiao, this repo is intended for Decap CMS related issues.

For Netlify build related issues I suggest to reach out in the forums: [https://answers.netlify.com/](https://answers.netlify.com/)

Closing the issue, and please comment if you have any other questions.
