### ISSUE TITLE
Data Files Array Editing View Is Convoluted

### ISSUE THREAD

**Issue by alteducation** [netlify/netlify-cms#661]
**- Do you want to request a *feature* or report a *bug*?**
      Feature 
**- What is the current behavior?**
      Instead Of being Minimised Like [This](https://pasteboard.co/GNQv7zt.png) The Array Elements 
      are open by default. This makes adding new posts and general navigation difficult. Also The 
      button for adding new entry is at the bottom this makes the user scroll to the bottom every time to 
      create an entry. Please consider changing it to the top of the page or top and bottom. Another Issue 
      thing is after saving an entry the the editor closes and goes back to the previous page. now the user
      needs to open the editor and scroll down again to make the next entry.

**- If the current behavior is a bug, please provide the steps to reproduce.**
      Create a new data file with an array and try adding new elements
**- What is the expected behavior?**
     Please keep the elements minimised and add the + button to the top as well.  Also if  possible  
      I think displaying the elements in the reverse order will make it easier to add new entries.
**- Please mention your CMS, node.js, and operating system version.**

**Comment by tech4him1** [comment]
This might be good as a configuration option,  maybe `expanded: true`.

**Comment by Benaiah** [comment]
@tech4him1 I have this functionality implemented in my widget HOC work - once I'm able to get back to that and get it updated and merged it will close this issue.

**Comment by erquhart** [comment]
As a UX issue, this is also related to #490.

**Comment by erquhart** [comment]
Everything here is addressed in 1.0 except the core issue of minimizing by default. We should add a config option, agreed.

**Comment by tech4him1** [comment]
Closed in #923.
