### ISSUE TITLE
Update the readme and set the repo to archived or consider identifying community maintainers

### ISSUE THREAD

**Issue by DDunc** [netlify/netlify-cms#6612]
There are a large number of open issues which have not been acknowledged and many major issues are 18 months old. There have been no commits in 6+ months while 100+ new issues have been opened with minimal or no acknowledgement.

All of this strongly suggests Netlify CMS is no longer being actively maintained and absent any updates it seems likely there will continue to not be enough developer resources available. While OSS is always as-is, it would be helpful to update the readme to make it clear to new users this project has been archived. Alternatively, Netlify could benefit from looking into turning this repo over to community maintainers rather than letting it slowly bitrot. Which is a shame, because the CMS has a lot of users and a lot of great engineering effort and support has gone into it!
 
I use Netlify's paid services and I'm very satisfied with them, my initial conversion to becoming a paid user was through using Netlify CMS, in large part due to the level of support and active feature development. It's entirely understandable that business priorities may need to change over time! But the current state of this project no longer reflects Netlify's engineering quality for paid services or its ability to keep pace with the broader ecosystem.

If there is a plan to begin actively maintaining Netlify CMS again in the future, it would be very useful to convey that information in the readme.

**Comment by komali2** [comment]
Does anybody have maintained alternatives to hosting a Hugo site with admin features?

**Comment by martinjagodic** [comment]
Great news, this project is back from the dead! Read more at [Netlify blog](https://www.netlify.com/blog/netlify-cms-to-become-decap-cms/) or [Decap blog](https://decapcms.org/blog/2023/02/introducing-decap)

**Comment by komali2** [comment]
> Does anybody have maintained alternatives to hosting a Hugo site with admin features?

By the way, in the end I went with https://github.com/StaticJsCMS/static-cms which is a fork of this repo

This repo still doesn't have any new commits or anything, though I'm happy to hear there's new maintainers (I don't know who they are). In case it doesn't work out, there's always staticcms.
