### ISSUE TITLE
Is it possible for Netlify CMS to simply authenticate directly with GitHub?

### ISSUE THREAD

**Issue by nottrobin** [netlify/netlify-cms#663]
I love the simplicity of static sites, and for a while now I've been meaning to play around with creating a CMS-like interface for allowing content editors to edit a Jekyll site in a markdown repository.

Then I found Netlify CMS and it looked like you'd solved the exact problem I was interested in - providing an admin area as a single-page application, where users can authenticate through OAuth and then edit the pages in a CMS interface, committing back to the repository when changes are saved.

But after looking into it for a while, I've found that actually the solution provided is rather unsatifying, because in fact I need to use Netlify as my OAuth backend for this to work (even if I can it to be a proxy user-management to GitHub). I [can't simply let my users authenticate with GitHub](https://github.com/netlify/netlify-cms/issues/37).

From #37:

> Currently the GitHub backend depends on netlify's Authentication Provider system ...
> We do want to see other OAuth services enabled as well so there's no dependency on netlify.

This significantly complicated the problem space, by adding in a dependent service. For most users, this seems like an unnecessary complication.

My question is, is there a good reason why the Netlify CMS didn't implement the much more obvious solution first, and authenticate directly with GitHub? This must surely have been the first thing that would have occurred to anyone trying to solve this problem. Is there a technical limitation with GitHub's OAuth API that prevents this? Or has it simply been done this way to support [Netlify's pricing model](https://www.netlify.com/pricing/) by encouraging people to use Netlify as a service?

**Comment by nottrobin** [comment]
Perhaps I'm misunderstanding the way OAuth works? Perhaps it needs some back-end functionality on the same domain? I just kinda thought the whole point of OAuth is that the client could authenticate with a third party service.

**Comment by nottrobin** [comment]
Okay I've answered my question by reading about [OAuth flows: implicit grant](https://auth0.com/docs/api-auth/which-oauth-flow-to-use#is-the-client-a-native-app-or-a-spa-) and discovering that [GitHub explicitly doesn't support implicit grant](https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-authorization-options-for-oauth-apps/#about-authorization-options-for-oauth-apps).

This means that there needs to be a server-side component to any application that wants to talk to GitHub's API through OAuth. And Netlify offers such a server-side component, and I also have the option of [running one myself](https://github.com/vencax/netlify-cms-github-oauth-provider). Now this makes sense - Netlify hasn't made the problem more complicated than it has to be, it simply has to be this complicated.

**Comment by tech4him1** [comment]
@nottrobin Yes, that is pretty much why it works like it does. Let us know if you have any more questions!

**Comment by Benaiah** [comment]
@nottrobin note that it is possible to set up the CMS without Netlify specifically - there’s a brief guide here: https://github.com/netlify/netlify-cms/blob/master/docs/custom-authentication.md

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jimafisk** [comment]
@Benaiah the guide you referenced is missing, any chance it still exists somewhere? Netlify is a great service, but I think this project would have a better chance of gaining traction if it was more clear how to set up independent of a specific host.

@nottrobin I've been really curious about the same thing! It looks like [GitLab supports implicit flow](https://docs.gitlab.com/ce/api/oauth2.html). People have also been working on allowing GitLab to be used as the backend for NetlifyCMS: https://github.com/netlify/netlify-cms/issues/57

**Comment by tech4him1** [comment]
@jimafisk Our new authentication docs are at https://www.netlifycms.org/docs/authentication-backends/.

**Comment by blyedev** [comment]
> @jimafisk Our new authentication docs are at https://www.netlifycms.org/docs/authentication-backends/.

This link is also broken

**Comment by martinjagodic** [comment]
@blyedev I believe this is what you are looking for: https://decapcms.org/docs/backends-overview/

**Comment by vadimkantorov** [comment]
Is it possible to configure DecapCMS to let the user provide it with the user's issued GitHub token and have DecapCMS then talk to GitHub API directly? (in this case, bypassing the auth flow with GitHub/Netlify and thus not needing a server-side component at all, besides GitHub API itself)

For many cases, this should be sufficient (especially with new GitHub tokens allowing repo-level access) and should make DecapCMS ideal for small GitHub-powered blogs

**Comment by SolidKalium** [comment]
This issue is currently linked to from the [docs/github-backend](https://decapcms.org/docs/github-backend/) page.

My understanding is that PKCE with an Authorization Code workflow could theoretically help, and GitHub added support for it earlier this year. But as mentioned in #6597 and its links, there are still hurdles related to CORS and GitHub not having a concept of public (no private backend) clients.

So we will still need to use an [OAuth client](https://decapcms.org/docs/external-oauth-clients/) running via a cloud function (or on a full server if you really want) for the near future.

**Comment by vadimkantorov** [comment]
The Personal Access Token-based login fully eliminates the need for the backend/cloud proxy fun toon, and can be a viable option for small websites in the meanwhile (while waiting for public client support in GitHub side)

Sveltia added this login method, it would be great if original DecapCMS also had this support

**Comment by martinjagodic** [comment]
@vadimkantorov are you open to submitting a PR that would add this feature? Or maybe just provide more details on how this would work/how it works on Sveltia. The best place to put this info would be in a new issue. Thanks!
