### ISSUE TITLE
Question about Netlify-cms features

### ISSUE THREAD

**Issue by rphad23** [netlify/netlify-cms#6643]
can i host this on my own server separately from netlify themselves? I want to be able to  host this on my firebase website. Is this pooisble?

**Comment by dfdez** [comment]
Hey @rphad23 sure you can host netlifycms anywhere is an open source project. The only downside is that you lose some functionalities like making reviews in the [preview links ](https://docs.netlify.com/site-deploys/deploy-previews/)

**Comment by rphad23** [comment]
@dfdez how would i do that? is there some documentation i can follow?
