### ISSUE TITLE
Feature request: Wordpress import

### ISSUE THREAD

**Issue by raae** [netlify/netlify-cms#665]
I have years of blog posts in WordPress and would love to switch over to the Netlify CMS, but manually importing them all would be a pain. I am guessing this is the same for many other users.

Important for me: 
* Keep slug as is
* Import featured image
* Import content images

I can live with small errors in the formatting as I am guessing html to markdown can be error-prone. 

A bonus would be importing advanced custom fields as well, building up the same content model based on the import.

I am guessing it might not be your first priority, just wanted to get this need communicated.

**Comment by tech4him1** [comment]
@raae Netlify CMS is just a content editor (a headless CMS), it doesn't actually deal with making your content into a website. You must use a static site generator or some other sort of build tool to actually create the site. If you have decided on a static site generator, have you checked to see if it has an import tool? We are working on a tool to generate your CMS editor config (https://github.com/netlify/netlify-cms/issues/322), but that will only work *after* you already have the site converted into markdown. Does that make sense?

**Comment by erquhart** [comment]
Actually @biilmann created a tool for this to support Smashing's migration from Wordpress to Hugo, and there's a Jekyll exporter that might get you close to your target as well.

Not certain how up to date the Hugo tool is, honestly, but it's here: https://github.com/netlify/make-wp-epic

Jekyll tool, which isn't by us, but looks fairly well maintained, is here: https://github.com/benbalter/wordpress-to-jekyll-exporter

**Comment by raae** [comment]
I know it is a headless CMS. I would like all my posts converted into markdown I can continue to edit in Netlify CMS, even before deciding on an SSG @tech4him1.

I will have a look at some of the SSG specific ones you mentioned @erquhart.

**Comment by tech4him1** [comment]
@raae The problem is that the CMS has no idea how you are going to want the markdown and front-matter formatted, as that will depend on your SSG. The format used by Jekyll is pretty widely supported, so you may just be able to use the WordPress Jekyll exporter that @erquhart mentioned above.

**Comment by paulkn** [comment]
[Gatsby.js](https://www.gatsbyjs.org/) may be the best option now. It uses GraphQL to pull in data from Wordpress or many other sources and is compatible with NetlifyCMS as well. See here for more info: https://www.gatsbyjs.org/tutorial/part-four/#transformer-plugins
