### ISSUE TITLE
Kramdown's block inline attribute lists doesn't get rendered by the CMS preview

### ISSUE THREAD

**Issue by bkroggel** [netlify/netlify-cms#666]
**- Do you want to request a *feature* or report a *bug*?**
Feature

**- What is the current behavior?**
Jekylls default markdown parser Kramdown normally allows to add attributes (like classes, ids...) via the so called ["block inline attribute list"](https://kramdown.gettalong.org/quickref.html#block-attributes). The Netlify CMS markdown engine doesn't recognize these special blocks of information and handles them like usual text elements.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Add something like `{:style="color: red"}` right after a block of text in the markdown editor.

**- What is the expected behavior?**
Following the steps in the section above the Jekyll output will show a red colored text, while the Netlify CMS preview window will purely show `{:style="color: red"}` as result.

**- Please mention your CMS, node.js, and operating system version.**
0.5.0

This is definitely nothing that needs to be considered in the short run. If you really stick to the Netlify CMS approach it would be a much better solution to use the widget system and build some custom ones for additional styles or classes. However especially for users who use external markdown editors it could be handy to take a look at the results after copying the raw markdown content to the Netlify CMS editor.

**Comment by erquhart** [comment]
You're exactly right, this is why we have the widget system - we can't support all of the various things folks do with markdown, so we **loosely** support the only real spec, Commonmark. If you do anything in this regard, let us know! We'd like to start compiling community resources for discoverability in the near future.
