### ISSUE TITLE
Instead change the require of swiper.esm.js in C:\...netlify\functions-internal\server.js to a dynamic import()

### ISSUE THREAD

**Issue by pullmann4rent** [netlify/netlify-cms#6660]
**Describe the bug**
Hello,
I downloaded a swiper libary and I want to add it, now I get this error

```
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\xxx\xxx\node_modules\swiper\swiper.esm.js from C:\xxx\xxx\.netlify\functions-internal\server.js not supported.
Instead change the require of swiper.esm.js in C:\xxx\xxx\.netlify\functions-internal\server.js to a dynamic import() which is available in all CommonJS modules.
```

**To Reproduce**
it happens when I import this code:

`import { Swiper, SwiperSlide } from 'swiper/react';`

**Expected behavior**
.

**Screenshots**
.

**Applicable Versions:**

 - Netlify CMS version: 
 - Git provider: github
 - OS: windows 11
 - Browser version chrome

 - Node.JS version: 16

**CMS configuration**

**Additional context**

**Comment by samo4** [comment]
Please try Netlify forums. This place is for CMS bugs only.
