### ISSUE TITLE
Can't join Public Slack Channel via Join Us button at bottom of website 

### ISSUE THREAD

**Issue by clarkejt** [netlify/netlify-cms#6668]
**Describe the bug**
When you click the Join Us (on slack) button at the bottom of the netlifycms.org website, the slack invite requires that you have an @netlify.com email address. 

**To Reproduce**
1. Go to (https://www.netlifycms.org)
2. Click on Join Us Button (bottom right)
3. Slack invite will open
4. See that you require an @netlify.com email address

**Expected behavior**
A user should be able to sign up with any email address 

**Screenshots**
<img width="178" alt="image" src="https://user-images.githubusercontent.com/473446/214508881-5905bf3e-f960-49ef-bdc7-695beeeb310b.png">

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/473446/214508983-a18dd65a-0e86-4015-86ee-519b112cc353.png">

**Additional context**
Looks like it was previously an issue here #4695

**Comment by talves** [comment]
Hey Martin, any chance the community will move to discord instead?

**Comment by samo4** [comment]
yes, we'll run discord server side by side for a while and 
@talves you can help by testing this [invite](https://discord.gg/S9hyFmdNsD)

**Comment by talves** [comment]
Worked Great, thanks!
