### ISSUE TITLE
Media library improvements

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#669]
The media library is about to be released - this is just a quick, public place for me to stash improvements prior to release. Most, if not all, of these will be converted to standalone issues.

- double-click on an asset should insert the asset (when insertion is available)
- display count of loaded assets in the UI

**Comment by erquhart** [comment]
Need to split this out into two separate issues.

**Comment by neutyp** [comment]
Do we yet have an issue for making the media library a proper page instead of just a modal?

**Comment by erquhart** [comment]
@neutyp no, we still need that.

**Comment by erquhart** [comment]
These other bits here aren't too big, the double click bit was more applicable when we were using a table. Closing.
