### ISSUE TITLE
Decide on browser support

### ISSUE THREAD

**Issue by tech4him1** [netlify/netlify-cms#674]
Right now, we have no stated browser support. We should probably decide on this.

The default that the latest versions of Babel and PostCSS use right now is this list: [`browserslist` defaults](http://browserl.ist/?q=defaults)

**Comment by tech4him1** [comment]
Current CSS browser support:
```
chrome 61
chrome 60
edge 15
edge 14
firefox 56
firefox 55
ie 11
ie 10
ie_mob 11
ie_mob 10
ios_saf 11
ios_saf 10.3
opera 47
opera 46
safari 11
safari 10.1
```
~ _[Browser List](http://browserl.ist/?q=last+2+Chrome+versions%2C+last+2+Firefox+versions%2C+last+2+Edge+versions%2C+last+2+ie+versions%2C+last+2+ie_mob+versions%2C+last+2+ios_saf+versions%2C+last+2+opera+versions%2C+last+2+safari+versions)_

**Comment by tech4him1** [comment]
Current JS compatibility ([jscc.info](http://jscc.info/)):
```
Chrome >=4
Firefox >=2
IE >=5.5
Opera >=9
Safari >=3.1
Edge >=12
iOS Safari >=3.2
```

**Comment by tech4him1** [comment]
I'm thinking we should go with:
```
last 2 Chrome versions
last 2 Opera versions
last 2 Firefox versions
last 2 Edge versions
IE 11
last 2 Safari versions
IE_mob 11
last 2 iOS versions
last 2 ChromeAndroid versions
```
@erquhart @Benaiah sound good?

**Comment by Benaiah** [comment]
@tech4him1 sounds good to me!

**Comment by erquhart** [comment]
Just adding for posterity that we landed on [this](https://github.com/netlify/netlify-cms/blob/cd72e1d9dd83e79dcc2f9c927c4cb5ced60b47cc/package.json#L66):

```
  "browserslist": [
    "last 2 Chrome versions",
    "last 2 Opera versions",
    "last 2 Firefox versions",
    "last 2 Edge versions",
    "last 2 Safari versions",
    "last 2 iOS versions",
    "last 2 ChromeAndroid versions"
  ],
```

@tech4him1 feel free to close if nothing else is pending here.

**Comment by tech4him1** [comment]
See https://github.com/netlify/netlify-cms/issues/695#issuecomment-336918050 for why IE 11 support was dropped.
