### ISSUE TITLE
Provide instructions for adding a new contributor to the README

### ISSUE THREAD

**Issue by verythorough** [netlify/netlify-cms#676]
Thanks to the work of @DirtyF, we now have an all-contributors listing on the README, recognizing contributions of a variety of types. 🎉 

Now we just need some instructions to make it easy for anyone to add new contributors to the list. I'm thinking it makes sense to add it to CONTRIBUTING.md, and link to it from the contributor list in the README.

**Comment by DirtyF** [comment]
I should have documented this in the first place, thanks for the reminder.
