### ISSUE TITLE
Github Backend - API Rate Limiting

### ISSUE THREAD

**Issue by cassiozen** [netlify/netlify-cms#68]
- [x] Data retrieves should be paginated.
- [x] Github backend should keep track of `X-RateLimit-Remaining` and `X-RateLimit-Reset headers`
- [x] CMS App sho inform the user in critical cases

**Comment by erquhart** [comment]
I would add that we should be using the Trees API instead of Contents API for retrieving directories of files (undocumented ~100k limit vs 1k limit).

**Comment by erezrokah** [comment]
Closed in https://github.com/netlify/netlify-cms/pull/3494
