### ISSUE TITLE
Browser support: Firefox

### ISSUE THREAD

**Issue by DirtyF** [netlify/netlify-cms#688]
Hi all,

Tested the latest release with Firefox (nightly) and preview and markdown mode are not available, looks like the progress bar isn't able to finish loading.

```gherkin
Given I'm editing a post
Then Preview is not showing
And I can't click on the preview button to unload the preview
And I can't click on the markdown button to load the markdown mode
```

![netlify-cms](https://user-images.githubusercontent.com/103008/31542640-1e23e982-b013-11e7-8b0b-4c47bbc77b4c.gif)

**Comment by tech4him1** [comment]
@DirtyF Do you have any relevant errors in your browser console?

**Comment by erquhart** [comment]
@DirtyF it looks to be working in Firefox stable - if that changes, we'll definitely chase it down. Hard to say if a bug in a nightly browser build is us or not without digging in.

**Comment by DirtyF** [comment]
@erquhart I switched to Nightly to test [Quantum](https://www.mozilla.org/en-US/firefox/quantum/) before it goes in the stable channel. It looks like they are quiet of lot of [changes for developers](https://developer.mozilla.org/en-US/Firefox/Releases/57).
