### ISSUE TITLE
save fails silently if no title field is configured

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#690]
**- Do you want to request a *feature* or report a *bug*?**
bug
**- What is the current behavior?**
Saving fails silently if no title field is configured.

**- If the current behavior is a bug, please provide the steps to reproduce.**
- configure a collection with a single field called "test"
- enter text to the field
- save the entry
- observe error in console
- observe no error in UI

**- What is the expected behavior?**
There should be an error in the UI.

**- Please mention your CMS, node.js, and operating system version.**
CMS 0.5.1

**Comment by tech4him1** [comment]
@erquhart I believe you can also have a `path` field right now as well as `title`:
https://github.com/netlify/netlify-cms/blob/2324f08d6980fd1d98ba4d6479bd5041f6b171f4/src/backends/backend.js#L31

**Comment by tech4him1** [comment]
I believe that this only occurs when the collection doesn't specify a custom slug, or the slug contains a `{{slug}}` part.

**Comment by erquhart** [comment]
Yeah, it's better than silent failure.

**Comment by erquhart** [comment]
Update: there is now an error in the UI, but it doesn't specifically tell the user how to fix.
