### ISSUE TITLE
CMS broken in IE11

### ISSUE THREAD

**Issue by tech4him1** [netlify/netlify-cms#695]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
The CMS seems to be broken in IE 11. The error deals with `Symbol` not being a valid type.

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**
The CMS should work in IE 11.

**- Please mention your CMS, node.js, and operating system version.**

master

**Comment by tech4him1** [comment]
@erquhart Are you able to check into this as well, or are you not on Windows?

**Comment by talves** [comment]
Take a look at this solution https://github.com/babel/babel-preset-env/issues/203#issuecomment-285820866

It may be a better option for the babel setup. I will test it out also when I get a chance.

**Comment by tech4him1** [comment]
We also cannot add `useBuiltIns: "usage"` directly to fix this, because https://github.com/babel/babel/issues/6485.

**Comment by tech4him1** [comment]
This will be much easier to implement after `babel-preset-env@2` is released. We can then use `useBuiltIns: "usage"` to have it automatically require only the polyfills needed. See https://github.com/babel/babel-preset-env#usebuiltins-usage.

**Comment by erquhart** [comment]
After much discussion in Gitter, dropping IE11 support seems the proper path forward.

Reasons, in order of importance:
1. IE11 usage is even smaller than Safari now, under 4% globally, and shrinking.
2. We can't guarantee support without extensive, continual testing against that browser, which isn't proportionate to impact for our users, and our dependencies already vary in IE11 support.
3. Bundle size.

Lastly, and perhaps most tellingly, the CMS seems to have always been broken in IE11, and no one has reported it.

Documentation should be added about this decision with the PR for dropping support.

**Comment by neutyp** [comment]
Where are you reading that stat on IE11? I'm seeing 11.99%, much higher than 4%

**Comment by tech4him1** [comment]
Just another note on this: the CMS has been broken in IE11 only since 0.3.1, released January 19. We might still have IE11 users that haven't upgraded yet (this fits enterprise usage as well).

**Comment by erquhart** [comment]
@neutyp http://gs.statcounter.com/

All of these stats services are based on whatever data that service has collected, in statcounter's case via their analytics script. It's the most used reference in my experience. What are you using?
