### ISSUE TITLE
Open content editor to a specific entry by path

### ISSUE THREAD

**Issue by rriemann** [netlify/netlify-cms#697]
This is a feature request.

I use jekyll to generate my pages and would like to have buttons with the link to edit the site.
For github, I use:

    <a href="https://github.com/{{ site.repository }}/edit/master/{{ page.path }}">via Github</a>

This works nice, because I can easily access the page.path

I would like to use `my-domain.com/admin/#/edit/{{page.path }}` for Netlify. This is currently not supported.

**Comment by erquhart** [comment]
The end result would be great, but entries don't map 1:1 with the resulting file path. We'd need to consider how best to do this.

**Comment by rriemann** [comment]
The problem is that netlify cms does not accept a path, but needs the name of a collection defined in the config and the slug defined in the file.

**Comment by erquhart** [comment]
Hmm we could transform the url you're proposing, come to think of it. Given `{cmsUrl}/edit/{filePath}/{fileName}`:

- Use a catch-all route for the `edit` url segment
- Find a `file` entry in the config with a path that matches `{filePath}/{fileName}`
- If no file matches, find a `folder` collection in the config whose directory matches `{filePath}`
- If a `folder` collection matches, search the entries in the backend for a file name that matches { fileName }
- If no matches found, 404

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rriemann** [comment]
This would be nice. I'll be very busy until the end of the year, but maybe I can contribute later.

**Comment by erquhart** [comment]
Hey, it's good to be busy! Most of the time, anyway lol. Sounds great :)

**Comment by RoObsessedCode** [comment]
Hello, I am new to the Netlify-CMS community and am interested in taking on this ticket. Is it currently available? Thanks!

**Comment by rriemann** [comment]
They @RoObsessedCode, cool you find your way to this ticket. Please take it!

**Comment by erquhart** [comment]
@RoObsessedCode welcome! It's all you my friend :)

**Comment by RoObsessedCode** [comment]
My first question for you @rriemann @erquhart (Hope it is okay if I post my queries here).

Right now, the way it is, collection name is needed in the file path so suppose you have these 2 urls(for this example lets assume pages and blogs are two collections)

1.     {cmsUrl}/edit/blog/2
2.     {cmsUrl}/edit/page/2

If we refactored to eliminate the collection name we would end up with the same path but they need to be different to represent two different views

Both would end up as: {cmsUrl}/edit/2

Do you recognize the conflict I am proposing? How do you suggest to work around this issue?

**Comment by rriemann** [comment]
In my setup, every resource has only one view. We could just define that if a person has access to more than one view/collection to edit the same file, the person is either presented a choice dialogue or the link must contain the collection in the URL fragment.

I see another problem. I think the CMS uses not the filename (or part of it) like github, but instead a token (can someone confirm?). In some cases, this may be equivalent, but this is not true in all cases.

**Comment by erquhart** [comment]
@RoObsessedCode we wouldn't change the URL structure - we'd just parse the `edit` path and redirect to the real one. @rriemann it won't actually matter what identifier Netlify CMS uses, we'll use the filename to query the backend for folder collections. Might be good to do that for both file and folder collections just for consistency.

**Comment by RoObsessedCode** [comment]
Thanks @erquhart. I am in the process of seeing how everything works together and how exactly to implement the steps you listed above. I will keep the team updated. Thanks!

**Comment by erquhart** [comment]
Feel free to reach out for help in [Gitter](https://gitter.im/netlify/netlifycms), great community there.

**Comment by tech4him1** [comment]
@RoObsessedCode Let us know if you need any help on this!

**Comment by erquhart** [comment]
Considering this no longer in process.

**Comment by erquhart** [comment]
Closed in #2556
