### ISSUE TITLE
Add breadcrumb

### ISSUE THREAD

**Issue by phae** [netlify/netlify-cms#70]
A user needs:
- to know where the heck they are in the system

Add the breadcrumb back to the interface, at the very top, just below the header. It should provide a clickable trail for the user to get all the way back to the dashboard and any screens in between (usually dashboard > category > edit

**Comment by okonet** [comment]
I feel like breadcrumbs is a wrong choice here for a few reasons:

* There are just a few main screens in the UI: dashboard, entry list, entry view/edit
* They all are quite distinguishable by their look: each screen has its own purpose and quite unique
* When editing an article in some category, it's not important what category it is right now
* Actually, users should be able to change the category of an article in the edit screen IMO

Users should be able to see where they are but this can be achieved with a better typography and visual hierarchy. I'm planning to get there as soon as I finish my work on #82 if there are no objections.

Thoughts?

**Comment by cassiozen** [comment]
I will close this for inactivity.  Please feel free to reopen if needed.
