### ISSUE TITLE
Add necessary polyfills to support transpiled features.

### ISSUE THREAD

**Issue by tech4him1** [netlify/netlify-cms#702]
We transpile our JS code, but it doesn't necessarily support everything (see https://babeljs.io/docs/usage/caveats/). When `babel-preset-env` v7 is released, we can use `useBuiltIns: "usage"` to automatically add any polyfills needed after transpilation.

**Comment by tech4him1** [comment]
We can also remove the browser targets from the `.babelrc`, when we upgrade to v7, because they added support for using the `browserslist` in package.json.

**Comment by tech4him1** [comment]
I also think we should remove the `stage-*` presets and use the specific plugins we want directly.

**Comment by tech4him1** [comment]
Babel 7 also affects the `transform-runtime` plugin: `useBuiltIns` is added, which means we can stop using polyfilled `Map`, `Symbol`, etc, by setting it to `true`.

**Comment by tech4him1** [comment]
If the discussion in https://github.com/babel/babel/issues/6628 takes off, that would be nice.

**Comment by tech4him1** [comment]
Just did some testing with v7.0.0-beta.38. `transform-runtime` has the benefit of not polluting the global scope, but IMO it's not the most maintainable/minimal option, since it transpiles *everything*, even if the browser supports it.

I propose that we do:
```json5
["@babel/preset-env", {
  "modules": false,
  "useBuiltIns": "usage" // Add necessary polyfills to the global scope.
}]
```
Only use the runtime transform for helpers. We probably don't really need this anyway -- we're not transpiling much anyway with only the last 2 versions of browsers -- so it probably won't really change size.
```json5
["@babel/plugin-transform-runtime", {
  "helpers": true,
  "useBuiltIns": true,
  "useESModules": true,
  "polyfill": false,
  "regenerator": false
}]
```

**Comment by erquhart** [comment]
I'm with that.

**Comment by erezrokah** [comment]
Closing this as outdated. Please re-open if necessary.
