### ISSUE TITLE
I keep getting redirect to deployed website when i try to access http://localhost:5173/admin/index.html

### ISSUE THREAD

**Issue by teotimepacreau** [netlify/netlify-cms#7067]
**Describe the bug**
When I try to access the local admin page (http://localhost:5173/admin/index.html) it redirects me everytime to the deployed Netlify page, so I can't make any changes locally

**Expected behavior**
When going to the localhost admin/index.html page, accessin to the local DECAP admin panel and allow to add posts locally

**Screenshots**

https://github.com/decaporg/decap-cms/assets/95431443/f86b5167-bf67-495d-b2bd-944494210e53

**Applicable Versions:**

 - Decap CMS version: 2.10.192
 - Git provider: GitHub
 - OS: Windows 11
 - Browser version : Chrome 120.0
 - Node.JS version: v18.17.0

**CMS configuration**
config.yml : 
backend:
  name: git-gateway
  repo: teotimepacreau/Mairies-Sveltekit
  branch: decap  # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/uploads"  # Media files will be stored in the repo under static/uploads
public_folder: "/uploads"  # The src attribute for uploaded media will begin with /uploads

collections:
  - name: "articles"  # Used in routes, e.g., /admin/collections/blog
    label: "Articles"  # Used in the UI
    folder: "src/articles"  # The path to the folder where the documents are stored
    create: true  # Allow users to create new documents in this collection
    slug: "{{slug}}"  # Filename template, e.g., title.md
    fields: 
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Photo", name: "featured", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

**Comment by martinjagodic** [comment]
@teotimepacreau does this happen on decap v3 also?

**Comment by martinjagodic** [comment]
I see. You need to run the local server, not login with GitHub. See here: https://decapcms.org/docs/working-with-a-local-git-repository/
