### ISSUE TITLE
How to integrate into React app?

### ISSUE THREAD

**Issue by whmountains** [netlify/netlify-cms#711]
From the Readme:

> A complete, more complex install, that gives you more flexibility but requires that you use a static site builder with a build system that supports npm packages.

Where can I find more documentation about this installation method?

**Comment by erquhart** [comment]
It's open ended because the CMS can be use with any static site generator, and there are quite a few. If you reach out on [Gitter](https://gitter.im/netlify/netlifycms), you can get help for your specific case.
