### ISSUE TITLE
Logout Page needs a Home Config

### ISSUE THREAD

**Issue by talves** [netlify/netlify-cms#713]
**- Do you want to request a *feature* or report a *bug*?**
Feature

**- What is the current behavior?**
No button or redirect configuration for a logout of the CMS

**- What is the expected behavior?**
I would like to be able to specify the endpoint of the logout. Default would be to go back to the login page, but think it would be great to see it go to a config defined page or allow for a home button upon a setting in the config.

***NOTE:*** After some thought on a redirect button, I am thinking we should just expect the CMS to be a stand alone or allow the page to have the CMS as a component and use the current site's wrapper layout and navigation controlled by the site.

**Comment by talves** [comment]
Right, Improvement is for features that already exist 👍

**Comment by erquhart** [comment]
I'm in agreement with this, and I don't think we should assume the CMS is standalone, as it's typically not. Can you elaborate?

**Comment by talves** [comment]
@erquhart Yes, #737 and this issue are closely related and could be combined really. BUT, there needs to be the option for a path back to the main site or continuation path when the admin has control of the page. I was thinking in the config there could exist a path (ie `home_uri`) that would allow the navigation to a configured home path. If the path did not exist, the button would not show up.  There are probably a lot of arguments for both to exist, but this one seemed the easiest to implement without a restructure of the CMS architecture. #737 requires some architectural re-design, so I agree it could be done later.

**Note:** After configuring the CMS and working it into a couple sites, I felt less opinionated about #737, but it would be a nice option down the road.
