### ISSUE TITLE
Relation widget: cascade deletes

### ISSUE THREAD

**Issue by r1b** [netlify/netlify-cms#717]
**- Do you want to request a *feature* or report a *bug*?**

Feature

**- What is the current behavior?**

Deleted objects do not cascade to their references in relation widgets

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Create an object `A`
2. Create an object `B` with a  relation that refers to `A`
3. Delete `A`
4. An `orphan` remains in object `B`. It may not be displayed visually but it is still in the raw data.

**- What is the expected behavior?**

The data referring to the now-deleted object should be removed

**- Please mention your CMS, node.js, and operating system version.**

Netlify Version: 0.5.0  
Node Version: 8.6.0  
OS Version: Variable

**Comment by erquhart** [comment]
Relation dependency management is definitely on our radar - we've taken a swing at it in the past, but nothing landed. It would almost definitely require tracking relations via metadata.

**Comment by erquhart** [comment]
Closing in favor of #192, which captures the larger relation dependency story.
