### ISSUE TITLE
Unpublishing for the editorial workflow

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#727]
**- Do you want to request a *feature* or report a *bug*?**

feature

**- What is the current behavior?**

Published posts cannot be unpublished.

**- What is the expected behavior?**

User should be able to unpublish a published post:

- Push a commit to the published branch to remove the entry
- Create a new branch with an additional commit to re-add the removed entry
- PR the new branch
- Set status in the editorial workflow to Ready to Publish

**Comment by neutyp** [comment]
IMO, this feels to me like a critically basic action for a CMS. Any action I take, I should be able to undo.

**Comment by erquhart** [comment]
What's really funny is this was actually discussed in the very first CMS issue - check out this comment: https://github.com/netlify/netlify-cms/issues/1#issuecomment-99974145

**Comment by erquhart** [comment]
I discovered on accident that we already have everything we need to do this through what is ultimately a bug: every save in the CMS results in a commit, with or without actual changes to the entry. (And yeah we should fix that.) So currently we can trivially unpublish in the workflow as follows:

* Persist a change, same action as saving, which results in a PR in the EW (this step isn't necessary if the entry already has unpublished changes in the workflow)
* Delete the entry
* Rejoice

Come to think of it, I bet the deletion we added in 1.0 doesn't affect changes already in the workflow...

**Comment by nodox** [comment]
What is the status of this issue? Would love a way to unpublished a post after a fixed amount of time has past. Think expiring job posts.

**Comment by erquhart** [comment]
It's open for anyone to pick up if you're interested in working on it. Note that this ticket would cover manual unpublishing - scheduled publishing, which would pave the way for scheduled unpublishing - is discussed https://github.com/netlify/netlify-cms/issues/263.

**Comment by lizzzp1** [comment]
Could I take this?

**Comment by erquhart** [comment]
@lizzzp1 all yours! The steps you'll want to take are outlined in a comment above: https://github.com/netlify/netlify-cms/issues/727#issuecomment-350426136

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lizzzp1** [comment]
@erquhart is there a way to run just what you need? Running `yarn start` that runs everything, but it eats up my cpu :(

**Comment by erquhart** [comment]
@talves any chance this ^^ is due to the new builds? On mobile right now, don't recall how it impacted the dev tasks.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by talves** [comment]
CPU or the issue itself? Not sure on either one.

**Comment by erquhart** [comment]
@lizzzp1 we've played with our builds a bit, can you try again and see if the issue persists? It shouldn't be so resource intensive that a reasonably spec'd machine can't handle it. We don't have a great development workflow that doesn't include all modules, unfortunately.

**Comment by lizzzp1** [comment]
@erquhart will do!

**Comment by lizzzp1** [comment]
@erquhart it's noticeably better. Thanks!

**Comment by lizzzp1** [comment]
@erquhart Wondering if I could get a nudge in the right direction in terms of what code this touches and how to test locally. 😬 I was trying to test a bit on my site, but not seeing the issue, but maybe I'm just not fully understanding.

**Comment by erquhart** [comment]
You'd need to have some understanding of how the CMS works as a user, specifically the editorial workflow. The workflow allows your entries to be pull requests until you "publish" them, which merges the pull request and generally results in your site rebuilding and the published item going live.

This ticket is about adding "unpublish" functionality for items that are already published, so it will touch the GitHub backend (`packages/netlify-cms-backend-github`) and probably be triggered through the editor toolbar, where a dropdown currently contains the "publish" command - the toolbar component is here: https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-core/src/components/Editor/EditorToolbar.js
