### ISSUE TITLE
Netlify Invite Emails go to bare domain not /admin

### ISSUE THREAD

**Issue by spade-archer** [netlify/netlify-cms#7335]
When I invite a user to my site, (Jekyll, source on Github, hosted on Netlify), the email confirmation:

> You have been invited
> 
> You have been invited to create a user on (website). Follow this link to accept the invite:
> 
> **Accept the invite**

However the 'Accept the invite' link goes to /#invite_token=xxx domain, not /admin/#invite_token=xxx

Because the # isn't passed to the domain, I can't use a redirect to fix this. I can't find any way to configure this in Netlify, so is there something in the Decap settings which fixes this?

**Comment by tjgilpin** [comment]
Yep, I've run into the same issue. There's a couple of (pretty clunky TBH!) ways to get around this 

1. Click on 'Accept Invite' - then modify URL in address bar from `/#invite_token=xxx` to `/admin/#invite_token=xxx`
2. Set up a redirect in JS - eg:

```
  const currentHash = window.location.hash;
  if (currentHash.includes("_token")) {
    window.location.href = "/admin/" + currentHash;
  }
```

**Comment by martinjagodic** [comment]
You can define custom Netlify Identity email templates, as documented here: https://docs.netlify.com/security/secure-access-to-sites/identity/identity-generated-emails/#email-templates

Put these files in your repo's admin folder, for instance, `static/admin/emails`. Then you just set the path to each file in Netlify's dashboard.

This is how our templates look like:

**invitation.html**
```html
<h2>You have been invited</h2>

<p>You have been invited to create a user on {{ .SiteURL }}. Follow this link to accept the invite:</p>
<p><a href="{{ .SiteURL }}/admin/#invite_token={{ .Token }}">Accept the invite</a></p>
```

**confirmation.html**
```html
<h2>Confirm your signup</h2>

<p>Follow this link to confirm your user:</p>
<p><a href="{{ .SiteURL }}/admin/#confirmation_token={{ .Token }}">Confirm your mail</a></p>
```

**password-recovery.html**
```html
<h2>Reset Password</h2>

<p>Follow this link to reset the password for your user:</p>
<p><a href="{{ .SiteURL }}/admin/#recovery_token={{ .Token }}">Reset Password</a></p>
```

**email-change.html**
```html
<h2>Confirm Change of Email</h2>

<p>Follow this link to confirm the update of your email from {{ .Email }} to {{ .NewEmail }}:</p>
<p><a href="{{ .SiteURL }}/admin/#email_change_token={{ .Token }}">Change Email</a></p>
```
