### ISSUE TITLE
Attempting to read frontmatter in data files under editorial workflow

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#743]
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

An error is shown in the console that reflects the CMS attempting to read front-matter from a data file (e.g. json, yaml)

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Can be reproduced via `yarn start` on a local cms clone, but with a live GitHub backend
2. Configure the local CMS clone to use a repo with a "_data/settings.json" file (should contain at least an empty json object) and a "_data/authors.yml" (can have data or be completely blank)
3. Run the cms locally with the updated config
4. Make a change to an entry in the settings collection and save
5. Navigate to the editorial workflow
6. Observe "Error: Unrecgonized (sic) front-matter format."

**- What is the expected behavior?**

The CMS should only attempt to read front-matter in files that have front-matter, and should not throw an error in this case

**- Please mention your CMS, node.js, and operating system version.**

0.6.0

**Comment by tech4him1** [comment]
Interesting, I wonder if that is related to this code:
https://github.com/netlify/netlify-cms/blob/6d7bf3b1867c5cf366b20a89bcc28fcb3f941786/src/formats/formats.js#L10-L12

**Comment by tech4him1** [comment]
This happens only on the Editorial Workflow dashboard: if you actually click edit on the entry, you will be able to edit it normally, with the correct format.
