### ISSUE TITLE
Update to Extending doc breaks docs site build

### ISSUE THREAD

**Issue by verythorough** [netlify/netlify-cms#749]
**- Do you want to request a *feature* or report a *bug*?**
docs bug

**- What is the current behavior?**
While preparing to preview a docs edit, I discovered that builds on the netlify-cms-www repo have been failing since https://github.com/netlify/netlify-cms/commit/64b0d4cf068a9d84f8bf74275ffd3f3c84e83ab2. This is because the site is built with Hugo, and it's trying to process the shortcode syntax that's now in the code sample.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Go to https://www.netlifycms.org/docs/extending/ and see that the new version has not published.

**- What is the expected behavior?**
Content on https://www.netlifycms.org/docs should match content in https://github.com/netlify/netlify-cms/tree/master/docs.

I discovered that you can [escape the shortcodes](https://discourse.gohugo.io/t/solved-how-to-make-hugo-ignore-shortcode-delimiters-e-g-when-used-in-code-blocks/6045) by adding `/* */` inside them, and it works in the Hugo-built site:
![screen shot 2017-10-27 at 11 16 19 am](https://user-images.githubusercontent.com/6111186/32119068-df6bad3c-bb08-11e7-9136-f68a5d92d2ea.png)

However, the version on GitHub still shows the escape characters:
![screen shot 2017-10-27 at 11 16 38 am](https://user-images.githubusercontent.com/6111186/32119091-fd599b6a-bb08-11e7-95cd-cb674ec93386.png)

Ah, the joys of writing markdown for two simultaneous interpreters!

**Comment by erquhart** [comment]
Great catch @verythorough, reverted in [`83a1d34`](https://github.com/netlify/netlify-cms/commits/83a1d34).
