### ISSUE TITLE
Markdown field content does not swap places when parent list item is reordered

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#754]
When a list widget item with a markdown field is reordered, the data from the markdown field remains in its original position in the list.

Note that this only occurs in the UI, the markdown widget value is correct in the persisted data.

**Comment by erquhart** [comment]
This is almost certainly the same state persist issue that causes the markdown widget to maintain its value when a new entry is created from an existing entry. It happens because the markdown widget value isn't directly controlled by the Redux state object, but rather maintains its own state and updates the Redux store as necessary.

Ideally, rather than attempting to address this in the markdown widget, we should provide a high level solution that can be adopted by other widgets that manage their own value state.

Related to #901.

**Comment by nop33** [comment]
has anyone found a workaround regarding this? :/ I have created an FAQ page with hundreds of entries and now I cannot reorder them...

**Comment by erquhart** [comment]
Reordering does work, the markdown field just doesn't update. If you reorder without editing the markdown fields themselves, the reorder will work. Collapsing the list items helps, as you need to ignore the markdown fields (and don't edit them) until this bug is resolved.

**Comment by nop33** [comment]
Thanks for your reply!

> If you reorder without editing the markdown fields themselves, the reorder will work.

This is not the case. Without touching the content of the list items and simply re-ordering them (collapsed as you suggested), the markdown field contents do not re-order:

![kapture 2018-10-28 at 12 48 05](https://user-images.githubusercontent.com/1579899/47615502-da377680-daaf-11e8-8576-1ede1ade6778.gif)

**Comment by erquhart** [comment]
They don't _appear_ to reorder. If you save after the reorder, you'll see the reorder was effective. That's why I recommended keeping the fields collapsed to avoid confusion during reorder.

Obviously this is extremely janky and not how it should work, just wanted you to have a workaround until we have a fix.

**Comment by nop33** [comment]
Ah, I see. Thanks for the feedback!

**Comment by erquhart** [comment]
Closed in #2129.

**Comment by unyo** [comment]
@erquhart This bug seems to still be occurring in netlify-cms-app@2.9.7, re-ordering a list updates non-markdown fields but the markdown fields show out of date text until you toggle Rich Text / Markdown.

**Comment by erquhart** [comment]
I've been overhauling the markdown widget for a while (just got put on hold for a bit), a fix for this will be included.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
