### ISSUE TITLE
Collapse/expand all for list widget

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#756]
List widgets get unwieldy when they have more than a couple of items - expand/collapse all functionality would help.

**Comment by erquhart** [comment]
I no longer think we should "collapse all" objects within a list, as we're already collapsing the list and are soon to implement object widget closing as well in #851. Closing in favor of that.

**Comment by Benaiah** [comment]
@erquhart the PR implementing this feature (#912) notes one major usecase: sorting the list items. I think it's worth taking another look at the feature for that, particularly since we have an implementation in a PR already (though that PR needs to be a little more sophisticated before merging).

**Comment by erquhart** [comment]
Yeah I checked that PR and came to the exact same conclusion right after making my previous comment lol. More discussion going on there now.
