### ISSUE TITLE
Add ability to edit a component

### ISSUE THREAD

**Issue by arikfr** [netlify/netlify-cms#762]
**- Do you want to request a *feature* or report a *bug*?**

Feature.

**- What is the current behavior?**

After a component is added to the text it can no longer be edited from the WYSIWYG editor, but only from markdown view. It will be nice if when doubled clicked the component will open the component editor.

**Comment by erquhart** [comment]
Totally agree - this is something to look into once the v1 redesign is out in December.

**Comment by erquhart** [comment]
Fixed in 1.0 - that form you used to edit when inserting an editor component _is now the component_ within the editor, always there to edit the value.
