### ISSUE TITLE
Netlify CMS "authorized popup"

### ISSUE THREAD

**Issue by VitaliiZhukov** [netlify/netlify-cms#770]
Hi!
I've met a weird CMS behaviour. I have a private repo on github and the website is stored on AWS with a custom domain.
After setting up the custom domain (like it is in placeholder
![screen shot 2017-10-31 at 20 05 43](https://user-images.githubusercontent.com/10582247/32237799-fcc1ff32-be76-11e7-91e1-018811f64530.png)
) I could go to /admin page and see a "login with github" button. But after authorization process was complete I only had a hanging popup window with a line "Authorized". No errors,  console was clean.
![screen shot 2017-10-30 at 20 18 57](https://user-images.githubusercontent.com/10582247/32237685-ab0aba62-be76-11e7-954a-cbc9f21cb9a4.png)

Finally I've found the way to complete the process - I had to remove "www." from custom domain field, and it worked well. (Thanks to https://github.com/erquhart)
But solution wasn't obvious without any warnings or errors. And placeholder has "www" prefix.

Thanks!

**Comment by erquhart** [comment]
@delwin for sure - we just need to be able to reproduce the issue live. Can you share the link to your site? (dcv.ampul.com doesn't appear to be live.)

**Comment by katabame** [comment]
same like delwin here,
My site has hosted with Netlify subdomain and I can't log into netlify-cms.

For your reproduce, below is site domain and repository.
Site: http://blog.kataba.me/
Repo: https://github.com/katabame/kataba.me/tree/blog

**Comment by tech4him1** [comment]
Thank you so much for the repro case @katabame! I think I've found the issue.

The problematic code is on https://api.netlify.com/auth/done, the page that shows the "Authorized" screen.
```js
console.log("Got host: %o", host);
if ( host === "katabame.netlify.com" ||  host === "kataba.me" ||  host == "localhost") {
  window.opener.postMessage(
    'authorization:github:success:{\"token\":\"an-example-token\",\"provider\":\"github\"}',
    e.origin
  );
}
```

The problem is that you are logging in from a subdomain, `blog.kataba.me`, but the Netlify authorization code only works for the root domain, `kataba.me`.

@erquhart @bcomnes @biilmann Can this code be fixed, or do logins need to be restricted to top-level domains only?

**Comment by tech4him1** [comment]
@erquhart I assume that we'll still have a "real" fix at some point? Not everybody can or will use Git Gateway.

**Comment by erquhart** [comment]
Not really a bug, auth only works against your custom domain. @delwin would need to change his Netlify site domain to "dcv.ampul.com", and @katabame would change his to "blog.kataba.me".

To request improvements in functionality, or to get other ideas about how to work around this, reach out in Netlify's community [Gitter](https://gitter.im/netlify/community) or submit the request to support@netlify.com.

**Comment by katabame** [comment]
I leave a note for @delwin or who in similar situation.

As https://github.com/netlify/netlify-cms/issues/770#issuecomment-377334439 say, I need to auth with git-gateway.
Here is detailed steps that I did.

1. Add `<script src="https://identity-js.netlify.com/v1/netlify-identity-widget.js"></script>` in your CMS `index.html` header.
    See [this](https://github.com/katabame/kataba.me/blob/blog/source/admin/index.html#L11) for example.
1. Rewrite your CMS `config.yml` backend section.
    You'll need specify branch if you're using subbranch for your site.
    See [this](https://github.com/katabame/kataba.me/blob/blog/source/admin/config.yml#L1-L3) for example.
1. Add `Git-Gateway` Identity from your netlify dashboard.
    I recommend change `Registration preferences` setting to `Invite Only`.
1. Invite yourself
    You'll receive email from netlify. When you click `Accept the invite` link, you'll jump to `YourTopDomain.com/#invite_token=TOKEN` (for me, `https://kataba.me/#invite_token=TOKEN`).
    But that link will not work, you need to rewrite&access link to `Subdomain.YourTopDomain.com/#invite_token=TOKEN` (for me, `https://blog.kataba.me/#invite_token=TOKEN`)
    Then netlify identity will ask you for set your password.
1. Now you can login to netlify-cms dashboard.

**Comment by Brondahl** [comment]
@katabame Thanks for that blow-by-blow; it's really helpful!
Can I suggest linking point 3 to the Identity docs (here: https://www.netlify.com/docs/identity/ ) and/or including the current step-by-step instructions:
i) From the Netlify Dashboard, Select 'Identity' and "Enable Identity".
ii) (Recommended) In the settings page that then opens up scroll down to Registration and set "Invite Only".
iii) Scoll further down to Services and click "Enable GitGateway".

(If you could edit that into your post, I think it'll make this thread more useful for other devs - it's always annoying to trawl through a thread trying to piece together the necessary steps from multiple posts. :)

**Comment by katabame** [comment]
@Brondahl 
> (If you could edit that into your post, I think it'll make this thread more useful for other devs - it's always annoying to trawl through a thread trying to piece together the necessary steps from multiple posts. :)

Yes, it's so annoying. I edited the post, no annoying anymore!

**Comment by erquhart** [comment]
@tech4him1 @Brondahl I think you're misunderstanding - Git Gateway and Netlify Identity aren't a temporary workaround, they're Netlify's answer for (among other things) authenticating against a Netlify site domain and it's subdomains. The GitHub/Bitbucket/GitLab backends on their own make use of a freebie auth server that we provide to everyone at cms.netlify.com, but if you want to authenticate for all of your branch subdomains on Netlify, use Netlify Identity.

**Comment by robsonsobral** [comment]
@erquhart , hi!

Please, is there a way to login on my staging domain using BitBucket? Thank you!

**Comment by tech4him1** [comment]
@erquhart Will the "https://api.netlify.com/auth" server be deprecated then, and people be forced to us Git Gateway?

**Comment by erquhart** [comment]
@Brondahl Netlify's own auth works only for a single domain, you'll need to create a separate Netlify site for your staging domain.

@tech4him1 no, not at all, just not as robust as Identity, that's all.

**Comment by n33m4** [comment]
Like some other users, I couldn't login to netlify-cms on my website, because after trying to login with my github account, the login popup said **Authorized** but then nothing happened. I was trying to setup a Jekyll website using github pages and github backend (and netlify authentication server). In my case, just adding the property `site_domain: <username>.github.io` to `backend` field in config.yml did not solve the problem. I also had to set `<username>.github.io` as my site domain in netlify dashboard. That solved the problem for me and I could login using my github account.
