### ISSUE TITLE
Oauth: Problem fetching repo data from GitHub

### ISSUE THREAD

**Issue by davidebe** [netlify/netlify-cms#772]
While trying to login to access the content manager I get a yellow toast message saying "not found"

the errors in the console are:
`https://api.github.com/repos/owner/repository?ts=1509484800647 404 (Not Found)`
`Problem fetching repo data from GitHub`

I've followed the steps for creating a blog using the netlify cms and added an oauth app to github. Is there anything else that I'm missing?

![screen shot 2017-10-31 at 5 28 13 pm](https://user-images.githubusercontent.com/859247/32249900-ef7ec744-be60-11e7-96a4-a4dbb05589e1.png)

**Comment by tech4him1** [comment]
@davidebe Is this an organization repo? If so, please make sure that your organization has granted access to the CMS, under the CMS entry in https://github.com/settings/applications.

**Comment by Benaiah** [comment]
It looks like the CMS hasn't been correctly configured - `owner` and `repository` in the API url you gave (`https://api.github.com/repos/owner/repository?ts=1509484800647`) seem to be example values that were meant to be replaced with your own username and repository. There's no such `owner/repository` repo on Github (see https://github.com/owner/repository), hence the 404. I suspect you've pasted an example `config.yml` without filling out the config with your own info. Could you link or paste your `config.yml`? Even if that's not the issue you're seeing, the config will help with debugging.

**Comment by davidebe** [comment]
Hi @Benaiah and thanks a lot, managed to fix it (with some help) also by putting the repo information in the admin/config.yml. 

🙏
