### ISSUE TITLE
bug: list fields do not default to empty list

### ISSUE THREAD

**Issue by r1b** [netlify/netlify-cms#782]
**- Do you want to request a *feature* or report a *bug*?**

Report a *bug*

**- What is the current behavior?**

List fields do not default to an empty array

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a collection with a `list` field that has no `default` value
2. Attempts to save the collection without populating the list field with an empty object will fail with a crash.
3. Adding a `default: []` entry to the `list` field fixes the issue

**- What is the expected behavior?**

List fields should always default to an empty array without user intervention.

**- Please mention your CMS, node.js, and operating system version.**

CMS version: v0.5.0  
Node.js version: v8.6.9  
OS version: Varies, Ubuntu LTS or OS X

**Comment by erquhart** [comment]
Fixed in 1.0.

**Comment by r1b** [comment]
Thanks!
