### ISSUE TITLE
Duplicate uploading same asset name

### ISSUE THREAD

**Issue by talves** [netlify/netlify-cms#783]
**- This is a *bug*?**

**- What is the current behavior?**
![](https://user-images.githubusercontent.com/784848/32533819-6fa3f740-c407-11e7-874d-dc51355754f8.png)

**- Reproduce.**
Open the media library ui and upload the same asset. A duplicate will show as in the picture above.

**- What is the expected behavior?**
Should only show one thumbnail per item

**- Please mention your CMS, node.js, and operating system version.**
Chrome Browser, et. al.

**Comment by erquhart** [comment]
Since GitHub doesn't paginate, we could actually just check the array of images in memory for an image of the same name and remove the old one if it exists.
