### ISSUE TITLE
netlify-cms oauth in golang

### ISSUE THREAD

**Issue by igk1972** [netlify/netlify-cms#784]
Hi!
Inspired by [netlify-cms-github-oauth-provider](https://github.com/vencax/netlify-cms-github-oauth-provider) (node-js), and I created my implementation on Go lang.

See [netlify-cms-oauth-provider-go](https://github.com/igk1972/netlify-cms-oauth-provider-go)

Maybe it's interesting to someone.

**Comment by erquhart** [comment]
Nice!!! Leaving this open until it's added to the [docs](https://www.netlifycms.org/docs/custom-authentication/#external-oauth-clients). Thanks!

**Comment by tech4him1** [comment]
@igk1972 Feel free to submit a PR to our (docs)[https://github.com/netlify/netlify-cms/blob/master/docs/custom-authentication.md] to add this.

**Comment by tech4him1** [comment]
Closed by #823/#845.
