### ISSUE TITLE
Gallery Widget

### ISSUE THREAD

**Issue by hhsnopek** [netlify/netlify-cms#8]
see [TODO.md#gallery-widget](https://github.com/netlify/netlify-cms/blob/master/TODO.md#gallery-widget)

**Comment by lexoyo** [comment]
Hello
I'm interested in widgets in general and a gallery widget in particular
The TODO.md file is missing, do you know if it has been moved or deleted?

**Comment by biilmann** [comment]
@lexoyo the TODO.md got lost in the process when we switched from the old Ember based ersion to the new React based version, and we're planning on starting to use issues and GitHub projects to track TODOs.

A gallery widget would be super useful - are you interested in helping out creating one?

Could be by contributing code or by working on UI/Design, gathering examples of the best CMS gallery widgets out there, etc...

**Comment by lexoyo** [comment]
Sure, let me try
But do you think I could start with a slide show widget? It would be more useful to me... Should I open an issue about it? Or should I stick to the gallery widget?

**Comment by lexoyo** [comment]
Ok so I thought about this and have a question: this would be about making the widget editor and the layout file which displays the gallery or just the widget edtor?

I am trying to get my hands in the code right now

**Comment by lexoyo** [comment]
[This is how squarespace do it](https://support.squarespace.com/hc/en-us/articles/208404698)
![](https://support.squarespace.com/hc/en-us/article_attachments/202983118/add_gallery_content.jpg)
![](https://support.squarespace.com/hc/en-us/article_attachments/202983178/add_image.jpg)
![](https://support.squarespace.com/hc/en-us/article_attachments/202914557/change_status.jpg)

[This is how weebly do it](https://hc.weebly.com/hc/en-us/articles/201273653-Upload-Multiple-Images-w-Slideshows-and-Galleries) but it has front end and admin mixed up (we would handle that with layouts)

![](https://cdn2.editmysite.com/images/landing-pages/global/features/Photos-Slideshows/photo-upload.png)
![](https://hc.weebly.com/hc/en-us/article_attachments/203661058/ss_tool_box.png)

**Comment by erquhart** [comment]
@biilmann I'm thinking the repeatable functionality that's coming will supercede this via repeatable image fields. Is this filling any other gaps you can think of? Otherwise we can close.

**Comment by Benaiah** [comment]
@erquhart yeah, I think a list widget with a custom preview would handle this use case smoothly.

**Comment by PaulEibensteiner** [comment]
If someone already created such a custom editor component, could you share it? (@erquhart?)
I do have problems accessing the nested fields and returning a variable amount of regex matches...thx in advance

**Comment by erquhart** [comment]
This isn't for an editor component, it's for a widget. I'm not aware of anyone having created one yet, that's what this ticket is for.

**Comment by owenhoskins** [comment]
@tech4him1 @PaulEibensteiner I've done some initial explorations into how to tackle this but I am a long way out from a solution as of yet. I'll be able to invest some time over the course of the next few months and would be happy to help if anyone wants to take a stab at it.

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
