### ISSUE TITLE
Relation doesn't work for collections defined within a file-based collection

### ISSUE THREAD

**Issue by ilyabo** [netlify/netlify-cms#800]
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
Currently it doesn't seem possible to define a relation referring to a collection within a file-based collection.

**- If the current behavior is a bug, please provide the steps to reproduce.**

Say I have a collection of sections defined in settings:

      - name: "settings"
        files:
          - name: sections
            file: "data/sections.yml"
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Label, name: label, widget: string}

Then I want to make a collection of pages where each page would refer to a section:

      - name: pages
        folder: "src/pages"
        create: true
        slug: "{{slug}}"
        fields:
          - {label: "Path", name: "path", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {name: section, widget: relation, collection: sections, valueField: name}

Well, this doesn't work. The field "Section" is not linked to the sections collection in settings.

**- What is the expected behavior?**

The field "Section" should be linked to the sections collection in settings.

**- Please mention your CMS, node.js, and operating system version.**
0.7.0

**Comment by erquhart** [comment]
In your example, `sections` is not a collection - it's an entry within the `settings` collection.

I haven't actually tried using a relation this way, but it's definitely a valid use case. We need to peek at what's available from the matched collection in this case, not certain what it would do at the moment.

If you give it a shot with my correction above, comment back with your findings!

**Comment by ilyabo** [comment]
Can a file based collection be at the top level? I thought it has to reside in a collection with "files:". I think I even have tried to put it at the top at some point, but will try again.

**Comment by erquhart** [comment]
The collection with "files" is the top level collection - the bits inside are entries.

**Comment by erquhart** [comment]
Update: yeah relation widget doesn't work for file collections - it's built to search a folder of files that share the same data model. We'll need to consider how relations with one-off files could work.

**Comment by shaunbent** [comment]
Hello, I wonder if there has been any movement on this issue? I have just tried to do the same thing and found that it is not possible.

**Comment by erquhart** [comment]
Current status is that this is a reasonable feature request, definitely open to someone digging in and feeling out how it might work. Discussion in that vein can continue here in this issue.

**Comment by mittalyashu** [comment]
My use-case for using relation widget is to fetch the data from `_data/author.yml` file and while creating a post it should show the list of the author from the same `yml` file so that I can select the appropriate value.

**Comment by Arenal94** [comment]
> My use-case for using relation widget is to fetch the data from `_data/author.yml` file and while creating a post it should show the list of the author from the same `yml` file so that I can select the appropriate value.

How is the status of this feature? I'm in the same use-case.

**Comment by erquhart** [comment]
The fundamental issue is that relations work by searching for a specific field in each entry of a collection. File collections don't share the same field configuration.

That said, I suppose we could just implement it with the understanding that we're expecting specific fields to be present in all entries, eg. they all have a "name" field.

**Comment by Arenal94** [comment]
@erquhart It would be amazing !! 

Speaking from my own case, the fields will be present in all the entries because this file collection is totally managed by the admin panel of Netlify-CMS, and to be a valid entry is necessary to have a "name" field. 

I think, (if its possible) It would be great to specify something like a "primary key" in the file collection to avoid forcing the files to have a "name" field.

I would be pleased to help you in this feature, but atm I´m working on my corporative website (which I want to be managed by your awesome CMS).

Thank you for your time.
Adrián.

**Comment by erquhart** [comment]
If you do get time we're happy to support the effort! Otherwise, we'll leave this open and see if anyone else is interested in taking it on.

**Comment by dawaltconley** [comment]
I don't know if there's been any movement on this, but this seems to be working for me. I have a `_data/videos.yml` file that looks kinda like this:

```
categories:
  - director
  - editor
source: Vimeo
```

And a `config.yml` file like this:

```
collections:
  - label: Data
    name: data
    files:
      - label: Videos
        name: video-data
        file: _data/videos.yml
        fields:
          - label: Categories
            name: categories
            widget: list
          - label: Source
            name: source
            widget: string
  - label: Videos
    label_singular: Video
    name: videos
    folder: _posts
    fields:
      - label: Source
        name: source
        widget: relation
        collection: data
        searchFields: categories
        valueField: categories
```

If I create a new `_data` file with a `source` property and add it to the `data` collection, it's source also becomes available to the relation widget.

I agree though that it would be nicer if you could refer to _specific_ files from the relation widget, so that not all of the files in a collection need to share the same property. Maybe by `collection: {{ collection }}/{{ entry_name }}` or something.

**Comment by d4rekanguok** [comment]
I ran into the same problems & implemented my own relation widget in the end. As of 2.4, `loadEntry` method is available to widgets. You can use this method to load entry from other collections, including file one.

config.yml 
```yml
collections:
  - name: collection-name
    files:
      - name: file-name
```
widget
```js
class FileRelationWidget extends React.Component {
  async componentDidMount() {
    const { loadEntry } = this.props
    
    try {
     const result = await loadEntry('collection-name', 'file-name')
     const { data } = results.payload.entry
     /* do stuff */
    } catch (err ) {  ... }
  }
  render() {
    return ( /* input stuff */ )
  }
}
```

**Comment by SixFingeredAmish** [comment]
@dawaltconley I tried following your instructions. It doesn't seem to work for me. Do you have to output the data file in your static generator?

**Comment by jonaseltes** [comment]
@d4rekanguok Any chance you'd share you the full widget? 😊

**Comment by d4rekanguok** [comment]
@jonaseltes Sure! [the code is over here](https://github.com/d4rekanguok/netlify-cms-widgets/tree/master/packages/widget-file-relation), I've recently published it as a package.

It can be install with
```
npm i @ncwidgets/file-relation
```

If you're interested you can find an example usage in the same repo:
- [register widget](https://github.com/d4rekanguok/netlify-cms-widgets/blob/7cd27d7b7125f749a5c8aa4590e97761ec775ead/packages/playground/index.js#L52)
- [usage in config.yml](https://github.com/d4rekanguok/netlify-cms-widgets/blob/7cd27d7b7125f749a5c8aa4590e97761ec775ead/packages/playground/static/config.yml#L26)

I'll add a readme when I can get near a computer later. If you decide to try it out, please let me know if you run into any issues, thanks!

**Comment by jonaseltes** [comment]
@d4rekanguok In case it wouldn't be too much work an example of using inline creation & registration directly (no NPM) would be amazing! As seen here https://www.netlifycms.org/docs/custom-widgets/#registerwidget

Let me know if too much of work and I'll try figure it out.

**Comment by erquhart** [comment]
Awesome work @d4rekanguok!

**Comment by d4rekanguok** [comment]
@erquhart Thank _you_ for your work! `loadEntry` has been working well for me, I'm also using it in [another widget](https://github.com/d4rekanguok/netlify-cms-widgets/tree/master/packages/widget-reorder)

I did get an interesting issue recently (https://github.com/d4rekanguok/netlify-cms-widgets/issues/17) where using file-relation inside the same entry as its target list crashes the browser. It seems like `loadEntry` is causing a infinite loop somehow, I haven't looked too much it yet.

**Comment by erquhart** [comment]
Yeah that's the kind of thing I'm concerned about. We exposed `loadEntry` knowing it could cause issues, but wanted to let folks at least try to use it.

**Comment by TidyIQ** [comment]
Can the widget @d4rekanguok created be merged with the standard Netlify CMS widgets?

**Comment by brunetton** [comment]
Just run onto the same issue. As @TidyIQ suggested, @d4rekanguok widget should be added to satndard widgets, or at least to beta features. 
Why do you think about @erquhart ?

**Comment by d4rekanguok** [comment]
We've just linted out an issue with `loadEntry` recently (huge thanks to @erezrokah who addresses it in record time) & it feels very stable now! I'll try to submit a wip PR to the default relation widget & see if it can be moved forward.

If you can't add a build pipeline to your project & this feature is deterring you from using netlify-cms, I've just published a custom netlify-cms build that includes 2 additional custom widgets: `file-relation` and `id`. This could be a good temporary workaround.

Swap your inline script as below:

```diff
- <script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
+ <script src="https://unpkg.com/@ncwidgets/netlify-cms@^0.7.0/dist/netlify-cms.js"></script>
```
For a more detail on how to use the custom file-relation widget, please refer to the [readme here](https://github.com/d4rekanguok/netlify-cms-widgets/blob/master/packages/widget-file-relation/readme.md)

**Comment by erezrokah** [comment]
>      - {name: section, widget: relation, collection: sections, valueField: name}

Commenting on the original issue, the `collection` value here should be `settings` and not the file name which is `sections`
