### ISSUE TITLE
Git Gateway: Incorrect author for file deletion.

### ISSUE THREAD

**Issue by tech4him1** [netlify/netlify-cms#819]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
If an entry is created using Git Gateway, it will show up as being authored by the person who actually saved it. If the entry is deleted, however, the commit will be shown as coming from the Git Gateway owner.

See example here, both of the last two commits were made by me: https://github.com/verythorough/testing-json/commits/0ab590bd59bed4334cc9cb3f5922e5fdfafdeda2.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Use a different user account than the one that set up the site in Netlify/Git-Gateway.
2. Delete an entry (or media file).

**- What is the expected behavior?**
The deletion commit should show the actual user as the committer while deletion.

**- Please mention your CMS, node.js, and operating system version.**

CMS 0.7.0

**Comment by tech4him1** [comment]
This may be related to the fact that the code for deletion sends the request directly, instead of using the `commit` function (which sets the author):
https://github.com/netlify/netlify-cms/blob/1acdb8ddf5051edf103ca3d2475f53c91110e513/src/backends/github/API.js#L298

**Comment by erquhart** [comment]
@erezrokah can you check whether we're still doing Git Gateway deletions without setting the author?

**Comment by erezrokah** [comment]
Doesn't reproduce here https://github.com/erezrokah/netlify-cms-reproductions/commits/netlify_cms/issue_819 (tested with git-gateway)
