### ISSUE TITLE
Delete entry. Failed to delete entry: API_ERROR: Not found

### ISSUE THREAD

**Issue by aleksand88** [netlify/netlify-cms#821]
Netlify CMS version 0.7.4

I tried to delete entry from admin panel and received message:
`Failed to delete entry: API_ERROR: Not found`

This is from console - https://prnt.sc/havsi6

**[SOLVED]**
There was a wrong path in config.yml
`collections:
name: "news"
label: "News"
folder: "/content/news"`

folder should be `content/news` with no `/` before

Also about `static/images/`
I added this like it in docs - https://www.netlifycms.org/docs/quick-start/#configuration But this path looks like not right.
I use Hugo and the path in `media_folder` should be relative to root:
`media_folder: "themes/v2-styled/static/images"` - that works well with no errors.

**Comment by tech4him1** [comment]
@aleksand88 I'll go ahead and close this, since you resolved the issue. If you want to, please feel free to open an issue about not breaking when there is a leading slash.

**Comment by jvoros** [comment]
Thank you for posting your solution. Helped me fix my bug.
