### ISSUE TITLE
GatsbyJS Integration

### ISSUE THREAD

**Issue by zionis137** [netlify/netlify-cms#838]
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
It is quite hard to set up a (customized) netlify-CMS on GatsbyJS. 

**- What is the expected behavior?**
A gatsby plugin which integrates netlify-CMS nicely in Gatsby. Gatsby is based on React, hence the parameter for the `registerPreviewTemplate` function could be automatical generated. 
Also the "Hot-Reload" function from Gatsby is great function when customizing the CMS.

A simpler alternative would be a starter-template (#16) for GatsbyJS using `registerPreviewTemplate`.

**Comment by tech4him1** [comment]
@zionis137 Have you seen this starter template yet: https://github.com/AustinGreen/gatsby-starter-netlify-cms?

**Comment by erquhart** [comment]
Note for posterity - there is now an official plugin for Gatsby: https://www.npmjs.com/package/gatsby-plugin-netlify-cms
