### ISSUE TITLE
Date widget doesn't respect format attribute

### ISSUE THREAD

**Issue by biilmann** [netlify/netlify-cms#841]
We're seeing an issue with a date widget defined like:

```
- {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
```

Where the output in the front-matter ends up being `11/23/2017 7:35 AM`.

**Comment by tech4him1** [comment]
I think this is a duplicate of https://github.com/netlify/netlify-cms/issues/529?

**Comment by biilmann** [comment]
True! Closing
