### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by vuhuong155** [netlify/netlify-cms#849]
Dear team, after install i got this error screen, without any bug report, can you help me to solve this?
https://imgur.com/a/E6JN6

**- Do you want to request a *feature* or report a *bug*?**

**- What is the current behavior?**

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Please mention your CMS, node.js, and operating system version.**

**Comment by tech4him1** [comment]
Can you provide a link to your config.yml?

**Comment by tech4him1** [comment]
@vuhuong155 Looking at your site, we don't support GitLab as a backend yet, although it is a work in progress: https://github.com/netlify/netlify-cms/pull/517.
