### ISSUE TITLE
Assets renamed/moved? (main.js and main.css)

### ISSUE THREAD

**Issue by magnify** [netlify/netlify-cms#85]
Did the assets from the example at https://github.com/netlify/netlify-cms#installing move or get renamed?

**Comment by calavera** [comment]
I'm not completely sure they are valid at the moment, but @cassiozen will know better

**Comment by cassiozen** [comment]
Hi @magnify - We'll publish a snapshot to the correct address this week. 

In the meanwhile, you can access the last snapshot files on these urls:
https://d33wubrfki0l68.cloudfront.net/css/36fbfca7f51af5d058771a2e4ebec58472c0af4c/cms.css
https://d33wubrfki0l68.cloudfront.net/js/9cbdf4934d23e8fcc0ce7eb3cb4ea02e410b6f76/cms.js

**Comment by magnify** [comment]
Thanks!
