### ISSUE TITLE
Collapse Object widgets

### ISSUE THREAD

**Issue by custa1200** [netlify/netlify-cms#851]
I am using Object types to organise sections. it would be great if they could be collapsed and expanded, ideally defaults set in the config.yml

**Comment by erquhart** [comment]
We have collapsible lists and list items in the UI overhaul, collapsing objects wouldn't be a stretch. I don't think we'd put it in the config just yet, but I have considered it for collapsible items in general.

I think after 1.0 we could put this in.

cc/ @neutyp

**Comment by neutyp** [comment]
Dumb question: what is an object as opposed to a widget? 

What is the benefit of seeing these collapsed, and what would they show when collapsed?

**Comment by tech4him1** [comment]
@neutyp An object is one of our widget types, that is simply used to group other widgets together.
![capture](https://user-images.githubusercontent.com/20345941/34084581-598c6ed0-e340-11e7-9723-b89a61790eb2.JPG)

**Comment by neutyp** [comment]
Aha! Thanks! This should and could easily collapse in the same way that lists do :) Design should be the exact same, without the button at right to add another item

**Comment by tech4him1** [comment]
@neutyp In most cases, the user should not be able to add an item. @erquhart @Benaiah Is there any reason that we would want an `object` widget to be user-editable?

**Comment by neutyp** [comment]
FYI, I wasnt implying the ability to re-arrange or delete (which are possible in list widget). I just meant the collapse function can look the exact same

**Comment by tech4him1** [comment]
Oh, of course, I misread your statement. The term `object` is what we call a group in JavaScript code, so I guess it just got carried over to the widget name :).

**Comment by erquhart** [comment]
@drlogout provided a PR for this a while ago, getting it merged now. It does reuse the styling of the list expand/collapse functionality as expected.

@neutyp I do intend at some point to rename "object" to "group", agreed.

**Comment by tech4him1** [comment]
@erquhart @neutyp What about renaming it to `group`, but leaving `object` as a depreciated option?

**Comment by erquhart** [comment]
@tech4him1 agreed.

**Comment by andreasvirkus** [comment]
Hi there, any action on this? Would love to see collapsed objects.

My reason is that I'm defining every JSON field for a translation file and the nesting is quite heavy.
Collapsed objects/groups would make the navigation _a lot_ more user-friendly.

**Comment by erquhart** [comment]
Just needs design and elbow grease :)
