### ISSUE TITLE
Color type

### ISSUE THREAD

**Issue by custa1200** [netlify/netlify-cms#852]
It would be handy to add a color Type to the list of widget that could use the native color pickers as a minimum

**Comment by tech4him1** [comment]
@custa1200 You can always add a custom widget to your CMS, like this: https://www.netlifycms.org/docs/extending/#registerwidget.

**Comment by erquhart** [comment]
I wouldn't mind this as a core widget either. We're probably going to get rid of the concept of core widgets anyway to some extent after 1.0.

@custa1200 it'd be pretty cool to integrate this into a widget: https://casesandberg.github.io/react-color/

I'd envision an input sized box that is colored with the selected color, and with the color value in the middle. Clicking could just trigger one of the popup styles widgets in the demo there.

Config options should probably include:
* format (String) (default: `'hex'`) - one of `'hex'`, `'rgb'`, `'rgba'`, or `'hsla'`
* defaultColors (Array) (optional) - array of color values to display for click selection
* allowInput (Boolean) (default: `false`) - whether to allow a raw value to be manually entered, setting this to `true` requires that `defaultColors` be defined

Thoughts?

**Comment by custa1200** [comment]
Would be nice to have a lookup to a bunch of predefined colours too. Being that I’m trying to use this as a theme creator back end for
Something it would be great to be able to
define a list of colours elsewhere that it could consume.

**Comment by tech4him1** [comment]
@custa1200 Do you think @erquhart's idea of `defaultColors` above would be what you are looking for?

**Comment by custa1200** [comment]
I think that would be a great starting point. My use case would be I’d also like to be able to have a user add a list of theme colours and then be able to choose from that list for other items.

**Comment by erquhart** [comment]
I mentioned the concept of a third "meta" entry type to complement the collection and singles types we've been discussing. That was for curating a collection of tags for use throughout CMS entries. This would benefit from similar treatment.

**Comment by dumptyd** [comment]
Are there any plans to add this as a core widget or having a generic `input` widget that would support most of the input types listed here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#%3Cinput%3E_types?

**Comment by erezrokah** [comment]
@dumptyd this is a good candidate for contribution.

**Comment by felixboet** [comment]
Thanks @erezrokah to point me here. [Here](https://github.com/felixboet/netlify-cms-widget-colorpicker/) is the color-picker I created based on react-color. [Here](https://colorpicker-widget.netlify.app/#/collections/colors/entries/colors) is the live example

I would propose to not allow as many color-pickers from react-color, as I do now, because some are not working correctly and it would be some work to fully supportthem all. To keep it simple we could just use the "chrome picker" and keep my custom widget for advanced usecases?

**Comment by felixboet** [comment]
Here is [my proposal for the color widget](https://github.com/felixboet/netlify-cms/tree/852-Color-Widget), suggestions and feedback welcome!

I added two options:

- "disableAlpha" (defaults to false) to hide the alpha slider in the color picker
- "editable" (defaults to false) so by default you can just use the color picker to prevent input of invalid color strings in the string field.

 ... but I am not happy with the option title "editable", it could be misleading - any other suggestions?

And there is already an (unmaintained) NPM module called "netlify-cms-widget-color" ... any idea what's the best way to solve that? ask the author to transfer ownership?

**Comment by felixboet** [comment]
maybe better to disable alpha by default / change to "enableAlpha"?

**Comment by felixboet** [comment]
> 
> ... but I am not happy with the option title "editable", it could be misleading - any other suggestions?
> 

found the proposal "allowInput" by erquhart above, sounds good for me

**Comment by erezrokah** [comment]
> Here is [my proposal for the color widget](https://github.com/felixboet/netlify-cms/tree/852-Color-Widget), suggestions and feedback welcome!

Do you mind opening a PR? This way it will get more visibility. You can keep it as draft until it's ready.

> There is already an (unmaintained) NPM module called "netlify-cms-widget-color" ... any idea what's the best way to solve that? ask the author to transfer ownership?

`netlify-cms-widget-color-picker`?

**Comment by felixboet** [comment]
> Do you mind opening a PR? This way it will get more visibility. You can keep it as draft until it's ready.

@erezrokah done, anything to do to mark it as a draft?

**Comment by erezrokah** [comment]
Thanks @felixboet, this is a small link to do it:
![image](https://user-images.githubusercontent.com/26760571/95677979-0f243180-0bd2-11eb-88e2-9fc691fd13bb.png)

I went ahead and clicked it for you 😄
