### ISSUE TITLE
Scroll sync broken in Safari

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#859]
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

Attempting to scroll in the editor with scroll syncing on causes scroll position to jump to the bottom of the entry and remain there.

**- If the current behavior is a bug, please provide the steps to reproduce.**

* Open a lengthy [entry](https://cms-demo.netlify.com/#/collections/kitchenSink/entries/a-big-entry-with-all-the-things)
* Try to scroll the control panel

**- What is the expected behavior?**

Scrolling should work, and the two panes should scroll in sync

**- Please mention your CMS, node.js, and operating system version.**

CMS 0.7.6

**Comment by erquhart** [comment]
Note: until this is fixed, you can turn off scroll syncing via the double-arrow button in the upper right corner of the editor.

**Comment by erezrokah** [comment]
Closing as stale. This doesn't seem to happen with latest CMS and Safari
