### ISSUE TITLE
UI components

### ISSUE THREAD

**Issue by okonet** [netlify/netlify-cms#86]
Since we still don't have any reusable UI components (like buttons or dropdowns) in place, I'd like to start a discussion about bringing in a UI library like [react-toolbox](https://github.com/react-toolbox/react-toolbox).

Pros of react-toolbox are:
- It is modular and we can include only needed modules into the bundle
- It is easily to theme
- It uses CSS-modules underneath, so it's even easier to change the look if we need to
- It has a set of _consistent_ UI components. I don't like the idea of having tons of different 3rd party UI components in place since they will have different APIs and different UX
- It follows Material Design, which is also a very well thought design system for UIs
- It is responsive out of the box

Cons are:
- It uses Sass to generate its own CSS. This is okay but still an additional dependency in the build process
- It follows Material Design, so it will look like it, even if we change colors (I personally like it, but decided to put it here)

After doing some work I've done on #81, it feels like a time waste and I'd just use the UI components from the react-toolbox directly.

I honestly don't think that investing into our own UI library is worth the time at this moment but I'd like to hear some feedback in this regard.

Thoughts @cassiozen @biilmann?

**Comment by cassiozen** [comment]
We are indeed running now, but we want this to be a long living open-source project. I agree on making some concessions to speed up development for now, but not one that could impact this longer term vision.

To give an specific example: I'm ok on using a UI library for now, but I would prefer to avoid using one that is irreversibly tied to material design.

**Comment by cassiozen** [comment]
Since we're already using it, I think we should keep using it until we deliver a polished CMS version for Smashing. We could open a "Refactor" milestone right now and add a task to remove 'react-toolbox'

**Comment by okonet** [comment]
Okay what are other alternatives? I'm not married with the MUI. But time the choice should be a solid visual framework that allows us build UI fast and in a consistent way. 

One more though is if should go away from using CSS at all and switch either to inline styles or some CSS-in-JS solutions or there. Right now I'm having troubles each time I pull from master because someone has added some global CSS again. And there is no way of disallowing this at the moment.

**Comment by cassiozen** [comment]
But we're using CSS Modules, there's no reason why anyone should be updating global CSS.... When did that happen?

**Comment by okonet** [comment]
I can find out exact commit or you can search yourself. The point is: CSS modules still allow you adding global styles. CSS-in-JS doesn't.

**Comment by cassiozen** [comment]
Just to update here based on what we talked on Slack:
1) index.css is full of globals that were ported in a run from the ember version. We should get rid of them
2) We will keep using CSS Modules
3) We will add css linting to discourage the usage of globals in CSS

**Comment by cassiozen** [comment]
We still need to solve the UI issue. 
I vote for: Keep using react-toolbox for now, refactor later (Delay the decision until we have delivered Smashing and have more time to discuss alternatives).

**Comment by okonet** [comment]
Related PR #90

**Comment by okonet** [comment]
> (ideally, we should proxy the usage of react-toolbox through components/UI)

As I mentioned in #81 it looks like a waste of time with no real value to me.

I don't think that refactoring from react-toolbox is very hard though since the API is pretty much good IMO. We shouldn't use some of the features like `icon: String` prop etc but other than that I think it is very close to any other UI lib. Either way since we don't have a lot of screens this task shouldn't take long.

**Comment by cassiozen** [comment]
Ok, I agree to go forward this way.

**Comment by WebStackDev** [comment]
Not sure if you know about these components too: http://elemental-ui.com/
