### ISSUE TITLE
Adding an image to an empty rich text editor doesn't trigger the Image widget

### ISSUE THREAD

**Issue by imorente** [netlify/netlify-cms#895]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**

![add-image-bug](https://user-images.githubusercontent.com/83225/33744922-b0666204-db68-11e7-81e5-f39131c5ecc5.gif)

**- If the current behavior is a bug, please provide the steps to reproduce.**

- Create a new post that has a rich text field
- Click on the editor, then click on the + button and select "Image" from the dropdown
- The image widget appears for a second and disappears, leaving the text `![null]()` 
 
**- What is the expected behavior?**
- The image widget doesn't disappear.

**- Please mention your CMS, node.js, and operating system version.**

Netlify CMS version 1.0.0, Chrome Version 62.0.3202.94 (Official Build) (64-bit), Mac OS Sierra

**Comment by tech4him1** [comment]
I can reproduce, but this only seems to happen with new entries -- if all the content is removed from an existing entry the image widget still works for me.

**Comment by tech4him1** [comment]
Possibly related to #829.

**Comment by tech4him1** [comment]
Looking at Redux, on initial load `entryDraft.entry.data.body` is set to `null` instead of an empty string. Only when it is `null` does the image widget crash.

**Comment by erquhart** [comment]
@tech4him1 moved that bit from your last comment into a separate issue, #956.

**Comment by tech4him1** [comment]
@erquhart No, my comment is not talking about the alt text being `null`. My point was that `entryDraft.entry.data.body` should be set to an empty string initially, so that the image widget didn't crash.

**Comment by tech4him1** [comment]
@erquhart I believe the `null` crashing part was fixed in https://github.com/netlify/netlify-cms/pull/955.

**Comment by erquhart** [comment]
Ah, I see what you mean. Yeah that's a general problem, not sure why things are being set to null. I would assume it's somewhere in our Redux implementation.
