### ISSUE TITLE
UI missalignemnts in Safari

### ISSUE THREAD

**Issue by creativityhurts** [netlify/netlify-cms#914]
Icons are missaligned on Safari 10.1.2 on MacOS Sierra. Tested on https://cms-demo.netlify.com

Could be related to #907 

<img width="186" alt="screen shot 2017-12-11 at 1 33 10 pm" src="https://user-images.githubusercontent.com/435233/33833862-f14aa1f0-de78-11e7-8ee6-9371ff317c80.png">
<img width="347" alt="screen shot 2017-12-11 at 1 35 51 pm" src="https://user-images.githubusercontent.com/435233/33833863-f172a57e-de78-11e7-846c-713f8a0f0ef2.png">

**Comment by erquhart** [comment]
Not happening in Safari 11, (or Firefox 57/Quantum) but we'll take a fix from someone with Safari 10.
