### ISSUE TITLE
Error "MARK_COMPONENTS is not defined" when trying to edit a page

### ISSUE THREAD

**Issue by ilyabo** [netlify/netlify-cms#916]
Seems that the constant `MARK_COMPONENTS` is not imported in `renderers.js`:

![image](https://user-images.githubusercontent.com/351828/33859988-db8f8a8e-ded6-11e7-962d-5260b6561111.png)

**Comment by tech4him1** [comment]
@ilyabo Can we take a look at your config (repo link, maybe)?

**Comment by ilyabo** [comment]
[Here it is](https://github.com/freie-schule-bergmeilen/website/blob/master/static/admin/config.yml)

The error was showing up when I was trying to edit a page with links like this one:
`**[Flyer_Goennerverein](http://www.fsbergmeilen.ch/wp-content/uploads/2015/02/Flyer_Goennerverein.pdf)**
`

**Comment by tech4him1** [comment]
What collection was the page in that was causing the error?

**Comment by ilyabo** [comment]
Pages

**Comment by tech4him1** [comment]
@ilyabo What was the entire content of the page that was causing the error?

**Comment by tech4him1** [comment]
@ilyabo Can you try upgrading your CMS to `^1.0.0`? There were a large amount of fixes to the editor done in that release?

**Comment by ilyabo** [comment]
Yes, it doesn't crash on 1.0.2.

Thanks! The new version looks super cool!
