### ISSUE TITLE
Website: Side menu unusable on medium-sized screens.

### ISSUE THREAD

**Issue by tech4him1** [netlify/netlify-cms#917]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
On my laptop, I cannot see the entire docs menu on the left side of the website, because it overflows the height of my screen. I cannot scroll it either, so it is inaccessible.
![www netlifycms org_docs_widgets_](https://user-images.githubusercontent.com/20345941/33865113-74300bbc-dead-11e7-9b0d-6d08417e6cf5.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**
- Make your browser window vertically smaller or access the [docs site](www.netlifycms.org) on a smaller screen. 
- Try to use the menu in the left sidebar (you may need to open a page with a lot of subheaders, like the [Widgets page](https://www.netlifycms.org/docs/widgets/)).

**- What is the expected behavior?**
The menu should be accessible on all screen sizes.

**Comment by tech4him1** [comment]
cc/ @verythorough @ziburski

**Comment by verythorough** [comment]
I dropped in a quick temporary fix, adding `overflow-y: auto` to the fixed nav. The default browser scrollbar isn't the prettiest, but it keeps the entire menu accessible for now. Happy to see design input for a longer-term solution (or maybe that becomes part of a bigger re-design).

**Comment by erquhart** [comment]
That works great! Overflow scrolling is the standard approach, I don't think we need to improve it - please reopen if you disagree.

**Comment by tech4him1** [comment]
Agreed, thanks!
