### ISSUE TITLE
Custom Editor Widget: toPreview output has no effect

### ISSUE THREAD

**Issue by bkroggel** [netlify/netlify-cms#918]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
Adding a custom editor widget via `registerEditorComponent` appends elements to the markdown editor as well as the preview window that solely follow the principles noted in the `toBlock` section instead of `toBlock` and `toPreview`.

**- If the current behavior is a bug, please provide the steps to reproduce.**
E.g. add the Youtube editor component you can find [in the example section](https://www.netlifycms.org/docs/custom-widgets/#registereditorcomponent) and try to append a video to a blogpost.

**- What is the expected behavior?**
Since there is a `toBlock` and a `toPreview` section associated with every custom editor widget it is expected that the `toBlock` part actually gets added to the text editor while the `toPreview` element gets displayed in the preview window.

**- Please mention your CMS, node.js, and operating system version.**
Netlify CMS version 1.0.2

**Comment by erquhart** [comment]
@bkroggel I'm not able to reproduce this - the example project in the cms repo uses that same example code and the youtube preview works fine.  Here's a live demo to test against: https://cms-demo.netlify.com/#/collections/posts/new

Do you have a live reproduction?

**Comment by bkroggel** [comment]
Thanks for your reply @erquhart.
I restarted chrome with all plugins disabled and it seems to work as expected. Sorry to bother you with that - should have tried that in the first place. 🙈

**Comment by erquhart** [comment]
No problem!
