### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by okonet** [netlify/netlify-cms#92]
We have already plenty of code quality tools in place and with #90 there will be more. 

To ensure the code quality we should use CI to run checks on every PR. Especially since most of CI services are free for open source projects.

Choices are: [TravisCI](https://travis-ci.org/), [CircleCI](https://circleci.com/), [CodeShip](https://codeship.com/). AFAIK all of them support GitHub PRs.

**Comment by calavera** [comment]
We use TravisCI in other OSS projects we have, we should be consistent.

**Comment by okonet** [comment]
Awesome! Can you enable it for this project? I'll take care of `travis.yml`.
