### ISSUE TITLE
Shouldn't `file`be accepted too?

### ISSUE THREAD

**Issue by zapic0** [netlify/netlify-cms#921]
Doc says it's possible to use single `file`:
https://github.com/netlify/netlify-cms/blob/master/website/site/content/docs/collection-types.md#single-file

https://github.com/netlify/netlify-cms/blob/cfbf31b130172d0f2c44fcfa0bcc4d96bd84ef5f/src/reducers/collections.js#L31

**Comment by verythorough** [comment]
Yeah, sorry, the docs were wrong! I've updated them to explain that `file`s should be nested inside a `files` collection.

**Comment by zapic0** [comment]
Thanks!
