### ISSUE TITLE
List View Bad UX

### ISSUE THREAD

**Issue by alteducation** [netlify/netlify-cms#928]
**- Do you want to request a *feature* or report a *bug*?**
Feature/Bad UX Fix

**- What is the current behavior?**
I am using netlify admin to edit this page https://www.alternativeeducation.in/learning-spaces.
which is a json file like this https://github.com/alteducation/web/blob/gh-pages/_data/learning-spaces.json 

The Issue is the add new button for adding new entries is located at the top of the page whereas the input to add new entries show up at the bottom. So for every entry you have to scroll to the bottom to add a new one.  On top of that the entries show up maximized by default this causes the user to scroll down even more and makes the browser lag due to all this content.
Gif:
https://gfycat.com/GrandNeedyDolphin
**- If the current behavior is a bug, please provide the steps to reproduce.**
Please Create An Object Of Arrays and edit it with netlify Admin.
**- What is the expected behavior?**
1. Please Make The Array Items Show Up Minimized By Default like this 
[![img2](https://user-images.githubusercontent.com/20345941/34066979-e3d84a20-e1d6-11e7-82a5-9a3940f9e746.png)](https://postimg.org/image/z6aastdff/)
 
2. When add new is pressed please show the new item on top as opposed to bottom.
3. Please create an option to hide the preview pane by default on select pages or globally. The Preview Pane Creates Extra Lag on Pages with a lot of content. An Option to have it hidden by default is much needed.
**- Please mention your CMS, node.js, and operating system version.**
CMS version 1.

**Comment by neutyp** [comment]
So I'm hearing to requests: 
1. You'd like lists to be collapsed by default.
2. The interface should scroll to the bottom of a list when creating a new entry/list item

**Comment by alteducation** [comment]
1. Yes :)

2. Can we have the '**new entry box**' appear at the top instead of auto scrolling to the bottom.

3. An option to turn off **live preview** (by default) on select pages would be really helpful.

**Comment by tech4him1** [comment]
3. You can already do that, although it doesn't look like it is documented:
```yaml
  - name: "my-collection"
    label: "My Collection"
    editor:
      preview: false # Turn off the live preview for this collection.
    ...
```

**Comment by tech4him1** [comment]
> Regarding the field option name, I believe we should default these to collapsed when an entry is opened, so I'm thinking "expanded" is a good name for the option.
> (@erquhart at https://github.com/netlify/netlify-cms/pull/912#issuecomment-352913491)

1. Should be fixed by #912.

**Comment by tech4him1** [comment]
@neutyp Should number 2 be split into a new issue or would you like it left in context here?
> @alteducation: When add new is pressed please show the new item on top as opposed to bottom.
> @neutyp: The interface should scroll to the bottom of a list when creating a new entry/list item
> @alteducation: Can we have the '**new entry box**' appear at the top instead of auto scrolling to the bottom.

**Comment by neutyp** [comment]
I've opened a more targeted discussion around this topic here: https://github.com/netlify/netlify-cms/issues/963 

Please weigh in with your opinions there :)
