### ISSUE TITLE
Confusing behavior when you add collection config without creating entry file

### ISSUE THREAD

**Issue by carrickjason** [netlify/netlify-cms#929]
**- Do you want to request a *feature* or report a *bug*?**
Both?  Not sure if what is happening is desired behavior.

**- What is the current behavior?**
If you add a file entry to a collection in the `config.yml` file without adding the file at the specified path, The CMS simply shows 'No Entries' for that collection.  If you remove that file config, the rest of your entries show up as they should. 

**- If the current behavior is a bug, please provide the steps to reproduce.**
Add a file entry to a collection without adding the file in your fs.

**- What is the expected behavior?**
The docs are not clear that, in order to add an entry, you must also create the file yourself.  I guess I assumed that it would because if you add an entry to a folder type collection, it adds/commits the file for you.  On top of this, only seeing 'No Entries' under the collection in the CMS and not seeing anything in the browser console is confusing and made it difficult to debug.

**- Please mention your CMS, node.js, and operating system version.**
CMS version 1.0.1
Node version 9.2.1
OS: Mac OS High Sierra

I'm loving the CMS though and If I can provide any help on this, please let me know.

**Comment by tech4him1** [comment]
cc/ @erquhart This looks like a regression in 1.0. If one of the files in a file collection does not actually exist in the repo, no files at all in the collection show up.

**Comment by erquhart** [comment]
I checked, this goes back to 0.4.0 at least. This is definitely important, but I think we should reserve the high priority label for absolute showstoppers.

**Comment by tech4him1** [comment]
I think there a two separate bugs we need to think of this as here:

1. No files in the collection show up if one is missing. This is definitely a high-priority bug.
2. (After that is fixed,) If a file is missing, it is not shown in the collection. Creating the file would be an enhancement, still fairly high priority.

**Comment by Swieckowski** [comment]
I think I'd like to claim this. Thanks!

**Comment by erquhart** [comment]
Awesome!

**Comment by tech4him1** [comment]
I've looked into this a bit, but forgot to update the issue. The applicable code is:
https://github.com/netlify/netlify-cms/blob/756d562c6651b1634143f1f7d47ffc8119fe59bb/src/backends/github/implementation.js#L60-L83

I'm guessing when `readFile` returns a 404, and the Promise is rejected, it causes some rejection further up the call stack that prevents *any* of the files from showing up.

**Comment by tech4him1** [comment]
Just brainstorming, I wonder if a good way to do that would just be to create a blank file immediately? Or we could just resolve to an empty string instead of rejecting (only if a 404). Either way, though, we would need to make sure this only happened during `entriesByFiles` calls, not with `entriesByFolder`.

**Comment by erquhart** [comment]
Agreed, but we should notify the user at least with a toast or something, "Created blank file "_data/entry.json". In the future (like beyond 2.0), I'd like to see this pulled into validation and some kind of prompt like "The files listed below are in your configuration, but don't exist in your repo. Would you like to create them now?". But again, that's futuristic :)

**Comment by tech4him1** [comment]
@erquhart So, I see two ways to fix this, then:

1. Only show files that actually exist in the repo.
  - This would still fix this issue, as it was causing *all* files to disappear.
2. Create a new file if it's in the config.
  - I don't actually think this is really a deviation from our current behavior -- if the file is explicitly specified in the config, I'm assuming that it should be able to be filled out?
  - This could either be done at load time, or save time.

**Comment by erquhart** [comment]
Not a deviation, I guess just a feature. I'd say load time only because the file may have been misspelled, and we want it to be clear what happened.

**Comment by renestalder** [comment]
I don't get it. I just tried to create a file collection. I used the example code from the documentation, but it only shows "No entries". Now, in your issue description you say, the file has to be created be the developer. No mention of that in the documentation. And it's also not clear if a empty file is enough or if it needs to container the data structure with empty values. Anyway, can't get file collections working.

**Comment by erquhart** [comment]
@renestalder an empty file is enough if the format accepts an empty value as valid. e.g., a blank file is valid YAML, but not valid JSON.

If all files in your configuration exist in your repo, and contain valid values for the file type, the collection will work.

**Comment by erquhart** [comment]
Also, docs are now updated with this information, thanks for pointing out the gap.

**Comment by tech4him1** [comment]
This has been partially fixed in #1093 -- if a file fails to load, all other entries in a collection will still work.

**Comment by erezrokah** [comment]
closing as stale. Please comment if still relevant
