### ISSUE TITLE
Improve widget documentation linking and history

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#934]
The widget docs now show each widget on a separate page thanks to the awesome improvements in #866. Things we should consider improving include:

* Using an actual hash for links (currently uses "/#<widget-name>"
* Updating browser history when a new widget docs link is clicked so that back/forward buttons work
* Allowing each widget doc page to be accessed only one way (currently "/#<widget-name>" and "/<widget-name>" both work, the former leading to the widget cloud view, the latter to the standalone generated page

**Comment by tech4him1** [comment]
@erquhart It looks like it is using an actual hash for links, am I misunderstanding? https://deploy-preview-866--netlify-cms-www.netlify.com/docs/widgets/#file
