### ISSUE TITLE
Plugins & Custom Widget Repo

### ISSUE THREAD

**Issue by LaneLourcey** [netlify/netlify-cms#936]
I'm just making my way through the docs but I thought I saw something about plugins, and I know there are custom widgets. Is there any place these are posted or can be shared?

**Comment by tech4him1** [comment]
Duplicate of https://github.com/netlify/netlify-cms/issues/919

**Comment by erquhart** [comment]
@LaneLourcey thanks for pointing this out - we're discussing potential solutions in #919 as Caleb mentioned, but we don't have anything working just yet. Soon!
