### ISSUE TITLE
netlify-cms doesn't look at `base` in `netlify.toml`

### ISSUE THREAD

**Issue by jean** [netlify/netlify-cms#938]
**- Do you want to request a *feature* or report a *bug*?**

Report a bug.

**- What is the current behavior?**

Netlify CMS creates new content in the repo root (e.g. `/pages/new.md`), instead of in _base_ (e.g. `site/pages/new.md`). 

(This can be configured in `config.yml`, but it should not be necessary to configure this in two different places.)

**- If the current behavior is a bug, please provide the steps to reproduce.**

Create a `netlify.toml` file with content like:

```
[build]
  base    = "site"
  publish = "site/output"
  command = "nikola build"
```

Subsequently use the CMS to create pages. Pages are created in sibling folders of `site`, rather than child folders.

**- What is the expected behavior?**

Pages should be created in the _base_ folder designated by `netlify.toml`

**Comment by tech4him1** [comment]
I don't think we are planning on supporting config from the `netlify.toml`, since that is specific to Netlify. The CMS is designed to work separately from any specific hosting provider (it doesn't require Netlify hosting to work).
