### ISSUE TITLE
Image gallery freezes the entire computer

### ISSUE THREAD

**Issue by andreasremdt** [netlify/netlify-cms#939]
**- Do you want to request a *feature* or report a *bug*?**
Report a bug

**- What is the current behavior?**
Opening the image gallery freezes the entire browser and even the computer for seconds. This is extremely present when the image previews are loaded. Once they are loaded, the performance is a bit better but it is still very laggy until one closes the gallery overlay.

Memory and CPU appear to be normal, but it's worth mentioning that the entire operating system freezes for seconds, I can't even click Start.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Open a copy of the Netlify CMS and add images to the gallery. I used a tutorial from Brian Douglas (https://github.com/bdougie/hugo-restaurant-tutorial) with the included sample pictures.

**- What is the expected behavior?**
Not freezing the entire computer while loading the image previews.

**- Please mention your CMS, node.js, and operating system version.**
Netlify CMS 1.0.2
Windows 7 64-Bit
Chrome 63

Let me know if I can do further checks and analyzes on my system. Perhaps this is a bug in the browser?

**Comment by neutyp** [comment]
What images are you uploading? How large are they in filesize or other complexity?

**Comment by andreasremdt** [comment]
They are actually quite different. The majority has dimensions of 960x620 and weight around 60 KB. However, there are two images that have dimensions of 8000x5000 and weight around 14 MB, maybe that's what causing the problem?

**Comment by neutyp** [comment]
Can you try and reproduce with and without those large images? I have a hunch they may be part of the problem

**Comment by andreasremdt** [comment]
Yep, definitely the big photos. After deleting the two pictures with the high resolution, the interface is fluid and responsive. However, if I only upload one photo with such dimensions the interface becomes almost unusable due to lag.

I can share said picture with you, if you'd like.

**Comment by neutyp** [comment]
Okay thanks for confirming! I'm going to close this issue as I've opened one a bit more focused, here: https://github.com/netlify/netlify-cms/issues/946

Can you weigh in on that issue to confirm you're seeing heavy performance issues on your machine?

**Comment by andreasremdt** [comment]
Sure, always!
