### ISSUE TITLE
Indicate collection each entry in the collection search view

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#945]
Currently, searching across collections can yield a list of titles, with no indication of what collection they belong to. The collection should be indicated on each item.

**Comment by solpark** [comment]
I'd like to take this issue! I've figured out how to access the collection name and display it for each found search item, but I'd like to know how and where it should be displayed.

**Comment by tech4him1** [comment]
@solpark Awesome! Feel free to ask questions on our [Gitter channel](https://gitter.im/netlify/NetlifyCMS) if you need any pointers.

@erquhart @neutyp @ziburski Can you outline what design we want on this?

**Comment by erquhart** [comment]
@solpark are you up for proposing a solution that you think works? If so, just submit a pull request! You'll get one or more reviews with suggestions on how things might be improved if necessary. If you'd really like a bit more guidance, though, definitely ask either here or on [Gitter](https://gitter.im/netlify/netlifycms) as @tech4him1 mentioned :)

**Comment by solpark** [comment]
Thank you @erquhart ! Just opened a pull request :)
