### ISSUE TITLE
Whitespace pasting from Markdown loses syntactically relevant details

### ISSUE THREAD

**Issue by fool** [netlify/netlify-cms#953]
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

when copying markdown out of the editor, no whitespace at the beginning of lines is preserved.  When pasting it back into another markdown-expecting location, this causes material changes in the layout.

**- If the current behavior is a bug, please provide the steps to reproduce.**

create a document with this markdown:

```
This is some specially-indented codeblock:
      6 spaces in
     5 spaces in
    4 spaces in
```

...which you can see rendered like this in the previewer as well as the final markdown:

![image](https://user-images.githubusercontent.com/229024/34235246-25832658-e5a5-11e7-80eb-766be5536b66.png)

However, when copy-pasting it out of there, it just looks like this:

```
This is some specially-indented codeblock:
6 spaces in
5 spaces in
4 spaces in
```

this further manifests in places like bullet lists where this:

```
- point one
   - subpoint 1a
```

is collapsed upon copy-pasting into a single-level.

**- What is the expected behavior?**

I'd expect the syntactically important whitespace to be copied and pasted properly. 

**- Please mention your CMS, node.js, and operating system version.**

CMS v1.0.2 as built with node lts/boron on ubuntu linux 14.04

This is related to https://github.com/netlify/netlify-cms/issues/637 but I am not clear that the discussion there (fences vs indentation seems to be the main topic?) covers this use case, which I use pretty extensively and have had to do a lot of copy-pasting lately due to this other situation:  https://github.com/netlify/netlify-cms/issues/941 .  Having to reformat my 200-line bullet list with interspersed intentionally-extra-indented content was not the most pleasant task on my docket ;)

**Comment by erquhart** [comment]
I'm not quite sure how to repro this - copying and pasting from the markdown widget retains whitespace. When you say "copy-pasting it out of there", can you provide exact steps?

**Comment by fool** [comment]
I promise you that it didn't preserve whitespace when I needed it - when I couldn't save several huge documents due to https://github.com/netlify/netlify-cms/issues/941 .  Nor did it work when I filed the bug - I literally copied from the codeblock in my report, into the editor in markdown mode (worked), then copied out of the editor, exited the editor, re-entered the editor, pasted, and the spacing was all gone.

However - today, in chrome on linux and OSX, it works fine.

It was super frustrating but obviously non-actionable since no longer reproducible.

**Comment by erquhart** [comment]
Weird, that's definitely frustrating. Re-open if you hit it again.

**Comment by fool** [comment]
Just re-occurred.  I only seem to see it AFTER I get the API error about being logged out/ "failed to persist entry":  https://github.com/netlify/netlify-cms/issues/941

Here's a sample from the doc.  I've just added the '12345678' to show the # of spaces in this line starting with "Site.find"

![image](https://user-images.githubusercontent.com/229024/35538447-bfd1ff5a-0502-11e8-9118-7de80868d7c2.png)

I can select the spaces, but when pasting them, nothing happens.  When pasting the line, I get this:

![image](https://user-images.githubusercontent.com/229024/35538476-e2b867ca-0502-11e8-995d-4af433e66f85.png)

literally no whitespace besides single spaces is preserved:

- there are several empty lines (which ARE syntactically important in breaking lines in the output)
- there is a space in front of the minus, which is NOT syntactically important.
- there is NO SPACE in front of the indented code block, which makes it not a code block upon reinsertion.

**Comment by erquhart** [comment]
Only after timeout eh? Did you see anything console errors either time when this occurred?

**Comment by fool** [comment]
Don't recall but will go open a window to repro for you and check into that
:)

**Comment by fool** [comment]
Finally got this reproduced.  When I attempt to save in a window where my authentication has timed out, this is the error message that flashes briefly (~10s) near the top of the editor:

![image](https://user-images.githubusercontent.com/229024/36312829-931fde4c-12e4-11e8-97a1-1feb89d37588.png)

I then copy and paste what I've been working on since the CMS is effectively frozen at this point - hitting the save button has no further effect.  The content loses its spacing as mentioned above when pasting into an editor to repaste back into the CMS

In the console, I saw these errors:

![image](https://user-images.githubusercontent.com/229024/36312946-f3a81dc4-12e4-11e8-8069-edfd99eaee84.png)

expanding the first one got me a huge list of variables which I'll need two screenshots to show:

![image](https://user-images.githubusercontent.com/229024/36312998-25bfedb4-12e5-11e8-8a38-15dfa7e10ed6.png)

![image](https://user-images.githubusercontent.com/229024/36313019-334ef9ac-12e5-11e8-8260-384b63c88641.png)

The second one seemed to be just an identity issue so I didn't expand it.

@erquhart  if you want to reproduce, it occurs to me you could follow these steps.  I wasn't suggesting them initially, since  they'd be impossible for anyone else on the CMS team except @Benaiah  to do - since it requires a login to a Netlify-internal site.

1. (you've already been added as an Identity user with appropriate CMS permissions to the site)
2. login at https://internal-docs.netlify.com/admin/#
3. start editing a new document with some syntactical spacing in it
4. open browser console
5. leave window open overnight
6. try to save
7. try to paste that content out into your editor

**Comment by fool** [comment]
So - I ran into this again today as I do every time I spend a substantial amount of time editing a document, and discovered something new:

the content pastes as expected, with whitespace back into the CMS directly.  It's just not saved in the cutbuffer (on my mac) as ascii spacing - but the CMS editor gets it right.

Of course this is a dangerous game - between copying, reloading the CMS, relogging in, renavigating back to the document in question if you get distracted (as I often do), and copy something else - you've lost that content entirely rather than just the spacing.  

However - I think this issue is now better summarized as "copying from CMS does not use plaintext whitespace" than "whitespace is entirely lost".

As someone who uses a non-richtext (vim) editor, this is extremely suboptimal for me - but it is no longer a mystery or total misbehavior if you use editors that understand whatever kind of styling is copied into the cutbuffer (e.g. CKeditor or TinyMCE according to this related thread:  https://superuser.com/questions/547773/how-do-i-copy-paste-website-content-with-formatting)

**Comment by tech4him1** [comment]
@fool If the token has not timed out, does the copying work with plaintext whitespace, or is it the same?

**Comment by fool** [comment]
@tech4him1 - behavior is unrelated to token status: same behavior with valid token.  

I suspect this is now considered notabug?

If you think it's still worth having an open issue for, I'll restructure the report and title, LMK!

**Comment by tech4him1** [comment]
I'd like to see what @erquhart thinks, since he wrote most of editor so far.

**Comment by erquhart** [comment]
@fool this is worth keeping open, the whole cutting and pasting story is still rough.

**Comment by mifi** [comment]
Just had the same issue

**Comment by Gashanas** [comment]
Hey, any updates on this? I am still facing the issue. I noticed that it happens with links and other modified texts like bolded or formatted ones. When I am pasting post from other website with links or bold text, it loses spacing, so I have to double check each pasted text before publishing.
<img width="896" alt="Screenshot 2020-04-08 at 14 16 00" src="https://user-images.githubusercontent.com/25568040/78778303-bf0aaf00-79a3-11ea-8353-9337b4dfd838.png">

**Comment by erezrokah** [comment]
I believe this was fixed in https://github.com/netlify/netlify-cms/pull/3864 (see https://github.com/netlify/netlify-cms/issues/3727).
Please comment if still happens
