### ISSUE TITLE
Image alt text in markdown widget defaults to null

### ISSUE THREAD

**Issue by erquhart** [netlify/netlify-cms#956]
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

When an image is inserted in the markdown editor (rich text mode), the alt text is persisted as `null` if left blank.

**- If the current behavior is a bug, please provide the steps to reproduce.**

* create a new entry that uses the markdown widget
* insert an image before making any other changes in the widget
* switch to markdown view
* note that alt value is "null" as a string

**- What is the expected behavior?**

* alt value should be an empty string

**- Please mention your CMS, node.js, and operating system version.**

CMS 1.0.3

**Comment by erquhart** [comment]
From @tech4him1 in [#895](https://github.com/netlify/netlify-cms/issues/895#issuecomment-350361798):

> Looking at Redux, on initial load `entryDraft.entry.data.body` is set to `null` instead of an empty string. Only when it is `null` does the image widget crash.

**Comment by papandreou** [comment]
This still happens in 1.8.1 after https://github.com/netlify/netlify-cms/pull/1126 was merged.

**Comment by erquhart** [comment]
Confirmed, thanks for pointing that out.
