### ISSUE TITLE
Be able to remove images added to widgets

### ISSUE THREAD

**Issue by mirkea** [netlify/netlify-cms#960]
**- Do you want to request a *feature* or report a *bug*?**
Request a feature

**- What is the current behavior?**
- add an image into an image image widget
- no way to remove it

**- What is the expected behavior?**
- I should be able to have no image in there

**- Please mention your CMS, node.js, and operating system version.**
Netlify CMS version 0.4.6
WIndows 10 64biy
node.js v8.4.0

**Comment by tech4him1** [comment]
The latest CMS version is 1.0.3 and this feature is supported, can you update?
