### ISSUE TITLE
Re-implement React Hot Loader

### ISSUE THREAD

**Issue by tech4him1** [netlify/netlify-cms#966]
React Hot Loader (and HMR in general) was removed in v1.0 since it was not working correctly. There were also some bugs with our transpiler that should both be fixed in RHL v4 (https://github.com/netlify/netlify-cms/pull/765#issuecomment-346502229). We should try to re-add this once it gets stable and working.

**Comment by tech4him1** [comment]
https://github.com/gaearon/react-hot-loader/issues/703 explains the basic changes made to allow v4 work better.

**Comment by theKashey** [comment]
React-hot-loader v4.0.0-beta16(aka "next") is super stable and just working.

**Comment by erquhart** [comment]
Awesome, thanks for the heads up @theKashey

**Comment by tech4him1** [comment]
> [*Caleb @tech4him1 Mar 31 09:24*](https://gitter.im/gaearon/react-hot-loader?at=5abfa847bb1018b37a4582db)
> @theKashey I'm getting back around to implementing RHL v4. Should the hot(module) wrapper be around any Redux Provider's, or just around the root App itself? Thank you!

> [*Anton @theKashey Mar 31 16:13*](https://gitter.im/gaearon/react-hot-loader?at=5ac00803c4d0ae8007212261)
> Should be on top paths you gonna change. Root App is "on top" enought, @tech4him1, but dont use hot and react-dom/mount in one file.
