### ISSUE TITLE
netlify bitbucket and hugo admin not working. 

### ISSUE THREAD

**Issue by thisisspeedy** [netlify/netlify-cms#967]
**- Do you want to request a *feature* or report a *bug*?**

**- What is the current behavior?**

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Please mention your CMS, node.js, and operating system version.**

Windows 10. Node 9.30, Hugo 0.31.1, Netlify CMS,
Trying to set up admin path authentication via bitbucket per video https://youtu.be/NSts93C9UeE?t=20m49s. 

Error "There's been an error - please report it!".

**Comment by tech4him1** [comment]
Thanks for checking out Netlify CMS! The CMS does not support BitBucket as a backend yet, it's a work in progress: https://github.com/netlify/netlify-cms/pull/525.
