### ISSUE TITLE
Switch to react-router-redux

### ISSUE THREAD

**Issue by okonet** [netlify/netlify-cms#98]
We should eliminate direct manipulation of `history` in favor of using redux action creators.

See https://github.com/reactjs/react-router-redux#what-if-i-want-to-issue-navigation-events-via-redux-actions

**Comment by cassiozen** [comment]
I think React Router Redux is actually pretty bad... We should investigate migrating to React Router 4 and using ControlledRouter.

**Comment by okonet** [comment]
I didn't look into it yet but I agree it's worth looking at.
