### ISSUE TITLE
Support custom delimiters for frontmatter.

### ISSUE THREAD

**Issue by tech4him1** [netlify/netlify-cms#980]
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
After https://github.com/netlify/netlify-cms/issues/563, we now support frontmatter in multiple formats, but we only allow it to be parsed using the default delimiters. 

**- What is the expected behavior?**
It would be nice to allow the user to specify their own delimiters for parsing frontmatter out of an entry file. @erquhart [suggested](https://github.com/netlify/netlify-cms/issues/563#issuecomment-352533855) using `frontmatter_delimiter: "~~~"`.

**Comment by erquhart** [comment]
Note: could also accept an array of opening/closing delims, as gray-matter does: `['~~~', '~~~']`. No, I cannot think of a use case for this lol. But I'm sure someone can.

**Comment by Swieckowski** [comment]
I'd like to take this issue, it might take a bit since I'm completely green to the codebase.

**Comment by Swieckowski** [comment]
I'd like to take this, but it might take me a bit since I'm green to the codebase.
