### ISSUE TITLE
SVGs do not appear properly in Microsoft Edge

### ISSUE THREAD

**Issue by tech4him1** [netlify/netlify-cms#983]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
SVGs run off the edge of the media library view in Microsoft Edge. They seem to appear properly in FireFox and Chrome.
Broken:
![capture](https://user-images.githubusercontent.com/20345941/34580638-ea53612c-f14a-11e7-8b84-f835c5765894.JPG)
Correct:
![capture2](https://user-images.githubusercontent.com/20345941/34580766-59e3ad8a-f14b-11e7-87b3-5d0d42784156.JPG)

**Comment by erezrokah** [comment]
Closing as stale. Please comment if still relevant
