### ISSUE TITLE
Formatting preservation when pasting content to rich editor

### ISSUE THREAD

**Issue by dmgawel** [netlify/netlify-cms#991]
**- Do you want to request a *feature* or report a *bug*?**

It depends on the point of view :P But it's regression so I'd say: bug.

**- What is the current behavior?**

Since version 0.7 of CMS pasting formatted text from Dropbox Paper / Google Docs / Word / etc. to rich text editor ends up with clear, non-formatted text.

**- If the current behavior is a bug, please provide the steps to reproduce.**

Copy formatted text (headings, bold, italics, bullet points) from any editor mentioned above to Netlify CMS editor in rich mode.

**- What is the expected behavior?**

Formatting supported by markdown should be preserved (skipping any custom formatting - colors, fonts, etc.).

**- Please mention your CMS, node.js, and operating system version.**

Last known version of CMS that kept some formatting: 0.6.0

**Comment by erquhart** [comment]
Yeah we definitely need to up our game there. You're right about it being a regression - one of the advantages of the old ProseMirror editor was better built in support for weird paste formats - but I'm going to call this an enhancement because we switched cores from ProseMirror to Slate, and Slate doesn't come with this out of the box.

**Comment by erezrokah** [comment]
Closing as stale. Please re-open if having issues when pasting rich text (see https://github.com/netlify/netlify-cms/issues/3727 for example)

**Comment by inwardmovement** [comment]
Pasting content from Google Docs still clear formats, for example using [cms-demo.netlify.com](https://cms-demo.netlify.com/):

Rich text copied from GDoc:
> **This is bold** and _this is italic_.

When pasted into NetlifyCMS rich text editor becomes:
> This is bold and this is italic.

Will this be solved soon?

**Comment by erezrokah** [comment]
Hi @inwardmovement, can you please open a new issue for this?
